<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities5 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 2876, 'id_state' => 13, 'name' => ' Bação'],
                ['id_city' => 2877, 'id_state' => 13, 'name' => ' Baependi'],
                ['id_city' => 2878, 'id_state' => 13, 'name' => ' Baguari'],
                ['id_city' => 2879, 'id_state' => 13, 'name' => ' Baiões'],
                ['id_city' => 2880, 'id_state' => 13, 'name' => ' Baixa'],
                ['id_city' => 2881, 'id_state' => 13, 'name' => ' Balbinópolis'],
                ['id_city' => 2882, 'id_state' => 13, 'name' => ' Baldim'],
                ['id_city' => 2883, 'id_state' => 13, 'name' => ' Bambuí'],
                ['id_city' => 2884, 'id_state' => 13, 'name' => ' Bandeira'],
                ['id_city' => 2885, 'id_state' => 13, 'name' => ' Bandeira do Sul'],
                ['id_city' => 2886, 'id_state' => 13, 'name' => ' Bandeirantes'],
                ['id_city' => 2887, 'id_state' => 13, 'name' => ' Barão de Cocais'],
                ['id_city' => 2888, 'id_state' => 13, 'name' => ' Barão de Monte Alto'],
                ['id_city' => 2889, 'id_state' => 13, 'name' => ' Barbacena'],
                ['id_city' => 2890, 'id_state' => 13, 'name' => ' Barra Alegre'],
                ['id_city' => 2891, 'id_state' => 13, 'name' => ' Barra da Figueira'],
                ['id_city' => 2892, 'id_state' => 13, 'name' => ' Barra do Ariranha'],
                ['id_city' => 2893, 'id_state' => 13, 'name' => ' Barra do Cuieté'],
                ['id_city' => 2894, 'id_state' => 13, 'name' => ' Barra Feliz'],
                ['id_city' => 2895, 'id_state' => 13, 'name' => ' Barra Longa'],
                ['id_city' => 2896, 'id_state' => 13, 'name' => ' Barranco Alto'],
                ['id_city' => 2897, 'id_state' => 13, 'name' => ' Barreiro'],
                ['id_city' => 2898, 'id_state' => 13, 'name' => ' Barreiro Branco'],
                ['id_city' => 2899, 'id_state' => 13, 'name' => ' Barreiro da Raiz'],
                ['id_city' => 2900, 'id_state' => 13, 'name' => ' Barreiro do Rio Verde'],
                ['id_city' => 2901, 'id_state' => 13, 'name' => ' Barretos de Alvinópolis'],
                ['id_city' => 2902, 'id_state' => 13, 'name' => ' Barrocão'],
                ['id_city' => 2903, 'id_state' => 13, 'name' => ' Barroso'],
                ['id_city' => 2904, 'id_state' => 13, 'name' => ' Baú'],
                ['id_city' => 2905, 'id_state' => 13, 'name' => ' Bela Vista de Minas'],
                ['id_city' => 2906, 'id_state' => 13, 'name' => ' Belisário'],
                ['id_city' => 2907, 'id_state' => 13, 'name' => ' Belmiro Braga'],
                ['id_city' => 2908, 'id_state' => 13, 'name' => ' Belo Horizonte'],
                ['id_city' => 2909, 'id_state' => 13, 'name' => ' Belo Oriente'],
                ['id_city' => 2910, 'id_state' => 13, 'name' => ' Belo Oriente'],
                ['id_city' => 2911, 'id_state' => 13, 'name' => ' Belo Vale'],
                ['id_city' => 2912, 'id_state' => 13, 'name' => ' Bentópolis de Minas'],
                ['id_city' => 2913, 'id_state' => 13, 'name' => ' Berilo'],
                ['id_city' => 2914, 'id_state' => 13, 'name' => ' Berizal'],
                ['id_city' => 2915, 'id_state' => 13, 'name' => ' Bertópolis'],
                ['id_city' => 2916, 'id_state' => 13, 'name' => ' Betim'],
                ['id_city' => 2917, 'id_state' => 13, 'name' => ' Bias Fortes'],
                ['id_city' => 2918, 'id_state' => 13, 'name' => ' Bicas'],
                ['id_city' => 2919, 'id_state' => 13, 'name' => ' Bicuíba'],
                ['id_city' => 2920, 'id_state' => 13, 'name' => ' Biquinhas'],
                ['id_city' => 2921, 'id_state' => 13, 'name' => ' Bituri'],
                ['id_city' => 2922, 'id_state' => 13, 'name' => ' Boa Esperança'],
                ['id_city' => 2923, 'id_state' => 13, 'name' => ' Boa Família'],
                ['id_city' => 2924, 'id_state' => 13, 'name' => ' Boa União de Itabirinha'],
                ['id_city' => 2925, 'id_state' => 13, 'name' => ' Boa Vista de Minas'],
                ['id_city' => 2926, 'id_state' => 13, 'name' => ' Bocaina de Minas'],
                ['id_city' => 2927, 'id_state' => 13, 'name' => ' Bocaiúva'],
                ['id_city' => 2928, 'id_state' => 13, 'name' => ' Bom Despacho'],
                ['id_city' => 2929, 'id_state' => 13, 'name' => ' Bom Jardim de Minas'],
                ['id_city' => 2930, 'id_state' => 13, 'name' => ' Bom Jesus da Cachoeira'],
                ['id_city' => 2931, 'id_state' => 13, 'name' => ' Bom Jesus da Penha'],
                ['id_city' => 2932, 'id_state' => 13, 'name' => ' Bom Jesus de Cardosos'],
                ['id_city' => 2933, 'id_state' => 13, 'name' => ' Bom Jesus do Amparo'],
                ['id_city' => 2934, 'id_state' => 13, 'name' => ' Bom Jesus do Divino'],
                ['id_city' => 2935, 'id_state' => 13, 'name' => ' Bom Jesus do Galho'],
                ['id_city' => 2936, 'id_state' => 13, 'name' => ' Bom Jesus do Madeira'],
                ['id_city' => 2937, 'id_state' => 13, 'name' => ' Bom Pastor'],
                ['id_city' => 2938, 'id_state' => 13, 'name' => ' Bom Repouso'],
                ['id_city' => 2939, 'id_state' => 13, 'name' => ' Bom Retiro'],
                ['id_city' => 2940, 'id_state' => 13, 'name' => ' Bom Sucesso'],
                ['id_city' => 2941, 'id_state' => 13, 'name' => ' Bom Sucesso de Patos'],
                ['id_city' => 2942, 'id_state' => 13, 'name' => ' Bonança'],
                ['id_city' => 2943, 'id_state' => 13, 'name' => ' Bonfim'],
                ['id_city' => 2944, 'id_state' => 13, 'name' => ' Bonfinópolis de Minas'],
                ['id_city' => 2945, 'id_state' => 13, 'name' => ' Bonito de Minas'],
                ['id_city' => 2946, 'id_state' => 13, 'name' => ' Borba Gato'],
                ['id_city' => 2947, 'id_state' => 13, 'name' => ' Borda da Mata'],
                ['id_city' => 2948, 'id_state' => 13, 'name' => ' Botelhos'],
                ['id_city' => 2949, 'id_state' => 13, 'name' => ' Botumirim'],
                ['id_city' => 2950, 'id_state' => 13, 'name' => ' Brás Pires'],
                ['id_city' => 2951, 'id_state' => 13, 'name' => ' Brasilândia de Minas'],
                ['id_city' => 2952, 'id_state' => 13, 'name' => ' Brasília de Minas'],
                ['id_city' => 2953, 'id_state' => 13, 'name' => ' Brasópolis'],
                ['id_city' => 2954, 'id_state' => 13, 'name' => ' Braúnas'],
                ['id_city' => 2955, 'id_state' => 13, 'name' => ' Brejaúba'],
                ['id_city' => 2956, 'id_state' => 13, 'name' => ' Brejaubinha'],
                ['id_city' => 2957, 'id_state' => 13, 'name' => ' Brejo Bonito'],
                ['id_city' => 2958, 'id_state' => 13, 'name' => ' Brejo do Amparo'],
                ['id_city' => 2959, 'id_state' => 13, 'name' => ' Brumadinho'],
                ['id_city' => 2960, 'id_state' => 13, 'name' => ' Brumal'],
                ['id_city' => 2961, 'id_state' => 13, 'name' => ' Buarque de Macedo'],
                ['id_city' => 2962, 'id_state' => 13, 'name' => ' Bueno'],
                ['id_city' => 2963, 'id_state' => 13, 'name' => ' Bueno Brandão'],
                ['id_city' => 2964, 'id_state' => 13, 'name' => ' Buenópolis'],
                ['id_city' => 2965, 'id_state' => 13, 'name' => ' Bugre'],
                ['id_city' => 2966, 'id_state' => 13, 'name' => ' Buritis'],
                ['id_city' => 2967, 'id_state' => 13, 'name' => ' Buritizeiro'],
                ['id_city' => 2968, 'id_state' => 13, 'name' => ' Caatinga'],
                ['id_city' => 2969, 'id_state' => 13, 'name' => ' Cabeceira Grande'],
                ['id_city' => 2970, 'id_state' => 13, 'name' => ' Cabo Verde'],
                ['id_city' => 2971, 'id_state' => 13, 'name' => ' Caburu'],
                ['id_city' => 2972, 'id_state' => 13, 'name' => ' Caçaratiba'],
                ['id_city' => 2973, 'id_state' => 13, 'name' => ' Caçarema'],
                ['id_city' => 2974, 'id_state' => 13, 'name' => ' Cachoeira Alegre'],
                ['id_city' => 2975, 'id_state' => 13, 'name' => ' Cachoeira da Prata'],
                ['id_city' => 2976, 'id_state' => 13, 'name' => ' Cachoeira de Minas'],
                ['id_city' => 2977, 'id_state' => 13, 'name' => ' Cachoeira de Pajeú'],
                ['id_city' => 2978, 'id_state' => 13, 'name' => ' Cachoeira de Santa Cruz'],
                ['id_city' => 2979, 'id_state' => 13, 'name' => ' Cachoeira do Brumado'],
                ['id_city' => 2980, 'id_state' => 13, 'name' => ' Cachoeira do Campo'],
                ['id_city' => 2981, 'id_state' => 13, 'name' => ' Cachoeira do Manteiga'],
                ['id_city' => 2982, 'id_state' => 13, 'name' => ' Cachoeira do Vale'],
                ['id_city' => 2983, 'id_state' => 13, 'name' => ' Cachoeira dos Antunes'],
                ['id_city' => 2984, 'id_state' => 13, 'name' => ' Cachoeira Dourada'],
                ['id_city' => 2985, 'id_state' => 13, 'name' => ' Cachoeirinha'],
                ['id_city' => 2986, 'id_state' => 13, 'name' => ' Caetano Lopes'],
                ['id_city' => 2987, 'id_state' => 13, 'name' => ' Caetanópolis'],
                ['id_city' => 2988, 'id_state' => 13, 'name' => ' Caeté'],
                ['id_city' => 2989, 'id_state' => 13, 'name' => ' Caiana'],
                ['id_city' => 2990, 'id_state' => 13, 'name' => ' Caiapó'],
                ['id_city' => 2991, 'id_state' => 13, 'name' => ' Cajuri'],
                ['id_city' => 2992, 'id_state' => 13, 'name' => ' Caldas'],
                ['id_city' => 2993, 'id_state' => 13, 'name' => ' Calixto'],
                ['id_city' => 2994, 'id_state' => 13, 'name' => ' Camacho'],
                ['id_city' => 2995, 'id_state' => 13, 'name' => ' Camanducaia'],
                ['id_city' => 2996, 'id_state' => 13, 'name' => ' Camargos'],
                ['id_city' => 2997, 'id_state' => 13, 'name' => ' Cambuí'],
                ['id_city' => 2998, 'id_state' => 13, 'name' => ' Cambuquira'],
                ['id_city' => 2999, 'id_state' => 13, 'name' => ' Campanário'],
                ['id_city' => 3000, 'id_state' => 13, 'name' => ' Campanha'],
                ['id_city' => 3001, 'id_state' => 13, 'name' => ' Campestre'],
                ['id_city' => 3002, 'id_state' => 13, 'name' => ' Campestrinho'],
                ['id_city' => 3003, 'id_state' => 13, 'name' => ' Campina Verde'],
                ['id_city' => 3004, 'id_state' => 13, 'name' => ' Campo Alegre de Minas'],
                ['id_city' => 3005, 'id_state' => 13, 'name' => ' Campo Azul'],
                ['id_city' => 3006, 'id_state' => 13, 'name' => ' Campo Belo'],
                ['id_city' => 3007, 'id_state' => 13, 'name' => ' Campo do Meio'],
                ['id_city' => 3008, 'id_state' => 13, 'name' => ' Campo Florido'],
                ['id_city' => 3009, 'id_state' => 13, 'name' => ' Campo Redondo'],
                ['id_city' => 3010, 'id_state' => 13, 'name' => ' Campolide'],
                ['id_city' => 3011, 'id_state' => 13, 'name' => ' Campos Altos'],
                ['id_city' => 3012, 'id_state' => 13, 'name' => ' Campos Gerais'],
                ['id_city' => 3013, 'id_state' => 13, 'name' => ' Cana Verde'],
                ['id_city' => 3014, 'id_state' => 13, 'name' => ' Canaã'],
                ['id_city' => 3015, 'id_state' => 13, 'name' => ' Canabrava'],
                ['id_city' => 3016, 'id_state' => 13, 'name' => ' Canápolis'],
                ['id_city' => 3017, 'id_state' => 13, 'name' => ' Canastrão'],
                ['id_city' => 3018, 'id_state' => 13, 'name' => ' Candeias'],
                ['id_city' => 3019, 'id_state' => 13, 'name' => ' Canoeiros'],
                ['id_city' => 3020, 'id_state' => 13, 'name' => ' Cantagalo'],
                ['id_city' => 3021, 'id_state' => 13, 'name' => ' Caparaó'],
                ['id_city' => 3022, 'id_state' => 13, 'name' => ' Capela Nova'],
                ['id_city' => 3023, 'id_state' => 13, 'name' => ' Capelinha'],
                ['id_city' => 3024, 'id_state' => 13, 'name' => ' Capetinga'],
                ['id_city' => 3025, 'id_state' => 13, 'name' => ' Capim Branco'],
                ['id_city' => 3026, 'id_state' => 13, 'name' => ' Capinópolis'],
                ['id_city' => 3027, 'id_state' => 13, 'name' => ' Capitânia'],
                ['id_city' => 3028, 'id_state' => 13, 'name' => ' Capitão Andrade'],
                ['id_city' => 3029, 'id_state' => 13, 'name' => ' Capitão Enéas'],
                ['id_city' => 3030, 'id_state' => 13, 'name' => ' Capitólio'],
                ['id_city' => 3031, 'id_state' => 13, 'name' => ' Caputira'],
                ['id_city' => 3032, 'id_state' => 13, 'name' => ' Caraí'],
                ['id_city' => 3033, 'id_state' => 13, 'name' => ' Caranaíba'],
                ['id_city' => 3034, 'id_state' => 13, 'name' => ' Carandaí'],
                ['id_city' => 3035, 'id_state' => 13, 'name' => ' Carangola'],
                ['id_city' => 3036, 'id_state' => 13, 'name' => ' Caratinga'],
                ['id_city' => 3037, 'id_state' => 13, 'name' => ' Carbonita'],
                ['id_city' => 3038, 'id_state' => 13, 'name' => ' Serra do Cipó'],
                ['id_city' => 3039, 'id_state' => 13, 'name' => ' Careaçu'],
                ['id_city' => 3040, 'id_state' => 13, 'name' => ' Carioca'],
                ['id_city' => 3041, 'id_state' => 13, 'name' => ' Carlos Alves'],
                ['id_city' => 3042, 'id_state' => 13, 'name' => ' Carlos Chagas'],
                ['id_city' => 3043, 'id_state' => 13, 'name' => ' Carmésia'],
                ['id_city' => 3044, 'id_state' => 13, 'name' => ' Carmo da Cachoeira'],
                ['id_city' => 3045, 'id_state' => 13, 'name' => ' Carmo da Mata'],
                ['id_city' => 3046, 'id_state' => 13, 'name' => ' Carmo de Minas'],
                ['id_city' => 3047, 'id_state' => 13, 'name' => ' Carmo do Cajuru'],
                ['id_city' => 3048, 'id_state' => 13, 'name' => ' Carmo do Paranaíba'],
                ['id_city' => 3049, 'id_state' => 13, 'name' => ' Carmo do Rio Claro'],
                ['id_city' => 3050, 'id_state' => 13, 'name' => ' Carmópolis de Minas'],
                ['id_city' => 3051, 'id_state' => 13, 'name' => ' Carneirinho'],
                ['id_city' => 3052, 'id_state' => 13, 'name' => ' Carrancas'],
                ['id_city' => 3053, 'id_state' => 13, 'name' => ' Carvalho de Brito'],
                ['id_city' => 3054, 'id_state' => 13, 'name' => ' Carvalhópolis'],
                ['id_city' => 3055, 'id_state' => 13, 'name' => ' Carvalhos'],
                ['id_city' => 3056, 'id_state' => 13, 'name' => ' Casa Grande'],
                ['id_city' => 3057, 'id_state' => 13, 'name' => ' Cascalho Rico'],
                ['id_city' => 3058, 'id_state' => 13, 'name' => ' Cássia'],
                ['id_city' => 3059, 'id_state' => 13, 'name' => ' Cataguarino'],
                ['id_city' => 3060, 'id_state' => 13, 'name' => ' Cataguases'],
                ['id_city' => 3061, 'id_state' => 13, 'name' => ' Catajás'],
                ['id_city' => 3062, 'id_state' => 13, 'name' => ' Catas Altas'],
                ['id_city' => 3063, 'id_state' => 13, 'name' => ' Catas Altas da Noruega'],
                ['id_city' => 3064, 'id_state' => 13, 'name' => ' Catiara'],
                ['id_city' => 3065, 'id_state' => 13, 'name' => ' Catuji'],
                ['id_city' => 3066, 'id_state' => 13, 'name' => ' Catuné'],
                ['id_city' => 3067, 'id_state' => 13, 'name' => ' Catuni'],
                ['id_city' => 3068, 'id_state' => 13, 'name' => ' Catuti'],
                ['id_city' => 3069, 'id_state' => 13, 'name' => ' Caxambu'],
                ['id_city' => 3070, 'id_state' => 13, 'name' => ' Cedro do Abaeté'],
                ['id_city' => 3071, 'id_state' => 13, 'name' => ' Centenário'],
                ['id_city' => 3072, 'id_state' => 13, 'name' => ' Central de Minas'],
                ['id_city' => 3073, 'id_state' => 13, 'name' => ' Central de Santa Helena'],
                ['id_city' => 3074, 'id_state' => 13, 'name' => ' Centralina'],
                ['id_city' => 3075, 'id_state' => 13, 'name' => ' Cervo'],
                ['id_city' => 3076, 'id_state' => 13, 'name' => ' Chácara'],
                ['id_city' => 3077, 'id_state' => 13, 'name' => ' Chalé'],
                ['id_city' => 3078, 'id_state' => 13, 'name' => ' Chapada de Minas'],
                ['id_city' => 3079, 'id_state' => 13, 'name' => ' Chapada do Norte'],
                ['id_city' => 3080, 'id_state' => 13, 'name' => ' Chapada Gaúcha'],
                ['id_city' => 3081, 'id_state' => 13, 'name' => ' Chaveslândia'],
                ['id_city' => 3082, 'id_state' => 13, 'name' => ' Chiador'],
                ['id_city' => 3083, 'id_state' => 13, 'name' => ' Chonim'],
                ['id_city' => 3084, 'id_state' => 13, 'name' => ' Chumbo'],
                ['id_city' => 3085, 'id_state' => 13, 'name' => ' Cipotânea'],
                ['id_city' => 3086, 'id_state' => 13, 'name' => ' Cisneiros'],
                ['id_city' => 3087, 'id_state' => 13, 'name' => ' Claraval'],
                ['id_city' => 3088, 'id_state' => 13, 'name' => ' Claro de Minas'],
                ['id_city' => 3089, 'id_state' => 13, 'name' => ' Claro dos Poções'],
                ['id_city' => 3090, 'id_state' => 13, 'name' => ' Cláudio'],
                ['id_city' => 3091, 'id_state' => 13, 'name' => ' Cláudio Manuel'],
                ['id_city' => 3092, 'id_state' => 13, 'name' => ' Cocais'],
                ['id_city' => 3093, 'id_state' => 13, 'name' => ' Coco'],
                ['id_city' => 3094, 'id_state' => 13, 'name' => ' Coimbra'],
                ['id_city' => 3095, 'id_state' => 13, 'name' => ' Coluna'],
                ['id_city' => 3096, 'id_state' => 13, 'name' => ' Comendador Gomes'],
                ['id_city' => 3097, 'id_state' => 13, 'name' => ' Comercinho'],
                ['id_city' => 3098, 'id_state' => 13, 'name' => ' Conceição da Aparecida'],
                ['id_city' => 3099, 'id_state' => 13, 'name' => ' Conceição da Barra de Minas'],
                ['id_city' => 3100, 'id_state' => 13, 'name' => ' Conceição da Boa Vista'],
                ['id_city' => 3101, 'id_state' => 13, 'name' => ' Conceição da Brejaúba'],
                ['id_city' => 3102, 'id_state' => 13, 'name' => ' Conceição da Ibitipoca'],
                ['id_city' => 3103, 'id_state' => 13, 'name' => ' Conceição das Alagoas'],
                ['id_city' => 3104, 'id_state' => 13, 'name' => ' Conceição das Pedras'],
                ['id_city' => 3105, 'id_state' => 13, 'name' => ' Conceição de Ipanema'],
                ['id_city' => 3106, 'id_state' => 13, 'name' => ' Conceição de Itaguá'],
                ['id_city' => 3107, 'id_state' => 13, 'name' => ' Conceição de Minas'],
                ['id_city' => 3108, 'id_state' => 13, 'name' => ' Conceição de Piracicaba'],
                ['id_city' => 3109, 'id_state' => 13, 'name' => ' Conceição de Tronqueiras'],
                ['id_city' => 3110, 'id_state' => 13, 'name' => ' Conceição do Capim'],
                ['id_city' => 3111, 'id_state' => 13, 'name' => ' Conceição do Formoso'],
                ['id_city' => 3112, 'id_state' => 13, 'name' => ' Conceição do Mato Dentro'],
                ['id_city' => 3113, 'id_state' => 13, 'name' => ' Conceição do Pará'],
                ['id_city' => 3114, 'id_state' => 13, 'name' => ' Conceição do Rio Acima'],
                ['id_city' => 3115, 'id_state' => 13, 'name' => ' Conceição do Rio Verde'],
                ['id_city' => 3116, 'id_state' => 13, 'name' => ' Conceição dos Ouros'],
                ['id_city' => 3117, 'id_state' => 13, 'name' => ' Concórdia de Mucuri'],
                ['id_city' => 3118, 'id_state' => 13, 'name' => ' Condado do Norte'],
                ['id_city' => 3119, 'id_state' => 13, 'name' => ' Cônego João Pio'],
                ['id_city' => 3120, 'id_state' => 13, 'name' => ' Cônego Marinho'],
                ['id_city' => 3121, 'id_state' => 13, 'name' => ' Confins'],
                ['id_city' => 3122, 'id_state' => 13, 'name' => ' Congonhal'],
                ['id_city' => 3123, 'id_state' => 13, 'name' => ' Congonhas'],
                ['id_city' => 3124, 'id_state' => 13, 'name' => ' Congonhas do Norte'],
                ['id_city' => 3125, 'id_state' => 13, 'name' => ' Conquista'],
                ['id_city' => 3126, 'id_state' => 13, 'name' => ' Conselheiro Lafaiete'],
                ['id_city' => 3127, 'id_state' => 13, 'name' => ' Conselheiro Mata'],
                ['id_city' => 3128, 'id_state' => 13, 'name' => ' Conselheiro Pena'],
                ['id_city' => 3129, 'id_state' => 13, 'name' => ' Consolação'],
                ['id_city' => 3130, 'id_state' => 13, 'name' => ' Contagem'],
                ['id_city' => 3131, 'id_state' => 13, 'name' => ' Contrato'],
                ['id_city' => 3132, 'id_state' => 13, 'name' => ' Contria'],
                ['id_city' => 3133, 'id_state' => 13, 'name' => ' Coqueiral'],
                ['id_city' => 3134, 'id_state' => 13, 'name' => ' Coração de Jesus'],
                ['id_city' => 3135, 'id_state' => 13, 'name' => ' Cordisburgo'],
                ['id_city' => 3136, 'id_state' => 13, 'name' => ' Cordislândia'],
                ['id_city' => 3137, 'id_state' => 13, 'name' => ' Corinto'],
                ['id_city' => 3138, 'id_state' => 13, 'name' => ' Coroaci'],
                ['id_city' => 3139, 'id_state' => 13, 'name' => ' Coromandel'],
                ['id_city' => 3140, 'id_state' => 13, 'name' => ' Coronel Fabriciano'],
                ['id_city' => 3141, 'id_state' => 13, 'name' => ' Coronel Murta'],
                ['id_city' => 3142, 'id_state' => 13, 'name' => ' Coronel Pacheco'],
                ['id_city' => 3143, 'id_state' => 13, 'name' => ' Coronel Xavier Chaves'],
                ['id_city' => 3144, 'id_state' => 13, 'name' => ' Córrego Danta'],
                ['id_city' => 3145, 'id_state' => 13, 'name' => ' Córrego do Barro'],
                ['id_city' => 3146, 'id_state' => 13, 'name' => ' Córrego do Bom Jesus'],
                ['id_city' => 3147, 'id_state' => 13, 'name' => ' Córrego do Ouro'],
                ['id_city' => 3148, 'id_state' => 13, 'name' => ' Córrego Fundo'],
                ['id_city' => 3149, 'id_state' => 13, 'name' => ' Córrego Novo'],
                ['id_city' => 3150, 'id_state' => 13, 'name' => ' Córregos'],
                ['id_city' => 3151, 'id_state' => 13, 'name' => ' Correia de Almeida'],
                ['id_city' => 3152, 'id_state' => 13, 'name' => ' Correntinho'],
                ['id_city' => 3153, 'id_state' => 13, 'name' => ' Costa Sena'],
                ['id_city' => 3154, 'id_state' => 13, 'name' => ' Costas'],
                ['id_city' => 3155, 'id_state' => 13, 'name' => ' Costas da Mantiqueira'],
                ['id_city' => 3156, 'id_state' => 13, 'name' => ' Couto de Magalhães de Minas'],
                ['id_city' => 3157, 'id_state' => 13, 'name' => ' Crisólia'],
                ['id_city' => 3158, 'id_state' => 13, 'name' => ' Crisólita'],
                ['id_city' => 3159, 'id_state' => 13, 'name' => ' Crispim Jaques'],
                ['id_city' => 3160, 'id_state' => 13, 'name' => ' Cristais'],
                ['id_city' => 3161, 'id_state' => 13, 'name' => ' Cristália'],
                ['id_city' => 3162, 'id_state' => 13, 'name' => ' Cristiano Otoni'],
                ['id_city' => 3163, 'id_state' => 13, 'name' => ' Cristina'],
                ['id_city' => 3164, 'id_state' => 13, 'name' => ' Crucilândia'],
                ['id_city' => 3165, 'id_state' => 13, 'name' => ' Cruzeiro da Fortaleza'],
                ['id_city' => 3166, 'id_state' => 13, 'name' => ' Cruzeiro dos Peixotos'],
                ['id_city' => 3167, 'id_state' => 13, 'name' => ' Cruzília'],
                ['id_city' => 3168, 'id_state' => 13, 'name' => ' Cubas'],
                ['id_city' => 3169, 'id_state' => 13, 'name' => ' Cuité Velho'],
                ['id_city' => 3170, 'id_state' => 13, 'name' => ' Cuparaque'],
                ['id_city' => 3171, 'id_state' => 13, 'name' => ' Curimataí'],
                ['id_city' => 3172, 'id_state' => 13, 'name' => ' Curral de Dentro'],
                ['id_city' => 3173, 'id_state' => 13, 'name' => ' Curvelo'],
                ['id_city' => 3174, 'id_state' => 13, 'name' => ' Datas'],
                ['id_city' => 3175, 'id_state' => 13, 'name' => ' Delfim Moreira'],
                ['id_city' => 3176, 'id_state' => 13, 'name' => ' Delfinópolis'],
                ['id_city' => 3177, 'id_state' => 13, 'name' => ' Delta'],
                ['id_city' => 3178, 'id_state' => 13, 'name' => ' Deputado Augusto Clementino'],
                ['id_city' => 3179, 'id_state' => 13, 'name' => ' Derribadinha'],
                ['id_city' => 3180, 'id_state' => 13, 'name' => ' Descoberto'],
                ['id_city' => 3181, 'id_state' => 13, 'name' => ' Desembargador Otoni'],
                ['id_city' => 3182, 'id_state' => 13, 'name' => ' Desemboque'],
                ['id_city' => 3183, 'id_state' => 13, 'name' => ' Desterro de Entre Rios'],
                ['id_city' => 3184, 'id_state' => 13, 'name' => ' Desterro do Melo'],
                ['id_city' => 3185, 'id_state' => 13, 'name' => ' Diamante de Ubá'],
                ['id_city' => 3186, 'id_state' => 13, 'name' => ' Diamantina'],
                ['id_city' => 3187, 'id_state' => 13, 'name' => ' Dias'],
                ['id_city' => 3188, 'id_state' => 13, 'name' => ' Dias Tavares'],
                ['id_city' => 3189, 'id_state' => 13, 'name' => ' Diogo de Vasconcelos'],
                ['id_city' => 3190, 'id_state' => 13, 'name' => ' Dionísio'],
                ['id_city' => 3191, 'id_state' => 13, 'name' => ' Divinésia'],
                ['id_city' => 3192, 'id_state' => 13, 'name' => ' Divino'],
                ['id_city' => 3193, 'id_state' => 13, 'name' => ' Divino das Laranjeiras'],
                ['id_city' => 3194, 'id_state' => 13, 'name' => ' Divino de Virgolândia'],
                ['id_city' => 3195, 'id_state' => 13, 'name' => ' Divino Espírito Santo'],
                ['id_city' => 3196, 'id_state' => 13, 'name' => ' Divinolândia de Minas'],
                ['id_city' => 3197, 'id_state' => 13, 'name' => ' Divinópolis'],
                ['id_city' => 3198, 'id_state' => 13, 'name' => ' Divisa Alegre'],
                ['id_city' => 3199, 'id_state' => 13, 'name' => ' Divisa Nova'],
                ['id_city' => 3200, 'id_state' => 13, 'name' => ' Divisópolis'],
                ['id_city' => 3201, 'id_state' => 13, 'name' => ' Dois de Abril'],
                ['id_city' => 3202, 'id_state' => 13, 'name' => ' Dom Bosco'],
                ['id_city' => 3203, 'id_state' => 13, 'name' => ' Dom Cavati'],
                ['id_city' => 3204, 'id_state' => 13, 'name' => ' Dom Joaquim'],
                ['id_city' => 3205, 'id_state' => 13, 'name' => ' Dom Lara'],
                ['id_city' => 3206, 'id_state' => 13, 'name' => ' Dom Modesto'],
                ['id_city' => 3207, 'id_state' => 13, 'name' => ' Dom Silvério'],
                ['id_city' => 3208, 'id_state' => 13, 'name' => ' Dom Viçoso'],
                ['id_city' => 3209, 'id_state' => 13, 'name' => ' Dona Euzébia'],
                ['id_city' => 3210, 'id_state' => 13, 'name' => ' Dores da Vitória'],
                ['id_city' => 3211, 'id_state' => 13, 'name' => ' Dores de Campos'],
                ['id_city' => 3212, 'id_state' => 13, 'name' => ' Dores de Guanhães'],
                ['id_city' => 3213, 'id_state' => 13, 'name' => ' Dores do Indaiá'],
                ['id_city' => 3214, 'id_state' => 13, 'name' => ' Dores do Paraibuna'],
                ['id_city' => 3215, 'id_state' => 13, 'name' => ' Dores do Turvo'],
                ['id_city' => 3216, 'id_state' => 13, 'name' => ' Doresópolis'],
                ['id_city' => 3217, 'id_state' => 13, 'name' => ' Douradinho'],
                ['id_city' => 3218, 'id_state' => 13, 'name' => ' Douradoquara'],
                ['id_city' => 3219, 'id_state' => 13, 'name' => ' Doutor Campolina'],
                ['id_city' => 3220, 'id_state' => 13, 'name' => ' Doutor Lund'],
                ['id_city' => 3221, 'id_state' => 13, 'name' => ' Durandé'],
                ['id_city' => 3222, 'id_state' => 13, 'name' => ' Edgard Melo'],
                ['id_city' => 3223, 'id_state' => 13, 'name' => ' Elói Mendes'],
                ['id_city' => 3224, 'id_state' => 13, 'name' => ' Emboabas'],
                ['id_city' => 3225, 'id_state' => 13, 'name' => ' Engenheiro Caldas'],
                ['id_city' => 3226, 'id_state' => 13, 'name' => ' Engenheiro Correia'],
                ['id_city' => 3227, 'id_state' => 13, 'name' => ' Engenheiro Navarro'],
                ['id_city' => 3228, 'id_state' => 13, 'name' => ' Engenheiro Schnoor'],
                ['id_city' => 3229, 'id_state' => 13, 'name' => ' Engenho do Ribeiro'],
                ['id_city' => 3230, 'id_state' => 13, 'name' => ' Engenho Novo'],
                ['id_city' => 3231, 'id_state' => 13, 'name' => ' Entre Folhas'],
                ['id_city' => 3232, 'id_state' => 13, 'name' => ' Entre Rios de Minas'],
                ['id_city' => 3233, 'id_state' => 13, 'name' => ' Epaminondas Otoni'],
                ['id_city' => 3234, 'id_state' => 13, 'name' => ' Ermidinha'],
                ['id_city' => 3235, 'id_state' => 13, 'name' => ' Ervália'],
                ['id_city' => 3236, 'id_state' => 13, 'name' => ' Esmeraldas'],
                ['id_city' => 3237, 'id_state' => 13, 'name' => ' Esmeraldas de Ferros'],
                ['id_city' => 3238, 'id_state' => 13, 'name' => ' Espera Feliz'],
                ['id_city' => 3239, 'id_state' => 13, 'name' => ' Espinosa'],
                ['id_city' => 3240, 'id_state' => 13, 'name' => ' Espírito Santo do Dourado'],
                ['id_city' => 3241, 'id_state' => 13, 'name' => ' Esteios'],
                ['id_city' => 3242, 'id_state' => 13, 'name' => ' Estevão de Araújo'],
                ['id_city' => 3243, 'id_state' => 13, 'name' => ' Estiva'],
                ['id_city' => 3244, 'id_state' => 13, 'name' => ' Estrela da Barra'],
                ['id_city' => 3245, 'id_state' => 13, 'name' => ' Estrela Dalva'],
                ['id_city' => 3246, 'id_state' => 13, 'name' => ' Estrela de Jordânia'],
                ['id_city' => 3247, 'id_state' => 13, 'name' => ' Estrela do Indaiá'],
                ['id_city' => 3248, 'id_state' => 13, 'name' => ' Estrela do Sul'],
                ['id_city' => 3249, 'id_state' => 13, 'name' => ' Eugenópolis'],
                ['id_city' => 3250, 'id_state' => 13, 'name' => ' Euxenita'],
                ['id_city' => 3251, 'id_state' => 13, 'name' => ' Ewbank da Câmara'],
                ['id_city' => 3252, 'id_state' => 13, 'name' => ' Expedicionário Alício'],
                ['id_city' => 3253, 'id_state' => 13, 'name' => ' Extração'],
                ['id_city' => 3254, 'id_state' => 13, 'name' => ' Extrema'],
                ['id_city' => 3255, 'id_state' => 13, 'name' => ' Fama'],
                ['id_city' => 3256, 'id_state' => 13, 'name' => ' Faria Lemos'],
                ['id_city' => 3257, 'id_state' => 13, 'name' => ' Farias'],
                ['id_city' => 3258, 'id_state' => 13, 'name' => ' Fechados'],
                ['id_city' => 3259, 'id_state' => 13, 'name' => ' Felicina'],
                ['id_city' => 3260, 'id_state' => 13, 'name' => ' Felício dos Santos'],
                ['id_city' => 3261, 'id_state' => 13, 'name' => ' Felisburgo'],
                ['id_city' => 3262, 'id_state' => 13, 'name' => ' Felixlândia'],
                ['id_city' => 3263, 'id_state' => 13, 'name' => ' Fernandes Tourinho'],
                ['id_city' => 3264, 'id_state' => 13, 'name' => ' Fernão Dias'],
                ['id_city' => 3265, 'id_state' => 13, 'name' => ' Ferreiras'],
                ['id_city' => 3266, 'id_state' => 13, 'name' => ' Ferreirópolis'],
                ['id_city' => 3267, 'id_state' => 13, 'name' => ' Ferros'],
                ['id_city' => 3268, 'id_state' => 13, 'name' => ' Ferruginha'],
                ['id_city' => 3269, 'id_state' => 13, 'name' => ' Fervedouro'],
                ['id_city' => 3270, 'id_state' => 13, 'name' => ' Fidalgo'],
                ['id_city' => 3271, 'id_state' => 13, 'name' => ' Fidelândia'],
                ['id_city' => 3272, 'id_state' => 13, 'name' => ' Flor de Minas'],
                ['id_city' => 3273, 'id_state' => 13, 'name' => ' Florália'],
                ['id_city' => 3274, 'id_state' => 13, 'name' => ' Floresta'],
                ['id_city' => 3275, 'id_state' => 13, 'name' => ' Florestal'],
                ['id_city' => 3276, 'id_state' => 13, 'name' => ' Florestina'],
                ['id_city' => 3277, 'id_state' => 13, 'name' => ' Fonseca'],
                ['id_city' => 3278, 'id_state' => 13, 'name' => ' Formiga'],
                ['id_city' => 3279, 'id_state' => 13, 'name' => ' Formoso'],
                ['id_city' => 3280, 'id_state' => 13, 'name' => ' Fortaleza de Minas'],
                ['id_city' => 3281, 'id_state' => 13, 'name' => ' Fortuna de Minas'],
                ['id_city' => 3282, 'id_state' => 13, 'name' => ' Francisco Badaró'],
                ['id_city' => 3283, 'id_state' => 13, 'name' => ' Francisco Dumont'],
                ['id_city' => 3284, 'id_state' => 13, 'name' => ' Francisco Sá'],
                ['id_city' => 3285, 'id_state' => 13, 'name' => ' Franciscópolis'],
                ['id_city' => 3286, 'id_state' => 13, 'name' => ' Frei Eustáquio'],
                ['id_city' => 3287, 'id_state' => 13, 'name' => ' Frei Gaspar'],
                ['id_city' => 3288, 'id_state' => 13, 'name' => ' Frei Inocêncio'],
                ['id_city' => 3289, 'id_state' => 13, 'name' => ' Frei Lagonegro'],
                ['id_city' => 3290, 'id_state' => 13, 'name' => ' Frei Orlando'],
                ['id_city' => 3291, 'id_state' => 13, 'name' => ' Frei Serafim'],
                ['id_city' => 3292, 'id_state' => 13, 'name' => ' Freire Cardoso'],
                ['id_city' => 3293, 'id_state' => 13, 'name' => ' Fronteira'],
                ['id_city' => 3294, 'id_state' => 13, 'name' => ' Fronteira dos Vales'],
                ['id_city' => 3295, 'id_state' => 13, 'name' => ' Fruta de Leite'],
                ['id_city' => 3296, 'id_state' => 13, 'name' => ' Frutal'],
                ['id_city' => 3297, 'id_state' => 13, 'name' => ' Funchal'],
                ['id_city' => 3298, 'id_state' => 13, 'name' => ' Funilândia'],
                ['id_city' => 3299, 'id_state' => 13, 'name' => ' Furquim'],
                ['id_city' => 3300, 'id_state' => 13, 'name' => ' Galego'],
                ['id_city' => 3301, 'id_state' => 13, 'name' => ' Galena'],
                ['id_city' => 3302, 'id_state' => 13, 'name' => ' Galiléia'],
                ['id_city' => 3303, 'id_state' => 13, 'name' => ' Gama'],
                ['id_city' => 3304, 'id_state' => 13, 'name' => ' Gameleiras'],
                ['id_city' => 3305, 'id_state' => 13, 'name' => ' Garapuava'],
                ['id_city' => 3306, 'id_state' => 13, 'name' => ' Gavião'],
                ['id_city' => 3307, 'id_state' => 13, 'name' => ' Glaucilândia'],
                ['id_city' => 3308, 'id_state' => 13, 'name' => ' Glaura'],
                ['id_city' => 3309, 'id_state' => 13, 'name' => ' Glucínio'],
                ['id_city' => 3310, 'id_state' => 13, 'name' => ' Goiabeira'],
                ['id_city' => 3311, 'id_state' => 13, 'name' => ' Goianá'],
                ['id_city' => 3312, 'id_state' => 13, 'name' => ' Goianases'],
                ['id_city' => 3313, 'id_state' => 13, 'name' => ' Gonçalves'],
                ['id_city' => 3314, 'id_state' => 13, 'name' => ' Gonzaga'],
                ['id_city' => 3315, 'id_state' => 13, 'name' => ' Gororós'],
                ['id_city' => 3316, 'id_state' => 13, 'name' => ' Gorutuba'],
                ['id_city' => 3317, 'id_state' => 13, 'name' => ' Gouveia'],
                ['id_city' => 3318, 'id_state' => 13, 'name' => ' Governador Valadares'],
                ['id_city' => 3319, 'id_state' => 13, 'name' => ' Gramínea'],
                ['id_city' => 3320, 'id_state' => 13, 'name' => ' Granada'],
                ['id_city' => 3321, 'id_state' => 13, 'name' => ' Grão Mogol'],
                ['id_city' => 3322, 'id_state' => 13, 'name' => ' Grota'],
                ['id_city' => 3323, 'id_state' => 13, 'name' => ' Grupiara'],
                ['id_city' => 3324, 'id_state' => 13, 'name' => ' Guaicui'],
                ['id_city' => 3325, 'id_state' => 13, 'name' => ' Guaipava'],
                ['id_city' => 3326, 'id_state' => 13, 'name' => ' Guanhães'],
                ['id_city' => 3327, 'id_state' => 13, 'name' => ' Guapé'],
                ['id_city' => 3328, 'id_state' => 13, 'name' => ' Guaraciaba'],
                ['id_city' => 3329, 'id_state' => 13, 'name' => ' Guaraciama'],
                ['id_city' => 3330, 'id_state' => 13, 'name' => ' Guaranésia'],
                ['id_city' => 3331, 'id_state' => 13, 'name' => ' Guarani'],
                ['id_city' => 3332, 'id_state' => 13, 'name' => ' Guaranilândia'],
                ['id_city' => 3333, 'id_state' => 13, 'name' => ' Guarará'],
                ['id_city' => 3334, 'id_state' => 13, 'name' => ' Guarataia'],
                ['id_city' => 3335, 'id_state' => 13, 'name' => ' Guarda dos Ferreiros'],
                ['id_city' => 3336, 'id_state' => 13, 'name' => ' Guarda-Mor'],
                ['id_city' => 3337, 'id_state' => 13, 'name' => ' Guardinha'],
                ['id_city' => 3338, 'id_state' => 13, 'name' => ' Guaxima'],
                ['id_city' => 3339, 'id_state' => 13, 'name' => ' Guaxupé'],
                ['id_city' => 3340, 'id_state' => 13, 'name' => ' Guidoval'],
                ['id_city' => 3341, 'id_state' => 13, 'name' => ' Guimarânia'],
                ['id_city' => 3342, 'id_state' => 13, 'name' => ' Guinda'],
                ['id_city' => 3343, 'id_state' => 13, 'name' => ' Guiricema'],
                ['id_city' => 3344, 'id_state' => 13, 'name' => ' Gurinhatã'],
                ['id_city' => 3345, 'id_state' => 13, 'name' => ' Heliodora'],
                ['id_city' => 3346, 'id_state' => 13, 'name' => ' Hematita'],
                ['id_city' => 3347, 'id_state' => 13, 'name' => ' Hermilo Alves'],
                ['id_city' => 3348, 'id_state' => 13, 'name' => ' Honorópolis'],
                ['id_city' => 3349, 'id_state' => 13, 'name' => ' Iapu'],
                ['id_city' => 3350, 'id_state' => 13, 'name' => ' Ibertioga'],
                ['id_city' => 3351, 'id_state' => 13, 'name' => ' Ibiá'],
                ['id_city' => 3352, 'id_state' => 13, 'name' => ' Ibiaí'],
                ['id_city' => 3353, 'id_state' => 13, 'name' => ' Ibiracatu'],
                ['id_city' => 3354, 'id_state' => 13, 'name' => ' Ibiraci'],
                ['id_city' => 3355, 'id_state' => 13, 'name' => ' Ibirité'],
                ['id_city' => 3356, 'id_state' => 13, 'name' => ' Ibitira'],
                ['id_city' => 3357, 'id_state' => 13, 'name' => ' Ibitiúra de Minas'],
                ['id_city' => 3358, 'id_state' => 13, 'name' => ' Ibituruna'],
                ['id_city' => 3359, 'id_state' => 13, 'name' => ' Icaraí de Minas'],
                ['id_city' => 3360, 'id_state' => 13, 'name' => ' Igarapé'],
                ['id_city' => 3361, 'id_state' => 13, 'name' => ' Igaratinga'],
                ['id_city' => 3362, 'id_state' => 13, 'name' => ' Iguatama'],
                ['id_city' => 3363, 'id_state' => 13, 'name' => ' Ijaci'],
                ['id_city' => 3364, 'id_state' => 13, 'name' => ' Ilhéus do Prata'],
                ['id_city' => 3365, 'id_state' => 13, 'name' => ' Ilicínea'],
                ['id_city' => 3366, 'id_state' => 13, 'name' => ' Imbé de Minas'],
                ['id_city' => 3367, 'id_state' => 13, 'name' => ' Inconfidentes'],
                ['id_city' => 3368, 'id_state' => 13, 'name' => ' Indaiabira'],
                ['id_city' => 3369, 'id_state' => 13, 'name' => ' Independência'],
                ['id_city' => 3370, 'id_state' => 13, 'name' => ' Indianópolis'],
                ['id_city' => 3371, 'id_state' => 13, 'name' => ' Ingaí'],
                ['id_city' => 3372, 'id_state' => 13, 'name' => ' Inhaí'],
                ['id_city' => 3373, 'id_state' => 13, 'name' => ' Inhapim'],
                ['id_city' => 3374, 'id_state' => 13, 'name' => ' Inhaúma'],
                ['id_city' => 3375, 'id_state' => 13, 'name' => ' Inimutaba'],
                ['id_city' => 3376, 'id_state' => 13, 'name' => ' Ipaba'],
                ['id_city' => 3377, 'id_state' => 13, 'name' => ' Ipanema'],
                ['id_city' => 3378, 'id_state' => 13, 'name' => ' Ipatinga'],
                ['id_city' => 3379, 'id_state' => 13, 'name' => ' Ipiaçu'],
                ['id_city' => 3380, 'id_state' => 13, 'name' => ' Ipoema'],
                ['id_city' => 3381, 'id_state' => 13, 'name' => ' Ipuiúna'],
                ['id_city' => 3382, 'id_state' => 13, 'name' => ' Iraí de Minas'],
                ['id_city' => 3383, 'id_state' => 13, 'name' => ' Itabira'],
                ['id_city' => 3384, 'id_state' => 13, 'name' => ' Itabirinha'],
                ['id_city' => 3385, 'id_state' => 13, 'name' => ' Itabirito'],
                ['id_city' => 3386, 'id_state' => 13, 'name' => ' Itaboca'],
                ['id_city' => 3387, 'id_state' => 13, 'name' => ' Itacambira'],
                ['id_city' => 3388, 'id_state' => 13, 'name' => ' Itacarambi'],
                ['id_city' => 3389, 'id_state' => 13, 'name' => ' Itaci'],
                ['id_city' => 3390, 'id_state' => 13, 'name' => ' Itacolomi'],
                ['id_city' => 3391, 'id_state' => 13, 'name' => ' Itaguara'],
                ['id_city' => 3392, 'id_state' => 13, 'name' => ' Itaim'],
                ['id_city' => 3393, 'id_state' => 13, 'name' => ' Itaipé'],
                ['id_city' => 3394, 'id_state' => 13, 'name' => ' Itajubá'],
                ['id_city' => 3395, 'id_state' => 13, 'name' => ' Itajutiba'],
                ['id_city' => 3396, 'id_state' => 13, 'name' => ' Itamarandiba'],
                ['id_city' => 3397, 'id_state' => 13, 'name' => ' Itamarati'],
                ['id_city' => 3398, 'id_state' => 13, 'name' => ' Itamarati de Minas'],
                ['id_city' => 3399, 'id_state' => 13, 'name' => ' Itambacuri'],
                ['id_city' => 3400, 'id_state' => 13, 'name' => ' Itambé do Mato Dentro'],
                ['id_city' => 3401, 'id_state' => 13, 'name' => ' Itamirim'],
                ['id_city' => 3402, 'id_state' => 13, 'name' => ' Itamogi'],
                ['id_city' => 3403, 'id_state' => 13, 'name' => ' Itamonte'],
                ['id_city' => 3404, 'id_state' => 13, 'name' => ' Itamuri'],
                ['id_city' => 3405, 'id_state' => 13, 'name' => ' Itanhandu'],
                ['id_city' => 3406, 'id_state' => 13, 'name' => ' Itanhomi'],
                ['id_city' => 3407, 'id_state' => 13, 'name' => ' Itaobim'],
                ['id_city' => 3408, 'id_state' => 13, 'name' => ' Itapagipe'],
                ['id_city' => 3409, 'id_state' => 13, 'name' => ' Itapanhoacanga'],
                ['id_city' => 3410, 'id_state' => 13, 'name' => ' Itapecerica'],
                ['id_city' => 3411, 'id_state' => 13, 'name' => ' Itapeva'],
                ['id_city' => 3412, 'id_state' => 13, 'name' => ' Itapiru'],
                ['id_city' => 3413, 'id_state' => 13, 'name' => ' Itapirucu'],
                ['id_city' => 3414, 'id_state' => 13, 'name' => ' Itatiaiuçu'],
                ['id_city' => 3415, 'id_state' => 13, 'name' => ' Itaú de Minas'],
                ['id_city' => 3416, 'id_state' => 13, 'name' => ' Itaúna'],
                ['id_city' => 3417, 'id_state' => 13, 'name' => ' Itauninha'],
                ['id_city' => 3418, 'id_state' => 13, 'name' => ' Itaverava'],
                ['id_city' => 3419, 'id_state' => 13, 'name' => ' Itererê'],
                ['id_city' => 3420, 'id_state' => 13, 'name' => ' Itinga'],
                ['id_city' => 3421, 'id_state' => 13, 'name' => ' Itira'],
                ['id_city' => 3422, 'id_state' => 13, 'name' => ' Itueta'],
                ['id_city' => 3423, 'id_state' => 13, 'name' => ' Ituí'],
                ['id_city' => 3424, 'id_state' => 13, 'name' => ' Ituiutaba'],
                ['id_city' => 3425, 'id_state' => 13, 'name' => ' Itumirim'],
                ['id_city' => 3426, 'id_state' => 13, 'name' => ' Iturama'],
                ['id_city' => 3427, 'id_state' => 13, 'name' => ' Itutinga'],
                ['id_city' => 3428, 'id_state' => 13, 'name' => ' Jaboticatubas'],
                ['id_city' => 3429, 'id_state' => 13, 'name' => ' Jacarandira'],
                ['id_city' => 3430, 'id_state' => 13, 'name' => ' Jacaré'],
                ['id_city' => 3431, 'id_state' => 13, 'name' => ' Jacinto'],
                ['id_city' => 3432, 'id_state' => 13, 'name' => ' Jacuí'],
                ['id_city' => 3433, 'id_state' => 13, 'name' => ' Jacutinga'],
                ['id_city' => 3434, 'id_state' => 13, 'name' => ' Jaguaraçu'],
                ['id_city' => 3435, 'id_state' => 13, 'name' => ' Jaguarão'],
                ['id_city' => 3436, 'id_state' => 13, 'name' => ' Jaguaritira'],
                ['id_city' => 3437, 'id_state' => 13, 'name' => ' Jaíba'],
                ['id_city' => 3438, 'id_state' => 13, 'name' => ' Jampruca'],
                ['id_city' => 3439, 'id_state' => 13, 'name' => ' Janaúba'],
                ['id_city' => 3440, 'id_state' => 13, 'name' => ' Januária'],
                ['id_city' => 3441, 'id_state' => 13, 'name' => ' Japaraíba'],
                ['id_city' => 3442, 'id_state' => 13, 'name' => ' Japonvar'],
                ['id_city' => 3443, 'id_state' => 13, 'name' => ' Jardinésia'],
                ['id_city' => 3444, 'id_state' => 13, 'name' => ' Jeceaba'],
                ['id_city' => 3445, 'id_state' => 13, 'name' => ' Jenipapo de Minas'],
                ['id_city' => 3446, 'id_state' => 13, 'name' => ' Jequeri'],
                ['id_city' => 3447, 'id_state' => 13, 'name' => ' Jequitaí'],
                ['id_city' => 3448, 'id_state' => 13, 'name' => ' Jequitibá'],
                ['id_city' => 3449, 'id_state' => 13, 'name' => ' Jequitinhonha'],
                ['id_city' => 3450, 'id_state' => 13, 'name' => ' Jesuânia'],
                ['id_city' => 3451, 'id_state' => 13, 'name' => ' Joaíma'],
                ['id_city' => 3452, 'id_state' => 13, 'name' => ' Joanésia'],
                ['id_city' => 3453, 'id_state' => 13, 'name' => ' João Monlevade'],
                ['id_city' => 3454, 'id_state' => 13, 'name' => ' João Pinheiro'],
                ['id_city' => 3455, 'id_state' => 13, 'name' => ' Joaquim Felício'],
                ['id_city' => 3456, 'id_state' => 13, 'name' => ' Jordânia'],
                ['id_city' => 3457, 'id_state' => 13, 'name' => ' José Gonçalves de Minas'],
                ['id_city' => 3458, 'id_state' => 13, 'name' => ' José Raydan'],
                ['id_city' => 3459, 'id_state' => 13, 'name' => ' Joselândia'],
                ['id_city' => 3460, 'id_state' => 13, 'name' => ' Josenópolis'],
                ['id_city' => 3461, 'id_state' => 13, 'name' => ' Juatuba'],
                ['id_city' => 3462, 'id_state' => 13, 'name' => ' Jubaí'],
                ['id_city' => 3463, 'id_state' => 13, 'name' => ' Juiraçu'],
                ['id_city' => 3464, 'id_state' => 13, 'name' => ' Juiz de Fora'],
                ['id_city' => 3465, 'id_state' => 13, 'name' => ' Junco de Minas'],
                ['id_city' => 3466, 'id_state' => 13, 'name' => ' Juramento'],
                ['id_city' => 3467, 'id_state' => 13, 'name' => ' Juréia'],
                ['id_city' => 3468, 'id_state' => 13, 'name' => ' Juruaia'],
                ['id_city' => 3469, 'id_state' => 13, 'name' => ' Jurumirim'],
                ['id_city' => 3470, 'id_state' => 13, 'name' => ' Justinópolis'],
                ['id_city' => 3471, 'id_state' => 13, 'name' => ' Juvenília'],
                ['id_city' => 3472, 'id_state' => 13, 'name' => ' Lacerdina'],
                ['id_city' => 3473, 'id_state' => 13, 'name' => ' Ladainha'],
                ['id_city' => 3474, 'id_state' => 13, 'name' => ' Lagamar'],
                ['id_city' => 3475, 'id_state' => 13, 'name' => ' Lagoa Bonita'],
                ['id_city' => 3476, 'id_state' => 13, 'name' => ' Lagoa da Prata'],
                ['id_city' => 3477, 'id_state' => 13, 'name' => ' Lagoa dos Patos'],
                ['id_city' => 3478, 'id_state' => 13, 'name' => ' Lagoa Dourada'],
                ['id_city' => 3479, 'id_state' => 13, 'name' => ' Lagoa Formosa'],
                ['id_city' => 3480, 'id_state' => 13, 'name' => ' Lagoa Grande'],
                ['id_city' => 3481, 'id_state' => 13, 'name' => ' Lagoa Santa'],
                ['id_city' => 3482, 'id_state' => 13, 'name' => ' Lajinha'],
                ['id_city' => 3483, 'id_state' => 13, 'name' => ' Lambari'],
                ['id_city' => 3484, 'id_state' => 13, 'name' => ' Lamim'],
                ['id_city' => 3485, 'id_state' => 13, 'name' => ' Lamounier'],
                ['id_city' => 3486, 'id_state' => 13, 'name' => ' Lapinha'],
                ['id_city' => 3487, 'id_state' => 13, 'name' => ' Laranjal'],
                ['id_city' => 3488, 'id_state' => 13, 'name' => ' Laranjeiras de Caldas'],
                ['id_city' => 3489, 'id_state' => 13, 'name' => ' Lassance'],
                ['id_city' => 3490, 'id_state' => 13, 'name' => ' Lavras'],
                ['id_city' => 3491, 'id_state' => 13, 'name' => ' Leandro Ferreira'],
                ['id_city' => 3492, 'id_state' => 13, 'name' => ' Leme do Prado'],
                ['id_city' => 3493, 'id_state' => 13, 'name' => ' Leopoldina'],
                ['id_city' => 3494, 'id_state' => 13, 'name' => ' Levinópolis'],
                ['id_city' => 3495, 'id_state' => 13, 'name' => ' Liberdade'],
                ['id_city' => 3496, 'id_state' => 13, 'name' => ' Lima Duarte'],
                ['id_city' => 3497, 'id_state' => 13, 'name' => ' Limeira do Oeste'],
                ['id_city' => 3498, 'id_state' => 13, 'name' => ' Limeira de Mantena'],
                ['id_city' => 3499, 'id_state' => 13, 'name' => ' Lobo Leite'],
                ['id_city' => 3500, 'id_state' => 13, 'name' => ' Lontra'],
                ['id_city' => 3501, 'id_state' => 13, 'name' => ' São José do Rio Manso'],
                ['id_city' => 3502, 'id_state' => 13, 'name' => ' Lufa'],
                ['id_city' => 3503, 'id_state' => 13, 'name' => ' Luisburgo'],
                ['id_city' => 3504, 'id_state' => 13, 'name' => ' Luislândia'],
                ['id_city' => 3505, 'id_state' => 13, 'name' => ' Luiz Pires de Minas'],
                ['id_city' => 3506, 'id_state' => 13, 'name' => ' Luizlândia do Oeste'],
                ['id_city' => 3507, 'id_state' => 13, 'name' => ' Luminárias'],
                ['id_city' => 3508, 'id_state' => 13, 'name' => ' Luminosa'],
                ['id_city' => 3509, 'id_state' => 13, 'name' => ' Luz'],
                ['id_city' => 3510, 'id_state' => 13, 'name' => ' Macaia'],
                ['id_city' => 3511, 'id_state' => 13, 'name' => ' Machacalis'],
                ['id_city' => 3512, 'id_state' => 13, 'name' => ' Machado'],
                ['id_city' => 3513, 'id_state' => 13, 'name' => ' Macuco'],
                ['id_city' => 3514, 'id_state' => 13, 'name' => ' Macuco de Minas'],
                ['id_city' => 3515, 'id_state' => 13, 'name' => ' Madre de Deus de Minas'],
                ['id_city' => 3516, 'id_state' => 13, 'name' => ' Mãe dos Homens'],
                ['id_city' => 3517, 'id_state' => 13, 'name' => ' Major Ezequiel'],
                ['id_city' => 3518, 'id_state' => 13, 'name' => ' Major Porto'],
                ['id_city' => 3519, 'id_state' => 13, 'name' => ' Malacacheta'],
                ['id_city' => 3520, 'id_state' => 13, 'name' => ' Mamonas');]
            ]);
        }
    }
