<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities15 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 9292, 'id_state' => 25, 'name' => ' Marinópolis'],
                ['id_city' => 9293, 'id_state' => 25, 'name' => ' Maristela'],
                ['id_city' => 9294, 'id_state' => 25, 'name' => ' Martim Francisco'],
                ['id_city' => 9295, 'id_state' => 25, 'name' => ' Martinho Prado Júnior'],
                ['id_city' => 9296, 'id_state' => 25, 'name' => ' Martinópolis'],
                ['id_city' => 9297, 'id_state' => 25, 'name' => ' Matão'],
                ['id_city' => 9298, 'id_state' => 25, 'name' => ' Mauá'],
                ['id_city' => 9299, 'id_state' => 25, 'name' => ' Mendonça'],
                ['id_city' => 9300, 'id_state' => 25, 'name' => ' Meridiano'],
                ['id_city' => 9301, 'id_state' => 25, 'name' => ' Mesópolis'],
                ['id_city' => 9302, 'id_state' => 25, 'name' => ' Miguelópolis'],
                ['id_city' => 9303, 'id_state' => 25, 'name' => ' Mineiros do Tietê'],
                ['id_city' => 9304, 'id_state' => 25, 'name' => ' Mira Estrela'],
                ['id_city' => 9305, 'id_state' => 25, 'name' => ' Miracatu'],
                ['id_city' => 9306, 'id_state' => 25, 'name' => ' Miraluz'],
                ['id_city' => 9307, 'id_state' => 25, 'name' => ' Mirandópolis'],
                ['id_city' => 9308, 'id_state' => 25, 'name' => ' Mirante do Paranapanema'],
                ['id_city' => 9309, 'id_state' => 25, 'name' => ' Mirassol'],
                ['id_city' => 9310, 'id_state' => 25, 'name' => ' Mirassolândia'],
                ['id_city' => 9311, 'id_state' => 25, 'name' => ' Mococa'],
                ['id_city' => 9312, 'id_state' => 25, 'name' => ' Mogi das Cruzes'],
                ['id_city' => 9313, 'id_state' => 25, 'name' => ' Mogi Guaçu'],
                ['id_city' => 9314, 'id_state' => 25, 'name' => ' Mogi Mirim'],
                ['id_city' => 9315, 'id_state' => 25, 'name' => ' Mombuca'],
                ['id_city' => 9316, 'id_state' => 25, 'name' => ' Monções'],
                ['id_city' => 9317, 'id_state' => 25, 'name' => ' Mongaguá'],
                ['id_city' => 9318, 'id_state' => 25, 'name' => ' Montalvão'],
                ['id_city' => 9319, 'id_state' => 25, 'name' => ' Monte Alegre do Sul'],
                ['id_city' => 9320, 'id_state' => 25, 'name' => ' Monte Alto'],
                ['id_city' => 9321, 'id_state' => 25, 'name' => ' Monte Aprazível'],
                ['id_city' => 9322, 'id_state' => 25, 'name' => ' Monte Azul Paulista'],
                ['id_city' => 9323, 'id_state' => 25, 'name' => ' Monte Cabrão'],
                ['id_city' => 9324, 'id_state' => 25, 'name' => ' Monte Castelo'],
                ['id_city' => 9325, 'id_state' => 25, 'name' => ' Monte Mor'],
                ['id_city' => 9326, 'id_state' => 25, 'name' => ' Monte Verde Paulista'],
                ['id_city' => 9327, 'id_state' => 25, 'name' => ' Monteiro Lobato'],
                ['id_city' => 9328, 'id_state' => 25, 'name' => ' Moreira César'],
                ['id_city' => 9329, 'id_state' => 25, 'name' => ' Morro Agudo'],
                ['id_city' => 9330, 'id_state' => 25, 'name' => ' Morro do Alto'],
                ['id_city' => 9331, 'id_state' => 25, 'name' => ' Morungaba'],
                ['id_city' => 9332, 'id_state' => 25, 'name' => ' Mostardas'],
                ['id_city' => 9333, 'id_state' => 25, 'name' => ' Motuca'],
                ['id_city' => 9334, 'id_state' => 25, 'name' => ' Mourão'],
                ['id_city' => 9335, 'id_state' => 25, 'name' => ' Murutinga do Sul'],
                ['id_city' => 9336, 'id_state' => 25, 'name' => ' Nantes'],
                ['id_city' => 9337, 'id_state' => 25, 'name' => ' Narandiba'],
                ['id_city' => 9338, 'id_state' => 25, 'name' => ' Natividade da Serra'],
                ['id_city' => 9339, 'id_state' => 25, 'name' => ' Nazaré Paulista'],
                ['id_city' => 9340, 'id_state' => 25, 'name' => ' Neves Paulista'],
                ['id_city' => 9341, 'id_state' => 25, 'name' => ' Nhandeara'],
                ['id_city' => 9342, 'id_state' => 25, 'name' => ' Nipoã'],
                ['id_city' => 9343, 'id_state' => 25, 'name' => ' Nogueira'],
                ['id_city' => 9344, 'id_state' => 25, 'name' => ' Nossa Senhora do Remédio'],
                ['id_city' => 9345, 'id_state' => 25, 'name' => ' Nova Alexandria'],
                ['id_city' => 9346, 'id_state' => 25, 'name' => ' Nova Aliança'],
                ['id_city' => 9347, 'id_state' => 25, 'name' => ' Nova América'],
                ['id_city' => 9348, 'id_state' => 25, 'name' => ' Nova Aparecida'],
                ['id_city' => 9349, 'id_state' => 25, 'name' => ' Nova Campina'],
                ['id_city' => 9350, 'id_state' => 25, 'name' => ' Nova Canaã Paulista'],
                ['id_city' => 9351, 'id_state' => 25, 'name' => ' Nova Castilho'],
                ['id_city' => 9352, 'id_state' => 25, 'name' => ' Nova Europa'],
                ['id_city' => 9353, 'id_state' => 25, 'name' => ' Nova Granada'],
                ['id_city' => 9354, 'id_state' => 25, 'name' => ' Nova Guataporanga'],
                ['id_city' => 9355, 'id_state' => 25, 'name' => ' Nova Independência'],
                ['id_city' => 9356, 'id_state' => 25, 'name' => ' Nova Itapirema'],
                ['id_city' => 9357, 'id_state' => 25, 'name' => ' Nova Luzitânia'],
                ['id_city' => 9358, 'id_state' => 25, 'name' => ' Nova Odessa'],
                ['id_city' => 9359, 'id_state' => 25, 'name' => ' Nova Pátria'],
                ['id_city' => 9360, 'id_state' => 25, 'name' => ' Nova Veneza'],
                ['id_city' => 9361, 'id_state' => 25, 'name' => ' Novais'],
                ['id_city' => 9362, 'id_state' => 25, 'name' => ' Novo Cravinhos'],
                ['id_city' => 9363, 'id_state' => 25, 'name' => ' Novo Horizonte'],
                ['id_city' => 9364, 'id_state' => 25, 'name' => ' Nuporanga'],
                ['id_city' => 9365, 'id_state' => 25, 'name' => ' Oásis'],
                ['id_city' => 9366, 'id_state' => 25, 'name' => ' Ocauçu'],
                ['id_city' => 9367, 'id_state' => 25, 'name' => ' Óleo'],
                ['id_city' => 9368, 'id_state' => 25, 'name' => ' Olímpia'],
                ['id_city' => 9369, 'id_state' => 25, 'name' => ' Oliveira Barros'],
                ['id_city' => 9370, 'id_state' => 25, 'name' => ' Onda Branca'],
                ['id_city' => 9371, 'id_state' => 25, 'name' => ' Onda Verde'],
                ['id_city' => 9372, 'id_state' => 25, 'name' => ' Oriente'],
                ['id_city' => 9373, 'id_state' => 25, 'name' => ' Orindiúva'],
                ['id_city' => 9374, 'id_state' => 25, 'name' => ' Orlândia'],
                ['id_city' => 9375, 'id_state' => 25, 'name' => ' Osasco'],
                ['id_city' => 9376, 'id_state' => 25, 'name' => ' Oscar Bressane'],
                ['id_city' => 9377, 'id_state' => 25, 'name' => ' Osvaldo Cruz'],
                ['id_city' => 9378, 'id_state' => 25, 'name' => ' Ourinhos'],
                ['id_city' => 9379, 'id_state' => 25, 'name' => ' Ouro Fino Paulista'],
                ['id_city' => 9380, 'id_state' => 25, 'name' => ' Ouro Verde'],
                ['id_city' => 9381, 'id_state' => 25, 'name' => ' Ouroeste'],
                ['id_city' => 9382, 'id_state' => 25, 'name' => ' Pacaembu'],
                ['id_city' => 9383, 'id_state' => 25, 'name' => ' Padre Nóbrega'],
                ['id_city' => 9384, 'id_state' => 25, 'name' => ' Palestina'],
                ['id_city' => 9385, 'id_state' => 25, 'name' => ' Palmares Paulista'],
                ['id_city' => 9386, 'id_state' => 25, 'name' => ' Palmeira D Oeste'],
                ['id_city' => 9387, 'id_state' => 25, 'name' => ' Palmeiras de São Paulo'],
                ['id_city' => 9388, 'id_state' => 25, 'name' => ' Palmital'],
                ['id_city' => 9389, 'id_state' => 25, 'name' => ' Panorama'],
                ['id_city' => 9390, 'id_state' => 25, 'name' => ' Paraguaçu Paulista'],
                ['id_city' => 9391, 'id_state' => 25, 'name' => ' Paraibuna'],
                ['id_city' => 9392, 'id_state' => 25, 'name' => ' Paraíso'],
                ['id_city' => 9393, 'id_state' => 25, 'name' => ' Paraisolândia'],
                ['id_city' => 9394, 'id_state' => 25, 'name' => ' Paranabi'],
                ['id_city' => 9395, 'id_state' => 25, 'name' => ' Paranapanema'],
                ['id_city' => 9396, 'id_state' => 25, 'name' => ' Paranapiacaba'],
                ['id_city' => 9397, 'id_state' => 25, 'name' => ' Paranapuã'],
                ['id_city' => 9398, 'id_state' => 25, 'name' => ' Parapuã'],
                ['id_city' => 9399, 'id_state' => 25, 'name' => ' Pardinho'],
                ['id_city' => 9400, 'id_state' => 25, 'name' => ' Pariquera-Açu'],
                ['id_city' => 9401, 'id_state' => 25, 'name' => ' Parisi'],
                ['id_city' => 9402, 'id_state' => 25, 'name' => ' Parnaso'],
                ['id_city' => 9403, 'id_state' => 25, 'name' => ' Parque Meia Lua'],
                ['id_city' => 9404, 'id_state' => 25, 'name' => ' Paruru'],
                ['id_city' => 9405, 'id_state' => 25, 'name' => ' Patrocínio Paulista'],
                ['id_city' => 9406, 'id_state' => 25, 'name' => ' Paulicéia'],
                ['id_city' => 9407, 'id_state' => 25, 'name' => ' Paulínia'],
                ['id_city' => 9408, 'id_state' => 25, 'name' => ' Paulistânia'],
                ['id_city' => 9409, 'id_state' => 25, 'name' => ' Paulo de Faria'],
                ['id_city' => 9410, 'id_state' => 25, 'name' => ' Paulópolis'],
                ['id_city' => 9411, 'id_state' => 25, 'name' => ' Pederneiras'],
                ['id_city' => 9412, 'id_state' => 25, 'name' => ' Pedra Bela'],
                ['id_city' => 9413, 'id_state' => 25, 'name' => ' Pedra Branca de Itararé'],
                ['id_city' => 9414, 'id_state' => 25, 'name' => ' Pedranópolis'],
                ['id_city' => 9415, 'id_state' => 25, 'name' => ' Pedregulho'],
                ['id_city' => 9416, 'id_state' => 25, 'name' => ' Pedreira'],
                ['id_city' => 9417, 'id_state' => 25, 'name' => ' Pedrinhas Paulista'],
                ['id_city' => 9418, 'id_state' => 25, 'name' => ' Pedro Barros'],
                ['id_city' => 9419, 'id_state' => 25, 'name' => ' Pedro de Toledo'],
                ['id_city' => 9420, 'id_state' => 25, 'name' => ' Penápolis'],
                ['id_city' => 9421, 'id_state' => 25, 'name' => ' Pereira Barreto'],
                ['id_city' => 9422, 'id_state' => 25, 'name' => ' Pereiras'],
                ['id_city' => 9423, 'id_state' => 25, 'name' => ' Peruíbe'],
                ['id_city' => 9424, 'id_state' => 25, 'name' => ' Piacatu'],
                ['id_city' => 9425, 'id_state' => 25, 'name' => ' Picinguaba'],
                ['id_city' => 9426, 'id_state' => 25, 'name' => ' Piedade'],
                ['id_city' => 9427, 'id_state' => 25, 'name' => ' Pilar do Sul'],
                ['id_city' => 9428, 'id_state' => 25, 'name' => ' Pindamonhangaba'],
                ['id_city' => 9429, 'id_state' => 25, 'name' => ' Pindorama'],
                ['id_city' => 9430, 'id_state' => 25, 'name' => ' Pinhalzinho'],
                ['id_city' => 9431, 'id_state' => 25, 'name' => ' Pinheiros'],
                ['id_city' => 9432, 'id_state' => 25, 'name' => ' Pioneiros'],
                ['id_city' => 9433, 'id_state' => 25, 'name' => ' Piquerobi'],
                ['id_city' => 9434, 'id_state' => 25, 'name' => ' Piquete'],
                ['id_city' => 9435, 'id_state' => 25, 'name' => ' Piracaia'],
                ['id_city' => 9436, 'id_state' => 25, 'name' => ' Piracicaba'],
                ['id_city' => 9437, 'id_state' => 25, 'name' => ' Piraju'],
                ['id_city' => 9438, 'id_state' => 25, 'name' => ' Pirajuí'],
                ['id_city' => 9439, 'id_state' => 25, 'name' => ' Pirambóia'],
                ['id_city' => 9440, 'id_state' => 25, 'name' => ' Pirangi'],
                ['id_city' => 9441, 'id_state' => 25, 'name' => ' Pirapitingui'],
                ['id_city' => 9442, 'id_state' => 25, 'name' => ' Pirapora do Bom Jesus'],
                ['id_city' => 9443, 'id_state' => 25, 'name' => ' Pirapozinho'],
                ['id_city' => 9444, 'id_state' => 25, 'name' => ' Pirassununga'],
                ['id_city' => 9445, 'id_state' => 25, 'name' => ' Piratininga'],
                ['id_city' => 9446, 'id_state' => 25, 'name' => ' Pitangueiras'],
                ['id_city' => 9447, 'id_state' => 25, 'name' => ' Planalto'],
                ['id_city' => 9448, 'id_state' => 25, 'name' => ' Planalto'],
                ['id_city' => 9449, 'id_state' => 25, 'name' => ' Planalto do Sul'],
                ['id_city' => 9450, 'id_state' => 25, 'name' => ' Platina'],
                ['id_city' => 9451, 'id_state' => 25, 'name' => ' Poá'],
                ['id_city' => 9452, 'id_state' => 25, 'name' => ' Poloni'],
                ['id_city' => 9453, 'id_state' => 25, 'name' => ' Polvilho'],
                ['id_city' => 9454, 'id_state' => 25, 'name' => ' Pompéia'],
                ['id_city' => 9455, 'id_state' => 25, 'name' => ' Pongaí'],
                ['id_city' => 9456, 'id_state' => 25, 'name' => ' Pontal'],
                ['id_city' => 9457, 'id_state' => 25, 'name' => ' Pontalinda'],
                ['id_city' => 9458, 'id_state' => 25, 'name' => ' Pontes Gestal'],
                ['id_city' => 9459, 'id_state' => 25, 'name' => ' Populina'],
                ['id_city' => 9460, 'id_state' => 25, 'name' => ' Porangaba'],
                ['id_city' => 9461, 'id_state' => 25, 'name' => ' Porto Feliz'],
                ['id_city' => 9462, 'id_state' => 25, 'name' => ' Porto Ferreira'],
                ['id_city' => 9463, 'id_state' => 25, 'name' => ' Porto Novo'],
                ['id_city' => 9464, 'id_state' => 25, 'name' => ' Potim'],
                ['id_city' => 9465, 'id_state' => 25, 'name' => ' Potirendaba'],
                ['id_city' => 9466, 'id_state' => 25, 'name' => ' Potunduva'],
                ['id_city' => 9467, 'id_state' => 25, 'name' => ' Pracinha'],
                ['id_city' => 9468, 'id_state' => 25, 'name' => ' Pradínia'],
                ['id_city' => 9469, 'id_state' => 25, 'name' => ' Pradópolis'],
                ['id_city' => 9470, 'id_state' => 25, 'name' => ' Praia Grande'],
                ['id_city' => 9471, 'id_state' => 25, 'name' => ' Pratânia'],
                ['id_city' => 9472, 'id_state' => 25, 'name' => ' Presidente Alves'],
                ['id_city' => 9473, 'id_state' => 25, 'name' => ' Presidente Bernardes'],
                ['id_city' => 9474, 'id_state' => 25, 'name' => ' Presidente Epitácio'],
                ['id_city' => 9475, 'id_state' => 25, 'name' => ' Presidente Prudente'],
                ['id_city' => 9476, 'id_state' => 25, 'name' => ' Presidente Venceslau'],
                ['id_city' => 9477, 'id_state' => 25, 'name' => ' Primavera'],
                ['id_city' => 9478, 'id_state' => 25, 'name' => ' Promissão'],
                ['id_city' => 9479, 'id_state' => 25, 'name' => ' Prudêncio de Morais'],
                ['id_city' => 9480, 'id_state' => 25, 'name' => ' Quadra'],
                ['id_city' => 9481, 'id_state' => 25, 'name' => ' Quatá'],
                ['id_city' => 9482, 'id_state' => 25, 'name' => ' Queiroz'],
                ['id_city' => 9483, 'id_state' => 25, 'name' => ' Queluz'],
                ['id_city' => 9484, 'id_state' => 25, 'name' => ' Quintana'],
                ['id_city' => 9485, 'id_state' => 25, 'name' => ' Quiririm'],
                ['id_city' => 9486, 'id_state' => 25, 'name' => ' Rafard'],
                ['id_city' => 9487, 'id_state' => 25, 'name' => ' Rancharia'],
                ['id_city' => 9488, 'id_state' => 25, 'name' => ' Rechan'],
                ['id_city' => 9489, 'id_state' => 25, 'name' => ' Redenção da Serra'],
                ['id_city' => 9490, 'id_state' => 25, 'name' => ' Regente Feijó'],
                ['id_city' => 9491, 'id_state' => 25, 'name' => ' Reginópolis'],
                ['id_city' => 9492, 'id_state' => 25, 'name' => ' Registro'],
                ['id_city' => 9493, 'id_state' => 25, 'name' => ' Restinga'],
                ['id_city' => 9494, 'id_state' => 25, 'name' => ' Riacho Grande'],
                ['id_city' => 9495, 'id_state' => 25, 'name' => ' Ribeira'],
                ['id_city' => 9496, 'id_state' => 25, 'name' => ' Ribeirão Bonito'],
                ['id_city' => 9497, 'id_state' => 25, 'name' => ' Ribeirão Branco'],
                ['id_city' => 9498, 'id_state' => 25, 'name' => ' Ribeirão Corrente'],
                ['id_city' => 9499, 'id_state' => 25, 'name' => ' Ribeirão do Sul'],
                ['id_city' => 9500, 'id_state' => 25, 'name' => ' Ribeirão dos Índios'],
                ['id_city' => 9501, 'id_state' => 25, 'name' => ' Ribeirão Grande'],
                ['id_city' => 9502, 'id_state' => 25, 'name' => ' Ribeirão Pires'],
                ['id_city' => 9503, 'id_state' => 25, 'name' => ' Ribeirão Preto'],
                ['id_city' => 9504, 'id_state' => 25, 'name' => ' Ribeiro do Vale'],
                ['id_city' => 9505, 'id_state' => 25, 'name' => ' Ribeiro dos Santos'],
                ['id_city' => 9506, 'id_state' => 25, 'name' => ' Rifaina'],
                ['id_city' => 9507, 'id_state' => 25, 'name' => ' Rincão'],
                ['id_city' => 9508, 'id_state' => 25, 'name' => ' Rinópolis'],
                ['id_city' => 9509, 'id_state' => 25, 'name' => ' Rio Claro'],
                ['id_city' => 9510, 'id_state' => 25, 'name' => ' Rio das Pedras'],
                ['id_city' => 9511, 'id_state' => 25, 'name' => ' Rio Grande da Serra'],
                ['id_city' => 9512, 'id_state' => 25, 'name' => ' Riolândia'],
                ['id_city' => 9513, 'id_state' => 25, 'name' => ' Riversul'],
                ['id_city' => 9514, 'id_state' => 25, 'name' => ' Roberto'],
                ['id_city' => 9515, 'id_state' => 25, 'name' => ' Rosália'],
                ['id_city' => 9516, 'id_state' => 25, 'name' => ' Rosana'],
                ['id_city' => 9517, 'id_state' => 25, 'name' => ' Roseira'],
                ['id_city' => 9518, 'id_state' => 25, 'name' => ' Rubiácea'],
                ['id_city' => 9519, 'id_state' => 25, 'name' => ' Rubião Júnior'],
                ['id_city' => 9520, 'id_state' => 25, 'name' => ' Rubinéia'],
                ['id_city' => 9521, 'id_state' => 25, 'name' => ' Ruilândia'],
                ['id_city' => 9522, 'id_state' => 25, 'name' => ' Sabaúna'],
                ['id_city' => 9523, 'id_state' => 25, 'name' => ' Sabino'],
                ['id_city' => 9524, 'id_state' => 25, 'name' => ' Sagres'],
                ['id_city' => 9525, 'id_state' => 25, 'name' => ' Sales'],
                ['id_city' => 9526, 'id_state' => 25, 'name' => ' Sales Oliveira'],
                ['id_city' => 9527, 'id_state' => 25, 'name' => ' Salesópolis'],
                ['id_city' => 9528, 'id_state' => 25, 'name' => ' Salmourão'],
                ['id_city' => 9529, 'id_state' => 25, 'name' => ' Saltinho'],
                ['id_city' => 9530, 'id_state' => 25, 'name' => ' Salto'],
                ['id_city' => 9531, 'id_state' => 25, 'name' => ' Salto de Pirapora'],
                ['id_city' => 9532, 'id_state' => 25, 'name' => ' Salto do Avanhandava'],
                ['id_city' => 9533, 'id_state' => 25, 'name' => ' Salto Grande'],
                ['id_city' => 9534, 'id_state' => 25, 'name' => ' Sandovalina'],
                ['id_city' => 9535, 'id_state' => 25, 'name' => ' Santa Adélia'],
                ['id_city' => 9536, 'id_state' => 25, 'name' => ' Santa Albertina'],
                ['id_city' => 9537, 'id_state' => 25, 'name' => ' Santa América'],
                ['id_city' => 9538, 'id_state' => 25, 'name' => ' Santa Bárbara D Oeste'],
                ['id_city' => 9539, 'id_state' => 25, 'name' => ' Santa Branca'],
                ['id_city' => 9540, 'id_state' => 25, 'name' => ' Santa Clara D Oeste'],
                ['id_city' => 9541, 'id_state' => 25, 'name' => ' Santa Cruz da Conceição'],
                ['id_city' => 9542, 'id_state' => 25, 'name' => ' Santa Cruz da Esperança'],
                ['id_city' => 9543, 'id_state' => 25, 'name' => ' Santa Cruz da Estrela'],
                ['id_city' => 9544, 'id_state' => 25, 'name' => ' Santa Cruz das Palmeiras'],
                ['id_city' => 9545, 'id_state' => 25, 'name' => ' Santa Cruz do Rio Pardo'],
                ['id_city' => 9546, 'id_state' => 25, 'name' => ' Santa Cruz dos Lopes'],
                ['id_city' => 9547, 'id_state' => 25, 'name' => ' Santa Ernestina'],
                ['id_city' => 9548, 'id_state' => 25, 'name' => ' Santa Eudóxia'],
                ['id_city' => 9549, 'id_state' => 25, 'name' => ' Santa Fé do Sul'],
                ['id_city' => 9550, 'id_state' => 25, 'name' => ' Santa Gertrudes'],
                ['id_city' => 9551, 'id_state' => 25, 'name' => ' Santa Isabel'],
                ['id_city' => 9552, 'id_state' => 25, 'name' => ' Santa Isabel do Marinheiro'],
                ['id_city' => 9553, 'id_state' => 25, 'name' => ' Santa Lúcia'],
                ['id_city' => 9554, 'id_state' => 25, 'name' => ' Santa Margarida Paulista'],
                ['id_city' => 9555, 'id_state' => 25, 'name' => ' Santa Maria da Serra'],
                ['id_city' => 9556, 'id_state' => 25, 'name' => ' Santa Maria do Gurupá'],
                ['id_city' => 9557, 'id_state' => 25, 'name' => ' Santa Mercedes'],
                ['id_city' => 9558, 'id_state' => 25, 'name' => ' Santa Rita D Oeste'],
                ['id_city' => 9559, 'id_state' => 25, 'name' => ' Santa Rita do Passa Quatro'],
                ['id_city' => 9560, 'id_state' => 25, 'name' => ' Santa Rita do Ribeira'],
                ['id_city' => 9561, 'id_state' => 25, 'name' => ' Santa Rosa de Viterbo'],
                ['id_city' => 9562, 'id_state' => 25, 'name' => ' Santa Salete'],
                ['id_city' => 9563, 'id_state' => 25, 'name' => ' Santana da Ponte Pensa'],
                ['id_city' => 9564, 'id_state' => 25, 'name' => ' Santana de Parnaíba'],
                ['id_city' => 9565, 'id_state' => 25, 'name' => ' Santelmo'],
                ['id_city' => 9566, 'id_state' => 25, 'name' => ' Santo Anastácio'],
                ['id_city' => 9567, 'id_state' => 25, 'name' => ' Santo André'],
                ['id_city' => 9568, 'id_state' => 25, 'name' => ' Santo Antônio da Alegria'],
                ['id_city' => 9569, 'id_state' => 25, 'name' => ' Santo Antônio da Estiva'],
                ['id_city' => 9570, 'id_state' => 25, 'name' => ' Santo Antônio de Posse'],
                ['id_city' => 9571, 'id_state' => 25, 'name' => ' Santo Antônio do Aracanguá'],
                ['id_city' => 9572, 'id_state' => 25, 'name' => ' Santo Antônio do Jardim'],
                ['id_city' => 9573, 'id_state' => 25, 'name' => ' Santo Antônio do Paranapanema'],
                ['id_city' => 9574, 'id_state' => 25, 'name' => ' Santo Antônio do Pinhal'],
                ['id_city' => 9575, 'id_state' => 25, 'name' => ' Santo Antônio Paulista'],
                ['id_city' => 9576, 'id_state' => 25, 'name' => ' Santo Expedito'],
                ['id_city' => 9577, 'id_state' => 25, 'name' => ' Santópolis do Aguapeí'],
                ['id_city' => 9578, 'id_state' => 25, 'name' => ' Santos'],
                ['id_city' => 9579, 'id_state' => 25, 'name' => ' São Benedito da Cachoeirinha'],
                ['id_city' => 9580, 'id_state' => 25, 'name' => ' São Benedito das Areias'],
                ['id_city' => 9581, 'id_state' => 25, 'name' => ' São Bento do Sapucaí'],
                ['id_city' => 9582, 'id_state' => 25, 'name' => ' São Bernardo do Campo'],
                ['id_city' => 9583, 'id_state' => 25, 'name' => ' São Berto'],
                ['id_city' => 9584, 'id_state' => 25, 'name' => ' São Caetano do Sul'],
                ['id_city' => 9585, 'id_state' => 25, 'name' => ' São Carlos'],
                ['id_city' => 9586, 'id_state' => 25, 'name' => ' São Francisco'],
                ['id_city' => 9587, 'id_state' => 25, 'name' => ' São Francisco da Praia'],
                ['id_city' => 9588, 'id_state' => 25, 'name' => ' São Francisco Xavier'],
                ['id_city' => 9589, 'id_state' => 25, 'name' => ' São João da Boa Vista'],
                ['id_city' => 9590, 'id_state' => 25, 'name' => ' São João das Duas Pontes'],
                ['id_city' => 9591, 'id_state' => 25, 'name' => ' São João de Iracema'],
                ['id_city' => 9592, 'id_state' => 25, 'name' => ' São João de Itaguaçu'],
                ['id_city' => 9593, 'id_state' => 25, 'name' => ' São João do Marinheiro'],
                ['id_city' => 9594, 'id_state' => 25, 'name' => ' São João do Pau d Alho'],
                ['id_city' => 9595, 'id_state' => 25, 'name' => ' São João Novo'],
                ['id_city' => 9596, 'id_state' => 25, 'name' => ' São Joaquim da Barra'],
                ['id_city' => 9597, 'id_state' => 25, 'name' => ' São José da Bela Vista'],
                ['id_city' => 9598, 'id_state' => 25, 'name' => ' São José das Laranjeiras'],
                ['id_city' => 9599, 'id_state' => 25, 'name' => ' São José do Barreiro'],
                ['id_city' => 9600, 'id_state' => 25, 'name' => ' São José do Rio Pardo'],
                ['id_city' => 9601, 'id_state' => 25, 'name' => ' São José do Rio Preto'],
                ['id_city' => 9602, 'id_state' => 25, 'name' => ' São José dos Campos'],
                ['id_city' => 9603, 'id_state' => 25, 'name' => ' São Lourenço da Serra'],
                ['id_city' => 9604, 'id_state' => 25, 'name' => ' São Lourenço do Turvo'],
                ['id_city' => 9605, 'id_state' => 25, 'name' => ' São Luiz do Paraitinga'],
                ['id_city' => 9606, 'id_state' => 25, 'name' => ' São Luiz do Guaricanga'],
                ['id_city' => 9607, 'id_state' => 25, 'name' => ' São Manuel'],
                ['id_city' => 9608, 'id_state' => 25, 'name' => ' São Martinho D Oeste'],
                ['id_city' => 9609, 'id_state' => 25, 'name' => ' São Miguel Arcanjo'],
                ['id_city' => 9610, 'id_state' => 25, 'name' => ' São Paulo'],
                ['id_city' => 9611, 'id_state' => 25, 'name' => ' São Pedro'],
                ['id_city' => 9612, 'id_state' => 25, 'name' => ' São Pedro do Turvo'],
                ['id_city' => 9613, 'id_state' => 25, 'name' => ' São Roque'],
                ['id_city' => 9614, 'id_state' => 25, 'name' => ' São Roque da Fartura'],
                ['id_city' => 9615, 'id_state' => 25, 'name' => ' São Sebastião'],
                ['id_city' => 9616, 'id_state' => 25, 'name' => ' São Sebastião da Grama'],
                ['id_city' => 9617, 'id_state' => 25, 'name' => ' São Sebastião da Serra'],
                ['id_city' => 9618, 'id_state' => 25, 'name' => ' São Silvestre de Jacareí'],
                ['id_city' => 9619, 'id_state' => 25, 'name' => ' São Simão'],
                ['id_city' => 9620, 'id_state' => 25, 'name' => ' São Vicente'],
                ['id_city' => 9621, 'id_state' => 25, 'name' => ' Sapezal'],
                ['id_city' => 9622, 'id_state' => 25, 'name' => ' Sarapuí'],
                ['id_city' => 9623, 'id_state' => 25, 'name' => ' Sarutaiá'],
                ['id_city' => 9624, 'id_state' => 25, 'name' => ' Sebastianópolis do Sul'],
                ['id_city' => 9625, 'id_state' => 25, 'name' => ' Serra Azul'],
                ['id_city' => 9626, 'id_state' => 25, 'name' => ' Serra Negra'],
                ['id_city' => 9627, 'id_state' => 25, 'name' => ' Serrana'],
                ['id_city' => 9628, 'id_state' => 25, 'name' => ' Sertãozinho'],
                ['id_city' => 9629, 'id_state' => 25, 'name' => ' Sete Barras'],
                ['id_city' => 9630, 'id_state' => 25, 'name' => ' Severínia'],
                ['id_city' => 9631, 'id_state' => 25, 'name' => ' Silvânia'],
                ['id_city' => 9632, 'id_state' => 25, 'name' => ' Silveiras'],
                ['id_city' => 9633, 'id_state' => 25, 'name' => ' Simões'],
                ['id_city' => 9634, 'id_state' => 25, 'name' => ' Simonsen'],
                ['id_city' => 9635, 'id_state' => 25, 'name' => ' Socorro'],
                ['id_city' => 9636, 'id_state' => 25, 'name' => ' Sodrélia'],
                ['id_city' => 9637, 'id_state' => 25, 'name' => ' Solemar'],
                ['id_city' => 9638, 'id_state' => 25, 'name' => ' Sorocaba'],
                ['id_city' => 9639, 'id_state' => 25, 'name' => ' Sousas'],
                ['id_city' => 9640, 'id_state' => 25, 'name' => ' Sud Mennucci'],
                ['id_city' => 9641, 'id_state' => 25, 'name' => ' Suinana'],
                ['id_city' => 9642, 'id_state' => 25, 'name' => ' Sumaré'],
                ['id_city' => 9643, 'id_state' => 25, 'name' => ' Sussui'],
                ['id_city' => 9644, 'id_state' => 25, 'name' => ' Suzanápolis'],
                ['id_city' => 9645, 'id_state' => 25, 'name' => ' Suzano'],
                ['id_city' => 9646, 'id_state' => 25, 'name' => ' Tabajara'],
                ['id_city' => 9647, 'id_state' => 25, 'name' => ' Tabapuã'],
                ['id_city' => 9648, 'id_state' => 25, 'name' => ' Tabatinga'],
                ['id_city' => 9649, 'id_state' => 25, 'name' => ' Taboão da Serra'],
                ['id_city' => 9650, 'id_state' => 25, 'name' => ' Taciba'],
                ['id_city' => 9651, 'id_state' => 25, 'name' => ' Taguaí'],
                ['id_city' => 9652, 'id_state' => 25, 'name' => ' Taiaçu'],
                ['id_city' => 9653, 'id_state' => 25, 'name' => ' Taiacupeba'],
                ['id_city' => 9654, 'id_state' => 25, 'name' => ' Taiúva'],
                ['id_city' => 9655, 'id_state' => 25, 'name' => ' Talhado'],
                ['id_city' => 9656, 'id_state' => 25, 'name' => ' Tambaú'],
                ['id_city' => 9657, 'id_state' => 25, 'name' => ' Tanabi'],
                ['id_city' => 9658, 'id_state' => 25, 'name' => ' Tapinas'],
                ['id_city' => 9659, 'id_state' => 25, 'name' => ' Tapiraí'],
                ['id_city' => 9660, 'id_state' => 25, 'name' => ' Tapiratiba'],
                ['id_city' => 9661, 'id_state' => 25, 'name' => ' Taquaral'],
                ['id_city' => 9662, 'id_state' => 25, 'name' => ' Taquaritinga'],
                ['id_city' => 9663, 'id_state' => 25, 'name' => ' Taquarituba'],
                ['id_city' => 9664, 'id_state' => 25, 'name' => ' Taquarivaí'],
                ['id_city' => 9665, 'id_state' => 25, 'name' => ' Tarabai'],
                ['id_city' => 9666, 'id_state' => 25, 'name' => ' Tarumã'],
                ['id_city' => 9667, 'id_state' => 25, 'name' => ' Tatuí'],
                ['id_city' => 9668, 'id_state' => 25, 'name' => ' Taubaté'],
                ['id_city' => 9669, 'id_state' => 25, 'name' => ' Tecainda'],
                ['id_city' => 9670, 'id_state' => 25, 'name' => ' Tejupá'],
                ['id_city' => 9671, 'id_state' => 25, 'name' => ' Teodoro Sampaio'],
                ['id_city' => 9672, 'id_state' => 25, 'name' => ' Termas de Ibirá'],
                ['id_city' => 9673, 'id_state' => 25, 'name' => ' Terra Nova D Oeste'],
                ['id_city' => 9674, 'id_state' => 25, 'name' => ' Terra Roxa'],
                ['id_city' => 9675, 'id_state' => 25, 'name' => ' Tibiriçá'],
                ['id_city' => 9676, 'id_state' => 25, 'name' => ' Tibiriçá do Paranapanema'],
                ['id_city' => 9677, 'id_state' => 25, 'name' => ' Tietê'],
                ['id_city' => 9678, 'id_state' => 25, 'name' => ' Timburi'],
                ['id_city' => 9679, 'id_state' => 25, 'name' => ' Toledo'],
                ['id_city' => 9680, 'id_state' => 25, 'name' => ' Torre de Pedra'],
                ['id_city' => 9681, 'id_state' => 25, 'name' => ' Torrinha'],
                ['id_city' => 9682, 'id_state' => 25, 'name' => ' Trabiju'],
                ['id_city' => 9683, 'id_state' => 25, 'name' => ' Tremembé'],
                ['id_city' => 9684, 'id_state' => 25, 'name' => ' Três Alianças'],
                ['id_city' => 9685, 'id_state' => 25, 'name' => ' Três Fronteiras'],
                ['id_city' => 9686, 'id_state' => 25, 'name' => ' Três Pontes'],
                ['id_city' => 9687, 'id_state' => 25, 'name' => ' Tuiuti'],
                ['id_city' => 9688, 'id_state' => 25, 'name' => ' Tujuguaba'],
                ['id_city' => 9689, 'id_state' => 25, 'name' => ' Tupã'],
                ['id_city' => 9690, 'id_state' => 25, 'name' => ' Tupi'],
                ['id_city' => 9691, 'id_state' => 25, 'name' => ' Tupi Paulista'],
                ['id_city' => 9692, 'id_state' => 25, 'name' => ' Turiba do Sul'],
                ['id_city' => 9693, 'id_state' => 25, 'name' => ' Turiúba'],
                ['id_city' => 9694, 'id_state' => 25, 'name' => ' Turmalina'],
                ['id_city' => 9695, 'id_state' => 25, 'name' => ' Turvínia'],
                ['id_city' => 9696, 'id_state' => 25, 'name' => ' Ubarana'],
                ['id_city' => 9697, 'id_state' => 25, 'name' => ' Ubatuba'],
                ['id_city' => 9698, 'id_state' => 25, 'name' => ' Ubirajara'],
                ['id_city' => 9699, 'id_state' => 25, 'name' => ' Uchoa'],
                ['id_city' => 9700, 'id_state' => 25, 'name' => ' União Paulista'],
                ['id_city' => 9701, 'id_state' => 25, 'name' => ' Universo'],
                ['id_city' => 9702, 'id_state' => 25, 'name' => ' Urânia'],
                ['id_city' => 9703, 'id_state' => 25, 'name' => ' Uru'],
                ['id_city' => 9704, 'id_state' => 25, 'name' => ' Urupês'],
                ['id_city' => 9705, 'id_state' => 25, 'name' => ' Ururai'],
                ['id_city' => 9706, 'id_state' => 25, 'name' => ' Utinga'],
                ['id_city' => 9707, 'id_state' => 25, 'name' => ' Vale Formoso'],
                ['id_city' => 9708, 'id_state' => 25, 'name' => ' Valentim Gentil'],
                ['id_city' => 9709, 'id_state' => 25, 'name' => ' Valinhos'],
                ['id_city' => 9710, 'id_state' => 25, 'name' => ' Valparaíso'],
                ['id_city' => 9711, 'id_state' => 25, 'name' => ' Vanglória'],
                ['id_city' => 9712, 'id_state' => 25, 'name' => ' Vargem'],
                ['id_city' => 9713, 'id_state' => 25, 'name' => ' Vargem Grande do Sul'],
                ['id_city' => 9714, 'id_state' => 25, 'name' => ' Vargem Grande Paulista'],
                ['id_city' => 9715, 'id_state' => 25, 'name' => ' Varpa'],
                ['id_city' => 9716, 'id_state' => 25, 'name' => ' Várzea Paulista'],
                ['id_city' => 9717, 'id_state' => 25, 'name' => ' Venda Branca'],
                ['id_city' => 9718, 'id_state' => 25, 'name' => ' Vera Cruz'],
                ['id_city' => 9719, 'id_state' => 25, 'name' => ' Vicente de Carvalho'],
                ['id_city' => 9720, 'id_state' => 25, 'name' => ' Vicentinópolis'],
                ['id_city' => 9721, 'id_state' => 25, 'name' => ' Vila Dirce'],
                ['id_city' => 9722, 'id_state' => 25, 'name' => ' Vila Nery'],
                ['id_city' => 9723, 'id_state' => 25, 'name' => ' Vila Xavier'],
                ['id_city' => 9724, 'id_state' => 25, 'name' => ' Vinhedo'],
                ['id_city' => 9725, 'id_state' => 25, 'name' => ' Viradouro'],
                ['id_city' => 9726, 'id_state' => 25, 'name' => ' Vista Alegre do Alto'],
                ['id_city' => 9727, 'id_state' => 25, 'name' => ' Vitória Brasil'],
                ['id_city' => 9728, 'id_state' => 25, 'name' => ' Vitoriana'],
                ['id_city' => 9729, 'id_state' => 25, 'name' => ' Votorantim'],
                ['id_city' => 9730, 'id_state' => 25, 'name' => ' Votuporanga'],
                ['id_city' => 9731, 'id_state' => 25, 'name' => ' Zacarias'],
                ['id_city' => 9732, 'id_state' => 27, 'name' => ' Abreulândia'],
                ['id_city' => 9733, 'id_state' => 27, 'name' => ' Aguiarnópolis'],
                ['id_city' => 9734, 'id_state' => 27, 'name' => ' Aliança do Tocantins'],
                ['id_city' => 9735, 'id_state' => 27, 'name' => ' Almas'],
                ['id_city' => 9736, 'id_state' => 27, 'name' => ' Alvorada'],
                ['id_city' => 9737, 'id_state' => 27, 'name' => ' Anajanópolis'],
                ['id_city' => 9738, 'id_state' => 27, 'name' => ' Ananás'],
                ['id_city' => 9739, 'id_state' => 27, 'name' => ' Angico'],
                ['id_city' => 9740, 'id_state' => 27, 'name' => ' Aparecida do Rio Negro'],
                ['id_city' => 9741, 'id_state' => 27, 'name' => ' Apinajé'],
                ['id_city' => 9742, 'id_state' => 27, 'name' => ' Aragaçuí'],
                ['id_city' => 9743, 'id_state' => 27, 'name' => ' Aragominas'],
                ['id_city' => 9744, 'id_state' => 27, 'name' => ' Araguacema'],
                ['id_city' => 9745, 'id_state' => 27, 'name' => ' Araguaçu'],
                ['id_city' => 9746, 'id_state' => 27, 'name' => ' Araguaína'],
                ['id_city' => 9747, 'id_state' => 27, 'name' => ' Araguanã'],
                ['id_city' => 9748, 'id_state' => 27, 'name' => ' Araguatins'],
                ['id_city' => 9749, 'id_state' => 27, 'name' => ' Arapoema'],
                ['id_city' => 9750, 'id_state' => 27, 'name' => ' Arraias'],
                ['id_city' => 9751, 'id_state' => 27, 'name' => ' Augustinópolis'],
                ['id_city' => 9752, 'id_state' => 27, 'name' => ' Aurora do Tocantins'],
                ['id_city' => 9753, 'id_state' => 27, 'name' => ' Axixá do Tocantins'],
                ['id_city' => 9754, 'id_state' => 27, 'name' => ' Babaçulândia'],
                ['id_city' => 9755, 'id_state' => 27, 'name' => ' Bandeirantes do Tocantins'],
                ['id_city' => 9756, 'id_state' => 27, 'name' => ' Barra do Grota'],
                ['id_city' => 9757, 'id_state' => 27, 'name' => ' Barra do Ouro'],
                ['id_city' => 9758, 'id_state' => 27, 'name' => ' Barrolândia'],
                ['id_city' => 9759, 'id_state' => 27, 'name' => ' Bernardo Sayão'],
                ['id_city' => 9760, 'id_state' => 27, 'name' => ' Bom Jesus do Tocantins'],
                ['id_city' => 9761, 'id_state' => 27, 'name' => ' Brasilândia'],
                ['id_city' => 9762, 'id_state' => 27, 'name' => ' Brasilândia do Tocantins'],
                ['id_city' => 9763, 'id_state' => 27, 'name' => ' Brejinho de Nazaré'],
                ['id_city' => 9764, 'id_state' => 27, 'name' => ' Buriti do Tocantins'],
                ['id_city' => 9765, 'id_state' => 27, 'name' => ' Cachoeirinha'],
                ['id_city' => 9766, 'id_state' => 27, 'name' => ' Campos Lindos'],
                ['id_city' => 9767, 'id_state' => 27, 'name' => ' Cana Brava'],
                ['id_city' => 9768, 'id_state' => 27, 'name' => ' Cariri do Tocantins'],
                ['id_city' => 9769, 'id_state' => 27, 'name' => ' Carmolândia'],
                ['id_city' => 9770, 'id_state' => 27, 'name' => ' Carrasco Bonito'],
                ['id_city' => 9771, 'id_state' => 27, 'name' => ' Cartucho'],
                ['id_city' => 9772, 'id_state' => 27, 'name' => ' Caseara'],
                ['id_city' => 9773, 'id_state' => 27, 'name' => ' Centenário'],
                ['id_city' => 9774, 'id_state' => 27, 'name' => ' Chapada de Areia'],
                ['id_city' => 9775, 'id_state' => 27, 'name' => ' Chapada da Natividade'],
                ['id_city' => 9776, 'id_state' => 27, 'name' => ' Cocalândia'],
                ['id_city' => 9777, 'id_state' => 27, 'name' => ' Cocalinho'],
                ['id_city' => 9778, 'id_state' => 27, 'name' => ' Colinas do Tocantins'],
                ['id_city' => 9779, 'id_state' => 27, 'name' => ' Colméia'],
                ['id_city' => 9780, 'id_state' => 27, 'name' => ' Combinado'],
                ['id_city' => 9781, 'id_state' => 27, 'name' => ' Conceição do Tocantins'],
                ['id_city' => 9782, 'id_state' => 27, 'name' => ' Correinha'],
                ['id_city' => 9783, 'id_state' => 27, 'name' => ' Couto de Magalhães'],
                ['id_city' => 9784, 'id_state' => 27, 'name' => ' Craolândia'],
                ['id_city' => 9785, 'id_state' => 27, 'name' => ' Cristalândia'],
                ['id_city' => 9786, 'id_state' => 27, 'name' => ' Crixás'],
                ['id_city' => 9787, 'id_state' => 27, 'name' => ' Crixás do Tocantins'],
                ['id_city' => 9788, 'id_state' => 27, 'name' => ' Darcinópolis'],
                ['id_city' => 9789, 'id_state' => 27, 'name' => ' Dianópolis'],
                ['id_city' => 9790, 'id_state' => 27, 'name' => ' Divinópolis do Tocantins'],
                ['id_city' => 9791, 'id_state' => 27, 'name' => ' Dois Irmãos do Tocantins'],
                ['id_city' => 9792, 'id_state' => 27, 'name' => ' Duerê'],
                ['id_city' => 9793, 'id_state' => 27, 'name' => ' Escondido'],
                ['id_city' => 9794, 'id_state' => 27, 'name' => ' Esperantina'],
                ['id_city' => 9795, 'id_state' => 27, 'name' => ' Fátima'],
                ['id_city' => 9796, 'id_state' => 27, 'name' => ' Figueirópolis'],
                ['id_city' => 9797, 'id_state' => 27, 'name' => ' Filadélfia'],
                ['id_city' => 9798, 'id_state' => 27, 'name' => ' Formoso do Araguaia'],
                ['id_city' => 9799, 'id_state' => 27, 'name' => ' Fortaleza do Tabocão'],
                ['id_city' => 9800, 'id_state' => 27, 'name' => ' Goianorte'],
                ['id_city' => 9801, 'id_state' => 27, 'name' => ' Goiatins'],
                ['id_city' => 9802, 'id_state' => 27, 'name' => ' Guaraí'],
                ['id_city' => 9803, 'id_state' => 27, 'name' => ' Gurupi'],
                ['id_city' => 9804, 'id_state' => 27, 'name' => ' Ilha Barreira Branca'],
                ['id_city' => 9805, 'id_state' => 27, 'name' => ' Ipueiras'],
                ['id_city' => 9806, 'id_state' => 27, 'name' => ' Itacajá'],
                ['id_city' => 9807, 'id_state' => 27, 'name' => ' Itaguatins'],
                ['id_city' => 9808, 'id_state' => 27, 'name' => ' Itapiratins'],
                ['id_city' => 9809, 'id_state' => 27, 'name' => ' Itaporã do Tocantins'],
                ['id_city' => 9810, 'id_state' => 27, 'name' => ' Jaú do Tocantins'],
                ['id_city' => 9811, 'id_state' => 27, 'name' => ' Juarina'],
                ['id_city' => 9812, 'id_state' => 27, 'name' => ' Jussara'],
                ['id_city' => 9813, 'id_state' => 27, 'name' => ' Lagoa da Confusão'],
                ['id_city' => 9814, 'id_state' => 27, 'name' => ' Lagoa do Tocantins'],
                ['id_city' => 9815, 'id_state' => 27, 'name' => ' Lajeado'],
                ['id_city' => 9816, 'id_state' => 27, 'name' => ' Lavandeira'],
                ['id_city' => 9817, 'id_state' => 27, 'name' => ' Lizarda'],
                ['id_city' => 9818, 'id_state' => 27, 'name' => ' Luzinópolis'],
                ['id_city' => 9819, 'id_state' => 27, 'name' => ' Marianópolis do Tocantins'],
                ['id_city' => 9820, 'id_state' => 27, 'name' => ' Mateiros'],
                ['id_city' => 9821, 'id_state' => 27, 'name' => ' Maurilândia do Tocantins'],
                ['id_city' => 9822, 'id_state' => 27, 'name' => ' Miracema do Tocantins'],
                ['id_city' => 9823, 'id_state' => 27, 'name' => ' Mirandópolis'],
                ['id_city' => 9824, 'id_state' => 27, 'name' => ' Miranorte'],
                ['id_city' => 9825, 'id_state' => 27, 'name' => ' Monte do Carmo'],
                ['id_city' => 9826, 'id_state' => 27, 'name' => ' Monte Lindo'],
                ['id_city' => 9827, 'id_state' => 27, 'name' => ' Monte Santo do Tocantins'],
                ['id_city' => 9828, 'id_state' => 27, 'name' => ' Palmeiras do Tocantins'],
                ['id_city' => 9829, 'id_state' => 27, 'name' => ' Muricilândia'],
                ['id_city' => 9830, 'id_state' => 27, 'name' => ' Natal'],
                ['id_city' => 9831, 'id_state' => 27, 'name' => ' Natividade'],
                ['id_city' => 9832, 'id_state' => 27, 'name' => ' Nazaré'],
                ['id_city' => 9833, 'id_state' => 27, 'name' => ' Nova Olinda'],
                ['id_city' => 9834, 'id_state' => 27, 'name' => ' Nova Rosalândia'],
                ['id_city' => 9835, 'id_state' => 27, 'name' => ' Novo Acordo'],
                ['id_city' => 9836, 'id_state' => 27, 'name' => ' Novo Alegre'],
                ['id_city' => 9837, 'id_state' => 27, 'name' => ' Novo Horizonte'],
                ['id_city' => 9838, 'id_state' => 27, 'name' => ' Novo Jardim'],
                ['id_city' => 9839, 'id_state' => 27, 'name' => ' Oliveira de Fátima'],
                ['id_city' => 9840, 'id_state' => 27, 'name' => ' Palmas'],
                ['id_city' => 9841, 'id_state' => 27, 'name' => ' Palmeirante'],
                ['id_city' => 9842, 'id_state' => 27, 'name' => ' Palmeirópolis'],
                ['id_city' => 9843, 'id_state' => 27, 'name' => ' Paraíso do Tocantins'],
                ['id_city' => 9844, 'id_state' => 27, 'name' => ' Paranã'],
                ['id_city' => 9845, 'id_state' => 27, 'name' => ' Pau D Arco'],
                ['id_city' => 9846, 'id_state' => 27, 'name' => ' Pé da Serra'],
                ['id_city' => 9847, 'id_state' => 27, 'name' => ' Pedro Afonso'],
                ['id_city' => 9848, 'id_state' => 27, 'name' => ' Pedro Ludovico'],
                ['id_city' => 9849, 'id_state' => 27, 'name' => ' Peixe'],
                ['id_city' => 9850, 'id_state' => 27, 'name' => ' Pequizeiro'],
                ['id_city' => 9851, 'id_state' => 27, 'name' => ' Pilões'],
                ['id_city' => 9852, 'id_state' => 27, 'name' => ' Pindorama do Tocantins'],
                ['id_city' => 9853, 'id_state' => 27, 'name' => ' Piraquê'],
                ['id_city' => 9854, 'id_state' => 27, 'name' => ' Pium'],
                ['id_city' => 9855, 'id_state' => 27, 'name' => ' Ponte Alta do Bom Jesus'],
                ['id_city' => 9856, 'id_state' => 27, 'name' => ' Ponte Alta do Tocantins'],
                ['id_city' => 9857, 'id_state' => 27, 'name' => ' Pontes'],
                ['id_city' => 9858, 'id_state' => 27, 'name' => ' Porãozinho'],
                ['id_city' => 9859, 'id_state' => 27, 'name' => ' Porto Alegre do Tocantins'],
                ['id_city' => 9860, 'id_state' => 27, 'name' => ' Porto Lemos'],
                ['id_city' => 9861, 'id_state' => 27, 'name' => ' Porto Nacional'],
                ['id_city' => 9862, 'id_state' => 27, 'name' => ' Praia Norte'],
                ['id_city' => 9863, 'id_state' => 27, 'name' => ' Presidente Kennedy'],
                ['id_city' => 9864, 'id_state' => 27, 'name' => ' Príncipe'],
                ['id_city' => 9865, 'id_state' => 27, 'name' => ' Pugmil'],
                ['id_city' => 9866, 'id_state' => 27, 'name' => ' Recursolândia'],
                ['id_city' => 9867, 'id_state' => 27, 'name' => ' Riachinho'],
                ['id_city' => 9868, 'id_state' => 27, 'name' => ' Rio da Conceição'],
                ['id_city' => 9869, 'id_state' => 27, 'name' => ' Rio dos Bois'],
                ['id_city' => 9870, 'id_state' => 27, 'name' => ' Rio Sono'],
                ['id_city' => 9871, 'id_state' => 27, 'name' => ' Sampaio'],
                ['id_city' => 9872, 'id_state' => 27, 'name' => ' Sandolândia'],
                ['id_city' => 9873, 'id_state' => 27, 'name' => ' Santa Fé do Araguaia'],
                ['id_city' => 9874, 'id_state' => 27, 'name' => ' Santa Maria do Tocantins'],
                ['id_city' => 9875, 'id_state' => 27, 'name' => ' Santa Rita do Tocantins'],
                ['id_city' => 9876, 'id_state' => 27, 'name' => ' Santa Rosa do Tocantins'],
                ['id_city' => 9877, 'id_state' => 27, 'name' => ' Santa Tereza do Tocantins'],
                ['id_city' => 9878, 'id_state' => 27, 'name' => ' Santa Terezinha do Tocantins'],
                ['id_city' => 9879, 'id_state' => 27, 'name' => ' São Bento do Tocantins'],
                ['id_city' => 9880, 'id_state' => 27, 'name' => ' São Félix do Tocantins'],
                ['id_city' => 9881, 'id_state' => 27, 'name' => ' São Miguel do Tocantins'],
                ['id_city' => 9882, 'id_state' => 27, 'name' => ' São Salvador do Tocantins'],
                ['id_city' => 9883, 'id_state' => 27, 'name' => ' São Sebastião do Tocantins'],
                ['id_city' => 9884, 'id_state' => 27, 'name' => ' São Valério da Natividade'],
                ['id_city' => 9885, 'id_state' => 27, 'name' => ' Silvanópolis'],
                ['id_city' => 9886, 'id_state' => 27, 'name' => ' Sítio Novo do Tocantins'],
                ['id_city' => 9887, 'id_state' => 27, 'name' => ' Sucupira'],
                ['id_city' => 9888, 'id_state' => 27, 'name' => ' Taguatinga'],
                ['id_city' => 9889, 'id_state' => 27, 'name' => ' Taipas do Tocantins'],
                ['id_city' => 9890, 'id_state' => 27, 'name' => ' Talismã'],
                ['id_city' => 9891, 'id_state' => 27, 'name' => ' Tamboril'],
                ['id_city' => 9892, 'id_state' => 27, 'name' => ' Taquaralto'],
                ['id_city' => 9893, 'id_state' => 27, 'name' => ' Taquarussu do Tocantins'],
                ['id_city' => 9894, 'id_state' => 27, 'name' => ' Tocantínia'],
                ['id_city' => 9895, 'id_state' => 27, 'name' => ' Tocantinópolis'],
                ['id_city' => 9896, 'id_state' => 27, 'name' => ' Tupirama'],
                ['id_city' => 9897, 'id_state' => 27, 'name' => ' Tupiratã'],
                ['id_city' => 9898, 'id_state' => 27, 'name' => ' Tupiratins'],
                ['id_city' => 9899, 'id_state' => 27, 'name' => ' Vênus'],
                ['id_city' => 9900, 'id_state' => 27, 'name' => ' Wanderlândia'],
                ['id_city' => 9901, 'id_state' => 27, 'name' => ' Xambioá'],
                ['id_city' => 9902, 'id_state' => 2, 'name' => ' Jequiá da Praia'],
                ['id_city' => 9903, 'id_state' => 9, 'name' => ' Ipiranga de Goiás'],
                ['id_city' => 9904, 'id_state' => 11, 'name' => ' Conquista D Oeste'],
                ['id_city' => 9905, 'id_state' => 11, 'name' => ' Colniza'],
                ['id_city' => 9906, 'id_state' => 11, 'name' => ' Rondolândia'],
                ['id_city' => 9907, 'id_state' => 11, 'name' => ' Santa Rita do Trivelato'],
                ['id_city' => 9908, 'id_state' => 11, 'name' => ' Nova Santa Helena'],
                ['id_city' => 9909, 'id_state' => 11, 'name' => ' Santo Antônio do Leste'],
                ['id_city' => 9910, 'id_state' => 11, 'name' => ' Nova Nazaré'],
                ['id_city' => 9911, 'id_state' => 11, 'name' => ' Santa Cruz do Xingu'],
                ['id_city' => 9912, 'id_state' => 11, 'name' => ' Bom Jesus do Araguaia'],
                ['id_city' => 9913, 'id_state' => 18, 'name' => ' Pau D Arco do Piauí'],
                ['id_city' => 9914, 'id_state' => 21, 'name' => ' Westfalia'],
                ['id_city' => 9915, 'id_state' => 21, 'name' => ' Santa Margarida do Sul'],
                ['id_city' => 9916, 'id_state' => 21, 'name' => ' Tio Hugo'],
                ['id_city' => 9917, 'id_state' => 6, 'name' => ' Canaúna'],
                ['id_city' => 9918, 'id_state' => 8, 'name' => ' São João do Norte'],
                ['id_city' => 9919, 'id_state' => 8, 'name' => ' São Raimundo da Pedra Menina'],
                ['id_city' => 9920, 'id_state' => 8, 'name' => ' Santa Cruz de Irupi'],
                ['id_city' => 9921, 'id_state' => 8, 'name' => ' São João do Príncipe'],
                ['id_city' => 9922, 'id_state' => 8, 'name' => ' Nossa Senhora de Fátima'],
                ['id_city' => 9923, 'id_state' => 8, 'name' => ' Santa Maria de Marechal'],
                ['id_city' => 9924, 'id_state' => 8, 'name' => ' Alto Castelinho'],
                ['id_city' => 9925, 'id_state' => 8, 'name' => ' Prosperidade'],
                ['id_city' => 9926, 'id_state' => 8, 'name' => ' São José de Fruteiras'],
            ]);
        }
}