<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities7 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        DB::table('vpr_countries_states_cities')->insert([
            ['id_city' => 4140, 'id_state' => 13, 'name' => ' Silvestre'],
            ['id_city' => 4141, 'id_state' => 13, 'name' => ' Silvianópolis'],
            ['id_city' => 4142, 'id_state' => 13, 'name' => ' Simão Campos'],
            ['id_city' => 4143, 'id_state' => 13, 'name' => ' Simão Pereira'],
            ['id_city' => 4144, 'id_state' => 13, 'name' => ' Simonésia'],
            ['id_city' => 4145, 'id_state' => 13, 'name' => ' Sobral Pinto'],
            ['id_city' => 4146, 'id_state' => 13, 'name' => ' Sobrália'],
            ['id_city' => 4147, 'id_state' => 13, 'name' => ' Soledade de Minas'],
            ['id_city' => 4148, 'id_state' => 13, 'name' => ' Sopa'],
            ['id_city' => 4149, 'id_state' => 13, 'name' => ' Tabajara'],
            ['id_city' => 4150, 'id_state' => 13, 'name' => ' Tabaúna'],
            ['id_city' => 4151, 'id_state' => 13, 'name' => ' Tabuão'],
            ['id_city' => 4152, 'id_state' => 13, 'name' => ' Tabuleiro'],
            ['id_city' => 4153, 'id_state' => 13, 'name' => ' Taiobeiras'],
            ['id_city' => 4154, 'id_state' => 13, 'name' => ' Taparuba'],
            ['id_city' => 4155, 'id_state' => 13, 'name' => ' Tapira'],
            ['id_city' => 4156, 'id_state' => 13, 'name' => ' Tapiraí'],
            ['id_city' => 4157, 'id_state' => 13, 'name' => ' Tapuirama'],
            ['id_city' => 4158, 'id_state' => 13, 'name' => ' Taquaraçu de Minas'],
            ['id_city' => 4159, 'id_state' => 13, 'name' => ' Taruaçu'],
            ['id_city' => 4160, 'id_state' => 13, 'name' => ' Tarumirim'],
            ['id_city' => 4161, 'id_state' => 13, 'name' => ' Tebas'],
            ['id_city' => 4162, 'id_state' => 13, 'name' => ' Teixeiras'],
            ['id_city' => 4163, 'id_state' => 13, 'name' => ' Tejuco'],
            ['id_city' => 4164, 'id_state' => 13, 'name' => ' Teófilo Otoni'],
            ['id_city' => 4165, 'id_state' => 13, 'name' => ' Terra Branca'],
            ['id_city' => 4166, 'id_state' => 13, 'name' => ' Timóteo'],
            ['id_city' => 4167, 'id_state' => 13, 'name' => ' Tiradentes'],
            ['id_city' => 4168, 'id_state' => 13, 'name' => ' Tiros'],
            ['id_city' => 4169, 'id_state' => 13, 'name' => ' Tobati'],
            ['id_city' => 4170, 'id_state' => 13, 'name' => ' Tocandira'],
            ['id_city' => 4171, 'id_state' => 13, 'name' => ' Tocantins'],
            ['id_city' => 4172, 'id_state' => 13, 'name' => ' Tocos do Moji'],
            ['id_city' => 4173, 'id_state' => 13, 'name' => ' Toledo'],
            ['id_city' => 4174, 'id_state' => 13, 'name' => ' Tomás Gonzaga'],
            ['id_city' => 4175, 'id_state' => 13, 'name' => ' Tombos'],
            ['id_city' => 4176, 'id_state' => 13, 'name' => ' Topázio'],
            ['id_city' => 4177, 'id_state' => 13, 'name' => ' Torneiros'],
            ['id_city' => 4178, 'id_state' => 13, 'name' => ' Torreões'],
            ['id_city' => 4179, 'id_state' => 13, 'name' => ' Três Corações'],
            ['id_city' => 4180, 'id_state' => 13, 'name' => ' Três Ilhas'],
            ['id_city' => 4181, 'id_state' => 13, 'name' => ' Três Marias'],
            ['id_city' => 4182, 'id_state' => 13, 'name' => ' Três Pontas'],
            ['id_city' => 4183, 'id_state' => 13, 'name' => ' Trimonte'],
            ['id_city' => 4184, 'id_state' => 13, 'name' => ' Tuiutinga'],
            ['id_city' => 4185, 'id_state' => 13, 'name' => ' Tumiritinga'],
            ['id_city' => 4186, 'id_state' => 13, 'name' => ' Tupaciguara'],
            ['id_city' => 4187, 'id_state' => 13, 'name' => ' Tuparecê'],
            ['id_city' => 4188, 'id_state' => 13, 'name' => ' Turmalina'],
            ['id_city' => 4189, 'id_state' => 13, 'name' => ' Turvolândia'],
            ['id_city' => 4190, 'id_state' => 13, 'name' => ' Ubá'],
            ['id_city' => 4191, 'id_state' => 13, 'name' => ' Ubaí'],
            ['id_city' => 4192, 'id_state' => 13, 'name' => ' Ubaporanga'],
            ['id_city' => 4193, 'id_state' => 13, 'name' => ' Ubari'],
            ['id_city' => 4194, 'id_state' => 13, 'name' => ' Uberaba'],
            ['id_city' => 4195, 'id_state' => 13, 'name' => ' Uberlândia'],
            ['id_city' => 4196, 'id_state' => 13, 'name' => ' Umburatiba'],
            ['id_city' => 4197, 'id_state' => 13, 'name' => ' Umbuzeiro'],
            ['id_city' => 4198, 'id_state' => 13, 'name' => ' Unaí'],
            ['id_city' => 4199, 'id_state' => 13, 'name' => ' União de Minas'],
            ['id_city' => 4200, 'id_state' => 13, 'name' => ' Uruana de Minas'],
            ['id_city' => 4201, 'id_state' => 13, 'name' => ' Urucânia'],
            ['id_city' => 4202, 'id_state' => 13, 'name' => ' Urucuia'],
            ['id_city' => 4203, 'id_state' => 13, 'name' => ' Usina Monte Alegre'],
            ['id_city' => 4204, 'id_state' => 13, 'name' => ' Vai-Volta'],
            ['id_city' => 4205, 'id_state' => 13, 'name' => ' Valadares'],
            ['id_city' => 4206, 'id_state' => 13, 'name' => ' Valão'],
            ['id_city' => 4207, 'id_state' => 13, 'name' => ' Vale Verde de Minas'],
            ['id_city' => 4208, 'id_state' => 13, 'name' => ' Valo Fundo'],
            ['id_city' => 4209, 'id_state' => 13, 'name' => ' Vargem Alegre'],
            ['id_city' => 4210, 'id_state' => 13, 'name' => ' Vargem Bonita'],
            ['id_city' => 4211, 'id_state' => 13, 'name' => ' Vargem Grande do Rio Pardo'],
            ['id_city' => 4212, 'id_state' => 13, 'name' => ' Vargem Linda'],
            ['id_city' => 4213, 'id_state' => 13, 'name' => ' Varginha'],
            ['id_city' => 4214, 'id_state' => 13, 'name' => ' Varjão de Minas'],
            ['id_city' => 4215, 'id_state' => 13, 'name' => ' Várzea da Palma'],
            ['id_city' => 4216, 'id_state' => 13, 'name' => ' Varzelândia'],
            ['id_city' => 4217, 'id_state' => 13, 'name' => ' Vau-Açu'],
            ['id_city' => 4218, 'id_state' => 13, 'name' => ' Vazante'],
            ['id_city' => 4219, 'id_state' => 13, 'name' => ' Vera Cruz de Minas'],
            ['id_city' => 4220, 'id_state' => 13, 'name' => ' Verdelândia'],
            ['id_city' => 4221, 'id_state' => 13, 'name' => ' Vereda do Paraíso'],
            ['id_city' => 4222, 'id_state' => 13, 'name' => ' Veredas'],
            ['id_city' => 4223, 'id_state' => 13, 'name' => ' Veredinha'],
            ['id_city' => 4224, 'id_state' => 13, 'name' => ' Veríssimo'],
            ['id_city' => 4225, 'id_state' => 13, 'name' => ' Vermelho'],
            ['id_city' => 4226, 'id_state' => 13, 'name' => ' Vermelho Novo'],
            ['id_city' => 4227, 'id_state' => 13, 'name' => ' Vermelho Velho'],
            ['id_city' => 4228, 'id_state' => 13, 'name' => ' Vespasiano'],
            ['id_city' => 4229, 'id_state' => 13, 'name' => ' Viçosa'],
            ['id_city' => 4230, 'id_state' => 13, 'name' => ' Vieiras'],
            ['id_city' => 4231, 'id_state' => 13, 'name' => ' Vila Bom Jesus'],
            ['id_city' => 4232, 'id_state' => 13, 'name' => ' Vila Costina'],
            ['id_city' => 4233, 'id_state' => 13, 'name' => ' Vila Nova de Minas'],
            ['id_city' => 4234, 'id_state' => 13, 'name' => ' Vila Nova dos Poções'],
            ['id_city' => 4235, 'id_state' => 13, 'name' => ' Vila Pereira'],
            ['id_city' => 4236, 'id_state' => 13, 'name' => ' Vilas Boas'],
            ['id_city' => 4237, 'id_state' => 13, 'name' => ' Virgem da Lapa'],
            ['id_city' => 4238, 'id_state' => 13, 'name' => ' Virgínia'],
            ['id_city' => 4239, 'id_state' => 13, 'name' => ' Virginópolis'],
            ['id_city' => 4240, 'id_state' => 13, 'name' => ' Virgolândia'],
            ['id_city' => 4241, 'id_state' => 13, 'name' => ' Visconde do Rio Branco'],
            ['id_city' => 4242, 'id_state' => 13, 'name' => ' Vista Alegre'],
            ['id_city' => 4243, 'id_state' => 13, 'name' => ' Vitorinos'],
            ['id_city' => 4244, 'id_state' => 13, 'name' => ' Volta Grande'],
            ['id_city' => 4245, 'id_state' => 13, 'name' => ' Wenceslau Braz'],
            ['id_city' => 4246, 'id_state' => 13, 'name' => ' Zelândia'],
            ['id_city' => 4247, 'id_state' => 13, 'name' => ' Zito Soares'],
            ['id_city' => 4248, 'id_state' => 12, 'name' => ' Água Boa'],
            ['id_city' => 4249, 'id_state' => 12, 'name' => ' Água Clara'],
            ['id_city' => 4250, 'id_state' => 12, 'name' => ' Albuquerque'],
            ['id_city' => 4251, 'id_state' => 12, 'name' => ' Alcinópolis'],
            ['id_city' => 4252, 'id_state' => 12, 'name' => ' Alto Sucuriú'],
            ['id_city' => 4253, 'id_state' => 12, 'name' => ' Amambaí'],
            ['id_city' => 4254, 'id_state' => 12, 'name' => ' Amandina'],
            ['id_city' => 4255, 'id_state' => 12, 'name' => ' Amolar'],
            ['id_city' => 4256, 'id_state' => 12, 'name' => ' Anastácio'],
            ['id_city' => 4257, 'id_state' => 12, 'name' => ' Anaurilândia'],
            ['id_city' => 4258, 'id_state' => 12, 'name' => ' Angélica'],
            ['id_city' => 4259, 'id_state' => 12, 'name' => ' Anhandui'],
            ['id_city' => 4260, 'id_state' => 12, 'name' => ' Antônio João'],
            ['id_city' => 4261, 'id_state' => 12, 'name' => ' Aparecida do Taboado'],
            ['id_city' => 4262, 'id_state' => 12, 'name' => ' Aquidauana'],
            ['id_city' => 4263, 'id_state' => 12, 'name' => ' Aral Moreira'],
            ['id_city' => 4264, 'id_state' => 12, 'name' => ' Arapuã'],
            ['id_city' => 4265, 'id_state' => 12, 'name' => ' Areado'],
            ['id_city' => 4266, 'id_state' => 12, 'name' => ' Árvore Grande'],
            ['id_city' => 4267, 'id_state' => 12, 'name' => ' Baianópolis'],
            ['id_city' => 4268, 'id_state' => 12, 'name' => ' Bálsamo'],
            ['id_city' => 4269, 'id_state' => 12, 'name' => ' Bandeirantes'],
            ['id_city' => 4270, 'id_state' => 12, 'name' => ' Bataguassu'],
            ['id_city' => 4271, 'id_state' => 12, 'name' => ' Batayporã'],
            ['id_city' => 4272, 'id_state' => 12, 'name' => ' Baús'],
            ['id_city' => 4273, 'id_state' => 12, 'name' => ' Bela Vista'],
            ['id_city' => 4274, 'id_state' => 12, 'name' => ' Bocajá'],
            ['id_city' => 4275, 'id_state' => 12, 'name' => ' Bocajá'],
            ['id_city' => 4276, 'id_state' => 12, 'name' => ' Bodoquena'],
            ['id_city' => 4277, 'id_state' => 12, 'name' => ' Bom Fim'],
            ['id_city' => 4278, 'id_state' => 12, 'name' => ' Bonito'],
            ['id_city' => 4279, 'id_state' => 12, 'name' => ' Boqueirão'],
            ['id_city' => 4280, 'id_state' => 12, 'name' => ' Brasilândia'],
            ['id_city' => 4281, 'id_state' => 12, 'name' => ' Caarapó'],
            ['id_city' => 4282, 'id_state' => 12, 'name' => ' Cabeceira do Apá'],
            ['id_city' => 4283, 'id_state' => 12, 'name' => ' Cachoeira'],
            ['id_city' => 4284, 'id_state' => 12, 'name' => ' Camapuã'],
            ['id_city' => 4285, 'id_state' => 12, 'name' => ' Camisão'],
            ['id_city' => 4286, 'id_state' => 12, 'name' => ' Campestre'],
            ['id_city' => 4287, 'id_state' => 12, 'name' => ' Campo Grande'],
            ['id_city' => 4288, 'id_state' => 12, 'name' => ' Capão Seco'],
            ['id_city' => 4289, 'id_state' => 12, 'name' => ' Caracol'],
            ['id_city' => 4290, 'id_state' => 12, 'name' => ' Carumbé'],
            ['id_city' => 4291, 'id_state' => 12, 'name' => ' Cassilândia'],
            ['id_city' => 4292, 'id_state' => 12, 'name' => ' Chapadão do Sul'],
            ['id_city' => 4293, 'id_state' => 12, 'name' => ' Cipolândia'],
            ['id_city' => 4294, 'id_state' => 12, 'name' => ' Coimbra'],
            ['id_city' => 4295, 'id_state' => 12, 'name' => ' Congonhas'],
            ['id_city' => 4296, 'id_state' => 12, 'name' => ' Corguinho'],
            ['id_city' => 4297, 'id_state' => 12, 'name' => ' Coronel Sapucaia'],
            ['id_city' => 4298, 'id_state' => 12, 'name' => ' Corumbá'],
            ['id_city' => 4299, 'id_state' => 12, 'name' => ' Costa Rica'],
            ['id_city' => 4300, 'id_state' => 12, 'name' => ' Coxim'],
            ['id_city' => 4301, 'id_state' => 12, 'name' => ' Cristalina'],
            ['id_city' => 4302, 'id_state' => 12, 'name' => ' Cruzaltina'],
            ['id_city' => 4303, 'id_state' => 12, 'name' => ' Culturama'],
            ['id_city' => 4304, 'id_state' => 12, 'name' => ' Cupins'],
            ['id_city' => 4305, 'id_state' => 12, 'name' => ' Debrasa'],
            ['id_city' => 4306, 'id_state' => 12, 'name' => ' Deodápolis'],
            ['id_city' => 4307, 'id_state' => 12, 'name' => ' Dois Irmãos do Buriti'],
            ['id_city' => 4308, 'id_state' => 12, 'name' => ' Douradina'],
            ['id_city' => 4309, 'id_state' => 12, 'name' => ' Dourados'],
            ['id_city' => 4310, 'id_state' => 12, 'name' => ' Eldorado'],
            ['id_city' => 4311, 'id_state' => 12, 'name' => ' Fátima do Sul'],
            ['id_city' => 4312, 'id_state' => 12, 'name' => ' Figueirão'],
            ['id_city' => 4313, 'id_state' => 12, 'name' => ' Garcias'],
            ['id_city' => 4314, 'id_state' => 12, 'name' => ' Glória de Dourados'],
            ['id_city' => 4315, 'id_state' => 12, 'name' => ' Guaçu'],
            ['id_city' => 4316, 'id_state' => 12, 'name' => ' Guaçulândia'],
            ['id_city' => 4317, 'id_state' => 12, 'name' => ' Guadalupe do Alto Paraná'],
            ['id_city' => 4318, 'id_state' => 12, 'name' => ' Guia Lopes da Laguna'],
            ['id_city' => 4319, 'id_state' => 12, 'name' => ' Iguatemi'],
            ['id_city' => 4320, 'id_state' => 12, 'name' => ' Ilha Comprida'],
            ['id_city' => 4321, 'id_state' => 12, 'name' => ' Ilha Grande'],
            ['id_city' => 4322, 'id_state' => 12, 'name' => ' Indaiá do Sul'],
            ['id_city' => 4323, 'id_state' => 12, 'name' => ' Indaiá Grande'],
            ['id_city' => 4324, 'id_state' => 12, 'name' => ' Indápolis'],
            ['id_city' => 4325, 'id_state' => 12, 'name' => ' Inocência'],
            ['id_city' => 4326, 'id_state' => 12, 'name' => ' Ipezal'],
            ['id_city' => 4327, 'id_state' => 12, 'name' => ' Itahum'],
            ['id_city' => 4328, 'id_state' => 12, 'name' => ' Itaporã'],
            ['id_city' => 4329, 'id_state' => 12, 'name' => ' Itaquiraí'],
            ['id_city' => 4330, 'id_state' => 12, 'name' => ' Ivinhema'],
            ['id_city' => 4331, 'id_state' => 12, 'name' => ' Jabuti'],
            ['id_city' => 4332, 'id_state' => 12, 'name' => ' Jacareí'],
            ['id_city' => 4333, 'id_state' => 12, 'name' => ' Japorã'],
            ['id_city' => 4334, 'id_state' => 12, 'name' => ' Jaraguari'],
            ['id_city' => 4335, 'id_state' => 12, 'name' => ' Jardim'],
            ['id_city' => 4336, 'id_state' => 12, 'name' => ' Jateí'],
            ['id_city' => 4337, 'id_state' => 12, 'name' => ' Jauru'],
            ['id_city' => 4338, 'id_state' => 12, 'name' => ' Juscelândia'],
            ['id_city' => 4339, 'id_state' => 12, 'name' => ' Jutí'],
            ['id_city' => 4340, 'id_state' => 12, 'name' => ' Ladário'],
            ['id_city' => 4341, 'id_state' => 12, 'name' => ' Lagoa Bonita'],
            ['id_city' => 4342, 'id_state' => 12, 'name' => ' Laguna Carapã'],
            ['id_city' => 4343, 'id_state' => 12, 'name' => ' Maracaju'],
            ['id_city' => 4344, 'id_state' => 12, 'name' => ' Miranda'],
            ['id_city' => 4345, 'id_state' => 12, 'name' => ' Montese'],
            ['id_city' => 4346, 'id_state' => 12, 'name' => ' Morangas'],
            ['id_city' => 4347, 'id_state' => 12, 'name' => ' Morraria do Sul'],
            ['id_city' => 4348, 'id_state' => 12, 'name' => ' Morumbi'],
            ['id_city' => 4349, 'id_state' => 12, 'name' => ' Mundo Novo'],
            ['id_city' => 4350, 'id_state' => 12, 'name' => ' Naviraí'],
            ['id_city' => 4351, 'id_state' => 12, 'name' => ' Nhecolândia'],
            ['id_city' => 4352, 'id_state' => 12, 'name' => ' Nioaque'],
            ['id_city' => 4353, 'id_state' => 12, 'name' => ' Nossa Senhora de Fátima'],
            ['id_city' => 4354, 'id_state' => 12, 'name' => ' Nova Alvorada do Sul'],
            ['id_city' => 4355, 'id_state' => 12, 'name' => ' Nova América'],
            ['id_city' => 4356, 'id_state' => 12, 'name' => ' Nova Andradina'],
            ['id_city' => 4357, 'id_state' => 12, 'name' => ' Nova Esperança'],
            ['id_city' => 4358, 'id_state' => 12, 'name' => ' Nova Jales'],
            ['id_city' => 4359, 'id_state' => 12, 'name' => ' Novo Horizonte do Sul'],
            ['id_city' => 4360, 'id_state' => 12, 'name' => ' Oriente'],
            ['id_city' => 4361, 'id_state' => 12, 'name' => ' Paiaguás'],
            ['id_city' => 4362, 'id_state' => 12, 'name' => ' Palmeiras'],
            ['id_city' => 4363, 'id_state' => 12, 'name' => ' Panambi'],
            ['id_city' => 4364, 'id_state' => 12, 'name' => ' Paraíso'],
            ['id_city' => 4365, 'id_state' => 12, 'name' => ' Paranaíba'],
            ['id_city' => 4366, 'id_state' => 12, 'name' => ' Paranhos'],
            ['id_city' => 4367, 'id_state' => 12, 'name' => ' Pedro Gomes'],
            ['id_city' => 4368, 'id_state' => 12, 'name' => ' Picadinha'],
            ['id_city' => 4369, 'id_state' => 12, 'name' => ' Pirapora'],
            ['id_city' => 4370, 'id_state' => 12, 'name' => ' Piraputanga'],
            ['id_city' => 4371, 'id_state' => 12, 'name' => ' Ponta Porã'],
            ['id_city' => 4372, 'id_state' => 12, 'name' => ' Ponte Vermelha'],
            ['id_city' => 4373, 'id_state' => 12, 'name' => ' Pontinha do Cocho'],
            ['id_city' => 4374, 'id_state' => 12, 'name' => ' Porto Esperança'],
            ['id_city' => 4375, 'id_state' => 12, 'name' => ' Porto Murtinho'],
            ['id_city' => 4376, 'id_state' => 12, 'name' => ' Porto Vilma'],
            ['id_city' => 4377, 'id_state' => 12, 'name' => ' Porto XV de Novembro'],
            ['id_city' => 4378, 'id_state' => 12, 'name' => ' Presidente Castelo'],
            ['id_city' => 4379, 'id_state' => 12, 'name' => ' Prudêncio Thomaz'],
            ['id_city' => 4380, 'id_state' => 12, 'name' => ' Quebra Côco'],
            ['id_city' => 4381, 'id_state' => 12, 'name' => ' Quebracho'],
            ['id_city' => 4382, 'id_state' => 12, 'name' => ' Ribas do Rio Pardo'],
            ['id_city' => 4383, 'id_state' => 12, 'name' => ' Rio Brilhante'],
            ['id_city' => 4384, 'id_state' => 12, 'name' => ' Rio Negro'],
            ['id_city' => 4385, 'id_state' => 12, 'name' => ' Rio Verde de Mato Grosso'],
            ['id_city' => 4386, 'id_state' => 12, 'name' => ' Rochedinho'],
            ['id_city' => 4387, 'id_state' => 12, 'name' => ' Rochedo'],
            ['id_city' => 4388, 'id_state' => 12, 'name' => ' Sanga Puitã'],
            ['id_city' => 4389, 'id_state' => 12, 'name' => ' Santa Rita do Pardo'],
            ['id_city' => 4390, 'id_state' => 12, 'name' => ' Santa Terezinha'],
            ['id_city' => 4391, 'id_state' => 12, 'name' => ' São Gabriel do Oeste'],
            ['id_city' => 4392, 'id_state' => 12, 'name' => ' São João do Apore'],
            ['id_city' => 4393, 'id_state' => 12, 'name' => ' São José'],
            ['id_city' => 4394, 'id_state' => 12, 'name' => ' São José do Sucuriú'],
            ['id_city' => 4395, 'id_state' => 12, 'name' => ' São Pedro'],
            ['id_city' => 4396, 'id_state' => 12, 'name' => ' São Pedro'],
            ['id_city' => 4397, 'id_state' => 12, 'name' => ' São Romão'],
            ['id_city' => 4398, 'id_state' => 12, 'name' => ' Selvíria'],
            ['id_city' => 4399, 'id_state' => 12, 'name' => ' Sete Quedas'],
            ['id_city' => 4400, 'id_state' => 12, 'name' => ' Sidrolândia'],
            ['id_city' => 4401, 'id_state' => 12, 'name' => ' Sonora'],
            ['id_city' => 4402, 'id_state' => 12, 'name' => ' Tacuru'],
            ['id_city' => 4403, 'id_state' => 12, 'name' => ' Tamandaré'],
            ['id_city' => 4404, 'id_state' => 12, 'name' => ' Taquari'],
            ['id_city' => 4405, 'id_state' => 12, 'name' => ' Taquarussu'],
            ['id_city' => 4406, 'id_state' => 12, 'name' => ' Taunay'],
            ['id_city' => 4407, 'id_state' => 12, 'name' => ' Terenos'],
            ['id_city' => 4408, 'id_state' => 12, 'name' => ' Três Lagoas'],
            ['id_city' => 4409, 'id_state' => 12, 'name' => ' Velhacaria'],
            ['id_city' => 4410, 'id_state' => 12, 'name' => ' Vicentina'],
            ['id_city' => 4411, 'id_state' => 12, 'name' => ' Vila Formosa'],
            ['id_city' => 4412, 'id_state' => 12, 'name' => ' Vila Marques'],
            ['id_city' => 4413, 'id_state' => 12, 'name' => ' Vila Rica'],
            ['id_city' => 4414, 'id_state' => 12, 'name' => ' Vila União'],
            ['id_city' => 4415, 'id_state' => 12, 'name' => ' Vila Vargas'],
            ['id_city' => 4416, 'id_state' => 12, 'name' => ' Vista Alegre'],
            ['id_city' => 4417, 'id_state' => 11, 'name' => ' Acorizal'],
            ['id_city' => 4418, 'id_state' => 11, 'name' => ' Água Boa'],
            ['id_city' => 4419, 'id_state' => 11, 'name' => ' Água Fria'],
            ['id_city' => 4420, 'id_state' => 11, 'name' => ' Aguaçu'],
            ['id_city' => 4421, 'id_state' => 11, 'name' => ' Aguapeí'],
            ['id_city' => 4422, 'id_state' => 11, 'name' => ' Águas Claras'],
            ['id_city' => 4423, 'id_state' => 11, 'name' => ' Ainhumas'],
            ['id_city' => 4424, 'id_state' => 11, 'name' => ' Alcantilado'],
            ['id_city' => 4425, 'id_state' => 11, 'name' => ' Alta Floresta'],
            ['id_city' => 4426, 'id_state' => 11, 'name' => ' Alto Araguaia'],
            ['id_city' => 4427, 'id_state' => 11, 'name' => ' Alto Boa Vista'],
            ['id_city' => 4428, 'id_state' => 11, 'name' => ' Alto Coité'],
            ['id_city' => 4429, 'id_state' => 11, 'name' => ' Alto Garças'],
            ['id_city' => 4430, 'id_state' => 11, 'name' => ' Alto Juruena'],
            ['id_city' => 4431, 'id_state' => 11, 'name' => ' Alto Paraguai'],
            ['id_city' => 4432, 'id_state' => 11, 'name' => ' Alto Paraíso'],
            ['id_city' => 4433, 'id_state' => 11, 'name' => ' Alto Taquari'],
            ['id_city' => 4434, 'id_state' => 11, 'name' => ' Analândia do Norte'],
            ['id_city' => 4435, 'id_state' => 11, 'name' => ' Apiacás'],
            ['id_city' => 4436, 'id_state' => 11, 'name' => ' Araguaiana'],
            ['id_city' => 4437, 'id_state' => 11, 'name' => ' Araguainha'],
            ['id_city' => 4438, 'id_state' => 11, 'name' => ' Araputanga'],
            ['id_city' => 4439, 'id_state' => 11, 'name' => ' Arenápolis'],
            ['id_city' => 4440, 'id_state' => 11, 'name' => ' Aripuanã'],
            ['id_city' => 4441, 'id_state' => 11, 'name' => ' Arruda'],
            ['id_city' => 4442, 'id_state' => 11, 'name' => ' Assari'],
            ['id_city' => 4443, 'id_state' => 11, 'name' => ' Barão de Melgaço'],
            ['id_city' => 4444, 'id_state' => 11, 'name' => ' Barra do Bugres'],
            ['id_city' => 4445, 'id_state' => 11, 'name' => ' Barra do Garças'],
            ['id_city' => 4446, 'id_state' => 11, 'name' => ' Batovi'],
            ['id_city' => 4447, 'id_state' => 11, 'name' => ' Baús'],
            ['id_city' => 4448, 'id_state' => 11, 'name' => ' Bauxi'],
            ['id_city' => 4449, 'id_state' => 11, 'name' => ' Bel Rios'],
            ['id_city' => 4450, 'id_state' => 11, 'name' => ' Bezerro Branco'],
            ['id_city' => 4451, 'id_state' => 11, 'name' => ' Boa Esperança'],
            ['id_city' => 4452, 'id_state' => 11, 'name' => ' Boa União'],
            ['id_city' => 4453, 'id_state' => 11, 'name' => ' Boa Vista'],
            ['id_city' => 4454, 'id_state' => 11, 'name' => ' Bom Sucesso'],
            ['id_city' => 4455, 'id_state' => 11, 'name' => ' Brasnorte'],
            ['id_city' => 4456, 'id_state' => 11, 'name' => ' Buriti'],
            ['id_city' => 4457, 'id_state' => 11, 'name' => ' Cáceres'],
            ['id_city' => 4458, 'id_state' => 11, 'name' => ' Caite'],
            ['id_city' => 4459, 'id_state' => 11, 'name' => ' Campinápolis'],
            ['id_city' => 4460, 'id_state' => 11, 'name' => ' Campo Novo do Parecis'],
            ['id_city' => 4461, 'id_state' => 11, 'name' => ' Campo Verde'],
            ['id_city' => 4462, 'id_state' => 11, 'name' => ' Campos de Júlio'],
            ['id_city' => 4463, 'id_state' => 11, 'name' => ' Campos Novos'],
            ['id_city' => 4464, 'id_state' => 11, 'name' => ' Canabrava do Norte'],
            ['id_city' => 4465, 'id_state' => 11, 'name' => ' Canarana'],
            ['id_city' => 4466, 'id_state' => 11, 'name' => ' Cangas'],
            ['id_city' => 4467, 'id_state' => 11, 'name' => ' Capão Grande'],
            ['id_city' => 4468, 'id_state' => 11, 'name' => ' Capão Verde'],
            ['id_city' => 4469, 'id_state' => 11, 'name' => ' Caramujo'],
            ['id_city' => 4470, 'id_state' => 11, 'name' => ' Caravagio'],
            ['id_city' => 4471, 'id_state' => 11, 'name' => ' Carlinda'],
            ['id_city' => 4472, 'id_state' => 11, 'name' => ' Cassununga'],
            ['id_city' => 4473, 'id_state' => 11, 'name' => ' Castanheira'],
            ['id_city' => 4474, 'id_state' => 11, 'name' => ' Catuai'],
            ['id_city' => 4475, 'id_state' => 11, 'name' => ' Chapada dos Guimarães'],
            ['id_city' => 4476, 'id_state' => 11, 'name' => ' Cidade Morena'],
            ['id_city' => 4477, 'id_state' => 11, 'name' => ' Cláudia'],
            ['id_city' => 4478, 'id_state' => 11, 'name' => ' Cocalinho'],
            ['id_city' => 4479, 'id_state' => 11, 'name' => ' Colíder'],
            ['id_city' => 4480, 'id_state' => 11, 'name' => ' Colorado do Norte'],
            ['id_city' => 4481, 'id_state' => 11, 'name' => ' Comodoro'],
            ['id_city' => 4482, 'id_state' => 11, 'name' => ' Confresa'],
            ['id_city' => 4483, 'id_state' => 11, 'name' => ' Coronel Ponce'],
            ['id_city' => 4484, 'id_state' => 11, 'name' => ' Cotrel'],
            ['id_city' => 4485, 'id_state' => 11, 'name' => ' Cotriguaçu'],
            ['id_city' => 4486, 'id_state' => 11, 'name' => ' Coxipó Açu'],
            ['id_city' => 4487, 'id_state' => 11, 'name' => ' Coxipó da Ponte'],
            ['id_city' => 4488, 'id_state' => 11, 'name' => ' Coxipó do Ouro'],
            ['id_city' => 4489, 'id_state' => 11, 'name' => ' Cristinópolis'],
            ['id_city' => 4490, 'id_state' => 11, 'name' => ' Cristo Rei'],
            ['id_city' => 4491, 'id_state' => 11, 'name' => ' Cuiabá'],
            ['id_city' => 4492, 'id_state' => 11, 'name' => ' Curvelândia'],
            ['id_city' => 4493, 'id_state' => 11, 'name' => ' Del Rios'],
            ['id_city' => 4494, 'id_state' => 11, 'name' => ' Denise'],
            ['id_city' => 4495, 'id_state' => 11, 'name' => ' Diamantino'],
            ['id_city' => 4496, 'id_state' => 11, 'name' => ' Dom Aquino'],
            ['id_city' => 4497, 'id_state' => 11, 'name' => ' Engenho'],
            ['id_city' => 4498, 'id_state' => 11, 'name' => ' Engenho Velho'],
            ['id_city' => 4499, 'id_state' => 11, 'name' => ' Entre Rios'],
            ['id_city' => 4500, 'id_state' => 11, 'name' => ' Estrela do Leste'],
            ['id_city' => 4501, 'id_state' => 11, 'name' => ' Faval'],
            ['id_city' => 4502, 'id_state' => 11, 'name' => ' Fazenda de Cima'],
            ['id_city' => 4503, 'id_state' => 11, 'name' => ' Feliz Natal'],
            ['id_city' => 4504, 'id_state' => 11, 'name' => ' Figueirópolis D Oeste'],
            ['id_city' => 4505, 'id_state' => 11, 'name' => ' Filadélfia'],
            ['id_city' => 4506, 'id_state' => 11, 'name' => ' Flor da Serra'],
            ['id_city' => 4507, 'id_state' => 11, 'name' => ' Fontanilhas'],
            ['id_city' => 4508, 'id_state' => 11, 'name' => ' Gaúcha do Norte'],
            ['id_city' => 4509, 'id_state' => 11, 'name' => ' General Carneiro'],
            ['id_city' => 4510, 'id_state' => 11, 'name' => ' Glória D Oeste'],
            ['id_city' => 4511, 'id_state' => 11, 'name' => ' Guarantã do Norte'],
            ['id_city' => 4512, 'id_state' => 11, 'name' => ' Guarita'],
            ['id_city' => 4513, 'id_state' => 11, 'name' => ' Guiratinga'],
            ['id_city' => 4514, 'id_state' => 11, 'name' => ' Horizonte do Oeste'],
            ['id_city' => 4515, 'id_state' => 11, 'name' => ' Indianápolis'],
            ['id_city' => 4516, 'id_state' => 11, 'name' => ' Indiavaí'],
            ['id_city' => 4517, 'id_state' => 11, 'name' => ' Irenópolis'],
            ['id_city' => 4518, 'id_state' => 11, 'name' => ' Itamarati Norte'],
            ['id_city' => 4519, 'id_state' => 11, 'name' => ' Itaúba'],
            ['id_city' => 4520, 'id_state' => 11, 'name' => ' Itiquira'],
            ['id_city' => 4521, 'id_state' => 11, 'name' => ' Jaciara'],
            ['id_city' => 4522, 'id_state' => 11, 'name' => ' Jangada'],
            ['id_city' => 4523, 'id_state' => 11, 'name' => ' Jarudore'],
            ['id_city' => 4524, 'id_state' => 11, 'name' => ' Jatobá'],
            ['id_city' => 4525, 'id_state' => 11, 'name' => ' Jauru'],
            ['id_city' => 4526, 'id_state' => 11, 'name' => ' Joselândia'],
            ['id_city' => 4527, 'id_state' => 11, 'name' => ' Juara'],
            ['id_city' => 4528, 'id_state' => 11, 'name' => ' Juína'],
            ['id_city' => 4529, 'id_state' => 11, 'name' => ' Juruena'],
            ['id_city' => 4530, 'id_state' => 11, 'name' => ' Juscimeira'],
            ['id_city' => 4531, 'id_state' => 11, 'name' => ' Lambari D Oeste'],
            ['id_city' => 4532, 'id_state' => 11, 'name' => ' Lavouras'],
            ['id_city' => 4533, 'id_state' => 11, 'name' => ' Lucas do Rio Verde'],
            ['id_city' => 4534, 'id_state' => 11, 'name' => ' Lucialva'],
            ['id_city' => 4535, 'id_state' => 11, 'name' => ' Luciara'],
            ['id_city' => 4536, 'id_state' => 11, 'name' => ' Machado'],
            ['id_city' => 4537, 'id_state' => 11, 'name' => ' Marcelândia'],
            ['id_city' => 4538, 'id_state' => 11, 'name' => ' Marzagão'],
            ['id_city' => 4539, 'id_state' => 11, 'name' => ' Mata Dentro'],
            ['id_city' => 4540, 'id_state' => 11, 'name' => ' Matupá'],
            ['id_city' => 4541, 'id_state' => 11, 'name' => ' Mimoso'],
            ['id_city' => 4542, 'id_state' => 11, 'name' => ' Mirassol D Oeste'],
            ['id_city' => 4543, 'id_state' => 11, 'name' => ' Nobres'],
            ['id_city' => 4544, 'id_state' => 11, 'name' => ' Nonoai do Norte'],
            ['id_city' => 4545, 'id_state' => 11, 'name' => ' Nortelândia'],
            ['id_city' => 4546, 'id_state' => 11, 'name' => ' Nossa Senhora da Guia'],
            ['id_city' => 4547, 'id_state' => 11, 'name' => ' Nossa Senhora do Livramento'],
            ['id_city' => 4548, 'id_state' => 11, 'name' => ' Nova Alvorada'],
            ['id_city' => 4549, 'id_state' => 11, 'name' => ' Nova Bandeirantes'],
            ['id_city' => 4550, 'id_state' => 11, 'name' => ' Nova Brasilândia'],
            ['id_city' => 4551, 'id_state' => 11, 'name' => ' Nova Brasília'],
            ['id_city' => 4552, 'id_state' => 11, 'name' => ' Nova Canaã do Norte'],
            ['id_city' => 4553, 'id_state' => 11, 'name' => ' Nova Catanduva'],
            ['id_city' => 4554, 'id_state' => 11, 'name' => ' Nova Galileia'],
            ['id_city' => 4555, 'id_state' => 11, 'name' => ' Nova Guarita'],
            ['id_city' => 4556, 'id_state' => 11, 'name' => ' Nova Lacerda'],
            ['id_city' => 4557, 'id_state' => 11, 'name' => ' Nova Marilândia'],
            ['id_city' => 4558, 'id_state' => 11, 'name' => ' Nova Maringá'],
            ['id_city' => 4559, 'id_state' => 11, 'name' => ' Nova Monte Verde'],
            ['id_city' => 4560, 'id_state' => 11, 'name' => ' Nova Mutum'],
            ['id_city' => 4561, 'id_state' => 11, 'name' => ' Nova Olímpia'],
            ['id_city' => 4562, 'id_state' => 11, 'name' => ' Nova Ubiratã'],
            ['id_city' => 4563, 'id_state' => 11, 'name' => ' Nova Xavantina'],
            ['id_city' => 4564, 'id_state' => 11, 'name' => ' Novo Diamantino'],
            ['id_city' => 4565, 'id_state' => 11, 'name' => ' Novo Eldorado'],
            ['id_city' => 4566, 'id_state' => 11, 'name' => ' Novo Horizonte do Norte'],
            ['id_city' => 4567, 'id_state' => 11, 'name' => ' Novo Mundo'],
            ['id_city' => 4568, 'id_state' => 11, 'name' => ' Novo Paraná'],
            ['id_city' => 4569, 'id_state' => 11, 'name' => ' Novo São Joaquim'],
            ['id_city' => 4570, 'id_state' => 11, 'name' => ' Padronal'],
            ['id_city' => 4571, 'id_state' => 11, 'name' => ' Pai André'],
            ['id_city' => 4572, 'id_state' => 11, 'name' => ' Paraíso do Leste'],
            ['id_city' => 4573, 'id_state' => 11, 'name' => ' Paranaitá'],
            ['id_city' => 4574, 'id_state' => 11, 'name' => ' Paranatinga'],
            ['id_city' => 4575, 'id_state' => 11, 'name' => ' Passagem da Conceição'],
            ['id_city' => 4576, 'id_state' => 11, 'name' => ' Pedra Preta'],
            ['id_city' => 4577, 'id_state' => 11, 'name' => ' Peixoto de Azevedo'],
            ['id_city' => 4578, 'id_state' => 11, 'name' => ' Pirizal'],
            ['id_city' => 4579, 'id_state' => 11, 'name' => ' Placa de Santo Antônio'],
            ['id_city' => 4580, 'id_state' => 11, 'name' => ' Planalto da Serra'],
            ['id_city' => 4581, 'id_state' => 11, 'name' => ' Poconé'],
            ['id_city' => 4582, 'id_state' => 11, 'name' => ' Pombas'],
            ['id_city' => 4583, 'id_state' => 11, 'name' => ' Pontal do Araguaia'],
            ['id_city' => 4584, 'id_state' => 11, 'name' => ' Ponte Branca'],
            ['id_city' => 4585, 'id_state' => 11, 'name' => ' Ponte de Pedra'],
            ['id_city' => 4586, 'id_state' => 11, 'name' => ' Pontes e Lacerda'],
            ['id_city' => 4587, 'id_state' => 11, 'name' => ' Pontinópolis'],
            ['id_city' => 4588, 'id_state' => 11, 'name' => ' Porto Alegre do Norte'],
            ['id_city' => 4589, 'id_state' => 11, 'name' => ' Porto dos Gaúchos'],
            ['id_city' => 4590, 'id_state' => 11, 'name' => ' Porto Esperidião'],
            ['id_city' => 4591, 'id_state' => 11, 'name' => ' Porto Estrela'],
            ['id_city' => 4592, 'id_state' => 11, 'name' => ' Poxoréu'],
            ['id_city' => 4593, 'id_state' => 11, 'name' => ' Praia Rica'],
            ['id_city' => 4594, 'id_state' => 11, 'name' => ' Primavera'],
            ['id_city' => 4595, 'id_state' => 11, 'name' => ' Primavera do Leste'],
            ['id_city' => 4596, 'id_state' => 11, 'name' => ' Progresso'],
            ['id_city' => 4597, 'id_state' => 11, 'name' => ' Querência'],
            ['id_city' => 4598, 'id_state' => 11, 'name' => ' Rancharia'],
            ['id_city' => 4599, 'id_state' => 11, 'name' => ' Reserva do Cabaçal'],
            ['id_city' => 4600, 'id_state' => 11, 'name' => ' Ribeirão Cascalheira'],
            ['id_city' => 4601, 'id_state' => 11, 'name' => ' Ribeirão dos Cocais'],
            ['id_city' => 4602, 'id_state' => 11, 'name' => ' Ribeirãozinho'],
            ['id_city' => 4603, 'id_state' => 11, 'name' => ' Rio Branco'],
            ['id_city' => 4604, 'id_state' => 11, 'name' => ' Rio Manso'],
            ['id_city' => 4605, 'id_state' => 11, 'name' => ' Riolândia'],
            ['id_city' => 4606, 'id_state' => 11, 'name' => ' Rondonópolis'],
            ['id_city' => 4607, 'id_state' => 11, 'name' => ' Rosário Oeste'],
            ['id_city' => 4608, 'id_state' => 11, 'name' => ' Salto do Céu'],
            ['id_city' => 4609, 'id_state' => 11, 'name' => ' Sangradouro'],
            ['id_city' => 4610, 'id_state' => 11, 'name' => ' Santa Carmem'],
            ['id_city' => 4611, 'id_state' => 11, 'name' => ' Santa Elvira'],
            ['id_city' => 4612, 'id_state' => 11, 'name' => ' Santa Fé'],
            ['id_city' => 4613, 'id_state' => 11, 'name' => ' Santa Rita'],
            ['id_city' => 4614, 'id_state' => 11, 'name' => ' Santa Terezinha'],
            ['id_city' => 4615, 'id_state' => 11, 'name' => ' Santaninha'],
            ['id_city' => 4616, 'id_state' => 11, 'name' => ' Santo Afonso'],
            ['id_city' => 4617, 'id_state' => 11, 'name' => ' Santo Antônio do Leverger'],
            ['id_city' => 4618, 'id_state' => 11, 'name' => ' São Cristovão'],
            ['id_city' => 4619, 'id_state' => 11, 'name' => ' Vale de São Domingos'],
            ['id_city' => 4620, 'id_state' => 11, 'name' => ' São Félix do Araguaia'],
            ['id_city' => 4621, 'id_state' => 11, 'name' => ' São Joaquim'],
            ['id_city' => 4622, 'id_state' => 11, 'name' => ' São Jorge'],
            ['id_city' => 4623, 'id_state' => 11, 'name' => ' São José'],
            ['id_city' => 4624, 'id_state' => 11, 'name' => ' São José do Apuí'],
            ['id_city' => 4625, 'id_state' => 11, 'name' => ' São José do Planalto'],
            ['id_city' => 4626, 'id_state' => 11, 'name' => ' São José do Povo'],
            ['id_city' => 4627, 'id_state' => 11, 'name' => ' São José do Rio Claro'],
            ['id_city' => 4628, 'id_state' => 11, 'name' => ' São José do Xingu'],
            ['id_city' => 4629, 'id_state' => 11, 'name' => ' São José dos Quatro Marcos'],
            ['id_city' => 4630, 'id_state' => 11, 'name' => ' São Lourenço de Fátima'],
            ['id_city' => 4631, 'id_state' => 11, 'name' => ' São Pedro da Cipa'],
            ['id_city' => 4632, 'id_state' => 11, 'name' => ' São Vicente'],
            ['id_city' => 4633, 'id_state' => 11, 'name' => ' Sapezal'],
            ['id_city' => 4634, 'id_state' => 11, 'name' => ' Selma'],
            ['id_city' => 4635, 'id_state' => 11, 'name' => ' Serra Nova Dourada'],
            ['id_city' => 4636, 'id_state' => 11, 'name' => ' Sinop'],
            ['id_city' => 4637, 'id_state' => 11, 'name' => ' Sonho Azul'],
            ['id_city' => 4638, 'id_state' => 11, 'name' => ' Sorriso'],
            ['id_city' => 4639, 'id_state' => 11, 'name' => ' Sumidouro'],
            ['id_city' => 4640, 'id_state' => 11, 'name' => ' Tabaporã'],
            ['id_city' => 4641, 'id_state' => 11, 'name' => ' Tangará da Serra'],
            ['id_city' => 4642, 'id_state' => 11, 'name' => ' Tapirapua'],
            ['id_city' => 4643, 'id_state' => 11, 'name' => ' Tapurah'],
            ['id_city' => 4644, 'id_state' => 11, 'name' => ' Terra Nova do Norte'],
            ['id_city' => 4645, 'id_state' => 11, 'name' => ' Terra Roxa'],
            ['id_city' => 4646, 'id_state' => 11, 'name' => ' Tesouro'],
            ['id_city' => 4647, 'id_state' => 11, 'name' => ' Toricueyje'],
            ['id_city' => 4648, 'id_state' => 11, 'name' => ' Torixoréu'],
            ['id_city' => 4649, 'id_state' => 11, 'name' => ' Três Pontes'],
            ['id_city' => 4650, 'id_state' => 11, 'name' => ' União do Sul'],
            ['id_city' => 4651, 'id_state' => 11, 'name' => ' Vale dos Sonhos'],
            ['id_city' => 4652, 'id_state' => 11, 'name' => ' Vale Rico'],
            ['id_city' => 4653, 'id_state' => 11, 'name' => ' Varginha'],
            ['id_city' => 4654, 'id_state' => 11, 'name' => ' Várzea Grande'],
            ['id_city' => 4655, 'id_state' => 11, 'name' => ' Vera'],
            ['id_city' => 4656, 'id_state' => 11, 'name' => ' Vila Atlântica'],
            ['id_city' => 4657, 'id_state' => 11, 'name' => ' Vila Bela da Santíssima Trindade'],
            ['id_city' => 4658, 'id_state' => 11, 'name' => ' Vila Bueno'],
            ['id_city' => 4659, 'id_state' => 11, 'name' => ' Vila Mutum'],
            ['id_city' => 4660, 'id_state' => 11, 'name' => ' Vila Operária'],
            ['id_city' => 4661, 'id_state' => 11, 'name' => ' Vila Paulista'],
            ['id_city' => 4662, 'id_state' => 11, 'name' => ' Vila Progresso'],
            ['id_city' => 4663, 'id_state' => 11, 'name' => ' Vila Rica'],
            ['id_city' => 4664, 'id_state' => 11, 'name' => ' Novo Santo Antônio'],
            ['id_city' => 4665, 'id_state' => 14, 'name' => ' Abaetetuba'],
            ['id_city' => 4666, 'id_state' => 14, 'name' => ' Abel Figueiredo'],
            ['id_city' => 4667, 'id_state' => 14, 'name' => ' Acará'],
            ['id_city' => 4668, 'id_state' => 14, 'name' => ' Afuá'],
            ['id_city' => 4669, 'id_state' => 14, 'name' => ' Agrópolis Bela Vista'],
            ['id_city' => 4670, 'id_state' => 14, 'name' => ' Água Azul do Norte'],
            ['id_city' => 4671, 'id_state' => 14, 'name' => ' Água Fria'],
            ['id_city' => 4672, 'id_state' => 14, 'name' => ' Alenquer'],
            ['id_city' => 4673, 'id_state' => 14, 'name' => ' Algodoal'],
            ['id_city' => 4674, 'id_state' => 14, 'name' => ' Almeirim'],
            ['id_city' => 4675, 'id_state' => 14, 'name' => ' Almoço'],
            ['id_city' => 4676, 'id_state' => 14, 'name' => ' Alta Pará'],
            ['id_city' => 4677, 'id_state' => 14, 'name' => ' Altamira'],
            ['id_city' => 4678, 'id_state' => 14, 'name' => ' Alter do Chão'],
            ['id_city' => 4679, 'id_state' => 14, 'name' => ' Alvorada'],
            ['id_city' => 4680, 'id_state' => 14, 'name' => ' Americano'],
            ['id_city' => 4681, 'id_state' => 14, 'name' => ' Anajás'],
            ['id_city' => 4682, 'id_state' => 14, 'name' => ' Ananindeua'],
            ['id_city' => 4683, 'id_state' => 14, 'name' => ' Anapu'],
            ['id_city' => 4684, 'id_state' => 14, 'name' => ' Antônio Lemos'],
            ['id_city' => 4685, 'id_state' => 14, 'name' => ' Apeú'],
            ['id_city' => 4686, 'id_state' => 14, 'name' => ' Apinagés'],
            ['id_city' => 4687, 'id_state' => 14, 'name' => ' Arapixuna'],
            ['id_city' => 4688, 'id_state' => 14, 'name' => ' Araquaim'],
            ['id_city' => 4689, 'id_state' => 14, 'name' => ' Arco-Íris'],
            ['id_city' => 4690, 'id_state' => 14, 'name' => ' Areias'],
            ['id_city' => 4691, 'id_state' => 14, 'name' => ' Arumanduba'],
            ['id_city' => 4692, 'id_state' => 14, 'name' => ' Aruri'],
            ['id_city' => 4693, 'id_state' => 14, 'name' => ' Aturiaí'],
            ['id_city' => 4694, 'id_state' => 14, 'name' => ' Augusto Corrêa'],
            ['id_city' => 4695, 'id_state' => 14, 'name' => ' Aurora do Pará'],
            ['id_city' => 4696, 'id_state' => 14, 'name' => ' Aveiro'],
            ['id_city' => 4697, 'id_state' => 14, 'name' => ' Bagre'],
            ['id_city' => 4698, 'id_state' => 14, 'name' => ' Baião'],
            ['id_city' => 4699, 'id_state' => 14, 'name' => ' Bannach'],
            ['id_city' => 4700, 'id_state' => 14, 'name' => ' Barcarena'],
            ['id_city' => 4701, 'id_state' => 14, 'name' => ' Barreira Branca'],
            ['id_city' => 4702, 'id_state' => 14, 'name' => ' Barreira dos Campos'],
            ['id_city' => 4703, 'id_state' => 14, 'name' => ' Barreiras'],
            ['id_city' => 4704, 'id_state' => 14, 'name' => ' Baturité'],
            ['id_city' => 4705, 'id_state' => 14, 'name' => ' Beja'],
            ['id_city' => 4706, 'id_state' => 14, 'name' => ' Bela Vista do Caracol'],
            ['id_city' => 4707, 'id_state' => 14, 'name' => ' Belém'],
            ['id_city' => 4708, 'id_state' => 14, 'name' => ' Belterra'],
            ['id_city' => 4709, 'id_state' => 14, 'name' => ' Benevides'],
            ['id_city' => 4710, 'id_state' => 14, 'name' => ' Benfica'],
            ['id_city' => 4711, 'id_state' => 14, 'name' => ' Boa Esperança'],
            ['id_city' => 4712, 'id_state' => 14, 'name' => ' Boa Fé'],
            ['id_city' => 4713, 'id_state' => 14, 'name' => ' Boa Sorte'],
            ['id_city' => 4714, 'id_state' => 14, 'name' => ' Boa Vista do Iririteua'],
            ['id_city' => 4715, 'id_state' => 14, 'name' => ' Boim'],
            ['id_city' => 4716, 'id_state' => 14, 'name' => ' Bom Jardim'],
            ['id_city' => 4717, 'id_state' => 14, 'name' => ' Bom Jesus do Tocantins'],
            ['id_city' => 4718, 'id_state' => 14, 'name' => ' Bonito'],
            ['id_city' => 4719, 'id_state' => 14, 'name' => ' Bragança'],
            ['id_city' => 4720, 'id_state' => 14, 'name' => ' Brasil Novo'],
            ['id_city' => 4721, 'id_state' => 14, 'name' => ' Brasília Legal'],
            ['id_city' => 4722, 'id_state' => 14, 'name' => ' Brejo do Meio'],
            ['id_city' => 4723, 'id_state' => 14, 'name' => ' Brejo Grande do Araguaia'],
            ['id_city' => 4724, 'id_state' => 14, 'name' => ' Breu Branco'],
            ['id_city' => 4725, 'id_state' => 14, 'name' => ' Breves'],
            ['id_city' => 4726, 'id_state' => 14, 'name' => ' Bujaru'],
            ['id_city' => 4727, 'id_state' => 14, 'name' => ' Cachoeira do Piriá'],
            ['id_city' => 4728, 'id_state' => 14, 'name' => ' Cachoeira do Arari'],
            ['id_city' => 4729, 'id_state' => 14, 'name' => ' Cafezal'],
            ['id_city' => 4730, 'id_state' => 14, 'name' => ' Cairari'],
            ['id_city' => 4731, 'id_state' => 14, 'name' => ' Caju'],
            ['id_city' => 4732, 'id_state' => 14, 'name' => ' Câmara do Marajó'],
            ['id_city' => 4733, 'id_state' => 14, 'name' => ' Cambuquira'],
            ['id_city' => 4734, 'id_state' => 14, 'name' => ' Cametá'],
            ['id_city' => 4735, 'id_state' => 14, 'name' => ' Camiranga'],
            ['id_city' => 4736, 'id_state' => 14, 'name' => ' Canaã dos Carajás'],
            ['id_city' => 4737, 'id_state' => 14, 'name' => ' Capanema'],
            ['id_city' => 4738, 'id_state' => 14, 'name' => ' Capitão Poço'],
            ['id_city' => 4739, 'id_state' => 14, 'name' => ' Caracará do Arari'],
            ['id_city' => 4740, 'id_state' => 14, 'name' => ' Carajás'],
            ['id_city' => 4741, 'id_state' => 14, 'name' => ' Carapajó'],
            ['id_city' => 4742, 'id_state' => 14, 'name' => ' Caraparu'],
            ['id_city' => 4743, 'id_state' => 14, 'name' => ' Caratateua'],
            ['id_city' => 4744, 'id_state' => 14, 'name' => ' Caripi'],
            ['id_city' => 4745, 'id_state' => 14, 'name' => ' Carrazedo'],
            ['id_city' => 4746, 'id_state' => 14, 'name' => ' Castanhal'],
            ['id_city' => 4747, 'id_state' => 14, 'name' => ' Castelo dos Sonhos'],
            ['id_city' => 4748, 'id_state' => 14, 'name' => ' Chaves'],
            ['id_city' => 4749, 'id_state' => 14, 'name' => ' Colares'],
            ['id_city' => 4750, 'id_state' => 14, 'name' => ' Conceição'],
            ['id_city' => 4751, 'id_state' => 14, 'name' => ' Conceição do Araguaia'],
            ['id_city' => 4752, 'id_state' => 14, 'name' => ' Concórdia do Pará'],
            ['id_city' => 4753, 'id_state' => 14, 'name' => ' Condeixa'],
            ['id_city' => 4754, 'id_state' => 14, 'name' => ' Coqueiro'],
            ['id_city' => 4755, 'id_state' => 14, 'name' => ' Cripurizão'],
            ['id_city' => 4756, 'id_state' => 14, 'name' => ' Cripurizinho'],
            ['id_city' => 4757, 'id_state' => 14, 'name' => ' Cuiú-Cuiú'],
            ['id_city' => 4758, 'id_state' => 14, 'name' => ' Cumaru do Norte'],
            ['id_city' => 4759, 'id_state' => 14, 'name' => ' Curionópolis'],
            ['id_city' => 4760, 'id_state' => 14, 'name' => ' Curralinho'],
            ['id_city' => 4761, 'id_state' => 14, 'name' => ' Curuá'],
            ['id_city' => 4762, 'id_state' => 14, 'name' => ' Curuaí'],
            ['id_city' => 4763, 'id_state' => 14, 'name' => ' Curuçá'],
            ['id_city' => 4764, 'id_state' => 14, 'name' => ' Curuçambaba'],
            ['id_city' => 4765, 'id_state' => 14, 'name' => ' Curumu'],
            ['id_city' => 4766, 'id_state' => 14, 'name' => ' Dom Eliseu'],
            ['id_city' => 4767, 'id_state' => 14, 'name' => ' Eldorado dos Carajás'],
            ['id_city' => 4768, 'id_state' => 14, 'name' => ' Emboraí'],
            ['id_city' => 4769, 'id_state' => 14, 'name' => ' Espírito Santo do Tauá'],
            ['id_city' => 4770, 'id_state' => 14, 'name' => ' Faro'],
            ['id_city' => 4771, 'id_state' => 14, 'name' => ' Fernandes Belo'],
            ['id_city' => 4772, 'id_state' => 14, 'name' => ' Flexal'],
            ['id_city' => 4773, 'id_state' => 14, 'name' => ' Floresta'],
            ['id_city' => 4774, 'id_state' => 14, 'name' => ' Floresta do Araguaia'],
            ['id_city' => 4775, 'id_state' => 14, 'name' => ' Garrafão do Norte'],
            ['id_city' => 4776, 'id_state' => 14, 'name' => ' Goianésia do Pará'],
            ['id_city' => 4777, 'id_state' => 14, 'name' => ' Gradaus'],
            ['id_city' => 4778, 'id_state' => 14, 'name' => ' Guajará-Açú'],
            ['id_city' => 4779, 'id_state' => 14, 'name' => ' Guajará-Miri'],
            ['id_city' => 4780, 'id_state' => 14, 'name' => ' Gurupá'],
            ['id_city' => 4781, 'id_state' => 14, 'name' => ' Gurupizinho'],
            ['id_city' => 4782, 'id_state' => 14, 'name' => ' Hidrelétrica Tucuruí'],
            ['id_city' => 4783, 'id_state' => 14, 'name' => ' Iataí'],
            ['id_city' => 4784, 'id_state' => 14, 'name' => ' Icoaraci'],
            ['id_city' => 4785, 'id_state' => 14, 'name' => ' Igarapé da Lama'],
            ['id_city' => 4786, 'id_state' => 14, 'name' => ' Igarapé-Açu'],
            ['id_city' => 4787, 'id_state' => 14, 'name' => ' Igarapé-Miri']
        ]);
    }
}