<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities12 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 7353, 'id_state' => 22, 'name' => ' Nova Vida'],
                ['id_city' => 7354, 'id_state' => 22, 'name' => ' Novo Horizonte do Oeste'],
                ['id_city' => 7355, 'id_state' => 22, 'name' => ' Ouro Preto do Oeste'],
                ['id_city' => 7356, 'id_state' => 22, 'name' => ' Parecis'],
                ['id_city' => 7357, 'id_state' => 22, 'name' => ' Pedras Negras'],
                ['id_city' => 7358, 'id_state' => 22, 'name' => ' Pimenta Bueno'],
                ['id_city' => 7359, 'id_state' => 22, 'name' => ' Pimenteiras do Oeste'],
                ['id_city' => 7360, 'id_state' => 22, 'name' => ' Porto Velho'],
                ['id_city' => 7361, 'id_state' => 22, 'name' => ' Presidente Médici'],
                ['id_city' => 7362, 'id_state' => 22, 'name' => ' Primavera de Rondônia'],
                ['id_city' => 7363, 'id_state' => 22, 'name' => ' Príncipe da Beira'],
                ['id_city' => 7364, 'id_state' => 22, 'name' => ' Rio Crespo'],
                ['id_city' => 7365, 'id_state' => 22, 'name' => ' Riozinho'],
                ['id_city' => 7366, 'id_state' => 22, 'name' => ' Rolim de Moura'],
                ['id_city' => 7367, 'id_state' => 22, 'name' => ' Santa Luzia D Oeste'],
                ['id_city' => 7368, 'id_state' => 22, 'name' => ' São Felipe D Oeste'],
                ['id_city' => 7369, 'id_state' => 22, 'name' => ' São Francisco do Guaporé'],
                ['id_city' => 7370, 'id_state' => 22, 'name' => ' São Miguel do Guaporé'],
                ['id_city' => 7371, 'id_state' => 22, 'name' => ' Seringueiras'],
                ['id_city' => 7372, 'id_state' => 22, 'name' => ' Tabajara'],
                ['id_city' => 7373, 'id_state' => 22, 'name' => ' Teixeirópolis'],
                ['id_city' => 7374, 'id_state' => 22, 'name' => ' Theobroma'],
                ['id_city' => 7375, 'id_state' => 22, 'name' => ' Urupá'],
                ['id_city' => 7376, 'id_state' => 22, 'name' => ' Vale do Anari'],
                ['id_city' => 7377, 'id_state' => 22, 'name' => ' Vale do Paraíso'],
                ['id_city' => 7378, 'id_state' => 22, 'name' => ' Extrema'],
                ['id_city' => 7379, 'id_state' => 22, 'name' => ' Vilhena'],
                ['id_city' => 7380, 'id_state' => 22, 'name' => ' Vista Alegre do Abunã'],
                ['id_city' => 7381, 'id_state' => 23, 'name' => ' Alto Alegre'],
                ['id_city' => 7382, 'id_state' => 23, 'name' => ' Amajari'],
                ['id_city' => 7383, 'id_state' => 23, 'name' => ' Boa Vista'],
                ['id_city' => 7384, 'id_state' => 23, 'name' => ' Bonfim'],
                ['id_city' => 7385, 'id_state' => 23, 'name' => ' Cantá'],
                ['id_city' => 7386, 'id_state' => 23, 'name' => ' Caracaraí'],
                ['id_city' => 7387, 'id_state' => 23, 'name' => ' Caroebe'],
                ['id_city' => 7388, 'id_state' => 23, 'name' => ' Iracema'],
                ['id_city' => 7389, 'id_state' => 23, 'name' => ' Mucajaí'],
                ['id_city' => 7390, 'id_state' => 23, 'name' => ' Normandia'],
                ['id_city' => 7391, 'id_state' => 23, 'name' => ' Pacaraima'],
                ['id_city' => 7392, 'id_state' => 23, 'name' => ' Rorainópolis'],
                ['id_city' => 7393, 'id_state' => 23, 'name' => ' São João da Baliza'],
                ['id_city' => 7394, 'id_state' => 23, 'name' => ' São Luiz'],
                ['id_city' => 7395, 'id_state' => 23, 'name' => ' Uiramutã'],
                ['id_city' => 7396, 'id_state' => 21, 'name' => ' Aceguá'],
                ['id_city' => 7397, 'id_state' => 21, 'name' => ' Afonso Rodrigues'],
                ['id_city' => 7398, 'id_state' => 21, 'name' => ' Água Santa'],
                ['id_city' => 7399, 'id_state' => 21, 'name' => ' Águas Claras'],
                ['id_city' => 7400, 'id_state' => 21, 'name' => ' Agudo'],
                ['id_city' => 7401, 'id_state' => 21, 'name' => ' Ajuricaba'],
                ['id_city' => 7402, 'id_state' => 21, 'name' => ' Albardão'],
                ['id_city' => 7403, 'id_state' => 21, 'name' => ' Alecrim'],
                ['id_city' => 7404, 'id_state' => 21, 'name' => ' Alegrete'],
                ['id_city' => 7405, 'id_state' => 21, 'name' => ' Alegria'],
                ['id_city' => 7406, 'id_state' => 21, 'name' => ' Alfredo Brenner'],
                ['id_city' => 7407, 'id_state' => 21, 'name' => ' Almirante Tamandaré do Sul'],
                ['id_city' => 7408, 'id_state' => 21, 'name' => ' Alpestre'],
                ['id_city' => 7409, 'id_state' => 21, 'name' => ' Alto Alegre'],
                ['id_city' => 7410, 'id_state' => 21, 'name' => ' Alto da União'],
                ['id_city' => 7411, 'id_state' => 21, 'name' => ' Alto Feliz'],
                ['id_city' => 7412, 'id_state' => 21, 'name' => ' Alto Paredão'],
                ['id_city' => 7413, 'id_state' => 21, 'name' => ' Alto Recreio'],
                ['id_city' => 7414, 'id_state' => 21, 'name' => ' Alto Uruguai'],
                ['id_city' => 7415, 'id_state' => 21, 'name' => ' Alvorada'],
                ['id_city' => 7416, 'id_state' => 21, 'name' => ' Amaral Ferrador'],
                ['id_city' => 7417, 'id_state' => 21, 'name' => ' Ametista do Sul'],
                ['id_city' => 7418, 'id_state' => 21, 'name' => ' André da Rocha'],
                ['id_city' => 7419, 'id_state' => 21, 'name' => ' Anta Gorda'],
                ['id_city' => 7420, 'id_state' => 21, 'name' => ' Antônio Kerpel'],
                ['id_city' => 7421, 'id_state' => 21, 'name' => ' Antônio Prado'],
                ['id_city' => 7422, 'id_state' => 21, 'name' => ' Arambaré'],
                ['id_city' => 7423, 'id_state' => 21, 'name' => ' Araricá'],
                ['id_city' => 7424, 'id_state' => 21, 'name' => ' Aratiba'],
                ['id_city' => 7425, 'id_state' => 21, 'name' => ' Arco Verde'],
                ['id_city' => 7426, 'id_state' => 21, 'name' => ' Arco-Íris'],
                ['id_city' => 7427, 'id_state' => 21, 'name' => ' Arroio Canoas'],
                ['id_city' => 7428, 'id_state' => 21, 'name' => ' Arroio do Meio'],
                ['id_city' => 7429, 'id_state' => 21, 'name' => ' Arroio do Padre'],
                ['id_city' => 7430, 'id_state' => 21, 'name' => ' Arroio do Sal'],
                ['id_city' => 7431, 'id_state' => 21, 'name' => ' Arroio do Só'],
                ['id_city' => 7432, 'id_state' => 21, 'name' => ' Arroio do Tigre'],
                ['id_city' => 7433, 'id_state' => 21, 'name' => ' Arroio dos Ratos'],
                ['id_city' => 7434, 'id_state' => 21, 'name' => ' Arroio Grande'],
                ['id_city' => 7435, 'id_state' => 21, 'name' => ' Árvore Só'],
                ['id_city' => 7436, 'id_state' => 21, 'name' => ' Arvorezinha'],
                ['id_city' => 7437, 'id_state' => 21, 'name' => ' Atafona'],
                ['id_city' => 7438, 'id_state' => 21, 'name' => ' Atiaçu'],
                ['id_city' => 7439, 'id_state' => 21, 'name' => ' Augusto Pestana'],
                ['id_city' => 7440, 'id_state' => 21, 'name' => ' Áurea'],
                ['id_city' => 7441, 'id_state' => 21, 'name' => ' Avelino Paranhos'],
                ['id_city' => 7442, 'id_state' => 21, 'name' => ' Azevedo Sodré'],
                ['id_city' => 7443, 'id_state' => 21, 'name' => ' Bacupari'],
                ['id_city' => 7444, 'id_state' => 21, 'name' => ' Bagé'],
                ['id_city' => 7445, 'id_state' => 21, 'name' => ' Baliza'],
                ['id_city' => 7446, 'id_state' => 21, 'name' => ' Balneário Pinhal'],
                ['id_city' => 7447, 'id_state' => 21, 'name' => ' Banhado do Colégio'],
                ['id_city' => 7448, 'id_state' => 21, 'name' => ' Barão'],
                ['id_city' => 7449, 'id_state' => 21, 'name' => ' Barão de Cotegipe'],
                ['id_city' => 7450, 'id_state' => 21, 'name' => ' Barão do Triunfo'],
                ['id_city' => 7451, 'id_state' => 21, 'name' => ' Barra do Guarita'],
                ['id_city' => 7452, 'id_state' => 21, 'name' => ' Barra do Ouro'],
                ['id_city' => 7453, 'id_state' => 21, 'name' => ' Barra do Quaraí'],
                ['id_city' => 7454, 'id_state' => 21, 'name' => ' Barra do Ribeiro'],
                ['id_city' => 7455, 'id_state' => 21, 'name' => ' Barra do Rio Azul'],
                ['id_city' => 7456, 'id_state' => 21, 'name' => ' Barra Funda'],
                ['id_city' => 7457, 'id_state' => 21, 'name' => ' Barracão'],
                ['id_city' => 7458, 'id_state' => 21, 'name' => ' Barreirinho'],
                ['id_city' => 7459, 'id_state' => 21, 'name' => ' Barreiro'],
                ['id_city' => 7460, 'id_state' => 21, 'name' => ' Barro Preto'],
                ['id_city' => 7461, 'id_state' => 21, 'name' => ' Barro Vermelho'],
                ['id_city' => 7462, 'id_state' => 21, 'name' => ' Barros Cassal'],
                ['id_city' => 7463, 'id_state' => 21, 'name' => ' Basílio'],
                ['id_city' => 7464, 'id_state' => 21, 'name' => ' Bela Vista'],
                ['id_city' => 7465, 'id_state' => 21, 'name' => ' Beluno'],
                ['id_city' => 7466, 'id_state' => 21, 'name' => ' Benjamin Constant do Sul'],
                ['id_city' => 7467, 'id_state' => 21, 'name' => ' Bento Gonçalves'],
                ['id_city' => 7468, 'id_state' => 21, 'name' => ' Bexiga'],
                ['id_city' => 7469, 'id_state' => 21, 'name' => ' Boa Esperança'],
                ['id_city' => 7470, 'id_state' => 21, 'name' => ' Boa Vista'],
                ['id_city' => 7471, 'id_state' => 21, 'name' => ' Boa Vista das Missões'],
                ['id_city' => 7472, 'id_state' => 21, 'name' => ' Boa Vista do Buricá'],
                ['id_city' => 7473, 'id_state' => 21, 'name' => ' Boa Vista do Cadeado'],
                ['id_city' => 7474, 'id_state' => 21, 'name' => ' Boa Vista do Incra'],
                ['id_city' => 7475, 'id_state' => 21, 'name' => ' Boa Vista do Sul'],
                ['id_city' => 7476, 'id_state' => 21, 'name' => ' Boca do Monte'],
                ['id_city' => 7477, 'id_state' => 21, 'name' => ' Boi Preto'],
                ['id_city' => 7478, 'id_state' => 21, 'name' => ' Bojuru'],
                ['id_city' => 7479, 'id_state' => 21, 'name' => ' Bom Jardim'],
                ['id_city' => 7480, 'id_state' => 21, 'name' => ' Bom Jesus'],
                ['id_city' => 7481, 'id_state' => 21, 'name' => ' Bom Princípio'],
                ['id_city' => 7482, 'id_state' => 21, 'name' => ' Bom Progresso'],
                ['id_city' => 7483, 'id_state' => 21, 'name' => ' Bom Retiro'],
                ['id_city' => 7484, 'id_state' => 21, 'name' => ' Bom Retiro do Guaíba'],
                ['id_city' => 7485, 'id_state' => 21, 'name' => ' Bom Retiro do Sul'],
                ['id_city' => 7486, 'id_state' => 21, 'name' => ' Bonito'],
                ['id_city' => 7487, 'id_state' => 21, 'name' => ' Boqueirão'],
                ['id_city' => 7488, 'id_state' => 21, 'name' => ' Vila Boqueirão'],
                ['id_city' => 7489, 'id_state' => 21, 'name' => ' Boqueirão do Leão'],
                ['id_city' => 7490, 'id_state' => 21, 'name' => ' Bororé'],
                ['id_city' => 7491, 'id_state' => 21, 'name' => ' Bossoroca'],
                ['id_city' => 7492, 'id_state' => 21, 'name' => ' Botucaraí'],
                ['id_city' => 7493, 'id_state' => 21, 'name' => ' Braga'],
                ['id_city' => 7494, 'id_state' => 21, 'name' => ' Brochier'],
                ['id_city' => 7495, 'id_state' => 21, 'name' => ' Buriti'],
                ['id_city' => 7496, 'id_state' => 21, 'name' => ' Butiá'],
                ['id_city' => 7497, 'id_state' => 21, 'name' => ' Butiás'],
                ['id_city' => 7498, 'id_state' => 21, 'name' => ' Caçapava do Sul'],
                ['id_city' => 7499, 'id_state' => 21, 'name' => ' Cacequi'],
                ['id_city' => 7500, 'id_state' => 21, 'name' => ' Cachoeira do Sul'],
                ['id_city' => 7501, 'id_state' => 21, 'name' => ' Cachoeirinha'],
                ['id_city' => 7502, 'id_state' => 21, 'name' => ' Cacique Doble'],
                ['id_city' => 7503, 'id_state' => 21, 'name' => ' Cadorna'],
                ['id_city' => 7504, 'id_state' => 21, 'name' => ' Caibaté'],
                ['id_city' => 7505, 'id_state' => 21, 'name' => ' Caiçara'],
                ['id_city' => 7506, 'id_state' => 21, 'name' => ' Camaquã'],
                ['id_city' => 7507, 'id_state' => 21, 'name' => ' Camargo'],
                ['id_city' => 7508, 'id_state' => 21, 'name' => ' Cambará do Sul'],
                ['id_city' => 7509, 'id_state' => 21, 'name' => ' Pains'],
                ['id_city' => 7510, 'id_state' => 21, 'name' => ' Campestre'],
                ['id_city' => 7511, 'id_state' => 21, 'name' => ' Campestre da Serra'],
                ['id_city' => 7512, 'id_state' => 21, 'name' => ' Campina das Missões'],
                ['id_city' => 7513, 'id_state' => 21, 'name' => ' Campina Redonda'],
                ['id_city' => 7514, 'id_state' => 21, 'name' => ' Campinas'],
                ['id_city' => 7515, 'id_state' => 21, 'name' => ' Campinas do Sul'],
                ['id_city' => 7516, 'id_state' => 21, 'name' => ' Campo Bom'],
                ['id_city' => 7517, 'id_state' => 21, 'name' => ' Campo Branco'],
                ['id_city' => 7518, 'id_state' => 21, 'name' => ' Campo do Meio'],
                ['id_city' => 7519, 'id_state' => 21, 'name' => ' Campo Novo'],
                ['id_city' => 7520, 'id_state' => 21, 'name' => ' Campo Santo'],
                ['id_city' => 7521, 'id_state' => 21, 'name' => ' Campo Seco'],
                ['id_city' => 7522, 'id_state' => 21, 'name' => ' Campo Vicente'],
                ['id_city' => 7523, 'id_state' => 21, 'name' => ' Campos Borges'],
                ['id_city' => 7524, 'id_state' => 21, 'name' => ' Candelária'],
                ['id_city' => 7525, 'id_state' => 21, 'name' => ' Cândido Freire'],
                ['id_city' => 7526, 'id_state' => 21, 'name' => ' Cândido Godói'],
                ['id_city' => 7527, 'id_state' => 21, 'name' => ' Candiota'],
                ['id_city' => 7528, 'id_state' => 21, 'name' => ' Canela'],
                ['id_city' => 7529, 'id_state' => 21, 'name' => ' Canguçu'],
                ['id_city' => 7530, 'id_state' => 21, 'name' => ' Canhembora'],
                ['id_city' => 7531, 'id_state' => 21, 'name' => ' Canoas'],
                ['id_city' => 7532, 'id_state' => 21, 'name' => ' Canudos do Vale'],
                ['id_city' => 7533, 'id_state' => 21, 'name' => ' Capané'],
                ['id_city' => 7534, 'id_state' => 21, 'name' => ' Capão Bonito do Sul'],
                ['id_city' => 7535, 'id_state' => 21, 'name' => ' Capão Bonito'],
                ['id_city' => 7536, 'id_state' => 21, 'name' => ' Capão Comprido'],
                ['id_city' => 7537, 'id_state' => 21, 'name' => ' Capão da Canoa'],
                ['id_city' => 7538, 'id_state' => 21, 'name' => ' Capão da Porteira'],
                ['id_city' => 7539, 'id_state' => 21, 'name' => ' Capão do Cedro'],
                ['id_city' => 7540, 'id_state' => 21, 'name' => ' Capão do Cipó'],
                ['id_city' => 7541, 'id_state' => 21, 'name' => ' Capão do Leão'],
                ['id_city' => 7542, 'id_state' => 21, 'name' => ' Capela de Santana'],
                ['id_city' => 7543, 'id_state' => 21, 'name' => ' Capela Velha'],
                ['id_city' => 7544, 'id_state' => 21, 'name' => ' Capinzal'],
                ['id_city' => 7545, 'id_state' => 21, 'name' => ' Capitão'],
                ['id_city' => 7546, 'id_state' => 21, 'name' => ' Capivari do Sul'],
                ['id_city' => 7547, 'id_state' => 21, 'name' => ' Capivarita'],
                ['id_city' => 7548, 'id_state' => 21, 'name' => ' Capo-Erê'],
                ['id_city' => 7549, 'id_state' => 21, 'name' => ' Capoeira Grande'],
                ['id_city' => 7550, 'id_state' => 21, 'name' => ' Caraá'],
                ['id_city' => 7551, 'id_state' => 21, 'name' => ' Carajá Seival'],
                ['id_city' => 7552, 'id_state' => 21, 'name' => ' Carazinho'],
                ['id_city' => 7553, 'id_state' => 21, 'name' => ' Carlos Barbosa'],
                ['id_city' => 7554, 'id_state' => 21, 'name' => ' Carlos Gomes'],
                ['id_city' => 7555, 'id_state' => 21, 'name' => ' Carovi'],
                ['id_city' => 7556, 'id_state' => 21, 'name' => ' Casca'],
                ['id_city' => 7557, 'id_state' => 21, 'name' => ' Cascata'],
                ['id_city' => 7558, 'id_state' => 21, 'name' => ' Caseiros'],
                ['id_city' => 7559, 'id_state' => 21, 'name' => ' Castelinho'],
                ['id_city' => 7560, 'id_state' => 21, 'name' => ' Catuípe'],
                ['id_city' => 7561, 'id_state' => 21, 'name' => ' Cavajureta'],
                ['id_city' => 7562, 'id_state' => 21, 'name' => ' Caverá'],
                ['id_city' => 7563, 'id_state' => 21, 'name' => ' Caxias do Sul'],
                ['id_city' => 7564, 'id_state' => 21, 'name' => ' Cazuza Ferreira'],
                ['id_city' => 7565, 'id_state' => 21, 'name' => ' Cedro Marcado'],
                ['id_city' => 7566, 'id_state' => 21, 'name' => ' Centenário'],
                ['id_city' => 7567, 'id_state' => 21, 'name' => ' Centro Linha Brasil'],
                ['id_city' => 7568, 'id_state' => 21, 'name' => ' Cerrito'],
                ['id_city' => 7569, 'id_state' => 21, 'name' => ' Cerrito Alegre'],
                ['id_city' => 7570, 'id_state' => 21, 'name' => ' Cerrito do Ouro'],
                ['id_city' => 7571, 'id_state' => 21, 'name' => ' Cerro Alto'],
                ['id_city' => 7572, 'id_state' => 21, 'name' => ' Cerro Branco'],
                ['id_city' => 7573, 'id_state' => 21, 'name' => ' Cerro Claro'],
                ['id_city' => 7574, 'id_state' => 21, 'name' => ' Cerro do Martins'],
                ['id_city' => 7575, 'id_state' => 21, 'name' => ' Cerro do Roque'],
                ['id_city' => 7576, 'id_state' => 21, 'name' => ' Cerro Grande'],
                ['id_city' => 7577, 'id_state' => 21, 'name' => ' Cerro Grande do Sul'],
                ['id_city' => 7578, 'id_state' => 21, 'name' => ' Cerro Largo'],
                ['id_city' => 7579, 'id_state' => 21, 'name' => ' Chapada'],
                ['id_city' => 7580, 'id_state' => 21, 'name' => ' Charqueadas'],
                ['id_city' => 7581, 'id_state' => 21, 'name' => ' Charrua'],
                ['id_city' => 7582, 'id_state' => 21, 'name' => ' Chiapetta'],
                ['id_city' => 7583, 'id_state' => 21, 'name' => ' Chico-lomã'],
                ['id_city' => 7584, 'id_state' => 21, 'name' => ' Chimarrão'],
                ['id_city' => 7585, 'id_state' => 21, 'name' => ' Chorão'],
                ['id_city' => 7586, 'id_state' => 21, 'name' => ' Chuí'],
                ['id_city' => 7587, 'id_state' => 21, 'name' => ' Chuvisca'],
                ['id_city' => 7588, 'id_state' => 21, 'name' => ' Cidreira'],
                ['id_city' => 7589, 'id_state' => 21, 'name' => ' Cinqüentenário'],
                ['id_city' => 7590, 'id_state' => 21, 'name' => ' Ciríaco'],
                ['id_city' => 7591, 'id_state' => 21, 'name' => ' Clara'],
                ['id_city' => 7592, 'id_state' => 21, 'name' => ' Clemente Argolo'],
                ['id_city' => 7593, 'id_state' => 21, 'name' => ' Coimbra'],
                ['id_city' => 7594, 'id_state' => 21, 'name' => ' Colinas'],
                ['id_city' => 7595, 'id_state' => 21, 'name' => ' Colônia das Almas'],
                ['id_city' => 7596, 'id_state' => 21, 'name' => ' Colônia Medeiros'],
                ['id_city' => 7597, 'id_state' => 21, 'name' => ' Colônia Municipal'],
                ['id_city' => 7598, 'id_state' => 21, 'name' => ' Colônia Nova'],
                ['id_city' => 7599, 'id_state' => 21, 'name' => ' Colônia São João'],
                ['id_city' => 7600, 'id_state' => 21, 'name' => ' Colônia Z-3'],
                ['id_city' => 7601, 'id_state' => 21, 'name' => ' Coloninha'],
                ['id_city' => 7602, 'id_state' => 21, 'name' => ' Colorado'],
                ['id_city' => 7603, 'id_state' => 21, 'name' => ' Comandai'],
                ['id_city' => 7604, 'id_state' => 21, 'name' => ' Condor'],
                ['id_city' => 7605, 'id_state' => 21, 'name' => ' Consolata'],
                ['id_city' => 7606, 'id_state' => 21, 'name' => ' Constantina'],
                ['id_city' => 7607, 'id_state' => 21, 'name' => ' Coqueiro Baixo'],
                ['id_city' => 7608, 'id_state' => 21, 'name' => ' Coqueiros do Sul'],
                ['id_city' => 7609, 'id_state' => 21, 'name' => ' Cordilheira'],
                ['id_city' => 7610, 'id_state' => 21, 'name' => ' Coroados'],
                ['id_city' => 7611, 'id_state' => 21, 'name' => ' Coronel Barros'],
                ['id_city' => 7612, 'id_state' => 21, 'name' => ' Coronel Bicaco'],
                ['id_city' => 7613, 'id_state' => 21, 'name' => ' Coronel Finzito'],
                ['id_city' => 7614, 'id_state' => 21, 'name' => ' Coronel Pilar'],
                ['id_city' => 7615, 'id_state' => 21, 'name' => ' Coronel Teixeira'],
                ['id_city' => 7616, 'id_state' => 21, 'name' => ' Cortado'],
                ['id_city' => 7617, 'id_state' => 21, 'name' => ' Costa da Cadeia'],
                ['id_city' => 7618, 'id_state' => 21, 'name' => ' Costão'],
                ['id_city' => 7619, 'id_state' => 21, 'name' => ' Cotiporã'],
                ['id_city' => 7620, 'id_state' => 21, 'name' => ' Coxilha'],
                ['id_city' => 7621, 'id_state' => 21, 'name' => ' Coxilha Grande'],
                ['id_city' => 7622, 'id_state' => 21, 'name' => ' CR-1'],
                ['id_city' => 7623, 'id_state' => 21, 'name' => ' Crissiumal'],
                ['id_city' => 7624, 'id_state' => 21, 'name' => ' Cristal'],
                ['id_city' => 7625, 'id_state' => 21, 'name' => ' Cristal do Sul'],
                ['id_city' => 7626, 'id_state' => 21, 'name' => ' Criúva'],
                ['id_city' => 7627, 'id_state' => 21, 'name' => ' Cruz Alta'],
                ['id_city' => 7628, 'id_state' => 21, 'name' => ' Cruzaltense'],
                ['id_city' => 7629, 'id_state' => 21, 'name' => ' Cruzeiro'],
                ['id_city' => 7630, 'id_state' => 21, 'name' => ' Cruzeiro do Sul'],
                ['id_city' => 7631, 'id_state' => 21, 'name' => ' Curral Alto'],
                ['id_city' => 7632, 'id_state' => 21, 'name' => ' Curumim'],
                ['id_city' => 7633, 'id_state' => 21, 'name' => ' Daltro Filho'],
                ['id_city' => 7634, 'id_state' => 21, 'name' => ' Dário Lassance'],
                ['id_city' => 7635, 'id_state' => 21, 'name' => ' David Canabarro'],
                ['id_city' => 7636, 'id_state' => 21, 'name' => ' Delfina'],
                ['id_city' => 7637, 'id_state' => 21, 'name' => ' Deodoro'],
                ['id_city' => 7638, 'id_state' => 21, 'name' => ' Depósito'],
                ['id_city' => 7639, 'id_state' => 21, 'name' => ' Derrubadas'],
                ['id_city' => 7640, 'id_state' => 21, 'name' => ' Dezesseis de Novembro'],
                ['id_city' => 7641, 'id_state' => 21, 'name' => ' Dilermando de Aguiar'],
                ['id_city' => 7642, 'id_state' => 21, 'name' => ' Divino'],
                ['id_city' => 7643, 'id_state' => 21, 'name' => ' Dois Irmãos'],
                ['id_city' => 7644, 'id_state' => 21, 'name' => ' Dois Irmãos das Missões'],
                ['id_city' => 7645, 'id_state' => 21, 'name' => ' Dois Lajeados'],
                ['id_city' => 7646, 'id_state' => 21, 'name' => ' São José do Sul'],
                ['id_city' => 7647, 'id_state' => 21, 'name' => ' Dom Feliciano'],
                ['id_city' => 7648, 'id_state' => 21, 'name' => ' Dom Pedrito'],
                ['id_city' => 7649, 'id_state' => 21, 'name' => ' Dom Pedro de Alcântara'],
                ['id_city' => 7650, 'id_state' => 21, 'name' => ' Dona Francisca'],
                ['id_city' => 7651, 'id_state' => 21, 'name' => ' Dona Otília'],
                ['id_city' => 7652, 'id_state' => 21, 'name' => ' Dourado'],
                ['id_city' => 7653, 'id_state' => 21, 'name' => ' Bozano'],
                ['id_city' => 7654, 'id_state' => 21, 'name' => ' Doutor Edgardo Pereira Velho'],
                ['id_city' => 7655, 'id_state' => 21, 'name' => ' Doutor Maurício Cardoso'],
                ['id_city' => 7656, 'id_state' => 21, 'name' => ' Doutor Ricardo'],
                ['id_city' => 7657, 'id_state' => 21, 'name' => ' Eldorado do Sul'],
                ['id_city' => 7658, 'id_state' => 21, 'name' => ' Eletra'],
                ['id_city' => 7659, 'id_state' => 21, 'name' => ' Encantado'],
                ['id_city' => 7660, 'id_state' => 21, 'name' => ' Encruzilhada'],
                ['id_city' => 7661, 'id_state' => 21, 'name' => ' Encruzilhada do Sul'],
                ['id_city' => 7662, 'id_state' => 21, 'name' => ' Engenho Velho'],
                ['id_city' => 7663, 'id_state' => 21, 'name' => ' Entre Rios do Sul'],
                ['id_city' => 7664, 'id_state' => 21, 'name' => ' Entre-Ijuís'],
                ['id_city' => 7665, 'id_state' => 21, 'name' => ' Entrepelado'],
                ['id_city' => 7666, 'id_state' => 21, 'name' => ' Erebango'],
                ['id_city' => 7667, 'id_state' => 21, 'name' => ' Erechim'],
                ['id_city' => 7668, 'id_state' => 21, 'name' => ' Ernestina'],
                ['id_city' => 7669, 'id_state' => 21, 'name' => ' Ernesto Alves'],
                ['id_city' => 7670, 'id_state' => 21, 'name' => ' Erval Grande'],
                ['id_city' => 7671, 'id_state' => 21, 'name' => ' Erval Seco'],
                ['id_city' => 7672, 'id_state' => 21, 'name' => ' Esmeralda'],
                ['id_city' => 7673, 'id_state' => 21, 'name' => ' Esperança do Sul'],
                ['id_city' => 7674, 'id_state' => 21, 'name' => ' Espigão'],
                ['id_city' => 7675, 'id_state' => 21, 'name' => ' Espigão Alto'],
                ['id_city' => 7676, 'id_state' => 21, 'name' => ' Espinilho Grande'],
                ['id_city' => 7677, 'id_state' => 21, 'name' => ' Espírito Santo'],
                ['id_city' => 7678, 'id_state' => 21, 'name' => ' Espumoso'],
                ['id_city' => 7679, 'id_state' => 21, 'name' => ' Esquina Araújo'],
                ['id_city' => 7680, 'id_state' => 21, 'name' => ' Esquina Bom Sucesso'],
                ['id_city' => 7681, 'id_state' => 21, 'name' => ' Esquina Gaúcha'],
                ['id_city' => 7682, 'id_state' => 21, 'name' => ' Esquina Ipiranga'],
                ['id_city' => 7683, 'id_state' => 21, 'name' => ' Esquina Piratini'],
                ['id_city' => 7684, 'id_state' => 21, 'name' => ' Estação'],
                ['id_city' => 7685, 'id_state' => 21, 'name' => ' Estância Grande'],
                ['id_city' => 7686, 'id_state' => 21, 'name' => ' Estância Velha'],
                ['id_city' => 7687, 'id_state' => 21, 'name' => ' Esteio'],
                ['id_city' => 7688, 'id_state' => 21, 'name' => ' Esteira'],
                ['id_city' => 7689, 'id_state' => 21, 'name' => ' Estreito'],
                ['id_city' => 7690, 'id_state' => 21, 'name' => ' Estrela'],
                ['id_city' => 7691, 'id_state' => 21, 'name' => ' Estrela Velha'],
                ['id_city' => 7692, 'id_state' => 21, 'name' => ' Eugênio de Castro'],
                ['id_city' => 7693, 'id_state' => 21, 'name' => ' Evangelista'],
                ['id_city' => 7694, 'id_state' => 21, 'name' => ' Fagundes Varela'],
                ['id_city' => 7695, 'id_state' => 21, 'name' => ' Fão'],
                ['id_city' => 7696, 'id_state' => 21, 'name' => ' Faria Lemos'],
                ['id_city' => 7697, 'id_state' => 21, 'name' => ' Farinhas'],
                ['id_city' => 7698, 'id_state' => 21, 'name' => ' Farrapos'],
                ['id_city' => 7699, 'id_state' => 21, 'name' => ' Farroupilha'],
                ['id_city' => 7700, 'id_state' => 21, 'name' => ' Faxinal'],
                ['id_city' => 7701, 'id_state' => 21, 'name' => ' Faxinal do Soturno'],
                ['id_city' => 7702, 'id_state' => 21, 'name' => ' Faxinalzinho'],
                ['id_city' => 7703, 'id_state' => 21, 'name' => ' Fazenda Fialho'],
                ['id_city' => 7704, 'id_state' => 21, 'name' => ' Fazenda Souza'],
                ['id_city' => 7705, 'id_state' => 21, 'name' => ' Fazenda Vilanova'],
                ['id_city' => 7706, 'id_state' => 21, 'name' => ' Feliz'],
                ['id_city' => 7707, 'id_state' => 21, 'name' => ' Ferreira'],
                ['id_city' => 7708, 'id_state' => 21, 'name' => ' Flores da Cunha'],
                ['id_city' => 7709, 'id_state' => 21, 'name' => ' Floresta'],
                ['id_city' => 7710, 'id_state' => 21, 'name' => ' Floriano Peixoto'],
                ['id_city' => 7711, 'id_state' => 21, 'name' => ' Flórida'],
                ['id_city' => 7712, 'id_state' => 21, 'name' => ' Fontoura Xavier'],
                ['id_city' => 7713, 'id_state' => 21, 'name' => ' Formigueiro'],
                ['id_city' => 7714, 'id_state' => 21, 'name' => ' Forninho'],
                ['id_city' => 7715, 'id_state' => 21, 'name' => ' Forquetinha'],
                ['id_city' => 7716, 'id_state' => 21, 'name' => ' Fortaleza dos Valos'],
                ['id_city' => 7717, 'id_state' => 21, 'name' => ' Frederico Westphalen'],
                ['id_city' => 7718, 'id_state' => 21, 'name' => ' Frei Sebastião'],
                ['id_city' => 7719, 'id_state' => 21, 'name' => ' Freire'],
                ['id_city' => 7720, 'id_state' => 21, 'name' => ' Garibaldi'],
                ['id_city' => 7721, 'id_state' => 21, 'name' => ' Garibaldina'],
                ['id_city' => 7722, 'id_state' => 21, 'name' => ' Garruchos'],
                ['id_city' => 7723, 'id_state' => 21, 'name' => ' Gaurama'],
                ['id_city' => 7724, 'id_state' => 21, 'name' => ' General Câmara'],
                ['id_city' => 7725, 'id_state' => 21, 'name' => ' Gentil'],
                ['id_city' => 7726, 'id_state' => 21, 'name' => ' Getúlio Vargas'],
                ['id_city' => 7727, 'id_state' => 21, 'name' => ' Giruá'],
                ['id_city' => 7728, 'id_state' => 21, 'name' => ' Glória'],
                ['id_city' => 7729, 'id_state' => 21, 'name' => ' Glorinha'],
                ['id_city' => 7730, 'id_state' => 21, 'name' => ' Goio-En'],
                ['id_city' => 7731, 'id_state' => 21, 'name' => ' Gramado'],
                ['id_city' => 7732, 'id_state' => 21, 'name' => ' Gramado dos Loureiros'],
                ['id_city' => 7733, 'id_state' => 21, 'name' => ' Gramado São Pedro'],
                ['id_city' => 7734, 'id_state' => 21, 'name' => ' Gramado Xavier'],
                ['id_city' => 7735, 'id_state' => 21, 'name' => ' Gravataí'],
                ['id_city' => 7736, 'id_state' => 21, 'name' => ' Guabiju'],
                ['id_city' => 7737, 'id_state' => 21, 'name' => ' Guaíba'],
                ['id_city' => 7738, 'id_state' => 21, 'name' => ' Guaporé'],
                ['id_city' => 7739, 'id_state' => 21, 'name' => ' Guarani das Missões'],
                ['id_city' => 7740, 'id_state' => 21, 'name' => ' Guassupi'],
                ['id_city' => 7741, 'id_state' => 21, 'name' => ' Harmonia'],
                ['id_city' => 7742, 'id_state' => 21, 'name' => ' Herval'],
                ['id_city' => 7743, 'id_state' => 21, 'name' => ' Herveiras'],
                ['id_city' => 7744, 'id_state' => 21, 'name' => ' Hidráulica'],
                ['id_city' => 7745, 'id_state' => 21, 'name' => ' Horizontina'],
                ['id_city' => 7746, 'id_state' => 21, 'name' => ' Hulha Negra'],
                ['id_city' => 7747, 'id_state' => 21, 'name' => ' Humaitá'],
                ['id_city' => 7748, 'id_state' => 21, 'name' => ' Ibarama'],
                ['id_city' => 7749, 'id_state' => 21, 'name' => ' Ibaré'],
                ['id_city' => 7750, 'id_state' => 21, 'name' => ' Ibiaçá'],
                ['id_city' => 7751, 'id_state' => 21, 'name' => ' Ibiraiaras'],
                ['id_city' => 7752, 'id_state' => 21, 'name' => ' Ibirapuitã'],
                ['id_city' => 7753, 'id_state' => 21, 'name' => ' Ibirubá'],
                ['id_city' => 7754, 'id_state' => 21, 'name' => ' Igrejinha'],
                ['id_city' => 7755, 'id_state' => 21, 'name' => ' Ijucapirama'],
                ['id_city' => 7756, 'id_state' => 21, 'name' => ' Ijuí'],
                ['id_city' => 7757, 'id_state' => 21, 'name' => ' Ilha dos Marinheiros'],
                ['id_city' => 7758, 'id_state' => 21, 'name' => ' Ilópolis'],
                ['id_city' => 7759, 'id_state' => 21, 'name' => ' Imbé'],
                ['id_city' => 7760, 'id_state' => 21, 'name' => ' Imigrante'],
                ['id_city' => 7761, 'id_state' => 21, 'name' => ' Independência'],
                ['id_city' => 7762, 'id_state' => 21, 'name' => ' Inhacorá'],
                ['id_city' => 7763, 'id_state' => 21, 'name' => ' Ipê'],
                ['id_city' => 7764, 'id_state' => 21, 'name' => ' Ipiranga'],
                ['id_city' => 7765, 'id_state' => 21, 'name' => ' Ipiranga do Sul'],
                ['id_city' => 7766, 'id_state' => 21, 'name' => ' Ipuaçu'],
                ['id_city' => 7767, 'id_state' => 21, 'name' => ' Iraí'],
                ['id_city' => 7768, 'id_state' => 21, 'name' => ' Iruí'],
                ['id_city' => 7769, 'id_state' => 21, 'name' => ' Itaara'],
                ['id_city' => 7770, 'id_state' => 21, 'name' => ' Itacolomi'],
                ['id_city' => 7771, 'id_state' => 21, 'name' => ' Itacurubi'],
                ['id_city' => 7772, 'id_state' => 21, 'name' => ' Itaí'],
                ['id_city' => 7773, 'id_state' => 21, 'name' => ' Itaimbezinho'],
                ['id_city' => 7774, 'id_state' => 21, 'name' => ' Itão'],
                ['id_city' => 7775, 'id_state' => 21, 'name' => ' Itapuã'],
                ['id_city' => 7776, 'id_state' => 21, 'name' => ' Itapuca'],
                ['id_city' => 7777, 'id_state' => 21, 'name' => ' Itapucá'],
                ['id_city' => 7778, 'id_state' => 21, 'name' => ' Itaqui'],
                ['id_city' => 7779, 'id_state' => 21, 'name' => ' Itati'],
                ['id_city' => 7780, 'id_state' => 21, 'name' => ' Itatiba do Sul'],
                ['id_city' => 7781, 'id_state' => 21, 'name' => ' Itaúba'],
                ['id_city' => 7782, 'id_state' => 21, 'name' => ' Ituim'],
                ['id_city' => 7783, 'id_state' => 21, 'name' => ' Ivaí'],
                ['id_city' => 7784, 'id_state' => 21, 'name' => ' Ivorá'],
                ['id_city' => 7785, 'id_state' => 21, 'name' => ' Ivoti'],
                ['id_city' => 7786, 'id_state' => 21, 'name' => ' Jaboticaba'],
                ['id_city' => 7787, 'id_state' => 21, 'name' => ' Jacuizinho'],
                ['id_city' => 7788, 'id_state' => 21, 'name' => ' Jacutinga'],
                ['id_city' => 7789, 'id_state' => 21, 'name' => ' Jaguarão'],
                ['id_city' => 7790, 'id_state' => 21, 'name' => ' Jaguarete'],
                ['id_city' => 7791, 'id_state' => 21, 'name' => ' Jaguari'],
                ['id_city' => 7792, 'id_state' => 21, 'name' => ' Jansen'],
                ['id_city' => 7793, 'id_state' => 21, 'name' => ' Jaquirana'],
                ['id_city' => 7794, 'id_state' => 21, 'name' => ' Jari'],
                ['id_city' => 7795, 'id_state' => 21, 'name' => ' Jazidas'],
                ['id_city' => 7796, 'id_state' => 21, 'name' => ' João Arregui'],
                ['id_city' => 7797, 'id_state' => 21, 'name' => ' João Rodrigues'],
                ['id_city' => 7798, 'id_state' => 21, 'name' => ' Joça Tavares'],
                ['id_city' => 7799, 'id_state' => 21, 'name' => ' Jóia'],
                ['id_city' => 7800, 'id_state' => 21, 'name' => ' José Otávio'],
                ['id_city' => 7801, 'id_state' => 21, 'name' => ' Juá'],
                ['id_city' => 7802, 'id_state' => 21, 'name' => ' Júlio de Castilhos'],
                ['id_city' => 7803, 'id_state' => 21, 'name' => ' Lagoa Bonita do Sul'],
                ['id_city' => 7804, 'id_state' => 21, 'name' => ' Lagoa dos Três Cantos'],
                ['id_city' => 7805, 'id_state' => 21, 'name' => ' Lagoa Vermelha'],
                ['id_city' => 7806, 'id_state' => 21, 'name' => ' Lagoão'],
                ['id_city' => 7807, 'id_state' => 21, 'name' => ' Lajeado'],
                ['id_city' => 7808, 'id_state' => 21, 'name' => ' Lajeado Bonito'],
                ['id_city' => 7809, 'id_state' => 21, 'name' => ' Lajeado Cerne'],
                ['id_city' => 7810, 'id_state' => 21, 'name' => ' Lajeado do Bugre'],
                ['id_city' => 7811, 'id_state' => 21, 'name' => ' Lajeado Grande'],
                ['id_city' => 7812, 'id_state' => 21, 'name' => ' Lara'],
                ['id_city' => 7813, 'id_state' => 21, 'name' => ' Laranjeira'],
                ['id_city' => 7814, 'id_state' => 21, 'name' => ' Lava-Pés'],
                ['id_city' => 7815, 'id_state' => 21, 'name' => ' Lavras do Sul'],
                ['id_city' => 7816, 'id_state' => 21, 'name' => ' Leonel Rocha'],
                ['id_city' => 7817, 'id_state' => 21, 'name' => ' Liberato Salzano'],
                ['id_city' => 7818, 'id_state' => 21, 'name' => ' Lindolfo Collor'],
                ['id_city' => 7819, 'id_state' => 21, 'name' => ' Linha Comprida'],
                ['id_city' => 7820, 'id_state' => 21, 'name' => ' Linha Nova'],
                ['id_city' => 7821, 'id_state' => 21, 'name' => ' Linha Vitória'],
                ['id_city' => 7822, 'id_state' => 21, 'name' => ' Loreto'],
                ['id_city' => 7823, 'id_state' => 21, 'name' => ' Maçambará'],
                ['id_city' => 7824, 'id_state' => 21, 'name' => ' Machadinho'],
                ['id_city' => 7825, 'id_state' => 21, 'name' => ' Magistério'],
                ['id_city' => 7826, 'id_state' => 21, 'name' => ' Mampituba'],
                ['id_city' => 7827, 'id_state' => 21, 'name' => ' Manchinha'],
                ['id_city' => 7828, 'id_state' => 21, 'name' => ' Mangueiras'],
                ['id_city' => 7829, 'id_state' => 21, 'name' => ' Manoel Viana'],
                ['id_city' => 7830, 'id_state' => 21, 'name' => ' Maquiné'],
                ['id_city' => 7831, 'id_state' => 21, 'name' => ' Maratá'],
                ['id_city' => 7832, 'id_state' => 21, 'name' => ' Marau'],
                ['id_city' => 7833, 'id_state' => 21, 'name' => ' Marcelino Ramos'],
                ['id_city' => 7834, 'id_state' => 21, 'name' => ' Marcorama'],
                ['id_city' => 7835, 'id_state' => 21, 'name' => ' Mariana Pimentel'],
                ['id_city' => 7836, 'id_state' => 21, 'name' => ' Mariano Moro'],
                ['id_city' => 7837, 'id_state' => 21, 'name' => ' Mariante'],
                ['id_city' => 7838, 'id_state' => 21, 'name' => ' Mariápolis'],
                ['id_city' => 7839, 'id_state' => 21, 'name' => ' Marques de Souza'],
                ['id_city' => 7840, 'id_state' => 21, 'name' => ' Mata'],
                ['id_city' => 7841, 'id_state' => 21, 'name' => ' Matarazzo'],
                ['id_city' => 7842, 'id_state' => 21, 'name' => ' Mato Castelhano'],
                ['id_city' => 7843, 'id_state' => 21, 'name' => ' Mato Grande'],
                ['id_city' => 7844, 'id_state' => 21, 'name' => ' Mato Leitão'],
                ['id_city' => 7845, 'id_state' => 21, 'name' => ' Mato Queimado'],
                ['id_city' => 7846, 'id_state' => 21, 'name' => ' Mauá'],
                ['id_city' => 7847, 'id_state' => 21, 'name' => ' Maximiliano de Almeida'],
                ['id_city' => 7848, 'id_state' => 21, 'name' => ' Medianeira'],
                ['id_city' => 7849, 'id_state' => 21, 'name' => ' Minas do Leão'],
                ['id_city' => 7850, 'id_state' => 21, 'name' => ' Miraguaí'],
                ['id_city' => 7851, 'id_state' => 21, 'name' => ' Miraguaia'],
                ['id_city' => 7852, 'id_state' => 21, 'name' => ' Mirim'],
                ['id_city' => 7853, 'id_state' => 21, 'name' => ' Montauri'],
                ['id_city' => 7854, 'id_state' => 21, 'name' => ' Monte Alegre'],
                ['id_city' => 7855, 'id_state' => 21, 'name' => ' Monte Alegre dos Campos'],
                ['id_city' => 7856, 'id_state' => 21, 'name' => ' Monte Alverne'],
                ['id_city' => 7857, 'id_state' => 21, 'name' => ' Monte Belo do Sul'],
                ['id_city' => 7858, 'id_state' => 21, 'name' => ' Monte Bonito'],
                ['id_city' => 7859, 'id_state' => 21, 'name' => ' Montenegro'],
                ['id_city' => 7860, 'id_state' => 21, 'name' => ' Mormaço'],
                ['id_city' => 7861, 'id_state' => 21, 'name' => ' Morrinhos'],
                ['id_city' => 7862, 'id_state' => 21, 'name' => ' Morrinhos do Sul'],
                ['id_city' => 7863, 'id_state' => 21, 'name' => ' Morro Alto'],
                ['id_city' => 7864, 'id_state' => 21, 'name' => ' Morro Azul'],
                ['id_city' => 7865, 'id_state' => 21, 'name' => ' Morro Redondo'],
                ['id_city' => 7866, 'id_state' => 21, 'name' => ' Morro Reuter'],
                ['id_city' => 7867, 'id_state' => 21, 'name' => ' Morungava'],
                ['id_city' => 7868, 'id_state' => 21, 'name' => ' Mostardas'],
                ['id_city' => 7869, 'id_state' => 21, 'name' => ' Muçum'],
                ['id_city' => 7870, 'id_state' => 21, 'name' => ' Muitos Capões'],
                ['id_city' => 7871, 'id_state' => 21, 'name' => ' Muliterno'],
                ['id_city' => 7872, 'id_state' => 21, 'name' => ' Não-Me-Toque'],
                ['id_city' => 7873, 'id_state' => 21, 'name' => ' Nazaré'],
                ['id_city' => 7874, 'id_state' => 21, 'name' => ' Nicolau Vergueiro'],
                ['id_city' => 7875, 'id_state' => 21, 'name' => ' Nonoai'],
                ['id_city' => 7876, 'id_state' => 21, 'name' => ' Nossa Senhora Aparecida'],
                ['id_city' => 7877, 'id_state' => 21, 'name' => ' Nossa Senhora da Conceição'],
                ['id_city' => 7878, 'id_state' => 21, 'name' => ' Nova Alvorada'],
                ['id_city' => 7879, 'id_state' => 21, 'name' => ' Nova Araçá'],
                ['id_city' => 7880, 'id_state' => 21, 'name' => ' Nova Bassano'],
                ['id_city' => 7881, 'id_state' => 21, 'name' => ' Nova Boa Vista'],
                ['id_city' => 7882, 'id_state' => 21, 'name' => ' Nova Bréscia'],
                ['id_city' => 7883, 'id_state' => 21, 'name' => ' Nova Candelária'],
                ['id_city' => 7884, 'id_state' => 21, 'name' => ' Nova Esperança do Sul'],
                ['id_city' => 7885, 'id_state' => 21, 'name' => ' Nova Hartz'],
                ['id_city' => 7886, 'id_state' => 21, 'name' => ' Nova Milano'],
                ['id_city' => 7887, 'id_state' => 21, 'name' => ' Nova Pádua'],
                ['id_city' => 7888, 'id_state' => 21, 'name' => ' Nova Palma'],
                ['id_city' => 7889, 'id_state' => 21, 'name' => ' Nova Petrópolis'],
                ['id_city' => 7890, 'id_state' => 21, 'name' => ' Nova Prata'],
                ['id_city' => 7891, 'id_state' => 21, 'name' => ' Nova Ramada'],
                ['id_city' => 7892, 'id_state' => 21, 'name' => ' Nova Roma do Sul'],
                ['id_city' => 7893, 'id_state' => 21, 'name' => ' Nova Santa Rita'],
                ['id_city' => 7894, 'id_state' => 21, 'name' => ' Nova Sardenha'],
                ['id_city' => 7895, 'id_state' => 21, 'name' => ' Novo Barreiro'],
                ['id_city' => 7896, 'id_state' => 21, 'name' => ' Novo Cabrais'],
                ['id_city' => 7897, 'id_state' => 21, 'name' => ' Novo Hamburgo'],
                ['id_city' => 7898, 'id_state' => 21, 'name' => ' Novo Horizonte'],
                ['id_city' => 7899, 'id_state' => 21, 'name' => ' Novo Machado'],
                ['id_city' => 7900, 'id_state' => 21, 'name' => ' Novo Planalto'],
                ['id_city' => 7901, 'id_state' => 21, 'name' => ' Novo Tiradentes'],
                ['id_city' => 7902, 'id_state' => 21, 'name' => ' Vila Oliva'],
                ['id_city' => 7903, 'id_state' => 21, 'name' => ' Oralina'],
                ['id_city' => 7904, 'id_state' => 21, 'name' => ' Osório'],
                ['id_city' => 7905, 'id_state' => 21, 'name' => ' Osvaldo Cruz'],
                ['id_city' => 7906, 'id_state' => 21, 'name' => ' Osvaldo Kroeff'],
                ['id_city' => 7907, 'id_state' => 21, 'name' => ' Otávio Rocha'],
                ['id_city' => 7908, 'id_state' => 21, 'name' => ' Pacheca'],
                ['id_city' => 7909, 'id_state' => 21, 'name' => ' Padilha'],
                ['id_city' => 7910, 'id_state' => 21, 'name' => ' Padre Gonzales'],
                ['id_city' => 7911, 'id_state' => 21, 'name' => ' Paim Filho'],
                ['id_city' => 7912, 'id_state' => 21, 'name' => ' Palmares do Sul'],
                ['id_city' => 7913, 'id_state' => 21, 'name' => ' Palmas'],
                ['id_city' => 7914, 'id_state' => 21, 'name' => ' Palmeira das Missões'],
                ['id_city' => 7915, 'id_state' => 21, 'name' => ' Palmitinho'],
                ['id_city' => 7916, 'id_state' => 21, 'name' => ' Pampeiro'],
                ['id_city' => 7917, 'id_state' => 21, 'name' => ' Panambi'],
                ['id_city' => 7918, 'id_state' => 21, 'name' => ' Pantano Grande'],
                ['id_city' => 7919, 'id_state' => 21, 'name' => ' Paraí'],
                ['id_city' => 7920, 'id_state' => 21, 'name' => ' Paraíso do Sul'],
                ['id_city' => 7921, 'id_state' => 21, 'name' => ' Pareci Novo'],
                ['id_city' => 7922, 'id_state' => 21, 'name' => ' Parobé'],
                ['id_city' => 7923, 'id_state' => 21, 'name' => ' Passa Sete'],
                ['id_city' => 7924, 'id_state' => 21, 'name' => ' Passinhos'],
                ['id_city' => 7925, 'id_state' => 21, 'name' => ' Passo Burmann'],
                ['id_city' => 7926, 'id_state' => 21, 'name' => ' Passo da Areia'],
                ['id_city' => 7927, 'id_state' => 21, 'name' => ' Passo da Caveira'],
                ['id_city' => 7928, 'id_state' => 21, 'name' => ' Passo das Pedras'],
                ['id_city' => 7929, 'id_state' => 21, 'name' => ' Passo do Adão'],
                ['id_city' => 7930, 'id_state' => 21, 'name' => ' Passo do Sabão'],
                ['id_city' => 7931, 'id_state' => 21, 'name' => ' Passo do Sobrado'],
                ['id_city' => 7932, 'id_state' => 21, 'name' => ' Passo Fundo'],
                ['id_city' => 7933, 'id_state' => 21, 'name' => ' Passo Novo'],
                ['id_city' => 7934, 'id_state' => 21, 'name' => ' Passo Raso'],
                ['id_city' => 7935, 'id_state' => 21, 'name' => ' Paulo Bento'],
                ['id_city' => 7936, 'id_state' => 21, 'name' => ' Pavão'],
                ['id_city' => 7937, 'id_state' => 21, 'name' => ' Paverama'],
                ['id_city' => 7938, 'id_state' => 21, 'name' => ' Pedras Altas'],
                ['id_city' => 7939, 'id_state' => 21, 'name' => ' Pedreiras'],
                ['id_city' => 7940, 'id_state' => 21, 'name' => ' Pedro Garcia'],
                ['id_city' => 7941, 'id_state' => 21, 'name' => ' Pedro Osório'],
                ['id_city' => 7942, 'id_state' => 21, 'name' => ' Pedro Paiva'],
                ['id_city' => 7943, 'id_state' => 21, 'name' => ' Pejuçara'],
                ['id_city' => 7944, 'id_state' => 21, 'name' => ' Pelotas'],
                ['id_city' => 7945, 'id_state' => 21, 'name' => ' Picada Café'],
                ['id_city' => 7946, 'id_state' => 21, 'name' => ' Pinhal'],
                ['id_city' => 7947, 'id_state' => 21, 'name' => ' Pinhal Alto'],
                ['id_city' => 7948, 'id_state' => 21, 'name' => ' Pinhal da Serra'],
                ['id_city' => 7949, 'id_state' => 21, 'name' => ' Pinhal Grande'],
                ['id_city' => 7950, 'id_state' => 21, 'name' => ' Pinhalzinho'],
                ['id_city' => 7951, 'id_state' => 21, 'name' => ' Pinheirinho do Vale'],
                ['id_city' => 7952, 'id_state' => 21, 'name' => ' Pinheiro Machado'],
                ['id_city' => 7953, 'id_state' => 21, 'name' => ' Pinheiro Marcado'],
                ['id_city' => 7954, 'id_state' => 21, 'name' => ' Pinto Bandeira'],
                ['id_city' => 7955, 'id_state' => 21, 'name' => ' Piraí'],
                ['id_city' => 7956, 'id_state' => 21, 'name' => ' Pirapó'],
                ['id_city' => 7957, 'id_state' => 21, 'name' => ' Piratini'],
                ['id_city' => 7958, 'id_state' => 21, 'name' => ' Pitanga'],
                ['id_city' => 7959, 'id_state' => 21, 'name' => ' Planalto'],
                ['id_city' => 7960, 'id_state' => 21, 'name' => ' Plano Alto'],
                ['id_city' => 7961, 'id_state' => 21, 'name' => ' Poço das Antas'],
                ['id_city' => 7962, 'id_state' => 21, 'name' => ' Polígono do Erval'],
                ['id_city' => 7963, 'id_state' => 21, 'name' => ' Pólo Petroquímico de Triunfo'],
                ['id_city' => 7964, 'id_state' => 21, 'name' => ' Pontão'],
                ['id_city' => 7965, 'id_state' => 21, 'name' => ' Ponte Preta'],
                ['id_city' => 7966, 'id_state' => 21, 'name' => ' Portão'],
                ['id_city' => 7967, 'id_state' => 21, 'name' => ' Porto Alegre'],
                ['id_city' => 7968, 'id_state' => 21, 'name' => ' Porto Batista'],
                ['id_city' => 7969, 'id_state' => 21, 'name' => ' Porto Lucena'],
                ['id_city' => 7970, 'id_state' => 21, 'name' => ' Porto Mauá'],
                ['id_city' => 7971, 'id_state' => 21, 'name' => ' Porto Vera Cruz'],
                ['id_city' => 7972, 'id_state' => 21, 'name' => ' Porto Xavier'],
                ['id_city' => 7973, 'id_state' => 21, 'name' => ' Pouso Novo'],
                ['id_city' => 7974, 'id_state' => 21, 'name' => ' Povo Novo'],
                ['id_city' => 7975, 'id_state' => 21, 'name' => ' Povoado Tozzo'],
                ['id_city' => 7976, 'id_state' => 21, 'name' => ' Pranchada'],
                ['id_city' => 7977, 'id_state' => 21, 'name' => ' Pratos'],
                ['id_city' => 7978, 'id_state' => 21, 'name' => ' Presidente Lucena'],
                ['id_city' => 7979, 'id_state' => 21, 'name' => ' Progresso'],
                ['id_city' => 7980, 'id_state' => 21, 'name' => ' Protásio Alves'],
                ['id_city' => 7981, 'id_state' => 21, 'name' => ' Pulador'],
                ['id_city' => 7982, 'id_state' => 21, 'name' => ' Putinga'],
                ['id_city' => 7983, 'id_state' => 21, 'name' => ' Quaraí'],
                ['id_city' => 7984, 'id_state' => 21, 'name' => ' Quaraim'],
                ['id_city' => 7985, 'id_state' => 21, 'name' => ' Quatro Irmãos'],
                ['id_city' => 7986, 'id_state' => 21, 'name' => ' Quevedos'],
                ['id_city' => 7987, 'id_state' => 21, 'name' => ' Quilombo'],
                ['id_city' => 7988, 'id_state' => 21, 'name' => ' Quinta'],
                ['id_city' => 7989, 'id_state' => 21, 'name' => ' Quintão'],
                ['id_city' => 7990, 'id_state' => 21, 'name' => ' Quinze de Novembro'],
                ['id_city' => 7991, 'id_state' => 21, 'name' => ' Quitéria'],
                ['id_city' => 7992, 'id_state' => 21, 'name' => ' Rancho Velho'],
                ['id_city' => 7993, 'id_state' => 21, 'name' => ' Redentora'],
                ['id_city' => 7994, 'id_state' => 21, 'name' => ' Refugiado'],
                ['id_city' => 7995, 'id_state' => 21, 'name' => ' Relvado'],
                ['id_city' => 7996, 'id_state' => 21, 'name' => ' Restinga Seca'],
                ['id_city' => 7997, 'id_state' => 21, 'name' => ' Rincão de São Pedro'],
                ['id_city' => 7998, 'id_state' => 21, 'name' => ' Rincão Del Rei']
            ]);
        }
    }