<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities3 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 1574, 'id_state' => 6, 'name' => ' Guaraciaba do Norte'],
                ['id_city' => 1575, 'id_state' => 6, 'name' => ' Guaramiranga'],
                ['id_city' => 1576, 'id_state' => 6, 'name' => ' Guararu'],
                ['id_city' => 1577, 'id_state' => 6, 'name' => ' Guassi'],
                ['id_city' => 1578, 'id_state' => 6, 'name' => ' Guassossé'],
                ['id_city' => 1579, 'id_state' => 6, 'name' => ' Guia'],
                ['id_city' => 1580, 'id_state' => 6, 'name' => ' Guriú'],
                ['id_city' => 1581, 'id_state' => 6, 'name' => ' Hidrolândia'],
                ['id_city' => 1582, 'id_state' => 6, 'name' => ' Holanda'],
                ['id_city' => 1583, 'id_state' => 6, 'name' => ' Horizonte'],
                ['id_city' => 1584, 'id_state' => 6, 'name' => ' Iapi'],
                ['id_city' => 1585, 'id_state' => 6, 'name' => ' Iara'],
                ['id_city' => 1586, 'id_state' => 6, 'name' => ' Ibaretama'],
                ['id_city' => 1587, 'id_state' => 6, 'name' => ' Ibiapaba'],
                ['id_city' => 1588, 'id_state' => 6, 'name' => ' Ibiapina'],
                ['id_city' => 1589, 'id_state' => 6, 'name' => ' Ibicatu'],
                ['id_city' => 1590, 'id_state' => 6, 'name' => ' Ibicuã'],
                ['id_city' => 1591, 'id_state' => 6, 'name' => ' Ibicuitaba'],
                ['id_city' => 1592, 'id_state' => 6, 'name' => ' Ibicuitinga'],
                ['id_city' => 1593, 'id_state' => 6, 'name' => ' Iborepi'],
                ['id_city' => 1594, 'id_state' => 6, 'name' => ' Ibuaçu'],
                ['id_city' => 1595, 'id_state' => 6, 'name' => ' Ibuguaçu'],
                ['id_city' => 1596, 'id_state' => 6, 'name' => ' Icapuí'],
                ['id_city' => 1597, 'id_state' => 6, 'name' => ' Icaraí'],
                ['id_city' => 1598, 'id_state' => 6, 'name' => ' Icó'],
                ['id_city' => 1599, 'id_state' => 6, 'name' => ' Icozinho'],
                ['id_city' => 1600, 'id_state' => 6, 'name' => ' Ideal'],
                ['id_city' => 1601, 'id_state' => 6, 'name' => ' Igaroi'],
                ['id_city' => 1602, 'id_state' => 6, 'name' => ' Iguatu'],
                ['id_city' => 1603, 'id_state' => 6, 'name' => ' Independência'],
                ['id_city' => 1604, 'id_state' => 6, 'name' => ' Ingazeiras'],
                ['id_city' => 1605, 'id_state' => 6, 'name' => ' Inhamuns'],
                ['id_city' => 1606, 'id_state' => 6, 'name' => ' Inhuçu'],
                ['id_city' => 1607, 'id_state' => 6, 'name' => ' Inhuporanga'],
                ['id_city' => 1608, 'id_state' => 6, 'name' => ' Ipaporanga'],
                ['id_city' => 1609, 'id_state' => 6, 'name' => ' Ipaumirim'],
                ['id_city' => 1610, 'id_state' => 6, 'name' => ' Ipu'],
                ['id_city' => 1611, 'id_state' => 6, 'name' => ' Ipueiras'],
                ['id_city' => 1612, 'id_state' => 6, 'name' => ' Ipueiras dos Gomes'],
                ['id_city' => 1613, 'id_state' => 6, 'name' => ' Iracema'],
                ['id_city' => 1614, 'id_state' => 6, 'name' => ' Irajá'],
                ['id_city' => 1615, 'id_state' => 6, 'name' => ' Irapuã'],
                ['id_city' => 1616, 'id_state' => 6, 'name' => ' Iratinga'],
                ['id_city' => 1617, 'id_state' => 6, 'name' => ' Irauçuba'],
                ['id_city' => 1618, 'id_state' => 6, 'name' => ' Isidoro'],
                ['id_city' => 1619, 'id_state' => 6, 'name' => ' Itacima'],
                ['id_city' => 1620, 'id_state' => 6, 'name' => ' Itaguá'],
                ['id_city' => 1621, 'id_state' => 6, 'name' => ' Itaiçaba'],
                ['id_city' => 1622, 'id_state' => 6, 'name' => ' Itaipaba'],
                ['id_city' => 1623, 'id_state' => 6, 'name' => ' Itaitinga'],
                ['id_city' => 1624, 'id_state' => 6, 'name' => ' Itans'],
                ['id_city' => 1625, 'id_state' => 6, 'name' => ' Itapajé'],
                ['id_city' => 1626, 'id_state' => 6, 'name' => ' Itapebussu'],
                ['id_city' => 1627, 'id_state' => 6, 'name' => ' Itapeim'],
                ['id_city' => 1628, 'id_state' => 6, 'name' => ' Itapipoca'],
                ['id_city' => 1629, 'id_state' => 6, 'name' => ' Itapiúna'],
                ['id_city' => 1630, 'id_state' => 6, 'name' => ' Itapó'],
                ['id_city' => 1631, 'id_state' => 6, 'name' => ' Itarema'],
                ['id_city' => 1632, 'id_state' => 6, 'name' => ' Itatira'],
                ['id_city' => 1633, 'id_state' => 6, 'name' => ' Jaburuna'],
                ['id_city' => 1634, 'id_state' => 6, 'name' => ' Jacampari'],
                ['id_city' => 1635, 'id_state' => 6, 'name' => ' Jacarecoara'],
                ['id_city' => 1636, 'id_state' => 6, 'name' => ' Jacaúna'],
                ['id_city' => 1637, 'id_state' => 6, 'name' => ' Jaguarão'],
                ['id_city' => 1638, 'id_state' => 6, 'name' => ' Jaguaretama'],
                ['id_city' => 1639, 'id_state' => 6, 'name' => ' Jaguaribara'],
                ['id_city' => 1640, 'id_state' => 6, 'name' => ' Jaguaribe'],
                ['id_city' => 1641, 'id_state' => 6, 'name' => ' Jaguaruana'],
                ['id_city' => 1642, 'id_state' => 6, 'name' => ' Jaibaras'],
                ['id_city' => 1643, 'id_state' => 6, 'name' => ' Jamacaru'],
                ['id_city' => 1644, 'id_state' => 6, 'name' => ' Jandrangoeirva'],
                ['id_city' => 1645, 'id_state' => 6, 'name' => ' Jardim'],
                ['id_city' => 1646, 'id_state' => 6, 'name' => ' Jardimirim'],
                ['id_city' => 1647, 'id_state' => 6, 'name' => ' Jati'],
                ['id_city' => 1648, 'id_state' => 6, 'name' => ' Jijoca de Jericoacoara'],
                ['id_city' => 1649, 'id_state' => 6, 'name' => ' João Cordeiro'],
                ['id_city' => 1650, 'id_state' => 6, 'name' => ' Jordão'],
                ['id_city' => 1651, 'id_state' => 6, 'name' => ' José de Alencar'],
                ['id_city' => 1652, 'id_state' => 6, 'name' => ' Juá'],
                ['id_city' => 1653, 'id_state' => 6, 'name' => ' Juatama'],
                ['id_city' => 1654, 'id_state' => 6, 'name' => ' Juazeiro de Baixo'],
                ['id_city' => 1655, 'id_state' => 6, 'name' => ' Juazeiro do Norte'],
                ['id_city' => 1656, 'id_state' => 6, 'name' => ' Jubaia'],
                ['id_city' => 1657, 'id_state' => 6, 'name' => ' Jucás'],
                ['id_city' => 1658, 'id_state' => 6, 'name' => ' Jurema'],
                ['id_city' => 1659, 'id_state' => 6, 'name' => ' Justiniano Serpa'],
                ['id_city' => 1660, 'id_state' => 6, 'name' => ' Lacerda'],
                ['id_city' => 1661, 'id_state' => 6, 'name' => ' Ladeira Grande'],
                ['id_city' => 1662, 'id_state' => 6, 'name' => ' Lagoa de São João'],
                ['id_city' => 1663, 'id_state' => 6, 'name' => ' Lagoa do Juvenal'],
                ['id_city' => 1664, 'id_state' => 6, 'name' => ' Lagoa do Mato'],
                ['id_city' => 1665, 'id_state' => 6, 'name' => ' Lagoa dos Crioulos'],
                ['id_city' => 1666, 'id_state' => 6, 'name' => ' Lagoa Grande'],
                ['id_city' => 1667, 'id_state' => 6, 'name' => ' Lagoinha'],
                ['id_city' => 1668, 'id_state' => 6, 'name' => ' Lambedouro'],
                ['id_city' => 1669, 'id_state' => 6, 'name' => ' Lameiro'],
                ['id_city' => 1670, 'id_state' => 6, 'name' => ' Lavras da Mangabeira'],
                ['id_city' => 1671, 'id_state' => 6, 'name' => ' Lima Campos'],
                ['id_city' => 1672, 'id_state' => 6, 'name' => ' Limoeiro do Norte'],
                ['id_city' => 1673, 'id_state' => 6, 'name' => ' Lisieux'],
                ['id_city' => 1674, 'id_state' => 6, 'name' => ' Livramento'],
                ['id_city' => 1675, 'id_state' => 6, 'name' => ' Logradouro'],
                ['id_city' => 1676, 'id_state' => 6, 'name' => ' Macambira'],
                ['id_city' => 1677, 'id_state' => 6, 'name' => ' Macaóca'],
                ['id_city' => 1678, 'id_state' => 6, 'name' => ' Macaraú'],
                ['id_city' => 1679, 'id_state' => 6, 'name' => ' Maceió'],
                ['id_city' => 1680, 'id_state' => 6, 'name' => ' Madalena'],
                ['id_city' => 1681, 'id_state' => 6, 'name' => ' Major Simplício'],
                ['id_city' => 1682, 'id_state' => 6, 'name' => ' Majorlândia'],
                ['id_city' => 1683, 'id_state' => 6, 'name' => ' Malhada Grande'],
                ['id_city' => 1684, 'id_state' => 6, 'name' => ' Mangabeira'],
                ['id_city' => 1685, 'id_state' => 6, 'name' => ' Manibu'],
                ['id_city' => 1686, 'id_state' => 6, 'name' => ' Manituba'],
                ['id_city' => 1687, 'id_state' => 6, 'name' => ' Mapuá'],
                ['id_city' => 1688, 'id_state' => 6, 'name' => ' Maracanaú'],
                ['id_city' => 1689, 'id_state' => 6, 'name' => ' Maraguá'],
                ['id_city' => 1690, 'id_state' => 6, 'name' => ' Maranguape'],
                ['id_city' => 1691, 'id_state' => 6, 'name' => ' Mararupá'],
                ['id_city' => 1692, 'id_state' => 6, 'name' => ' Marco'],
                ['id_city' => 1693, 'id_state' => 6, 'name' => ' Marinheiros'],
                ['id_city' => 1694, 'id_state' => 6, 'name' => ' Marrecas'],
                ['id_city' => 1695, 'id_state' => 6, 'name' => ' Marrocos'],
                ['id_city' => 1696, 'id_state' => 6, 'name' => ' Marruás'],
                ['id_city' => 1697, 'id_state' => 6, 'name' => ' Martinópole'],
                ['id_city' => 1698, 'id_state' => 6, 'name' => ' Massapê'],
                ['id_city' => 1699, 'id_state' => 6, 'name' => ' Mata Fresca'],
                ['id_city' => 1700, 'id_state' => 6, 'name' => ' Matias'],
                ['id_city' => 1701, 'id_state' => 6, 'name' => ' Matriz'],
                ['id_city' => 1702, 'id_state' => 6, 'name' => ' Mauriti'],
                ['id_city' => 1703, 'id_state' => 6, 'name' => ' Mel'],
                ['id_city' => 1704, 'id_state' => 6, 'name' => ' Meruoca'],
                ['id_city' => 1705, 'id_state' => 6, 'name' => ' Messejana'],
                ['id_city' => 1706, 'id_state' => 6, 'name' => ' Miguel Xavier'],
                ['id_city' => 1707, 'id_state' => 6, 'name' => ' Milagres'],
                ['id_city' => 1708, 'id_state' => 6, 'name' => ' Milhã'],
                ['id_city' => 1709, 'id_state' => 6, 'name' => ' Milton Belo'],
                ['id_city' => 1710, 'id_state' => 6, 'name' => ' Mineirolândia'],
                ['id_city' => 1711, 'id_state' => 6, 'name' => ' Miragem'],
                ['id_city' => 1712, 'id_state' => 6, 'name' => ' Miraíma'],
                ['id_city' => 1713, 'id_state' => 6, 'name' => ' Mirambé'],
                ['id_city' => 1714, 'id_state' => 6, 'name' => ' Missão Nova'],
                ['id_city' => 1715, 'id_state' => 6, 'name' => ' Missão Velha'],
                ['id_city' => 1716, 'id_state' => 6, 'name' => ' Missi'],
                ['id_city' => 1717, 'id_state' => 6, 'name' => ' Moitas'],
                ['id_city' => 1718, 'id_state' => 6, 'name' => ' Mombaça'],
                ['id_city' => 1719, 'id_state' => 6, 'name' => ' Mondubim'],
                ['id_city' => 1720, 'id_state' => 6, 'name' => ' Monguba'],
                ['id_city' => 1721, 'id_state' => 6, 'name' => ' Monsenhor Tabosa'],
                ['id_city' => 1722, 'id_state' => 6, 'name' => ' Monte Alegre'],
                ['id_city' => 1723, 'id_state' => 6, 'name' => ' Monte Castelo'],
                ['id_city' => 1724, 'id_state' => 6, 'name' => ' Monte Grave'],
                ['id_city' => 1725, 'id_state' => 6, 'name' => ' Monte Sion'],
                ['id_city' => 1726, 'id_state' => 6, 'name' => ' Montenebo'],
                ['id_city' => 1727, 'id_state' => 6, 'name' => ' Morada Nova'],
                ['id_city' => 1728, 'id_state' => 6, 'name' => ' Moraújo'],
                ['id_city' => 1729, 'id_state' => 6, 'name' => ' Morrinhos'],
                ['id_city' => 1730, 'id_state' => 6, 'name' => ' Morrinhos Novos'],
                ['id_city' => 1731, 'id_state' => 6, 'name' => ' Morro Branco'],
                ['id_city' => 1732, 'id_state' => 6, 'name' => ' Mucambo'],
                ['id_city' => 1733, 'id_state' => 6, 'name' => ' Mulungu'],
                ['id_city' => 1734, 'id_state' => 6, 'name' => ' Mulungu'],
                ['id_city' => 1735, 'id_state' => 6, 'name' => ' Mumbaba'],
                ['id_city' => 1736, 'id_state' => 6, 'name' => ' Mundau'],
                ['id_city' => 1737, 'id_state' => 6, 'name' => ' Muribeca'],
                ['id_city' => 1738, 'id_state' => 6, 'name' => ' Muriti'],
                ['id_city' => 1739, 'id_state' => 6, 'name' => ' Mutambeiras'],
                ['id_city' => 1740, 'id_state' => 6, 'name' => ' Naraniu'],
                ['id_city' => 1741, 'id_state' => 6, 'name' => ' Nascente'],
                ['id_city' => 1742, 'id_state' => 6, 'name' => ' Nenenlândia'],
                ['id_city' => 1743, 'id_state' => 6, 'name' => ' Nossa Senhora do Livramento'],
                ['id_city' => 1744, 'id_state' => 6, 'name' => ' Nova Betânia'],
                ['id_city' => 1745, 'id_state' => 6, 'name' => ' Nova Fátima'],
                ['id_city' => 1746, 'id_state' => 6, 'name' => ' Nova Floresta'],
                ['id_city' => 1747, 'id_state' => 6, 'name' => ' Nova Olinda'],
                ['id_city' => 1748, 'id_state' => 6, 'name' => ' Nova Russas'],
                ['id_city' => 1749, 'id_state' => 6, 'name' => ' Nova Vida'],
                ['id_city' => 1750, 'id_state' => 6, 'name' => ' Novo Assis'],
                ['id_city' => 1751, 'id_state' => 6, 'name' => ' Novo Oriente'],
                ['id_city' => 1752, 'id_state' => 6, 'name' => ' Ocara'],
                ['id_city' => 1753, 'id_state' => 6, 'name' => ' Oiticica'],
                ['id_city' => 1754, 'id_state' => 6, 'name' => ' Olho-D Água'],
                ['id_city' => 1755, 'id_state' => 6, 'name' => ' Olho-D Água da Bica'],
                ['id_city' => 1756, 'id_state' => 6, 'name' => ' Oliveiras'],
                ['id_city' => 1757, 'id_state' => 6, 'name' => ' Orós'],
                ['id_city' => 1758, 'id_state' => 6, 'name' => ' Pacajus'],
                ['id_city' => 1759, 'id_state' => 6, 'name' => ' Pacatuba'],
                ['id_city' => 1760, 'id_state' => 6, 'name' => ' Pacoti'],
                ['id_city' => 1761, 'id_state' => 6, 'name' => ' Pacujá'],
                ['id_city' => 1762, 'id_state' => 6, 'name' => ' Padre Cícero'],
                ['id_city' => 1763, 'id_state' => 6, 'name' => ' Padre Linhares'],
                ['id_city' => 1764, 'id_state' => 6, 'name' => ' Padre Vieira'],
                ['id_city' => 1765, 'id_state' => 6, 'name' => ' Pajeú'],
                ['id_city' => 1766, 'id_state' => 6, 'name' => ' Palestina'],
                ['id_city' => 1767, 'id_state' => 6, 'name' => ' Palestina do Norte'],
                ['id_city' => 1768, 'id_state' => 6, 'name' => ' Palhano'],
                ['id_city' => 1769, 'id_state' => 6, 'name' => ' Palmácia'],
                ['id_city' => 1770, 'id_state' => 6, 'name' => ' Palmatória'],
                ['id_city' => 1771, 'id_state' => 6, 'name' => ' Panacuí'],
                ['id_city' => 1772, 'id_state' => 6, 'name' => ' Paracuá'],
                ['id_city' => 1773, 'id_state' => 6, 'name' => ' Paracuru'],
                ['id_city' => 1774, 'id_state' => 6, 'name' => ' Paraipaba'],
                ['id_city' => 1775, 'id_state' => 6, 'name' => ' Parajuru'],
                ['id_city' => 1776, 'id_state' => 6, 'name' => ' Parambu'],
                ['id_city' => 1777, 'id_state' => 6, 'name' => ' Paramoti'],
                ['id_city' => 1778, 'id_state' => 6, 'name' => ' Parangaba'],
                ['id_city' => 1779, 'id_state' => 6, 'name' => ' Parapuí'],
                ['id_city' => 1780, 'id_state' => 6, 'name' => ' Parazinho'],
                ['id_city' => 1781, 'id_state' => 6, 'name' => ' Paripueira'],
                ['id_city' => 1782, 'id_state' => 6, 'name' => ' Passagem'],
                ['id_city' => 1783, 'id_state' => 6, 'name' => ' Passagem Funda'],
                ['id_city' => 1784, 'id_state' => 6, 'name' => ' Pasta'],
                ['id_city' => 1785, 'id_state' => 6, 'name' => ' Patacas'],
                ['id_city' => 1786, 'id_state' => 6, 'name' => ' Patriarca'],
                ['id_city' => 1787, 'id_state' => 6, 'name' => ' Pavuna'],
                ['id_city' => 1788, 'id_state' => 6, 'name' => ' Pecém'],
                ['id_city' => 1789, 'id_state' => 6, 'name' => ' Pedra Branca'],
                ['id_city' => 1790, 'id_state' => 6, 'name' => ' Pedras'],
                ['id_city' => 1791, 'id_state' => 6, 'name' => ' Pedrinhas'],
                ['id_city' => 1792, 'id_state' => 6, 'name' => ' Peixe'],
                ['id_city' => 1793, 'id_state' => 6, 'name' => ' Peixe Gordo'],
                ['id_city' => 1794, 'id_state' => 6, 'name' => ' Penaforte'],
                ['id_city' => 1795, 'id_state' => 6, 'name' => ' Pentecoste'],
                ['id_city' => 1796, 'id_state' => 6, 'name' => ' Pereiro'],
                ['id_city' => 1797, 'id_state' => 6, 'name' => ' Pernambuquinho'],
                ['id_city' => 1798, 'id_state' => 6, 'name' => ' Pessoa Anta'],
                ['id_city' => 1799, 'id_state' => 6, 'name' => ' Pindoguaba'],
                ['id_city' => 1800, 'id_state' => 6, 'name' => ' Pindoretama'],
                ['id_city' => 1801, 'id_state' => 6, 'name' => ' Pio X'],
                ['id_city' => 1802, 'id_state' => 6, 'name' => ' Piquet Carneiro'],
                ['id_city' => 1803, 'id_state' => 6, 'name' => ' Damião Carneiro'],
                ['id_city' => 1804, 'id_state' => 6, 'name' => ' Pirangi'],
                ['id_city' => 1805, 'id_state' => 6, 'name' => ' Pires Ferreira'],
                ['id_city' => 1806, 'id_state' => 6, 'name' => ' Pitombeira'],
                ['id_city' => 1807, 'id_state' => 6, 'name' => ' Pitombeiras'],
                ['id_city' => 1808, 'id_state' => 6, 'name' => ' Plácido Martins'],
                ['id_city' => 1809, 'id_state' => 6, 'name' => ' Poço'],
                ['id_city' => 1810, 'id_state' => 6, 'name' => ' Poço Comprido'],
                ['id_city' => 1811, 'id_state' => 6, 'name' => ' Poço Grande'],
                ['id_city' => 1812, 'id_state' => 6, 'name' => ' Rosário'],
                ['id_city' => 1813, 'id_state' => 6, 'name' => ' Ponta da Serra'],
                ['id_city' => 1814, 'id_state' => 6, 'name' => ' Poranga'],
                ['id_city' => 1815, 'id_state' => 6, 'name' => ' Porfirio Sampaio'],
                ['id_city' => 1816, 'id_state' => 6, 'name' => ' Porteiras'],
                ['id_city' => 1817, 'id_state' => 6, 'name' => ' Potengi'],
                ['id_city' => 1818, 'id_state' => 6, 'name' => ' Poti'],
                ['id_city' => 1819, 'id_state' => 6, 'name' => ' Potiretama'],
                ['id_city' => 1820, 'id_state' => 6, 'name' => ' Prata'],
                ['id_city' => 1821, 'id_state' => 6, 'name' => ' Prudente de Morais'],
                ['id_city' => 1822, 'id_state' => 6, 'name' => ' Quatiguaba'],
                ['id_city' => 1823, 'id_state' => 6, 'name' => ' Queimados'],
                ['id_city' => 1824, 'id_state' => 6, 'name' => ' Quimami'],
                ['id_city' => 1825, 'id_state' => 6, 'name' => ' Quincoé'],
                ['id_city' => 1826, 'id_state' => 6, 'name' => ' Quincuncá'],
                ['id_city' => 1827, 'id_state' => 6, 'name' => ' Quitaiús'],
                ['id_city' => 1828, 'id_state' => 6, 'name' => ' Quiterianópolis'],
                ['id_city' => 1829, 'id_state' => 6, 'name' => ' Quixadá'],
                ['id_city' => 1830, 'id_state' => 6, 'name' => ' Quixariú'],
                ['id_city' => 1831, 'id_state' => 6, 'name' => ' Quixelô'],
                ['id_city' => 1832, 'id_state' => 6, 'name' => ' Quixeramobim'],
                ['id_city' => 1833, 'id_state' => 6, 'name' => ' Quixeré'],
                ['id_city' => 1834, 'id_state' => 6, 'name' => ' Gadelha'],
                ['id_city' => 1835, 'id_state' => 6, 'name' => ' Raimundo Martins'],
                ['id_city' => 1836, 'id_state' => 6, 'name' => ' Redenção'],
                ['id_city' => 1837, 'id_state' => 6, 'name' => ' Reriutaba'],
                ['id_city' => 1838, 'id_state' => 6, 'name' => ' Santa Cruz do Banabuiú'],
                ['id_city' => 1839, 'id_state' => 6, 'name' => ' Riacho Grande'],
                ['id_city' => 1840, 'id_state' => 6, 'name' => ' Riacho Verde'],
                ['id_city' => 1841, 'id_state' => 6, 'name' => ' Riacho Vermelho'],
                ['id_city' => 1842, 'id_state' => 6, 'name' => ' Rinaré'],
                ['id_city' => 1843, 'id_state' => 6, 'name' => ' Roldão'],
                ['id_city' => 1844, 'id_state' => 6, 'name' => ' Russas'],
                ['id_city' => 1845, 'id_state' => 6, 'name' => ' Sabiaguaba'],
                ['id_city' => 1846, 'id_state' => 6, 'name' => ' Saboeiro'],
                ['id_city' => 1847, 'id_state' => 6, 'name' => ' Sacramento'],
                ['id_city' => 1848, 'id_state' => 6, 'name' => ' Salão'],
                ['id_city' => 1849, 'id_state' => 6, 'name' => ' Salitre'],
                ['id_city' => 1850, 'id_state' => 6, 'name' => ' Sambaíba'],
                ['id_city' => 1851, 'id_state' => 6, 'name' => ' Santa Ana'],
                ['id_city' => 1852, 'id_state' => 6, 'name' => ' Santa Fé'],
                ['id_city' => 1853, 'id_state' => 6, 'name' => ' Santa Felícia'],
                ['id_city' => 1854, 'id_state' => 6, 'name' => ' Santa Luzia'],
                ['id_city' => 1855, 'id_state' => 6, 'name' => ' Santa Quitéria'],
                ['id_city' => 1856, 'id_state' => 6, 'name' => ' Santa Tereza'],
                ['id_city' => 1857, 'id_state' => 6, 'name' => ' Santana'],
                ['id_city' => 1858, 'id_state' => 6, 'name' => ' Santana do Acaraú'],
                ['id_city' => 1859, 'id_state' => 6, 'name' => ' Santana do Cariri'],
                ['id_city' => 1860, 'id_state' => 6, 'name' => ' Santarém'],
                ['id_city' => 1861, 'id_state' => 6, 'name' => ' Santo Antônio'],
                ['id_city' => 1862, 'id_state' => 6, 'name' => ' Santo Antônio da Pindoba'],
                ['id_city' => 1863, 'id_state' => 6, 'name' => ' Santo Antônio dos Fernandes'],
                ['id_city' => 1864, 'id_state' => 6, 'name' => ' São Bartolomeu'],
                ['id_city' => 1865, 'id_state' => 6, 'name' => ' São Benedito'],
                ['id_city' => 1866, 'id_state' => 6, 'name' => ' São Domingos'],
                ['id_city' => 1867, 'id_state' => 6, 'name' => ' São Felipe'],
                ['id_city' => 1868, 'id_state' => 6, 'name' => ' São Francisco'],
                ['id_city' => 1869, 'id_state' => 6, 'name' => ' Barra Nova'],
                ['id_city' => 1870, 'id_state' => 6, 'name' => ' São Gonçalo do Amarante'],
                ['id_city' => 1871, 'id_state' => 6, 'name' => ' São Gonçalo do Umari'],
                ['id_city' => 1872, 'id_state' => 6, 'name' => ' São João de Deus'],
                ['id_city' => 1873, 'id_state' => 6, 'name' => ' São João do Jaguaribe'],
                ['id_city' => 1874, 'id_state' => 6, 'name' => ' São João dos Queiroz'],
                ['id_city' => 1875, 'id_state' => 6, 'name' => ' São Joaquim'],
                ['id_city' => 1876, 'id_state' => 6, 'name' => ' São Joaquim do Salgado'],
                ['id_city' => 1877, 'id_state' => 6, 'name' => ' São José'],
                ['id_city' => 1878, 'id_state' => 6, 'name' => ' São José do Lagamar'],
                ['id_city' => 1879, 'id_state' => 6, 'name' => ' São José'],
                ['id_city' => 1880, 'id_state' => 6, 'name' => ' São José das Lontras'],
                ['id_city' => 1881, 'id_state' => 6, 'name' => ' São José de Solonópole'],
                ['id_city' => 1882, 'id_state' => 6, 'name' => ' São José do Torto'],
                ['id_city' => 1883, 'id_state' => 6, 'name' => ' São Luís do Curu'],
                ['id_city' => 1884, 'id_state' => 6, 'name' => ' São Miguel'],
                ['id_city' => 1885, 'id_state' => 6, 'name' => ' São Paulinho'],
                ['id_city' => 1886, 'id_state' => 6, 'name' => ' São Pedro do Norte'],
                ['id_city' => 1887, 'id_state' => 6, 'name' => ' São Romão'],
                ['id_city' => 1888, 'id_state' => 6, 'name' => ' São Sebastião'],
                ['id_city' => 1889, 'id_state' => 6, 'name' => ' São Vicente'],
                ['id_city' => 1890, 'id_state' => 6, 'name' => ' Sapo'],
                ['id_city' => 1891, 'id_state' => 6, 'name' => ' Sapupara'],
                ['id_city' => 1892, 'id_state' => 6, 'name' => ' Sebastião de Abreu'],
                ['id_city' => 1893, 'id_state' => 6, 'name' => ' Senador Carlos Jereissati'],
                ['id_city' => 1894, 'id_state' => 6, 'name' => ' Senador Pompeu'],
                ['id_city' => 1895, 'id_state' => 6, 'name' => ' Senador Sá'],
                ['id_city' => 1896, 'id_state' => 6, 'name' => ' Sereno de Cima'],
                ['id_city' => 1897, 'id_state' => 6, 'name' => ' Serra do Félix'],
                ['id_city' => 1898, 'id_state' => 6, 'name' => ' Serragem'],
                ['id_city' => 1899, 'id_state' => 6, 'name' => ' Serrota'],
                ['id_city' => 1900, 'id_state' => 6, 'name' => ' Serrote'],
                ['id_city' => 1901, 'id_state' => 6, 'name' => ' Sitiá'],
                ['id_city' => 1902, 'id_state' => 6, 'name' => ' Sítios Novos'],
                ['id_city' => 1903, 'id_state' => 6, 'name' => ' Siupê'],
                ['id_city' => 1904, 'id_state' => 6, 'name' => ' Sobral'],
                ['id_city' => 1905, 'id_state' => 6, 'name' => ' Soledade'],
                ['id_city' => 1906, 'id_state' => 6, 'name' => ' Solonópole'],
                ['id_city' => 1907, 'id_state' => 6, 'name' => ' Suassurana'],
                ['id_city' => 1908, 'id_state' => 6, 'name' => ' Sucatinga'],
                ['id_city' => 1909, 'id_state' => 6, 'name' => ' Sucesso'],
                ['id_city' => 1910, 'id_state' => 6, 'name' => ' Sussuanha'],
                ['id_city' => 1911, 'id_state' => 6, 'name' => ' Tabainha'],
                ['id_city' => 1912, 'id_state' => 6, 'name' => ' Taboleiro'],
                ['id_city' => 1913, 'id_state' => 6, 'name' => ' Tabuleiro do Norte'],
                ['id_city' => 1914, 'id_state' => 6, 'name' => ' Taíba'],
                ['id_city' => 1915, 'id_state' => 6, 'name' => ' Tamboril'],
                ['id_city' => 1916, 'id_state' => 6, 'name' => ' Tanques'],
                ['id_city' => 1917, 'id_state' => 6, 'name' => ' Tapera'],
                ['id_city' => 1918, 'id_state' => 6, 'name' => ' Taperuaba'],
                ['id_city' => 1919, 'id_state' => 6, 'name' => ' Tapuiara'],
                ['id_city' => 1920, 'id_state' => 6, 'name' => ' Targinos'],
                ['id_city' => 1921, 'id_state' => 6, 'name' => ' Tarrafas'],
                ['id_city' => 1922, 'id_state' => 6, 'name' => ' Tauá'],
                ['id_city' => 1923, 'id_state' => 6, 'name' => ' Tejuçuoca'],
                ['id_city' => 1924, 'id_state' => 6, 'name' => ' Tianguá'],
                ['id_city' => 1925, 'id_state' => 6, 'name' => ' Timonha'],
                ['id_city' => 1926, 'id_state' => 6, 'name' => ' Tipi'],
                ['id_city' => 1927, 'id_state' => 6, 'name' => ' Tomé'],
                ['id_city' => 1928, 'id_state' => 6, 'name' => ' Trairi'],
                ['id_city' => 1929, 'id_state' => 6, 'name' => ' Trapiá'],
                ['id_city' => 1930, 'id_state' => 6, 'name' => ' Trici'],
                ['id_city' => 1931, 'id_state' => 6, 'name' => ' Tróia'],
                ['id_city' => 1932, 'id_state' => 6, 'name' => ' Trussu'],
                ['id_city' => 1933, 'id_state' => 6, 'name' => ' Tucunduba'],
                ['id_city' => 1934, 'id_state' => 6, 'name' => ' Tucuns'],
                ['id_city' => 1935, 'id_state' => 6, 'name' => ' Tuína'],
                ['id_city' => 1936, 'id_state' => 6, 'name' => ' Tururu'],
                ['id_city' => 1937, 'id_state' => 6, 'name' => ' Ubajara'],
                ['id_city' => 1938, 'id_state' => 6, 'name' => ' Ubaúna'],
                ['id_city' => 1939, 'id_state' => 6, 'name' => ' Ubiraçu'],
                ['id_city' => 1940, 'id_state' => 6, 'name' => ' Uiraponga'],
                ['id_city' => 1941, 'id_state' => 6, 'name' => ' Umari'],
                ['id_city' => 1942, 'id_state' => 6, 'name' => ' Umarituba'],
                ['id_city' => 1943, 'id_state' => 6, 'name' => ' Umburanas'],
                ['id_city' => 1944, 'id_state' => 6, 'name' => ' Umirim'],
                ['id_city' => 1945, 'id_state' => 6, 'name' => ' Uruburetama'],
                ['id_city' => 1946, 'id_state' => 6, 'name' => ' Uruoca'],
                ['id_city' => 1947, 'id_state' => 6, 'name' => ' Uruquê'],
                ['id_city' => 1948, 'id_state' => 6, 'name' => ' Varjota'],
                ['id_city' => 1949, 'id_state' => 6, 'name' => ' Várzea'],
                ['id_city' => 1950, 'id_state' => 6, 'name' => ' Várzea Alegre'],
                ['id_city' => 1951, 'id_state' => 6, 'name' => ' Várzea da Volta'],
                ['id_city' => 1952, 'id_state' => 6, 'name' => ' Várzea do Gilo'],
                ['id_city' => 1953, 'id_state' => 6, 'name' => ' Vazantes'],
                ['id_city' => 1954, 'id_state' => 6, 'name' => ' Ventura'],
                ['id_city' => 1955, 'id_state' => 6, 'name' => ' Vertentes do Lagedo'],
                ['id_city' => 1956, 'id_state' => 6, 'name' => ' Viçosa do Ceará'],
                ['id_city' => 1957, 'id_state' => 6, 'name' => ' Viçosa'],
                ['id_city' => 1958, 'id_state' => 6, 'name' => ' Vila Soares'],
                ['id_city' => 1959, 'id_state' => 7, 'name' => ' Brasília'],
                ['id_city' => 1960, 'id_state' => 8, 'name' => ' Acioli'],
                ['id_city' => 1961, 'id_state' => 8, 'name' => ' Afonso Cláudio'],
                ['id_city' => 1962, 'id_state' => 8, 'name' => ' Aghá'],
                ['id_city' => 1963, 'id_state' => 8, 'name' => ' Água Doce do Norte'],
                ['id_city' => 1964, 'id_state' => 8, 'name' => ' Águia Branca'],
                ['id_city' => 1965, 'id_state' => 8, 'name' => ' Airituba'],
                ['id_city' => 1966, 'id_state' => 8, 'name' => ' Alegre'],
                ['id_city' => 1967, 'id_state' => 8, 'name' => ' Alfredo Chaves'],
                ['id_city' => 1968, 'id_state' => 8, 'name' => ' Alto Calçado'],
                ['id_city' => 1969, 'id_state' => 8, 'name' => ' Alto Caldeirão'],
                ['id_city' => 1970, 'id_state' => 8, 'name' => ' Alto Mutum Preto'],
                ['id_city' => 1971, 'id_state' => 8, 'name' => ' Alto Rio Novo'],
                ['id_city' => 1972, 'id_state' => 8, 'name' => ' Alto Santa Maria'],
                ['id_city' => 1973, 'id_state' => 8, 'name' => ' Anchieta'],
                ['id_city' => 1974, 'id_state' => 8, 'name' => ' Ângelo Frechiani'],
                ['id_city' => 1975, 'id_state' => 8, 'name' => ' Anutiba'],
                ['id_city' => 1976, 'id_state' => 8, 'name' => ' Apiacá'],
                ['id_city' => 1977, 'id_state' => 8, 'name' => ' Araçatiba'],
                ['id_city' => 1978, 'id_state' => 8, 'name' => ' Aracê'],
                ['id_city' => 1979, 'id_state' => 8, 'name' => ' Aracruz'],
                ['id_city' => 1980, 'id_state' => 8, 'name' => ' Aracui'],
                ['id_city' => 1981, 'id_state' => 8, 'name' => ' Araguaia'],
                ['id_city' => 1982, 'id_state' => 8, 'name' => ' Araraí'],
                ['id_city' => 1983, 'id_state' => 8, 'name' => ' Argolas'],
                ['id_city' => 1984, 'id_state' => 8, 'name' => ' Atílio Vivácqua'],
                ['id_city' => 1985, 'id_state' => 8, 'name' => ' Baía Nova'],
                ['id_city' => 1986, 'id_state' => 8, 'name' => ' Baixo Guandu'],
                ['id_city' => 1987, 'id_state' => 8, 'name' => ' Morello'],
                ['id_city' => 1988, 'id_state' => 8, 'name' => ' Barra de São Francisco'],
                ['id_city' => 1989, 'id_state' => 8, 'name' => ' Barra Nova'],
                ['id_city' => 1990, 'id_state' => 8, 'name' => ' Barra Seca'],
                ['id_city' => 1991, 'id_state' => 8, 'name' => ' Baunilha'],
                ['id_city' => 1992, 'id_state' => 8, 'name' => ' Bebedouro'],
                ['id_city' => 1993, 'id_state' => 8, 'name' => ' Boa Esperança'],
                ['id_city' => 1994, 'id_state' => 8, 'name' => ' Boapaba'],
                ['id_city' => 1995, 'id_state' => 8, 'name' => ' Bom Jesus do Norte'],
                ['id_city' => 1996, 'id_state' => 8, 'name' => ' Bonsucesso'],
                ['id_city' => 1997, 'id_state' => 8, 'name' => ' Braço do Rio'],
                ['id_city' => 1998, 'id_state' => 8, 'name' => ' Brejetuba'],
                ['id_city' => 1999, 'id_state' => 8, 'name' => ' Burarama'],
                ['id_city' => 2000, 'id_state' => 8, 'name' => ' Cachoeirinha de Itaúna'],
                ['id_city' => 2001, 'id_state' => 8, 'name' => ' Cachoeiro de Itapemirim'],
                ['id_city' => 2002, 'id_state' => 8, 'name' => ' Café'],
                ['id_city' => 2003, 'id_state' => 8, 'name' => ' Calogi'],
                ['id_city' => 2004, 'id_state' => 8, 'name' => ' Câmara'],
                ['id_city' => 2005, 'id_state' => 8, 'name' => ' Carapina'],
                ['id_city' => 2006, 'id_state' => 8, 'name' => ' Cariacica'],
                ['id_city' => 2007, 'id_state' => 8, 'name' => ' Castelo'],
                ['id_city' => 2008, 'id_state' => 8, 'name' => ' Celina'],
                ['id_city' => 2009, 'id_state' => 8, 'name' => ' Colatina'],
                ['id_city' => 2010, 'id_state' => 8, 'name' => ' Conceição da Barra'],
                ['id_city' => 2011, 'id_state' => 8, 'name' => ' Conceição do Castelo'],
                ['id_city' => 2012, 'id_state' => 8, 'name' => ' Conceição do Muqui'],
                ['id_city' => 2013, 'id_state' => 8, 'name' => ' Conduru'],
                ['id_city' => 2014, 'id_state' => 8, 'name' => ' Praia do Coqueiral'],
                ['id_city' => 2015, 'id_state' => 8, 'name' => ' Córrego dos Monos'],
                ['id_city' => 2016, 'id_state' => 8, 'name' => ' Cotaxé'],
                ['id_city' => 2017, 'id_state' => 8, 'name' => ' Cristal do Norte'],
                ['id_city' => 2018, 'id_state' => 8, 'name' => ' Crubixá'],
                ['id_city' => 2019, 'id_state' => 8, 'name' => ' Desengano'],
                ['id_city' => 2020, 'id_state' => 8, 'name' => ' Divino de São Lourenço'],
                ['id_city' => 2021, 'id_state' => 8, 'name' => ' Divino Espírito Santo'],
                ['id_city' => 2022, 'id_state' => 8, 'name' => ' Djalma Coutinho'],
                ['id_city' => 2023, 'id_state' => 8, 'name' => ' Domingos Martins'],
                ['id_city' => 2024, 'id_state' => 8, 'name' => ' Dona América'],
                ['id_city' => 2025, 'id_state' => 8, 'name' => ' Dores do Rio Preto'],
                ['id_city' => 2026, 'id_state' => 8, 'name' => ' Duas Barras'],
                ['id_city' => 2027, 'id_state' => 8, 'name' => ' Ecoporanga'],
                ['id_city' => 2028, 'id_state' => 8, 'name' => ' Estrela do Norte'],
                ['id_city' => 2029, 'id_state' => 8, 'name' => ' Fartura'],
                ['id_city' => 2030, 'id_state' => 8, 'name' => ' Fazenda Guandu'],
                ['id_city' => 2031, 'id_state' => 8, 'name' => ' Fundão'],
                ['id_city' => 2032, 'id_state' => 8, 'name' => ' Garrafão'],
                ['id_city' => 2033, 'id_state' => 8, 'name' => ' Gironda'],
                ['id_city' => 2034, 'id_state' => 8, 'name' => ' Goiabeiras'],
                ['id_city' => 2035, 'id_state' => 8, 'name' => ' Governador Lacerda de Aguiar'],
                ['id_city' => 2036, 'id_state' => 8, 'name' => ' Governador Lindenberg'],
                ['id_city' => 2037, 'id_state' => 8, 'name' => ' Graça Aranha'],
                ['id_city' => 2038, 'id_state' => 8, 'name' => ' Gruta'],
                ['id_city' => 2039, 'id_state' => 8, 'name' => ' Guaçuí'],
                ['id_city' => 2040, 'id_state' => 8, 'name' => ' Vila Guaraná'],
                ['id_city' => 2041, 'id_state' => 8, 'name' => ' Guarapari'],
                ['id_city' => 2042, 'id_state' => 8, 'name' => ' Guararema'],
                ['id_city' => 2043, 'id_state' => 8, 'name' => ' Ibatiba'],
                ['id_city' => 2044, 'id_state' => 8, 'name' => ' Ibicaba'],
                ['id_city' => 2045, 'id_state' => 8, 'name' => ' Ibiraçu'],
                ['id_city' => 2046, 'id_state' => 8, 'name' => ' Ibitirama'],
                ['id_city' => 2047, 'id_state' => 8, 'name' => ' Ibitiruí'],
                ['id_city' => 2048, 'id_state' => 8, 'name' => ' Ibituba'],
                ['id_city' => 2049, 'id_state' => 8, 'name' => ' Iconha'],
                ['id_city' => 2050, 'id_state' => 8, 'name' => ' Imburana'],
                ['id_city' => 2051, 'id_state' => 8, 'name' => ' Iriritiba'],
                ['id_city' => 2052, 'id_state' => 8, 'name' => ' Irundi'],
                ['id_city' => 2053, 'id_state' => 8, 'name' => ' Irupi'],
                ['id_city' => 2054, 'id_state' => 8, 'name' => ' Isabel'],
                ['id_city' => 2055, 'id_state' => 8, 'name' => ' Itabaiana'],
                ['id_city' => 2056, 'id_state' => 8, 'name' => ' Itaçu'],
                ['id_city' => 2057, 'id_state' => 8, 'name' => ' Itaguaçu'],
                ['id_city' => 2058, 'id_state' => 8, 'name' => ' Itaicí'],
                ['id_city' => 2059, 'id_state' => 8, 'name' => ' Itaimbé'],
                ['id_city' => 2060, 'id_state' => 8, 'name' => ' Itaipava'],
                ['id_city' => 2061, 'id_state' => 8, 'name' => ' Itamira'],
                ['id_city' => 2062, 'id_state' => 8, 'name' => ' Itaóca'],
                ['id_city' => 2063, 'id_state' => 8, 'name' => ' Itapecoá'],
                ['id_city' => 2064, 'id_state' => 8, 'name' => ' Itapemirim'],
                ['id_city' => 2065, 'id_state' => 8, 'name' => ' Itaperuna'],
                ['id_city' => 2066, 'id_state' => 8, 'name' => ' Itapina'],
                ['id_city' => 2067, 'id_state' => 8, 'name' => ' Itaquari'],
                ['id_city' => 2068, 'id_state' => 8, 'name' => ' Itarana'],
                ['id_city' => 2069, 'id_state' => 8, 'name' => ' Itaúnas'],
                ['id_city' => 2070, 'id_state' => 8, 'name' => ' Itauninhas'],
                ['id_city' => 2071, 'id_state' => 8, 'name' => ' Iúna'],
                ['id_city' => 2072, 'id_state' => 8, 'name' => ' Jabaquara'],
                ['id_city' => 2073, 'id_state' => 8, 'name' => ' Jacaraipe'],
                ['id_city' => 2074, 'id_state' => 8, 'name' => ' Jaciguá'],
                ['id_city' => 2075, 'id_state' => 8, 'name' => ' Jacupemba'],
                ['id_city' => 2076, 'id_state' => 8, 'name' => ' Jaguaré'],
                ['id_city' => 2077, 'id_state' => 8, 'name' => ' Jerônimo Monteiro'],
                ['id_city' => 2078, 'id_state' => 8, 'name' => ' Joaçuba'],
                ['id_city' => 2079, 'id_state' => 8, 'name' => ' João Neiva'],
                ['id_city' => 2080, 'id_state' => 8, 'name' => ' Joatuba'],
                ['id_city' => 2081, 'id_state' => 8, 'name' => ' José Carlos'],
                ['id_city' => 2082, 'id_state' => 8, 'name' => ' Lajinha'],
                ['id_city' => 2083, 'id_state' => 8, 'name' => ' Laranja da Terra'],
                ['id_city' => 2084, 'id_state' => 8, 'name' => ' Limoeiro'],
                ['id_city' => 2085, 'id_state' => 8, 'name' => ' Linhares'],
                ['id_city' => 2086, 'id_state' => 8, 'name' => ' Mangaraí'],
                ['id_city' => 2087, 'id_state' => 8, 'name' => ' Mantenópolis'],
                ['id_city' => 2088, 'id_state' => 8, 'name' => ' Marataízes'],
                ['id_city' => 2089, 'id_state' => 8, 'name' => ' Marechal Floriano'],
                ['id_city' => 2090, 'id_state' => 8, 'name' => ' Marilândia'],
                ['id_city' => 2091, 'id_state' => 8, 'name' => ' Matilde'],
                ['id_city' => 2092, 'id_state' => 8, 'name' => ' Melgaço'],
                ['id_city' => 2093, 'id_state' => 8, 'name' => ' Menino Jesus'],
                ['id_city' => 2094, 'id_state' => 8, 'name' => ' Mimoso do Sul'],
                ['id_city' => 2095, 'id_state' => 8, 'name' => ' Montanha'],
                ['id_city' => 2096, 'id_state' => 8, 'name' => ' Monte Carmelo do Rio Novo'],
                ['id_city' => 2097, 'id_state' => 8, 'name' => ' Monte Pio'],
                ['id_city' => 2098, 'id_state' => 8, 'name' => ' Monte Sinai'],
                ['id_city' => 2099, 'id_state' => 8, 'name' => ' Mucurici'],
                ['id_city' => 2100, 'id_state' => 8, 'name' => ' Mundo Novo'],
                ['id_city' => 2101, 'id_state' => 8, 'name' => ' Muniz Freire'],
                ['id_city' => 2102, 'id_state' => 8, 'name' => ' Muqui'],
                ['id_city' => 2103, 'id_state' => 8, 'name' => ' Nestor Gomes'],
                ['id_city' => 2104, 'id_state' => 8, 'name' => ' Nova Almeida'],
                ['id_city' => 2105, 'id_state' => 8, 'name' => ' Nova Venécia'],
                ['id_city' => 2106, 'id_state' => 8, 'name' => ' Nova Verona'],
                ['id_city' => 2107, 'id_state' => 8, 'name' => ' Novo Brasil'],
                ['id_city' => 2108, 'id_state' => 8, 'name' => ' Novo Horizonte'],
                ['id_city' => 2109, 'id_state' => 8, 'name' => ' Pacotuba'],
                ['id_city' => 2110, 'id_state' => 8, 'name' => ' Paineiras'],
                ['id_city' => 2111, 'id_state' => 8, 'name' => ' Palmeira'],
                ['id_city' => 2112, 'id_state' => 8, 'name' => ' Palmerino'],
                ['id_city' => 2113, 'id_state' => 8, 'name' => ' Pancas'],
                ['id_city' => 2114, 'id_state' => 8, 'name' => ' Paraju'],
                ['id_city' => 2115, 'id_state' => 8, 'name' => ' Paulista'],
                ['id_city' => 2116, 'id_state' => 8, 'name' => ' Pedro Canário'],
                ['id_city' => 2117, 'id_state' => 8, 'name' => ' Pendanga'],
                ['id_city' => 2118, 'id_state' => 8, 'name' => ' Pequiá'],
                ['id_city' => 2119, 'id_state' => 8, 'name' => ' Nossa Senhora das Graças'],
                ['id_city' => 2120, 'id_state' => 8, 'name' => ' Piaçu'],
                ['id_city' => 2121, 'id_state' => 8, 'name' => ' Pinheiros'],
                ['id_city' => 2122, 'id_state' => 8, 'name' => ' Piracema'],
                ['id_city' => 2123, 'id_state' => 8, 'name' => ' Piúma'],
                ['id_city' => 2124, 'id_state' => 8, 'name' => ' Ponte de Itabapoana'],
                ['id_city' => 2125, 'id_state' => 8, 'name' => ' Ponto Belo'],
                ['id_city' => 2126, 'id_state' => 8, 'name' => ' Pontões'],
                ['id_city' => 2127, 'id_state' => 8, 'name' => ' Porangá'],
                ['id_city' => 2128, 'id_state' => 8, 'name' => ' Barra do Riacho'],
                ['id_city' => 2129, 'id_state' => 8, 'name' => ' Praia Grande'],
                ['id_city' => 2130, 'id_state' => 8, 'name' => ' Presidente Kennedy'],
                ['id_city' => 2131, 'id_state' => 8, 'name' => ' Princesa'],
                ['id_city' => 2132, 'id_state' => 8, 'name' => ' Queimado'],
                ['id_city' => 2133, 'id_state' => 8, 'name' => ' Quilômetro 14 do Mutum'],
                ['id_city' => 2134, 'id_state' => 8, 'name' => ' Regência'],
                ['id_city' => 2135, 'id_state' => 8, 'name' => ' Riacho'],
                ['id_city' => 2136, 'id_state' => 8, 'name' => ' Ribeirão do Cristo'],
                ['id_city' => 2137, 'id_state' => 8, 'name' => ' Rio Bananal'],
                ['id_city' => 2138, 'id_state' => 8, 'name' => ' Rio Calçado'],
                ['id_city' => 2139, 'id_state' => 8, 'name' => ' Rio Muqui'],
                ['id_city' => 2140, 'id_state' => 8, 'name' => ' Rio Novo do Sul'],
                ['id_city' => 2141, 'id_state' => 8, 'name' => ' Rio Preto'],
                ['id_city' => 2142, 'id_state' => 8, 'name' => ' Rive'],
                ['id_city' => 2143, 'id_state' => 8, 'name' => ' Sagrada Família'],
                ['id_city' => 2144, 'id_state' => 8, 'name' => ' Santa Angélica'],
                ['id_city' => 2145, 'id_state' => 8, 'name' => ' Santa Cruz'],
                ['id_city' => 2146, 'id_state' => 8, 'name' => ' Santa Júlia'],
                ['id_city' => 2147, 'id_state' => 8, 'name' => ' Santa Leopoldina'],
                ['id_city' => 2148, 'id_state' => 8, 'name' => ' Santa Luzia de Mantenópolis'],
                ['id_city' => 2149, 'id_state' => 8, 'name' => ' Santa Luzia do Azul'],
                ['id_city' => 2150, 'id_state' => 8, 'name' => ' Santa Luzia do Norte'],
                ['id_city' => 2151, 'id_state' => 8, 'name' => ' Santa Maria de Jetibá'],
                ['id_city' => 2152, 'id_state' => 8, 'name' => ' Santa Marta'],
                ['id_city' => 2153, 'id_state' => 8, 'name' => ' Santa Teresa'],
                ['id_city' => 2154, 'id_state' => 8, 'name' => ' Santa Terezinha'],
                ['id_city' => 2155, 'id_state' => 8, 'name' => ' Santíssima Trindade'],
                ['id_city' => 2156, 'id_state' => 8, 'name' => ' Santo Agostinho'],
                ['id_city' => 2157, 'id_state' => 8, 'name' => ' Santo Antônio'],
                ['id_city' => 2158, 'id_state' => 8, 'name' => ' Santo Antônio do Canaã'],
                ['id_city' => 2159, 'id_state' => 8, 'name' => ' Santo Antônio do Muqui'],
                ['id_city' => 2160, 'id_state' => 8, 'name' => ' Santo Antônio do Pousalegre'],
                ['id_city' => 2161, 'id_state' => 8, 'name' => ' Santo Antônio do Quinze'],
                ['id_city' => 2162, 'id_state' => 8, 'name' => ' São Domingos do Norte'],
                ['id_city' => 2163, 'id_state' => 8, 'name' => ' São Francisco'],
                ['id_city' => 2164, 'id_state' => 8, 'name' => ' São Francisco Xavier do Guandu'],
                ['id_city' => 2165, 'id_state' => 8, 'name' => ' São Gabriel da Palha'],
                ['id_city' => 2166, 'id_state' => 8, 'name' => ' São Geraldo'],
                ['id_city' => 2167, 'id_state' => 8, 'name' => ' São Jacinto'],
                ['id_city' => 2168, 'id_state' => 8, 'name' => ' São João de Petrópolis'],
                ['id_city' => 2169, 'id_state' => 8, 'name' => ' São João de Viçosa'],
                ['id_city' => 2170, 'id_state' => 8, 'name' => ' São João do Sobrado'],
                ['id_city' => 2171, 'id_state' => 8, 'name' => ' São Jorge do Oliveira'],
                ['id_city' => 2172, 'id_state' => 8, 'name' => ' São Jorge do Tiradentes'],
                ['id_city' => 2173, 'id_state' => 8, 'name' => ' São José das Torres'],
                ['id_city' => 2174, 'id_state' => 8, 'name' => ' São José de Mantenópolis'],
                ['id_city' => 2175, 'id_state' => 8, 'name' => ' São José do Calçado'],
                ['id_city' => 2176, 'id_state' => 8, 'name' => ' São José do Sobradinho'],
                ['id_city' => 2177, 'id_state' => 8, 'name' => ' São Mateus'],
                ['id_city' => 2178, 'id_state' => 8, 'name' => ' São Pedro'],
                ['id_city' => 2179, 'id_state' => 8, 'name' => ' São Pedro de Itabapoana'],
                ['id_city' => 2180, 'id_state' => 8, 'name' => ' São Pedro de Rates'],
                ['id_city' => 2181, 'id_state' => 8, 'name' => ' São Rafael'],
                ['id_city' => 2182, 'id_state' => 8, 'name' => ' São Roque do Canaã'],
                ['id_city' => 2183, 'id_state' => 8, 'name' => ' São Tiago'],
                ['id_city' => 2184, 'id_state' => 8, 'name' => ' Sapucaia'],
                ['id_city' => 2185, 'id_state' => 8, 'name' => ' Serra'],
                ['id_city' => 2186, 'id_state' => 8, 'name' => ' Serra Pelada'],
                ['id_city' => 2187, 'id_state' => 8, 'name' => ' Sobreiro'],
                ['id_city' => 2188, 'id_state' => 8, 'name' => ' Sooretama'],
                ['id_city' => 2189, 'id_state' => 8, 'name' => ' Timbuí'],
                ['id_city' => 2190, 'id_state' => 8, 'name' => ' Todos os Santos'],
                ['id_city' => 2191, 'id_state' => 8, 'name' => ' Urânia'],
                ['id_city' => 2192, 'id_state' => 8, 'name' => ' Vargem Alta'],
                ['id_city' => 2193, 'id_state' => 8, 'name' => ' Vargem Grande do Soturno'],
                ['id_city' => 2194, 'id_state' => 8, 'name' => ' Venda Nova do Imigrante'],
                ['id_city' => 2195, 'id_state' => 8, 'name' => ' Viana'],
                ['id_city' => 2196, 'id_state' => 8, 'name' => ' Vieira Machado'],
                ['id_city' => 2197, 'id_state' => 8, 'name' => ' Vila Nelita'],
                ['id_city' => 2198, 'id_state' => 8, 'name' => ' Vila Nova de Bananal'],
                ['id_city' => 2199, 'id_state' => 8, 'name' => ' Vila Pavão'],
                ['id_city' => 2200, 'id_state' => 8, 'name' => ' Vila Valério'],
                ['id_city' => 2201, 'id_state' => 8, 'name' => ' Vila Velha'],
                ['id_city' => 2202, 'id_state' => 8, 'name' => ' Vila Verde'],
                ['id_city' => 2203, 'id_state' => 8, 'name' => ' Vinhático'],
                ['id_city' => 2204, 'id_state' => 8, 'name' => ' Vinte e Cinco de Julho'],
                ['id_city' => 2205, 'id_state' => 8, 'name' => ' Vitória'],
                ['id_city' => 2206, 'id_state' => 9, 'name' => ' Abadia de Goiás'],
                ['id_city' => 2207, 'id_state' => 9, 'name' => ' Abadiânia'],
                ['id_city' => 2208, 'id_state' => 9, 'name' => ' Acreúna'],
                ['id_city' => 2209, 'id_state' => 9, 'name' => ' Adelândia'],
                ['id_city' => 2210, 'id_state' => 9, 'name' => ' Água Fria de Goiás'],
                ['id_city' => 2211, 'id_state' => 9, 'name' => ' Água Limpa'],
                ['id_city' => 2212, 'id_state' => 9, 'name' => ' Águas Lindas de Goiás'],
                ['id_city' => 2213, 'id_state' => 9, 'name' => ' Alexânia'],
                ['id_city' => 2214, 'id_state' => 9, 'name' => ' Aloândia'],
                ['id_city' => 2215, 'id_state' => 9, 'name' => ' Alto Alvorada'],
                ['id_city' => 2216, 'id_state' => 9, 'name' => ' Alto Horizonte'],
                ['id_city' => 2217, 'id_state' => 9, 'name' => ' Alto Paraíso de Goiás'],
                ['id_city' => 2218, 'id_state' => 9, 'name' => ' Alvorada do Norte'],
                ['id_city' => 2219, 'id_state' => 9, 'name' => ' Amaralina'],
                ['id_city' => 2220, 'id_state' => 9, 'name' => ' Americano do Brasil'],
                ['id_city' => 2221, 'id_state' => 9, 'name' => ' Amorinópolis'],
                ['id_city' => 2222, 'id_state' => 9, 'name' => ' Anápolis'],
                ['id_city' => 2223, 'id_state' => 9, 'name' => ' Anhangüera'],
                ['id_city' => 2224, 'id_state' => 9, 'name' => ' Anicuns'],
                ['id_city' => 2225, 'id_state' => 9, 'name' => ' Aparecida'],
                ['id_city' => 2226, 'id_state' => 9, 'name' => ' Aparecida de Goiânia'],
                ['id_city' => 2227, 'id_state' => 9, 'name' => ' Aparecida de Goiás'],
                ['id_city' => 2228, 'id_state' => 9, 'name' => ' Aparecida do Rio Claro'],
                ['id_city' => 2229, 'id_state' => 9, 'name' => ' Aparecida do Rio Doce'],
                ['id_city' => 2230, 'id_state' => 9, 'name' => ' Aporé'],
                ['id_city' => 2231, 'id_state' => 9, 'name' => ' Araçu'],
                ['id_city' => 2232, 'id_state' => 9, 'name' => ' Aragarças'],
                ['id_city' => 2233, 'id_state' => 9, 'name' => ' Aragoiânia']
            ]);
    }
}