<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities6 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        DB::table('vpr_countries_states_cities')->insert([
            ['id_city' => 3521, 'id_state' => 13, 'name' => ' Manga'],
            ['id_city' => 3522, 'id_state' => 13, 'name' => ' Manhuaçu'],
            ['id_city' => 3523, 'id_state' => 13, 'name' => ' Manhumirim'],
            ['id_city' => 3524, 'id_state' => 13, 'name' => ' Mantena'],
            ['id_city' => 3525, 'id_state' => 13, 'name' => ' Mantiqueira'],
            ['id_city' => 3526, 'id_state' => 13, 'name' => ' Mantiqueira do Palmital'],
            ['id_city' => 3527, 'id_state' => 13, 'name' => ' Mar de Espanha'],
            ['id_city' => 3528, 'id_state' => 13, 'name' => ' Marambainha'],
            ['id_city' => 3529, 'id_state' => 13, 'name' => ' Maravilhas'],
            ['id_city' => 3530, 'id_state' => 13, 'name' => ' Maria da Fé'],
            ['id_city' => 3531, 'id_state' => 13, 'name' => ' Mariana'],
            ['id_city' => 3532, 'id_state' => 13, 'name' => ' Marilac'],
            ['id_city' => 3533, 'id_state' => 13, 'name' => ' Marilândia'],
            ['id_city' => 3534, 'id_state' => 13, 'name' => ' Mário Campos'],
            ['id_city' => 3535, 'id_state' => 13, 'name' => ' Maripá de Minas'],
            ['id_city' => 3536, 'id_state' => 13, 'name' => ' Marliéria'],
            ['id_city' => 3537, 'id_state' => 13, 'name' => ' Marmelópolis'],
            ['id_city' => 3538, 'id_state' => 13, 'name' => ' Martinésia'],
            ['id_city' => 3539, 'id_state' => 13, 'name' => ' Martinho Campos'],
            ['id_city' => 3540, 'id_state' => 13, 'name' => ' Martins Guimarães'],
            ['id_city' => 3541, 'id_state' => 13, 'name' => ' Martins Soares'],
            ['id_city' => 3542, 'id_state' => 13, 'name' => ' Mata Verde'],
            ['id_city' => 3543, 'id_state' => 13, 'name' => ' Materlândia'],
            ['id_city' => 3544, 'id_state' => 13, 'name' => ' Mateus Leme'],
            ['id_city' => 3545, 'id_state' => 13, 'name' => ' Mathias Lobato'],
            ['id_city' => 3546, 'id_state' => 13, 'name' => ' Matias Barbosa'],
            ['id_city' => 3547, 'id_state' => 13, 'name' => ' Matias Cardoso'],
            ['id_city' => 3548, 'id_state' => 13, 'name' => ' Matipó'],
            ['id_city' => 3549, 'id_state' => 13, 'name' => ' Mato Verde'],
            ['id_city' => 3550, 'id_state' => 13, 'name' => ' Matozinhos'],
            ['id_city' => 3551, 'id_state' => 13, 'name' => ' Matutina'],
            ['id_city' => 3552, 'id_state' => 13, 'name' => ' Medeiros'],
            ['id_city' => 3553, 'id_state' => 13, 'name' => ' Medina'],
            ['id_city' => 3554, 'id_state' => 13, 'name' => ' Melo Viana'],
            ['id_city' => 3555, 'id_state' => 13, 'name' => ' Mendanha'],
            ['id_city' => 3556, 'id_state' => 13, 'name' => ' Mendes Pimentel'],
            ['id_city' => 3557, 'id_state' => 13, 'name' => ' Mendonça'],
            ['id_city' => 3558, 'id_state' => 13, 'name' => ' Mercês'],
            ['id_city' => 3559, 'id_state' => 13, 'name' => ' Mercês de Água Limpa'],
            ['id_city' => 3560, 'id_state' => 13, 'name' => ' Mesquita'],
            ['id_city' => 3561, 'id_state' => 13, 'name' => ' Mestre Caetano'],
            ['id_city' => 3562, 'id_state' => 13, 'name' => ' Miguel Burnier'],
            ['id_city' => 3563, 'id_state' => 13, 'name' => ' Milagre'],
            ['id_city' => 3564, 'id_state' => 13, 'name' => ' Milho Verde'],
            ['id_city' => 3565, 'id_state' => 13, 'name' => ' Minas Novas'],
            ['id_city' => 3566, 'id_state' => 13, 'name' => ' Minduri'],
            ['id_city' => 3567, 'id_state' => 13, 'name' => ' Mirabela'],
            ['id_city' => 3568, 'id_state' => 13, 'name' => ' Miradouro'],
            ['id_city' => 3569, 'id_state' => 13, 'name' => ' Miragaia'],
            ['id_city' => 3570, 'id_state' => 13, 'name' => ' Miraí'],
            ['id_city' => 3571, 'id_state' => 13, 'name' => ' Miralta'],
            ['id_city' => 3572, 'id_state' => 13, 'name' => ' Mirantão'],
            ['id_city' => 3573, 'id_state' => 13, 'name' => ' Miraporanga'],
            ['id_city' => 3574, 'id_state' => 13, 'name' => ' Miravânia'],
            ['id_city' => 3575, 'id_state' => 13, 'name' => ' Missionário'],
            ['id_city' => 3576, 'id_state' => 13, 'name' => ' Mocambeiro'],
            ['id_city' => 3577, 'id_state' => 13, 'name' => ' Mocambinho'],
            ['id_city' => 3578, 'id_state' => 13, 'name' => ' Moeda'],
            ['id_city' => 3579, 'id_state' => 13, 'name' => ' Moema'],
            ['id_city' => 3580, 'id_state' => 13, 'name' => ' Monjolinho de Minas'],
            ['id_city' => 3581, 'id_state' => 13, 'name' => ' Monjolos'],
            ['id_city' => 3582, 'id_state' => 13, 'name' => ' Monsenhor Horta'],
            ['id_city' => 3583, 'id_state' => 13, 'name' => ' Monsenhor Isidro'],
            ['id_city' => 3584, 'id_state' => 13, 'name' => ' Monsenhor João Alexandre'],
            ['id_city' => 3585, 'id_state' => 13, 'name' => ' Monsenhor Paulo'],
            ['id_city' => 3586, 'id_state' => 13, 'name' => ' Montalvânia'],
            ['id_city' => 3587, 'id_state' => 13, 'name' => ' Monte Alegre de Minas'],
            ['id_city' => 3588, 'id_state' => 13, 'name' => ' Monte Azul'],
            ['id_city' => 3589, 'id_state' => 13, 'name' => ' Monte Belo'],
            ['id_city' => 3590, 'id_state' => 13, 'name' => ' Monte Carmelo'],
            ['id_city' => 3591, 'id_state' => 13, 'name' => ' Monte Celeste'],
            ['id_city' => 3592, 'id_state' => 13, 'name' => ' Monte Formoso'],
            ['id_city' => 3593, 'id_state' => 13, 'name' => ' Monte Rei'],
            ['id_city' => 3594, 'id_state' => 13, 'name' => ' Monte Santo de Minas'],
            ['id_city' => 3595, 'id_state' => 13, 'name' => ' Monte Sião'],
            ['id_city' => 3596, 'id_state' => 13, 'name' => ' Monte Verde'],
            ['id_city' => 3597, 'id_state' => 13, 'name' => ' Montes Claros'],
            ['id_city' => 3598, 'id_state' => 13, 'name' => ' Montezuma'],
            ['id_city' => 3599, 'id_state' => 13, 'name' => ' Morada Nova de Minas'],
            ['id_city' => 3600, 'id_state' => 13, 'name' => ' Morro'],
            ['id_city' => 3601, 'id_state' => 13, 'name' => ' Morro da Garça'],
            ['id_city' => 3602, 'id_state' => 13, 'name' => ' Morro do Ferro'],
            ['id_city' => 3603, 'id_state' => 13, 'name' => ' Morro do Pilar'],
            ['id_city' => 3604, 'id_state' => 13, 'name' => ' Morro Vermelho'],
            ['id_city' => 3605, 'id_state' => 13, 'name' => ' Mucuri'],
            ['id_city' => 3606, 'id_state' => 13, 'name' => ' Mundo Novo de Minas'],
            ['id_city' => 3607, 'id_state' => 13, 'name' => ' Munhoz'],
            ['id_city' => 3608, 'id_state' => 13, 'name' => ' Muquém'],
            ['id_city' => 3609, 'id_state' => 13, 'name' => ' Muriaé'],
            ['id_city' => 3610, 'id_state' => 13, 'name' => ' Mutum'],
            ['id_city' => 3611, 'id_state' => 13, 'name' => ' Muzambinho'],
            ['id_city' => 3612, 'id_state' => 13, 'name' => ' Nacip Raydan'],
            ['id_city' => 3613, 'id_state' => 13, 'name' => ' Nanuque'],
            ['id_city' => 3614, 'id_state' => 13, 'name' => ' Naque'],
            ['id_city' => 3615, 'id_state' => 13, 'name' => ' Naque-Nanuque'],
            ['id_city' => 3616, 'id_state' => 13, 'name' => ' Natalândia'],
            ['id_city' => 3617, 'id_state' => 13, 'name' => ' Natércia'],
            ['id_city' => 3618, 'id_state' => 13, 'name' => ' Nazaré de Minas'],
            ['id_city' => 3619, 'id_state' => 13, 'name' => ' Nazareno'],
            ['id_city' => 3620, 'id_state' => 13, 'name' => ' Nelson de Sena'],
            ['id_city' => 3621, 'id_state' => 13, 'name' => ' Neolândia'],
            ['id_city' => 3622, 'id_state' => 13, 'name' => ' Nepomuceno'],
            ['id_city' => 3623, 'id_state' => 13, 'name' => ' Nhandutiba'],
            ['id_city' => 3624, 'id_state' => 13, 'name' => ' Nicolândia'],
            ['id_city' => 3625, 'id_state' => 13, 'name' => ' Ninheira'],
            ['id_city' => 3626, 'id_state' => 13, 'name' => ' Nova Belém'],
            ['id_city' => 3627, 'id_state' => 13, 'name' => ' Nova Era'],
            ['id_city' => 3628, 'id_state' => 13, 'name' => ' Nova Esperança'],
            ['id_city' => 3629, 'id_state' => 13, 'name' => ' Nova Lima'],
            ['id_city' => 3630, 'id_state' => 13, 'name' => ' Nova Minda'],
            ['id_city' => 3631, 'id_state' => 13, 'name' => ' Nova Módica'],
            ['id_city' => 3632, 'id_state' => 13, 'name' => ' Nova Ponte'],
            ['id_city' => 3633, 'id_state' => 13, 'name' => ' Nova Porteirinha'],
            ['id_city' => 3634, 'id_state' => 13, 'name' => ' Nova Resende'],
            ['id_city' => 3635, 'id_state' => 13, 'name' => ' Nova Serrana'],
            ['id_city' => 3636, 'id_state' => 13, 'name' => ' Nova União'],
            ['id_city' => 3637, 'id_state' => 13, 'name' => ' Novilhona'],
            ['id_city' => 3638, 'id_state' => 13, 'name' => ' Novo Cruzeiro'],
            ['id_city' => 3639, 'id_state' => 13, 'name' => ' Novo Horizonte'],
            ['id_city' => 3640, 'id_state' => 13, 'name' => ' Novo Oriente de Minas'],
            ['id_city' => 3641, 'id_state' => 13, 'name' => ' Novorizonte'],
            ['id_city' => 3642, 'id_state' => 13, 'name' => ' Ocidente'],
            ['id_city' => 3643, 'id_state' => 13, 'name' => ' Olaria'],
            ['id_city' => 3644, 'id_state' => 13, 'name' => ' Olegário Maciel'],
            ['id_city' => 3645, 'id_state' => 13, 'name' => ' Olhos D Água do Oeste'],
            ['id_city' => 3646, 'id_state' => 13, 'name' => ' Olhos D Água'],
            ['id_city' => 3647, 'id_state' => 13, 'name' => ' Olímpio Campos'],
            ['id_city' => 3648, 'id_state' => 13, 'name' => ' Olímpio Noronha'],
            ['id_city' => 3649, 'id_state' => 13, 'name' => ' Oliveira'],
            ['id_city' => 3650, 'id_state' => 13, 'name' => ' Oliveira Fortes'],
            ['id_city' => 3651, 'id_state' => 13, 'name' => ' Onça de Pitangui'],
            ['id_city' => 3652, 'id_state' => 13, 'name' => ' Oratórios'],
            ['id_city' => 3653, 'id_state' => 13, 'name' => ' Orizânia'],
            ['id_city' => 3654, 'id_state' => 13, 'name' => ' Ouro Branco'],
            ['id_city' => 3655, 'id_state' => 13, 'name' => ' Ouro Fino'],
            ['id_city' => 3656, 'id_state' => 13, 'name' => ' Ouro Preto'],
            ['id_city' => 3657, 'id_state' => 13, 'name' => ' Ouro Verde de Minas'],
            ['id_city' => 3658, 'id_state' => 13, 'name' => ' Paciência'],
            ['id_city' => 3659, 'id_state' => 13, 'name' => ' Padre Brito'],
            ['id_city' => 3660, 'id_state' => 13, 'name' => ' Padre Carvalho'],
            ['id_city' => 3661, 'id_state' => 13, 'name' => ' Padre Felisberto'],
            ['id_city' => 3662, 'id_state' => 13, 'name' => ' Padre Fialho'],
            ['id_city' => 3663, 'id_state' => 13, 'name' => ' Padre João Afonso'],
            ['id_city' => 3664, 'id_state' => 13, 'name' => ' Padre Júlio Maria'],
            ['id_city' => 3665, 'id_state' => 13, 'name' => ' Padre Paraíso'],
            ['id_city' => 3666, 'id_state' => 13, 'name' => ' Padre Pinto'],
            ['id_city' => 3667, 'id_state' => 13, 'name' => ' Padre Viegas'],
            ['id_city' => 3668, 'id_state' => 13, 'name' => ' Pai Pedro'],
            ['id_city' => 3669, 'id_state' => 13, 'name' => ' Paineiras'],
            ['id_city' => 3670, 'id_state' => 13, 'name' => ' Pains'],
            ['id_city' => 3671, 'id_state' => 13, 'name' => ' Paiolinho'],
            ['id_city' => 3672, 'id_state' => 13, 'name' => ' Paiva'],
            ['id_city' => 3673, 'id_state' => 13, 'name' => ' Palma'],
            ['id_city' => 3674, 'id_state' => 13, 'name' => ' Palmeiral'],
            ['id_city' => 3675, 'id_state' => 13, 'name' => ' Palmeirinha'],
            ['id_city' => 3676, 'id_state' => 13, 'name' => ' Palmital dos Carvalhos'],
            ['id_city' => 3677, 'id_state' => 13, 'name' => ' Palmópolis'],
            ['id_city' => 3678, 'id_state' => 13, 'name' => ' Pântano'],
            ['id_city' => 3679, 'id_state' => 13, 'name' => ' Papagaios'],
            ['id_city' => 3680, 'id_state' => 13, 'name' => ' Pará de Minas'],
            ['id_city' => 3681, 'id_state' => 13, 'name' => ' Paracatu'],
            ['id_city' => 3682, 'id_state' => 13, 'name' => ' Paraguaçu'],
            ['id_city' => 3683, 'id_state' => 13, 'name' => ' Paraguai'],
            ['id_city' => 3684, 'id_state' => 13, 'name' => ' Paraíso Garcia'],
            ['id_city' => 3685, 'id_state' => 13, 'name' => ' Paraisópolis'],
            ['id_city' => 3686, 'id_state' => 13, 'name' => ' Paraopeba'],
            ['id_city' => 3687, 'id_state' => 13, 'name' => ' Paredão de Minas'],
            ['id_city' => 3688, 'id_state' => 13, 'name' => ' Parque Durval de Barros'],
            ['id_city' => 3689, 'id_state' => 13, 'name' => ' Parque Industrial'],
            ['id_city' => 3690, 'id_state' => 13, 'name' => ' Passa Dez'],
            ['id_city' => 3691, 'id_state' => 13, 'name' => ' Passa Quatro'],
            ['id_city' => 3692, 'id_state' => 13, 'name' => ' Passa Tempo'],
            ['id_city' => 3693, 'id_state' => 13, 'name' => ' Passa Vinte'],
            ['id_city' => 3694, 'id_state' => 13, 'name' => ' Passabém'],
            ['id_city' => 3695, 'id_state' => 13, 'name' => ' Passagem de Mariana'],
            ['id_city' => 3696, 'id_state' => 13, 'name' => ' Passos'],
            ['id_city' => 3697, 'id_state' => 13, 'name' => ' Patis'],
            ['id_city' => 3698, 'id_state' => 13, 'name' => ' Patos de Minas'],
            ['id_city' => 3699, 'id_state' => 13, 'name' => ' Patrimônio'],
            ['id_city' => 3700, 'id_state' => 13, 'name' => ' Patrocínio'],
            ['id_city' => 3701, 'id_state' => 13, 'name' => ' Patrocínio do Muriaé'],
            ['id_city' => 3702, 'id_state' => 13, 'name' => ' Paula Cândido'],
            ['id_city' => 3703, 'id_state' => 13, 'name' => ' Paula Lima'],
            ['id_city' => 3704, 'id_state' => 13, 'name' => ' Paulistas'],
            ['id_city' => 3705, 'id_state' => 13, 'name' => ' Pavão'],
            ['id_city' => 3706, 'id_state' => 13, 'name' => ' Pé do Morro'],
            ['id_city' => 3707, 'id_state' => 13, 'name' => ' Peçanha'],
            ['id_city' => 3708, 'id_state' => 13, 'name' => ' Pedra Azul'],
            ['id_city' => 3709, 'id_state' => 13, 'name' => ' Pedra Bonita'],
            ['id_city' => 3710, 'id_state' => 13, 'name' => ' Pedra Corrida'],
            ['id_city' => 3711, 'id_state' => 13, 'name' => ' Pedra do Anta'],
            ['id_city' => 3712, 'id_state' => 13, 'name' => ' Pedra do Indaiá'],
            ['id_city' => 3713, 'id_state' => 13, 'name' => ' Pedra do Sino'],
            ['id_city' => 3714, 'id_state' => 13, 'name' => ' Pedra Dourada'],
            ['id_city' => 3715, 'id_state' => 13, 'name' => ' Pedra Grande'],
            ['id_city' => 3716, 'id_state' => 13, 'name' => ' Pedra Menina'],
            ['id_city' => 3717, 'id_state' => 13, 'name' => ' Pedralva'],
            ['id_city' => 3718, 'id_state' => 13, 'name' => ' Pedras de Maria da Cruz'],
            ['id_city' => 3719, 'id_state' => 13, 'name' => ' Pedrinópolis'],
            ['id_city' => 3720, 'id_state' => 13, 'name' => ' Pedro Leopoldo'],
            ['id_city' => 3721, 'id_state' => 13, 'name' => ' Pedro Lessa'],
            ['id_city' => 3722, 'id_state' => 13, 'name' => ' Pedro Teixeira'],
            ['id_city' => 3723, 'id_state' => 13, 'name' => ' Pedro Versiani'],
            ['id_city' => 3724, 'id_state' => 13, 'name' => ' Penédia'],
            ['id_city' => 3725, 'id_state' => 13, 'name' => ' Penha de França'],
            ['id_city' => 3726, 'id_state' => 13, 'name' => ' Penha do Capim'],
            ['id_city' => 3727, 'id_state' => 13, 'name' => ' Penha do Cassiano'],
            ['id_city' => 3728, 'id_state' => 13, 'name' => ' Penha do Norte'],
            ['id_city' => 3729, 'id_state' => 13, 'name' => ' Penha Longa'],
            ['id_city' => 3730, 'id_state' => 13, 'name' => ' Pequeri'],
            ['id_city' => 3731, 'id_state' => 13, 'name' => ' Pequi'],
            ['id_city' => 3732, 'id_state' => 13, 'name' => ' Perdigão'],
            ['id_city' => 3733, 'id_state' => 13, 'name' => ' Perdilândia'],
            ['id_city' => 3734, 'id_state' => 13, 'name' => ' Perdizes'],
            ['id_city' => 3735, 'id_state' => 13, 'name' => ' Perdões'],
            ['id_city' => 3736, 'id_state' => 13, 'name' => ' Pereirinhas'],
            ['id_city' => 3737, 'id_state' => 13, 'name' => ' Periquito'],
            ['id_city' => 3738, 'id_state' => 13, 'name' => ' Perpétuo Socorro'],
            ['id_city' => 3739, 'id_state' => 13, 'name' => ' Pescador'],
            ['id_city' => 3740, 'id_state' => 13, 'name' => ' Petúnia'],
            ['id_city' => 3741, 'id_state' => 13, 'name' => ' Piacatuba'],
            ['id_city' => 3742, 'id_state' => 13, 'name' => ' Pião'],
            ['id_city' => 3743, 'id_state' => 13, 'name' => ' Piau'],
            ['id_city' => 3744, 'id_state' => 13, 'name' => ' Pic Sagarana'],
            ['id_city' => 3745, 'id_state' => 13, 'name' => ' Piedade de Caratinga'],
            ['id_city' => 3746, 'id_state' => 13, 'name' => ' Piedade de Ponte Nova'],
            ['id_city' => 3747, 'id_state' => 13, 'name' => ' Piedade do Paraopeba'],
            ['id_city' => 3748, 'id_state' => 13, 'name' => ' Piedade do Rio Grande'],
            ['id_city' => 3749, 'id_state' => 13, 'name' => ' Piedade dos Gerais'],
            ['id_city' => 3750, 'id_state' => 13, 'name' => ' Pilar'],
            ['id_city' => 3751, 'id_state' => 13, 'name' => ' Pimenta'],
            ['id_city' => 3752, 'id_state' => 13, 'name' => ' Pindaíbas'],
            ['id_city' => 3753, 'id_state' => 13, 'name' => ' Pingo-D Água'],
            ['id_city' => 3754, 'id_state' => 13, 'name' => ' Pinheirinhos'],
            ['id_city' => 3755, 'id_state' => 13, 'name' => ' Pinheiros Altos'],
            ['id_city' => 3756, 'id_state' => 13, 'name' => ' Pinhotiba'],
            ['id_city' => 3757, 'id_state' => 13, 'name' => ' Pintópolis'],
            ['id_city' => 3758, 'id_state' => 13, 'name' => ' Pintos Negreiros'],
            ['id_city' => 3759, 'id_state' => 13, 'name' => ' Piracaiba'],
            ['id_city' => 3760, 'id_state' => 13, 'name' => ' Piracema'],
            ['id_city' => 3761, 'id_state' => 13, 'name' => ' Pirajuba'],
            ['id_city' => 3762, 'id_state' => 13, 'name' => ' Piranga'],
            ['id_city' => 3763, 'id_state' => 13, 'name' => ' Piranguçu'],
            ['id_city' => 3764, 'id_state' => 13, 'name' => ' Piranguinho'],
            ['id_city' => 3765, 'id_state' => 13, 'name' => ' Piranguita'],
            ['id_city' => 3766, 'id_state' => 13, 'name' => ' Pirapanema'],
            ['id_city' => 3767, 'id_state' => 13, 'name' => ' Pirapetinga'],
            ['id_city' => 3768, 'id_state' => 13, 'name' => ' Pirapora'],
            ['id_city' => 3769, 'id_state' => 13, 'name' => ' Piraúba'],
            ['id_city' => 3770, 'id_state' => 13, 'name' => ' Alto Belo'],
            ['id_city' => 3771, 'id_state' => 13, 'name' => ' Piscamba'],
            ['id_city' => 3772, 'id_state' => 13, 'name' => ' Pitangui'],
            ['id_city' => 3773, 'id_state' => 13, 'name' => ' Pitarana'],
            ['id_city' => 3774, 'id_state' => 13, 'name' => ' Piumhi'],
            ['id_city' => 3775, 'id_state' => 13, 'name' => ' Planalto de Minas'],
            ['id_city' => 3776, 'id_state' => 13, 'name' => ' Planura'],
            ['id_city' => 3777, 'id_state' => 13, 'name' => ' Plautino Soares'],
            ['id_city' => 3778, 'id_state' => 13, 'name' => ' Poaia'],
            ['id_city' => 3779, 'id_state' => 13, 'name' => ' Poço Fundo'],
            ['id_city' => 3780, 'id_state' => 13, 'name' => ' Poções de Paineiras'],
            ['id_city' => 3781, 'id_state' => 13, 'name' => ' Poços de Caldas'],
            ['id_city' => 3782, 'id_state' => 13, 'name' => ' Pocrane'],
            ['id_city' => 3783, 'id_state' => 13, 'name' => ' Pompéu'],
            ['id_city' => 3784, 'id_state' => 13, 'name' => ' Poncianos'],
            ['id_city' => 3785, 'id_state' => 13, 'name' => ' Pontalete'],
            ['id_city' => 3786, 'id_state' => 13, 'name' => ' Ponte Alta'],
            ['id_city' => 3787, 'id_state' => 13, 'name' => ' Ponte Alta de Minas'],
            ['id_city' => 3788, 'id_state' => 13, 'name' => ' Ponte dos Ciganos'],
            ['id_city' => 3789, 'id_state' => 13, 'name' => ' Ponte Firme'],
            ['id_city' => 3790, 'id_state' => 13, 'name' => ' Ponte Nova'],
            ['id_city' => 3791, 'id_state' => 13, 'name' => ' Ponte Segura'],
            ['id_city' => 3792, 'id_state' => 13, 'name' => ' Pontevila'],
            ['id_city' => 3793, 'id_state' => 13, 'name' => ' Ponto Chique'],
            ['id_city' => 3794, 'id_state' => 13, 'name' => ' Ponto Chique do Martelo'],
            ['id_city' => 3795, 'id_state' => 13, 'name' => ' Ponto do Marambaia'],
            ['id_city' => 3796, 'id_state' => 13, 'name' => ' Ponto dos Volantes'],
            ['id_city' => 3797, 'id_state' => 13, 'name' => ' Porteirinha'],
            ['id_city' => 3798, 'id_state' => 13, 'name' => ' Porto Agrário'],
            ['id_city' => 3799, 'id_state' => 13, 'name' => ' Porto das Flores'],
            ['id_city' => 3800, 'id_state' => 13, 'name' => ' Porto dos Mendes'],
            ['id_city' => 3801, 'id_state' => 13, 'name' => ' Porto Firme'],
            ['id_city' => 3802, 'id_state' => 13, 'name' => ' Poté'],
            ['id_city' => 3803, 'id_state' => 13, 'name' => ' Pouso Alegre'],
            ['id_city' => 3804, 'id_state' => 13, 'name' => ' Pouso Alto'],
            ['id_city' => 3805, 'id_state' => 13, 'name' => ' Prados'],
            ['id_city' => 3806, 'id_state' => 13, 'name' => ' Prata'],
            ['id_city' => 3807, 'id_state' => 13, 'name' => ' Pratápolis'],
            ['id_city' => 3808, 'id_state' => 13, 'name' => ' Pratinha'],
            ['id_city' => 3809, 'id_state' => 13, 'name' => ' Presidente Bernardes'],
            ['id_city' => 3810, 'id_state' => 13, 'name' => ' Presidente Juscelino'],
            ['id_city' => 3811, 'id_state' => 13, 'name' => ' Presidente Kubitschek'],
            ['id_city' => 3812, 'id_state' => 13, 'name' => ' Presidente Olegário'],
            ['id_city' => 3813, 'id_state' => 13, 'name' => ' Presidente Pena'],
            ['id_city' => 3814, 'id_state' => 13, 'name' => ' Professor Sperber'],
            ['id_city' => 3815, 'id_state' => 13, 'name' => ' Providência'],
            ['id_city' => 3816, 'id_state' => 13, 'name' => ' Prudente de Morais'],
            ['id_city' => 3817, 'id_state' => 13, 'name' => ' Quartel de São João'],
            ['id_city' => 3818, 'id_state' => 13, 'name' => ' Quartel do Sacramento'],
            ['id_city' => 3819, 'id_state' => 13, 'name' => ' Quartel Geral'],
            ['id_city' => 3820, 'id_state' => 13, 'name' => ' Quatituba'],
            ['id_city' => 3821, 'id_state' => 13, 'name' => ' Queixada'],
            ['id_city' => 3822, 'id_state' => 13, 'name' => ' Queluzito'],
            ['id_city' => 3823, 'id_state' => 13, 'name' => ' Quem-Quem'],
            ['id_city' => 3824, 'id_state' => 13, 'name' => ' Quilombo'],
            ['id_city' => 3825, 'id_state' => 13, 'name' => ' Quintinos'],
            ['id_city' => 3826, 'id_state' => 13, 'name' => ' Raposos'],
            ['id_city' => 3827, 'id_state' => 13, 'name' => ' Raul Soares'],
            ['id_city' => 3828, 'id_state' => 13, 'name' => ' Ravena'],
            ['id_city' => 3829, 'id_state' => 13, 'name' => ' Realeza'],
            ['id_city' => 3830, 'id_state' => 13, 'name' => ' Recreio'],
            ['id_city' => 3831, 'id_state' => 13, 'name' => ' Reduto'],
            ['id_city' => 3832, 'id_state' => 13, 'name' => ' Resende Costa'],
            ['id_city' => 3833, 'id_state' => 13, 'name' => ' Resplendor'],
            ['id_city' => 3834, 'id_state' => 13, 'name' => ' Ressaquinha'],
            ['id_city' => 3835, 'id_state' => 13, 'name' => ' Riachinho'],
            ['id_city' => 3836, 'id_state' => 13, 'name' => ' Riacho da Cruz'],
            ['id_city' => 3837, 'id_state' => 13, 'name' => ' Riacho dos Machados'],
            ['id_city' => 3838, 'id_state' => 13, 'name' => ' Ribeirão das Neves'],
            ['id_city' => 3839, 'id_state' => 13, 'name' => ' Ribeirão de São Domingos'],
            ['id_city' => 3840, 'id_state' => 13, 'name' => ' Ribeirão Vermelho'],
            ['id_city' => 3841, 'id_state' => 13, 'name' => ' Ribeiro Junqueira'],
            ['id_city' => 3842, 'id_state' => 13, 'name' => ' Ribeiros'],
            ['id_city' => 3843, 'id_state' => 13, 'name' => ' Rio Acima'],
            ['id_city' => 3844, 'id_state' => 13, 'name' => ' Rio Casca'],
            ['id_city' => 3845, 'id_state' => 13, 'name' => ' Rio das Mortes'],
            ['id_city' => 3846, 'id_state' => 13, 'name' => ' Rio do Prado'],
            ['id_city' => 3847, 'id_state' => 13, 'name' => ' Rio Doce'],
            ['id_city' => 3848, 'id_state' => 13, 'name' => ' Rio Espera'],
            ['id_city' => 3849, 'id_state' => 13, 'name' => ' Rio Manso'],
            ['id_city' => 3850, 'id_state' => 13, 'name' => ' Rio Melo'],
            ['id_city' => 3851, 'id_state' => 13, 'name' => ' Rio Novo'],
            ['id_city' => 3852, 'id_state' => 13, 'name' => ' Rio Paranaíba'],
            ['id_city' => 3853, 'id_state' => 13, 'name' => ' Rio Pardo de Minas'],
            ['id_city' => 3854, 'id_state' => 13, 'name' => ' Rio Piracicaba'],
            ['id_city' => 3855, 'id_state' => 13, 'name' => ' Rio Pomba'],
            ['id_city' => 3856, 'id_state' => 13, 'name' => ' Rio Pretinho'],
            ['id_city' => 3857, 'id_state' => 13, 'name' => ' Rio Preto'],
            ['id_city' => 3858, 'id_state' => 13, 'name' => ' Rio Vermelho'],
            ['id_city' => 3859, 'id_state' => 13, 'name' => ' Ritápolis'],
            ['id_city' => 3860, 'id_state' => 13, 'name' => ' Roça Grande'],
            ['id_city' => 3861, 'id_state' => 13, 'name' => ' Roças Novas'],
            ['id_city' => 3862, 'id_state' => 13, 'name' => ' Rochedo de Minas'],
            ['id_city' => 3863, 'id_state' => 13, 'name' => ' Rodeador'],
            ['id_city' => 3864, 'id_state' => 13, 'name' => ' Rodeiro'],
            ['id_city' => 3865, 'id_state' => 13, 'name' => ' Rodrigo Silva'],
            ['id_city' => 3866, 'id_state' => 13, 'name' => ' Romaria'],
            ['id_city' => 3867, 'id_state' => 13, 'name' => ' Rosário da Limeira'],
            ['id_city' => 3868, 'id_state' => 13, 'name' => ' Rosário de Minas'],
            ['id_city' => 3869, 'id_state' => 13, 'name' => ' Rosário do Pontal'],
            ['id_city' => 3870, 'id_state' => 13, 'name' => ' Roseiral'],
            ['id_city' => 3871, 'id_state' => 13, 'name' => ' Rubelita'],
            ['id_city' => 3872, 'id_state' => 13, 'name' => ' Rubim'],
            ['id_city' => 3873, 'id_state' => 13, 'name' => ' Sabará'],
            ['id_city' => 3874, 'id_state' => 13, 'name' => ' Sabinópolis'],
            ['id_city' => 3875, 'id_state' => 13, 'name' => ' Sacramento'],
            ['id_city' => 3876, 'id_state' => 13, 'name' => ' Salinas'],
            ['id_city' => 3877, 'id_state' => 13, 'name' => ' Salitre de Minas'],
            ['id_city' => 3878, 'id_state' => 13, 'name' => ' Salto da Divisa'],
            ['id_city' => 3879, 'id_state' => 13, 'name' => ' Sanatório Santa Fé'],
            ['id_city' => 3880, 'id_state' => 13, 'name' => ' Santa Bárbara'],
            ['id_city' => 3881, 'id_state' => 13, 'name' => ' Santa Bárbara do Leste'],
            ['id_city' => 3882, 'id_state' => 13, 'name' => ' Santa Bárbara do Monte Verde'],
            ['id_city' => 3883, 'id_state' => 13, 'name' => ' Santa Bárbara do Tugúrio'],
            ['id_city' => 3884, 'id_state' => 13, 'name' => ' Santa Cruz da Aparecida'],
            ['id_city' => 3885, 'id_state' => 13, 'name' => ' Santa Cruz de Botumirim'],
            ['id_city' => 3886, 'id_state' => 13, 'name' => ' Santa Cruz de Minas'],
            ['id_city' => 3887, 'id_state' => 13, 'name' => ' Santa Cruz de Salinas'],
            ['id_city' => 3888, 'id_state' => 13, 'name' => ' Santa Cruz do Escalvado'],
            ['id_city' => 3889, 'id_state' => 13, 'name' => ' Santa Cruz do Prata'],
            ['id_city' => 3890, 'id_state' => 13, 'name' => ' Santa da Pedra'],
            ['id_city' => 3891, 'id_state' => 13, 'name' => ' Santa Efigênia'],
            ['id_city' => 3892, 'id_state' => 13, 'name' => ' Santa Efigênia de Minas'],
            ['id_city' => 3893, 'id_state' => 13, 'name' => ' Santa Fé de Minas'],
            ['id_city' => 3894, 'id_state' => 13, 'name' => ' Santa Filomena'],
            ['id_city' => 3895, 'id_state' => 13, 'name' => ' Santa Helena de Minas'],
            ['id_city' => 3896, 'id_state' => 13, 'name' => ' Santa Juliana'],
            ['id_city' => 3897, 'id_state' => 13, 'name' => ' Santa Luzia'],
            ['id_city' => 3898, 'id_state' => 13, 'name' => ' Santa Luzia da Serra'],
            ['id_city' => 3899, 'id_state' => 13, 'name' => ' Santa Margarida'],
            ['id_city' => 3900, 'id_state' => 13, 'name' => ' Santa Maria de Itabira'],
            ['id_city' => 3901, 'id_state' => 13, 'name' => ' Santa Maria do Salto'],
            ['id_city' => 3902, 'id_state' => 13, 'name' => ' Santa Maria do Suaçuí'],
            ['id_city' => 3903, 'id_state' => 13, 'name' => ' Santa Rita da Estrela'],
            ['id_city' => 3904, 'id_state' => 13, 'name' => ' Santa Rita de Caldas'],
            ['id_city' => 3905, 'id_state' => 13, 'name' => ' Santa Rita de Jacutinga'],
            ['id_city' => 3906, 'id_state' => 13, 'name' => ' Santa Rita de Minas'],
            ['id_city' => 3907, 'id_state' => 13, 'name' => ' Santa Rita de Ouro Preto'],
            ['id_city' => 3908, 'id_state' => 13, 'name' => ' Santa Rita do Cedro'],
            ['id_city' => 3909, 'id_state' => 13, 'name' => ' Santa Rita do Ibitipoca'],
            ['id_city' => 3910, 'id_state' => 13, 'name' => ' Santa Rita do Itueto'],
            ['id_city' => 3911, 'id_state' => 13, 'name' => ' Santa Rita do Rio do Peixe'],
            ['id_city' => 3912, 'id_state' => 13, 'name' => ' Santa Rita do Sapucaí'],
            ['id_city' => 3913, 'id_state' => 13, 'name' => ' Santa Rita Durão'],
            ['id_city' => 3914, 'id_state' => 13, 'name' => ' Santa Rosa da Serra'],
            ['id_city' => 3915, 'id_state' => 13, 'name' => ' Santa Rosa de Lima'],
            ['id_city' => 3916, 'id_state' => 13, 'name' => ' Santa Rosa dos Dourados'],
            ['id_city' => 3917, 'id_state' => 13, 'name' => ' Santa Teresa do Bonito'],
            ['id_city' => 3918, 'id_state' => 13, 'name' => ' Santa Terezinha de Minas'],
            ['id_city' => 3919, 'id_state' => 13, 'name' => ' Santa Vitória'],
            ['id_city' => 3920, 'id_state' => 13, 'name' => ' Santana da Vargem'],
            ['id_city' => 3921, 'id_state' => 13, 'name' => ' Santana de Caldas'],
            ['id_city' => 3922, 'id_state' => 13, 'name' => ' Santana de Cataguases'],
            ['id_city' => 3923, 'id_state' => 13, 'name' => ' Santana de Patos'],
            ['id_city' => 3924, 'id_state' => 13, 'name' => ' Santana de Pirapama'],
            ['id_city' => 3925, 'id_state' => 13, 'name' => ' Santana do Alfié'],
            ['id_city' => 3926, 'id_state' => 13, 'name' => ' Santana do Araçuaí'],
            ['id_city' => 3927, 'id_state' => 13, 'name' => ' Santana do Campestre'],
            ['id_city' => 3928, 'id_state' => 13, 'name' => ' Santana do Capivari'],
            ['id_city' => 3929, 'id_state' => 13, 'name' => ' Santana do Deserto'],
            ['id_city' => 3930, 'id_state' => 13, 'name' => ' Santana do Garambéu'],
            ['id_city' => 3931, 'id_state' => 13, 'name' => ' Santana do Jacaré'],
            ['id_city' => 3932, 'id_state' => 13, 'name' => ' Santana do Manhuaçu'],
            ['id_city' => 3933, 'id_state' => 13, 'name' => ' Santana do Paraíso'],
            ['id_city' => 3934, 'id_state' => 13, 'name' => ' Santana do Paraopeba'],
            ['id_city' => 3935, 'id_state' => 13, 'name' => ' Santana do Riacho'],
            ['id_city' => 3936, 'id_state' => 13, 'name' => ' Santana do Tabuleiro'],
            ['id_city' => 3937, 'id_state' => 13, 'name' => ' Santana dos Montes'],
            ['id_city' => 3938, 'id_state' => 13, 'name' => ' Santo Antônio da Boa Vista'],
            ['id_city' => 3939, 'id_state' => 13, 'name' => ' Santo Antônio da Fortaleza'],
            ['id_city' => 3940, 'id_state' => 13, 'name' => ' Santo Antônio da Vargem Alegre'],
            ['id_city' => 3941, 'id_state' => 13, 'name' => ' Santo Antônio do Amparo'],
            ['id_city' => 3942, 'id_state' => 13, 'name' => ' Santo Antônio do Aventureiro'],
            ['id_city' => 3943, 'id_state' => 13, 'name' => ' Santo Antônio do Boqueirão'],
            ['id_city' => 3944, 'id_state' => 13, 'name' => ' Santo Antônio do Cruzeiro'],
            ['id_city' => 3945, 'id_state' => 13, 'name' => ' Santo Antônio do Glória'],
            ['id_city' => 3946, 'id_state' => 13, 'name' => ' Santo Antônio do Grama'],
            ['id_city' => 3947, 'id_state' => 13, 'name' => ' Santo Antônio do Itambé'],
            ['id_city' => 3948, 'id_state' => 13, 'name' => ' Santo Antônio do Jacinto'],
            ['id_city' => 3949, 'id_state' => 13, 'name' => ' Santo Antônio do Leite'],
            ['id_city' => 3950, 'id_state' => 13, 'name' => ' Santo Antônio do Manhuaçu'],
            ['id_city' => 3951, 'id_state' => 13, 'name' => ' Santo Antônio do Monte'],
            ['id_city' => 3952, 'id_state' => 13, 'name' => ' Santo Antônio do Mucuri'],
            ['id_city' => 3953, 'id_state' => 13, 'name' => ' Santo Antônio do Norte'],
            ['id_city' => 3954, 'id_state' => 13, 'name' => ' Santo Antônio do Pirapetinga'],
            ['id_city' => 3955, 'id_state' => 13, 'name' => ' Santo Antônio do Retiro'],
            ['id_city' => 3956, 'id_state' => 13, 'name' => ' Santo Antônio do Rio Abaixo'],
            ['id_city' => 3957, 'id_state' => 13, 'name' => ' Santo Antônio dos Araújos'],
            ['id_city' => 3958, 'id_state' => 13, 'name' => ' Santo Antônio dos Campos'],
            ['id_city' => 3959, 'id_state' => 13, 'name' => ' Santo Hilário'],
            ['id_city' => 3960, 'id_state' => 13, 'name' => ' Santo Hipólito'],
            ['id_city' => 3961, 'id_state' => 13, 'name' => ' Santos Dumont'],
            ['id_city' => 3962, 'id_state' => 13, 'name' => ' São Bartolomeu'],
            ['id_city' => 3963, 'id_state' => 13, 'name' => ' São Benedito'],
            ['id_city' => 3964, 'id_state' => 13, 'name' => ' São Bento Abade'],
            ['id_city' => 3965, 'id_state' => 13, 'name' => ' São Bento de Caldas'],
            ['id_city' => 3966, 'id_state' => 13, 'name' => ' São Brás do Suaçuí'],
            ['id_city' => 3967, 'id_state' => 13, 'name' => ' São Braz'],
            ['id_city' => 3968, 'id_state' => 13, 'name' => ' São Cândido'],
            ['id_city' => 3969, 'id_state' => 13, 'name' => ' São Domingos'],
            ['id_city' => 3970, 'id_state' => 13, 'name' => ' São Domingos da Bocaina'],
            ['id_city' => 3971, 'id_state' => 13, 'name' => ' São Domingos das Dores'],
            ['id_city' => 3972, 'id_state' => 13, 'name' => ' São Domingos do Prata'],
            ['id_city' => 3973, 'id_state' => 13, 'name' => ' São Félix de Minas'],
            ['id_city' => 3974, 'id_state' => 13, 'name' => ' São Francisco'],
            ['id_city' => 3975, 'id_state' => 13, 'name' => ' São Francisco de Paula'],
            ['id_city' => 3976, 'id_state' => 13, 'name' => ' São Francisco de Sales'],
            ['id_city' => 3977, 'id_state' => 13, 'name' => ' São Francisco do Glória'],
            ['id_city' => 3978, 'id_state' => 13, 'name' => ' São Francisco do Humaitá'],
            ['id_city' => 3979, 'id_state' => 13, 'name' => ' São Geraldo'],
            ['id_city' => 3980, 'id_state' => 13, 'name' => ' São Geraldo'],
            ['id_city' => 3981, 'id_state' => 13, 'name' => ' São Geraldo da Piedade'],
            ['id_city' => 3982, 'id_state' => 13, 'name' => ' São Geraldo de Tumiritinga'],
            ['id_city' => 3983, 'id_state' => 13, 'name' => ' São Geraldo do Baguari'],
            ['id_city' => 3984, 'id_state' => 13, 'name' => ' São Geraldo do Baixio'],
            ['id_city' => 3985, 'id_state' => 13, 'name' => ' São Gonçalo de Botelhos'],
            ['id_city' => 3986, 'id_state' => 13, 'name' => ' São Gonçalo do Abaeté'],
            ['id_city' => 3987, 'id_state' => 13, 'name' => ' São Gonçalo do Monte'],
            ['id_city' => 3988, 'id_state' => 13, 'name' => ' São Gonçalo do Pará'],
            ['id_city' => 3989, 'id_state' => 13, 'name' => ' São Gonçalo do Rio Abaixo'],
            ['id_city' => 3990, 'id_state' => 13, 'name' => ' São Gonçalo do Rio das Pedras'],
            ['id_city' => 3991, 'id_state' => 13, 'name' => ' São Gonçalo do Rio Preto'],
            ['id_city' => 3992, 'id_state' => 13, 'name' => ' São Gonçalo do Sapucaí'],
            ['id_city' => 3993, 'id_state' => 13, 'name' => ' São Gotardo'],
            ['id_city' => 3994, 'id_state' => 13, 'name' => ' São Jerônimo dos Poções'],
            ['id_city' => 3995, 'id_state' => 13, 'name' => ' São João Batista do Glória'],
            ['id_city' => 3996, 'id_state' => 13, 'name' => ' São João da Chapada'],
            ['id_city' => 3997, 'id_state' => 13, 'name' => ' São João da Lagoa'],
            ['id_city' => 3998, 'id_state' => 13, 'name' => ' São João da Mata'],
            ['id_city' => 3999, 'id_state' => 13, 'name' => ' São João da Ponte'],
            ['id_city' => 4000, 'id_state' => 13, 'name' => ' São João da Sapucaia'],
            ['id_city' => 4001, 'id_state' => 13, 'name' => ' São João da Serra'],
            ['id_city' => 4002, 'id_state' => 13, 'name' => ' São João da Serra Negra'],
            ['id_city' => 4003, 'id_state' => 13, 'name' => ' São João da Vereda'],
            ['id_city' => 4004, 'id_state' => 13, 'name' => ' São João das Missões'],
            ['id_city' => 4005, 'id_state' => 13, 'name' => ' São João Del Rei'],
            ['id_city' => 4006, 'id_state' => 13, 'name' => ' São João do Bonito'],
            ['id_city' => 4007, 'id_state' => 13, 'name' => ' São João do Jacutinga'],
            ['id_city' => 4008, 'id_state' => 13, 'name' => ' São João do Manhuaçu'],
            ['id_city' => 4009, 'id_state' => 13, 'name' => ' São João do Manteninha'],
            ['id_city' => 4010, 'id_state' => 13, 'name' => ' São João do Oriente'],
            ['id_city' => 4011, 'id_state' => 13, 'name' => ' São João do Pacuí'],
            ['id_city' => 4012, 'id_state' => 13, 'name' => ' São João do Paraíso'],
            ['id_city' => 4013, 'id_state' => 13, 'name' => ' São João Evangelista'],
            ['id_city' => 4014, 'id_state' => 13, 'name' => ' São João Nepomuceno'],
            ['id_city' => 4015, 'id_state' => 13, 'name' => ' São Joaquim'],
            ['id_city' => 4016, 'id_state' => 13, 'name' => ' São Joaquim de Bicas'],
            ['id_city' => 4017, 'id_state' => 13, 'name' => ' São José da Barra'],
            ['id_city' => 4018, 'id_state' => 13, 'name' => ' São José da Bela Vista'],
            ['id_city' => 4019, 'id_state' => 13, 'name' => ' São José da Lapa'],
            ['id_city' => 4020, 'id_state' => 13, 'name' => ' São José da Pedra Menina'],
            ['id_city' => 4021, 'id_state' => 13, 'name' => ' São José da Safira'],
            ['id_city' => 4022, 'id_state' => 13, 'name' => ' São José da Varginha'],
            ['id_city' => 4023, 'id_state' => 13, 'name' => ' Goiabal'],
            ['id_city' => 4024, 'id_state' => 13, 'name' => ' São José do Acácio'],
            ['id_city' => 4025, 'id_state' => 13, 'name' => ' São José do Alegre'],
            ['id_city' => 4026, 'id_state' => 13, 'name' => ' São José do Barreiro'],
            ['id_city' => 4027, 'id_state' => 13, 'name' => ' São José do Batatal'],
            ['id_city' => 4028, 'id_state' => 13, 'name' => ' São José do Buriti'],
            ['id_city' => 4029, 'id_state' => 13, 'name' => ' São José do Divino'],
            ['id_city' => 4030, 'id_state' => 13, 'name' => ' São José do Goiabal'],
            ['id_city' => 4031, 'id_state' => 13, 'name' => ' São José do Itueto'],
            ['id_city' => 4032, 'id_state' => 13, 'name' => ' São José do Jacuri'],
            ['id_city' => 4033, 'id_state' => 13, 'name' => ' São José do Mantimento'],
            ['id_city' => 4034, 'id_state' => 13, 'name' => ' São José do Mato Dentro'],
            ['id_city' => 4035, 'id_state' => 13, 'name' => ' São José do Pântano'],
            ['id_city' => 4036, 'id_state' => 13, 'name' => ' São José do Paraopeba'],
            ['id_city' => 4037, 'id_state' => 13, 'name' => ' São José dos Lopes'],
            ['id_city' => 4038, 'id_state' => 13, 'name' => ' São José dos Salgados'],
            ['id_city' => 4039, 'id_state' => 13, 'name' => ' São Lourenço'],
            ['id_city' => 4040, 'id_state' => 13, 'name' => ' São Manoel do Guaiaçu'],
            ['id_city' => 4041, 'id_state' => 13, 'name' => ' São Mateus de Minas'],
            ['id_city' => 4042, 'id_state' => 13, 'name' => ' São Miguel do Anta'],
            ['id_city' => 4043, 'id_state' => 13, 'name' => ' São Pedro da Garça'],
            ['id_city' => 4044, 'id_state' => 13, 'name' => ' São Pedro da União'],
            ['id_city' => 4045, 'id_state' => 13, 'name' => ' São Pedro das Tabocas'],
            ['id_city' => 4046, 'id_state' => 13, 'name' => ' São Pedro de Caldas'],
            ['id_city' => 4047, 'id_state' => 13, 'name' => ' São Pedro do Avaí'],
            ['id_city' => 4048, 'id_state' => 13, 'name' => ' São Pedro do Glória'],
            ['id_city' => 4049, 'id_state' => 13, 'name' => ' São Pedro do Jequitinhonha'],
            ['id_city' => 4050, 'id_state' => 13, 'name' => ' São Pedro do Suaçuí'],
            ['id_city' => 4051, 'id_state' => 13, 'name' => ' São Pedro dos Ferros'],
            ['id_city' => 4052, 'id_state' => 13, 'name' => ' São Roberto'],
            ['id_city' => 4053, 'id_state' => 13, 'name' => ' São Romão'],
            ['id_city' => 4054, 'id_state' => 13, 'name' => ' São Roque de Minas'],
            ['id_city' => 4055, 'id_state' => 13, 'name' => ' São Sebastião da Barra'],
            ['id_city' => 4056, 'id_state' => 13, 'name' => ' São Sebastião da Bela Vista'],
            ['id_city' => 4057, 'id_state' => 13, 'name' => ' São Sebastião da Vala'],
            ['id_city' => 4058, 'id_state' => 13, 'name' => ' São Sebastião da Vargem Alegre'],
            ['id_city' => 4059, 'id_state' => 13, 'name' => ' São Sebastião da Vitória'],
            ['id_city' => 4060, 'id_state' => 13, 'name' => ' São Sebastião de Braúnas'],
            ['id_city' => 4061, 'id_state' => 13, 'name' => ' São Sebastião do Anta'],
            ['id_city' => 4062, 'id_state' => 13, 'name' => ' São Sebastião do Baixio'],
            ['id_city' => 4063, 'id_state' => 13, 'name' => ' São Sebastião do Barreado'],
            ['id_city' => 4064, 'id_state' => 13, 'name' => ' São Sebastião do Barreiro'],
            ['id_city' => 4065, 'id_state' => 13, 'name' => ' São Sebastião do Bonsucesso'],
            ['id_city' => 4066, 'id_state' => 13, 'name' => ' São Sebastião do Bugre'],
            ['id_city' => 4067, 'id_state' => 13, 'name' => ' São Sebastião do Gil'],
            ['id_city' => 4068, 'id_state' => 13, 'name' => ' São Sebastião do Maranhão'],
            ['id_city' => 4069, 'id_state' => 13, 'name' => ' São Sebastião do Óculo'],
            ['id_city' => 4070, 'id_state' => 13, 'name' => ' São Sebastião do Oeste'],
            ['id_city' => 4071, 'id_state' => 13, 'name' => ' São Sebastião do Paraíso'],
            ['id_city' => 4072, 'id_state' => 13, 'name' => ' São Sebastião do Pontal'],
            ['id_city' => 4073, 'id_state' => 13, 'name' => ' São Sebastião do Rio Preto'],
            ['id_city' => 4074, 'id_state' => 13, 'name' => ' São Sebastião do Rio Verde'],
            ['id_city' => 4075, 'id_state' => 13, 'name' => ' São Sebastião do Sacramento'],
            ['id_city' => 4076, 'id_state' => 13, 'name' => ' São Sebastião do Soberbo'],
            ['id_city' => 4077, 'id_state' => 13, 'name' => ' São Sebastião dos Poções'],
            ['id_city' => 4078, 'id_state' => 13, 'name' => ' São Sebastião dos Robertos'],
            ['id_city' => 4079, 'id_state' => 13, 'name' => ' São Sebastião dos Torres'],
            ['id_city' => 4080, 'id_state' => 13, 'name' => ' São Tiago'],
            ['id_city' => 4081, 'id_state' => 13, 'name' => ' São Tomás de Aquino'],
            ['id_city' => 4082, 'id_state' => 13, 'name' => ' São Thomé das Letras'],
            ['id_city' => 4083, 'id_state' => 13, 'name' => ' São Vicente'],
            ['id_city' => 4084, 'id_state' => 13, 'name' => ' São Vicente da Estrela'],
            ['id_city' => 4085, 'id_state' => 13, 'name' => ' São Vicente de Minas'],
            ['id_city' => 4086, 'id_state' => 13, 'name' => ' São Vicente do Grama'],
            ['id_city' => 4087, 'id_state' => 13, 'name' => ' São Vicente do Rio Doce'],
            ['id_city' => 4088, 'id_state' => 13, 'name' => ' São Vítor'],
            ['id_city' => 4089, 'id_state' => 13, 'name' => ' Sapucaí'],
            ['id_city' => 4090, 'id_state' => 13, 'name' => ' Sapucaí-Mirim'],
            ['id_city' => 4091, 'id_state' => 13, 'name' => ' Sapucaia'],
            ['id_city' => 4092, 'id_state' => 13, 'name' => ' Sapucaia de Guanhães'],
            ['id_city' => 4093, 'id_state' => 13, 'name' => ' Sapucaia do Norte'],
            ['id_city' => 4094, 'id_state' => 13, 'name' => ' Sarandira'],
            ['id_city' => 4095, 'id_state' => 13, 'name' => ' Sardoá'],
            ['id_city' => 4096, 'id_state' => 13, 'name' => ' Sarzedo'],
            ['id_city' => 4097, 'id_state' => 13, 'name' => ' Saudade'],
            ['id_city' => 4098, 'id_state' => 13, 'name' => ' Sem Peixe'],
            ['id_city' => 4099, 'id_state' => 13, 'name' => ' Senador Amaral'],
            ['id_city' => 4100, 'id_state' => 13, 'name' => ' Senador Cortes'],
            ['id_city' => 4101, 'id_state' => 13, 'name' => ' Senador Firmino'],
            ['id_city' => 4102, 'id_state' => 13, 'name' => ' Senador José Bento'],
            ['id_city' => 4103, 'id_state' => 13, 'name' => ' Senador Melo Viana'],
            ['id_city' => 4104, 'id_state' => 13, 'name' => ' Senador Modestino Gonçalves'],
            ['id_city' => 4105, 'id_state' => 13, 'name' => ' Senador Mourão'],
            ['id_city' => 4106, 'id_state' => 13, 'name' => ' Senhora da Glória'],
            ['id_city' => 4107, 'id_state' => 13, 'name' => ' Senhora da Penha'],
            ['id_city' => 4108, 'id_state' => 13, 'name' => ' Senhora das Dores'],
            ['id_city' => 4109, 'id_state' => 13, 'name' => ' Senhora de Oliveira'],
            ['id_city' => 4110, 'id_state' => 13, 'name' => ' Senhora do Carmo'],
            ['id_city' => 4111, 'id_state' => 13, 'name' => ' Senhora do Porto'],
            ['id_city' => 4112, 'id_state' => 13, 'name' => ' Senhora dos Remédios'],
            ['id_city' => 4113, 'id_state' => 13, 'name' => ' Sereno'],
            ['id_city' => 4114, 'id_state' => 13, 'name' => ' Sericita'],
            ['id_city' => 4115, 'id_state' => 13, 'name' => ' Seritinga'],
            ['id_city' => 4116, 'id_state' => 13, 'name' => ' Serra Azul'],
            ['id_city' => 4117, 'id_state' => 13, 'name' => ' Serra Azul de Minas'],
            ['id_city' => 4118, 'id_state' => 13, 'name' => ' Serra Bonita'],
            ['id_city' => 4119, 'id_state' => 13, 'name' => ' Serra da Canastra'],
            ['id_city' => 4120, 'id_state' => 13, 'name' => ' Serra da Saudade'],
            ['id_city' => 4121, 'id_state' => 13, 'name' => ' Serra das Araras'],
            ['id_city' => 4122, 'id_state' => 13, 'name' => ' Serra do Camapuã'],
            ['id_city' => 4123, 'id_state' => 13, 'name' => ' Serra do Salitre'],
            ['id_city' => 4124, 'id_state' => 13, 'name' => ' Serra dos Aimorés'],
            ['id_city' => 4125, 'id_state' => 13, 'name' => ' Serra dos Lemes'],
            ['id_city' => 4126, 'id_state' => 13, 'name' => ' Serra Nova'],
            ['id_city' => 4127, 'id_state' => 13, 'name' => ' Serrania'],
            ['id_city' => 4128, 'id_state' => 13, 'name' => ' Serranópolis de Minas'],
            ['id_city' => 4129, 'id_state' => 13, 'name' => ' Serranos'],
            ['id_city' => 4130, 'id_state' => 13, 'name' => ' Serro'],
            ['id_city' => 4131, 'id_state' => 13, 'name' => ' Sertãozinho'],
            ['id_city' => 4132, 'id_state' => 13, 'name' => ' Sete Cachoeiras'],
            ['id_city' => 4133, 'id_state' => 13, 'name' => ' Sete Lagoas'],
            ['id_city' => 4134, 'id_state' => 13, 'name' => ' Setubinha'],
            ['id_city' => 4135, 'id_state' => 13, 'name' => ' Silva Campos'],
            ['id_city' => 4136, 'id_state' => 13, 'name' => ' Silva Xavier'],
            ['id_city' => 4137, 'id_state' => 13, 'name' => ' Silvano'],
            ['id_city' => 4138, 'id_state' => 13, 'name' => ' Silveira Carvalho'],
            ['id_city' => 4139, 'id_state' => 13, 'name' => ' Silveirânia']
        ]);
    }
    
}