<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities11 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 6711, 'id_state' => 16, 'name' => ' São Mateus do Sul'],
                ['id_city' => 6712, 'id_state' => 16, 'name' => ' São Miguel'],
                ['id_city' => 6713, 'id_state' => 16, 'name' => ' São Miguel do Cambui'],
                ['id_city' => 6714, 'id_state' => 16, 'name' => ' São Miguel do Iguaçu'],
                ['id_city' => 6715, 'id_state' => 16, 'name' => ' São Paulo'],
                ['id_city' => 6716, 'id_state' => 16, 'name' => ' São Pedro'],
                ['id_city' => 6717, 'id_state' => 16, 'name' => ' São Pedro do Florido'],
                ['id_city' => 6718, 'id_state' => 16, 'name' => ' São Pedro do Iguaçu'],
                ['id_city' => 6719, 'id_state' => 16, 'name' => ' São Pedro do Ivaí'],
                ['id_city' => 6720, 'id_state' => 16, 'name' => ' São Pedro do Paraná'],
                ['id_city' => 6721, 'id_state' => 16, 'name' => ' São Pedro Lopei'],
                ['id_city' => 6722, 'id_state' => 16, 'name' => ' São Pio X'],
                ['id_city' => 6723, 'id_state' => 16, 'name' => ' São Roque'],
                ['id_city' => 6724, 'id_state' => 16, 'name' => ' São Roque do Pinhal'],
                ['id_city' => 6725, 'id_state' => 16, 'name' => ' São Salvador'],
                ['id_city' => 6726, 'id_state' => 16, 'name' => ' São Sebastião'],
                ['id_city' => 6727, 'id_state' => 16, 'name' => ' São Sebastião da Amoreira'],
                ['id_city' => 6728, 'id_state' => 16, 'name' => ' São Silvestre'],
                ['id_city' => 6729, 'id_state' => 16, 'name' => ' São Tomé'],
                ['id_city' => 6730, 'id_state' => 16, 'name' => ' São Valentim'],
                ['id_city' => 6731, 'id_state' => 16, 'name' => ' São Vicente'],
                ['id_city' => 6732, 'id_state' => 16, 'name' => ' Sapé'],
                ['id_city' => 6733, 'id_state' => 16, 'name' => ' Sapopema'],
                ['id_city' => 6734, 'id_state' => 16, 'name' => ' Sarandi'],
                ['id_city' => 6735, 'id_state' => 16, 'name' => ' Saudade do Iguaçu'],
                ['id_city' => 6736, 'id_state' => 16, 'name' => ' Sede Alvorada'],
                ['id_city' => 6737, 'id_state' => 16, 'name' => ' Sede Chaparral'],
                ['id_city' => 6738, 'id_state' => 16, 'name' => ' Sede Nova Sant Ana'],
                ['id_city' => 6739, 'id_state' => 16, 'name' => ' Sede Progresso'],
                ['id_city' => 6740, 'id_state' => 16, 'name' => ' Selva'],
                ['id_city' => 6741, 'id_state' => 16, 'name' => ' Sengés'],
                ['id_city' => 6742, 'id_state' => 16, 'name' => ' Senhor Bom Jesus dos Gramados'],
                ['id_city' => 6743, 'id_state' => 16, 'name' => ' Serra dos Dourados'],
                ['id_city' => 6744, 'id_state' => 16, 'name' => ' Serra Negra'],
                ['id_city' => 6745, 'id_state' => 16, 'name' => ' Serranópolis do Iguaçu'],
                ['id_city' => 6746, 'id_state' => 16, 'name' => ' Serraria Klas'],
                ['id_city' => 6747, 'id_state' => 16, 'name' => ' Serrinha'],
                ['id_city' => 6748, 'id_state' => 16, 'name' => ' Sertaneja'],
                ['id_city' => 6749, 'id_state' => 16, 'name' => ' Sertanópolis'],
                ['id_city' => 6750, 'id_state' => 16, 'name' => ' Sertãozinho'],
                ['id_city' => 6751, 'id_state' => 16, 'name' => ' Sete Saltos de Cima'],
                ['id_city' => 6752, 'id_state' => 16, 'name' => ' Siqueira Belo'],
                ['id_city' => 6753, 'id_state' => 16, 'name' => ' Siqueira Campos'],
                ['id_city' => 6754, 'id_state' => 16, 'name' => ' Socavão'],
                ['id_city' => 6755, 'id_state' => 16, 'name' => ' Colônia Socorro'],
                ['id_city' => 6756, 'id_state' => 16, 'name' => ' Sulina'],
                ['id_city' => 6757, 'id_state' => 16, 'name' => ' Sumaré'],
                ['id_city' => 6758, 'id_state' => 16, 'name' => ' Sussui'],
                ['id_city' => 6759, 'id_state' => 16, 'name' => ' Sutis'],
                ['id_city' => 6760, 'id_state' => 16, 'name' => ' Taipa'],
                ['id_city' => 6761, 'id_state' => 16, 'name' => ' Tamarana'],
                ['id_city' => 6762, 'id_state' => 16, 'name' => ' Tambarutaca'],
                ['id_city' => 6763, 'id_state' => 16, 'name' => ' Tamboara'],
                ['id_city' => 6764, 'id_state' => 16, 'name' => ' Tanque Grande'],
                ['id_city' => 6765, 'id_state' => 16, 'name' => ' Tapejara'],
                ['id_city' => 6766, 'id_state' => 16, 'name' => ' Tapira'],
                ['id_city' => 6767, 'id_state' => 16, 'name' => ' Tapui'],
                ['id_city' => 6768, 'id_state' => 16, 'name' => ' Taquara'],
                ['id_city' => 6769, 'id_state' => 16, 'name' => ' Taquari dos Polacos'],
                ['id_city' => 6770, 'id_state' => 16, 'name' => ' Taquari dos Russos'],
                ['id_city' => 6771, 'id_state' => 16, 'name' => ' Taquaruna'],
                ['id_city' => 6772, 'id_state' => 16, 'name' => ' Teixeira Soares'],
                ['id_city' => 6773, 'id_state' => 16, 'name' => ' Telêmaco Borba'],
                ['id_city' => 6774, 'id_state' => 16, 'name' => ' Teolândia'],
                ['id_city' => 6775, 'id_state' => 16, 'name' => ' Tereza Breda'],
                ['id_city' => 6776, 'id_state' => 16, 'name' => ' Tereza Cristina'],
                ['id_city' => 6777, 'id_state' => 16, 'name' => ' Terra Boa'],
                ['id_city' => 6778, 'id_state' => 16, 'name' => ' Terra Nova'],
                ['id_city' => 6779, 'id_state' => 16, 'name' => ' Terra Rica'],
                ['id_city' => 6780, 'id_state' => 16, 'name' => ' Terra Roxa'],
                ['id_city' => 6781, 'id_state' => 16, 'name' => ' Tibagi'],
                ['id_city' => 6782, 'id_state' => 16, 'name' => ' Tijucas do Sul'],
                ['id_city' => 6783, 'id_state' => 16, 'name' => ' Tijuco Preto'],
                ['id_city' => 6784, 'id_state' => 16, 'name' => ' Tijuco Preto'],
                ['id_city' => 6785, 'id_state' => 16, 'name' => ' Timbu Velho'],
                ['id_city' => 6786, 'id_state' => 16, 'name' => ' Tindiquera'],
                ['id_city' => 6787, 'id_state' => 16, 'name' => ' Tiradentes'],
                ['id_city' => 6788, 'id_state' => 16, 'name' => ' Toledo'],
                ['id_city' => 6789, 'id_state' => 16, 'name' => ' Tomaz Coelho'],
                ['id_city' => 6790, 'id_state' => 16, 'name' => ' Tomazina'],
                ['id_city' => 6791, 'id_state' => 16, 'name' => ' Três Barras do Paraná'],
                ['id_city' => 6792, 'id_state' => 16, 'name' => ' Três Bicos'],
                ['id_city' => 6793, 'id_state' => 16, 'name' => ' Três Bocas'],
                ['id_city' => 6794, 'id_state' => 16, 'name' => ' Três Capões'],
                ['id_city' => 6795, 'id_state' => 16, 'name' => ' Três Córregos'],
                ['id_city' => 6796, 'id_state' => 16, 'name' => ' Três Lagoas'],
                ['id_city' => 6797, 'id_state' => 16, 'name' => ' Três Pinheiros'],
                ['id_city' => 6798, 'id_state' => 16, 'name' => ' Três Placas'],
                ['id_city' => 6799, 'id_state' => 16, 'name' => ' Triângulo'],
                ['id_city' => 6800, 'id_state' => 16, 'name' => ' Trindade'],
                ['id_city' => 6801, 'id_state' => 16, 'name' => ' Triolândia'],
                ['id_city' => 6802, 'id_state' => 16, 'name' => ' Tronco'],
                ['id_city' => 6803, 'id_state' => 16, 'name' => ' Tunas do Paraná'],
                ['id_city' => 6804, 'id_state' => 16, 'name' => ' Tuneiras do Oeste'],
                ['id_city' => 6805, 'id_state' => 16, 'name' => ' Tupãssi'],
                ['id_city' => 6806, 'id_state' => 16, 'name' => ' Tupinambá'],
                ['id_city' => 6807, 'id_state' => 16, 'name' => ' Turvo'],
                ['id_city' => 6808, 'id_state' => 16, 'name' => ' Ubaldino Taques'],
                ['id_city' => 6809, 'id_state' => 16, 'name' => ' Ubauna'],
                ['id_city' => 6810, 'id_state' => 16, 'name' => ' Ubiratã'],
                ['id_city' => 6811, 'id_state' => 16, 'name' => ' Umuarama'],
                ['id_city' => 6812, 'id_state' => 16, 'name' => ' União'],
                ['id_city' => 6813, 'id_state' => 16, 'name' => ' União da Vitória'],
                ['id_city' => 6814, 'id_state' => 16, 'name' => ' União do Oeste'],
                ['id_city' => 6815, 'id_state' => 16, 'name' => ' Uniflor'],
                ['id_city' => 6816, 'id_state' => 16, 'name' => ' Uraí'],
                ['id_city' => 6817, 'id_state' => 16, 'name' => ' Uvaia'],
                ['id_city' => 6818, 'id_state' => 16, 'name' => ' Valentins'],
                ['id_city' => 6819, 'id_state' => 16, 'name' => ' Valério'],
                ['id_city' => 6820, 'id_state' => 16, 'name' => ' Vargeado'],
                ['id_city' => 6821, 'id_state' => 16, 'name' => ' Vassoural'],
                ['id_city' => 6822, 'id_state' => 16, 'name' => ' Ventania'],
                ['id_city' => 6823, 'id_state' => 16, 'name' => ' Vera Cruz do Oeste'],
                ['id_city' => 6824, 'id_state' => 16, 'name' => ' Vera Guarani'],
                ['id_city' => 6825, 'id_state' => 16, 'name' => ' Verê'],
                ['id_city' => 6826, 'id_state' => 16, 'name' => ' Vida Nova'],
                ['id_city' => 6827, 'id_state' => 16, 'name' => ' Vidigal'],
                ['id_city' => 6828, 'id_state' => 16, 'name' => ' Alto Paraíso'],
                ['id_city' => 6829, 'id_state' => 16, 'name' => ' Vila Diniz'],
                ['id_city' => 6830, 'id_state' => 16, 'name' => ' Vila dos Roldos'],
                ['id_city' => 6831, 'id_state' => 16, 'name' => ' Vila Flórida'],
                ['id_city' => 6832, 'id_state' => 16, 'name' => ' Vila Gandhi'],
                ['id_city' => 6833, 'id_state' => 16, 'name' => ' Vila Guay'],
                ['id_city' => 6834, 'id_state' => 16, 'name' => ' Vila Nova'],
                ['id_city' => 6835, 'id_state' => 16, 'name' => ' Vila Nova de Florença'],
                ['id_city' => 6836, 'id_state' => 16, 'name' => ' Vila Paraíso'],
                ['id_city' => 6837, 'id_state' => 16, 'name' => ' Vila Reis'],
                ['id_city' => 6838, 'id_state' => 16, 'name' => ' Vila Rica do Ivaí'],
                ['id_city' => 6839, 'id_state' => 16, 'name' => ' Vila Silva Jardim'],
                ['id_city' => 6840, 'id_state' => 16, 'name' => ' Vila Velha'],
                ['id_city' => 6841, 'id_state' => 16, 'name' => ' Virmond'],
                ['id_city' => 6842, 'id_state' => 16, 'name' => ' Vista Alegre'],
                ['id_city' => 6843, 'id_state' => 16, 'name' => ' Vista Bonita'],
                ['id_city' => 6844, 'id_state' => 16, 'name' => ' Colônia Vitória'],
                ['id_city' => 6845, 'id_state' => 16, 'name' => ' Vitorino'],
                ['id_city' => 6846, 'id_state' => 16, 'name' => ' Warta'],
                ['id_city' => 6847, 'id_state' => 16, 'name' => ' Wenceslau Braz'],
                ['id_city' => 6848, 'id_state' => 16, 'name' => ' Xambrê'],
                ['id_city' => 6849, 'id_state' => 16, 'name' => ' Xaxim'],
                ['id_city' => 6850, 'id_state' => 16, 'name' => ' Yolanda'],
                ['id_city' => 6851, 'id_state' => 16, 'name' => ' Quarto Centenário'],
                ['id_city' => 6852, 'id_state' => 19, 'name' => ' Abarracamento'],
                ['id_city' => 6853, 'id_state' => 19, 'name' => ' Ilha Grande'],
                ['id_city' => 6854, 'id_state' => 19, 'name' => ' Afonso Arinos'],
                ['id_city' => 6855, 'id_state' => 19, 'name' => ' Agulhas Negras'],
                ['id_city' => 6856, 'id_state' => 19, 'name' => ' Amparo'],
                ['id_city' => 6857, 'id_state' => 19, 'name' => ' Andrade Pinto'],
                ['id_city' => 6858, 'id_state' => 19, 'name' => ' Angra dos Reis'],
                ['id_city' => 6859, 'id_state' => 19, 'name' => ' Anta'],
                ['id_city' => 6860, 'id_state' => 19, 'name' => ' Aperibé'],
                ['id_city' => 6861, 'id_state' => 19, 'name' => ' Araruama'],
                ['id_city' => 6862, 'id_state' => 19, 'name' => ' Areal'],
                ['id_city' => 6863, 'id_state' => 19, 'name' => ' Armação dos Búzios'],
                ['id_city' => 6864, 'id_state' => 19, 'name' => ' Arraial do Cabo'],
                ['id_city' => 6865, 'id_state' => 19, 'name' => ' Arrozal'],
                ['id_city' => 6866, 'id_state' => 19, 'name' => ' Avelar'],
                ['id_city' => 6867, 'id_state' => 19, 'name' => ' Bacaxá'],
                ['id_city' => 6868, 'id_state' => 19, 'name' => ' Baltazar'],
                ['id_city' => 6869, 'id_state' => 19, 'name' => ' Banquete'],
                ['id_city' => 6870, 'id_state' => 19, 'name' => ' Barão de Juparana'],
                ['id_city' => 6871, 'id_state' => 19, 'name' => ' Barcelos'],
                ['id_city' => 6872, 'id_state' => 19, 'name' => ' Barra Alegre'],
                ['id_city' => 6873, 'id_state' => 19, 'name' => ' Barra de Macaé'],
                ['id_city' => 6874, 'id_state' => 19, 'name' => ' Barra de São João'],
                ['id_city' => 6875, 'id_state' => 19, 'name' => ' Barra do Piraí'],
                ['id_city' => 6876, 'id_state' => 19, 'name' => ' Barra Mansa'],
                ['id_city' => 6877, 'id_state' => 19, 'name' => ' Barra Seca'],
                ['id_city' => 6878, 'id_state' => 19, 'name' => ' Belford Roxo'],
                ['id_city' => 6879, 'id_state' => 19, 'name' => ' Bemposta'],
                ['id_city' => 6880, 'id_state' => 19, 'name' => ' Boa Esperança'],
                ['id_city' => 6881, 'id_state' => 19, 'name' => ' Boa Sorte'],
                ['id_city' => 6882, 'id_state' => 19, 'name' => ' Boa Ventura'],
                ['id_city' => 6883, 'id_state' => 19, 'name' => ' Bom Jardim'],
                ['id_city' => 6884, 'id_state' => 19, 'name' => ' Bom Jesus do Itabapoana'],
                ['id_city' => 6885, 'id_state' => 19, 'name' => ' Bom Jesus do Querendo'],
                ['id_city' => 6886, 'id_state' => 19, 'name' => ' Cabo Frio'],
                ['id_city' => 6887, 'id_state' => 19, 'name' => ' Cabuçu'],
                ['id_city' => 6888, 'id_state' => 19, 'name' => ' Cachoeiras de Macacu'],
                ['id_city' => 6889, 'id_state' => 19, 'name' => ' Cachoeiros'],
                ['id_city' => 6890, 'id_state' => 19, 'name' => ' Calheiros'],
                ['id_city' => 6891, 'id_state' => 19, 'name' => ' Cambiasca'],
                ['id_city' => 6892, 'id_state' => 19, 'name' => ' Cambuci'],
                ['id_city' => 6893, 'id_state' => 19, 'name' => ' Campo do Coelho'],
                ['id_city' => 6894, 'id_state' => 19, 'name' => ' Campos dos Goytacazes'],
                ['id_city' => 6895, 'id_state' => 19, 'name' => ' Campos Elíseos'],
                ['id_city' => 6896, 'id_state' => 19, 'name' => ' Cantagalo'],
                ['id_city' => 6897, 'id_state' => 19, 'name' => ' Carabuçu'],
                ['id_city' => 6898, 'id_state' => 19, 'name' => ' Carapebus'],
                ['id_city' => 6899, 'id_state' => 19, 'name' => ' Cardoso Moreira'],
                ['id_city' => 6900, 'id_state' => 19, 'name' => ' Carmo'],
                ['id_city' => 6901, 'id_state' => 19, 'name' => ' Cascatinha'],
                ['id_city' => 6902, 'id_state' => 19, 'name' => ' Casimiro de Abreu'],
                ['id_city' => 6903, 'id_state' => 19, 'name' => ' Cava'],
                ['id_city' => 6904, 'id_state' => 19, 'name' => ' Coelho da Rocha'],
                ['id_city' => 6905, 'id_state' => 19, 'name' => ' Colônia'],
                ['id_city' => 6906, 'id_state' => 19, 'name' => ' Comendador Levy Gasparian'],
                ['id_city' => 6907, 'id_state' => 19, 'name' => ' Comendador Venâncio'],
                ['id_city' => 6908, 'id_state' => 19, 'name' => ' Conceição de Jacareí'],
                ['id_city' => 6909, 'id_state' => 19, 'name' => ' Conceição de Macabu'],
                ['id_city' => 6910, 'id_state' => 19, 'name' => ' Conrado'],
                ['id_city' => 6911, 'id_state' => 19, 'name' => ' Conselheiro Paulino'],
                ['id_city' => 6912, 'id_state' => 19, 'name' => ' Conservatória'],
                ['id_city' => 6913, 'id_state' => 19, 'name' => ' Cordeiro'],
                ['id_city' => 6914, 'id_state' => 19, 'name' => ' Coroa Grande'],
                ['id_city' => 6915, 'id_state' => 19, 'name' => ' Correas'],
                ['id_city' => 6916, 'id_state' => 19, 'name' => ' Córrego da Prata'],
                ['id_city' => 6917, 'id_state' => 19, 'name' => ' Córrego do Ouro'],
                ['id_city' => 6918, 'id_state' => 19, 'name' => ' Correntezas'],
                ['id_city' => 6919, 'id_state' => 19, 'name' => ' Cunhambebe'],
                ['id_city' => 6920, 'id_state' => 19, 'name' => ' Dorândia'],
                ['id_city' => 6921, 'id_state' => 19, 'name' => ' Dores de Macabu'],
                ['id_city' => 6922, 'id_state' => 19, 'name' => ' Doutor Elias'],
                ['id_city' => 6923, 'id_state' => 19, 'name' => ' Doutor Loreti'],
                ['id_city' => 6924, 'id_state' => 19, 'name' => ' Duas Barras'],
                ['id_city' => 6925, 'id_state' => 19, 'name' => ' Duque de Caxias'],
                ['id_city' => 6926, 'id_state' => 19, 'name' => ' Engenheiro Passos'],
                ['id_city' => 6927, 'id_state' => 19, 'name' => ' Engenheiro Paulo de Frontin'],
                ['id_city' => 6928, 'id_state' => 19, 'name' => ' Engenheiro Pedreira'],
                ['id_city' => 6929, 'id_state' => 19, 'name' => ' Estrada Nova'],
                ['id_city' => 6930, 'id_state' => 19, 'name' => ' Euclidelândia'],
                ['id_city' => 6931, 'id_state' => 19, 'name' => ' Falcão'],
                ['id_city' => 6932, 'id_state' => 19, 'name' => ' Floriano'],
                ['id_city' => 6933, 'id_state' => 19, 'name' => ' Fumaça'],
                ['id_city' => 6934, 'id_state' => 19, 'name' => ' Funil'],
                ['id_city' => 6935, 'id_state' => 19, 'name' => ' Gaviões'],
                ['id_city' => 6936, 'id_state' => 19, 'name' => ' Getulândia'],
                ['id_city' => 6937, 'id_state' => 19, 'name' => ' Glicério'],
                ['id_city' => 6938, 'id_state' => 19, 'name' => ' Goitacazes'],
                ['id_city' => 6939, 'id_state' => 19, 'name' => ' Governador Portela'],
                ['id_city' => 6940, 'id_state' => 19, 'name' => ' Guapimirim'],
                ['id_city' => 6941, 'id_state' => 19, 'name' => ' Guia de Pacobaíba'],
                ['id_city' => 6942, 'id_state' => 19, 'name' => ' Ibitiguaçu'],
                ['id_city' => 6943, 'id_state' => 19, 'name' => ' Ibitioca'],
                ['id_city' => 6944, 'id_state' => 19, 'name' => ' Ibituporanga'],
                ['id_city' => 6945, 'id_state' => 19, 'name' => ' Iguaba Grande'],
                ['id_city' => 6946, 'id_state' => 19, 'name' => ' Imbariê'],
                ['id_city' => 6947, 'id_state' => 19, 'name' => ' Inconfidência'],
                ['id_city' => 6948, 'id_state' => 19, 'name' => ' Inhomirim'],
                ['id_city' => 6949, 'id_state' => 19, 'name' => ' Inoã'],
                ['id_city' => 6950, 'id_state' => 19, 'name' => ' Ipiabás'],
                ['id_city' => 6951, 'id_state' => 19, 'name' => ' Ipiiba'],
                ['id_city' => 6952, 'id_state' => 19, 'name' => ' Ipuca'],
                ['id_city' => 6953, 'id_state' => 19, 'name' => ' Itabapoana'],
                ['id_city' => 6954, 'id_state' => 19, 'name' => ' Itaboraí'],
                ['id_city' => 6955, 'id_state' => 19, 'name' => ' Itacurussá'],
                ['id_city' => 6956, 'id_state' => 19, 'name' => ' Itaguaí'],
                ['id_city' => 6957, 'id_state' => 19, 'name' => ' Itaipava'],
                ['id_city' => 6958, 'id_state' => 19, 'name' => ' Itaipu'],
                ['id_city' => 6959, 'id_state' => 19, 'name' => ' Itajara'],
                ['id_city' => 6960, 'id_state' => 19, 'name' => ' Italva'],
                ['id_city' => 6961, 'id_state' => 19, 'name' => ' Itambi'],
                ['id_city' => 6962, 'id_state' => 19, 'name' => ' Itaocara'],
                ['id_city' => 6963, 'id_state' => 19, 'name' => ' Itaperuna'],
                ['id_city' => 6964, 'id_state' => 19, 'name' => ' Itatiaia'],
                ['id_city' => 6965, 'id_state' => 19, 'name' => ' Jaguarembé'],
                ['id_city' => 6966, 'id_state' => 19, 'name' => ' Jamapará'],
                ['id_city' => 6967, 'id_state' => 19, 'name' => ' Japeri'],
                ['id_city' => 6968, 'id_state' => 19, 'name' => ' Japuíba'],
                ['id_city' => 6969, 'id_state' => 19, 'name' => ' Laje do Muriaé'],
                ['id_city' => 6970, 'id_state' => 19, 'name' => ' Laranjais'],
                ['id_city' => 6971, 'id_state' => 19, 'name' => ' Lídice'],
                ['id_city' => 6972, 'id_state' => 19, 'name' => ' Lumiar'],
                ['id_city' => 6973, 'id_state' => 19, 'name' => ' Macabuzinho'],
                ['id_city' => 6974, 'id_state' => 19, 'name' => ' Macaé'],
                ['id_city' => 6975, 'id_state' => 19, 'name' => ' Macuco'],
                ['id_city' => 6976, 'id_state' => 19, 'name' => ' Magé'],
                ['id_city' => 6977, 'id_state' => 19, 'name' => ' Mambucaba'],
                ['id_city' => 6978, 'id_state' => 19, 'name' => ' Mangaratiba'],
                ['id_city' => 6979, 'id_state' => 19, 'name' => ' Maniva'],
                ['id_city' => 6980, 'id_state' => 19, 'name' => ' Manuel Duarte'],
                ['id_city' => 6981, 'id_state' => 19, 'name' => ' Marangatu'],
                ['id_city' => 6982, 'id_state' => 19, 'name' => ' Maricá'],
                ['id_city' => 6983, 'id_state' => 19, 'name' => ' Mendes'],
                ['id_city' => 6984, 'id_state' => 19, 'name' => ' Mesquita'],
                ['id_city' => 6985, 'id_state' => 19, 'name' => ' Miguel Pereira'],
                ['id_city' => 6986, 'id_state' => 19, 'name' => ' Miracema'],
                ['id_city' => 6987, 'id_state' => 19, 'name' => ' Monnerat'],
                ['id_city' => 6988, 'id_state' => 19, 'name' => ' Monjolo'],
                ['id_city' => 6989, 'id_state' => 19, 'name' => ' Monte Alegre'],
                ['id_city' => 6990, 'id_state' => 19, 'name' => ' Monte Verde'],
                ['id_city' => 6991, 'id_state' => 19, 'name' => ' Monumento'],
                ['id_city' => 6992, 'id_state' => 19, 'name' => ' Morangaba'],
                ['id_city' => 6993, 'id_state' => 19, 'name' => ' Morro do Côco'],
                ['id_city' => 6994, 'id_state' => 19, 'name' => ' Morro Grande'],
                ['id_city' => 6995, 'id_state' => 19, 'name' => ' Mussurepe'],
                ['id_city' => 6996, 'id_state' => 19, 'name' => ' Natividade'],
                ['id_city' => 6997, 'id_state' => 19, 'name' => ' Neves'],
                ['id_city' => 6998, 'id_state' => 19, 'name' => ' Nhunguaçu'],
                ['id_city' => 6999, 'id_state' => 19, 'name' => ' Nilópolis'],
                ['id_city' => 7000, 'id_state' => 19, 'name' => ' Niterói'],
                ['id_city' => 7001, 'id_state' => 19, 'name' => ' Nossa Senhora da Aparecida'],
                ['id_city' => 7002, 'id_state' => 19, 'name' => ' Nossa Senhora da Penha'],
                ['id_city' => 7003, 'id_state' => 19, 'name' => ' Nossa Senhora do Amparo'],
                ['id_city' => 7004, 'id_state' => 19, 'name' => ' Nova Friburgo'],
                ['id_city' => 7005, 'id_state' => 19, 'name' => ' Nova Iguaçu'],
                ['id_city' => 7006, 'id_state' => 19, 'name' => ' Olinda'],
                ['id_city' => 7007, 'id_state' => 19, 'name' => ' Ourânia'],
                ['id_city' => 7008, 'id_state' => 19, 'name' => ' Papucaia'],
                ['id_city' => 7009, 'id_state' => 19, 'name' => ' Paquequer Pequeno'],
                ['id_city' => 7010, 'id_state' => 19, 'name' => ' Paracambi'],
                ['id_city' => 7011, 'id_state' => 19, 'name' => ' Paraíba do Sul'],
                ['id_city' => 7012, 'id_state' => 19, 'name' => ' Paraíso do Tobias'],
                ['id_city' => 7013, 'id_state' => 19, 'name' => ' Paraoquena'],
                ['id_city' => 7014, 'id_state' => 19, 'name' => ' Parapeúna'],
                ['id_city' => 7015, 'id_state' => 19, 'name' => ' Parati'],
                ['id_city' => 7016, 'id_state' => 19, 'name' => ' Parati Mirim'],
                ['id_city' => 7017, 'id_state' => 19, 'name' => ' Passa Três'],
                ['id_city' => 7018, 'id_state' => 19, 'name' => ' Paty do Alferes'],
                ['id_city' => 7019, 'id_state' => 19, 'name' => ' Pedra Selada'],
                ['id_city' => 7020, 'id_state' => 19, 'name' => ' Pedro do Rio'],
                ['id_city' => 7021, 'id_state' => 19, 'name' => ' Penedo'],
                ['id_city' => 7022, 'id_state' => 19, 'name' => ' Pentagna'],
                ['id_city' => 7023, 'id_state' => 19, 'name' => ' Petrópolis'],
                ['id_city' => 7024, 'id_state' => 19, 'name' => ' Piabetá'],
                ['id_city' => 7025, 'id_state' => 19, 'name' => ' Pião'],
                ['id_city' => 7026, 'id_state' => 19, 'name' => ' Pinheiral'],
                ['id_city' => 7027, 'id_state' => 19, 'name' => ' Pipeiras'],
                ['id_city' => 7028, 'id_state' => 19, 'name' => ' Piraí'],
                ['id_city' => 7029, 'id_state' => 19, 'name' => ' Pirangaí'],
                ['id_city' => 7030, 'id_state' => 19, 'name' => ' Pirapetinga de Bom Jesus'],
                ['id_city' => 7031, 'id_state' => 19, 'name' => ' Porciúncula'],
                ['id_city' => 7032, 'id_state' => 19, 'name' => ' Portela'],
                ['id_city' => 7033, 'id_state' => 19, 'name' => ' Porto Real'],
                ['id_city' => 7034, 'id_state' => 19, 'name' => ' Porto Velho do Cunha'],
                ['id_city' => 7035, 'id_state' => 19, 'name' => ' Posse'],
                ['id_city' => 7036, 'id_state' => 19, 'name' => ' Pureza'],
                ['id_city' => 7037, 'id_state' => 19, 'name' => ' Purilândia'],
                ['id_city' => 7038, 'id_state' => 19, 'name' => ' Quartéis'],
                ['id_city' => 7039, 'id_state' => 19, 'name' => ' Quatis'],
                ['id_city' => 7040, 'id_state' => 19, 'name' => ' Queimados'],
                ['id_city' => 7041, 'id_state' => 19, 'name' => ' Quissamã'],
                ['id_city' => 7042, 'id_state' => 19, 'name' => ' Raposo'],
                ['id_city' => 7043, 'id_state' => 19, 'name' => ' Renascença'],
                ['id_city' => 7044, 'id_state' => 19, 'name' => ' Resende'],
                ['id_city' => 7045, 'id_state' => 19, 'name' => ' Retiro do Muriaé'],
                ['id_city' => 7046, 'id_state' => 19, 'name' => ' Rialto'],
                ['id_city' => 7047, 'id_state' => 19, 'name' => ' Ribeirão de São Joaquim'],
                ['id_city' => 7048, 'id_state' => 19, 'name' => ' Rio Bonito'],
                ['id_city' => 7049, 'id_state' => 19, 'name' => ' Rio Claro'],
                ['id_city' => 7050, 'id_state' => 19, 'name' => ' Rio das Flores'],
                ['id_city' => 7051, 'id_state' => 19, 'name' => ' Rio das Ostras'],
                ['id_city' => 7052, 'id_state' => 19, 'name' => ' Rio de Janeiro'],
                ['id_city' => 7053, 'id_state' => 19, 'name' => ' Riograndina'],
                ['id_city' => 7054, 'id_state' => 19, 'name' => ' Rosal'],
                ['id_city' => 7055, 'id_state' => 19, 'name' => ' Sacra Família do Tinguá'],
                ['id_city' => 7056, 'id_state' => 19, 'name' => ' Salutaris'],
                ['id_city' => 7057, 'id_state' => 19, 'name' => ' Sambaetiba'],
                ['id_city' => 7058, 'id_state' => 19, 'name' => ' Sampaio Correia'],
                ['id_city' => 7059, 'id_state' => 19, 'name' => ' Sana'],
                ['id_city' => 7060, 'id_state' => 19, 'name' => ' Santa Clara'],
                ['id_city' => 7061, 'id_state' => 19, 'name' => ' Santa Cruz'],
                ['id_city' => 7062, 'id_state' => 19, 'name' => ' Santa Cruz da Serra'],
                ['id_city' => 7063, 'id_state' => 19, 'name' => ' Santa Isabel'],
                ['id_city' => 7064, 'id_state' => 19, 'name' => ' Santa Isabel do Rio Preto'],
                ['id_city' => 7065, 'id_state' => 19, 'name' => ' Santa Maria'],
                ['id_city' => 7066, 'id_state' => 19, 'name' => ' Santa Maria Madalena'],
                ['id_city' => 7067, 'id_state' => 19, 'name' => ' Santa Rita da Floresta'],
                ['id_city' => 7068, 'id_state' => 19, 'name' => ' Santanésia'],
                ['id_city' => 7069, 'id_state' => 19, 'name' => ' Santo Aleixo'],
                ['id_city' => 7070, 'id_state' => 19, 'name' => ' Santo Amaro de Campos'],
                ['id_city' => 7071, 'id_state' => 19, 'name' => ' Santo Antônio de Pádua'],
                ['id_city' => 7072, 'id_state' => 19, 'name' => ' Santo Antônio do Imbé'],
                ['id_city' => 7073, 'id_state' => 19, 'name' => ' Santo Eduardo'],
                ['id_city' => 7074, 'id_state' => 19, 'name' => ' São Fidélis'],
                ['id_city' => 7075, 'id_state' => 19, 'name' => ' São Francisco de Itabapoana'],
                ['id_city' => 7076, 'id_state' => 19, 'name' => ' São Gonçalo'],
                ['id_city' => 7077, 'id_state' => 19, 'name' => ' São João da Barra'],
                ['id_city' => 7078, 'id_state' => 19, 'name' => ' São João de Meriti'],
                ['id_city' => 7079, 'id_state' => 19, 'name' => ' São João do Paraíso'],
                ['id_city' => 7080, 'id_state' => 19, 'name' => ' São João Marcos'],
                ['id_city' => 7081, 'id_state' => 19, 'name' => ' São Joaquim'],
                ['id_city' => 7082, 'id_state' => 19, 'name' => ' São José de Ubá'],
                ['id_city' => 7083, 'id_state' => 19, 'name' => ' São José do Ribeirão'],
                ['id_city' => 7084, 'id_state' => 19, 'name' => ' São José do Turvo'],
                ['id_city' => 7085, 'id_state' => 19, 'name' => ' São José do Vale do Rio Preto'],
                ['id_city' => 7086, 'id_state' => 19, 'name' => ' São Mateus'],
                ['id_city' => 7087, 'id_state' => 19, 'name' => ' São Pedro da Aldeia'],
                ['id_city' => 7088, 'id_state' => 19, 'name' => ' São Sebastião de Campos'],
                ['id_city' => 7089, 'id_state' => 19, 'name' => ' São Sebastião do Alto'],
                ['id_city' => 7090, 'id_state' => 19, 'name' => ' São Sebastião do Paraíba'],
                ['id_city' => 7091, 'id_state' => 19, 'name' => ' São Sebastião dos Ferreiros'],
                ['id_city' => 7092, 'id_state' => 19, 'name' => ' São Vicente de Paula'],
                ['id_city' => 7093, 'id_state' => 19, 'name' => ' Sapucaia'],
                ['id_city' => 7094, 'id_state' => 19, 'name' => ' Saquarema'],
                ['id_city' => 7095, 'id_state' => 19, 'name' => ' Saracuruna'],
                ['id_city' => 7096, 'id_state' => 19, 'name' => ' Sebastião de Lacerda'],
                ['id_city' => 7097, 'id_state' => 19, 'name' => ' Seropédica'],
                ['id_city' => 7098, 'id_state' => 19, 'name' => ' Serrinha'],
                ['id_city' => 7099, 'id_state' => 19, 'name' => ' Sete Pontes'],
                ['id_city' => 7100, 'id_state' => 19, 'name' => ' Silva Jardim'],
                ['id_city' => 7101, 'id_state' => 19, 'name' => ' Sodrelândia'],
                ['id_city' => 7102, 'id_state' => 19, 'name' => ' Sossego'],
                ['id_city' => 7103, 'id_state' => 19, 'name' => ' Subaio'],
                ['id_city' => 7104, 'id_state' => 19, 'name' => ' Sumidouro'],
                ['id_city' => 7105, 'id_state' => 19, 'name' => ' Suruí'],
                ['id_city' => 7106, 'id_state' => 19, 'name' => ' Taboas'],
                ['id_city' => 7107, 'id_state' => 19, 'name' => ' Tamoios'],
                ['id_city' => 7108, 'id_state' => 19, 'name' => ' Tanguá'],
                ['id_city' => 7109, 'id_state' => 19, 'name' => ' Tapera'],
                ['id_city' => 7110, 'id_state' => 19, 'name' => ' Tarituba'],
                ['id_city' => 7111, 'id_state' => 19, 'name' => ' Teresópolis'],
                ['id_city' => 7112, 'id_state' => 19, 'name' => ' Tocos'],
                ['id_city' => 7113, 'id_state' => 19, 'name' => ' Trajano de Morais'],
                ['id_city' => 7114, 'id_state' => 19, 'name' => ' Travessão'],
                ['id_city' => 7115, 'id_state' => 19, 'name' => ' Três Irmãos'],
                ['id_city' => 7116, 'id_state' => 19, 'name' => ' Três Rios'],
                ['id_city' => 7117, 'id_state' => 19, 'name' => ' Triunfo'],
                ['id_city' => 7118, 'id_state' => 19, 'name' => ' Valão do Barro'],
                ['id_city' => 7119, 'id_state' => 19, 'name' => ' Valença'],
                ['id_city' => 7120, 'id_state' => 19, 'name' => ' Vargem Alegre'],
                ['id_city' => 7121, 'id_state' => 19, 'name' => ' Varre-Sai'],
                ['id_city' => 7122, 'id_state' => 19, 'name' => ' Vassouras'],
                ['id_city' => 7123, 'id_state' => 19, 'name' => ' Venda das Flores'],
                ['id_city' => 7124, 'id_state' => 19, 'name' => ' Vila da Grama'],
                ['id_city' => 7125, 'id_state' => 19, 'name' => ' Vila Muriqui'],
                ['id_city' => 7126, 'id_state' => 19, 'name' => ' Vila Nova de Campos'],
                ['id_city' => 7127, 'id_state' => 19, 'name' => ' Visconde de Imbé'],
                ['id_city' => 7128, 'id_state' => 19, 'name' => ' Volta Redonda'],
                ['id_city' => 7129, 'id_state' => 19, 'name' => ' Werneck'],
                ['id_city' => 7130, 'id_state' => 19, 'name' => ' Xerém'],
                ['id_city' => 7131, 'id_state' => 20, 'name' => ' Acari'],
                ['id_city' => 7132, 'id_state' => 20, 'name' => ' Açu'],
                ['id_city' => 7133, 'id_state' => 20, 'name' => ' Afonso Bezerra'],
                ['id_city' => 7134, 'id_state' => 20, 'name' => ' Água Nova'],
                ['id_city' => 7135, 'id_state' => 20, 'name' => ' Alexandria'],
                ['id_city' => 7136, 'id_state' => 20, 'name' => ' Almino Afonso'],
                ['id_city' => 7137, 'id_state' => 20, 'name' => ' Alto do Rodrigues'],
                ['id_city' => 7138, 'id_state' => 20, 'name' => ' Angicos'],
                ['id_city' => 7139, 'id_state' => 20, 'name' => ' Antônio Martins'],
                ['id_city' => 7140, 'id_state' => 20, 'name' => ' Apodi'],
                ['id_city' => 7141, 'id_state' => 20, 'name' => ' Areia Branca'],
                ['id_city' => 7142, 'id_state' => 20, 'name' => ' Arez'],
                ['id_city' => 7143, 'id_state' => 20, 'name' => ' Baía Formosa'],
                ['id_city' => 7144, 'id_state' => 20, 'name' => ' Barão de Serra Branca'],
                ['id_city' => 7145, 'id_state' => 20, 'name' => ' Baraúna'],
                ['id_city' => 7146, 'id_state' => 20, 'name' => ' Barcelona'],
                ['id_city' => 7147, 'id_state' => 20, 'name' => ' Belo Horizonte'],
                ['id_city' => 7148, 'id_state' => 20, 'name' => ' Bento Fernandes'],
                ['id_city' => 7149, 'id_state' => 20, 'name' => ' Boa Saúde'],
                ['id_city' => 7150, 'id_state' => 20, 'name' => ' Bodó'],
                ['id_city' => 7151, 'id_state' => 20, 'name' => ' Bom Jesus'],
                ['id_city' => 7152, 'id_state' => 20, 'name' => ' Brejinho'],
                ['id_city' => 7153, 'id_state' => 20, 'name' => ' Caiçara do Norte'],
                ['id_city' => 7154, 'id_state' => 20, 'name' => ' Caiçara do Rio do Vento'],
                ['id_city' => 7155, 'id_state' => 20, 'name' => ' Caicó'],
                ['id_city' => 7156, 'id_state' => 20, 'name' => ' Campo Grande'],
                ['id_city' => 7157, 'id_state' => 20, 'name' => ' Campo Redondo'],
                ['id_city' => 7158, 'id_state' => 20, 'name' => ' Canguaretama'],
                ['id_city' => 7159, 'id_state' => 20, 'name' => ' Caraúbas'],
                ['id_city' => 7160, 'id_state' => 20, 'name' => ' Carnaúba dos Dantas'],
                ['id_city' => 7161, 'id_state' => 20, 'name' => ' Carnaubais'],
                ['id_city' => 7162, 'id_state' => 20, 'name' => ' Ceará-Mirim'],
                ['id_city' => 7163, 'id_state' => 20, 'name' => ' Cerro Corá'],
                ['id_city' => 7164, 'id_state' => 20, 'name' => ' Coronel Ezequiel'],
                ['id_city' => 7165, 'id_state' => 20, 'name' => ' Coronel João Pessoa'],
                ['id_city' => 7166, 'id_state' => 20, 'name' => ' Córrego de São Mateus'],
                ['id_city' => 7167, 'id_state' => 20, 'name' => ' Cruzeta'],
                ['id_city' => 7168, 'id_state' => 20, 'name' => ' Currais Novos'],
                ['id_city' => 7169, 'id_state' => 20, 'name' => ' Doutor Severiano'],
                ['id_city' => 7170, 'id_state' => 20, 'name' => ' Encanto'],
                ['id_city' => 7171, 'id_state' => 20, 'name' => ' Equador'],
                ['id_city' => 7172, 'id_state' => 20, 'name' => ' Espírito Santo'],
                ['id_city' => 7173, 'id_state' => 20, 'name' => ' Paraú'],
                ['id_city' => 7174, 'id_state' => 20, 'name' => ' Extremoz'],
                ['id_city' => 7175, 'id_state' => 20, 'name' => ' Felipe Guerra'],
                ['id_city' => 7176, 'id_state' => 20, 'name' => ' Fernando Pedroza'],
                ['id_city' => 7177, 'id_state' => 20, 'name' => ' Firmamento'],
                ['id_city' => 7178, 'id_state' => 20, 'name' => ' Florânia'],
                ['id_city' => 7179, 'id_state' => 20, 'name' => ' Francisco Dantas'],
                ['id_city' => 7180, 'id_state' => 20, 'name' => ' Frutuoso Gomes'],
                ['id_city' => 7181, 'id_state' => 20, 'name' => ' Galinhos'],
                ['id_city' => 7182, 'id_state' => 20, 'name' => ' Gameleira'],
                ['id_city' => 7183, 'id_state' => 20, 'name' => ' Goianinha'],
                ['id_city' => 7184, 'id_state' => 20, 'name' => ' Governador Dix-Sept Rosado'],
                ['id_city' => 7185, 'id_state' => 20, 'name' => ' Grossos'],
                ['id_city' => 7186, 'id_state' => 20, 'name' => ' Guamaré'],
                ['id_city' => 7187, 'id_state' => 20, 'name' => ' Ielmo Marinho'],
                ['id_city' => 7188, 'id_state' => 20, 'name' => ' Igreja Nova'],
                ['id_city' => 7189, 'id_state' => 20, 'name' => ' Ipanguaçu'],
                ['id_city' => 7190, 'id_state' => 20, 'name' => ' Ipiranga'],
                ['id_city' => 7191, 'id_state' => 20, 'name' => ' Ipueira'],
                ['id_city' => 7192, 'id_state' => 20, 'name' => ' Itajá'],
                ['id_city' => 7193, 'id_state' => 20, 'name' => ' Itaú'],
                ['id_city' => 7194, 'id_state' => 20, 'name' => ' Jaçanã'],
                ['id_city' => 7195, 'id_state' => 20, 'name' => ' Jandaíra'],
                ['id_city' => 7196, 'id_state' => 20, 'name' => ' Janduís'],
                ['id_city' => 7197, 'id_state' => 20, 'name' => ' Japi'],
                ['id_city' => 7198, 'id_state' => 20, 'name' => ' Jardim de Angicos'],
                ['id_city' => 7199, 'id_state' => 20, 'name' => ' Jardim de Piranhas'],
                ['id_city' => 7200, 'id_state' => 20, 'name' => ' Jardim do Seridó'],
                ['id_city' => 7201, 'id_state' => 20, 'name' => ' João Câmara'],
                ['id_city' => 7202, 'id_state' => 20, 'name' => ' João Dias'],
                ['id_city' => 7203, 'id_state' => 20, 'name' => ' José da Penha'],
                ['id_city' => 7204, 'id_state' => 20, 'name' => ' Jucurutu'],
                ['id_city' => 7205, 'id_state' => 20, 'name' => ' Jundiá'],
                ['id_city' => 7206, 'id_state' => 20, 'name' => ' Lagoa D Anta'],
                ['id_city' => 7207, 'id_state' => 20, 'name' => ' Lagoa de Pedras'],
                ['id_city' => 7208, 'id_state' => 20, 'name' => ' Lagoa de Velhos'],
                ['id_city' => 7209, 'id_state' => 20, 'name' => ' Lagoa Nova'],
                ['id_city' => 7210, 'id_state' => 20, 'name' => ' Lagoa Salgada'],
                ['id_city' => 7211, 'id_state' => 20, 'name' => ' Lajes'],
                ['id_city' => 7212, 'id_state' => 20, 'name' => ' Lajes Pintadas'],
                ['id_city' => 7213, 'id_state' => 20, 'name' => ' Lucrécia'],
                ['id_city' => 7214, 'id_state' => 20, 'name' => ' Luís Gomes'],
                ['id_city' => 7215, 'id_state' => 20, 'name' => ' Macaíba'],
                ['id_city' => 7216, 'id_state' => 20, 'name' => ' Macau'],
                ['id_city' => 7217, 'id_state' => 20, 'name' => ' Major Felipe'],
                ['id_city' => 7218, 'id_state' => 20, 'name' => ' Major Sales'],
                ['id_city' => 7219, 'id_state' => 20, 'name' => ' Marcelino Vieira'],
                ['id_city' => 7220, 'id_state' => 20, 'name' => ' Martins'],
                ['id_city' => 7221, 'id_state' => 20, 'name' => ' Mata de São Braz'],
                ['id_city' => 7222, 'id_state' => 20, 'name' => ' Maxaranguape'],
                ['id_city' => 7223, 'id_state' => 20, 'name' => ' Messias Targino'],
                ['id_city' => 7224, 'id_state' => 20, 'name' => ' Montanhas'],
                ['id_city' => 7225, 'id_state' => 20, 'name' => ' Monte Alegre'],
                ['id_city' => 7226, 'id_state' => 20, 'name' => ' Monte das Gameleiras'],
                ['id_city' => 7227, 'id_state' => 20, 'name' => ' Mossoró'],
                ['id_city' => 7228, 'id_state' => 20, 'name' => ' Natal'],
                ['id_city' => 7229, 'id_state' => 20, 'name' => ' Nísia Floresta'],
                ['id_city' => 7230, 'id_state' => 20, 'name' => ' Nova Cruz'],
                ['id_city' => 7231, 'id_state' => 20, 'name' => ' Olho-D Água do Borges'],
                ['id_city' => 7232, 'id_state' => 20, 'name' => ' Ouro Branco'],
                ['id_city' => 7233, 'id_state' => 20, 'name' => ' Paraná'],
                ['id_city' => 7234, 'id_state' => 20, 'name' => ' Parazinho'],
                ['id_city' => 7235, 'id_state' => 20, 'name' => ' Parelhas'],
                ['id_city' => 7236, 'id_state' => 20, 'name' => ' Parnamirim'],
                ['id_city' => 7237, 'id_state' => 20, 'name' => ' Passa e Fica'],
                ['id_city' => 7238, 'id_state' => 20, 'name' => ' Passagem'],
                ['id_city' => 7239, 'id_state' => 20, 'name' => ' Patu'],
                ['id_city' => 7240, 'id_state' => 20, 'name' => ' Pau dos Ferros'],
                ['id_city' => 7241, 'id_state' => 20, 'name' => ' Pedra Grande'],
                ['id_city' => 7242, 'id_state' => 20, 'name' => ' Pedra Preta'],
                ['id_city' => 7243, 'id_state' => 20, 'name' => ' Pedro Avelino'],
                ['id_city' => 7244, 'id_state' => 20, 'name' => ' Pedro Velho'],
                ['id_city' => 7245, 'id_state' => 20, 'name' => ' Pendências'],
                ['id_city' => 7246, 'id_state' => 20, 'name' => ' Pilões'],
                ['id_city' => 7247, 'id_state' => 20, 'name' => ' Poço Branco'],
                ['id_city' => 7248, 'id_state' => 20, 'name' => ' Portalegre'],
                ['id_city' => 7249, 'id_state' => 20, 'name' => ' Porto do Mangue'],
                ['id_city' => 7250, 'id_state' => 20, 'name' => ' Pureza'],
                ['id_city' => 7251, 'id_state' => 20, 'name' => ' Rafael Fernandes'],
                ['id_city' => 7252, 'id_state' => 20, 'name' => ' Rafael Godeiro'],
                ['id_city' => 7253, 'id_state' => 20, 'name' => ' Riacho da Cruz'],
                ['id_city' => 7254, 'id_state' => 20, 'name' => ' Riacho de Santana'],
                ['id_city' => 7255, 'id_state' => 20, 'name' => ' Riachuelo'],
                ['id_city' => 7256, 'id_state' => 20, 'name' => ' Rio do Fogo'],
                ['id_city' => 7257, 'id_state' => 20, 'name' => ' Rodolfo Fernandes'],
                ['id_city' => 7258, 'id_state' => 20, 'name' => ' Rosário'],
                ['id_city' => 7259, 'id_state' => 20, 'name' => ' Ruy Barbosa'],
                ['id_city' => 7260, 'id_state' => 20, 'name' => ' Salva Vida'],
                ['id_city' => 7261, 'id_state' => 20, 'name' => ' Santa Cruz'],
                ['id_city' => 7262, 'id_state' => 20, 'name' => ' Santa Fé'],
                ['id_city' => 7263, 'id_state' => 20, 'name' => ' Santa Maria'],
                ['id_city' => 7264, 'id_state' => 20, 'name' => ' Santa Teresa'],
                ['id_city' => 7265, 'id_state' => 20, 'name' => ' Santana do Matos'],
                ['id_city' => 7266, 'id_state' => 20, 'name' => ' Santana do Seridó'],
                ['id_city' => 7267, 'id_state' => 20, 'name' => ' Santo Antônio'],
                ['id_city' => 7268, 'id_state' => 20, 'name' => ' Santo Antônio do Potengi'],
                ['id_city' => 7269, 'id_state' => 20, 'name' => ' São Bento do Norte'],
                ['id_city' => 7270, 'id_state' => 20, 'name' => ' São Bento do Trairi'],
                ['id_city' => 7271, 'id_state' => 20, 'name' => ' São Bernardo'],
                ['id_city' => 7272, 'id_state' => 20, 'name' => ' São Fernando'],
                ['id_city' => 7273, 'id_state' => 20, 'name' => ' São Francisco do Oeste'],
                ['id_city' => 7274, 'id_state' => 20, 'name' => ' São Geraldo'],
                ['id_city' => 7275, 'id_state' => 20, 'name' => ' São Gonçalo do Amarante'],
                ['id_city' => 7276, 'id_state' => 20, 'name' => ' São João do Sabugi'],
                ['id_city' => 7277, 'id_state' => 20, 'name' => ' São José da Passagem'],
                ['id_city' => 7278, 'id_state' => 20, 'name' => ' São José de Mipibu'],
                ['id_city' => 7279, 'id_state' => 20, 'name' => ' São José do Campestre'],
                ['id_city' => 7280, 'id_state' => 20, 'name' => ' São José do Campestre'],
                ['id_city' => 7281, 'id_state' => 20, 'name' => ' São José do Seridó'],
                ['id_city' => 7282, 'id_state' => 20, 'name' => ' São Miguel'],
                ['id_city' => 7283, 'id_state' => 20, 'name' => ' São Miguel do Gostoso'],
                ['id_city' => 7284, 'id_state' => 20, 'name' => ' São Paulo do Potengi'],
                ['id_city' => 7285, 'id_state' => 20, 'name' => ' São Pedro'],
                ['id_city' => 7286, 'id_state' => 20, 'name' => ' São Rafael'],
                ['id_city' => 7287, 'id_state' => 20, 'name' => ' São Tomé'],
                ['id_city' => 7288, 'id_state' => 20, 'name' => ' São Vicente'],
                ['id_city' => 7289, 'id_state' => 20, 'name' => ' Senador Elói de Souza'],
                ['id_city' => 7290, 'id_state' => 20, 'name' => ' Senador Georgino Avelino'],
                ['id_city' => 7291, 'id_state' => 20, 'name' => ' Serra Caiada'],
                ['id_city' => 7292, 'id_state' => 20, 'name' => ' Serra da Tapuia'],
                ['id_city' => 7293, 'id_state' => 20, 'name' => ' Serra de São Bento'],
                ['id_city' => 7294, 'id_state' => 20, 'name' => ' Serra do Mel'],
                ['id_city' => 7295, 'id_state' => 20, 'name' => ' Serra Negra do Norte'],
                ['id_city' => 7296, 'id_state' => 20, 'name' => ' Serrinha'],
                ['id_city' => 7297, 'id_state' => 20, 'name' => ' Serrinha dos Pintos'],
                ['id_city' => 7298, 'id_state' => 20, 'name' => ' Severiano Melo'],
                ['id_city' => 7299, 'id_state' => 20, 'name' => ' Sítio Novo'],
                ['id_city' => 7300, 'id_state' => 20, 'name' => ' Taboleiro Grande'],
                ['id_city' => 7301, 'id_state' => 20, 'name' => ' Taipu'],
                ['id_city' => 7302, 'id_state' => 20, 'name' => ' Tangará'],
                ['id_city' => 7303, 'id_state' => 20, 'name' => ' Tenente Ananias'],
                ['id_city' => 7304, 'id_state' => 20, 'name' => ' Tenente Laurentino Cruz'],
                ['id_city' => 7305, 'id_state' => 20, 'name' => ' Tibau'],
                ['id_city' => 7306, 'id_state' => 20, 'name' => ' Tibau do Sul'],
                ['id_city' => 7307, 'id_state' => 20, 'name' => ' Timbaúba dos Batistas'],
                ['id_city' => 7308, 'id_state' => 20, 'name' => ' Touros'],
                ['id_city' => 7309, 'id_state' => 20, 'name' => ' Trairi'],
                ['id_city' => 7310, 'id_state' => 20, 'name' => ' Triunfo Potiguar'],
                ['id_city' => 7311, 'id_state' => 20, 'name' => ' Umarizal'],
                ['id_city' => 7312, 'id_state' => 20, 'name' => ' Upanema'],
                ['id_city' => 7313, 'id_state' => 20, 'name' => ' Várzea'],
                ['id_city' => 7314, 'id_state' => 20, 'name' => ' Venha-Ver'],
                ['id_city' => 7315, 'id_state' => 20, 'name' => ' Vera Cruz'],
                ['id_city' => 7316, 'id_state' => 20, 'name' => ' Viçosa'],
                ['id_city' => 7317, 'id_state' => 20, 'name' => ' Vila Flor'],
                ['id_city' => 7318, 'id_state' => 22, 'name' => ' Abunã'],
                ['id_city' => 7319, 'id_state' => 22, 'name' => ' Alto Alegre dos Parecis'],
                ['id_city' => 7320, 'id_state' => 22, 'name' => ' Alta Floresta D Oeste'],
                ['id_city' => 7321, 'id_state' => 22, 'name' => ' Alto Paraíso'],
                ['id_city' => 7322, 'id_state' => 22, 'name' => ' Alvorada D Oeste'],
                ['id_city' => 7323, 'id_state' => 22, 'name' => ' Ariquemes'],
                ['id_city' => 7324, 'id_state' => 22, 'name' => ' Buritis'],
                ['id_city' => 7325, 'id_state' => 22, 'name' => ' Cabixi'],
                ['id_city' => 7326, 'id_state' => 22, 'name' => ' Cacaulândia'],
                ['id_city' => 7327, 'id_state' => 22, 'name' => ' Cacoal'],
                ['id_city' => 7328, 'id_state' => 22, 'name' => ' Calama'],
                ['id_city' => 7329, 'id_state' => 22, 'name' => ' Campo Novo de Rondônia'],
                ['id_city' => 7330, 'id_state' => 22, 'name' => ' Candeias do Jamari'],
                ['id_city' => 7331, 'id_state' => 22, 'name' => ' Castanheiras'],
                ['id_city' => 7332, 'id_state' => 22, 'name' => ' Cerejeiras'],
                ['id_city' => 7333, 'id_state' => 22, 'name' => ' Chupinguaia'],
                ['id_city' => 7334, 'id_state' => 22, 'name' => ' Colorado do Oeste'],
                ['id_city' => 7335, 'id_state' => 22, 'name' => ' Corumbiara'],
                ['id_city' => 7336, 'id_state' => 22, 'name' => ' Costa Marques'],
                ['id_city' => 7337, 'id_state' => 22, 'name' => ' Cujubim'],
                ['id_city' => 7338, 'id_state' => 22, 'name' => ' Espigão do Oeste'],
                ['id_city' => 7339, 'id_state' => 22, 'name' => ' Governador Jorge Teixeira'],
                ['id_city' => 7340, 'id_state' => 22, 'name' => ' Guajará-Mirim'],
                ['id_city' => 7341, 'id_state' => 22, 'name' => ' Jaci Paraná'],
                ['id_city' => 7342, 'id_state' => 22, 'name' => ' Itapuã do Oeste'],
                ['id_city' => 7343, 'id_state' => 22, 'name' => ' Jaru'],
                ['id_city' => 7344, 'id_state' => 22, 'name' => ' Ji-Paraná'],
                ['id_city' => 7345, 'id_state' => 22, 'name' => ' Machadinho D Oeste'],
                ['id_city' => 7346, 'id_state' => 22, 'name' => ' Marco Rondon'],
                ['id_city' => 7347, 'id_state' => 22, 'name' => ' Ministro Andreazza'],
                ['id_city' => 7348, 'id_state' => 22, 'name' => ' Mirante da Serra'],
                ['id_city' => 7349, 'id_state' => 22, 'name' => ' Monte Negro'],
                ['id_city' => 7350, 'id_state' => 22, 'name' => ' Nova Brasilândia D Oeste'],
                ['id_city' => 7351, 'id_state' => 22, 'name' => ' Nova Mamoré'],
                ['id_city' => 7352, 'id_state' => 22, 'name' => ' Nova União']
            ]);
        }
    }