<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities9 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 5436, 'id_state' => 17, 'name' => ' Japecanga'],
                ['id_city' => 5437, 'id_state' => 17, 'name' => ' Jaqueira'],
                ['id_city' => 5438, 'id_state' => 17, 'name' => ' Jataúba'],
                ['id_city' => 5439, 'id_state' => 17, 'name' => ' Jatiúca'],
                ['id_city' => 5440, 'id_state' => 17, 'name' => ' Jatobá'],
                ['id_city' => 5441, 'id_state' => 17, 'name' => ' Jenipapo'],
                ['id_city' => 5442, 'id_state' => 17, 'name' => ' João Alfredo'],
                ['id_city' => 5443, 'id_state' => 17, 'name' => ' Joaquim Nabuco'],
                ['id_city' => 5444, 'id_state' => 17, 'name' => ' José da Costa'],
                ['id_city' => 5445, 'id_state' => 17, 'name' => ' José Mariano'],
                ['id_city' => 5446, 'id_state' => 17, 'name' => ' Juçaral'],
                ['id_city' => 5447, 'id_state' => 17, 'name' => ' Jucati'],
                ['id_city' => 5448, 'id_state' => 17, 'name' => ' Jupi'],
                ['id_city' => 5449, 'id_state' => 17, 'name' => ' Jurema'],
                ['id_city' => 5450, 'id_state' => 17, 'name' => ' Jutaí'],
                ['id_city' => 5451, 'id_state' => 17, 'name' => ' Lagoa'],
                ['id_city' => 5452, 'id_state' => 17, 'name' => ' Lagoa de São José'],
                ['id_city' => 5453, 'id_state' => 17, 'name' => ' Lagoa do Barro'],
                ['id_city' => 5454, 'id_state' => 17, 'name' => ' Lagoa do Carro'],
                ['id_city' => 5455, 'id_state' => 17, 'name' => ' Lagoa do Itaenga'],
                ['id_city' => 5456, 'id_state' => 17, 'name' => ' Lagoa do Ouro'],
                ['id_city' => 5457, 'id_state' => 17, 'name' => ' Lagoa do Souza'],
                ['id_city' => 5458, 'id_state' => 17, 'name' => ' Lagoa dos Gatos'],
                ['id_city' => 5459, 'id_state' => 17, 'name' => ' Lagoa Grande'],
                ['id_city' => 5460, 'id_state' => 17, 'name' => ' Laje de São José'],
                ['id_city' => 5461, 'id_state' => 17, 'name' => ' Laje Grande'],
                ['id_city' => 5462, 'id_state' => 17, 'name' => ' Lajedo'],
                ['id_city' => 5463, 'id_state' => 17, 'name' => ' Lajedo do Cedro'],
                ['id_city' => 5464, 'id_state' => 17, 'name' => ' Limoeiro'],
                ['id_city' => 5465, 'id_state' => 17, 'name' => ' Livramento do Tiúma'],
                ['id_city' => 5466, 'id_state' => 17, 'name' => ' Luanda'],
                ['id_city' => 5467, 'id_state' => 17, 'name' => ' Macaparana'],
                ['id_city' => 5468, 'id_state' => 17, 'name' => ' Machados'],
                ['id_city' => 5469, 'id_state' => 17, 'name' => ' Macujé'],
                ['id_city' => 5470, 'id_state' => 17, 'name' => ' Manari'],
                ['id_city' => 5471, 'id_state' => 17, 'name' => ' Mandacaia'],
                ['id_city' => 5472, 'id_state' => 17, 'name' => ' Mandacaru'],
                ['id_city' => 5473, 'id_state' => 17, 'name' => ' Maniçoba'],
                ['id_city' => 5474, 'id_state' => 17, 'name' => ' Maraial'],
                ['id_city' => 5475, 'id_state' => 17, 'name' => ' Maravilha'],
                ['id_city' => 5476, 'id_state' => 17, 'name' => ' Mimoso'],
                ['id_city' => 5477, 'id_state' => 17, 'name' => ' Miracica'],
                ['id_city' => 5478, 'id_state' => 17, 'name' => ' Mirandiba'],
                ['id_city' => 5479, 'id_state' => 17, 'name' => ' Morais'],
                ['id_city' => 5480, 'id_state' => 17, 'name' => ' Moreilândia'],
                ['id_city' => 5481, 'id_state' => 17, 'name' => ' Moreno'],
                ['id_city' => 5482, 'id_state' => 17, 'name' => ' Moxotó'],
                ['id_city' => 5483, 'id_state' => 17, 'name' => ' Mulungu'],
                ['id_city' => 5484, 'id_state' => 17, 'name' => ' Murupé'],
                ['id_city' => 5485, 'id_state' => 17, 'name' => ' Mutuca'],
                ['id_city' => 5486, 'id_state' => 17, 'name' => ' Nascente'],
                ['id_city' => 5487, 'id_state' => 17, 'name' => ' Nazaré da Mata'],
                ['id_city' => 5488, 'id_state' => 17, 'name' => ' Negras'],
                ['id_city' => 5489, 'id_state' => 17, 'name' => ' Nossa Senhora da Luz'],
                ['id_city' => 5490, 'id_state' => 17, 'name' => ' Nossa Senhora do Carmo'],
                ['id_city' => 5491, 'id_state' => 17, 'name' => ' Nossa Senhora do Ó'],
                ['id_city' => 5492, 'id_state' => 17, 'name' => ' Nova Cruz'],
                ['id_city' => 5493, 'id_state' => 17, 'name' => ' Olho D Água de Dentro'],
                ['id_city' => 5494, 'id_state' => 17, 'name' => ' Olinda'],
                ['id_city' => 5495, 'id_state' => 17, 'name' => ' Oratório'],
                ['id_city' => 5496, 'id_state' => 17, 'name' => ' Ori'],
                ['id_city' => 5497, 'id_state' => 17, 'name' => ' Orobó'],
                ['id_city' => 5498, 'id_state' => 17, 'name' => ' Orocó'],
                ['id_city' => 5499, 'id_state' => 17, 'name' => ' Ouricuri'],
                ['id_city' => 5500, 'id_state' => 17, 'name' => ' Pajeú'],
                ['id_city' => 5501, 'id_state' => 17, 'name' => ' Palmares'],
                ['id_city' => 5502, 'id_state' => 17, 'name' => ' Palmeirina'],
                ['id_city' => 5503, 'id_state' => 17, 'name' => ' Panelas'],
                ['id_city' => 5504, 'id_state' => 17, 'name' => ' Pão de Açúcar'],
                ['id_city' => 5505, 'id_state' => 17, 'name' => ' Pão de Açúcar do Poção'],
                ['id_city' => 5506, 'id_state' => 17, 'name' => ' Papagaio'],
                ['id_city' => 5507, 'id_state' => 17, 'name' => ' Paquevira'],
                ['id_city' => 5508, 'id_state' => 17, 'name' => ' Pará'],
                ['id_city' => 5509, 'id_state' => 17, 'name' => ' Paranatama'],
                ['id_city' => 5510, 'id_state' => 17, 'name' => ' Parnamirim'],
                ['id_city' => 5511, 'id_state' => 17, 'name' => ' Passagem do Tó'],
                ['id_city' => 5512, 'id_state' => 17, 'name' => ' Passira'],
                ['id_city' => 5513, 'id_state' => 17, 'name' => ' Pau Ferro'],
                ['id_city' => 5514, 'id_state' => 17, 'name' => ' Paudalho'],
                ['id_city' => 5515, 'id_state' => 17, 'name' => ' Paulista'],
                ['id_city' => 5516, 'id_state' => 17, 'name' => ' Pedra'],
                ['id_city' => 5517, 'id_state' => 17, 'name' => ' Perpétuo Socorro'],
                ['id_city' => 5518, 'id_state' => 17, 'name' => ' Pesqueira'],
                ['id_city' => 5519, 'id_state' => 17, 'name' => ' Petrolândia'],
                ['id_city' => 5520, 'id_state' => 17, 'name' => ' Petrolina'],
                ['id_city' => 5521, 'id_state' => 17, 'name' => ' Pirituba'],
                ['id_city' => 5522, 'id_state' => 17, 'name' => ' Poção'],
                ['id_city' => 5523, 'id_state' => 17, 'name' => ' Poção de Afrânio'],
                ['id_city' => 5524, 'id_state' => 17, 'name' => ' Poço Comprido'],
                ['id_city' => 5525, 'id_state' => 17, 'name' => ' Poço Fundo'],
                ['id_city' => 5526, 'id_state' => 17, 'name' => ' Pombos'],
                ['id_city' => 5527, 'id_state' => 17, 'name' => ' Pontas de Pedra'],
                ['id_city' => 5528, 'id_state' => 17, 'name' => ' Primavera'],
                ['id_city' => 5529, 'id_state' => 17, 'name' => ' Quipapá'],
                ['id_city' => 5530, 'id_state' => 17, 'name' => ' Quitimbu'],
                ['id_city' => 5531, 'id_state' => 17, 'name' => ' Quixabá'],
                ['id_city' => 5532, 'id_state' => 17, 'name' => ' Rainha Isabel'],
                ['id_city' => 5533, 'id_state' => 17, 'name' => ' Rajada'],
                ['id_city' => 5534, 'id_state' => 17, 'name' => ' Rancharia'],
                ['id_city' => 5535, 'id_state' => 17, 'name' => ' Recife'],
                ['id_city' => 5536, 'id_state' => 17, 'name' => ' Riacho das Almas'],
                ['id_city' => 5537, 'id_state' => 17, 'name' => ' Riacho do Meio'],
                ['id_city' => 5538, 'id_state' => 17, 'name' => ' Riacho Fechado'],
                ['id_city' => 5539, 'id_state' => 17, 'name' => ' Riacho Pequeno'],
                ['id_city' => 5540, 'id_state' => 17, 'name' => ' Ribeirão'],
                ['id_city' => 5541, 'id_state' => 17, 'name' => ' Rio da Barra'],
                ['id_city' => 5542, 'id_state' => 17, 'name' => ' Rio Formoso'],
                ['id_city' => 5543, 'id_state' => 17, 'name' => ' Sairé'],
                ['id_city' => 5544, 'id_state' => 17, 'name' => ' Salgadinho'],
                ['id_city' => 5545, 'id_state' => 17, 'name' => ' Salgueiro'],
                ['id_city' => 5546, 'id_state' => 17, 'name' => ' Saloá'],
                ['id_city' => 5547, 'id_state' => 17, 'name' => ' Salobro'],
                ['id_city' => 5548, 'id_state' => 17, 'name' => ' Sanharó'],
                ['id_city' => 5549, 'id_state' => 17, 'name' => ' Santa Cruz'],
                ['id_city' => 5550, 'id_state' => 17, 'name' => ' Santa Cruz da Baixa Verde'],
                ['id_city' => 5551, 'id_state' => 17, 'name' => ' Santa Cruz do Capibaribe'],
                ['id_city' => 5552, 'id_state' => 17, 'name' => ' Santa Filomena'],
                ['id_city' => 5553, 'id_state' => 17, 'name' => ' Santa Maria da Boa Vista'],
                ['id_city' => 5554, 'id_state' => 17, 'name' => ' Santa Maria do Cambucá'],
                ['id_city' => 5555, 'id_state' => 17, 'name' => ' Santa Rita'],
                ['id_city' => 5556, 'id_state' => 17, 'name' => ' Santa Terezinha'],
                ['id_city' => 5557, 'id_state' => 17, 'name' => ' Santana de São Joaquim'],
                ['id_city' => 5558, 'id_state' => 17, 'name' => ' Santo Agostinho'],
                ['id_city' => 5559, 'id_state' => 17, 'name' => ' Santo Antônio das Queimadas],'
                ['id_city' => 5560, 'id_state' => 17, 'name' => ' Santo Antônio dos Palmares'],
                ['id_city' => 5561, 'id_state' => 17, 'name' => ' São Benedito do Sul'],
                ['id_city' => 5562, 'id_state' => 17, 'name' => ' São Bento do Una'],
                ['id_city' => 5563, 'id_state' => 17, 'name' => ' São Caetano do Navio'],
                ['id_city' => 5564, 'id_state' => 17, 'name' => ' São Caitano'],
                ['id_city' => 5565, 'id_state' => 17, 'name' => ' São Domingos'],
                ['id_city' => 5566, 'id_state' => 17, 'name' => ' São João'],
                ['id_city' => 5567, 'id_state' => 17, 'name' => ' São Joaquim do Monte'],
                ['id_city' => 5568, 'id_state' => 17, 'name' => ' São José'],
                ['id_city' => 5569, 'id_state' => 17, 'name' => ' São José da Coroa Grande'],
                ['id_city' => 5570, 'id_state' => 17, 'name' => ' São José do Belmonte'],
                ['id_city' => 5571, 'id_state' => 17, 'name' => ' São José do Egito'],
                ['id_city' => 5572, 'id_state' => 17, 'name' => ' São Lázaro'],
                ['id_city' => 5573, 'id_state' => 17, 'name' => ' São Lourenço da Mata'],
                ['id_city' => 5574, 'id_state' => 17, 'name' => ' São Pedro'],
                ['id_city' => 5575, 'id_state' => 17, 'name' => ' São Vicente'],
                ['id_city' => 5576, 'id_state' => 17, 'name' => ' São Vicente Ferrer'],
                ['id_city' => 5577, 'id_state' => 17, 'name' => ' Sapucarana'],
                ['id_city' => 5578, 'id_state' => 17, 'name' => ' Saué'],
                ['id_city' => 5579, 'id_state' => 17, 'name' => ' Serra Branca'],
                ['id_city' => 5580, 'id_state' => 17, 'name' => ' Serra do Vento'],
                ['id_city' => 5581, 'id_state' => 17, 'name' => ' Serra Talhada'],
                ['id_city' => 5582, 'id_state' => 17, 'name' => ' Serrita'],
                ['id_city' => 5583, 'id_state' => 17, 'name' => ' Serrolândia'],
                ['id_city' => 5584, 'id_state' => 17, 'name' => ' Sertânia'],
                ['id_city' => 5585, 'id_state' => 17, 'name' => ' Sertãozinho de Baixo'],
                ['id_city' => 5586, 'id_state' => 17, 'name' => ' Siriji'],
                ['id_city' => 5587, 'id_state' => 17, 'name' => ' Sirinhaém'],
                ['id_city' => 5588, 'id_state' => 17, 'name' => ' Sítio dos Nunes'],
                ['id_city' => 5589, 'id_state' => 17, 'name' => ' Solidão'],
                ['id_city' => 5590, 'id_state' => 17, 'name' => ' Surubim'],
                ['id_city' => 5591, 'id_state' => 17, 'name' => ' Tabira'],
                ['id_city' => 5592, 'id_state' => 17, 'name' => ' Tabocas'],
                ['id_city' => 5593, 'id_state' => 17, 'name' => ' Tacaimbó'],
                ['id_city' => 5594, 'id_state' => 17, 'name' => ' Tacaratu'],
                ['id_city' => 5595, 'id_state' => 17, 'name' => ' Tamandaré'],
                ['id_city' => 5596, 'id_state' => 17, 'name' => ' Tamboatá'],
                ['id_city' => 5597, 'id_state' => 17, 'name' => ' Tapiraim'],
                ['id_city' => 5598, 'id_state' => 17, 'name' => ' Taquaritinga do Norte'],
                ['id_city' => 5599, 'id_state' => 17, 'name' => ' Tara'],
                ['id_city' => 5600, 'id_state' => 17, 'name' => ' Tauapiranga'],
                ['id_city' => 5601, 'id_state' => 17, 'name' => ' Tejucupapo'],
                ['id_city' => 5602, 'id_state' => 17, 'name' => ' Terezinha'],
                ['id_city' => 5603, 'id_state' => 17, 'name' => ' Terra Nova'],
                ['id_city' => 5604, 'id_state' => 17, 'name' => ' Timbaúba'],
                ['id_city' => 5605, 'id_state' => 17, 'name' => ' Timorante'],
                ['id_city' => 5606, 'id_state' => 17, 'name' => ' Toritama'],
                ['id_city' => 5607, 'id_state' => 17, 'name' => ' Tracunhaém'],
                ['id_city' => 5608, 'id_state' => 17, 'name' => ' Trapiá'],
                ['id_city' => 5609, 'id_state' => 17, 'name' => ' Três Ladeiras'],
                ['id_city' => 5610, 'id_state' => 17, 'name' => ' Trindade'],
                ['id_city' => 5611, 'id_state' => 17, 'name' => ' Triunfo'],
                ['id_city' => 5612, 'id_state' => 17, 'name' => ' Tupanaci'],
                ['id_city' => 5613, 'id_state' => 17, 'name' => ' Tupanatinga'],
                ['id_city' => 5614, 'id_state' => 17, 'name' => ' Tupaóca'],
                ['id_city' => 5615, 'id_state' => 17, 'name' => ' Tuparetama'],
                ['id_city' => 5616, 'id_state' => 17, 'name' => ' Umãs'],
                ['id_city' => 5617, 'id_state' => 17, 'name' => ' Umburetama'],
                ['id_city' => 5618, 'id_state' => 17, 'name' => ' Upatininga'],
                ['id_city' => 5619, 'id_state' => 17, 'name' => ' Urimama'],
                ['id_city' => 5620, 'id_state' => 17, 'name' => ' Uruçu-Mirim'],
                ['id_city' => 5621, 'id_state' => 17, 'name' => ' Urucubá'],
                ['id_city' => 5622, 'id_state' => 17, 'name' => ' Vasques'],
                ['id_city' => 5623, 'id_state' => 17, 'name' => ' Veneza'],
                ['id_city' => 5624, 'id_state' => 17, 'name' => ' Venturosa'],
                ['id_city' => 5625, 'id_state' => 17, 'name' => ' Verdejante'],
                ['id_city' => 5626, 'id_state' => 17, 'name' => ' Vertente do Lério'],
                ['id_city' => 5627, 'id_state' => 17, 'name' => ' Vertentes'],
                ['id_city' => 5628, 'id_state' => 17, 'name' => ' Vicência'],
                ['id_city' => 5629, 'id_state' => 17, 'name' => ' Vila Nova'],
                ['id_city' => 5630, 'id_state' => 17, 'name' => ' Viração'],
                ['id_city' => 5631, 'id_state' => 17, 'name' => ' Vitória de Santo Antão'],
                ['id_city' => 5632, 'id_state' => 17, 'name' => ' Volta do Moxotó'],
                ['id_city' => 5633, 'id_state' => 17, 'name' => ' Xexéu'],
                ['id_city' => 5634, 'id_state' => 17, 'name' => ' Xucuru'],
                ['id_city' => 5635, 'id_state' => 17, 'name' => ' Zé Gomes'],
                ['id_city' => 5636, 'id_state' => 18, 'name' => ' Acauã'],
                ['id_city' => 5637, 'id_state' => 18, 'name' => ' Agricolândia'],
                ['id_city' => 5638, 'id_state' => 18, 'name' => ' Água Branca'],
                ['id_city' => 5639, 'id_state' => 18, 'name' => ' Alagoinha do Piauí'],
                ['id_city' => 5640, 'id_state' => 18, 'name' => ' Alegrete do Piauí'],
                ['id_city' => 5641, 'id_state' => 18, 'name' => ' Alto Longá'],
                ['id_city' => 5642, 'id_state' => 18, 'name' => ' Altos'],
                ['id_city' => 5643, 'id_state' => 18, 'name' => ' Alvorada do Gurguéia'],
                ['id_city' => 5644, 'id_state' => 18, 'name' => ' Amarante'],
                ['id_city' => 5645, 'id_state' => 18, 'name' => ' Angical do Piauí'],
                ['id_city' => 5646, 'id_state' => 18, 'name' => ' Anísio de Abreu'],
                ['id_city' => 5647, 'id_state' => 18, 'name' => ' Antônio Almeida'],
                ['id_city' => 5648, 'id_state' => 18, 'name' => ' Aroazes'],
                ['id_city' => 5649, 'id_state' => 18, 'name' => ' Arraial'],
                ['id_city' => 5650, 'id_state' => 18, 'name' => ' Assunção do Piauí'],
                ['id_city' => 5651, 'id_state' => 18, 'name' => ' Avelino Lopes'],
                ['id_city' => 5652, 'id_state' => 18, 'name' => ' Baixa Grande do Ribeiro'],
                ['id_city' => 5653, 'id_state' => 18, 'name' => ' Barra D Alcântara'],
                ['id_city' => 5654, 'id_state' => 18, 'name' => ' Barras'],
                ['id_city' => 5655, 'id_state' => 18, 'name' => ' Barreiras do Piauí'],
                ['id_city' => 5656, 'id_state' => 18, 'name' => ' Barro Duro'],
                ['id_city' => 5657, 'id_state' => 18, 'name' => ' Batalha'],
                ['id_city' => 5658, 'id_state' => 18, 'name' => ' Bela Vista do Piauí'],
                ['id_city' => 5659, 'id_state' => 18, 'name' => ' Belém do Piauí'],
                ['id_city' => 5660, 'id_state' => 18, 'name' => ' Beneditinos'],
                ['id_city' => 5661, 'id_state' => 18, 'name' => ' Bertolínia'],
                ['id_city' => 5662, 'id_state' => 18, 'name' => ' Betânia do Piauí'],
                ['id_city' => 5663, 'id_state' => 18, 'name' => ' Boa Hora'],
                ['id_city' => 5664, 'id_state' => 18, 'name' => ' Bocaina'],
                ['id_city' => 5665, 'id_state' => 18, 'name' => ' Bom Jesus'],
                ['id_city' => 5666, 'id_state' => 18, 'name' => ' Bom Princípio do Piauí'],
                ['id_city' => 5667, 'id_state' => 18, 'name' => ' Bonfim do Piauí'],
                ['id_city' => 5668, 'id_state' => 18, 'name' => ' Boqueirão do Piauí'],
                ['id_city' => 5669, 'id_state' => 18, 'name' => ' Brasileira'],
                ['id_city' => 5670, 'id_state' => 18, 'name' => ' Brejo do Piauí'],
                ['id_city' => 5671, 'id_state' => 18, 'name' => ' Buriti dos Lopes'],
                ['id_city' => 5672, 'id_state' => 18, 'name' => ' Buriti dos Montes'],
                ['id_city' => 5673, 'id_state' => 18, 'name' => ' Cabeceiras do Piauí'],
                ['id_city' => 5674, 'id_state' => 18, 'name' => ' Cajazeiras do Piauí'],
                ['id_city' => 5675, 'id_state' => 18, 'name' => ' Cajueiro da Praia'],
                ['id_city' => 5676, 'id_state' => 18, 'name' => ' Caldeirão Grande do Piauí'],
                ['id_city' => 5677, 'id_state' => 18, 'name' => ' Campinas do Piauí'],
                ['id_city' => 5678, 'id_state' => 18, 'name' => ' Campo Alegre do Fidalgo'],
                ['id_city' => 5679, 'id_state' => 18, 'name' => ' Campo Grande do Piauí'],
                ['id_city' => 5680, 'id_state' => 18, 'name' => ' Campo Largo do Piauí'],
                ['id_city' => 5681, 'id_state' => 18, 'name' => ' Campo Maior'],
                ['id_city' => 5682, 'id_state' => 18, 'name' => ' Canavieira'],
                ['id_city' => 5683, 'id_state' => 18, 'name' => ' Canto do Buriti'],
                ['id_city' => 5684, 'id_state' => 18, 'name' => ' Capitão de Campos'],
                ['id_city' => 5685, 'id_state' => 18, 'name' => ' Capitão Gervásio Oliveira'],
                ['id_city' => 5686, 'id_state' => 18, 'name' => ' Caracol'],
                ['id_city' => 5687, 'id_state' => 18, 'name' => ' Caraúbas do Piauí'],
                ['id_city' => 5688, 'id_state' => 18, 'name' => ' Caridade do Piauí'],
                ['id_city' => 5689, 'id_state' => 18, 'name' => ' Castelo do Piauí'],
                ['id_city' => 5690, 'id_state' => 18, 'name' => ' Caxingó'],
                ['id_city' => 5691, 'id_state' => 18, 'name' => ' Cocal'],
                ['id_city' => 5692, 'id_state' => 18, 'name' => ' Cocal de Telha'],
                ['id_city' => 5693, 'id_state' => 18, 'name' => ' Cocal dos Alves'],
                ['id_city' => 5694, 'id_state' => 18, 'name' => ' Coivaras'],
                ['id_city' => 5695, 'id_state' => 18, 'name' => ' Colônia do Gurguéia'],
                ['id_city' => 5696, 'id_state' => 18, 'name' => ' Colônia do Piauí'],
                ['id_city' => 5697, 'id_state' => 18, 'name' => ' Conceição do Canindé'],
                ['id_city' => 5698, 'id_state' => 18, 'name' => ' Coronel José Dias'],
                ['id_city' => 5699, 'id_state' => 18, 'name' => ' Corrente'],
                ['id_city' => 5700, 'id_state' => 18, 'name' => ' Cristalândia do Piauí'],
                ['id_city' => 5701, 'id_state' => 18, 'name' => ' Cristino Castro'],
                ['id_city' => 5702, 'id_state' => 18, 'name' => ' Curimatá'],
                ['id_city' => 5703, 'id_state' => 18, 'name' => ' Currais'],
                ['id_city' => 5704, 'id_state' => 18, 'name' => ' Curral Novo do Piauí'],
                ['id_city' => 5705, 'id_state' => 18, 'name' => ' Curralinhos'],
                ['id_city' => 5706, 'id_state' => 18, 'name' => ' Demerval Lobão'],
                ['id_city' => 5707, 'id_state' => 18, 'name' => ' Dirceu Arcoverde'],
                ['id_city' => 5708, 'id_state' => 18, 'name' => ' Dom Expedito Lopes'],
                ['id_city' => 5709, 'id_state' => 18, 'name' => ' Dom Inocêncio'],
                ['id_city' => 5710, 'id_state' => 18, 'name' => ' Domingos Mourão'],
                ['id_city' => 5711, 'id_state' => 18, 'name' => ' Elesbão Veloso'],
                ['id_city' => 5712, 'id_state' => 18, 'name' => ' Eliseu Martins'],
                ['id_city' => 5713, 'id_state' => 18, 'name' => ' Esperantina'],
                ['id_city' => 5714, 'id_state' => 18, 'name' => ' Fartura do Piauí'],
                ['id_city' => 5715, 'id_state' => 18, 'name' => ' Flores do Piauí'],
                ['id_city' => 5716, 'id_state' => 18, 'name' => ' Floresta do Piauí'],
                ['id_city' => 5717, 'id_state' => 18, 'name' => ' Floriano'],
                ['id_city' => 5718, 'id_state' => 18, 'name' => ' Francinópolis'],
                ['id_city' => 5719, 'id_state' => 18, 'name' => ' Francisco Ayres'],
                ['id_city' => 5720, 'id_state' => 18, 'name' => ' Francisco Macedo'],
                ['id_city' => 5721, 'id_state' => 18, 'name' => ' Francisco Santos'],
                ['id_city' => 5722, 'id_state' => 18, 'name' => ' Fronteiras'],
                ['id_city' => 5723, 'id_state' => 18, 'name' => ' Geminiano'],
                ['id_city' => 5724, 'id_state' => 18, 'name' => ' Gilbués'],
                ['id_city' => 5725, 'id_state' => 18, 'name' => ' Guadalupe'],
                ['id_city' => 5726, 'id_state' => 18, 'name' => ' Guaribas'],
                ['id_city' => 5727, 'id_state' => 18, 'name' => ' Hugo Napoleão'],
                ['id_city' => 5728, 'id_state' => 18, 'name' => ' Ilha Grande'],
                ['id_city' => 5729, 'id_state' => 18, 'name' => ' Inhuma'],
                ['id_city' => 5730, 'id_state' => 18, 'name' => ' Ipiranga do Piauí'],
                ['id_city' => 5731, 'id_state' => 18, 'name' => ' Isaías Coelho'],
                ['id_city' => 5732, 'id_state' => 18, 'name' => ' Itainópolis'],
                ['id_city' => 5733, 'id_state' => 18, 'name' => ' Itaueira'],
                ['id_city' => 5734, 'id_state' => 18, 'name' => ' Jacobina do Piauí'],
                ['id_city' => 5735, 'id_state' => 18, 'name' => ' Jaicós'],
                ['id_city' => 5736, 'id_state' => 18, 'name' => ' Jardim do Mulato'],
                ['id_city' => 5737, 'id_state' => 18, 'name' => ' Jatobá do Piauí'],
                ['id_city' => 5738, 'id_state' => 18, 'name' => ' Jerumenha'],
                ['id_city' => 5739, 'id_state' => 18, 'name' => ' João Costa'],
                ['id_city' => 5740, 'id_state' => 18, 'name' => ' Joaquim Pires'],
                ['id_city' => 5741, 'id_state' => 18, 'name' => ' Joca Marques'],
                ['id_city' => 5742, 'id_state' => 18, 'name' => ' José de Freitas'],
                ['id_city' => 5743, 'id_state' => 18, 'name' => ' Juazeiro do Piauí'],
                ['id_city' => 5744, 'id_state' => 18, 'name' => ' Júlio Borges'],
                ['id_city' => 5745, 'id_state' => 18, 'name' => ' Jurema'],
                ['id_city' => 5746, 'id_state' => 18, 'name' => ' Lagoa Alegre'],
                ['id_city' => 5747, 'id_state' => 18, 'name' => ' Lagoa de São Francisco'],
                ['id_city' => 5748, 'id_state' => 18, 'name' => ' Lagoa do Barro do Piauí'],
                ['id_city' => 5749, 'id_state' => 18, 'name' => ' Lagoa do Piauí'],
                ['id_city' => 5750, 'id_state' => 18, 'name' => ' Lagoa do Sítio'],
                ['id_city' => 5751, 'id_state' => 18, 'name' => ' Lagoinha do Piauí'],
                ['id_city' => 5752, 'id_state' => 18, 'name' => ' Landri Sales'],
                ['id_city' => 5753, 'id_state' => 18, 'name' => ' Luís Correia'],
                ['id_city' => 5754, 'id_state' => 18, 'name' => ' Luzilândia'],
                ['id_city' => 5755, 'id_state' => 18, 'name' => ' Madeiro'],
                ['id_city' => 5756, 'id_state' => 18, 'name' => ' Manoel Emídio'],
                ['id_city' => 5757, 'id_state' => 18, 'name' => ' Marcolândia'],
                ['id_city' => 5758, 'id_state' => 18, 'name' => ' Marcos Parente'],
                ['id_city' => 5759, 'id_state' => 18, 'name' => ' Massapê do Piauí'],
                ['id_city' => 5760, 'id_state' => 18, 'name' => ' Matias Olímpio'],
                ['id_city' => 5761, 'id_state' => 18, 'name' => ' Miguel Alves'],
                ['id_city' => 5762, 'id_state' => 18, 'name' => ' Miguel Leão'],
                ['id_city' => 5763, 'id_state' => 18, 'name' => ' Milton Brandão'],
                ['id_city' => 5764, 'id_state' => 18, 'name' => ' Monsenhor Gil'],
                ['id_city' => 5765, 'id_state' => 18, 'name' => ' Monsenhor Hipólito'],
                ['id_city' => 5766, 'id_state' => 18, 'name' => ' Monte Alegre do Piauí'],
                ['id_city' => 5767, 'id_state' => 18, 'name' => ' Morro Cabeça no Tempo'],
                ['id_city' => 5768, 'id_state' => 18, 'name' => ' Morro do Chapéu do Piauí'],
                ['id_city' => 5769, 'id_state' => 18, 'name' => ' Murici dos Portelas'],
                ['id_city' => 5770, 'id_state' => 18, 'name' => ' Nazaré do Piauí'],
                ['id_city' => 5771, 'id_state' => 18, 'name' => ' Nossa Senhora de Nazaré'],
                ['id_city' => 5772, 'id_state' => 18, 'name' => ' Nossa Senhora dos Remédios'],
                ['id_city' => 5773, 'id_state' => 18, 'name' => ' Nova Santa Rita'],
                ['id_city' => 5774, 'id_state' => 18, 'name' => ' Novo Nilo'],
                ['id_city' => 5775, 'id_state' => 18, 'name' => ' Novo Oriente do Piauí'],
                ['id_city' => 5776, 'id_state' => 18, 'name' => ' Novo Santo Antônio'],
                ['id_city' => 5777, 'id_state' => 18, 'name' => ' Oeiras'],
                ['id_city' => 5778, 'id_state' => 18, 'name' => ' Olho D Água do Piauí'],
                ['id_city' => 5779, 'id_state' => 18, 'name' => ' Padre Marcos'],
                ['id_city' => 5780, 'id_state' => 18, 'name' => ' Paes Landim'],
                ['id_city' => 5781, 'id_state' => 18, 'name' => ' Pajeú do Piauí'],
                ['id_city' => 5782, 'id_state' => 18, 'name' => ' Palmeira do Piauí'],
                ['id_city' => 5783, 'id_state' => 18, 'name' => ' Palmeirais'],
                ['id_city' => 5784, 'id_state' => 18, 'name' => ' Paquetá'],
                ['id_city' => 5785, 'id_state' => 18, 'name' => ' Parnaguá'],
                ['id_city' => 5786, 'id_state' => 18, 'name' => ' Parnaíba'],
                ['id_city' => 5787, 'id_state' => 18, 'name' => ' Passagem Franca do Piauí'],
                ['id_city' => 5788, 'id_state' => 18, 'name' => ' Patos do Piauí'],
                ['id_city' => 5789, 'id_state' => 18, 'name' => ' Paulistana'],
                ['id_city' => 5790, 'id_state' => 18, 'name' => ' Pavussu'],
                ['id_city' => 5791, 'id_state' => 18, 'name' => ' Pedro II'],
                ['id_city' => 5792, 'id_state' => 18, 'name' => ' Pedro Laurentino'],
                ['id_city' => 5793, 'id_state' => 18, 'name' => ' Picos'],
                ['id_city' => 5794, 'id_state' => 18, 'name' => ' Pimenteiras'],
                ['id_city' => 5795, 'id_state' => 18, 'name' => ' Pio IX'],
                ['id_city' => 5796, 'id_state' => 18, 'name' => ' Piracuruca'],
                ['id_city' => 5797, 'id_state' => 18, 'name' => ' Piripiri'],
                ['id_city' => 5798, 'id_state' => 18, 'name' => ' Porto'],
                ['id_city' => 5799, 'id_state' => 18, 'name' => ' Porto Alegre do Piauí'],
                ['id_city' => 5800, 'id_state' => 18, 'name' => ' Prata do Piauí'],
                ['id_city' => 5801, 'id_state' => 18, 'name' => ' Queimada Nova'],
                ['id_city' => 5802, 'id_state' => 18, 'name' => ' Redenção do Gurguéia'],
                ['id_city' => 5803, 'id_state' => 18, 'name' => ' Regeneração'],
                ['id_city' => 5804, 'id_state' => 18, 'name' => ' Riacho Frio'],
                ['id_city' => 5805, 'id_state' => 18, 'name' => ' Ribeira do Piauí'],
                ['id_city' => 5806, 'id_state' => 18, 'name' => ' Ribeiro Gonçalves'],
                ['id_city' => 5807, 'id_state' => 18, 'name' => ' Rio Grande do Piauí'],
                ['id_city' => 5808, 'id_state' => 18, 'name' => ' Santa Cruz do Piauí'],
                ['id_city' => 5809, 'id_state' => 18, 'name' => ' Santa Cruz dos Milagres'],
                ['id_city' => 5810, 'id_state' => 18, 'name' => ' Santa Filomena'],
                ['id_city' => 5811, 'id_state' => 18, 'name' => ' Santa Luz'],
                ['id_city' => 5812, 'id_state' => 18, 'name' => ' Santa Rosa do Piauí'],
                ['id_city' => 5813, 'id_state' => 18, 'name' => ' Santana do Piauí'],
                ['id_city' => 5814, 'id_state' => 18, 'name' => ' Santo Antônio de Lisboa'],
                ['id_city' => 5815, 'id_state' => 18, 'name' => ' Santo Antônio dos Milagres'],
                ['id_city' => 5816, 'id_state' => 18, 'name' => ' Santo Inácio do Piauí'],
                ['id_city' => 5817, 'id_state' => 18, 'name' => ' São Braz do Piauí'],
                ['id_city' => 5818, 'id_state' => 18, 'name' => ' São Félix do Piauí'],
                ['id_city' => 5819, 'id_state' => 18, 'name' => ' São Francisco de Assis do P],iauí'
                ['id_city' => 5820, 'id_state' => 18, 'name' => ' São Francisco do Piauí'],
                ['id_city' => 5821, 'id_state' => 18, 'name' => ' São Gonçalo do Gurguéia'],
                ['id_city' => 5822, 'id_state' => 18, 'name' => ' São Gonçalo do Piauí'],
                ['id_city' => 5823, 'id_state' => 18, 'name' => ' São João da Canabrava'],
                ['id_city' => 5824, 'id_state' => 18, 'name' => ' São João da Fronteira'],
                ['id_city' => 5825, 'id_state' => 18, 'name' => ' São João da Serra'],
                ['id_city' => 5826, 'id_state' => 18, 'name' => ' São João da Varjota'],
                ['id_city' => 5827, 'id_state' => 18, 'name' => ' São João do Arraial'],
                ['id_city' => 5828, 'id_state' => 18, 'name' => ' São João do Piauí'],
                ['id_city' => 5829, 'id_state' => 18, 'name' => ' São José do Divino'],
                ['id_city' => 5830, 'id_state' => 18, 'name' => ' São José do Peixe'],
                ['id_city' => 5831, 'id_state' => 18, 'name' => ' São José do Piauí'],
                ['id_city' => 5832, 'id_state' => 18, 'name' => ' São Julião'],
                ['id_city' => 5833, 'id_state' => 18, 'name' => ' São Lourenço do Piauí'],
                ['id_city' => 5834, 'id_state' => 18, 'name' => ' São Luís do Piauí'],
                ['id_city' => 5835, 'id_state' => 18, 'name' => ' São Miguel da Baixa Grande'],
                ['id_city' => 5836, 'id_state' => 18, 'name' => ' São Miguel do Fidalgo'],
                ['id_city' => 5837, 'id_state' => 18, 'name' => ' São Miguel do Tapuio'],
                ['id_city' => 5838, 'id_state' => 18, 'name' => ' São Pedro do Piauí'],
                ['id_city' => 5839, 'id_state' => 18, 'name' => ' São Raimundo Nonato'],
                ['id_city' => 5840, 'id_state' => 18, 'name' => ' Sebastião Barros'],
                ['id_city' => 5841, 'id_state' => 18, 'name' => ' Sebastião Leal'],
                ['id_city' => 5842, 'id_state' => 18, 'name' => ' Sigefredo Pacheco'],
                ['id_city' => 5843, 'id_state' => 18, 'name' => ' Simões'],
                ['id_city' => 5844, 'id_state' => 18, 'name' => ' Simplício Mendes'],
                ['id_city' => 5845, 'id_state' => 18, 'name' => ' Socorro do Piauí'],
                ['id_city' => 5846, 'id_state' => 18, 'name' => ' Sussuapara'],
                ['id_city' => 5847, 'id_state' => 18, 'name' => ' Tamboril do Piauí'],
                ['id_city' => 5848, 'id_state' => 18, 'name' => ' Tanque do Piauí'],
                ['id_city' => 5849, 'id_state' => 18, 'name' => ' Teresina'],
                ['id_city' => 5850, 'id_state' => 18, 'name' => ' União'],
                ['id_city' => 5851, 'id_state' => 18, 'name' => ' Uruçuí'],
                ['id_city' => 5852, 'id_state' => 18, 'name' => ' Valença do Piauí'],
                ['id_city' => 5853, 'id_state' => 18, 'name' => ' Várzea Branca'],
                ['id_city' => 5854, 'id_state' => 18, 'name' => ' Várzea Grande'],
                ['id_city' => 5855, 'id_state' => 18, 'name' => ' Vera Mendes'],
                ['id_city' => 5856, 'id_state' => 18, 'name' => ' Vila Nova do Piauí'],
                ['id_city' => 5857, 'id_state' => 18, 'name' => ' Wall Ferraz'],
                ['id_city' => 5858, 'id_state' => 16, 'name' => ' Abapã'],
                ['id_city' => 5859, 'id_state' => 16, 'name' => ' Abatiá'],
                ['id_city' => 5860, 'id_state' => 16, 'name' => ' Acampamento das Minas'],
                ['id_city' => 5861, 'id_state' => 16, 'name' => ' Açungui'],
                ['id_city' => 5862, 'id_state' => 16, 'name' => ' Adhemar de Barros'],
                ['id_city' => 5863, 'id_state' => 16, 'name' => ' Adrianópolis'],
                ['id_city' => 5864, 'id_state' => 16, 'name' => ' Agostinho'],
                ['id_city' => 5865, 'id_state' => 16, 'name' => ' Água Azul'],
                ['id_city' => 5866, 'id_state' => 16, 'name' => ' Água Boa'],
                ['id_city' => 5867, 'id_state' => 16, 'name' => ' Água Branca'],
                ['id_city' => 5868, 'id_state' => 16, 'name' => ' Água Mineral'],
                ['id_city' => 5869, 'id_state' => 16, 'name' => ' Água Vermelha'],
                ['id_city' => 5870, 'id_state' => 16, 'name' => ' Agudos do Sul'],
                ['id_city' => 5871, 'id_state' => 16, 'name' => ' Alecrim'],
                ['id_city' => 5872, 'id_state' => 16, 'name' => ' Alexandra'],
                ['id_city' => 5873, 'id_state' => 16, 'name' => ' Almirante Tamandaré'],
                ['id_city' => 5874, 'id_state' => 16, 'name' => ' Altamira do Paraná'],
                ['id_city' => 5875, 'id_state' => 16, 'name' => ' Altaneira'],
                ['id_city' => 5876, 'id_state' => 16, 'name' => ' Alto Alegre'],
                ['id_city' => 5877, 'id_state' => 16, 'name' => ' Alto Alegre do Iguaçu'],
                ['id_city' => 5878, 'id_state' => 16, 'name' => ' Alto Amparo'],
                ['id_city' => 5879, 'id_state' => 16, 'name' => ' Alto do Amparo'],
                ['id_city' => 5880, 'id_state' => 16, 'name' => ' Alto Pará'],
                ['id_city' => 5881, 'id_state' => 16, 'name' => ' Alto Paraná'],
                ['id_city' => 5882, 'id_state' => 16, 'name' => ' Alto Piquiri'],
                ['id_city' => 5883, 'id_state' => 16, 'name' => ' Alto Porã'],
                ['id_city' => 5884, 'id_state' => 16, 'name' => ' Alto Sabiá'],
                ['id_city' => 5885, 'id_state' => 16, 'name' => ' Alto Santa Fé'],
                ['id_city' => 5886, 'id_state' => 16, 'name' => ' Alto São João'],
                ['id_city' => 5887, 'id_state' => 16, 'name' => ' Altônia'],
                ['id_city' => 5888, 'id_state' => 16, 'name' => ' Alvorada do Iguaçu'],
                ['id_city' => 5889, 'id_state' => 16, 'name' => ' Alvorada do Sul'],
                ['id_city' => 5890, 'id_state' => 16, 'name' => ' Amaporã'],
                ['id_city' => 5891, 'id_state' => 16, 'name' => ' Amorinha'],
                ['id_city' => 5892, 'id_state' => 16, 'name' => ' Ampére'],
                ['id_city' => 5893, 'id_state' => 16, 'name' => ' Anahy'],
                ['id_city' => 5894, 'id_state' => 16, 'name' => ' Andirá'],
                ['id_city' => 5895, 'id_state' => 16, 'name' => ' Andorinhas'],
                ['id_city' => 5896, 'id_state' => 16, 'name' => ' Angai'],
                ['id_city' => 5897, 'id_state' => 16, 'name' => ' Ângulo'],
                ['id_city' => 5898, 'id_state' => 16, 'name' => ' Antas'],
                ['id_city' => 5899, 'id_state' => 16, 'name' => ' Antas'],
                ['id_city' => 5900, 'id_state' => 16, 'name' => ' Antonina'],
                ['id_city' => 5901, 'id_state' => 16, 'name' => ' Antônio Brandão de Oliveira],'
                ['id_city' => 5902, 'id_state' => 16, 'name' => ' Antônio Olinto'],
                ['id_city' => 5903, 'id_state' => 16, 'name' => ' Anunciação'],
                ['id_city' => 5904, 'id_state' => 16, 'name' => ' Aparecida do Oeste'],
                ['id_city' => 5905, 'id_state' => 16, 'name' => ' Apiaba'],
                ['id_city' => 5906, 'id_state' => 16, 'name' => ' Apucarana'],
                ['id_city' => 5907, 'id_state' => 16, 'name' => ' Aquidaban'],
                ['id_city' => 5908, 'id_state' => 16, 'name' => ' Aranha'],
                ['id_city' => 5909, 'id_state' => 16, 'name' => ' Arapongas'],
                ['id_city' => 5910, 'id_state' => 16, 'name' => ' Arapoti'],
                ['id_city' => 5911, 'id_state' => 16, 'name' => ' Arapuã'],
                ['id_city' => 5912, 'id_state' => 16, 'name' => ' Arapuan'],
                ['id_city' => 5913, 'id_state' => 16, 'name' => ' Ararapira'],
                ['id_city' => 5914, 'id_state' => 16, 'name' => ' Araruna'],
                ['id_city' => 5915, 'id_state' => 16, 'name' => ' Araucária'],
                ['id_city' => 5916, 'id_state' => 16, 'name' => ' Areia Branca dos Assis'],
                ['id_city' => 5917, 'id_state' => 16, 'name' => ' Areias'],
                ['id_city' => 5918, 'id_state' => 16, 'name' => ' Aricanduva'],
                ['id_city' => 5919, 'id_state' => 16, 'name' => ' Ariranha do Ivaí'],
                ['id_city' => 5920, 'id_state' => 16, 'name' => ' Aroeira'],
                ['id_city' => 5921, 'id_state' => 16, 'name' => ' Arquimedes'],
                ['id_city' => 5922, 'id_state' => 16, 'name' => ' Assaí'],
                ['id_city' => 5923, 'id_state' => 16, 'name' => ' Assis Chateaubriand'],
                ['id_city' => 5924, 'id_state' => 16, 'name' => ' Astorga'],
                ['id_city' => 5925, 'id_state' => 16, 'name' => ' Atalaia'],
                ['id_city' => 5926, 'id_state' => 16, 'name' => ' Aurora do Iguaçu'],
                ['id_city' => 5927, 'id_state' => 16, 'name' => ' Bairro Cachoeira'],
                ['id_city' => 5928, 'id_state' => 16, 'name' => ' Bairro Limoeiro'],
                ['id_city' => 5929, 'id_state' => 16, 'name' => ' Balsa Nova'],
                ['id_city' => 5930, 'id_state' => 16, 'name' => ' Bandeirantes'],
                ['id_city' => 5931, 'id_state' => 16, 'name' => ' Bandeirantes d Oeste'],
                ['id_city' => 5932, 'id_state' => 16, 'name' => ' Banhado'],
                ['id_city' => 5933, 'id_state' => 16, 'name' => ' Barão de Lucena'],
                ['id_city' => 5934, 'id_state' => 16, 'name' => ' Barbosa Ferraz'],
                ['id_city' => 5935, 'id_state' => 16, 'name' => ' Barra Bonita'],
                ['id_city' => 5936, 'id_state' => 16, 'name' => ' Barra Bonita'],
                ['id_city' => 5937, 'id_state' => 16, 'name' => ' Barra do Jacaré'],
                ['id_city' => 5938, 'id_state' => 16, 'name' => ' Barra Grande'],
                ['id_city' => 5939, 'id_state' => 16, 'name' => ' Barra Grande'],
                ['id_city' => 5940, 'id_state' => 16, 'name' => ' Barra Grande'],
                ['id_city' => 5941, 'id_state' => 16, 'name' => ' Barra Santa Salete'],
                ['id_city' => 5942, 'id_state' => 16, 'name' => ' Barracão'],
                ['id_city' => 5943, 'id_state' => 16, 'name' => ' Barreiro'],
                ['id_city' => 5944, 'id_state' => 16, 'name' => ' Barreiros'],
                ['id_city' => 5945, 'id_state' => 16, 'name' => ' Barrinha'],
                ['id_city' => 5946, 'id_state' => 16, 'name' => ' Barro Preto'],
                ['id_city' => 5947, 'id_state' => 16, 'name' => ' Bateias'],
                ['id_city' => 5948, 'id_state' => 16, 'name' => ' Baulândia'],
                ['id_city' => 5949, 'id_state' => 16, 'name' => ' Bela Vista'],
                ['id_city' => 5950, 'id_state' => 16, 'name' => ' Bela Vista da Caroba'],
                ['id_city' => 5951, 'id_state' => 16, 'name' => ' Bela Vista do Ivaí'],
                ['id_city' => 5952, 'id_state' => 16, 'name' => ' Bela Vista do Paraíso'],
                ['id_city' => 5953, 'id_state' => 16, 'name' => ' Bela Vista do Piquiri'],
                ['id_city' => 5954, 'id_state' => 16, 'name' => ' Bela Vista do Tapiracui'],
                ['id_city' => 5955, 'id_state' => 16, 'name' => ' Bentópolis'],
                ['id_city' => 5956, 'id_state' => 16, 'name' => ' Bernardelli'],
                ['id_city' => 5957, 'id_state' => 16, 'name' => ' Betaras'],
                ['id_city' => 5958, 'id_state' => 16, 'name' => ' Bituruna'],
                ['id_city' => 5959, 'id_state' => 16, 'name' => ' Boa Esperança'],
                ['id_city' => 5960, 'id_state' => 16, 'name' => ' Boa Esperança do Iguaçu'],
                ['id_city' => 5961, 'id_state' => 16, 'name' => ' Boa Ventura de São Roque'],
                ['id_city' => 5962, 'id_state' => 16, 'name' => ' Boa Vista'],
                ['id_city' => 5963, 'id_state' => 16, 'name' => ' Boa Vista da Aparecida'],
                ['id_city' => 5964, 'id_state' => 16, 'name' => ' Bocaina'],
                ['id_city' => 5965, 'id_state' => 16, 'name' => ' Bocaiúva do Sul'],
                ['id_city' => 5966, 'id_state' => 16, 'name' => ' Bom Jardim do Sul'],
                ['id_city' => 5967, 'id_state' => 16, 'name' => ' Bom Jesus do Sul'],
                ['id_city' => 5968, 'id_state' => 16, 'name' => ' Bom Progresso'],
                ['id_city' => 5969, 'id_state' => 16, 'name' => ' Bom Retiro'],
                ['id_city' => 5970, 'id_state' => 16, 'name' => ' Bom Sucesso'],
                ['id_city' => 5971, 'id_state' => 16, 'name' => ' Bom Sucesso do Sul'],
                ['id_city' => 5972, 'id_state' => 16, 'name' => ' Borda do Campo'],
                ['id_city' => 5973, 'id_state' => 16, 'name' => ' Borman'],
                ['id_city' => 5974, 'id_state' => 16, 'name' => ' Borrazópolis'],
                ['id_city' => 5975, 'id_state' => 16, 'name' => ' Botuquara'],
                ['id_city' => 5976, 'id_state' => 16, 'name' => ' Bourbonia'],
                ['id_city' => 5977, 'id_state' => 16, 'name' => ' Braganey'],
                ['id_city' => 5978, 'id_state' => 16, 'name' => ' Bragantina'],
                ['id_city' => 5979, 'id_state' => 16, 'name' => ' Brasilândia do Sul'],
                ['id_city' => 5980, 'id_state' => 16, 'name' => ' Bugre'],
                ['id_city' => 5981, 'id_state' => 16, 'name' => ' Bulcão'],
                ['id_city' => 5982, 'id_state' => 16, 'name' => ' Cabrito'],
                ['id_city' => 5983, 'id_state' => 16, 'name' => ' Cacatu'],
                ['id_city' => 5984, 'id_state' => 16, 'name' => ' Cachoeira'],
                ['id_city' => 5985, 'id_state' => 16, 'name' => ' Cachoeira de Cima'],
                ['id_city' => 5986, 'id_state' => 16, 'name' => ' Cachoeira de São José'],
                ['id_city' => 5987, 'id_state' => 16, 'name' => ' Cachoeira do Espírito Santo],'
                ['id_city' => 5988, 'id_state' => 16, 'name' => ' Colônia Cachoeira'],
                ['id_city' => 5989, 'id_state' => 16, 'name' => ' Cachoeirinha'],
                ['id_city' => 5990, 'id_state' => 16, 'name' => ' Cadeadinho'],
                ['id_city' => 5991, 'id_state' => 16, 'name' => ' Caetano Mendes'],
                ['id_city' => 5992, 'id_state' => 16, 'name' => ' Cafeara'],
                ['id_city' => 5993, 'id_state' => 16, 'name' => ' Cafeeiros'],
                ['id_city' => 5994, 'id_state' => 16, 'name' => ' Cafelândia'],
                ['id_city' => 5995, 'id_state' => 16, 'name' => ' Cafezal do Sul'],
                ['id_city' => 5996, 'id_state' => 16, 'name' => ' Caitá'],
                ['id_city' => 5997, 'id_state' => 16, 'name' => ' Califórnia'],
                ['id_city' => 5998, 'id_state' => 16, 'name' => ' Calógeras'],
                ['id_city' => 5999, 'id_state' => 16, 'name' => ' Cambará'],
                ['id_city' => 6000, 'id_state' => 16, 'name' => ' Cambé'],
                ['id_city' => 6001, 'id_state' => 16, 'name' => ' Cambiju'],
                ['id_city' => 6002, 'id_state' => 16, 'name' => ' Cambira'],
                ['id_city' => 6003, 'id_state' => 16, 'name' => ' Campestrinho'],
                ['id_city' => 6004, 'id_state' => 16, 'name' => ' Campina'],
                ['id_city' => 6005, 'id_state' => 16, 'name' => ' Campina da Lagoa'],
                ['id_city' => 6006, 'id_state' => 16, 'name' => ' Campina do Miranguava'],
                ['id_city' => 6007, 'id_state' => 16, 'name' => ' Campina do Simão'],
                ['id_city' => 6008, 'id_state' => 16, 'name' => ' Campina dos Furtados'],
                ['id_city' => 6009, 'id_state' => 16, 'name' => ' Campina Grande do Sul'],
                ['id_city' => 6010, 'id_state' => 16, 'name' => ' Campinas'],
                ['id_city' => 6011, 'id_state' => 16, 'name' => ' Campo Bonito'],
                ['id_city' => 6012, 'id_state' => 16, 'name' => ' Campo do Meio'],
                ['id_city' => 6013, 'id_state' => 16, 'name' => ' Campo do Tenente'],
                ['id_city' => 6014, 'id_state' => 16, 'name' => ' Campo Largo'],
                ['id_city' => 6015, 'id_state' => 16, 'name' => ' Campo Largo da Roseira'],
                ['id_city' => 6016, 'id_state' => 16, 'name' => ' Campo Magro'],
                ['id_city' => 6017, 'id_state' => 16, 'name' => ' Campo Mourão'],
                ['id_city' => 6018, 'id_state' => 16, 'name' => ' Cândido de Abreu'],
                ['id_city' => 6019, 'id_state' => 16, 'name' => ' Candói'],
                ['id_city' => 6020, 'id_state' => 16, 'name' => ' Canela'],
                ['id_city' => 6021, 'id_state' => 16, 'name' => ' Cantagalo'],
                ['id_city' => 6022, 'id_state' => 16, 'name' => ' Canzianópolis'],
                ['id_city' => 6023, 'id_state' => 16, 'name' => ' Capanema'],
                ['id_city' => 6024, 'id_state' => 16, 'name' => ' Capão Alto'],
                ['id_city' => 6025, 'id_state' => 16, 'name' => ' Capão Bonito'],
                ['id_city' => 6026, 'id_state' => 16, 'name' => ' Capão da Lagoa'],
                ['id_city' => 6027, 'id_state' => 16, 'name' => ' Capão Grande'],
                ['id_city' => 6028, 'id_state' => 16, 'name' => ' Capão Rico'],
                ['id_city' => 6029, 'id_state' => 16, 'name' => ' Capitão Leônidas Marques'],
                ['id_city' => 6030, 'id_state' => 16, 'name' => ' Capivara'],
                ['id_city' => 6031, 'id_state' => 16, 'name' => ' Capoeirinha'],
                ['id_city' => 6032, 'id_state' => 16, 'name' => ' Cara Pintado'],
                ['id_city' => 6033, 'id_state' => 16, 'name' => ' Cará-Cará'],
                ['id_city' => 6034, 'id_state' => 16, 'name' => ' Carajá'],
                ['id_city' => 6035, 'id_state' => 16, 'name' => ' Carambeí'],
                ['id_city' => 6036, 'id_state' => 16, 'name' => ' Caramuru'],
                ['id_city' => 6037, 'id_state' => 16, 'name' => ' Caratuva'],
                ['id_city' => 6038, 'id_state' => 16, 'name' => ' Carazinho'],
                ['id_city' => 6039, 'id_state' => 16, 'name' => ' Carbonera'],
                ['id_city' => 6040, 'id_state' => 16, 'name' => ' Carlópolis'],
                ['id_city' => 6041, 'id_state' => 16, 'name' => ' Casa Nova'],
                ['id_city' => 6042, 'id_state' => 16, 'name' => ' Cascatinha'],
                ['id_city' => 6043, 'id_state' => 16, 'name' => ' Cascavel'],
                ['id_city' => 6044, 'id_state' => 16, 'name' => ' Castro'],
                ['id_city' => 6045, 'id_state' => 16, 'name' => ' Catanduvas'],
                ['id_city' => 6046, 'id_state' => 16, 'name' => ' Catanduvas do Sul'],
                ['id_city' => 6047, 'id_state' => 16, 'name' => ' Catarinenses'],
                ['id_city' => 6048, 'id_state' => 16, 'name' => ' Caxambu'],
                ['id_city' => 6049, 'id_state' => 16, 'name' => ' Centenário'],
                ['id_city' => 6050, 'id_state' => 16, 'name' => ' Centenário do Sul'],
                ['id_city' => 6051, 'id_state' => 16, 'name' => ' Central Lupion'],
                ['id_city' => 6052, 'id_state' => 16, 'name' => ' Centralito'],
                ['id_city' => 6053, 'id_state' => 16, 'name' => ' Centro Novo'],
                ['id_city' => 6054, 'id_state' => 16, 'name' => ' Cerne'],
                ['id_city' => 6055, 'id_state' => 16, 'name' => ' Cerrado Grande'],
                ['id_city' => 6056, 'id_state' => 16, 'name' => ' Cerro Azul'],
                ['id_city' => 6057, 'id_state' => 16, 'name' => ' Cerro Velho'],
                ['id_city' => 6058, 'id_state' => 16, 'name' => ' Céu Azul'],
                ['id_city' => 6059, 'id_state' => 16, 'name' => ' Chopinzinho'],
                ['id_city' => 6060, 'id_state' => 16, 'name' => ' Cianorte'],
                ['id_city' => 6061, 'id_state' => 16, 'name' => ' Cidade Gaúcha'],
                ['id_city' => 6062, 'id_state' => 16, 'name' => ' Cintra Pimentel'],
                ['id_city' => 6063, 'id_state' => 16, 'name' => ' Clevelândia'],
                ['id_city' => 6064, 'id_state' => 16, 'name' => ' Coitinho'],
                ['id_city' => 6065, 'id_state' => 16, 'name' => ' Colombo'],
                ['id_city' => 6066, 'id_state' => 16, 'name' => ' Colônia Acioli'],
                ['id_city' => 6067, 'id_state' => 16, 'name' => ' Colônia Castelhanos'],
                ['id_city' => 6068, 'id_state' => 16, 'name' => ' Colônia Castrolânda'],
                ['id_city' => 6069, 'id_state' => 16, 'name' => ' Colônia Centenário'],
                ['id_city' => 6070, 'id_state' => 16, 'name' => ' Colônia Cristina'],
                ['id_city' => 6071, 'id_state' => 16, 'name' => ' Colônia Dom Carlos']
            ]);
        }
    }