<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities13 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 7999, 'id_state' => 21, 'name' => ' Rincão do Cristóvão Pereira'],
                ['id_city' => 8000, 'id_state' => 21, 'name' => ' Rincão do Meio'],
                ['id_city' => 8001, 'id_state' => 21, 'name' => ' Rincão do Segredo'],
                ['id_city' => 8002, 'id_state' => 21, 'name' => ' Rincão Doce'],
                ['id_city' => 8003, 'id_state' => 21, 'name' => ' Rincão dos Kroeff'],
                ['id_city' => 8004, 'id_state' => 21, 'name' => ' Rincão dos Mendes'],
                ['id_city' => 8005, 'id_state' => 21, 'name' => ' Rincão Vermelho'],
                ['id_city' => 8006, 'id_state' => 21, 'name' => ' Rio Azul'],
                ['id_city' => 8007, 'id_state' => 21, 'name' => ' Rio Branco'],
                ['id_city' => 8008, 'id_state' => 21, 'name' => ' Rio da Ilha'],
                ['id_city' => 8009, 'id_state' => 21, 'name' => ' Rio dos Índios'],
                ['id_city' => 8010, 'id_state' => 21, 'name' => ' Rio Grande'],
                ['id_city' => 8011, 'id_state' => 21, 'name' => ' Rio Pardinho'],
                ['id_city' => 8012, 'id_state' => 21, 'name' => ' Rio Pardo'],
                ['id_city' => 8013, 'id_state' => 21, 'name' => ' Rio Telha'],
                ['id_city' => 8014, 'id_state' => 21, 'name' => ' Rio Tigre'],
                ['id_city' => 8015, 'id_state' => 21, 'name' => ' Rio Toldo'],
                ['id_city' => 8016, 'id_state' => 21, 'name' => ' Riozinho'],
                ['id_city' => 8017, 'id_state' => 21, 'name' => ' Roca Sales'],
                ['id_city' => 8018, 'id_state' => 21, 'name' => ' Rodeio Bonito'],
                ['id_city' => 8019, 'id_state' => 21, 'name' => ' Rolador'],
                ['id_city' => 8020, 'id_state' => 21, 'name' => ' Rolante'],
                ['id_city' => 8021, 'id_state' => 21, 'name' => ' Rolantinho da Figueira'],
                ['id_city' => 8022, 'id_state' => 21, 'name' => ' Ronda Alta'],
                ['id_city' => 8023, 'id_state' => 21, 'name' => ' Rondinha'],
                ['id_city' => 8024, 'id_state' => 21, 'name' => ' Roque Gonzales'],
                ['id_city' => 8025, 'id_state' => 21, 'name' => ' Rosário'],
                ['id_city' => 8026, 'id_state' => 21, 'name' => ' Rosário do Sul'],
                ['id_city' => 8027, 'id_state' => 21, 'name' => ' Sagrada Família'],
                ['id_city' => 8028, 'id_state' => 21, 'name' => ' Saicã'],
                ['id_city' => 8029, 'id_state' => 21, 'name' => ' Saldanha Marinho'],
                ['id_city' => 8030, 'id_state' => 21, 'name' => ' Saltinho'],
                ['id_city' => 8031, 'id_state' => 21, 'name' => ' Salto'],
                ['id_city' => 8032, 'id_state' => 21, 'name' => ' Salto do Jacuí'],
                ['id_city' => 8033, 'id_state' => 21, 'name' => ' Salvador das Missões'],
                ['id_city' => 8034, 'id_state' => 21, 'name' => ' Salvador do Sul'],
                ['id_city' => 8035, 'id_state' => 21, 'name' => ' Sananduva'],
                ['id_city' => 8036, 'id_state' => 21, 'name' => ' Sant auta'],
                ['id_city' => 8037, 'id_state' => 21, 'name' => ' Santa Bárbara'],
                ['id_city' => 8038, 'id_state' => 21, 'name' => ' Santa Bárbara do Sul'],
                ['id_city' => 8039, 'id_state' => 21, 'name' => ' Santa Catarina'],
                ['id_city' => 8040, 'id_state' => 21, 'name' => ' Santa Cecília do Sul'],
                ['id_city' => 8041, 'id_state' => 21, 'name' => ' Santa Clara do Ingaí'],
                ['id_city' => 8042, 'id_state' => 21, 'name' => ' Santa Clara do Sul'],
                ['id_city' => 8043, 'id_state' => 21, 'name' => ' Santa Cristina do Pinhal'],
                ['id_city' => 8044, 'id_state' => 21, 'name' => ' Santa Cruz'],
                ['id_city' => 8045, 'id_state' => 21, 'name' => ' Santa Cruz da Concórdia'],
                ['id_city' => 8046, 'id_state' => 21, 'name' => ' Santa Cruz do Sul'],
                ['id_city' => 8047, 'id_state' => 21, 'name' => ' Santa Flora'],
                ['id_city' => 8048, 'id_state' => 21, 'name' => ' Santa Inês'],
                ['id_city' => 8049, 'id_state' => 21, 'name' => ' Santa Izabel do Sul'],
                ['id_city' => 8050, 'id_state' => 21, 'name' => ' Santa Lúcia'],
                ['id_city' => 8051, 'id_state' => 21, 'name' => ' Santa Lúcia do Piaí'],
                ['id_city' => 8052, 'id_state' => 21, 'name' => ' Santa Luíza'],
                ['id_city' => 8053, 'id_state' => 21, 'name' => ' Santa Luzia'],
                ['id_city' => 8054, 'id_state' => 21, 'name' => ' Santa Maria'],
                ['id_city' => 8055, 'id_state' => 21, 'name' => ' Santa Maria do Herval'],
                ['id_city' => 8056, 'id_state' => 21, 'name' => ' Santa Rita do Sul'],
                ['id_city' => 8057, 'id_state' => 21, 'name' => ' Santa Rosa'],
                ['id_city' => 8058, 'id_state' => 21, 'name' => ' Santa Rosa'],
                ['id_city' => 8059, 'id_state' => 21, 'name' => ' Santa Silvana'],
                ['id_city' => 8060, 'id_state' => 21, 'name' => ' Santa Terezinha'],
                ['id_city' => 8061, 'id_state' => 21, 'name' => ' Santa Tereza'],
                ['id_city' => 8062, 'id_state' => 21, 'name' => ' Santa Vitória do Palmar'],
                ['id_city' => 8063, 'id_state' => 21, 'name' => ' Santana'],
                ['id_city' => 8064, 'id_state' => 21, 'name' => ' Santana da Boa Vista'],
                ['id_city' => 8065, 'id_state' => 21, 'name' => ' Santana do Livramento'],
                ['id_city' => 8066, 'id_state' => 21, 'name' => ' Santiago'],
                ['id_city' => 8067, 'id_state' => 21, 'name' => ' Santo Amaro do Sul'],
                ['id_city' => 8068, 'id_state' => 21, 'name' => ' Santo Ângelo'],
                ['id_city' => 8069, 'id_state' => 21, 'name' => ' Santo Antônio'],
                ['id_city' => 8070, 'id_state' => 21, 'name' => ' Santo Antônio da Patrulha'],
                ['id_city' => 8071, 'id_state' => 21, 'name' => ' Santo Antônio das Missões'],
                ['id_city' => 8072, 'id_state' => 21, 'name' => ' Santo Antônio de Castro'],
                ['id_city' => 8073, 'id_state' => 21, 'name' => ' Santo Antônio do Bom Retiro'],
                ['id_city' => 8074, 'id_state' => 21, 'name' => ' Santo Antônio do Palma'],
                ['id_city' => 8075, 'id_state' => 21, 'name' => ' Santo Antônio do Planalto'],
                ['id_city' => 8076, 'id_state' => 21, 'name' => ' Santo Augusto'],
                ['id_city' => 8077, 'id_state' => 21, 'name' => ' Santo Cristo'],
                ['id_city' => 8078, 'id_state' => 21, 'name' => ' Santo Expedito do Sul'],
                ['id_city' => 8079, 'id_state' => 21, 'name' => ' Santo Inácio'],
                ['id_city' => 8080, 'id_state' => 21, 'name' => ' São Bento'],
                ['id_city' => 8081, 'id_state' => 21, 'name' => ' São Bom Jesus'],
                ['id_city' => 8082, 'id_state' => 21, 'name' => ' São Borja'],
                ['id_city' => 8083, 'id_state' => 21, 'name' => ' São Carlos'],
                ['id_city' => 8084, 'id_state' => 21, 'name' => ' São Domingos do Sul'],
                ['id_city' => 8085, 'id_state' => 21, 'name' => ' São Francisco'],
                ['id_city' => 8086, 'id_state' => 21, 'name' => ' São Francisco de Assis'],
                ['id_city' => 8087, 'id_state' => 21, 'name' => ' São Francisco de Paula'],
                ['id_city' => 8088, 'id_state' => 21, 'name' => ' São Gabriel'],
                ['id_city' => 8089, 'id_state' => 21, 'name' => ' São Jerônimo'],
                ['id_city' => 8090, 'id_state' => 21, 'name' => ' São João'],
                ['id_city' => 8091, 'id_state' => 21, 'name' => ' São João Batista'],
                ['id_city' => 8092, 'id_state' => 21, 'name' => ' São João Bosco'],
                ['id_city' => 8093, 'id_state' => 21, 'name' => ' São João da Urtiga'],
                ['id_city' => 8094, 'id_state' => 21, 'name' => ' São João do Polêsine'],
                ['id_city' => 8095, 'id_state' => 21, 'name' => ' São Jorge'],
                ['id_city' => 8096, 'id_state' => 21, 'name' => ' São José'],
                ['id_city' => 8097, 'id_state' => 21, 'name' => ' São José da Glória'],
                ['id_city' => 8098, 'id_state' => 21, 'name' => ' São José das Missões'],
                ['id_city' => 8099, 'id_state' => 21, 'name' => ' São José de Castro'],
                ['id_city' => 8100, 'id_state' => 21, 'name' => ' São José do Centro'],
                ['id_city' => 8101, 'id_state' => 21, 'name' => ' São José do Herval'],
                ['id_city' => 8102, 'id_state' => 21, 'name' => ' São José do Hortêncio'],
                ['id_city' => 8103, 'id_state' => 21, 'name' => ' São José do Inhacorá'],
                ['id_city' => 8104, 'id_state' => 21, 'name' => ' São José do Norte'],
                ['id_city' => 8105, 'id_state' => 21, 'name' => ' São José do Ouro'],
                ['id_city' => 8106, 'id_state' => 21, 'name' => ' São José dos Ausentes'],
                ['id_city' => 8107, 'id_state' => 21, 'name' => ' São Leopoldo'],
                ['id_city' => 8108, 'id_state' => 21, 'name' => ' São Lourenço das Missões'],
                ['id_city' => 8109, 'id_state' => 21, 'name' => ' São Lourenço do Sul'],
                ['id_city' => 8110, 'id_state' => 21, 'name' => ' São Luís Rei'],
                ['id_city' => 8111, 'id_state' => 21, 'name' => ' São Luiz'],
                ['id_city' => 8112, 'id_state' => 21, 'name' => ' São Luiz Gonzaga'],
                ['id_city' => 8113, 'id_state' => 21, 'name' => ' São Manuel'],
                ['id_city' => 8114, 'id_state' => 21, 'name' => ' São Marcos'],
                ['id_city' => 8115, 'id_state' => 21, 'name' => ' São Martinho'],
                ['id_city' => 8116, 'id_state' => 21, 'name' => ' São Martinho da Serra'],
                ['id_city' => 8117, 'id_state' => 21, 'name' => ' São Miguel'],
                ['id_city' => 8118, 'id_state' => 21, 'name' => ' São Miguel das Missões'],
                ['id_city' => 8119, 'id_state' => 21, 'name' => ' São Nicolau'],
                ['id_city' => 8120, 'id_state' => 21, 'name' => ' São Paulo'],
                ['id_city' => 8121, 'id_state' => 21, 'name' => ' São Paulo das Missões'],
                ['id_city' => 8122, 'id_state' => 21, 'name' => ' São Pedro'],
                ['id_city' => 8123, 'id_state' => 21, 'name' => ' São Pedro das Missões'],
                ['id_city' => 8124, 'id_state' => 21, 'name' => ' São Pedro da Serra'],
                ['id_city' => 8125, 'id_state' => 21, 'name' => ' São Pedro do Butiá'],
                ['id_city' => 8126, 'id_state' => 21, 'name' => ' São Pedro do Iraxim'],
                ['id_city' => 8127, 'id_state' => 21, 'name' => ' São Pedro do Sul'],
                ['id_city' => 8128, 'id_state' => 21, 'name' => ' São Roque'],
                ['id_city' => 8129, 'id_state' => 21, 'name' => ' São Sebastião'],
                ['id_city' => 8130, 'id_state' => 21, 'name' => ' São Sebastião do Caí'],
                ['id_city' => 8131, 'id_state' => 21, 'name' => ' São Sepé'],
                ['id_city' => 8132, 'id_state' => 21, 'name' => ' São Simão'],
                ['id_city' => 8133, 'id_state' => 21, 'name' => ' São Valentim'],
                ['id_city' => 8134, 'id_state' => 21, 'name' => ' São Valentim do Sul'],
                ['id_city' => 8135, 'id_state' => 21, 'name' => ' São Valério do Sul'],
                ['id_city' => 8136, 'id_state' => 21, 'name' => ' São Vendelino'],
                ['id_city' => 8137, 'id_state' => 21, 'name' => ' São Vicente do Sul'],
                ['id_city' => 8138, 'id_state' => 21, 'name' => ' Sapiranga'],
                ['id_city' => 8139, 'id_state' => 21, 'name' => ' Sapucaia do Sul'],
                ['id_city' => 8140, 'id_state' => 21, 'name' => ' Sarandi'],
                ['id_city' => 8141, 'id_state' => 21, 'name' => ' Seberi'],
                ['id_city' => 8142, 'id_state' => 21, 'name' => ' Vila Seca'],
                ['id_city' => 8143, 'id_state' => 21, 'name' => ' Sede Aurora'],
                ['id_city' => 8144, 'id_state' => 21, 'name' => ' Sede Nova'],
                ['id_city' => 8145, 'id_state' => 21, 'name' => ' Segredo'],
                ['id_city' => 8146, 'id_state' => 21, 'name' => ' Seival'],
                ['id_city' => 8147, 'id_state' => 21, 'name' => ' Selbach'],
                ['id_city' => 8148, 'id_state' => 21, 'name' => ' Senador Salgado Filho'],
                ['id_city' => 8149, 'id_state' => 21, 'name' => ' Sentinela do Sul'],
                ['id_city' => 8150, 'id_state' => 21, 'name' => ' Serafim Schmidt'],
                ['id_city' => 8151, 'id_state' => 21, 'name' => ' Serafina Corrêa'],
                ['id_city' => 8152, 'id_state' => 21, 'name' => ' Sério'],
                ['id_city' => 8153, 'id_state' => 21, 'name' => ' Serra dos Gregórios'],
                ['id_city' => 8154, 'id_state' => 21, 'name' => ' Serrinha'],
                ['id_city' => 8155, 'id_state' => 21, 'name' => ' Sertão'],
                ['id_city' => 8156, 'id_state' => 21, 'name' => ' Sertão Santana'],
                ['id_city' => 8157, 'id_state' => 21, 'name' => ' Sertãozinho'],
                ['id_city' => 8158, 'id_state' => 21, 'name' => ' Sete de Setembro'],
                ['id_city' => 8159, 'id_state' => 21, 'name' => ' Sete Lagoas'],
                ['id_city' => 8160, 'id_state' => 21, 'name' => ' Severiano de Almeida'],
                ['id_city' => 8161, 'id_state' => 21, 'name' => ' Silva Jardim'],
                ['id_city' => 8162, 'id_state' => 21, 'name' => ' Silveira'],
                ['id_city' => 8163, 'id_state' => 21, 'name' => ' Silveira Martins'],
                ['id_city' => 8164, 'id_state' => 21, 'name' => ' Sinimbu'],
                ['id_city' => 8165, 'id_state' => 21, 'name' => ' Sírio'],
                ['id_city' => 8166, 'id_state' => 21, 'name' => ' Sítio Gabriel'],
                ['id_city' => 8167, 'id_state' => 21, 'name' => ' Sobradinho'],
                ['id_city' => 8168, 'id_state' => 21, 'name' => ' Soledade'],
                ['id_city' => 8169, 'id_state' => 21, 'name' => ' Souza Ramos'],
                ['id_city' => 8170, 'id_state' => 21, 'name' => ' Suspiro'],
                ['id_city' => 8171, 'id_state' => 21, 'name' => ' Tabaí'],
                ['id_city' => 8172, 'id_state' => 21, 'name' => ' Tabajara'],
                ['id_city' => 8173, 'id_state' => 21, 'name' => ' Taim'],
                ['id_city' => 8174, 'id_state' => 21, 'name' => ' Tainhas'],
                ['id_city' => 8175, 'id_state' => 21, 'name' => ' Tamanduá'],
                ['id_city' => 8176, 'id_state' => 21, 'name' => ' Tanque'],
                ['id_city' => 8177, 'id_state' => 21, 'name' => ' Tapejara'],
                ['id_city' => 8178, 'id_state' => 21, 'name' => ' Tapera'],
                ['id_city' => 8179, 'id_state' => 21, 'name' => ' Tapes'],
                ['id_city' => 8180, 'id_state' => 21, 'name' => ' Taquara'],
                ['id_city' => 8181, 'id_state' => 21, 'name' => ' Taquari'],
                ['id_city' => 8182, 'id_state' => 21, 'name' => ' Taquarichim'],
                ['id_city' => 8183, 'id_state' => 21, 'name' => ' Taquaruçu do Sul'],
                ['id_city' => 8184, 'id_state' => 21, 'name' => ' Tavares'],
                ['id_city' => 8185, 'id_state' => 21, 'name' => ' Tenente Portela'],
                ['id_city' => 8186, 'id_state' => 21, 'name' => ' Terra de Areia'],
                ['id_city' => 8187, 'id_state' => 21, 'name' => ' Tesouras'],
                ['id_city' => 8188, 'id_state' => 21, 'name' => ' Teutônia'],
                ['id_city' => 8189, 'id_state' => 21, 'name' => ' Tiaraju'],
                ['id_city' => 8190, 'id_state' => 21, 'name' => ' Timbaúva'],
                ['id_city' => 8191, 'id_state' => 21, 'name' => ' Tiradentes do Sul'],
                ['id_city' => 8192, 'id_state' => 21, 'name' => ' Toropi'],
                ['id_city' => 8193, 'id_state' => 21, 'name' => ' Toroquá'],
                ['id_city' => 8194, 'id_state' => 21, 'name' => ' Torquato Severo'],
                ['id_city' => 8195, 'id_state' => 21, 'name' => ' Torres'],
                ['id_city' => 8196, 'id_state' => 21, 'name' => ' Torrinhas'],
                ['id_city' => 8197, 'id_state' => 21, 'name' => ' Touro Passo'],
                ['id_city' => 8198, 'id_state' => 21, 'name' => ' Tramandaí'],
                ['id_city' => 8199, 'id_state' => 21, 'name' => ' Travesseiro'],
                ['id_city' => 8200, 'id_state' => 21, 'name' => ' Trentin'],
                ['id_city' => 8201, 'id_state' => 21, 'name' => ' Três Arroios'],
                ['id_city' => 8202, 'id_state' => 21, 'name' => ' Três Barras'],
                ['id_city' => 8203, 'id_state' => 21, 'name' => ' Três Cachoeiras'],
                ['id_city' => 8204, 'id_state' => 21, 'name' => ' Três Coroas'],
                ['id_city' => 8205, 'id_state' => 21, 'name' => ' Três de Maio'],
                ['id_city' => 8206, 'id_state' => 21, 'name' => ' Três Forquilhas'],
                ['id_city' => 8207, 'id_state' => 21, 'name' => ' Três Palmeiras'],
                ['id_city' => 8208, 'id_state' => 21, 'name' => ' Três Passos'],
                ['id_city' => 8209, 'id_state' => 21, 'name' => ' Três Vendas'],
                ['id_city' => 8210, 'id_state' => 21, 'name' => ' Trindade do Sul'],
                ['id_city' => 8211, 'id_state' => 21, 'name' => ' Triunfo'],
                ['id_city' => 8212, 'id_state' => 21, 'name' => ' Tronqueiras'],
                ['id_city' => 8213, 'id_state' => 21, 'name' => ' Tucunduva'],
                ['id_city' => 8214, 'id_state' => 21, 'name' => ' Tuiuti'],
                ['id_city' => 8215, 'id_state' => 21, 'name' => ' Tunas'],
                ['id_city' => 8216, 'id_state' => 21, 'name' => ' Túnel Verde'],
                ['id_city' => 8217, 'id_state' => 21, 'name' => ' Tupanci do Sul'],
                ['id_city' => 8218, 'id_state' => 21, 'name' => ' Tupanciretã'],
                ['id_city' => 8219, 'id_state' => 21, 'name' => ' Tupanci'],
                ['id_city' => 8220, 'id_state' => 21, 'name' => ' Tupantuba'],
                ['id_city' => 8221, 'id_state' => 21, 'name' => ' Tuparendi'],
                ['id_city' => 8222, 'id_state' => 21, 'name' => ' Tupi Silveira'],
                ['id_city' => 8223, 'id_state' => 21, 'name' => ' Tupinambá'],
                ['id_city' => 8224, 'id_state' => 21, 'name' => ' Turuçu'],
                ['id_city' => 8225, 'id_state' => 21, 'name' => ' Turvinho'],
                ['id_city' => 8226, 'id_state' => 21, 'name' => ' Ubiretama'],
                ['id_city' => 8227, 'id_state' => 21, 'name' => ' Umbu'],
                ['id_city' => 8228, 'id_state' => 21, 'name' => ' União da Serra'],
                ['id_city' => 8229, 'id_state' => 21, 'name' => ' Unistalda'],
                ['id_city' => 8230, 'id_state' => 21, 'name' => ' Uruguaiana'],
                ['id_city' => 8231, 'id_state' => 21, 'name' => ' Vacacai'],
                ['id_city' => 8232, 'id_state' => 21, 'name' => ' Vacaria'],
                ['id_city' => 8233, 'id_state' => 21, 'name' => ' Valdástico'],
                ['id_city' => 8234, 'id_state' => 21, 'name' => ' Vale do Rio Cai'],
                ['id_city' => 8235, 'id_state' => 21, 'name' => ' Vale do Sol'],
                ['id_city' => 8236, 'id_state' => 21, 'name' => ' Vale Real'],
                ['id_city' => 8237, 'id_state' => 21, 'name' => ' Vale Veneto'],
                ['id_city' => 8238, 'id_state' => 21, 'name' => ' Vale Verde'],
                ['id_city' => 8239, 'id_state' => 21, 'name' => ' Vanini'],
                ['id_city' => 8240, 'id_state' => 21, 'name' => ' Venâncio Aires'],
                ['id_city' => 8241, 'id_state' => 21, 'name' => ' Vera Cruz'],
                ['id_city' => 8242, 'id_state' => 21, 'name' => ' Veranópolis'],
                ['id_city' => 8243, 'id_state' => 21, 'name' => ' Vertentes'],
                ['id_city' => 8244, 'id_state' => 21, 'name' => ' Vespasiano Correa'],
                ['id_city' => 8245, 'id_state' => 21, 'name' => ' Viadutos'],
                ['id_city' => 8246, 'id_state' => 21, 'name' => ' Viamão'],
                ['id_city' => 8247, 'id_state' => 21, 'name' => ' Vicente Dutra'],
                ['id_city' => 8248, 'id_state' => 21, 'name' => ' Victor Graeff'],
                ['id_city' => 8249, 'id_state' => 21, 'name' => ' Vila Bender'],
                ['id_city' => 8250, 'id_state' => 21, 'name' => ' Vila Cruz'],
                ['id_city' => 8251, 'id_state' => 21, 'name' => ' Vila Flores'],
                ['id_city' => 8252, 'id_state' => 21, 'name' => ' Vila Lângaro'],
                ['id_city' => 8253, 'id_state' => 21, 'name' => ' Vila Laranjeira'],
                ['id_city' => 8254, 'id_state' => 21, 'name' => ' Vila Maria'],
                ['id_city' => 8255, 'id_state' => 21, 'name' => ' Vila Nova do Sul'],
                ['id_city' => 8256, 'id_state' => 21, 'name' => ' Vila Rica'],
                ['id_city' => 8257, 'id_state' => 21, 'name' => ' Vila Seca'],
                ['id_city' => 8258, 'id_state' => 21, 'name' => ' Vila Turvo'],
                ['id_city' => 8259, 'id_state' => 21, 'name' => ' Vista Alegre'],
                ['id_city' => 8260, 'id_state' => 21, 'name' => ' Vista Alegre do Prata'],
                ['id_city' => 8261, 'id_state' => 21, 'name' => ' Vista Gaúcha'],
                ['id_city' => 8262, 'id_state' => 21, 'name' => ' Vitória'],
                ['id_city' => 8263, 'id_state' => 21, 'name' => ' Vitória das Missões'],
                ['id_city' => 8264, 'id_state' => 21, 'name' => ' Volta Alegre'],
                ['id_city' => 8265, 'id_state' => 21, 'name' => ' Volta Fechada'],
                ['id_city' => 8266, 'id_state' => 21, 'name' => ' Volta Grande'],
                ['id_city' => 8267, 'id_state' => 21, 'name' => ' Xadrez'],
                ['id_city' => 8268, 'id_state' => 21, 'name' => ' Xangri-Lá'],
                ['id_city' => 8269, 'id_state' => 21, 'name' => ' Novo Xingu'],
                ['id_city' => 8270, 'id_state' => 24, 'name' => ' Abdon Batista'],
                ['id_city' => 8271, 'id_state' => 24, 'name' => ' Abelardo Luz'],
                ['id_city' => 8272, 'id_state' => 24, 'name' => ' Agrolândia'],
                ['id_city' => 8273, 'id_state' => 24, 'name' => ' Agronômica'],
                ['id_city' => 8274, 'id_state' => 24, 'name' => ' Água Doce'],
                ['id_city' => 8275, 'id_state' => 24, 'name' => ' Águas Brancas'],
                ['id_city' => 8276, 'id_state' => 24, 'name' => ' Águas Claras'],
                ['id_city' => 8277, 'id_state' => 24, 'name' => ' Águas de Chapecó'],
                ['id_city' => 8278, 'id_state' => 24, 'name' => ' Águas Frias'],
                ['id_city' => 8279, 'id_state' => 24, 'name' => ' Águas Mornas'],
                ['id_city' => 8280, 'id_state' => 24, 'name' => ' Aguti'],
                ['id_city' => 8281, 'id_state' => 24, 'name' => ' Aiurê'],
                ['id_city' => 8282, 'id_state' => 24, 'name' => ' Alfredo Wagner'],
                ['id_city' => 8283, 'id_state' => 24, 'name' => ' Alto Alegre'],
                ['id_city' => 8284, 'id_state' => 24, 'name' => ' Alto Bela Vista'],
                ['id_city' => 8285, 'id_state' => 24, 'name' => ' Alto da Serra'],
                ['id_city' => 8286, 'id_state' => 24, 'name' => ' Anchieta'],
                ['id_city' => 8287, 'id_state' => 24, 'name' => ' Angelina'],
                ['id_city' => 8288, 'id_state' => 24, 'name' => ' Anita Garibaldi'],
                ['id_city' => 8289, 'id_state' => 24, 'name' => ' Anitápolis'],
                ['id_city' => 8290, 'id_state' => 24, 'name' => ' Anta Gorda'],
                ['id_city' => 8291, 'id_state' => 24, 'name' => ' Antônio Carlos'],
                ['id_city' => 8292, 'id_state' => 24, 'name' => ' Apiúna'],
                ['id_city' => 8293, 'id_state' => 24, 'name' => ' Arabutã'],
                ['id_city' => 8294, 'id_state' => 24, 'name' => ' Araquari'],
                ['id_city' => 8295, 'id_state' => 24, 'name' => ' Araranguá'],
                ['id_city' => 8296, 'id_state' => 24, 'name' => ' Armazém'],
                ['id_city' => 8297, 'id_state' => 24, 'name' => ' Arnópolis'],
                ['id_city' => 8298, 'id_state' => 24, 'name' => ' Arroio Trinta'],
                ['id_city' => 8299, 'id_state' => 24, 'name' => ' Arvoredo'],
                ['id_city' => 8300, 'id_state' => 24, 'name' => ' Ascurra'],
                ['id_city' => 8301, 'id_state' => 24, 'name' => ' Atalanta'],
                ['id_city' => 8302, 'id_state' => 24, 'name' => ' Aterrado Torto'],
                ['id_city' => 8303, 'id_state' => 24, 'name' => ' Aurora'],
                ['id_city' => 8304, 'id_state' => 24, 'name' => ' Azambuja'],
                ['id_city' => 8305, 'id_state' => 24, 'name' => ' Baia Alta'],
                ['id_city' => 8306, 'id_state' => 24, 'name' => ' Balneário Arroio do Silva'],
                ['id_city' => 8307, 'id_state' => 24, 'name' => ' Balneário Barra do Sul'],
                ['id_city' => 8308, 'id_state' => 24, 'name' => ' Balneário Camboriú'],
                ['id_city' => 8309, 'id_state' => 24, 'name' => ' Balneário Gaivota'],
                ['id_city' => 8310, 'id_state' => 24, 'name' => ' Balneário Morro dos Conventos'],
                ['id_city' => 8311, 'id_state' => 24, 'name' => ' Bandeirante'],
                ['id_city' => 8312, 'id_state' => 24, 'name' => ' Barra Bonita'],
                ['id_city' => 8313, 'id_state' => 24, 'name' => ' Barra Clara'],
                ['id_city' => 8314, 'id_state' => 24, 'name' => ' Barra da Lagoa'],
                ['id_city' => 8315, 'id_state' => 24, 'name' => ' Barra da Prata'],
                ['id_city' => 8316, 'id_state' => 24, 'name' => ' Barra Fria'],
                ['id_city' => 8317, 'id_state' => 24, 'name' => ' Barra Grande'],
                ['id_city' => 8318, 'id_state' => 24, 'name' => ' Barra Velha'],
                ['id_city' => 8319, 'id_state' => 24, 'name' => ' Barreiros'],
                ['id_city' => 8320, 'id_state' => 24, 'name' => ' Barro Branco'],
                ['id_city' => 8321, 'id_state' => 24, 'name' => ' Bateias de Baixo'],
                ['id_city' => 8322, 'id_state' => 24, 'name' => ' Bela Vista'],
                ['id_city' => 8323, 'id_state' => 24, 'name' => ' Bela Vista do Sul'],
                ['id_city' => 8324, 'id_state' => 24, 'name' => ' Bela Vista do Toldo'],
                ['id_city' => 8325, 'id_state' => 24, 'name' => ' Belmonte'],
                ['id_city' => 8326, 'id_state' => 24, 'name' => ' Benedito Novo'],
                ['id_city' => 8327, 'id_state' => 24, 'name' => ' Biguaçu'],
                ['id_city' => 8328, 'id_state' => 24, 'name' => ' Blumenau'],
                ['id_city' => 8329, 'id_state' => 24, 'name' => ' Bocaína do Sul'],
                ['id_city' => 8330, 'id_state' => 24, 'name' => ' Boiteuxburgo'],
                ['id_city' => 8331, 'id_state' => 24, 'name' => ' Bom Jardim da Serra'],
                ['id_city' => 8332, 'id_state' => 24, 'name' => ' Bom Jesus'],
                ['id_city' => 8333, 'id_state' => 24, 'name' => ' Bom Jesus do Oeste'],
                ['id_city' => 8334, 'id_state' => 24, 'name' => ' Bom Retiro'],
                ['id_city' => 8335, 'id_state' => 24, 'name' => ' Bom Sucesso'],
                ['id_city' => 8336, 'id_state' => 24, 'name' => ' Bombinhas'],
                ['id_city' => 8337, 'id_state' => 24, 'name' => ' Botuverá'],
                ['id_city' => 8338, 'id_state' => 24, 'name' => ' Braço do Norte'],
                ['id_city' => 8339, 'id_state' => 24, 'name' => ' Braço do Trombudo'],
                ['id_city' => 8340, 'id_state' => 24, 'name' => ' Brunópolis'],
                ['id_city' => 8341, 'id_state' => 24, 'name' => ' Brusque'],
                ['id_city' => 8342, 'id_state' => 24, 'name' => ' Caçador'],
                ['id_city' => 8343, 'id_state' => 24, 'name' => ' Cachoeira de Fátima'],
                ['id_city' => 8344, 'id_state' => 24, 'name' => ' Cachoeira do Bom Jesus'],
                ['id_city' => 8345, 'id_state' => 24, 'name' => ' Caibi'],
                ['id_city' => 8346, 'id_state' => 24, 'name' => ' Calmon'],
                ['id_city' => 8347, 'id_state' => 24, 'name' => ' Camboriú'],
                ['id_city' => 8348, 'id_state' => 24, 'name' => ' Cambuinzal'],
                ['id_city' => 8349, 'id_state' => 24, 'name' => ' Campeche'],
                ['id_city' => 8350, 'id_state' => 24, 'name' => ' Campinas'],
                ['id_city' => 8351, 'id_state' => 24, 'name' => ' Campo Alegre'],
                ['id_city' => 8352, 'id_state' => 24, 'name' => ' Campo Belo do Sul'],
                ['id_city' => 8353, 'id_state' => 24, 'name' => ' Campo Erê'],
                ['id_city' => 8354, 'id_state' => 24, 'name' => ' Campos Novos'],
                ['id_city' => 8355, 'id_state' => 24, 'name' => ' Canasvieiras'],
                ['id_city' => 8356, 'id_state' => 24, 'name' => ' Canelinha'],
                ['id_city' => 8357, 'id_state' => 24, 'name' => ' Canoas'],
                ['id_city' => 8358, 'id_state' => 24, 'name' => ' Canoinhas'],
                ['id_city' => 8359, 'id_state' => 24, 'name' => ' Capão Alto'],
                ['id_city' => 8360, 'id_state' => 24, 'name' => ' Capinzal'],
                ['id_city' => 8361, 'id_state' => 24, 'name' => ' Capivari de Baixo'],
                ['id_city' => 8362, 'id_state' => 24, 'name' => ' Caraíba'],
                ['id_city' => 8363, 'id_state' => 24, 'name' => ' Catanduvas'],
                ['id_city' => 8364, 'id_state' => 24, 'name' => ' Catuíra'],
                ['id_city' => 8365, 'id_state' => 24, 'name' => ' Caxambu do Sul'],
                ['id_city' => 8366, 'id_state' => 24, 'name' => ' Cedro Alto'],
                ['id_city' => 8367, 'id_state' => 24, 'name' => ' Celso Ramos'],
                ['id_city' => 8368, 'id_state' => 24, 'name' => ' Cerro Negro'],
                ['id_city' => 8369, 'id_state' => 24, 'name' => ' Chapadão do Lageado'],
                ['id_city' => 8370, 'id_state' => 24, 'name' => ' Chapecó'],
                ['id_city' => 8371, 'id_state' => 24, 'name' => ' Claraíba'],
                ['id_city' => 8372, 'id_state' => 24, 'name' => ' Cocal do Sul'],
                ['id_city' => 8373, 'id_state' => 24, 'name' => ' Colônia Santa Tereza'],
                ['id_city' => 8374, 'id_state' => 24, 'name' => ' Concórdia'],
                ['id_city' => 8375, 'id_state' => 24, 'name' => ' Cordilheira Alta'],
                ['id_city' => 8376, 'id_state' => 24, 'name' => ' Coronel Freitas'],
                ['id_city' => 8377, 'id_state' => 24, 'name' => ' Coronel Martins'],
                ['id_city' => 8378, 'id_state' => 24, 'name' => ' Correia Pinto'],
                ['id_city' => 8379, 'id_state' => 24, 'name' => ' Corupá'],
                ['id_city' => 8380, 'id_state' => 24, 'name' => ' Criciúma'],
                ['id_city' => 8381, 'id_state' => 24, 'name' => ' Cunha Porã'],
                ['id_city' => 8382, 'id_state' => 24, 'name' => ' Cunhataí'],
                ['id_city' => 8383, 'id_state' => 24, 'name' => ' Curitibanos'],
                ['id_city' => 8384, 'id_state' => 24, 'name' => ' Dal Pai'],
                ['id_city' => 8385, 'id_state' => 24, 'name' => ' Dalbérgia'],
                ['id_city' => 8386, 'id_state' => 24, 'name' => ' Descanso'],
                ['id_city' => 8387, 'id_state' => 24, 'name' => ' Dionísio Cerqueira'],
                ['id_city' => 8388, 'id_state' => 24, 'name' => ' Dona Emma'],
                ['id_city' => 8389, 'id_state' => 24, 'name' => ' Doutor Pedrinho'],
                ['id_city' => 8390, 'id_state' => 24, 'name' => ' Engenho Velho'],
                ['id_city' => 8391, 'id_state' => 24, 'name' => ' Enseada de Brito'],
                ['id_city' => 8392, 'id_state' => 24, 'name' => ' Entre Rios'],
                ['id_city' => 8393, 'id_state' => 24, 'name' => ' Ermo'],
                ['id_city' => 8394, 'id_state' => 24, 'name' => ' Erval Velho'],
                ['id_city' => 8395, 'id_state' => 24, 'name' => ' Espinilho'],
                ['id_city' => 8396, 'id_state' => 24, 'name' => ' Estação Cocal'],
                ['id_city' => 8397, 'id_state' => 24, 'name' => ' Faxinal dos Guedes'],
                ['id_city' => 8398, 'id_state' => 24, 'name' => ' Fazenda Zandavalli'],
                ['id_city' => 8399, 'id_state' => 24, 'name' => ' Felipe Schmidt'],
                ['id_city' => 8400, 'id_state' => 24, 'name' => ' Figueira'],
                ['id_city' => 8401, 'id_state' => 24, 'name' => ' Flor do Sertão'],
                ['id_city' => 8402, 'id_state' => 24, 'name' => ' Florianópolis'],
                ['id_city' => 8403, 'id_state' => 24, 'name' => ' Formosa do Sul'],
                ['id_city' => 8404, 'id_state' => 24, 'name' => ' Forquilhinha'],
                ['id_city' => 8405, 'id_state' => 24, 'name' => ' Fragosos'],
                ['id_city' => 8406, 'id_state' => 24, 'name' => ' Fraiburgo'],
                ['id_city' => 8407, 'id_state' => 24, 'name' => ' Frederico Wastner'],
                ['id_city' => 8408, 'id_state' => 24, 'name' => ' Frei Rogério'],
                ['id_city' => 8409, 'id_state' => 24, 'name' => ' Galvão'],
                ['id_city' => 8410, 'id_state' => 24, 'name' => ' Garcia'],
                ['id_city' => 8411, 'id_state' => 24, 'name' => ' Garopaba'],
                ['id_city' => 8412, 'id_state' => 24, 'name' => ' Garuva'],
                ['id_city' => 8413, 'id_state' => 24, 'name' => ' Gaspar'],
                ['id_city' => 8414, 'id_state' => 24, 'name' => ' Goio-En'],
                ['id_city' => 8415, 'id_state' => 24, 'name' => ' Governador Celso Ramos'],
                ['id_city' => 8416, 'id_state' => 24, 'name' => ' Grão Pará'],
                ['id_city' => 8417, 'id_state' => 24, 'name' => ' Grápia'],
                ['id_city' => 8418, 'id_state' => 24, 'name' => ' Gravatal'],
                ['id_city' => 8419, 'id_state' => 24, 'name' => ' Guabiruba'],
                ['id_city' => 8420, 'id_state' => 24, 'name' => ' Guaporanga'],
                ['id_city' => 8421, 'id_state' => 24, 'name' => ' Guaraciaba'],
                ['id_city' => 8422, 'id_state' => 24, 'name' => ' Guaramirim'],
                ['id_city' => 8423, 'id_state' => 24, 'name' => ' Guarujá do Sul'],
                ['id_city' => 8424, 'id_state' => 24, 'name' => ' Guatá'],
                ['id_city' => 8425, 'id_state' => 24, 'name' => ' Guatambú'],
                ['id_city' => 8426, 'id_state' => 24, 'name' => ' Hercílio Luz'],
                ['id_city' => 8427, 'id_state' => 24, 'name' => ' Herciliópolis'],
                ['id_city' => 8428, 'id_state' => 24, 'name' => ' Herval D Oeste'],
                ['id_city' => 8429, 'id_state' => 24, 'name' => ' Ibiam'],
                ['id_city' => 8430, 'id_state' => 24, 'name' => ' Ibicaré'],
                ['id_city' => 8431, 'id_state' => 24, 'name' => ' Ibicuí'],
                ['id_city' => 8432, 'id_state' => 24, 'name' => ' Ibirama'],
                ['id_city' => 8433, 'id_state' => 24, 'name' => ' Içara'],
                ['id_city' => 8434, 'id_state' => 24, 'name' => ' Ilhota'],
                ['id_city' => 8435, 'id_state' => 24, 'name' => ' Imaruí'],
                ['id_city' => 8436, 'id_state' => 24, 'name' => ' Imbituba'],
                ['id_city' => 8437, 'id_state' => 24, 'name' => ' Imbuia'],
                ['id_city' => 8438, 'id_state' => 24, 'name' => ' Indaial'],
                ['id_city' => 8439, 'id_state' => 24, 'name' => ' Índios'],
                ['id_city' => 8440, 'id_state' => 24, 'name' => ' Ingleses do Rio Vermelho'],
                ['id_city' => 8441, 'id_state' => 24, 'name' => ' Invernada'],
                ['id_city' => 8442, 'id_state' => 24, 'name' => ' Iomerê'],
                ['id_city' => 8443, 'id_state' => 24, 'name' => ' Ipira'],
                ['id_city' => 8444, 'id_state' => 24, 'name' => ' Ipoméia'],
                ['id_city' => 8445, 'id_state' => 24, 'name' => ' Iporã do Oeste'],
                ['id_city' => 8446, 'id_state' => 24, 'name' => ' Ipuaçu'],
                ['id_city' => 8447, 'id_state' => 24, 'name' => ' Ipumirim'],
                ['id_city' => 8448, 'id_state' => 24, 'name' => ' Iraceminha'],
                ['id_city' => 8449, 'id_state' => 24, 'name' => ' Irakitan'],
                ['id_city' => 8450, 'id_state' => 24, 'name' => ' Irani'],
                ['id_city' => 8451, 'id_state' => 24, 'name' => ' Iraputã'],
                ['id_city' => 8452, 'id_state' => 24, 'name' => ' Irati'],
                ['id_city' => 8453, 'id_state' => 24, 'name' => ' Irineópolis'],
                ['id_city' => 8454, 'id_state' => 24, 'name' => ' Itá'],
                ['id_city' => 8455, 'id_state' => 24, 'name' => ' Itaió'],
                ['id_city' => 8456, 'id_state' => 24, 'name' => ' Itaiópolis'],
                ['id_city' => 8457, 'id_state' => 24, 'name' => ' Itajaí'],
                ['id_city' => 8458, 'id_state' => 24, 'name' => ' Itajubá'],
                ['id_city' => 8459, 'id_state' => 24, 'name' => ' Itapema'],
                ['id_city' => 8460, 'id_state' => 24, 'name' => ' Itapiranga'],
                ['id_city' => 8461, 'id_state' => 24, 'name' => ' Itapoá'],
                ['id_city' => 8462, 'id_state' => 24, 'name' => ' Itapocu'],
                ['id_city' => 8463, 'id_state' => 24, 'name' => ' Itoupava'],
                ['id_city' => 8464, 'id_state' => 24, 'name' => ' Ituporanga'],
                ['id_city' => 8465, 'id_state' => 24, 'name' => ' Jaborá'],
                ['id_city' => 8466, 'id_state' => 24, 'name' => ' Jacinto Machado'],
                ['id_city' => 8467, 'id_state' => 24, 'name' => ' Jaguaruna'],
                ['id_city' => 8468, 'id_state' => 24, 'name' => ' Jaraguá do Sul'],
                ['id_city' => 8469, 'id_state' => 24, 'name' => ' Jardinópolis'],
                ['id_city' => 8470, 'id_state' => 24, 'name' => ' Joaçaba'],
                ['id_city' => 8471, 'id_state' => 24, 'name' => ' Joinville'],
                ['id_city' => 8472, 'id_state' => 24, 'name' => ' José Boiteux'],
                ['id_city' => 8473, 'id_state' => 24, 'name' => ' Jupiá'],
                ['id_city' => 8474, 'id_state' => 24, 'name' => ' Lacerdópolis'],
                ['id_city' => 8475, 'id_state' => 24, 'name' => ' Lages'],
                ['id_city' => 8476, 'id_state' => 24, 'name' => ' Lagoa'],
                ['id_city' => 8477, 'id_state' => 24, 'name' => ' Lagoa da Estiva'],
                ['id_city' => 8478, 'id_state' => 24, 'name' => ' Laguna'],
                ['id_city' => 8479, 'id_state' => 24, 'name' => ' Lajeado Grande'],
                ['id_city' => 8480, 'id_state' => 24, 'name' => ' Laurentino'],
                ['id_city' => 8481, 'id_state' => 24, 'name' => ' Lauro Müller'],
                ['id_city' => 8482, 'id_state' => 24, 'name' => ' Leão'],
                ['id_city' => 8483, 'id_state' => 24, 'name' => ' Lebon Régis'],
                ['id_city' => 8484, 'id_state' => 24, 'name' => ' Leoberto Leal'],
                ['id_city' => 8485, 'id_state' => 24, 'name' => ' Lindóia do Sul'],
                ['id_city' => 8486, 'id_state' => 24, 'name' => ' Linha das Palmeiras'],
                ['id_city' => 8487, 'id_state' => 24, 'name' => ' Lontras'],
                ['id_city' => 8488, 'id_state' => 24, 'name' => ' Lourdes'],
                ['id_city' => 8489, 'id_state' => 24, 'name' => ' Luiz Alves'],
                ['id_city' => 8490, 'id_state' => 24, 'name' => ' Luzerna'],
                ['id_city' => 8491, 'id_state' => 24, 'name' => ' Machados'],
                ['id_city' => 8492, 'id_state' => 24, 'name' => ' Macieira'],
                ['id_city' => 8493, 'id_state' => 24, 'name' => ' Mafra'],
                ['id_city' => 8494, 'id_state' => 24, 'name' => ' Major Gercino'],
                ['id_city' => 8495, 'id_state' => 24, 'name' => ' Major Vieira'],
                ['id_city' => 8496, 'id_state' => 24, 'name' => ' Maracajá'],
                ['id_city' => 8497, 'id_state' => 24, 'name' => ' Marari'],
                ['id_city' => 8498, 'id_state' => 24, 'name' => ' Maratá'],
                ['id_city' => 8499, 'id_state' => 24, 'name' => ' Maravilha'],
                ['id_city' => 8500, 'id_state' => 24, 'name' => ' Marcílio Dias'],
                ['id_city' => 8501, 'id_state' => 24, 'name' => ' Marechal Bormann'],
                ['id_city' => 8502, 'id_state' => 24, 'name' => ' Marema'],
                ['id_city' => 8503, 'id_state' => 24, 'name' => ' Mariflor'],
                ['id_city' => 8504, 'id_state' => 24, 'name' => ' Marombas'],
                ['id_city' => 8505, 'id_state' => 24, 'name' => ' Marombas Bossardi'],
                ['id_city' => 8506, 'id_state' => 24, 'name' => ' Massaranduba'],
                ['id_city' => 8507, 'id_state' => 24, 'name' => ' Matos Costa'],
                ['id_city' => 8508, 'id_state' => 24, 'name' => ' Meleiro'],
                ['id_city' => 8509, 'id_state' => 24, 'name' => ' Mirador'],
                ['id_city' => 8510, 'id_state' => 24, 'name' => ' Mirim'],
                ['id_city' => 8511, 'id_state' => 24, 'name' => ' Mirim Doce'],
                ['id_city' => 8512, 'id_state' => 24, 'name' => ' Modelo'],
                ['id_city' => 8513, 'id_state' => 24, 'name' => ' Mondaí'],
                ['id_city' => 8514, 'id_state' => 24, 'name' => ' Monte Alegre'],
                ['id_city' => 8515, 'id_state' => 24, 'name' => ' Monte Carlo'],
                ['id_city' => 8516, 'id_state' => 24, 'name' => ' Monte Castelo'],
                ['id_city' => 8517, 'id_state' => 24, 'name' => ' Morro Chato'],
                ['id_city' => 8518, 'id_state' => 24, 'name' => ' Morro da Fumaça'],
                ['id_city' => 8519, 'id_state' => 24, 'name' => ' Morro Grande'],
                ['id_city' => 8520, 'id_state' => 24, 'name' => ' Navegantes'],
                ['id_city' => 8521, 'id_state' => 24, 'name' => ' Nossa Senhora de Caravaggio'],
                ['id_city' => 8522, 'id_state' => 24, 'name' => ' Nova Cultura'],
                ['id_city' => 8523, 'id_state' => 24, 'name' => ' Nova Erechim'],
                ['id_city' => 8524, 'id_state' => 24, 'name' => ' Nova Guarita'],
                ['id_city' => 8525, 'id_state' => 24, 'name' => ' Nova Itaberaba'],
                ['id_city' => 8526, 'id_state' => 24, 'name' => ' Nova Petrópolis'],
                ['id_city' => 8527, 'id_state' => 24, 'name' => ' Nova Teutônia'],
                ['id_city' => 8528, 'id_state' => 24, 'name' => ' Nova Trento'],
                ['id_city' => 8529, 'id_state' => 24, 'name' => ' Nova Veneza'],
                ['id_city' => 8530, 'id_state' => 24, 'name' => ' Novo Horizonte'],
                ['id_city' => 8531, 'id_state' => 24, 'name' => ' Orleans'],
                ['id_city' => 8532, 'id_state' => 24, 'name' => ' Otacílio Costa'],
                ['id_city' => 8533, 'id_state' => 24, 'name' => ' Ouro'],
                ['id_city' => 8534, 'id_state' => 24, 'name' => ' Ouro Verde'],
                ['id_city' => 8535, 'id_state' => 24, 'name' => ' Paial'],
                ['id_city' => 8536, 'id_state' => 24, 'name' => ' Painel'],
                ['id_city' => 8537, 'id_state' => 24, 'name' => ' Palhoça'],
                ['id_city' => 8538, 'id_state' => 24, 'name' => ' Palma Sola'],
                ['id_city' => 8539, 'id_state' => 24, 'name' => ' Palmeira'],
                ['id_city' => 8540, 'id_state' => 24, 'name' => ' Palmitos'],
                ['id_city' => 8541, 'id_state' => 24, 'name' => ' Pântano do Sul'],
                ['id_city' => 8542, 'id_state' => 24, 'name' => ' Papanduva'],
                ['id_city' => 8543, 'id_state' => 24, 'name' => ' Paraíso'],
                ['id_city' => 8544, 'id_state' => 24, 'name' => ' Passo de Torres'],
                ['id_city' => 8545, 'id_state' => 24, 'name' => ' Passo Manso'],
                ['id_city' => 8546, 'id_state' => 24, 'name' => ' Passos Maia'],
                ['id_city' => 8547, 'id_state' => 24, 'name' => ' Paula Pereira'],
                ['id_city' => 8548, 'id_state' => 24, 'name' => ' Paulo Lopes'],
                ['id_city' => 8549, 'id_state' => 24, 'name' => ' Pedras Grandes'],
                ['id_city' => 8550, 'id_state' => 24, 'name' => ' Penha'],
                ['id_city' => 8551, 'id_state' => 24, 'name' => ' Pericó'],
                ['id_city' => 8552, 'id_state' => 24, 'name' => ' Peritiba'],
                ['id_city' => 8553, 'id_state' => 24, 'name' => ' Pescaria Brava'],
                ['id_city' => 8554, 'id_state' => 24, 'name' => ' Petrolândia'],
                ['id_city' => 8555, 'id_state' => 24, 'name' => ' Balneário Piçarras'],
                ['id_city' => 8556, 'id_state' => 24, 'name' => ' Pindotiba'],
                ['id_city' => 8557, 'id_state' => 24, 'name' => ' Pinhalzinho'],
                ['id_city' => 8558, 'id_state' => 24, 'name' => ' Pinheiral'],
                ['id_city' => 8559, 'id_state' => 24, 'name' => ' Pinheiro Preto'],
                ['id_city' => 8560, 'id_state' => 24, 'name' => ' Pinheiros'],
                ['id_city' => 8561, 'id_state' => 24, 'name' => ' Pirabeiraba'],
                ['id_city' => 8562, 'id_state' => 24, 'name' => ' Piratuba'],
                ['id_city' => 8563, 'id_state' => 24, 'name' => ' Planalto'],
                ['id_city' => 8564, 'id_state' => 24, 'name' => ' Planalto Alegre'],
                ['id_city' => 8565, 'id_state' => 24, 'name' => ' Poço Preto'],
                ['id_city' => 8566, 'id_state' => 24, 'name' => ' Pomerode'],
                ['id_city' => 8567, 'id_state' => 24, 'name' => ' Ponte Alta'],
                ['id_city' => 8568, 'id_state' => 24, 'name' => ' Ponte Alta do Norte'],
                ['id_city' => 8569, 'id_state' => 24, 'name' => ' Ponte Serrada'],
                ['id_city' => 8570, 'id_state' => 24, 'name' => ' Porto Belo'],
                ['id_city' => 8571, 'id_state' => 24, 'name' => ' Porto União'],
                ['id_city' => 8572, 'id_state' => 24, 'name' => ' Pouso Redondo'],
                ['id_city' => 8573, 'id_state' => 24, 'name' => ' Praia Grande'],
                ['id_city' => 8574, 'id_state' => 24, 'name' => ' Prata'],
                ['id_city' => 8575, 'id_state' => 24, 'name' => ' Presidente Castelo Branco'],
                ['id_city' => 8576, 'id_state' => 24, 'name' => ' Presidente Getúlio'],
                ['id_city' => 8577, 'id_state' => 24, 'name' => ' Presidente Juscelino'],
                ['id_city' => 8578, 'id_state' => 24, 'name' => ' Presidente Kennedy'],
                ['id_city' => 8579, 'id_state' => 24, 'name' => ' Presidente Nereu'],
                ['id_city' => 8580, 'id_state' => 24, 'name' => ' Princesa'],
                ['id_city' => 8581, 'id_state' => 24, 'name' => ' Quarta Linha'],
                ['id_city' => 8582, 'id_state' => 24, 'name' => ' Quilombo'],
                ['id_city' => 8583, 'id_state' => 24, 'name' => ' Quilômetro Doze'],
                ['id_city' => 8584, 'id_state' => 24, 'name' => ' Rancho Queimado'],
                ['id_city' => 8585, 'id_state' => 24, 'name' => ' Ratones'],
                ['id_city' => 8586, 'id_state' => 24, 'name' => ' Residência Fuck'],
                ['id_city' => 8587, 'id_state' => 24, 'name' => ' Ribeirão da Ilha'],
                ['id_city' => 8588, 'id_state' => 24, 'name' => ' Ribeirão Pequeno'],
                ['id_city' => 8589, 'id_state' => 24, 'name' => ' Rio Antinha'],
                ['id_city' => 8590, 'id_state' => 24, 'name' => ' Rio Bonito'],
                ['id_city' => 8591, 'id_state' => 24, 'name' => ' Rio D Una'],
                ['id_city' => 8592, 'id_state' => 24, 'name' => ' Rio da Anta'],
                ['id_city' => 8593, 'id_state' => 24, 'name' => ' Rio da Luz'],
                ['id_city' => 8594, 'id_state' => 24, 'name' => ' Rio das Antas'],
                ['id_city' => 8595, 'id_state' => 24, 'name' => ' Rio das Furnas'],
                ['id_city' => 8596, 'id_state' => 24, 'name' => ' Rio do Campo'],
                ['id_city' => 8597, 'id_state' => 24, 'name' => ' Rio do Oeste'],
                ['id_city' => 8598, 'id_state' => 24, 'name' => ' Rio do Sul'],
                ['id_city' => 8599, 'id_state' => 24, 'name' => ' Rio dos Bugres'],
                ['id_city' => 8600, 'id_state' => 24, 'name' => ' Rio dos Cedros'],
                ['id_city' => 8601, 'id_state' => 24, 'name' => ' Rio Fortuna'],
                ['id_city' => 8602, 'id_state' => 24, 'name' => ' Rio Maina'],
                ['id_city' => 8603, 'id_state' => 24, 'name' => ' Rio Negrinho'],
                ['id_city' => 8604, 'id_state' => 24, 'name' => ' Rio Preto do Sul'],
                ['id_city' => 8605, 'id_state' => 24, 'name' => ' Rio Rufino'],
                ['id_city' => 8606, 'id_state' => 24, 'name' => ' Riqueza'],
                ['id_city' => 8607, 'id_state' => 24, 'name' => ' Rodeio'],
                ['id_city' => 8608, 'id_state' => 24, 'name' => ' Romelândia'],
                ['id_city' => 8609, 'id_state' => 24, 'name' => ' Sai'],
                ['id_city' => 8610, 'id_state' => 24, 'name' => ' Salete'],
                ['id_city' => 8611, 'id_state' => 24, 'name' => ' Saltinho'],
                ['id_city' => 8612, 'id_state' => 24, 'name' => ' Salto Veloso'],
                ['id_city' => 8613, 'id_state' => 24, 'name' => ' Sanga da Toca'],
                ['id_city' => 8614, 'id_state' => 24, 'name' => ' Sangão'],
                ['id_city' => 8615, 'id_state' => 24, 'name' => ' Santa Cecília'],
                ['id_city' => 8616, 'id_state' => 24, 'name' => ' Santa Cruz do Timbó'],
                ['id_city' => 8617, 'id_state' => 24, 'name' => ' Santa Helena'],
                ['id_city' => 8618, 'id_state' => 24, 'name' => ' Santa Izabel'],
                ['id_city' => 8619, 'id_state' => 24, 'name' => ' Santa Lúcia'],
                ['id_city' => 8620, 'id_state' => 24, 'name' => ' Santa Maria'],
                ['id_city' => 8621, 'id_state' => 24, 'name' => ' Santa Rosa de Lima'],
                ['id_city' => 8622, 'id_state' => 24, 'name' => ' Santa Rosa do Sul'],
                ['id_city' => 8623, 'id_state' => 24, 'name' => ' Santa Terezinha'],
                ['id_city' => 8624, 'id_state' => 24, 'name' => ' Santa Terezinha do Progresso'],
                ['id_city' => 8625, 'id_state' => 24, 'name' => ' Santa Terezinha do Salto'],
                ['id_city' => 8626, 'id_state' => 24, 'name' => ' Santiago do Sul'],
                ['id_city' => 8627, 'id_state' => 24, 'name' => ' Santo Amaro da Imperatriz'],
                ['id_city' => 8628, 'id_state' => 24, 'name' => ' Santo Antônio de Lisboa'],
                ['id_city' => 8629, 'id_state' => 24, 'name' => ' São Bento Baixo'],
                ['id_city' => 8630, 'id_state' => 24, 'name' => ' São Bento do Sul'],
                ['id_city' => 8631, 'id_state' => 24, 'name' => ' São Bernardino'],
                ['id_city' => 8632, 'id_state' => 24, 'name' => ' São Bonifácio'],
                ['id_city' => 8633, 'id_state' => 24, 'name' => ' São Carlos'],
                ['id_city' => 8634, 'id_state' => 24, 'name' => ' São Cristóvão'],
                ['id_city' => 8635, 'id_state' => 24, 'name' => ' São Cristóvão do Sul'],
                ['id_city' => 8636, 'id_state' => 24, 'name' => ' São Defende'],
                ['id_city' => 8637, 'id_state' => 24, 'name' => ' São Domingos'],
                ['id_city' => 8638, 'id_state' => 24, 'name' => ' São Francisco do Sul'],
                ['id_city' => 8639, 'id_state' => 24, 'name' => ' São Gabriel']
            ]);
        }
    }