<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities16 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        
        DB::table('vpr_countries_states_cities')->insert([
            ['id_city' => 9927, 'id_state' => 8, 'name' => ' São Jorge da Barra Seca'],
            ['id_city' => 9928, 'id_state' => 8, 'name' => ' Jurama'],
            ['id_city' => 9929, 'id_state' => 13, 'name' => ' Sucanga'],
            ['id_city' => 9930, 'id_state' => 6, 'name' => ' Triângulo'],
            ['id_city' => 9931, 'id_state' => 6, 'name' => ' Cedro'],
            ['id_city' => 9932, 'id_state' => 6, 'name' => ' Patos dos Liberatos'],
            ['id_city' => 9933, 'id_state' => 6, 'name' => ' Campestre'],
            ['id_city' => 9934, 'id_state' => 6, 'name' => ' Timbaúba dos Marinheiros'],
            ['id_city' => 9935, 'id_state' => 9, 'name' => ' Rialma'],
            ['id_city' => 9936, 'id_state' => 17, 'name' => ' Jaboatão'],
            ['id_city' => 9937, 'id_state' => 17, 'name' => ' Navarro'],
            ['id_city' => 9938, 'id_state' => 17, 'name' => ' Cavaleiro'],
            ['id_city' => 9939, 'id_state' => 17, 'name' => ' Praia da Conceição'],
            ['id_city' => 9940, 'id_state' => 17, 'name' => ' Paratibe'],
            ['id_city' => 9941, 'id_state' => 13, 'name' => ' Chonin de Baixo'],
            ['id_city' => 9942, 'id_state' => 9, 'name' => ' JK'],
            ['id_city' => 9943, 'id_state' => 9, 'name' => ' Bezerra'],
            ['id_city' => 9944, 'id_state' => 19, 'name' => ' São Pedro da Serra'],
            ['id_city' => 9945, 'id_state' => 5, 'name' => ' Arraial D Ajuda'],
            ['id_city' => 9946, 'id_state' => 5, 'name' => ' Trancoso'],
            ['id_city' => 9947, 'id_state' => 5, 'name' => ' Itabatan'],
            ['id_city' => 9948, 'id_state' => 13, 'name' => ' Taquaral de Guanhães'],
            ['id_city' => 9949, 'id_state' => 9, 'name' => ' São Jorge'],
            ['id_city' => 9950, 'id_state' => 9, 'name' => ' Campo Lindo'],
            ['id_city' => 9951, 'id_state' => 19, 'name' => ' Batatal'],
            ['id_city' => 9952, 'id_state' => 19, 'name' => ' Serrinha'],
            ['id_city' => 9953, 'id_state' => 19, 'name' => ' Serrinha'],
            ['id_city' => 9954, 'id_state' => 16, 'name' => ' Jordão'],
            ['id_city' => 9955, 'id_state' => 16, 'name' => ' Biscaia'],
            ['id_city' => 9956, 'id_state' => 16, 'name' => ' Campo do Bugre'],
            ['id_city' => 9957, 'id_state' => 16, 'name' => ' Santa Cruz'],
            ['id_city' => 9958, 'id_state' => 16, 'name' => ' Caiva'],
            ['id_city' => 9959, 'id_state' => 16, 'name' => ' Itambezinho'],
            ['id_city' => 9960, 'id_state' => 9, 'name' => ' Girassol'],
            ['id_city' => 9961, 'id_state' => 9, 'name' => ' Edilândia'],
            ['id_city' => 9962, 'id_state' => 4, 'name' => ' Cacau Pirêra'],
            ['id_city' => 9963, 'id_state' => 19, 'name' => ' Ipituna'],
            ['id_city' => 9964, 'id_state' => 9, 'name' => ' Juscelândia'],
            ['id_city' => 9965, 'id_state' => 5, 'name' => ' Ilha de Bom Jesus dos Passos'],
            ['id_city' => 9966, 'id_state' => 5, 'name' => ' Ilha dos Frades'],
            ['id_city' => 9967, 'id_state' => 21, 'name' => ' Passo do Verde'],
            ['id_city' => 9968, 'id_state' => 9, 'name' => ' Jardim ABC de Goiás'],
            ['id_city' => 9969, 'id_state' => 8, 'name' => ' Barra do Sahy'],
            ['id_city' => 9970, 'id_state' => 16, 'name' => ' Bananas'],
            ['id_city' => 9971, 'id_state' => 16, 'name' => ' Candeia'],
            ['id_city' => 9972, 'id_state' => 16, 'name' => ' Guaraí'],
            ['id_city' => 9973, 'id_state' => 16, 'name' => ' Ouro Verde'],
            ['id_city' => 9974, 'id_state' => 16, 'name' => ' São Roque do Chopim'],
            ['id_city' => 9975, 'id_state' => 24, 'name' => ' Jorge Lacerda'],
            ['id_city' => 9976, 'id_state' => 24, 'name' => ' Idamar'],
            ['id_city' => 9977, 'id_state' => 6, 'name' => ' Penedo'],
            ['id_city' => 9978, 'id_state' => 6, 'name' => ' Umarizeiras'],
            ['id_city' => 9979, 'id_state' => 6, 'name' => ' Lages'],
            ['id_city' => 9980, 'id_state' => 6, 'name' => ' Cachoeira'],
            ['id_city' => 9981, 'id_state' => 6, 'name' => ' São João do Amanari'],
            ['id_city' => 9982, 'id_state' => 6, 'name' => ' Papara'],
            ['id_city' => 9983, 'id_state' => 6, 'name' => ' Manoel Guedes'],
            ['id_city' => 9984, 'id_state' => 9, 'name' => ' Olhos D Água'],
            ['id_city' => 9985, 'id_state' => 21, 'name' => ' Mato Perso'],
            ['id_city' => 9986, 'id_state' => 5, 'name' => ' Pilões'],
            ['id_city' => 9987, 'id_state' => 5, 'name' => ' Pedra Alta'],
            ['id_city' => 9988, 'id_state' => 23, 'name' => ' Santa Cecília'],
            ['id_city' => 9989, 'id_state' => 23, 'name' => ' Félix Pinto'],
            ['id_city' => 9990, 'id_state' => 23, 'name' => ' Taboca'],
            ['id_city' => 9991, 'id_state' => 23, 'name' => ' Novo Paraíso'],
            ['id_city' => 9992, 'id_state' => 9, 'name' => ' Planalmira'],
            ['id_city' => 9993, 'id_state' => 18, 'name' => ' Aroeiras do Itaim'],
            ['id_city' => 9994, 'id_state' => 11, 'name' => ' Ipiranga do Norte'],
            ['id_city' => 9995, 'id_state' => 11, 'name' => ' Itanhangá'],
            ['id_city' => 9996, 'id_state' => 1, 'name' => ' Campinas'],
            ['id_city' => 9997, 'id_state' => 14, 'name' => ' Moraes Almeida'],
            ['id_city' => 9998, 'id_state' => 12, 'name' => ' Nova Casa Verde'],
            ['id_city' => 9999, 'id_state' => 2, 'name' => ' Pontal de Coruripe'],
            ['id_city' => 10000, 'id_state' => 2, 'name' => ' Botafogo'],
            ['id_city' => 10001, 'id_state' => 2, 'name' => ' Bonsucesso'],
            ['id_city' => 10002, 'id_state' => 13, 'name' => ' Vila Acari'],
            ['id_city' => 10003, 'id_state' => 13, 'name' => ' Chapéu D Uvas'],
            ['id_city' => 10004, 'id_state' => 13, 'name' => ' Penido'],
            ['id_city' => 10005, 'id_state' => 13, 'name' => ' Monte Verde'],
            ['id_city' => 10006, 'id_state' => 13, 'name' => ' Pirapitinga'],
            ['id_city' => 10007, 'id_state' => 13, 'name' => ' Toledos'],
            ['id_city' => 10008, 'id_state' => 13, 'name' => ' Humaitá'],
            ['id_city' => 10009, 'id_state' => 6, 'name' => ' Ipaguaçú'],
            ['id_city' => 10010, 'id_state' => 25, 'name' => ' Arabá'],
            ['id_city' => 10011, 'id_state' => 2, 'name' => ' Peroba'],
            ['id_city' => 10012, 'id_state' => 21, 'name' => ' Passo do Goulart'],
            ['id_city' => 10013, 'id_state' => 4, 'name' => ' Agrovila São Sebastião do Caburi'],
            ['id_city' => 10014, 'id_state' => 4, 'name' => ' Novo Remanso'],
            ['id_city' => 10015, 'id_state' => 21, 'name' => ' Vila Fernando Ferrari'],
            ['id_city' => 10016, 'id_state' => 21, 'name' => ' Vale dos Vinhedos'],
            ['id_city' => 10017, 'id_state' => 21, 'name' => ' Borussia'],
            ['id_city' => 10018, 'id_state' => 21, 'name' => ' Aguapés'],
            ['id_city' => 10019, 'id_state' => 21, 'name' => ' Santa Luzia'],
            ['id_city' => 10020, 'id_state' => 14, 'name' => ' São Miguel de Pracuuba'],
            ['id_city' => 10021, 'id_state' => 14, 'name' => ' Cachoeira da Serra'],
            ['id_city' => 10022, 'id_state' => 14, 'name' => ' Caracol'],
            ['id_city' => 10023, 'id_state' => 14, 'name' => ' Alvorada'],
            ['id_city' => 10024, 'id_state' => 14, 'name' => ' Belo Monte'],
            ['id_city' => 10025, 'id_state' => 17, 'name' => ' Cuieiras'],
            ['id_city' => 10026, 'id_state' => 21, 'name' => ' Serrinha Velha'],
            ['id_city' => 10027, 'id_state' => 16, 'name' => ' São Luiz do Oeste'],
            ['id_city' => 10028, 'id_state' => 14, 'name' => ' Vila Mandi'],
            ['id_city' => 10029, 'id_state' => 25, 'name' => ' Conceição'],
            ['id_city' => 10030, 'id_state' => 25, 'name' => ' Lageado de Araçaíba'],
            ['id_city' => 10031, 'id_state' => 2, 'name' => ' Luziápolis'],
            ['id_city' => 10032, 'id_state' => 13, 'name' => ' Lagoa Seca'],
            ['id_city' => 10033, 'id_state' => 9, 'name' => ' Luiz Alves'],
            ['id_city' => 10034, 'id_state' => 19, 'name' => ' Frade'],
            ['id_city' => 10035, 'id_state' => 2, 'name' => ' Lagoa Grande'],
            ['id_city' => 10036, 'id_state' => 2, 'name' => ' Boqueirão'],
            ['id_city' => 10037, 'id_state' => 3, 'name' => ' Serra do Navio'],
            ['id_city' => 10038, 'id_state' => 16, 'name' => ' Charco'],
            ['id_city' => 10039, 'id_state' => 5, 'name' => ' Roda Velha'],
            ['id_city' => 10040, 'id_state' => 13, 'name' => ' Chaves'],
            ['id_city' => 10041, 'id_state' => 6, 'name' => ' Bom Princípio'],
            ['id_city' => 10042, 'id_state' => 5, 'name' => ' Barreiros'],
            ['id_city' => 10043, 'id_state' => 19, 'name' => ' Califórnia da Barra'],
            ['id_city' => 10044, 'id_state' => 9, 'name' => ' Nova Fátima'],
            ['id_city' => 10045, 'id_state' => 22, 'name' => ' São Carlos'],
            ['id_city' => 10046, 'id_state' => 22, 'name' => ' Nazaré'],
            ['id_city' => 10047, 'id_state' => 22, 'name' => ' Demarcação'],
            ['id_city' => 10048, 'id_state' => 22, 'name' => ' Mutum Paraná'],
            ['id_city' => 10049, 'id_state' => 22, 'name' => ' Fortaleza do Abunã'],
            ['id_city' => 10050, 'id_state' => 22, 'name' => ' Nova Califórnia'],
            ['id_city' => 10051, 'id_state' => 19, 'name' => ' Visconde de Mauá'],
            ['id_city' => 10052, 'id_state' => 9, 'name' => ' Arantina'],
            ['id_city' => 10053, 'id_state' => 11, 'name' => ' Comunidade Parque Boa Vista'],
            ['id_city' => 10054, 'id_state' => 13, 'name' => ' Três Barras da Estrada Real'],
            ['id_city' => 10055, 'id_state' => 16, 'name' => ' Ilha Encantada'],
            ['id_city' => 10056, 'id_state' => 16, 'name' => ' Ilha do Amparo'],
            ['id_city' => 10057, 'id_state' => 16, 'name' => ' Ilha de Eufrasina'],
            ['id_city' => 10058, 'id_state' => 16, 'name' => ' Ilha do Teixeira'],
            ['id_city' => 10059, 'id_state' => 16, 'name' => ' Ilha de São Miguel'],
            ['id_city' => 10060, 'id_state' => 5, 'name' => ' Porto Sauípe'],
            ['id_city' => 10061, 'id_state' => 13, 'name' => ' Santa Rita'],
            ['id_city' => 10062, 'id_state' => 9, 'name' => ' Trevo do José Rosário'],
            ['id_city' => 10063, 'id_state' => 9, 'name' => ' Souzalândia'],
            ['id_city' => 10064, 'id_state' => 6, 'name' => ' Santa Rosa'],
            ['id_city' => 10065, 'id_state' => 6, 'name' => ' Baixio das Palmeiras'],
            ['id_city' => 10066, 'id_state' => 6, 'name' => ' Belmonte'],
            ['id_city' => 10067, 'id_state' => 6, 'name' => ' Bela Vista'],
            ['id_city' => 10068, 'id_state' => 6, 'name' => ' Monte Alverne'],
            ['id_city' => 10069, 'id_state' => 6, 'name' => ' Campo Alegre'],
            ['id_city' => 10070, 'id_state' => 6, 'name' => ' Laranjeiras'],
            ['id_city' => 10071, 'id_state' => 6, 'name' => ' Pedras Brancas'],
            ['id_city' => 10072, 'id_state' => 5, 'name' => ' Passé'],
            ['id_city' => 10073, 'id_state' => 5, 'name' => ' Caroba'],
            ['id_city' => 10074, 'id_state' => 5, 'name' => ' Menino Jesus'],
            ['id_city' => 10075, 'id_state' => 5, 'name' => ' Madeira'],
            ['id_city' => 10076, 'id_state' => 5, 'name' => ' Passagem dos Teixeiras'],
            ['id_city' => 10077, 'id_state' => 5, 'name' => ' Cabôto'],
            ['id_city' => 10078, 'id_state' => 6, 'name' => ' Barbada'],
            ['id_city' => 10079, 'id_state' => 6, 'name' => ' Maravilha'],
            ['id_city' => 10080, 'id_state' => 6, 'name' => ' Monte Castelo'],
            ['id_city' => 10081, 'id_state' => 6, 'name' => ' Santa Rita'],
            ['id_city' => 10082, 'id_state' => 6, 'name' => ' Catolé da Pista'],
            ['id_city' => 10083, 'id_state' => 6, 'name' => ' Coité'],
            ['id_city' => 10084, 'id_state' => 14, 'name' => ' União da Floresta'],
            ['id_city' => 10085, 'id_state' => 21, 'name' => ' Taquaral'],
            ['id_city' => 10086, 'id_state' => 21, 'name' => ' Esperança'],
            ['id_city' => 10087, 'id_state' => 21, 'name' => ' Harmonia'],
            ['id_city' => 10088, 'id_state' => 21, 'name' => ' Faxinal'],
            ['id_city' => 10089, 'id_state' => 21, 'name' => ' Prado Novo'],
            ['id_city' => 10090, 'id_state' => 21, 'name' => ' Lagoa dos Patos'],
            ['id_city' => 10091, 'id_state' => 5, 'name' => ' Barra Avenida'],
            ['id_city' => 10092, 'id_state' => 9, 'name' => ' Posselândia'],
            ['id_city' => 10093, 'id_state' => 6, 'name' => ' Riacho Verde'],
            ['id_city' => 10094, 'id_state' => 6, 'name' => ' São Bernardo'],
            ['id_city' => 10095, 'id_state' => 6, 'name' => ' Forquilha'],
            ['id_city' => 10096, 'id_state' => 13, 'name' => ' Ribeirão da Folha'],
            ['id_city' => 10097, 'id_state' => 13, 'name' => ' Baixa Quente'],
            ['id_city' => 10098, 'id_state' => 13, 'name' => ' Cruzinha'],
            ['id_city' => 10099, 'id_state' => 13, 'name' => ' Lagoa Grande de Minas Novas'],
            ['id_city' => 10100, 'id_state' => 13, 'name' => ' São Sebastião'],
            ['id_city' => 10101, 'id_state' => 6, 'name' => ' Martinslândia'],
            ['id_city' => 10102, 'id_state' => 6, 'name' => ' Mocambo'],
            ['id_city' => 10103, 'id_state' => 6, 'name' => ' Paraiso'],
            ['id_city' => 10104, 'id_state' => 6, 'name' => ' Video'],
            ['id_city' => 10105, 'id_state' => 6, 'name' => ' Assis'],
            ['id_city' => 10106, 'id_state' => 6, 'name' => ' Curral Velho'],
            ['id_city' => 10107, 'id_state' => 6, 'name' => ' Lagoa das Pedras'],
            ['id_city' => 10108, 'id_state' => 6, 'name' => ' Realejo'],
            ['id_city' => 10109, 'id_state' => 2, 'name' => ' Barro Vermelho'],
            ['id_city' => 10110, 'id_state' => 2, 'name' => ' Ingá'],
            ['id_city' => 10111, 'id_state' => 2, 'name' => ' Retiro'],
            ['id_city' => 10112, 'id_state' => 2, 'name' => ' Riachão'],
            ['id_city' => 10113, 'id_state' => 5, 'name' => ' Caraíbas'],
            ['id_city' => 10114, 'id_state' => 6, 'name' => ' Prefeita Suely Pinheiro'],
            ['id_city' => 10115, 'id_state' => 13, 'name' => ' Pouso Alegre'],
            ['id_city' => 10116, 'id_state' => 13, 'name' => ' Boa Esperança'],
            ['id_city' => 10117, 'id_state' => 13, 'name' => ' Engenheiro Dolabela'],
            ['id_city' => 10118, 'id_state' => 2, 'name' => ' Barreiras'],
            ['id_city' => 10119, 'id_state' => 2, 'name' => ' Cana Brava'],
            ['id_city' => 10120, 'id_state' => 17, 'name' => ' Pé-de-Serra dos Mendes'],
            ['id_city' => 10121, 'id_state' => 17, 'name' => ' Alverne'],
            ['id_city' => 10122, 'id_state' => 17, 'name' => ' Sítio dos Remédios'],
            ['id_city' => 10123, 'id_state' => 17, 'name' => ' Serra Negra'],
            ['id_city' => 10124, 'id_state' => 17, 'name' => ' Cajazeiras'],
            ['id_city' => 10125, 'id_state' => 17, 'name' => ' Areias'],
            ['id_city' => 10126, 'id_state' => 17, 'name' => ' Logradouro dos Leões'],
            ['id_city' => 10127, 'id_state' => 17, 'name' => ' Cachoeira do Pinto'],
            ['id_city' => 10128, 'id_state' => 17, 'name' => ' Igreja Nova'],
            ['id_city' => 10129, 'id_state' => 17, 'name' => ' Cavalo Ruço de Deus'],
            ['id_city' => 10130, 'id_state' => 17, 'name' => ' Caldeirão'],
            ['id_city' => 10131, 'id_state' => 17, 'name' => ' Lagoa da Pedra'],
            ['id_city' => 10132, 'id_state' => 17, 'name' => ' Junco'],
            ['id_city' => 10133, 'id_state' => 17, 'name' => ' Usina Roçadinho'],
            ['id_city' => 10134, 'id_state' => 17, 'name' => ' Pau Amarelo'],
            ['id_city' => 10135, 'id_state' => 17, 'name' => ' Atapus'],
            ['id_city' => 10136, 'id_state' => 17, 'name' => ' Gambá'],
            ['id_city' => 10137, 'id_state' => 17, 'name' => ' Carne-de-Vaca'],
            ['id_city' => 10138, 'id_state' => 17, 'name' => ' São Lorenço'],
            ['id_city' => 10139, 'id_state' => 17, 'name' => ' São Severino'],
            ['id_city' => 10140, 'id_state' => 17, 'name' => ' Santa Rosa'],
            ['id_city' => 10141, 'id_state' => 17, 'name' => ' Jirau'],
            ['id_city' => 10142, 'id_state' => 17, 'name' => ' Neves'],
            ['id_city' => 10143, 'id_state' => 17, 'name' => ' Campo Alegre'],
            ['id_city' => 10144, 'id_state' => 17, 'name' => ' Vermelhos'],
            ['id_city' => 10145, 'id_state' => 17, 'name' => ' Matinada'],
            ['id_city' => 10146, 'id_state' => 17, 'name' => ' Santa Rita'],
            ['id_city' => 10147, 'id_state' => 17, 'name' => ' Tenebre'],
            ['id_city' => 10148, 'id_state' => 17, 'name' => ' Ipanema'],
            ['id_city' => 10149, 'id_state' => 17, 'name' => ' Rangel'],
            ['id_city' => 10150, 'id_state' => 17, 'name' => ' Pau Ferro'],
            ['id_city' => 10151, 'id_state' => 17, 'name' => ' Serrinha da Prata'],
            ['id_city' => 10152, 'id_state' => 17, 'name' => ' Caramuru'],
            ['id_city' => 10153, 'id_state' => 17, 'name' => ' Monte Alegre'],
            ['id_city' => 10154, 'id_state' => 17, 'name' => ' Santa Rosa'],
            ['id_city' => 10155, 'id_state' => 17, 'name' => ' São Francisco do Brígida'],
            ['id_city' => 10156, 'id_state' => 17, 'name' => ' Pernambuquinho'],
            ['id_city' => 10157, 'id_state' => 17, 'name' => ' Cruzeiro do Nordeste'],
            ['id_city' => 10158, 'id_state' => 17, 'name' => ' Moderna'],
            ['id_city' => 10159, 'id_state' => 17, 'name' => ' Umburanas'],
            ['id_city' => 10160, 'id_state' => 17, 'name' => ' Caroalina'],
            ['id_city' => 10161, 'id_state' => 17, 'name' => ' Valdemar Siqueira'],
            ['id_city' => 10162, 'id_state' => 17, 'name' => ' Santo Amaro'],
            ['id_city' => 10163, 'id_state' => 17, 'name' => ' Lagoa da Vaca'],
            ['id_city' => 10164, 'id_state' => 17, 'name' => ' Juca Ferrado'],
            ['id_city' => 10165, 'id_state' => 17, 'name' => ' Lério de Cima'],
            ['id_city' => 10166, 'id_state' => 17, 'name' => ' Mimoso'],
            ['id_city' => 10167, 'id_state' => 17, 'name' => ' Grossos'],
            ['id_city' => 10168, 'id_state' => 17, 'name' => ' São João do Ferraz'],
            ['id_city' => 10169, 'id_state' => 17, 'name' => ' Serra da Cachoeira'],
            ['id_city' => 10170, 'id_state' => 17, 'name' => ' Livramento'],
            ['id_city' => 10171, 'id_state' => 13, 'name' => ' Vila Bem-Querer'],
            ['id_city' => 10172, 'id_state' => 4, 'name' => ' Itapeaçu'],
            ['id_city' => 10173, 'id_state' => 4, 'name' => ' Vila Lindóia'],
            ['id_city' => 10174, 'id_state' => 4, 'name' => ' Santana'],
            ['id_city' => 10175, 'id_state' => 4, 'name' => ' Vila Zé Açu'],
            ['id_city' => 10176, 'id_state' => 4, 'name' => ' Vila Amazônia'],
            ['id_city' => 10177, 'id_state' => 4, 'name' => ' Novo Céu'],
            ['id_city' => 10178, 'id_state' => 4, 'name' => ' Purupuru'],
            ['id_city' => 10179, 'id_state' => 4, 'name' => ' Terra Nova'],
            ['id_city' => 10180, 'id_state' => 4, 'name' => ' Careiro Parauá'],
            ['id_city' => 10181, 'id_state' => 4, 'name' => ' Santo Antônio do Matupi'],
            ['id_city' => 10182, 'id_state' => 4, 'name' => ' Vila de Sacambu'],
            ['id_city' => 10183, 'id_state' => 4, 'name' => ' Vila Rica de Caviana'],
            ['id_city' => 10184, 'id_state' => 4, 'name' => ' Vila do Lago do Jacaré'],
            ['id_city' => 10185, 'id_state' => 4, 'name' => ' Repartimento de Tuiué'],
            ['id_city' => 10186, 'id_state' => 4, 'name' => ' Vila de Campinas'],
            ['id_city' => 10187, 'id_state' => 4, 'name' => ' Araras'],
            ['id_city' => 10188, 'id_state' => 4, 'name' => ' Murituba'],
            ['id_city' => 10189, 'id_state' => 4, 'name' => ' Vila Bittencourt'],
            ['id_city' => 10190, 'id_state' => 4, 'name' => ' Limoeiro'],
            ['id_city' => 10191, 'id_state' => 4, 'name' => ' Feijoal'],
            ['id_city' => 10192, 'id_state' => 4, 'name' => ' Belém de Solimões'],
            ['id_city' => 10193, 'id_state' => 4, 'name' => ' Palmeiras'],
            ['id_city' => 10194, 'id_state' => 4, 'name' => ' Estirão do Equador'],
            ['id_city' => 10195, 'id_state' => 4, 'name' => ' Platô do Piquiá'],
            ['id_city' => 10196, 'id_state' => 2, 'name' => ' Baixa Grande'],
            ['id_city' => 10197, 'id_state' => 2, 'name' => ' Farrinheira'],
            ['id_city' => 10198, 'id_state' => 2, 'name' => ' Flexeiras'],
            ['id_city' => 10199, 'id_state' => 2, 'name' => ' Mangabeiras'],
            ['id_city' => 10200, 'id_state' => 2, 'name' => ' Mata Limpa'],
            ['id_city' => 10201, 'id_state' => 2, 'name' => ' Pilões'],
            ['id_city' => 10202, 'id_state' => 2, 'name' => ' Poço'],
            ['id_city' => 10203, 'id_state' => 2, 'name' => ' Poço da Pedra de Cima'],
            ['id_city' => 10204, 'id_state' => 2, 'name' => ' Poço de Baixo'],
            ['id_city' => 10205, 'id_state' => 2, 'name' => ' Poço de Santana'],
            ['id_city' => 10206, 'id_state' => 2, 'name' => ' Quati'],
            ['id_city' => 10207, 'id_state' => 2, 'name' => ' Retiro'],
            ['id_city' => 10208, 'id_state' => 2, 'name' => ' Rio dos Bichos'],
            ['id_city' => 10209, 'id_state' => 2, 'name' => ' São Lourenço'],
            ['id_city' => 10210, 'id_state' => 2, 'name' => ' Serra da Massa'],
            ['id_city' => 10211, 'id_state' => 2, 'name' => ' Tabocas'],
            ['id_city' => 10212, 'id_state' => 2, 'name' => ' Taquara'],
            ['id_city' => 10213, 'id_state' => 2, 'name' => ' Varginha'],
            ['id_city' => 10214, 'id_state' => 17, 'name' => ' Chã de Cruz'],
            ['id_city' => 10215, 'id_state' => 17, 'name' => ' Caraíbas'],
            ['id_city' => 10216, 'id_state' => 17, 'name' => ' Riacho do Meio'],
            ['id_city' => 10217, 'id_state' => 17, 'name' => ' Santa Luzia'],
            ['id_city' => 10218, 'id_state' => 17, 'name' => ' Nossa Senhora Aparecida'],
            ['id_city' => 10219, 'id_state' => 17, 'name' => ' Raiz'],
            ['id_city' => 10220, 'id_state' => 17, 'name' => ' Taboquinha'],
            ['id_city' => 10221, 'id_state' => 17, 'name' => ' Vila Nova'],
            ['id_city' => 10222, 'id_state' => 17, 'name' => ' Caramuru'],
            ['id_city' => 10223, 'id_state' => 17, 'name' => ' Caraúba Torta'],
            ['id_city' => 10224, 'id_state' => 17, 'name' => ' Cachoeira Seca'],
            ['id_city' => 10225, 'id_state' => 17, 'name' => ' Itaúna'],
            ['id_city' => 10226, 'id_state' => 17, 'name' => ' Jacaré Grande'],
            ['id_city' => 10227, 'id_state' => 17, 'name' => ' Juá'],
            ['id_city' => 10228, 'id_state' => 17, 'name' => ' Laje'],
            ['id_city' => 10229, 'id_state' => 17, 'name' => ' Malhada Barreiras Queimadas'],
            ['id_city' => 10230, 'id_state' => 17, 'name' => ' Rafael'],
            ['id_city' => 10231, 'id_state' => 17, 'name' => ' Patos'],
            ['id_city' => 10232, 'id_state' => 17, 'name' => ' Palmatória'],
            ['id_city' => 10233, 'id_state' => 17, 'name' => ' Jacarezinho'],
            ['id_city' => 10234, 'id_state' => 17, 'name' => ' Malhada de Pedra'],
            ['id_city' => 10235, 'id_state' => 17, 'name' => ' Pau-Santo'],
            ['id_city' => 10236, 'id_state' => 17, 'name' => ' Terra Vermelha'],
            ['id_city' => 10237, 'id_state' => 17, 'name' => ' Pelada'],
            ['id_city' => 10238, 'id_state' => 17, 'name' => ' Xicuru'],
            ['id_city' => 10239, 'id_state' => 17, 'name' => ' Murici'],
            ['id_city' => 10240, 'id_state' => 17, 'name' => ' Serrote dos Bois de Cima'],
            ['id_city' => 10241, 'id_state' => 17, 'name' => ' Xique-Xique'],
            ['id_city' => 10242, 'id_state' => 17, 'name' => ' Nova Descoberta'],
            ['id_city' => 10243, 'id_state' => 17, 'name' => ' Ns2 Núcleo de Serviços'],
            ['id_city' => 10244, 'id_state' => 17, 'name' => ' Pedrinhas'],
            ['id_city' => 10245, 'id_state' => 17, 'name' => ' Massangano'],
            ['id_city' => 10246, 'id_state' => 17, 'name' => ' Serrote do Urubu'],
            ['id_city' => 10247, 'id_state' => 17, 'name' => ' Vila Nossa Senhora Aparecida'],
            ['id_city' => 10248, 'id_state' => 17, 'name' => ' Uruás'],
            ['id_city' => 10249, 'id_state' => 17, 'name' => ' Km 25'],
            ['id_city' => 10250, 'id_state' => 17, 'name' => ' Vila Nova - N5'],
            ['id_city' => 10251, 'id_state' => 9, 'name' => ' Santo Antônio da Esperança'],
            ['id_city' => 10252, 'id_state' => 13, 'name' => ' Bom Jesus do Prata'],
            ['id_city' => 10253, 'id_state' => 21, 'name' => ' Rincão de São Miguel'],
            ['id_city' => 10254, 'id_state' => 21, 'name' => ' Itapororó'],
            ['id_city' => 10255, 'id_state' => 21, 'name' => ' Guassu Boi'],
            ['id_city' => 10256, 'id_state' => 21, 'name' => ' Inhanduí'],
            ['id_city' => 10257, 'id_state' => 21, 'name' => ' Vasco Alves'],
            ['id_city' => 10258, 'id_state' => 21, 'name' => ' Catimbau'],
            ['id_city' => 10259, 'id_state' => 21, 'name' => ' Durasnal'],
            ['id_city' => 10260, 'id_state' => 18, 'name' => ' Nazária'],
            ['id_city' => 10261, 'id_state' => 22, 'name' => ' Triunfo'],
            ['id_city' => 10262, 'id_state' => 9, 'name' => ' Novo Goiás'],
            ['id_city' => 10263, 'id_state' => 6, 'name' => ' São Pedro do Gavião'],
            ['id_city' => 10264, 'id_state' => 13, 'name' => ' Cafemirim'],
            ['id_city' => 10265, 'id_state' => 22, 'name' => ' União Bandeirante'],
            ['id_city' => 10266, 'id_state' => 6, 'name' => ' Conceição'],
            ['id_city' => 10267, 'id_state' => 6, 'name' => ' Juritianha'],
            ['id_city' => 10268, 'id_state' => 6, 'name' => ' Lagoa do Carneiro'],
            ['id_city' => 10269, 'id_state' => 6, 'name' => ' Santa Fé'],
            ['id_city' => 10270, 'id_state' => 16, 'name' => ' Passo Amarelo'],
            ['id_city' => 10271, 'id_state' => 22, 'name' => ' Bom Futuro'],
            ['id_city' => 10272, 'id_state' => 22, 'name' => ' Tarilândia'],
            ['id_city' => 10273, 'id_state' => 22, 'name' => ' Bom Jesus'],
            ['id_city' => 10274, 'id_state' => 22, 'name' => ' Santa Cruz'],
            ['id_city' => 10275, 'id_state' => 16, 'name' => ' Cedro'],
            ['id_city' => 10276, 'id_state' => 5, 'name' => ' Palmares'],
            ['id_city' => 10277, 'id_state' => 5, 'name' => ' Dantelândia'],
            ['id_city' => 10278, 'id_state' => 5, 'name' => ' Veredinha'],
            ['id_city' => 10279, 'id_state' => 5, 'name' => ' Matinha'],
            ['id_city' => 10280, 'id_state' => 5, 'name' => ' São Sebastião'],
            ['id_city' => 10281, 'id_state' => 5, 'name' => ' Cabeceira do Jibóia'],
            ['id_city' => 10282, 'id_state' => 5, 'name' => ' Pradoso'],
            ['id_city' => 10283, 'id_state' => 5, 'name' => ' Cercadinho'],
            ['id_city' => 10284, 'id_state' => 16, 'name' => ' Martinópolis'],
            ['id_city' => 10285, 'id_state' => 11, 'name' => ' Piratininga'],
            ['id_city' => 10286, 'id_state' => 11, 'name' => ' Santo Antonio do Rio Bonito'],
            ['id_city' => 10287, 'id_state' => 11, 'name' => ' Novo Mato Grosso'],
            ['id_city' => 10288, 'id_state' => 11, 'name' => ' Santa Terezinha do Rio Ferro'],
            ['id_city' => 10289, 'id_state' => 11, 'name' => ' Parque Água Limpa'],
            ['id_city' => 10290, 'id_state' => 16, 'name' => ' Rio XV de Baixo'],
            ['id_city' => 10291, 'id_state' => 13, 'name' => ' Palmital de Minas'],
            ['id_city' => 10292, 'id_state' => 13, 'name' => ' Ruralminas'],
            ['id_city' => 10293, 'id_state' => 13, 'name' => ' Pedras de Marilândia'],
            ['id_city' => 10294, 'id_state' => 13, 'name' => ' Pinheiro Grosso'],
            ['id_city' => 10295, 'id_state' => 13, 'name' => ' Ponte do Cosme'],
            ['id_city' => 10296, 'id_state' => 13, 'name' => ' Faria'],
            ['id_city' => 10297, 'id_state' => 6, 'name' => ' Várzea da Onça'],
            ['id_city' => 10298, 'id_state' => 6, 'name' => ' Mosquito'],
            ['id_city' => 10299, 'id_state' => 22, 'name' => ' Palmeiras'],
            ['id_city' => 10300, 'id_state' => 11, 'name' => ' Pedro Neca'],
            ['id_city' => 10301, 'id_state' => 11, 'name' => ' Bocaiuval'],
            ['id_city' => 10302, 'id_state' => 11, 'name' => ' Vila Cardoso'],
            ['id_city' => 10303, 'id_state' => 11, 'name' => ' Água da Prata'],
            ['id_city' => 10304, 'id_state' => 11, 'name' => ' Nova Primavera'],
            ['id_city' => 10305, 'id_state' => 11, 'name' => ' Nova Cáceres'],
            ['id_city' => 10306, 'id_state' => 11, 'name' => ' São José do Pingador'],
            ['id_city' => 10307, 'id_state' => 11, 'name' => ' Guariba'],
            ['id_city' => 10308, 'id_state' => 11, 'name' => ' Marechal Rondon'],
            ['id_city' => 10309, 'id_state' => 22, 'name' => ' Boa Vista de Pacarana'],
            ['id_city' => 10310, 'id_state' => 22, 'name' => ' Nova Esperança'],
            ['id_city' => 10311, 'id_state' => 13, 'name' => ' Glória de Cataguases'],
            ['id_city' => 10312, 'id_state' => 6, 'name' => ' Anil'],
            ['id_city' => 10313, 'id_state' => 6, 'name' => ' Faveira'],
            ['id_city' => 10314, 'id_state' => 16, 'name' => ' Ouro Preto'],
            ['id_city' => 10315, 'id_state' => 21, 'name' => ' Piquiri'],
            ['id_city' => 10316, 'id_state' => 22, 'name' => ' Guaporé'],
            ['id_city' => 10317, 'id_state' => 16, 'name' => ' Santa Bárbara'],
            ['id_city' => 10318, 'id_state' => 21, 'name' => ' Bom Recreio'],
            ['id_city' => 10319, 'id_state' => 21, 'name' => ' Sede Independência'],
            ['id_city' => 10320, 'id_state' => 11, 'name' => ' Veranópolis'],
            ['id_city' => 10321, 'id_state' => 5, 'name' => ' Antarí'],
            ['id_city' => 10322, 'id_state' => 19, 'name' => ' Pachecos'],
            ['id_city' => 10323, 'id_state' => 19, 'name' => ' Manilha'],
            ['id_city' => 10324, 'id_state' => 19, 'name' => ' Visconde de Itaboraí'],
            ['id_city' => 10325, 'id_state' => 15, 'name' => ' Bebelândia'],
            ['id_city' => 10326, 'id_state' => 6, 'name' => ' Pai João'],
            ['id_city' => 10327, 'id_state' => 6, 'name' => ' Areré'],
            ['id_city' => 10328, 'id_state' => 6, 'name' => ' Córrego'],
            ['id_city' => 10329, 'id_state' => 6, 'name' => ' Cajueiro'],
            ['id_city' => 10330, 'id_state' => 6, 'name' => ' Lagoa do Barro'],
            ['id_city' => 10331, 'id_state' => 6, 'name' => ' Lagoa Grande'],
            ['id_city' => 10332, 'id_state' => 16, 'name' => ' Santo Izidoro'],
            ['id_city' => 10333, 'id_state' => 6, 'name' => ' Canta Galo'],
            ['id_city' => 10334, 'id_state' => 6, 'name' => ' Capitão Pedro Sampaio'],
            ['id_city' => 10335, 'id_state' => 6, 'name' => ' Caiçara'],
            ['id_city' => 10336, 'id_state' => 6, 'name' => ' Iguaçu'],
            ['id_city' => 10337, 'id_state' => 6, 'name' => ' Vazente do Curú'],
            ['id_city' => 10338, 'id_state' => 6, 'name' => ' Campos'],
            ['id_city' => 10339, 'id_state' => 6, 'name' => ' Faísca'],
            ['id_city' => 10340, 'id_state' => 13, 'name' => ' Vila Nova Floresta'],
            ['id_city' => 10341, 'id_state' => 20, 'name' => ' Pipa'],
            ['id_city' => 10342, 'id_state' => 6, 'name' => ' Juá'],
            ['id_city' => 10343, 'id_state' => 6, 'name' => ' Santo André'],
            ['id_city' => 10344, 'id_state' => 16, 'name' => ' Flor da Serra'],
            ['id_city' => 10345, 'id_state' => 6, 'name' => ' Alto Lindo'],
            ['id_city' => 10346, 'id_state' => 6, 'name' => ' Betânia'],
            ['id_city' => 10347, 'id_state' => 6, 'name' => ' Nova Veneza'],
            ['id_city' => 10348, 'id_state' => 14, 'name' => ' Palmares'],
            ['id_city' => 10349, 'id_state' => 6, 'name' => ' Mocambo'],
            ['id_city' => 10350, 'id_state' => 17, 'name' => ' Izacolandia'],
            ['id_city' => 10351, 'id_state' => 6, 'name' => ' Simão'],
            ['id_city' => 10352, 'id_state' => 6, 'name' => ' Boa Vista'],
            ['id_city' => 10353, 'id_state' => 6, 'name' => ' São Sebastião'],
            ['id_city' => 10354, 'id_state' => 6, 'name' => ' Canindezinho'],
            ['id_city' => 10355, 'id_state' => 6, 'name' => ' Viçosa'],
            ['id_city' => 10356, 'id_state' => 6, 'name' => ' Açude dos Pinheiros'],
            ['id_city' => 10357, 'id_state' => 6, 'name' => ' Chile'],
            ['id_city' => 10358, 'id_state' => 6, 'name' => ' Cacimbas'],
            ['id_city' => 10359, 'id_state' => 6, 'name' => ' Jucá'],
            ['id_city' => 10360, 'id_state' => 6, 'name' => ' Tapuio'],
            ['id_city' => 10361, 'id_state' => 6, 'name' => ' Belém'],
            ['id_city' => 10362, 'id_state' => 9, 'name' => ' Claudinápolis'],
            ['id_city' => 10363, 'id_state' => 16, 'name' => ' Colônia Malhada'],
            ['id_city' => 10364, 'id_state' => 16, 'name' => ' Rondinha'],
            ['id_city' => 10365, 'id_state' => 4, 'name' => ' Caiambé'],
            ['id_city' => 10366, 'id_state' => 6, 'name' => ' Corrente'],
            ['id_city' => 10367, 'id_state' => 6, 'name' => ' Pratiús'],
            ['id_city' => 10368, 'id_state' => 21, 'name' => ' Palma'],
            ['id_city' => 10369, 'id_state' => 21, 'name' => ' São Valentim'],
            ['id_city' => 10370, 'id_state' => 21, 'name' => ' Santo Antão'],
            ['id_city' => 10371, 'id_state' => 21, 'name' => ' Saraiva'],
            ['id_city' => 10372, 'id_state' => 21, 'name' => ' São Martinho'],
            ['id_city' => 10373, 'id_state' => 21, 'name' => ' São José da Reserva'],
            ['id_city' => 10374, 'id_state' => 21, 'name' => ' Cerro Alegre Baixo'],
            ['id_city' => 10375, 'id_state' => 6, 'name' => ' Capitão Mor'],
            ['id_city' => 10376, 'id_state' => 6, 'name' => ' Poço Verde'],
            ['id_city' => 10377, 'id_state' => 22, 'name' => ' Nova Dimensão'],
            ['id_city' => 10378, 'id_state' => 22, 'name' => ' Nova Conquista'],
            ['id_city' => 10379, 'id_state' => 9, 'name' => ' Vazante'],
            ['id_city' => 10380, 'id_state' => 9, 'name' => ' Prata'],
            ['id_city' => 10381, 'id_state' => 15, 'name' => ' Tanques'],
            ['id_city' => 10382, 'id_state' => 11, 'name' => ' Brianorte'],
            ['id_city' => 10383, 'id_state' => 5, 'name' => ' Adro de São Gonçalo'],
            ['id_city' => 10384, 'id_state' => 5, 'name' => ' Barrocão'],
            ['id_city' => 10385, 'id_state' => 5, 'name' => ' Florestal'],
            ['id_city' => 10386, 'id_state' => 5, 'name' => ' Raspador'],
            ['id_city' => 10387, 'id_state' => 5, 'name' => ' Tracupa'],
            ['id_city' => 10388, 'id_state' => 5, 'name' => ' Umbuzeiro'],
            ['id_city' => 10389, 'id_state' => 13, 'name' => ' Santo Antônio do Salto'],
            ['id_city' => 10390, 'id_state' => 13, 'name' => ' Lavras Novas'],
            ['id_city' => 10391, 'id_state' => 13, 'name' => ' São Manoel do Boi'],
            ['id_city' => 10392, 'id_state' => 21, 'name' => ' Vila Cristina'],
            ['id_city' => 10393, 'id_state' => 21, 'name' => ' Cinco da Boa Vista'],
            ['id_city' => 10394, 'id_state' => 21, 'name' => ' Pedras Brancas'],
            ['id_city' => 10395, 'id_state' => 21, 'name' => ' Capão da Herança'],
            ['id_city' => 10396, 'id_state' => 21, 'name' => ' Bela Vista'],
            ['id_city' => 10397, 'id_state' => 21, 'name' => ' Capão Grande'],
            ['id_city' => 10398, 'id_state' => 21, 'name' => ' Bom Retiro'],
            ['id_city' => 10399, 'id_state' => 21, 'name' => ' Fazenda das Laranjeiras'],
            ['id_city' => 10400, 'id_state' => 21, 'name' => ' Vila Ituim'],
            ['id_city' => 10401, 'id_state' => 21, 'name' => ' Morro Grande'],
            ['id_city' => 10402, 'id_state' => 21, 'name' => ' Encruzilhada São Sebastião'],
            ['id_city' => 10403, 'id_state' => 21, 'name' => ' Várzea dos Antunes'],
            ['id_city' => 10404, 'id_state' => 21, 'name' => ' Santa Rita'],
            ['id_city' => 10405, 'id_state' => 21, 'name' => ' Faxinal Preto'],
            ['id_city' => 10406, 'id_state' => 21, 'name' => ' São Gonçalo'],
            ['id_city' => 10407, 'id_state' => 21, 'name' => ' Várzea'],
            ['id_city' => 10408, 'id_state' => 21, 'name' => ' Capão do Tigre'],
            ['id_city' => 10409, 'id_state' => 21, 'name' => ' Capela São Francisco'],
            ['id_city' => 10410, 'id_state' => 21, 'name' => ' Casa Branca'],
            ['id_city' => 10411, 'id_state' => 21, 'name' => ' Boqueirão'],
            ['id_city' => 10412, 'id_state' => 21, 'name' => ' Sítio do Herval'],
            ['id_city' => 10413, 'id_state' => 21, 'name' => ' Nossa Senhora de Fátima'],
            ['id_city' => 10414, 'id_state' => 21, 'name' => ' Nossa Senhora da Saúde'],
            ['id_city' => 10415, 'id_state' => 21, 'name' => ' São Luiz'],
            ['id_city' => 10416, 'id_state' => 21, 'name' => ' Catanduva Grande'],
            ['id_city' => 10417, 'id_state' => 21, 'name' => ' Evaristo'],
            ['id_city' => 10418, 'id_state' => 21, 'name' => ' Pinheirinhos'],
            ['id_city' => 10419, 'id_state' => 21, 'name' => ' Sanga Funda'],
            ['id_city' => 10420, 'id_state' => 21, 'name' => ' Butiatuva'],
            ['id_city' => 10421, 'id_state' => 21, 'name' => ' Casa Velha'],
            ['id_city' => 10422, 'id_state' => 21, 'name' => ' Granja Getúlio Vargas'],
            ['id_city' => 10423, 'id_state' => 21, 'name' => ' Capão Novo'],
            ['id_city' => 10424, 'id_state' => 21, 'name' => ' Arroio Teixeira'],
            ['id_city' => 10425, 'id_state' => 21, 'name' => ' Arroio dos Mengues'],
            ['id_city' => 10426, 'id_state' => 21, 'name' => ' Morro dos Leffas'],
            ['id_city' => 10427, 'id_state' => 21, 'name' => ' Porto Colônia'],
            ['id_city' => 10428, 'id_state' => 21, 'name' => ' Rio do Terra'],
            ['id_city' => 10429, 'id_state' => 21, 'name' => ' Rainha do Mar'],
            ['id_city' => 10430, 'id_state' => 21, 'name' => ' Guará'],
            ['id_city' => 10431, 'id_state' => 21, 'name' => ' Estância Velha'],
            ['id_city' => 10432, 'id_state' => 21, 'name' => ' Nova Tramandaí'],
            ['id_city' => 10433, 'id_state' => 21, 'name' => ' Pega Fogo'],
            ['id_city' => 10434, 'id_state' => 21, 'name' => ' Francesa Alta'],
            ['id_city' => 10435, 'id_state' => 21, 'name' => ' General Neto'],
            ['id_city' => 10436, 'id_state' => 21, 'name' => ' Campinho'],
            ['id_city' => 10437, 'id_state' => 21, 'name' => ' Linha São João'],
            ['id_city' => 10438, 'id_state' => 21, 'name' => ' Arlindo'],
            ['id_city' => 10439, 'id_state' => 21, 'name' => ' Estância Nova'],
            ['id_city' => 10440, 'id_state' => 21, 'name' => ' Palanque'],
            ['id_city' => 10441, 'id_state' => 21, 'name' => ' Santa Emília'],
            ['id_city' => 10442, 'id_state' => 21, 'name' => ' Vale do Sampaio'],
            ['id_city' => 10443, 'id_state' => 21, 'name' => ' Sampaio'],
            ['id_city' => 10444, 'id_state' => 21, 'name' => ' Arroio Bonito'],
            ['id_city' => 10445, 'id_state' => 21, 'name' => ' Santo Antônio'],
            ['id_city' => 10446, 'id_state' => 21, 'name' => ' Poço Fundo'],
            ['id_city' => 10447, 'id_state' => 21, 'name' => ' Amoras'],
            ['id_city' => 10448, 'id_state' => 21, 'name' => ' Glória'],
            ['id_city' => 10449, 'id_state' => 21, 'name' => ' Novo Paraíso'],
            ['id_city' => 10450, 'id_state' => 21, 'name' => ' Pontes Filho'],
            ['id_city' => 10451, 'id_state' => 21, 'name' => ' Bela Vista do Fão'],
            ['id_city' => 10452, 'id_state' => 21, 'name' => ' Tamanduá'],
            ['id_city' => 10453, 'id_state' => 21, 'name' => ' Batovira'],
            ['id_city' => 10454, 'id_state' => 21, 'name' => ' Constantino'],
            ['id_city' => 10455, 'id_state' => 21, 'name' => ' Xaxim'],
            ['id_city' => 10456, 'id_state' => 21, 'name' => ' Forqueta'],
            ['id_city' => 10457, 'id_state' => 21, 'name' => ' Vale do Arroio Grande'],
            ['id_city' => 10458, 'id_state' => 21, 'name' => ' Palmas'],
            ['id_city' => 10459, 'id_state' => 21, 'name' => ' Xarqueada'],
            ['id_city' => 10460, 'id_state' => 21, 'name' => ' Pinhal Queimado'],
            ['id_city' => 10461, 'id_state' => 21, 'name' => ' Santa Rita do Sul'],
            ['id_city' => 10462, 'id_state' => 21, 'name' => ' Bandeirinha'],
            ['id_city' => 10463, 'id_state' => 21, 'name' => ' Capela Santo Antônio'],
            ['id_city' => 10464, 'id_state' => 21, 'name' => ' Cordeiro'],
            ['id_city' => 10465, 'id_state' => 21, 'name' => ' Bom Será'],
            ['id_city' => 10466, 'id_state' => 21, 'name' => ' Passo do Mendonça'],
            ['id_city' => 10467, 'id_state' => 21, 'name' => ' Atlântico'],
            ['id_city' => 10468, 'id_state' => 21, 'name' => ' Taim'],
            ['id_city' => 10469, 'id_state' => 21, 'name' => ' Coxilha do Lageado'],
            ['id_city' => 10470, 'id_state' => 21, 'name' => ' Bote'],
            ['id_city' => 10471, 'id_state' => 21, 'name' => ' Cerro Chato'],
            ['id_city' => 10472, 'id_state' => 21, 'name' => ' Mingote'],
            ['id_city' => 10473, 'id_state' => 21, 'name' => ' Jaguarão Chico'],
            ['id_city' => 10474, 'id_state' => 21, 'name' => ' Vila Freire'],
            ['id_city' => 10475, 'id_state' => 21, 'name' => ' Alto Alegre'],
            ['id_city' => 10476, 'id_state' => 21, 'name' => ' Candiota'],
            ['id_city' => 10477, 'id_state' => 21, 'name' => ' Baú'],
            ['id_city' => 10478, 'id_state' => 21, 'name' => ' Jaguarão Grande'],
            ['id_city' => 10479, 'id_state' => 21, 'name' => ' Passo Real de Candiota'],
            ['id_city' => 10480, 'id_state' => 21, 'name' => ' Seival'],
            ['id_city' => 10481, 'id_state' => 21, 'name' => ' Coronel Prestes'],
            ['id_city' => 10482, 'id_state' => 21, 'name' => ' Santa Bárbara'],
            ['id_city' => 10483, 'id_state' => 21, 'name' => ' Capitão Noronha'],
            ['id_city' => 10484, 'id_state' => 21, 'name' => ' Maria Santa'],
            ['id_city' => 10485, 'id_state' => 21, 'name' => ' Pompeu Machado'],
            ['id_city' => 10486, 'id_state' => 21, 'name' => ' Cerro Partido'],
            ['id_city' => 10487, 'id_state' => 21, 'name' => ' Aroeiras'],
            ['id_city' => 10488, 'id_state' => 21, 'name' => ' Monte Castelo'],
            ['id_city' => 10489, 'id_state' => 21, 'name' => ' Várzea'],
            ['id_city' => 10490, 'id_state' => 21, 'name' => ' Douradilho'],
            ['id_city' => 10491, 'id_state' => 21, 'name' => ' Campo de Sobradinho'],
            ['id_city' => 10492, 'id_state' => 21, 'name' => ' Murta'],
            ['id_city' => 10493, 'id_state' => 21, 'name' => ' Pitingal'],
            ['id_city' => 10494, 'id_state' => 21, 'name' => ' Linha Ocidental'],
            ['id_city' => 10495, 'id_state' => 21, 'name' => ' Sítio Alto'],
            ['id_city' => 10496, 'id_state' => 21, 'name' => ' Taboãozinho'],
            ['id_city' => 10497, 'id_state' => 21, 'name' => ' Taquaral'],
            ['id_city' => 10498, 'id_state' => 21, 'name' => ' Itaúba'],
            ['id_city' => 10499, 'id_state' => 21, 'name' => ' Rincão da Estrela'],
            ['id_city' => 10500, 'id_state' => 21, 'name' => ' São Luiz'],
            ['id_city' => 10501, 'id_state' => 21, 'name' => ' Vila Block'],
            ['id_city' => 10502, 'id_state' => 21, 'name' => ' Xiniquá'],
            ['id_city' => 10503, 'id_state' => 21, 'name' => ' Linha Bonita'],
            ['id_city' => 10504, 'id_state' => 21, 'name' => ' Boa Vista'],
            ['id_city' => 10505, 'id_state' => 21, 'name' => ' Barragem do Itu'],
            ['id_city' => 10506, 'id_state' => 21, 'name' => ' Piraju'],
            ['id_city' => 10507, 'id_state' => 21, 'name' => ' Capela São Paulo'],
            ['id_city' => 10508, 'id_state' => 21, 'name' => ' Rincao dos Pintos'],
            ['id_city' => 10509, 'id_state' => 21, 'name' => ' Linha Harmonia'],
            ['id_city' => 10510, 'id_state' => 21, 'name' => ' Linha Porto Alegre'],
            ['id_city' => 10511, 'id_state' => 21, 'name' => ' Fazenda Colorado'],
            ['id_city' => 10512, 'id_state' => 21, 'name' => ' São João dos Mellos'],
            ['id_city' => 10513, 'id_state' => 21, 'name' => ' Três Mártires'],
            ['id_city' => 10514, 'id_state' => 21, 'name' => ' Rincão do Appel'],
            ['id_city' => 10515, 'id_state' => 21, 'name' => ' Itaíba'],
            ['id_city' => 10516, 'id_state' => 21, 'name' => ' Capão Alto'],
            ['id_city' => 10517, 'id_state' => 21, 'name' => ' Santa Rosa'],
            ['id_city' => 10518, 'id_state' => 21, 'name' => ' São Bento'],
            ['id_city' => 10519, 'id_state' => 21, 'name' => ' São João'],
            ['id_city' => 10520, 'id_state' => 21, 'name' => ' Barrinha'],
            ['id_city' => 10521, 'id_state' => 21, 'name' => ' Lajeado Bonito'],
            ['id_city' => 10522, 'id_state' => 21, 'name' => ' Capivara'],
            ['id_city' => 10523, 'id_state' => 21, 'name' => ' Vista Gaúcha'],
            ['id_city' => 10524, 'id_state' => 21, 'name' => ' São Valentin da Gruta'],
            ['id_city' => 10525, 'id_state' => 21, 'name' => ' Braço Forte'],
            ['id_city' => 10526, 'id_state' => 21, 'name' => ' São Pedro'],
            ['id_city' => 10527, 'id_state' => 21, 'name' => ' Sítio Cassemiro'],
            ['id_city' => 10528, 'id_state' => 21, 'name' => ' Rincão dos Paivas'],
            ['id_city' => 10529, 'id_state' => 21, 'name' => ' Nossa Senhora de Fátima'],
            ['id_city' => 10530, 'id_state' => 21, 'name' => ' Alto Erval Novo'],
            ['id_city' => 10531, 'id_state' => 21, 'name' => ' Santo Antônio'],
            ['id_city' => 10532, 'id_state' => 21, 'name' => ' Açoita Cavalo'],
            ['id_city' => 10533, 'id_state' => 21, 'name' => ' Bom Jardim'],
            ['id_city' => 10534, 'id_state' => 21, 'name' => ' Lara'],
            ['id_city' => 10535, 'id_state' => 21, 'name' => ' Ismael'],
            ['id_city' => 10536, 'id_state' => 21, 'name' => ' Vista Nova'],
            ['id_city' => 10537, 'id_state' => 21, 'name' => ' Monte Belo'],
            ['id_city' => 10538, 'id_state' => 21, 'name' => ' Alto Uruguai'],
            ['id_city' => 10539, 'id_state' => 21, 'name' => ' Porto Soberbo'],
            ['id_city' => 10540, 'id_state' => 21, 'name' => ' Esquina Brasil Neves'],
            ['id_city' => 10541, 'id_state' => 21, 'name' => ' Pontão Santo Antônio'],
            ['id_city' => 10542, 'id_state' => 21, 'name' => ' Rincão dos Meoti'],
            ['id_city' => 10543, 'id_state' => 21, 'name' => ' Rincão dos Roratos'],
            ['id_city' => 10544, 'id_state' => 21, 'name' => ' Ressaca do Buriti'],
            ['id_city' => 10545, 'id_state' => 21, 'name' => ' Sossego'],
            ['id_city' => 10546, 'id_state' => 21, 'name' => ' União'],
            ['id_city' => 10547, 'id_state' => 21, 'name' => ' Lejeado Micuim'],
            ['id_city' => 10548, 'id_state' => 21, 'name' => ' Campestre'],
            ['id_city' => 10549, 'id_state' => 21, 'name' => ' São José'],
            ['id_city' => 10550, 'id_state' => 21, 'name' => ' Mato Grande'],
            ['id_city' => 10551, 'id_state' => 21, 'name' => ' Rincão dos Moraes'],
            ['id_city' => 10552, 'id_state' => 21, 'name' => ' São João das Missões'],
            ['id_city' => 10553, 'id_state' => 21, 'name' => ' Quinze de Novembro'],
            ['id_city' => 10554, 'id_state' => 21, 'name' => ' Rincão dos Mellos'],
            ['id_city' => 10555, 'id_state' => 21, 'name' => ' Rincão Maciel'],
            ['id_city' => 10556, 'id_state' => 21, 'name' => ' São Paulo das Tunas'],
            ['id_city' => 10557, 'id_state' => 21, 'name' => ' Giruazinho'],
            ['id_city' => 10558, 'id_state' => 21, 'name' => ' Barrinha'],
            ['id_city' => 10559, 'id_state' => 21, 'name' => ' Pratos'],
            ['id_city' => 10560, 'id_state' => 21, 'name' => ' Rincão Comprido'],
            ['id_city' => 10561, 'id_state' => 21, 'name' => ' Laranjeira'],
            ['id_city' => 10562, 'id_state' => 21, 'name' => ' Veado Pardo'],
            ['id_city' => 10563, 'id_state' => 21, 'name' => ' São Miguel']
        ]);
    }
}