<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        if(DB::table('vpr_countries_states_cities' )->count() == 0){
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 1, 'id_state' => 1, 'name' => ' Acrelândia'],
                ['id_city' => 2, 'id_state' => 1, 'name' => ' Assis Brasil'],
                ['id_city' => 3, 'id_state' => 1, 'name' => ' Brasiléia'],
                ['id_city' => 4, 'id_state' => 1, 'name' => ' Bujari'],
                ['id_city' => 5, 'id_state' => 1, 'name' => ' Capixaba'],
                ['id_city' => 6, 'id_state' => 1, 'name' => ' Cruzeiro do Sul'],
                ['id_city' => 7, 'id_state' => 1, 'name' => ' Epitaciolândia'],
                ['id_city' => 8, 'id_state' => 1, 'name' => ' Feijó'],
                ['id_city' => 9, 'id_state' => 1, 'name' => ' Jordão'],
                ['id_city' => 10, 'id_state' => 1, 'name' => ' Mâncio Lima'],
                ['id_city' => 11, 'id_state' => 1, 'name' => ' Manoel Urbano'],
                ['id_city' => 12, 'id_state' => 1, 'name' => ' Marechal Thaumaturgo'],
                ['id_city' => 13, 'id_state' => 1, 'name' => ' Plácido de Castro'],
                ['id_city' => 14, 'id_state' => 1, 'name' => ' Porto Acre'],
                ['id_city' => 15, 'id_state' => 1, 'name' => ' Porto Walter'],
                ['id_city' => 16, 'id_state' => 1, 'name' => ' Rio Branco'],
                ['id_city' => 17, 'id_state' => 1, 'name' => ' Rodrigues Alves'],
                ['id_city' => 18, 'id_state' => 1, 'name' => ' Santa Rosa do Purus'],
                ['id_city' => 19, 'id_state' => 1, 'name' => ' Sena Madureira'],
                ['id_city' => 20, 'id_state' => 1, 'name' => ' Senador Guiomard'],
                ['id_city' => 21, 'id_state' => 1, 'name' => ' Tarauacá'],
                ['id_city' => 22, 'id_state' => 1, 'name' => ' Xapuri'],
                ['id_city' => 23, 'id_state' => 2, 'name' => ' Água Branca'],
                ['id_city' => 24, 'id_state' => 2, 'name' => ' Alazão'],
                ['id_city' => 25, 'id_state' => 2, 'name' => ' Alecrim'],
                ['id_city' => 26, 'id_state' => 2, 'name' => ' Anadia'],
                ['id_city' => 27, 'id_state' => 2, 'name' => ' Anel'],
                ['id_city' => 28, 'id_state' => 2, 'name' => ' Anum Novo'],
                ['id_city' => 29, 'id_state' => 2, 'name' => ' Anum Velho'],
                ['id_city' => 30, 'id_state' => 2, 'name' => ' Arapiraca'],
                ['id_city' => 31, 'id_state' => 2, 'name' => ' Atalaia'],
                ['id_city' => 32, 'id_state' => 2, 'name' => ' Baixa da Onça'],
                ['id_city' => 33, 'id_state' => 2, 'name' => ' Baixa do Capim'],
                ['id_city' => 34, 'id_state' => 2, 'name' => ' Bálsamo'],
                ['id_city' => 35, 'id_state' => 2, 'name' => ' Bananeiras'],
                ['id_city' => 36, 'id_state' => 2, 'name' => ' Barra de Santo Antônio'],
                ['id_city' => 37, 'id_state' => 2, 'name' => ' Barra de São Miguel'],
                ['id_city' => 38, 'id_state' => 2, 'name' => ' Barra do Bonifácio'],
                ['id_city' => 39, 'id_state' => 2, 'name' => ' Barra Grande'],
                ['id_city' => 40, 'id_state' => 2, 'name' => ' Batalha'],
                ['id_city' => 41, 'id_state' => 2, 'name' => ' Batingas'],
                ['id_city' => 42, 'id_state' => 2, 'name' => ' Belém'],
                ['id_city' => 43, 'id_state' => 2, 'name' => ' Belo Monte'],
                ['id_city' => 44, 'id_state' => 2, 'name' => ' Boa Sorte'],
                ['id_city' => 45, 'id_state' => 2, 'name' => ' Boa Vista'],
                ['id_city' => 46, 'id_state' => 2, 'name' => ' Boca da Mata'],
                ['id_city' => 47, 'id_state' => 2, 'name' => ' Bom Jardim'],
                ['id_city' => 48, 'id_state' => 2, 'name' => ' Bonifácio'],
                ['id_city' => 49, 'id_state' => 2, 'name' => ' Branquinha'],
                ['id_city' => 50, 'id_state' => 2, 'name' => ' Cacimbinhas'],
                ['id_city' => 51, 'id_state' => 2, 'name' => ' Cajarana'],
                ['id_city' => 52, 'id_state' => 2, 'name' => ' Cajueiro'],
                ['id_city' => 53, 'id_state' => 2, 'name' => ' Caldeirões de Cima'],
                ['id_city' => 54, 'id_state' => 2, 'name' => ' Camadanta'],
                ['id_city' => 55, 'id_state' => 2, 'name' => ' Campestre'],
                ['id_city' => 56, 'id_state' => 2, 'name' => ' Campo Alegre'],
                ['id_city' => 57, 'id_state' => 2, 'name' => ' Campo Grande'],
                ['id_city' => 58, 'id_state' => 2, 'name' => ' Canaã'],
                ['id_city' => 59, 'id_state' => 2, 'name' => ' Canafístula'],
                ['id_city' => 60, 'id_state' => 2, 'name' => ' Canapi'],
                ['id_city' => 61, 'id_state' => 2, 'name' => ' Canastra'],
                ['id_city' => 62, 'id_state' => 2, 'name' => ' Cangandu'],
                ['id_city' => 63, 'id_state' => 2, 'name' => ' Capela'],
                ['id_city' => 64, 'id_state' => 2, 'name' => ' Carneiros'],
                ['id_city' => 65, 'id_state' => 2, 'name' => ' Carrasco'],
                ['id_city' => 66, 'id_state' => 2, 'name' => ' Chã Preta'],
                ['id_city' => 67, 'id_state' => 2, 'name' => ' Coité do Nóia'],
                ['id_city' => 68, 'id_state' => 2, 'name' => ' Colônia Leopoldina'],
                ['id_city' => 69, 'id_state' => 2, 'name' => ' Coqueiro Seco'],
                ['id_city' => 70, 'id_state' => 2, 'name' => ' Coruripe'],
                ['id_city' => 71, 'id_state' => 2, 'name' => ' Coruripe da Cal'],
                ['id_city' => 72, 'id_state' => 2, 'name' => ' Craíbas'],
                ['id_city' => 73, 'id_state' => 2, 'name' => ' Delmiro Gouveia'],
                ['id_city' => 74, 'id_state' => 2, 'name' => ' Dois Riachos'],
                ['id_city' => 75, 'id_state' => 2, 'name' => ' Entremontes'],
                ['id_city' => 76, 'id_state' => 2, 'name' => ' Estrela de Alagoas'],
                ['id_city' => 77, 'id_state' => 2, 'name' => ' Feira Grande'],
                ['id_city' => 78, 'id_state' => 2, 'name' => ' Feliz Deserto'],
                ['id_city' => 79, 'id_state' => 2, 'name' => ' Flexeiras'],
                ['id_city' => 80, 'id_state' => 2, 'name' => ' Gaspar'],
                ['id_city' => 81, 'id_state' => 2, 'name' => ' Girau do Ponciano'],
                ['id_city' => 82, 'id_state' => 2, 'name' => ' Ibateguara'],
                ['id_city' => 83, 'id_state' => 2, 'name' => ' Igaci'],
                ['id_city' => 84, 'id_state' => 2, 'name' => ' Igreja Nova'],
                ['id_city' => 85, 'id_state' => 2, 'name' => ' Inhapi'],
                ['id_city' => 86, 'id_state' => 2, 'name' => ' Jacaré dos Homens'],
                ['id_city' => 87, 'id_state' => 2, 'name' => ' Jacuípe'],
                ['id_city' => 88, 'id_state' => 2, 'name' => ' Japaratinga'],
                ['id_city' => 89, 'id_state' => 2, 'name' => ' Jaramataia'],
                ['id_city' => 90, 'id_state' => 2, 'name' => ' Jenipapo'],
                ['id_city' => 91, 'id_state' => 2, 'name' => ' Joaquim Gomes'],
                ['id_city' => 92, 'id_state' => 2, 'name' => ' Jundiá'],
                ['id_city' => 93, 'id_state' => 2, 'name' => ' Junqueiro'],
                ['id_city' => 94, 'id_state' => 2, 'name' => ' Lagoa da Areia'],
                ['id_city' => 95, 'id_state' => 2, 'name' => ' Lagoa da Canoa'],
                ['id_city' => 96, 'id_state' => 2, 'name' => ' Lagoa da Pedra'],
                ['id_city' => 97, 'id_state' => 2, 'name' => ' Lagoa Dantas'],
                ['id_city' => 98, 'id_state' => 2, 'name' => ' Lagoa do Caldeirão'],
                ['id_city' => 99, 'id_state' => 2, 'name' => ' Lagoa do Canto'],
                ['id_city' => 100, 'id_state' => 2, 'name' => ' Lagoa do Exú'],
                ['id_city' => 101, 'id_state' => 2, 'name' => ' Lagoa do Rancho'],
                ['id_city' => 102, 'id_state' => 2, 'name' => ' Lajes do Caldeirão'],
                ['id_city' => 103, 'id_state' => 2, 'name' => ' Laranjal'],
                ['id_city' => 104, 'id_state' => 2, 'name' => ' Limoeiro de Anadia'],
                ['id_city' => 105, 'id_state' => 2, 'name' => ' Maceió'],
                ['id_city' => 106, 'id_state' => 2, 'name' => ' Major Isidoro'],
                ['id_city' => 107, 'id_state' => 2, 'name' => ' Mar Vermelho'],
                ['id_city' => 108, 'id_state' => 2, 'name' => ' Maragogi'],
                ['id_city' => 109, 'id_state' => 2, 'name' => ' Maravilha'],
                ['id_city' => 110, 'id_state' => 2, 'name' => ' Marechal Deodoro'],
                ['id_city' => 111, 'id_state' => 2, 'name' => ' Maribondo'],
                ['id_city' => 112, 'id_state' => 2, 'name' => ' Massaranduba'],
                ['id_city' => 113, 'id_state' => 2, 'name' => ' Mata Grande'],
                ['id_city' => 114, 'id_state' => 2, 'name' => ' Matriz de Camaragibe'],
                ['id_city' => 115, 'id_state' => 2, 'name' => ' Messias'],
                ['id_city' => 116, 'id_state' => 2, 'name' => ' Minador do Negrão'],
                ['id_city' => 117, 'id_state' => 2, 'name' => ' Monteirópolis'],
                ['id_city' => 118, 'id_state' => 2, 'name' => ' Moreira'],
                ['id_city' => 119, 'id_state' => 2, 'name' => ' Munguba'],
                ['id_city' => 120, 'id_state' => 2, 'name' => ' Murici'],
                ['id_city' => 121, 'id_state' => 2, 'name' => ' Novo Lino'],
                ['id_city' => 122, 'id_state' => 2, 'name' => ' Olho D Água Grande'],
                ['id_city' => 123, 'id_state' => 2, 'name' => ' Olho D Água das Flores'],
                ['id_city' => 124, 'id_state' => 2, 'name' => ' Olho D Água de Cima'],
                ['id_city' => 125, 'id_state' => 2, 'name' => ' Olho D Água do Casado'],
                ['id_city' => 126, 'id_state' => 2, 'name' => ' Olho D Água dos Dandanhas'],
                ['id_city' => 127, 'id_state' => 2, 'name' => ' Olivença'],
                ['id_city' => 128, 'id_state' => 2, 'name' => ' Ouro Branco'],
                ['id_city' => 129, 'id_state' => 2, 'name' => ' Palestina'],
                ['id_city' => 130, 'id_state' => 2, 'name' => ' Palmeira de Fora'],
                ['id_city' => 131, 'id_state' => 2, 'name' => ' Palmeira dos Índios'],
                ['id_city' => 132, 'id_state' => 2, 'name' => ' Pão de Açúcar'],
                ['id_city' => 133, 'id_state' => 2, 'name' => ' Pariconha'],
                ['id_city' => 134, 'id_state' => 2, 'name' => ' Paripueira'],
                ['id_city' => 135, 'id_state' => 2, 'name' => ' Passo de Camaragibe'],
                ['id_city' => 136, 'id_state' => 2, 'name' => ' Pau D Arco'],
                ['id_city' => 137, 'id_state' => 2, 'name' => ' Pau Ferro'],
                ['id_city' => 138, 'id_state' => 2, 'name' => ' Paulo Jacinto'],
                ['id_city' => 139, 'id_state' => 2, 'name' => ' Penedo'],
                ['id_city' => 140, 'id_state' => 2, 'name' => ' Piaçabuçu'],
                ['id_city' => 141, 'id_state' => 2, 'name' => ' Pilar'],
                ['id_city' => 142, 'id_state' => 2, 'name' => ' Pindoba'],
                ['id_city' => 143, 'id_state' => 2, 'name' => ' Piranhas'],
                ['id_city' => 144, 'id_state' => 2, 'name' => ' Poção'],
                ['id_city' => 145, 'id_state' => 2, 'name' => ' Poço da Pedra'],
                ['id_city' => 146, 'id_state' => 2, 'name' => ' Poço das Trincheiras'],
                ['id_city' => 147, 'id_state' => 2, 'name' => ' Porto Calvo'],
                ['id_city' => 148, 'id_state' => 2, 'name' => ' Porto de Pedras'],
                ['id_city' => 149, 'id_state' => 2, 'name' => ' Porto Real do Colégio'],
                ['id_city' => 150, 'id_state' => 2, 'name' => ' Poxim'],
                ['id_city' => 151, 'id_state' => 2, 'name' => ' Quebrangulo'],
                ['id_city' => 152, 'id_state' => 2, 'name' => ' Riacho do Sertão'],
                ['id_city' => 153, 'id_state' => 2, 'name' => ' Riacho Fundo de Cima'],
                ['id_city' => 154, 'id_state' => 2, 'name' => ' Rio Largo'],
                ['id_city' => 155, 'id_state' => 2, 'name' => ' Rocha Cavalcante'],
                ['id_city' => 156, 'id_state' => 2, 'name' => ' Roteiro'],
                ['id_city' => 157, 'id_state' => 2, 'name' => ' Santa Efigênia'],
                ['id_city' => 158, 'id_state' => 2, 'name' => ' Santa Luzia do Norte'],
                ['id_city' => 159, 'id_state' => 2, 'name' => ' Santana do Ipanema'],
                ['id_city' => 160, 'id_state' => 2, 'name' => ' Santana do Mundaú'],
                ['id_city' => 161, 'id_state' => 2, 'name' => ' Santo Antônio'],
                ['id_city' => 162, 'id_state' => 2, 'name' => ' São Brás'],
                ['id_city' => 163, 'id_state' => 2, 'name' => ' São José da Laje'],
                ['id_city' => 164, 'id_state' => 2, 'name' => ' São José da Tapera'],
                ['id_city' => 165, 'id_state' => 2, 'name' => ' São Luís do Quitunde'],
                ['id_city' => 166, 'id_state' => 2, 'name' => ' São Miguel dos Campos'],
                ['id_city' => 167, 'id_state' => 2, 'name' => ' São Miguel dos Milagres'],
                ['id_city' => 168, 'id_state' => 2, 'name' => ' São Sebastião'],
                ['id_city' => 169, 'id_state' => 2, 'name' => ' Sapucaia'],
                ['id_city' => 170, 'id_state' => 2, 'name' => ' Satuba'],
                ['id_city' => 171, 'id_state' => 2, 'name' => ' Senador Rui Palmeira'],
                ['id_city' => 172, 'id_state' => 2, 'name' => ' Serra da Mandioca'],
                ['id_city' => 173, 'id_state' => 2, 'name' => ' Serra do São José'],
                ['id_city' => 174, 'id_state' => 2, 'name' => ' Taboleiro do Pinto'],
                ['id_city' => 175, 'id_state' => 2, 'name' => ' Taboquinha'],
                ['id_city' => 176, 'id_state' => 2, 'name' => ' Tanque D Arca'],
                ['id_city' => 177, 'id_state' => 2, 'name' => ' Taquarana'],
                ['id_city' => 178, 'id_state' => 2, 'name' => ' Tatuamunha'],
                ['id_city' => 179, 'id_state' => 2, 'name' => ' Teotônio Vilela'],
                ['id_city' => 180, 'id_state' => 2, 'name' => ' Traipu'],
                ['id_city' => 181, 'id_state' => 2, 'name' => ' União dos Palmares'],
                ['id_city' => 182, 'id_state' => 2, 'name' => ' Usina Camaçari'],
                ['id_city' => 183, 'id_state' => 2, 'name' => ' Viçosa'],
                ['id_city' => 184, 'id_state' => 2, 'name' => ' Vila Aparecida'],
                ['id_city' => 185, 'id_state' => 2, 'name' => ' Vila São Francisco'],
                ['id_city' => 186, 'id_state' => 4, 'name' => ' Alvarães'],
                ['id_city' => 187, 'id_state' => 4, 'name' => ' Amatari'],
                ['id_city' => 188, 'id_state' => 4, 'name' => ' Amaturá'],
                ['id_city' => 189, 'id_state' => 4, 'name' => ' Anamã'],
                ['id_city' => 190, 'id_state' => 4, 'name' => ' Anori'],
                ['id_city' => 191, 'id_state' => 4, 'name' => ' Apuí'],
                ['id_city' => 192, 'id_state' => 4, 'name' => ' Ariaú'],
                ['id_city' => 193, 'id_state' => 4, 'name' => ' Atalaia do Norte'],
                ['id_city' => 194, 'id_state' => 4, 'name' => ' Augusto Montenegro'],
                ['id_city' => 195, 'id_state' => 4, 'name' => ' Autazes'],
                ['id_city' => 196, 'id_state' => 4, 'name' => ' Axinim'],
                ['id_city' => 197, 'id_state' => 4, 'name' => ' Badajós'],
                ['id_city' => 198, 'id_state' => 4, 'name' => ' Balbina'],
                ['id_city' => 199, 'id_state' => 4, 'name' => ' Barcelos'],
                ['id_city' => 200, 'id_state' => 4, 'name' => ' Barreirinha'],
                ['id_city' => 201, 'id_state' => 4, 'name' => ' Benjamin Constant'],
                ['id_city' => 202, 'id_state' => 4, 'name' => ' Beruri'],
                ['id_city' => 203, 'id_state' => 4, 'name' => ' Boa Vista do Ramos'],
                ['id_city' => 204, 'id_state' => 4, 'name' => ' Boca do Acre'],
                ['id_city' => 205, 'id_state' => 4, 'name' => ' Borba'],
                ['id_city' => 206, 'id_state' => 4, 'name' => ' Caapiranga'],
                ['id_city' => 207, 'id_state' => 4, 'name' => ' Cametá'],
                ['id_city' => 208, 'id_state' => 4, 'name' => ' Canumã'],
                ['id_city' => 209, 'id_state' => 4, 'name' => ' Canutama'],
                ['id_city' => 210, 'id_state' => 4, 'name' => ' Carauari'],
                ['id_city' => 211, 'id_state' => 4, 'name' => ' Careiro'],
                ['id_city' => 212, 'id_state' => 4, 'name' => ' Careiro da Várzea'],
                ['id_city' => 213, 'id_state' => 4, 'name' => ' Carvoeiro'],
                ['id_city' => 214, 'id_state' => 4, 'name' => ' Coari'],
                ['id_city' => 215, 'id_state' => 4, 'name' => ' Codajás'],
                ['id_city' => 216, 'id_state' => 4, 'name' => ' Cucuí'],
                ['id_city' => 217, 'id_state' => 4, 'name' => ' Eirunepé'],
                ['id_city' => 218, 'id_state' => 4, 'name' => ' Envira'],
                ['id_city' => 219, 'id_state' => 4, 'name' => ' Floriano Peixoto'],
                ['id_city' => 220, 'id_state' => 4, 'name' => ' Fonte Boa'],
                ['id_city' => 221, 'id_state' => 4, 'name' => ' Freguesia do Andirá'],
                ['id_city' => 222, 'id_state' => 4, 'name' => ' Guajará'],
                ['id_city' => 223, 'id_state' => 4, 'name' => ' Humaitá'],
                ['id_city' => 224, 'id_state' => 4, 'name' => ' Iauaretê'],
                ['id_city' => 225, 'id_state' => 4, 'name' => ' Içanã'],
                ['id_city' => 226, 'id_state' => 4, 'name' => ' Ipixuna'],
                ['id_city' => 227, 'id_state' => 4, 'name' => ' Iranduba'],
                ['id_city' => 228, 'id_state' => 4, 'name' => ' Itacoatiara'],
                ['id_city' => 229, 'id_state' => 4, 'name' => ' Itamarati'],
                ['id_city' => 230, 'id_state' => 4, 'name' => ' Itapiranga'],
                ['id_city' => 231, 'id_state' => 4, 'name' => ' Japurá'],
                ['id_city' => 232, 'id_state' => 4, 'name' => ' Juruá'],
                ['id_city' => 233, 'id_state' => 4, 'name' => ' Jutaí'],
                ['id_city' => 234, 'id_state' => 4, 'name' => ' Lábrea'],
                ['id_city' => 235, 'id_state' => 4, 'name' => ' Lago Preto'],
                ['id_city' => 236, 'id_state' => 4, 'name' => ' Manacapuru'],
                ['id_city' => 237, 'id_state' => 4, 'name' => ' Manaquiri'],
                ['id_city' => 238, 'id_state' => 4, 'name' => ' Manaus'],
                ['id_city' => 239, 'id_state' => 4, 'name' => ' Manicoré'],
                ['id_city' => 240, 'id_state' => 4, 'name' => ' Maraã'],
                ['id_city' => 241, 'id_state' => 4, 'name' => ' Massauari'],
                ['id_city' => 242, 'id_state' => 4, 'name' => ' Maués'],
                ['id_city' => 243, 'id_state' => 4, 'name' => ' Mocambo'],
                ['id_city' => 244, 'id_state' => 4, 'name' => ' Moura'],
                ['id_city' => 245, 'id_state' => 4, 'name' => ' Murutinga'],
                ['id_city' => 246, 'id_state' => 4, 'name' => ' Nhamundá'],
                ['id_city' => 247, 'id_state' => 4, 'name' => ' Nova Olinda do Norte'],
                ['id_city' => 248, 'id_state' => 4, 'name' => ' Novo Airão'],
                ['id_city' => 249, 'id_state' => 4, 'name' => ' Novo Aripuanã'],
                ['id_city' => 250, 'id_state' => 4, 'name' => ' Osório da Fonseca'],
                ['id_city' => 251, 'id_state' => 4, 'name' => ' Parintins'],
                ['id_city' => 252, 'id_state' => 4, 'name' => ' Pauini'],
                ['id_city' => 253, 'id_state' => 4, 'name' => ' Pedras'],
                ['id_city' => 254, 'id_state' => 4, 'name' => ' Presidente Figueiredo'],
                ['id_city' => 255, 'id_state' => 4, 'name' => ' Repartimento'],
                ['id_city' => 256, 'id_state' => 4, 'name' => ' Rio Preto da Eva'],
                ['id_city' => 257, 'id_state' => 4, 'name' => ' Santa Isabel do Rio Negro'],
                ['id_city' => 258, 'id_state' => 4, 'name' => ' Santa Rita'],
                ['id_city' => 259, 'id_state' => 4, 'name' => ' Santo Antônio do Içá'],
                ['id_city' => 260, 'id_state' => 4, 'name' => ' São Felipe'],
                ['id_city' => 261, 'id_state' => 4, 'name' => ' São Gabriel da Cachoeira'],
                ['id_city' => 262, 'id_state' => 4, 'name' => ' São Paulo de Olivença'],
                ['id_city' => 263, 'id_state' => 4, 'name' => ' São Sebastião do Uatumã'],
                ['id_city' => 264, 'id_state' => 4, 'name' => ' Silves'],
                ['id_city' => 265, 'id_state' => 4, 'name' => ' Tabatinga'],
                ['id_city' => 266, 'id_state' => 4, 'name' => ' Tapauá'],
                ['id_city' => 267, 'id_state' => 4, 'name' => ' Tefé'],
                ['id_city' => 268, 'id_state' => 4, 'name' => ' Tonantins'],
                ['id_city' => 269, 'id_state' => 4, 'name' => ' Uarini'],
                ['id_city' => 270, 'id_state' => 4, 'name' => ' Urucará'],
                ['id_city' => 271, 'id_state' => 4, 'name' => ' Urucurituba'],
                ['id_city' => 272, 'id_state' => 4, 'name' => ' Vila Pitinga'],
                ['id_city' => 273, 'id_state' => 3, 'name' => ' Abacate da Pedreira'],
                ['id_city' => 274, 'id_state' => 3, 'name' => ' Amapá'],
                ['id_city' => 275, 'id_state' => 3, 'name' => ' Amapari'],
                ['id_city' => 276, 'id_state' => 3, 'name' => ' Ambé'],
                ['id_city' => 277, 'id_state' => 3, 'name' => ' Aporema'],
                ['id_city' => 278, 'id_state' => 3, 'name' => ' Ariri'],
                ['id_city' => 279, 'id_state' => 3, 'name' => ' Bailique'],
                ['id_city' => 280, 'id_state' => 3, 'name' => ' Boca do Jari'],
                ['id_city' => 281, 'id_state' => 3, 'name' => ' Calçoene'],
                ['id_city' => 282, 'id_state' => 3, 'name' => ' Cantanzal'],
                ['id_city' => 283, 'id_state' => 3, 'name' => ' Carmo'],
                ['id_city' => 284, 'id_state' => 3, 'name' => ' Clevelândia do Norte'],
                ['id_city' => 285, 'id_state' => 3, 'name' => ' Corre Água'],
                ['id_city' => 286, 'id_state' => 3, 'name' => ' Cunani'],
                ['id_city' => 287, 'id_state' => 3, 'name' => ' Curiaú'],
                ['id_city' => 288, 'id_state' => 3, 'name' => ' Cutias'],
                ['id_city' => 289, 'id_state' => 3, 'name' => ' Fazendinha'],
                ['id_city' => 290, 'id_state' => 3, 'name' => ' Ferreira Gomes'],
                ['id_city' => 291, 'id_state' => 3, 'name' => ' Fortaleza'],
                ['id_city' => 292, 'id_state' => 3, 'name' => ' Gaivota'],
                ['id_city' => 293, 'id_state' => 3, 'name' => ' Gurupora'],
                ['id_city' => 294, 'id_state' => 3, 'name' => ' Igarapé do Lago'],
                ['id_city' => 295, 'id_state' => 3, 'name' => ' Ilha de Santana'],
                ['id_city' => 296, 'id_state' => 3, 'name' => ' Inajá'],
                ['id_city' => 297, 'id_state' => 3, 'name' => ' Itaubal'],
                ['id_city' => 298, 'id_state' => 3, 'name' => ' Laranjal do Jari'],
                ['id_city' => 299, 'id_state' => 3, 'name' => ' Livramento do Pacuí'],
                ['id_city' => 300, 'id_state' => 3, 'name' => ' Lourenço'],
                ['id_city' => 301, 'id_state' => 3, 'name' => ' Macapá'],
                ['id_city' => 302, 'id_state' => 3, 'name' => ' Mazagão'],
                ['id_city' => 303, 'id_state' => 3, 'name' => ' Mazagão Velho'],
                ['id_city' => 304, 'id_state' => 3, 'name' => ' Oiapoque'],
                ['id_city' => 305, 'id_state' => 3, 'name' => ' Paredão'],
                ['id_city' => 306, 'id_state' => 3, 'name' => ' Porto Grande'],
                ['id_city' => 307, 'id_state' => 3, 'name' => ' Pracuúba'],
                ['id_city' => 308, 'id_state' => 3, 'name' => ' Santa Luzia do Pacuí'],
                ['id_city' => 309, 'id_state' => 3, 'name' => ' Santa Maria'],
                ['id_city' => 310, 'id_state' => 3, 'name' => ' Santana'],
                ['id_city' => 311, 'id_state' => 3, 'name' => ' São Joaquim do Pacuí'],
                ['id_city' => 312, 'id_state' => 3, 'name' => ' São Sebastião do Livramento'],
                ['id_city' => 313, 'id_state' => 3, 'name' => ' São Tomé'],
                ['id_city' => 314, 'id_state' => 3, 'name' => ' Sucuriju'],
                ['id_city' => 315, 'id_state' => 3, 'name' => ' Tartarugalzinho'],
                ['id_city' => 316, 'id_state' => 3, 'name' => ' Vila Velha'],
                ['id_city' => 317, 'id_state' => 3, 'name' => ' Vitória do Jari'],
                ['id_city' => 554, 'id_state' => 5, 'name' => ' Abadia'],
                ['id_city' => 555, 'id_state' => 5, 'name' => ' Abaíra'],
                ['id_city' => 556, 'id_state' => 5, 'name' => ' Abaré'],
                ['id_city' => 557, 'id_state' => 5, 'name' => ' Abelhas'],
                ['id_city' => 558, 'id_state' => 5, 'name' => ' Abóbora'],
                ['id_city' => 559, 'id_state' => 5, 'name' => ' Abrantes'],
                ['id_city' => 560, 'id_state' => 5, 'name' => ' Acajutiba'],
                ['id_city' => 561, 'id_state' => 5, 'name' => ' Açu da Torre'],
                ['id_city' => 562, 'id_state' => 5, 'name' => ' Açudina'],
                ['id_city' => 563, 'id_state' => 5, 'name' => ' Acupe'],
                ['id_city' => 564, 'id_state' => 5, 'name' => ' Adustina'],
                ['id_city' => 565, 'id_state' => 5, 'name' => ' Afligidos'],
                ['id_city' => 566, 'id_state' => 5, 'name' => ' Afrânio Peixoto'],
                ['id_city' => 567, 'id_state' => 5, 'name' => ' Água Doce'],
                ['id_city' => 568, 'id_state' => 5, 'name' => ' Água Fria'],
                ['id_city' => 569, 'id_state' => 5, 'name' => ' Águas do Paulista'],
                ['id_city' => 570, 'id_state' => 5, 'name' => ' Aiquara'],
                ['id_city' => 571, 'id_state' => 5, 'name' => ' Alagoinhas'],
                ['id_city' => 572, 'id_state' => 5, 'name' => ' Alcobaça'],
                ['id_city' => 573, 'id_state' => 5, 'name' => ' Alegre'],
                ['id_city' => 574, 'id_state' => 5, 'name' => ' Algodão'],
                ['id_city' => 575, 'id_state' => 5, 'name' => ' Algodões'],
                ['id_city' => 576, 'id_state' => 5, 'name' => ' Almadina'],
                ['id_city' => 577, 'id_state' => 5, 'name' => ' Alto Bonito'],
                ['id_city' => 578, 'id_state' => 5, 'name' => ' Amado Bahia'],
                ['id_city' => 579, 'id_state' => 5, 'name' => ' Amaniú'],
                ['id_city' => 580, 'id_state' => 5, 'name' => ' Amargosa'],
                ['id_city' => 581, 'id_state' => 5, 'name' => ' Amélia Rodrigues'],
                ['id_city' => 582, 'id_state' => 5, 'name' => ' América Dourada'],
                ['id_city' => 583, 'id_state' => 5, 'name' => ' Américo Alves'],
                ['id_city' => 584, 'id_state' => 5, 'name' => ' Anagé'],
                ['id_city' => 585, 'id_state' => 5, 'name' => ' Andaraí'],
                ['id_city' => 586, 'id_state' => 5, 'name' => ' Andorinha'],
                ['id_city' => 587, 'id_state' => 5, 'name' => ' Angical'],
                ['id_city' => 588, 'id_state' => 5, 'name' => ' Angico'],
                ['id_city' => 589, 'id_state' => 5, 'name' => ' Anguera'],
                ['id_city' => 590, 'id_state' => 5, 'name' => ' Antas'],
                ['id_city' => 591, 'id_state' => 5, 'name' => ' Antônio Cardoso'],
                ['id_city' => 592, 'id_state' => 5, 'name' => ' Antônio Gonçalves'],
                ['id_city' => 593, 'id_state' => 5, 'name' => ' Aporá'],
                ['id_city' => 594, 'id_state' => 5, 'name' => ' Apuarema'],
                ['id_city' => 595, 'id_state' => 5, 'name' => ' Araçás'],
                ['id_city' => 596, 'id_state' => 5, 'name' => ' Aracatu'],
                ['id_city' => 597, 'id_state' => 5, 'name' => ' Araci'],
                ['id_city' => 598, 'id_state' => 5, 'name' => ' Aramari'],
                ['id_city' => 599, 'id_state' => 5, 'name' => ' Arapiranga'],
                ['id_city' => 600, 'id_state' => 5, 'name' => ' Arataca'],
                ['id_city' => 601, 'id_state' => 5, 'name' => ' Aratuípe'],
                ['id_city' => 602, 'id_state' => 5, 'name' => ' Areias'],
                ['id_city' => 603, 'id_state' => 5, 'name' => ' Arembepe'],
                ['id_city' => 604, 'id_state' => 5, 'name' => ' Argoim'],
                ['id_city' => 605, 'id_state' => 5, 'name' => ' Argolo'],
                ['id_city' => 606, 'id_state' => 5, 'name' => ' Aribice'],
                ['id_city' => 607, 'id_state' => 5, 'name' => ' Aritaguá'],
                ['id_city' => 608, 'id_state' => 5, 'name' => ' Aurelino Leal'],
                ['id_city' => 609, 'id_state' => 5, 'name' => ' Baianópolis'],
                ['id_city' => 610, 'id_state' => 5, 'name' => ' Baixa do Palmeira'],
                ['id_city' => 611, 'id_state' => 5, 'name' => ' Baixa Grande'],
                ['id_city' => 612, 'id_state' => 5, 'name' => ' Baixão'],
                ['id_city' => 613, 'id_state' => 5, 'name' => ' Baixinha'],
                ['id_city' => 614, 'id_state' => 5, 'name' => ' Baluarte'],
                ['id_city' => 615, 'id_state' => 5, 'name' => ' Banco Central'],
                ['id_city' => 616, 'id_state' => 5, 'name' => ' Bandeira do Almada'],
                ['id_city' => 617, 'id_state' => 5, 'name' => ' Bandeira do Colônia'],
                ['id_city' => 618, 'id_state' => 5, 'name' => ' Bandiaçu'],
                ['id_city' => 619, 'id_state' => 5, 'name' => ' Banzaê'],
                ['id_city' => 620, 'id_state' => 5, 'name' => ' Baraúnas'],
                ['id_city' => 621, 'id_state' => 5, 'name' => ' Barcelos do Sul'],
                ['id_city' => 622, 'id_state' => 5, 'name' => ' Barra'],
                ['id_city' => 623, 'id_state' => 5, 'name' => ' Barra da Estiva'],
                ['id_city' => 624, 'id_state' => 5, 'name' => ' Barra do Choça'],
                ['id_city' => 625, 'id_state' => 5, 'name' => ' Barra do Jacuípe'],
                ['id_city' => 626, 'id_state' => 5, 'name' => ' Barra do Mendes'],
                ['id_city' => 627, 'id_state' => 5, 'name' => ' Barra do Pojuca'],
                ['id_city' => 628, 'id_state' => 5, 'name' => ' Barra do Rocha'],
                ['id_city' => 629, 'id_state' => 5, 'name' => ' Barra do Tarrachil'],
                ['id_city' => 630, 'id_state' => 5, 'name' => ' Barracas'],
                ['id_city' => 631, 'id_state' => 5, 'name' => ' Barreiras'],
                ['id_city' => 632, 'id_state' => 5, 'name' => ' Barro Alto'],
                ['id_city' => 633, 'id_state' => 5, 'name' => ' Barro Preto'],
                ['id_city' => 634, 'id_state' => 5, 'name' => ' Barro Vermelho'],
                ['id_city' => 635, 'id_state' => 5, 'name' => ' Barrocas'],
                ['id_city' => 636, 'id_state' => 5, 'name' => ' Bastião'],
                ['id_city' => 637, 'id_state' => 5, 'name' => ' Bate Pé'],
                ['id_city' => 638, 'id_state' => 5, 'name' => ' Batinga'],
                ['id_city' => 639, 'id_state' => 5, 'name' => ' Bela Flor'],
                ['id_city' => 640, 'id_state' => 5, 'name' => ' Belém da Cachoeira'],
                ['id_city' => 641, 'id_state' => 5, 'name' => ' Belmonte'],
                ['id_city' => 642, 'id_state' => 5, 'name' => ' Belo Campo'],
                ['id_city' => 643, 'id_state' => 5, 'name' => ' Bem-Bom'],
                ['id_city' => 644, 'id_state' => 5, 'name' => ' Bendegó'],
                ['id_city' => 645, 'id_state' => 5, 'name' => ' Bento Simões'],
                ['id_city' => 646, 'id_state' => 5, 'name' => ' Biritinga'],
                ['id_city' => 647, 'id_state' => 5, 'name' => ' Boa Espera'],
                ['id_city' => 648, 'id_state' => 5, 'name' => ' Boa Nova'],
                ['id_city' => 649, 'id_state' => 5, 'name' => ' Boa União'],
                ['id_city' => 650, 'id_state' => 5, 'name' => ' Boa Vista do Lagamar'],
                ['id_city' => 651, 'id_state' => 5, 'name' => ' Boa Vista do Tupim'],
                ['id_city' => 652, 'id_state' => 5, 'name' => ' Boaçu'],
                ['id_city' => 653, 'id_state' => 5, 'name' => ' Boca do Córrego'],
                ['id_city' => 654, 'id_state' => 5, 'name' => ' Bom Jesus da Lapa'],
                ['id_city' => 655, 'id_state' => 5, 'name' => ' Bom Jesus da Serra'],
                ['id_city' => 656, 'id_state' => 5, 'name' => ' Bom Sossego'],
                ['id_city' => 657, 'id_state' => 5, 'name' => ' Bonfim da Feira'],
                ['id_city' => 658, 'id_state' => 5, 'name' => ' Boninal'],
                ['id_city' => 659, 'id_state' => 5, 'name' => ' Bonito'],
                ['id_city' => 660, 'id_state' => 5, 'name' => ' Boquira'],
                ['id_city' => 661, 'id_state' => 5, 'name' => ' Botuporã'],
                ['id_city' => 662, 'id_state' => 5, 'name' => ' Botuquara'],
                ['id_city' => 663, 'id_state' => 5, 'name' => ' Brejinho das Ametistas'],
                ['id_city' => 664, 'id_state' => 5, 'name' => ' Brejo da Serra'],
                ['id_city' => 665, 'id_state' => 5, 'name' => ' Brejo Luíza de Brito'],
                ['id_city' => 666, 'id_state' => 5, 'name' => ' Brejo Novo'],
                ['id_city' => 667, 'id_state' => 5, 'name' => ' Brejões'],
                ['id_city' => 668, 'id_state' => 5, 'name' => ' Brejolândia'],
                ['id_city' => 669, 'id_state' => 5, 'name' => ' Brotas de Macaúbas'],
                ['id_city' => 670, 'id_state' => 5, 'name' => ' Brumado'],
                ['id_city' => 671, 'id_state' => 5, 'name' => ' Bucuituba'],
                ['id_city' => 672, 'id_state' => 5, 'name' => ' Buerarema'],
                ['id_city' => 673, 'id_state' => 5, 'name' => ' Buracica'],
                ['id_city' => 674, 'id_state' => 5, 'name' => ' Buranhém'],
                ['id_city' => 675, 'id_state' => 5, 'name' => ' Buril'],
                ['id_city' => 676, 'id_state' => 5, 'name' => ' Buris de Abrantes'],
                ['id_city' => 677, 'id_state' => 5, 'name' => ' Buritirama'],
                ['id_city' => 678, 'id_state' => 5, 'name' => ' Caatiba'],
                ['id_city' => 679, 'id_state' => 5, 'name' => ' Cabaceiras do Paraguaçu'],
                ['id_city' => 680, 'id_state' => 5, 'name' => ' Cabrália'],
                ['id_city' => 681, 'id_state' => 5, 'name' => ' Cacha Pregos'],
                ['id_city' => 682, 'id_state' => 5, 'name' => ' Cachoeira'],
                ['id_city' => 683, 'id_state' => 5, 'name' => ' Cachoeira do Mato'],
                ['id_city' => 684, 'id_state' => 5, 'name' => ' Caculé'],
                ['id_city' => 685, 'id_state' => 5, 'name' => ' Caém'],
                ['id_city' => 686, 'id_state' => 5, 'name' => ' Caetanos'],
                ['id_city' => 687, 'id_state' => 5, 'name' => ' Caeté-Açu'],
                ['id_city' => 688, 'id_state' => 5, 'name' => ' Caetité'],
                ['id_city' => 689, 'id_state' => 5, 'name' => ' Cafarnaum'],
                ['id_city' => 690, 'id_state' => 5, 'name' => ' Caiçara'],
                ['id_city' => 691, 'id_state' => 5, 'name' => ' Caimbé'],
                ['id_city' => 692, 'id_state' => 5, 'name' => ' Cairu'],
                ['id_city' => 693, 'id_state' => 5, 'name' => ' Caiubi'],
                ['id_city' => 694, 'id_state' => 5, 'name' => ' Cajuí'],
                ['id_city' => 695, 'id_state' => 5, 'name' => ' Caldas do Jorro'],
                ['id_city' => 696, 'id_state' => 5, 'name' => ' Caldeirão'],
                ['id_city' => 697, 'id_state' => 5, 'name' => ' Caldeirão Grande'],
                ['id_city' => 698, 'id_state' => 5, 'name' => ' Caldeiras'],
                ['id_city' => 699, 'id_state' => 5, 'name' => ' Camacan'],
                ['id_city' => 700, 'id_state' => 5, 'name' => ' Camaçari'],
                ['id_city' => 701, 'id_state' => 5, 'name' => ' Camamu'],
                ['id_city' => 702, 'id_state' => 5, 'name' => ' Camassandi'],
                ['id_city' => 703, 'id_state' => 5, 'name' => ' Camirim'],
                ['id_city' => 704, 'id_state' => 5, 'name' => ' Campinhos'],
                ['id_city' => 705, 'id_state' => 5, 'name' => ' Campo Alegre de Lourdes'],
                ['id_city' => 706, 'id_state' => 5, 'name' => ' Campo Formoso'],
                ['id_city' => 707, 'id_state' => 5, 'name' => ' Camurugi'],
                ['id_city' => 708, 'id_state' => 5, 'name' => ' Canabravinha'],
                ['id_city' => 709, 'id_state' => 5, 'name' => ' Canápolis'],
                ['id_city' => 710, 'id_state' => 5, 'name' => ' Canarana'],
                ['id_city' => 711, 'id_state' => 5, 'name' => ' Canatiba'],
                ['id_city' => 712, 'id_state' => 5, 'name' => ' Canavieiras'],
                ['id_city' => 713, 'id_state' => 5, 'name' => ' Canché'],
                ['id_city' => 714, 'id_state' => 5, 'name' => ' Candeal'],
                ['id_city' => 715, 'id_state' => 5, 'name' => ' Candeias'],
                ['id_city' => 716, 'id_state' => 5, 'name' => ' Candiba'],
                ['id_city' => 717, 'id_state' => 5, 'name' => ' Cândido Sales'],
                ['id_city' => 718, 'id_state' => 5, 'name' => ' Canoão'],
                ['id_city' => 719, 'id_state' => 5, 'name' => ' Cansanção'],
                ['id_city' => 720, 'id_state' => 5, 'name' => ' Canto do Sol'],
                ['id_city' => 721, 'id_state' => 5, 'name' => ' Canudos'],
                ['id_city' => 722, 'id_state' => 5, 'name' => ' Capão'],
                ['id_city' => 723, 'id_state' => 5, 'name' => ' Capela do Alto Alegre'],
                ['id_city' => 724, 'id_state' => 5, 'name' => ' Capim Grosso'],
                ['id_city' => 725, 'id_state' => 5, 'name' => ' Caraguataí'],
                ['id_city' => 726, 'id_state' => 5, 'name' => ' Caraíbas'],
                ['id_city' => 727, 'id_state' => 5, 'name' => ' Caraibuna'],
                ['id_city' => 728, 'id_state' => 5, 'name' => ' Caraípe'],
                ['id_city' => 729, 'id_state' => 5, 'name' => ' Caraiva'],
                ['id_city' => 730, 'id_state' => 5, 'name' => ' Caravelas'],
                ['id_city' => 731, 'id_state' => 5, 'name' => ' Cardeal da Silva'],
                ['id_city' => 732, 'id_state' => 5, 'name' => ' Carinhanha'],
                ['id_city' => 733, 'id_state' => 5, 'name' => ' Caripare'],
                ['id_city' => 734, 'id_state' => 5, 'name' => ' Carnaíba do Sertão'],
                ['id_city' => 735, 'id_state' => 5, 'name' => ' Carrapichel'],
                ['id_city' => 736, 'id_state' => 5, 'name' => ' Casa Nova'],
                ['id_city' => 737, 'id_state' => 5, 'name' => ' Castelo Novo'],
                ['id_city' => 738, 'id_state' => 5, 'name' => ' Castro Alves'],
                ['id_city' => 739, 'id_state' => 5, 'name' => ' Catinga do Moura'],
                ['id_city' => 740, 'id_state' => 5, 'name' => ' Catingal'],
                ['id_city' => 741, 'id_state' => 5, 'name' => ' Catolândia'],
                ['id_city' => 742, 'id_state' => 5, 'name' => ' Catolés'],
                ['id_city' => 743, 'id_state' => 5, 'name' => ' Catolezinho'],
                ['id_city' => 744, 'id_state' => 5, 'name' => ' Catu'],
                ['id_city' => 745, 'id_state' => 5, 'name' => ' Catu de Abrantes'],
                ['id_city' => 746, 'id_state' => 5, 'name' => ' Caturama'],
                ['id_city' => 747, 'id_state' => 5, 'name' => ' Cavunge'],
                ['id_city' => 748, 'id_state' => 5, 'name' => ' Central'],
                ['id_city' => 749, 'id_state' => 5, 'name' => ' Ceraima'],
                ['id_city' => 750, 'id_state' => 5, 'name' => ' Chorrochó'],
                ['id_city' => 751, 'id_state' => 5, 'name' => ' Cícero Dantas'],
                ['id_city' => 752, 'id_state' => 5, 'name' => ' Cinco Rios'],
                ['id_city' => 753, 'id_state' => 5, 'name' => ' Cipó'],
                ['id_city' => 754, 'id_state' => 5, 'name' => ' Coaraci'],
                ['id_city' => 755, 'id_state' => 5, 'name' => ' Cocos'],
                ['id_city' => 756, 'id_state' => 5, 'name' => ' Colônia'],
                ['id_city' => 757, 'id_state' => 5, 'name' => ' Comércio'],
                ['id_city' => 758, 'id_state' => 5, 'name' => ' Conceição da Feira'],
                ['id_city' => 759, 'id_state' => 5, 'name' => ' Conceição do Almeida'],
                ['id_city' => 760, 'id_state' => 5, 'name' => ' Conceição do Coité'],
                ['id_city' => 761, 'id_state' => 5, 'name' => ' Conceição do Jacuípe'],
                ['id_city' => 762, 'id_state' => 5, 'name' => ' Conde'],
                ['id_city' => 763, 'id_state' => 5, 'name' => ' Condeúba'],
                ['id_city' => 764, 'id_state' => 5, 'name' => ' Contendas do Sincorá'],
                ['id_city' => 765, 'id_state' => 5, 'name' => ' Copixaba'],
                ['id_city' => 766, 'id_state' => 5, 'name' => ' Coqueiros'],
                ['id_city' => 767, 'id_state' => 5, 'name' => ' Coquinhos'],
                ['id_city' => 768, 'id_state' => 5, 'name' => ' Coração de Maria'],
                ['id_city' => 769, 'id_state' => 5, 'name' => ' Cordeiros'],
                ['id_city' => 770, 'id_state' => 5, 'name' => ' Coribe'],
                ['id_city' => 771, 'id_state' => 5, 'name' => ' Coronel João Sá'],
                ['id_city' => 772, 'id_state' => 5, 'name' => ' Correntina'],
                ['id_city' => 773, 'id_state' => 5, 'name' => ' Corta Mão'],
                ['id_city' => 774, 'id_state' => 5, 'name' => ' Cotegipe'],
                ['id_city' => 775, 'id_state' => 5, 'name' => ' Coutos'],
                ['id_city' => 776, 'id_state' => 5, 'name' => ' Cravolândia'],
                ['id_city' => 777, 'id_state' => 5, 'name' => ' Crisópolis'],
                ['id_city' => 778, 'id_state' => 5, 'name' => ' Cristalândia'],
                ['id_city' => 779, 'id_state' => 5, 'name' => ' Cristópolis'],
                ['id_city' => 780, 'id_state' => 5, 'name' => ' Crussaí'],
                ['id_city' => 781, 'id_state' => 5, 'name' => ' Cruz das Almas'],
                ['id_city' => 782, 'id_state' => 5, 'name' => ' Cumuruxatiba'],
                ['id_city' => 783, 'id_state' => 5, 'name' => ' Cunhangi'],
                ['id_city' => 784, 'id_state' => 5, 'name' => ' Curaçá'],
                ['id_city' => 785, 'id_state' => 5, 'name' => ' Curral Falso'],
                ['id_city' => 786, 'id_state' => 5, 'name' => ' Dário Meira'],
                ['id_city' => 787, 'id_state' => 5, 'name' => ' Delfino'],
                ['id_city' => 788, 'id_state' => 5, 'name' => ' Descoberto'],
                ['id_city' => 789, 'id_state' => 5, 'name' => ' Dias Coelho'],
                ['id_city' => 790, 'id_state' => 5, 'name' => ' Dias D Ávila'],
                ['id_city' => 791, 'id_state' => 5, 'name' => ' Diógenes Sampaio'],
                ['id_city' => 792, 'id_state' => 5, 'name' => ' Dom Basílio'],
                ['id_city' => 793, 'id_state' => 5, 'name' => ' Dom Macedo Costa'],
                ['id_city' => 794, 'id_state' => 5, 'name' => ' Dona Maria'],
                ['id_city' => 795, 'id_state' => 5, 'name' => ' Duas Barras do Morro'],
                ['id_city' => 796, 'id_state' => 5, 'name' => ' Elísio Medrado'],
                ['id_city' => 797, 'id_state' => 5, 'name' => ' Encruzilhada'],
                ['id_city' => 798, 'id_state' => 5, 'name' => ' Engenheiro França'],
                ['id_city' => 799, 'id_state' => 5, 'name' => ' Engenheiro Pontes'],
                ['id_city' => 800, 'id_state' => 5, 'name' => ' Entre Rios'],
                ['id_city' => 801, 'id_state' => 5, 'name' => ' Érico Cardoso'],
                ['id_city' => 802, 'id_state' => 5, 'name' => ' Esplanada'],
                ['id_city' => 803, 'id_state' => 5, 'name' => ' Euclides da Cunha'],
                ['id_city' => 804, 'id_state' => 5, 'name' => ' Eunápolis'],
                ['id_city' => 805, 'id_state' => 5, 'name' => ' Fátima'],
                ['id_city' => 806, 'id_state' => 5, 'name' => ' Feira da Mata'],
                ['id_city' => 807, 'id_state' => 5, 'name' => ' Feira de Santana'],
                ['id_city' => 808, 'id_state' => 5, 'name' => ' Ferradas'],
                ['id_city' => 809, 'id_state' => 5, 'name' => ' Filadélfia'],
                ['id_city' => 810, 'id_state' => 5, 'name' => ' Filanésia'],
                ['id_city' => 811, 'id_state' => 5, 'name' => ' Firmino Alves'],
                ['id_city' => 812, 'id_state' => 5, 'name' => ' Floresta Azul'],
                ['id_city' => 813, 'id_state' => 5, 'name' => ' Formosa do Rio Preto'],
                ['id_city' => 814, 'id_state' => 5, 'name' => ' França'],
                ['id_city' => 815, 'id_state' => 5, 'name' => ' Gabiarra'],
                ['id_city' => 816, 'id_state' => 5, 'name' => ' Galeão'],
                ['id_city' => 817, 'id_state' => 5, 'name' => ' Gamboa'],
                ['id_city' => 818, 'id_state' => 5, 'name' => ' Gameleira da Lapa'],
                ['id_city' => 819, 'id_state' => 5, 'name' => ' Gameleira do Assuruá'],
                ['id_city' => 820, 'id_state' => 5, 'name' => ' Gandu'],
                ['id_city' => 821, 'id_state' => 5, 'name' => ' Gavião'],
                ['id_city' => 822, 'id_state' => 5, 'name' => ' Gentio do Ouro'],
                ['id_city' => 823, 'id_state' => 5, 'name' => ' Geolândia'],
                ['id_city' => 824, 'id_state' => 5, 'name' => ' Glória'],
                ['id_city' => 825, 'id_state' => 5, 'name' => ' Gongogi'],
                ['id_city' => 826, 'id_state' => 5, 'name' => ' Governador João Durval Carneiro'],
                ['id_city' => 827, 'id_state' => 5, 'name' => ' Governador Mangabeira'],
                ['id_city' => 828, 'id_state' => 5, 'name' => ' Guagirus'],
                ['id_city' => 829, 'id_state' => 5, 'name' => ' Guaí'],
                ['id_city' => 830, 'id_state' => 5, 'name' => ' Guajeru'],
                ['id_city' => 831, 'id_state' => 5, 'name' => ' Guanambi'],
                ['id_city' => 832, 'id_state' => 5, 'name' => ' Guapira'],
                ['id_city' => 833, 'id_state' => 5, 'name' => ' Guarajuba'],
                ['id_city' => 834, 'id_state' => 5, 'name' => ' Guaratinga'],
                ['id_city' => 835, 'id_state' => 5, 'name' => ' Guerém'],
                ['id_city' => 836, 'id_state' => 5, 'name' => ' Guiné'],
                ['id_city' => 837, 'id_state' => 5, 'name' => ' Guirapa'],
                ['id_city' => 838, 'id_state' => 5, 'name' => ' Gurupá Mirim'],
                ['id_city' => 839, 'id_state' => 5, 'name' => ' Heliópolis'],
                ['id_city' => 840, 'id_state' => 5, 'name' => ' Helvecia'],
                ['id_city' => 841, 'id_state' => 5, 'name' => ' Hidrolândia'],
                ['id_city' => 842, 'id_state' => 5, 'name' => ' Humildes'],
                ['id_city' => 843, 'id_state' => 5, 'name' => ' Iaçu'],
                ['id_city' => 844, 'id_state' => 5, 'name' => ' Ibatui'],
                ['id_city' => 845, 'id_state' => 5, 'name' => ' Ibiaçu'],
                ['id_city' => 846, 'id_state' => 5, 'name' => ' Ibiajara'],
                ['id_city' => 847, 'id_state' => 5, 'name' => ' Ibiapora'],
                ['id_city' => 848, 'id_state' => 5, 'name' => ' Ibiassucê'],
                ['id_city' => 849, 'id_state' => 5, 'name' => ' Ibicaraí'],
                ['id_city' => 850, 'id_state' => 5, 'name' => ' Ibicoara'],
                ['id_city' => 851, 'id_state' => 5, 'name' => ' Ibicuí'],
                ['id_city' => 852, 'id_state' => 5, 'name' => ' Ibipeba'],
                ['id_city' => 853, 'id_state' => 5, 'name' => ' Ibipetum'],
                ['id_city' => 854, 'id_state' => 5, 'name' => ' Ibipitanga'],
                ['id_city' => 855, 'id_state' => 5, 'name' => ' Ibiquera'],
                ['id_city' => 856, 'id_state' => 5, 'name' => ' Ibiraba'],
                ['id_city' => 857, 'id_state' => 5, 'name' => ' Ibirajá'],
                ['id_city' => 858, 'id_state' => 5, 'name' => ' Ibiranhém'],
                ['id_city' => 859, 'id_state' => 5, 'name' => ' Ibirapitanga'],
                ['id_city' => 860, 'id_state' => 5, 'name' => ' Ibirapuã'],
                ['id_city' => 861, 'id_state' => 5, 'name' => ' Ibirataia'],
                ['id_city' => 862, 'id_state' => 5, 'name' => ' Ibitiara'],
                ['id_city' => 863, 'id_state' => 5, 'name' => ' Ibitiguira'],
                ['id_city' => 864, 'id_state' => 5, 'name' => ' Ibitira'],
                ['id_city' => 865, 'id_state' => 5, 'name' => ' Ibititá'],
                ['id_city' => 866, 'id_state' => 5, 'name' => ' Ibitunane'],
                ['id_city' => 867, 'id_state' => 5, 'name' => ' Ibitupa'],
                ['id_city' => 868, 'id_state' => 5, 'name' => ' Ibó'],
                ['id_city' => 869, 'id_state' => 5, 'name' => ' Ibotirama'],
                ['id_city' => 870, 'id_state' => 5, 'name' => ' Ichu'],
                ['id_city' => 871, 'id_state' => 5, 'name' => ' Icó'],
                ['id_city' => 872, 'id_state' => 5, 'name' => ' Igaporã'],
                ['id_city' => 873, 'id_state' => 5, 'name' => ' Igará'],
                ['id_city' => 874, 'id_state' => 5, 'name' => ' Igarité'],
                ['id_city' => 875, 'id_state' => 5, 'name' => ' Igatu'],
                ['id_city' => 876, 'id_state' => 5, 'name' => ' Igrapiúna'],
                ['id_city' => 877, 'id_state' => 5, 'name' => ' Iguá'],
                ['id_city' => 878, 'id_state' => 5, 'name' => ' Iguaí'],
                ['id_city' => 879, 'id_state' => 5, 'name' => ' Iguaibi'],
                ['id_city' => 880, 'id_state' => 5, 'name' => ' Iguatemi'],
                ['id_city' => 881, 'id_state' => 5, 'name' => ' Iguira'],
                ['id_city' => 882, 'id_state' => 5, 'name' => ' Iguitu'],
                ['id_city' => 883, 'id_state' => 5, 'name' => ' Ilha de Maré'],
                ['id_city' => 884, 'id_state' => 5, 'name' => ' Ilhéus'],
                ['id_city' => 885, 'id_state' => 5, 'name' => ' Indaí'],
                ['id_city' => 886, 'id_state' => 5, 'name' => ' Inema'],
                ['id_city' => 887, 'id_state' => 5, 'name' => ' Inhambupe'],
                ['id_city' => 888, 'id_state' => 5, 'name' => ' Inhata'],
                ['id_city' => 889, 'id_state' => 5, 'name' => ' Inhaúmas'],
                ['id_city' => 890, 'id_state' => 5, 'name' => ' Inhobim'],
                ['id_city' => 891, 'id_state' => 5, 'name' => ' Inúbia'],
                ['id_city' => 892, 'id_state' => 5, 'name' => ' Ipecaetá'],
                ['id_city' => 893, 'id_state' => 5, 'name' => ' Ipiaú'],
                ['id_city' => 894, 'id_state' => 5, 'name' => ' Ipirá'],
                ['id_city' => 895, 'id_state' => 5, 'name' => ' Ipiúna'],
                ['id_city' => 896, 'id_state' => 5, 'name' => ' Ipucaba'],
                ['id_city' => 897, 'id_state' => 5, 'name' => ' Ipupiara'],
                ['id_city' => 898, 'id_state' => 5, 'name' => ' Irajuba'],
                ['id_city' => 899, 'id_state' => 5, 'name' => ' Iramaia'],
                ['id_city' => 900, 'id_state' => 5, 'name' => ' Iraporanga'],
                ['id_city' => 901, 'id_state' => 5, 'name' => ' Iraquara'],
                ['id_city' => 902, 'id_state' => 5, 'name' => ' Irará'],
                ['id_city' => 903, 'id_state' => 5, 'name' => ' Irecê'],
                ['id_city' => 904, 'id_state' => 5, 'name' => ' Irundiara'],
                ['id_city' => 905, 'id_state' => 5, 'name' => ' Ita-Azul'],
                ['id_city' => 906, 'id_state' => 5, 'name' => ' Itabela'],
                ['id_city' => 907, 'id_state' => 5, 'name' => ' Itaberaba'],
                ['id_city' => 908, 'id_state' => 5, 'name' => ' Itabuna']
            ]);
        }
    }
}