<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities10 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 6072, 'id_state' => 16, 'name' => ' Colônia Esperança'],
                ['id_city' => 6073, 'id_state' => 16, 'name' => ' Colônia General Carneiro'],
                ['id_city' => 6074, 'id_state' => 16, 'name' => ' Colônia Iapó'],
                ['id_city' => 6075, 'id_state' => 16, 'name' => ' Colônia Melissa'],
                ['id_city' => 6076, 'id_state' => 16, 'name' => ' Colônia Murici'],
                ['id_city' => 6077, 'id_state' => 16, 'name' => ' Colônia Padre Paulo'],
                ['id_city' => 6078, 'id_state' => 16, 'name' => ' Colônia Pereira'],
                ['id_city' => 6079, 'id_state' => 16, 'name' => ' Colônia Santos Andrade'],
                ['id_city' => 6080, 'id_state' => 16, 'name' => ' Colônia São José'],
                ['id_city' => 6081, 'id_state' => 16, 'name' => ' Colônia Sapucaí'],
                ['id_city' => 6082, 'id_state' => 16, 'name' => ' Colônia Saúde'],
                ['id_city' => 6083, 'id_state' => 16, 'name' => ' Colônia Tapera'],
                ['id_city' => 6084, 'id_state' => 16, 'name' => ' Colorado'],
                ['id_city' => 6085, 'id_state' => 16, 'name' => ' Comur'],
                ['id_city' => 6086, 'id_state' => 16, 'name' => ' Conceição'],
                ['id_city' => 6087, 'id_state' => 16, 'name' => ' Conchas Velhas'],
                ['id_city' => 6088, 'id_state' => 16, 'name' => ' Conciolândia'],
                ['id_city' => 6089, 'id_state' => 16, 'name' => ' Congonhas'],
                ['id_city' => 6090, 'id_state' => 16, 'name' => ' Congonhinhas'],
                ['id_city' => 6091, 'id_state' => 16, 'name' => ' Conselheiro Mairinck'],
                ['id_city' => 6092, 'id_state' => 16, 'name' => ' Conselheiro Zacarias'],
                ['id_city' => 6093, 'id_state' => 16, 'name' => ' Contenda'],
                ['id_city' => 6094, 'id_state' => 16, 'name' => ' Copacabana do Norte'],
                ['id_city' => 6095, 'id_state' => 16, 'name' => ' Corbélia'],
                ['id_city' => 6096, 'id_state' => 16, 'name' => ' Cornélio Procópio'],
                ['id_city' => 6097, 'id_state' => 16, 'name' => ' Coronel Domingos Soares'],
                ['id_city' => 6098, 'id_state' => 16, 'name' => ' Coronel Firmino Martins'],
                ['id_city' => 6099, 'id_state' => 16, 'name' => ' Coronel Vivida'],
                ['id_city' => 6100, 'id_state' => 16, 'name' => ' Correia de Freitas'],
                ['id_city' => 6101, 'id_state' => 16, 'name' => ' Corumbataí do Sul'],
                ['id_city' => 6102, 'id_state' => 16, 'name' => ' Corvo'],
                ['id_city' => 6103, 'id_state' => 16, 'name' => ' Costeira'],
                ['id_city' => 6104, 'id_state' => 16, 'name' => ' Covó'],
                ['id_city' => 6105, 'id_state' => 16, 'name' => ' Coxilha Rica'],
                ['id_city' => 6106, 'id_state' => 16, 'name' => ' Cristo Rei'],
                ['id_city' => 6107, 'id_state' => 16, 'name' => ' Cruz Machado'],
                ['id_city' => 6108, 'id_state' => 16, 'name' => ' Cruzeiro do Iguaçu'],
                ['id_city' => 6109, 'id_state' => 16, 'name' => ' Cruzeiro do Norte'],
                ['id_city' => 6110, 'id_state' => 16, 'name' => ' Cruzeiro do Oeste'],
                ['id_city' => 6111, 'id_state' => 16, 'name' => ' Cruzeiro do Sul'],
                ['id_city' => 6112, 'id_state' => 16, 'name' => ' Cruzmaltina'],
                ['id_city' => 6113, 'id_state' => 16, 'name' => ' Cunhaporanga'],
                ['id_city' => 6114, 'id_state' => 16, 'name' => ' Curitiba'],
                ['id_city' => 6115, 'id_state' => 16, 'name' => ' Curiúva'],
                ['id_city' => 6116, 'id_state' => 16, 'name' => ' Curucaca'],
                ['id_city' => 6117, 'id_state' => 16, 'name' => ' Deputado José Afonso'],
                ['id_city' => 6118, 'id_state' => 16, 'name' => ' Despique'],
                ['id_city' => 6119, 'id_state' => 16, 'name' => ' Dez de Maio'],
                ['id_city' => 6120, 'id_state' => 16, 'name' => ' Diamante d Oeste'],
                ['id_city' => 6121, 'id_state' => 16, 'name' => ' Diamante do Norte'],
                ['id_city' => 6122, 'id_state' => 16, 'name' => ' Diamante do Sul'],
                ['id_city' => 6123, 'id_state' => 16, 'name' => ' Doce Grande'],
                ['id_city' => 6124, 'id_state' => 16, 'name' => ' Dois Irmãos'],
                ['id_city' => 6125, 'id_state' => 16, 'name' => ' Dois Irmãos'],
                ['id_city' => 6126, 'id_state' => 16, 'name' => ' Dois Marcos'],
                ['id_city' => 6127, 'id_state' => 16, 'name' => ' Dois Vizinhos'],
                ['id_city' => 6128, 'id_state' => 16, 'name' => ' Dom Rodrigo'],
                ['id_city' => 6129, 'id_state' => 16, 'name' => ' Dorizon'],
                ['id_city' => 6130, 'id_state' => 16, 'name' => ' Douradina'],
                ['id_city' => 6131, 'id_state' => 16, 'name' => ' Doutor Antônio Paranhos'],
                ['id_city' => 6132, 'id_state' => 16, 'name' => ' Doutor Camargo'],
                ['id_city' => 6133, 'id_state' => 16, 'name' => ' Doutor Ernesto'],
                ['id_city' => 6134, 'id_state' => 16, 'name' => ' Doutor Oliveira Castro'],
                ['id_city' => 6135, 'id_state' => 16, 'name' => ' Doutor Ulysses'],
                ['id_city' => 6136, 'id_state' => 16, 'name' => ' Eduardo Xavier da Silva'],
                ['id_city' => 6137, 'id_state' => 16, 'name' => ' Emboguaçu'],
                ['id_city' => 6138, 'id_state' => 16, 'name' => ' Emboque'],
                ['id_city' => 6139, 'id_state' => 16, 'name' => ' Encantado d Oeste'],
                ['id_city' => 6140, 'id_state' => 16, 'name' => ' Encruzilhada'],
                ['id_city' => 6141, 'id_state' => 16, 'name' => ' Enéas Marques'],
                ['id_city' => 6142, 'id_state' => 16, 'name' => ' Engenheiro Beltrão'],
                ['id_city' => 6143, 'id_state' => 16, 'name' => ' Entre Rios'],
                ['id_city' => 6144, 'id_state' => 16, 'name' => ' Entre Rios do Oeste'],
                ['id_city' => 6145, 'id_state' => 16, 'name' => ' Esperança do Norte'],
                ['id_city' => 6146, 'id_state' => 16, 'name' => ' Esperança Nova'],
                ['id_city' => 6147, 'id_state' => 16, 'name' => ' Espigão Alto do Iguaçu'],
                ['id_city' => 6148, 'id_state' => 16, 'name' => ' Espírito Santo'],
                ['id_city' => 6149, 'id_state' => 16, 'name' => ' Estação General Lúcio'],
                ['id_city' => 6150, 'id_state' => 16, 'name' => ' Estação Roça Nova'],
                ['id_city' => 6151, 'id_state' => 16, 'name' => ' Europa'],
                ['id_city' => 6152, 'id_state' => 16, 'name' => ' Euzébio de Oliveira'],
                ['id_city' => 6153, 'id_state' => 16, 'name' => ' Faisqueira'],
                ['id_city' => 6154, 'id_state' => 16, 'name' => ' Farol'],
                ['id_city' => 6155, 'id_state' => 16, 'name' => ' Faxina'],
                ['id_city' => 6156, 'id_state' => 16, 'name' => ' Faxinal'],
                ['id_city' => 6157, 'id_state' => 16, 'name' => ' Faxinal do Céu'],
                ['id_city' => 6158, 'id_state' => 16, 'name' => ' Faxinal dos Elias'],
                ['id_city' => 6159, 'id_state' => 16, 'name' => ' Faxinal Santa Cruz'],
                ['id_city' => 6160, 'id_state' => 16, 'name' => ' Fazenda do Brigadeiro'],
                ['id_city' => 6161, 'id_state' => 16, 'name' => ' Fazenda dos Barbosas'],
                ['id_city' => 6162, 'id_state' => 16, 'name' => ' Fazenda Jangada'],
                ['id_city' => 6163, 'id_state' => 16, 'name' => ' Fazenda Rio Grande'],
                ['id_city' => 6164, 'id_state' => 16, 'name' => ' Fazenda Salmo 23'],
                ['id_city' => 6165, 'id_state' => 16, 'name' => ' Fazendinha'],
                ['id_city' => 6166, 'id_state' => 16, 'name' => ' Felpudo'],
                ['id_city' => 6167, 'id_state' => 16, 'name' => ' Fênix'],
                ['id_city' => 6168, 'id_state' => 16, 'name' => ' Fernandes Pinheiro'],
                ['id_city' => 6169, 'id_state' => 16, 'name' => ' Fernão Dias'],
                ['id_city' => 6170, 'id_state' => 16, 'name' => ' Ferraria'],
                ['id_city' => 6171, 'id_state' => 16, 'name' => ' Ferreiras'],
                ['id_city' => 6172, 'id_state' => 16, 'name' => ' Figueira'],
                ['id_city' => 6173, 'id_state' => 16, 'name' => ' Figueira do Oeste'],
                ['id_city' => 6174, 'id_state' => 16, 'name' => ' Fiusas'],
                ['id_city' => 6175, 'id_state' => 16, 'name' => ' Flor da Serra'],
                ['id_city' => 6176, 'id_state' => 16, 'name' => ' Flor da Serra do Sul'],
                ['id_city' => 6177, 'id_state' => 16, 'name' => ' Floraí'],
                ['id_city' => 6178, 'id_state' => 16, 'name' => ' Floresta'],
                ['id_city' => 6179, 'id_state' => 16, 'name' => ' Florestópolis'],
                ['id_city' => 6180, 'id_state' => 16, 'name' => ' Floriano'],
                ['id_city' => 6181, 'id_state' => 16, 'name' => ' Flórida'],
                ['id_city' => 6182, 'id_state' => 16, 'name' => ' Florópolis'],
                ['id_city' => 6183, 'id_state' => 16, 'name' => ' Fluviópolis'],
                ['id_city' => 6184, 'id_state' => 16, 'name' => ' Formigone'],
                ['id_city' => 6185, 'id_state' => 16, 'name' => ' Formosa do Oeste'],
                ['id_city' => 6186, 'id_state' => 16, 'name' => ' Foz do Iguaçu'],
                ['id_city' => 6187, 'id_state' => 16, 'name' => ' Foz do Jordão'],
                ['id_city' => 6188, 'id_state' => 16, 'name' => ' Francisco Alves'],
                ['id_city' => 6189, 'id_state' => 16, 'name' => ' Francisco Beltrão'],
                ['id_city' => 6190, 'id_state' => 16, 'name' => ' Francisco Frederico Teixeira Guimarães'],
                ['id_city' => 6191, 'id_state' => 16, 'name' => ' Frei Timóteo'],
                ['id_city' => 6192, 'id_state' => 16, 'name' => ' Fueros'],
                ['id_city' => 6193, 'id_state' => 16, 'name' => ' Fundão'],
                ['id_city' => 6194, 'id_state' => 16, 'name' => ' Gamadinho'],
                ['id_city' => 6195, 'id_state' => 16, 'name' => ' Gamela'],
                ['id_city' => 6196, 'id_state' => 16, 'name' => ' Gaúcha'],
                ['id_city' => 6197, 'id_state' => 16, 'name' => ' Gavião'],
                ['id_city' => 6198, 'id_state' => 16, 'name' => ' General Carneiro'],
                ['id_city' => 6199, 'id_state' => 16, 'name' => ' General Osório'],
                ['id_city' => 6200, 'id_state' => 16, 'name' => ' Geremia Lunardelli'],
                ['id_city' => 6201, 'id_state' => 16, 'name' => ' Godoy Moreira'],
                ['id_city' => 6202, 'id_state' => 16, 'name' => ' Goioerê'],
                ['id_city' => 6203, 'id_state' => 16, 'name' => ' Goioxim'],
                ['id_city' => 6204, 'id_state' => 16, 'name' => ' Góis'],
                ['id_city' => 6205, 'id_state' => 16, 'name' => ' Gonçalves Júnior'],
                ['id_city' => 6206, 'id_state' => 16, 'name' => ' Graciosa'],
                ['id_city' => 6207, 'id_state' => 16, 'name' => ' Grandes Rios'],
                ['id_city' => 6208, 'id_state' => 16, 'name' => ' Guaiporã'],
                ['id_city' => 6209, 'id_state' => 16, 'name' => ' Guaíra'],
                ['id_city' => 6210, 'id_state' => 16, 'name' => ' Guairaçá'],
                ['id_city' => 6211, 'id_state' => 16, 'name' => ' Guajuvira'],
                ['id_city' => 6212, 'id_state' => 16, 'name' => ' Guamiranga'],
                ['id_city' => 6213, 'id_state' => 16, 'name' => ' Guamirim'],
                ['id_city' => 6214, 'id_state' => 16, 'name' => ' Guapirama'],
                ['id_city' => 6215, 'id_state' => 16, 'name' => ' Guaporé'],
                ['id_city' => 6216, 'id_state' => 16, 'name' => ' Guaporema'],
                ['id_city' => 6217, 'id_state' => 16, 'name' => ' Guará'],
                ['id_city' => 6218, 'id_state' => 16, 'name' => ' Guaraci'],
                ['id_city' => 6219, 'id_state' => 16, 'name' => ' Guaragi'],
                ['id_city' => 6220, 'id_state' => 16, 'name' => ' Guaraituba'],
                ['id_city' => 6221, 'id_state' => 16, 'name' => ' Guarani'],
                ['id_city' => 6222, 'id_state' => 16, 'name' => ' Guaraniaçu'],
                ['id_city' => 6223, 'id_state' => 16, 'name' => ' Guarapuava'],
                ['id_city' => 6224, 'id_state' => 16, 'name' => ' Guarapuavinha'],
                ['id_city' => 6225, 'id_state' => 16, 'name' => ' Guaraqueçaba'],
                ['id_city' => 6226, 'id_state' => 16, 'name' => ' Guararema'],
                ['id_city' => 6227, 'id_state' => 16, 'name' => ' Guaratuba'],
                ['id_city' => 6228, 'id_state' => 16, 'name' => ' Guaraúna'],
                ['id_city' => 6229, 'id_state' => 16, 'name' => ' Guaravera'],
                ['id_city' => 6230, 'id_state' => 16, 'name' => ' Guardamoria'],
                ['id_city' => 6231, 'id_state' => 16, 'name' => ' Harmonia'],
                ['id_city' => 6232, 'id_state' => 16, 'name' => ' Herculândia'],
                ['id_city' => 6233, 'id_state' => 16, 'name' => ' Herval Grande'],
                ['id_city' => 6234, 'id_state' => 16, 'name' => ' Herveira'],
                ['id_city' => 6235, 'id_state' => 16, 'name' => ' Hidrelétrica Itaipu'],
                ['id_city' => 6236, 'id_state' => 16, 'name' => ' Honório Serpa'],
                ['id_city' => 6237, 'id_state' => 16, 'name' => ' Iarama'],
                ['id_city' => 6238, 'id_state' => 16, 'name' => ' Ibaiti'],
                ['id_city' => 6239, 'id_state' => 16, 'name' => ' Ibema'],
                ['id_city' => 6240, 'id_state' => 16, 'name' => ' Ibiaci'],
                ['id_city' => 6241, 'id_state' => 16, 'name' => ' Ibiporã'],
                ['id_city' => 6242, 'id_state' => 16, 'name' => ' Içara'],
                ['id_city' => 6243, 'id_state' => 16, 'name' => ' Icaraíma'],
                ['id_city' => 6244, 'id_state' => 16, 'name' => ' Icatu'],
                ['id_city' => 6245, 'id_state' => 16, 'name' => ' Igrejinha'],
                ['id_city' => 6246, 'id_state' => 16, 'name' => ' Iguaraçu'],
                ['id_city' => 6247, 'id_state' => 16, 'name' => ' Iguatemi'],
                ['id_city' => 6248, 'id_state' => 16, 'name' => ' Iguatu'],
                ['id_city' => 6249, 'id_state' => 16, 'name' => ' Iguiporã'],
                ['id_city' => 6250, 'id_state' => 16, 'name' => ' Ilha do Mel'],
                ['id_city' => 6251, 'id_state' => 16, 'name' => ' Ilha dos Valadares'],
                ['id_city' => 6252, 'id_state' => 16, 'name' => ' Imbaú'],
                ['id_city' => 6253, 'id_state' => 16, 'name' => ' Imbauzinho'],
                ['id_city' => 6254, 'id_state' => 16, 'name' => ' Imbituva'],
                ['id_city' => 6255, 'id_state' => 16, 'name' => ' Inácio Martins'],
                ['id_city' => 6256, 'id_state' => 16, 'name' => ' Inajá'],
                ['id_city' => 6257, 'id_state' => 16, 'name' => ' Independência'],
                ['id_city' => 6258, 'id_state' => 16, 'name' => ' Indianópolis'],
                ['id_city' => 6259, 'id_state' => 16, 'name' => ' Inspetor Carvalho'],
                ['id_city' => 6260, 'id_state' => 16, 'name' => ' Invernada'],
                ['id_city' => 6261, 'id_state' => 16, 'name' => ' Invernadinha'],
                ['id_city' => 6262, 'id_state' => 16, 'name' => ' Iolópolis'],
                ['id_city' => 6263, 'id_state' => 16, 'name' => ' Ipiranga'],
                ['id_city' => 6264, 'id_state' => 16, 'name' => ' Vila Ipiranga'],
                ['id_city' => 6265, 'id_state' => 16, 'name' => ' Iporã'],
                ['id_city' => 6266, 'id_state' => 16, 'name' => ' Iracema do Oeste'],
                ['id_city' => 6267, 'id_state' => 16, 'name' => ' Irapuan'],
                ['id_city' => 6268, 'id_state' => 16, 'name' => ' Irati'],
                ['id_city' => 6269, 'id_state' => 16, 'name' => ' Irerê'],
                ['id_city' => 6270, 'id_state' => 16, 'name' => ' Iretama'],
                ['id_city' => 6271, 'id_state' => 16, 'name' => ' Itaguajé'],
                ['id_city' => 6272, 'id_state' => 16, 'name' => ' Itaiacoca'],
                ['id_city' => 6273, 'id_state' => 16, 'name' => ' Itaipulândia'],
                ['id_city' => 6274, 'id_state' => 16, 'name' => ' Itambaracá'],
                ['id_city' => 6275, 'id_state' => 16, 'name' => ' Itambé'],
                ['id_city' => 6276, 'id_state' => 16, 'name' => ' Itapanhacanga'],
                ['id_city' => 6277, 'id_state' => 16, 'name' => ' Itapara'],
                ['id_city' => 6278, 'id_state' => 16, 'name' => ' Itapejara d Oeste'],
                ['id_city' => 6279, 'id_state' => 16, 'name' => ' Itaperuçu'],
                ['id_city' => 6280, 'id_state' => 16, 'name' => ' Itaqui'],
                ['id_city' => 6281, 'id_state' => 16, 'name' => ' Itaúna do Sul'],
                ['id_city' => 6282, 'id_state' => 16, 'name' => ' Itinga'],
                ['id_city' => 6283, 'id_state' => 16, 'name' => ' Ivaí'],
                ['id_city' => 6284, 'id_state' => 16, 'name' => ' Ivailândia'],
                ['id_city' => 6285, 'id_state' => 16, 'name' => ' Ivaiporã'],
                ['id_city' => 6286, 'id_state' => 16, 'name' => ' Ivaitinga'],
                ['id_city' => 6287, 'id_state' => 16, 'name' => ' Ivaté'],
                ['id_city' => 6288, 'id_state' => 16, 'name' => ' Ivatuba'],
                ['id_city' => 6289, 'id_state' => 16, 'name' => ' Jaborandi'],
                ['id_city' => 6290, 'id_state' => 16, 'name' => ' Jaboti'],
                ['id_city' => 6291, 'id_state' => 16, 'name' => ' Jaboticabal'],
                ['id_city' => 6292, 'id_state' => 16, 'name' => ' Jaburu'],
                ['id_city' => 6293, 'id_state' => 16, 'name' => ' Jacaré'],
                ['id_city' => 6294, 'id_state' => 16, 'name' => ' Jacarezinho'],
                ['id_city' => 6295, 'id_state' => 16, 'name' => ' Jaciaba'],
                ['id_city' => 6296, 'id_state' => 16, 'name' => ' Jacutinga'],
                ['id_city' => 6297, 'id_state' => 16, 'name' => ' Jaguapitã'],
                ['id_city' => 6298, 'id_state' => 16, 'name' => ' Jaguariaíva'],
                ['id_city' => 6299, 'id_state' => 16, 'name' => ' Jandaia do Sul'],
                ['id_city' => 6300, 'id_state' => 16, 'name' => ' Jangada'],
                ['id_city' => 6301, 'id_state' => 16, 'name' => ' Jangada do Sul'],
                ['id_city' => 6302, 'id_state' => 16, 'name' => ' Janiópolis'],
                ['id_city' => 6303, 'id_state' => 16, 'name' => ' Japira'],
                ['id_city' => 6304, 'id_state' => 16, 'name' => ' Japurá'],
                ['id_city' => 6305, 'id_state' => 16, 'name' => ' Jaracatiá'],
                ['id_city' => 6306, 'id_state' => 16, 'name' => ' Jardim'],
                ['id_city' => 6307, 'id_state' => 16, 'name' => ' Jardim Alegre'],
                ['id_city' => 6308, 'id_state' => 16, 'name' => ' Jardim Olinda'],
                ['id_city' => 6309, 'id_state' => 16, 'name' => ' Jardim Paredão'],
                ['id_city' => 6310, 'id_state' => 16, 'name' => ' Jandinópolis'],
                ['id_city' => 6311, 'id_state' => 16, 'name' => ' Jataizinho'],
                ['id_city' => 6312, 'id_state' => 16, 'name' => ' Javacaé'],
                ['id_city' => 6313, 'id_state' => 16, 'name' => ' Jesuítas'],
                ['id_city' => 6314, 'id_state' => 16, 'name' => ' Joá'],
                ['id_city' => 6315, 'id_state' => 16, 'name' => ' Joaquim Távora'],
                ['id_city' => 6316, 'id_state' => 16, 'name' => ' Colônia Jordãozinho'],
                ['id_city' => 6317, 'id_state' => 16, 'name' => ' José Lacerda'],
                ['id_city' => 6318, 'id_state' => 16, 'name' => ' Juciara'],
                ['id_city' => 6319, 'id_state' => 16, 'name' => ' Jundiaí do Sul'],
                ['id_city' => 6320, 'id_state' => 16, 'name' => ' Juranda'],
                ['id_city' => 6321, 'id_state' => 16, 'name' => ' Jussara'],
                ['id_city' => 6322, 'id_state' => 16, 'name' => ' Juvinópolis'],
                ['id_city' => 6323, 'id_state' => 16, 'name' => ' Kaloré'],
                ['id_city' => 6324, 'id_state' => 16, 'name' => ' km 30'],
                ['id_city' => 6325, 'id_state' => 16, 'name' => ' Lagoa'],
                ['id_city' => 6326, 'id_state' => 16, 'name' => ' Lagoa Bonita'],
                ['id_city' => 6327, 'id_state' => 16, 'name' => ' Lagoa dos Ribas'],
                ['id_city' => 6328, 'id_state' => 16, 'name' => ' Lagoa Dourada'],
                ['id_city' => 6329, 'id_state' => 16, 'name' => ' Lagoa Seca'],
                ['id_city' => 6330, 'id_state' => 16, 'name' => ' Lagoa Verde'],
                ['id_city' => 6331, 'id_state' => 16, 'name' => ' Lagoinha'],
                ['id_city' => 6332, 'id_state' => 16, 'name' => ' Lajeado'],
                ['id_city' => 6333, 'id_state' => 16, 'name' => ' Lajeado Bonito'],
                ['id_city' => 6334, 'id_state' => 16, 'name' => ' Lajeado Grande'],
                ['id_city' => 6335, 'id_state' => 16, 'name' => ' Lambari'],
                ['id_city' => 6336, 'id_state' => 16, 'name' => ' Lapa'],
                ['id_city' => 6337, 'id_state' => 16, 'name' => ' Laranja Azeda'],
                ['id_city' => 6338, 'id_state' => 16, 'name' => ' Laranjal'],
                ['id_city' => 6339, 'id_state' => 16, 'name' => ' Laranjeiras do Sul'],
                ['id_city' => 6340, 'id_state' => 16, 'name' => ' Lavra'],
                ['id_city' => 6341, 'id_state' => 16, 'name' => ' Lavrinha'],
                ['id_city' => 6342, 'id_state' => 16, 'name' => ' Leópolis'],
                ['id_city' => 6343, 'id_state' => 16, 'name' => ' Lerroville'],
                ['id_city' => 6344, 'id_state' => 16, 'name' => ' Lidianópolis'],
                ['id_city' => 6345, 'id_state' => 16, 'name' => ' Lindoeste'],
                ['id_city' => 6346, 'id_state' => 16, 'name' => ' Linha Giacomini'],
                ['id_city' => 6347, 'id_state' => 16, 'name' => ' Loanda'],
                ['id_city' => 6348, 'id_state' => 16, 'name' => ' Lobato'],
                ['id_city' => 6349, 'id_state' => 16, 'name' => ' Londrina'],
                ['id_city' => 6350, 'id_state' => 16, 'name' => ' Lopei'],
                ['id_city' => 6351, 'id_state' => 16, 'name' => ' Lovat'],
                ['id_city' => 6352, 'id_state' => 16, 'name' => ' Luar'],
                ['id_city' => 6353, 'id_state' => 16, 'name' => ' Luiziana'],
                ['id_city' => 6354, 'id_state' => 16, 'name' => ' Lunardelli'],
                ['id_city' => 6355, 'id_state' => 16, 'name' => ' Lupionópolis'],
                ['id_city' => 6356, 'id_state' => 16, 'name' => ' Macaco'],
                ['id_city' => 6357, 'id_state' => 16, 'name' => ' Macucos'],
                ['id_city' => 6358, 'id_state' => 16, 'name' => ' Mairá'],
                ['id_city' => 6359, 'id_state' => 16, 'name' => ' Maitá'],
                ['id_city' => 6360, 'id_state' => 16, 'name' => ' Mallet'],
                ['id_city' => 6361, 'id_state' => 16, 'name' => ' Malu'],
                ['id_city' => 6362, 'id_state' => 16, 'name' => ' Mamborê'],
                ['id_city' => 6363, 'id_state' => 16, 'name' => ' Mandaçaia'],
                ['id_city' => 6364, 'id_state' => 16, 'name' => ' Mandaguaçu'],
                ['id_city' => 6365, 'id_state' => 16, 'name' => ' Mandaguari'],
                ['id_city' => 6366, 'id_state' => 16, 'name' => ' Mandiocaba'],
                ['id_city' => 6367, 'id_state' => 16, 'name' => ' Mandirituba'],
                ['id_city' => 6368, 'id_state' => 16, 'name' => ' Manfrinópolis'],
                ['id_city' => 6369, 'id_state' => 16, 'name' => ' Mangueirinha'],
                ['id_city' => 6370, 'id_state' => 16, 'name' => ' Manoel Ribas'],
                ['id_city' => 6371, 'id_state' => 16, 'name' => ' Marabá'],
                ['id_city' => 6372, 'id_state' => 16, 'name' => ' Maracanã'],
                ['id_city' => 6373, 'id_state' => 16, 'name' => ' Marajó'],
                ['id_city' => 6374, 'id_state' => 16, 'name' => ' Maravilha'],
                ['id_city' => 6375, 'id_state' => 16, 'name' => ' Marcelino'],
                ['id_city' => 6376, 'id_state' => 16, 'name' => ' Marcianópolis'],
                ['id_city' => 6377, 'id_state' => 16, 'name' => ' Marechal Cândido Rondon'],
                ['id_city' => 6378, 'id_state' => 16, 'name' => ' Margarida'],
                ['id_city' => 6379, 'id_state' => 16, 'name' => ' Maria Helena'],
                ['id_city' => 6380, 'id_state' => 16, 'name' => ' Maria Luiza'],
                ['id_city' => 6381, 'id_state' => 16, 'name' => ' Marialva'],
                ['id_city' => 6382, 'id_state' => 16, 'name' => ' Mariental'],
                ['id_city' => 6383, 'id_state' => 16, 'name' => ' Marilândia do Sul'],
                ['id_city' => 6384, 'id_state' => 16, 'name' => ' Marilena'],
                ['id_city' => 6385, 'id_state' => 16, 'name' => ' Marilu'],
                ['id_city' => 6386, 'id_state' => 16, 'name' => ' Mariluz'],
                ['id_city' => 6387, 'id_state' => 16, 'name' => ' Marimbondo'],
                ['id_city' => 6388, 'id_state' => 16, 'name' => ' Maringá'],
                ['id_city' => 6389, 'id_state' => 16, 'name' => ' Mariópolis'],
                ['id_city' => 6390, 'id_state' => 16, 'name' => ' Maripá'],
                ['id_city' => 6391, 'id_state' => 16, 'name' => ' Maristela'],
                ['id_city' => 6392, 'id_state' => 16, 'name' => ' Mariza'],
                ['id_city' => 6393, 'id_state' => 16, 'name' => ' Marmelândia'],
                ['id_city' => 6394, 'id_state' => 16, 'name' => ' Marmeleiro'],
                ['id_city' => 6395, 'id_state' => 16, 'name' => ' Marquês de Abrantes'],
                ['id_city' => 6396, 'id_state' => 16, 'name' => ' Marquinho'],
                ['id_city' => 6397, 'id_state' => 16, 'name' => ' Marrecas'],
                ['id_city' => 6398, 'id_state' => 16, 'name' => ' Martins'],
                ['id_city' => 6399, 'id_state' => 16, 'name' => ' Marumbi'],
                ['id_city' => 6400, 'id_state' => 16, 'name' => ' Matelândia'],
                ['id_city' => 6401, 'id_state' => 16, 'name' => ' Matinhos'],
                ['id_city' => 6402, 'id_state' => 16, 'name' => ' Mato Queimado'],
                ['id_city' => 6403, 'id_state' => 16, 'name' => ' Mato Rico'],
                ['id_city' => 6404, 'id_state' => 16, 'name' => ' Mauá da Serra'],
                ['id_city' => 6405, 'id_state' => 16, 'name' => ' Medianeira'],
                ['id_city' => 6406, 'id_state' => 16, 'name' => ' Meia-Lua'],
                ['id_city' => 6407, 'id_state' => 16, 'name' => ' Memória'],
                ['id_city' => 6408, 'id_state' => 16, 'name' => ' Mendeslândia'],
                ['id_city' => 6409, 'id_state' => 16, 'name' => ' Mercedes'],
                ['id_city' => 6410, 'id_state' => 16, 'name' => ' Mirador'],
                ['id_city' => 6411, 'id_state' => 16, 'name' => ' Miranda'],
                ['id_city' => 6412, 'id_state' => 16, 'name' => ' Mirante do Piquiri'],
                ['id_city' => 6413, 'id_state' => 16, 'name' => ' Miraselva'],
                ['id_city' => 6414, 'id_state' => 16, 'name' => ' Missal'],
                ['id_city' => 6415, 'id_state' => 16, 'name' => ' Monjolinho'],
                ['id_city' => 6416, 'id_state' => 16, 'name' => ' Monte Real'],
                ['id_city' => 6417, 'id_state' => 16, 'name' => ' Moreira Sales'],
                ['id_city' => 6418, 'id_state' => 16, 'name' => ' Morretes'],
                ['id_city' => 6419, 'id_state' => 16, 'name' => ' Morro Alto'],
                ['id_city' => 6420, 'id_state' => 16, 'name' => ' Morro Inglês'],
                ['id_city' => 6421, 'id_state' => 16, 'name' => ' Munhoz de Melo'],
                ['id_city' => 6422, 'id_state' => 16, 'name' => ' Natingui'],
                ['id_city' => 6423, 'id_state' => 16, 'name' => ' Nilza'],
                ['id_city' => 6424, 'id_state' => 16, 'name' => ' Nordestina'],
                ['id_city' => 6425, 'id_state' => 16, 'name' => ' Nossa Senhora Aparecida'],
                ['id_city' => 6426, 'id_state' => 16, 'name' => ' Nossa Senhora da Aparecida'],
                ['id_city' => 6427, 'id_state' => 16, 'name' => ' Nossa Senhora da Candelária'],
                ['id_city' => 6428, 'id_state' => 16, 'name' => ' Nossa Senhora das Graças'],
                ['id_city' => 6429, 'id_state' => 16, 'name' => ' Nossa Senhora de Lourdes'],
                ['id_city' => 6430, 'id_state' => 16, 'name' => ' Nossa Senhora do Carmo'],
                ['id_city' => 6431, 'id_state' => 16, 'name' => ' Nova Aliança do Ivaí'],
                ['id_city' => 6432, 'id_state' => 16, 'name' => ' Nova Altamira'],
                ['id_city' => 6433, 'id_state' => 16, 'name' => ' Nova América da Colina'],
                ['id_city' => 6434, 'id_state' => 16, 'name' => ' Nova Amoreira'],
                ['id_city' => 6435, 'id_state' => 16, 'name' => ' Nova Aurora'],
                ['id_city' => 6436, 'id_state' => 16, 'name' => ' Nova Bilac'],
                ['id_city' => 6437, 'id_state' => 16, 'name' => ' Nova Brasília'],
                ['id_city' => 6438, 'id_state' => 16, 'name' => ' Nova Brasília do Itararé'],
                ['id_city' => 6439, 'id_state' => 16, 'name' => ' Nova Cantu'],
                ['id_city' => 6440, 'id_state' => 16, 'name' => ' Nova Concórdia'],
                ['id_city' => 6441, 'id_state' => 16, 'name' => ' Concórdia do Oeste'],
                ['id_city' => 6442, 'id_state' => 16, 'name' => ' Nova Esperança'],
                ['id_city' => 6443, 'id_state' => 16, 'name' => ' Nova Esperança do Sudoeste'],
                ['id_city' => 6444, 'id_state' => 16, 'name' => ' Nova Fátima'],
                ['id_city' => 6445, 'id_state' => 16, 'name' => ' Nova Laranjeiras'],
                ['id_city' => 6446, 'id_state' => 16, 'name' => ' Nova Londrina'],
                ['id_city' => 6447, 'id_state' => 16, 'name' => ' Nova Lourdes'],
                ['id_city' => 6448, 'id_state' => 16, 'name' => ' Nova Olímpia'],
                ['id_city' => 6449, 'id_state' => 16, 'name' => ' Nova Prata do Iguaçu'],
                ['id_city' => 6450, 'id_state' => 16, 'name' => ' Nova Riqueza'],
                ['id_city' => 6451, 'id_state' => 16, 'name' => ' Nova Santa Bárbara'],
                ['id_city' => 6452, 'id_state' => 16, 'name' => ' Nova Santa Rosa'],
                ['id_city' => 6453, 'id_state' => 16, 'name' => ' Nova Tebas'],
                ['id_city' => 6454, 'id_state' => 16, 'name' => ' Nova Tirol'],
                ['id_city' => 6455, 'id_state' => 16, 'name' => ' Nova Videira'],
                ['id_city' => 6456, 'id_state' => 16, 'name' => ' Novo Horizonte'],
                ['id_city' => 6457, 'id_state' => 16, 'name' => ' Novo Itacolomi'],
                ['id_city' => 6458, 'id_state' => 16, 'name' => ' Novo Jardim'],
                ['id_city' => 6459, 'id_state' => 16, 'name' => ' Novo Sarandi'],
                ['id_city' => 6460, 'id_state' => 16, 'name' => ' Novo Sobradinho'],
                ['id_city' => 6461, 'id_state' => 16, 'name' => ' Novo Três Passos'],
                ['id_city' => 6462, 'id_state' => 16, 'name' => ' Olaria'],
                ['id_city' => 6463, 'id_state' => 16, 'name' => ' Olho Agudo'],
                ['id_city' => 6464, 'id_state' => 16, 'name' => ' Olho d Água'],
                ['id_city' => 6465, 'id_state' => 16, 'name' => ' Oroité'],
                ['id_city' => 6466, 'id_state' => 16, 'name' => ' Ortigueira'],
                ['id_city' => 6467, 'id_state' => 16, 'name' => ' Ourilândia'],
                ['id_city' => 6468, 'id_state' => 16, 'name' => ' Ourizona'],
                ['id_city' => 6469, 'id_state' => 16, 'name' => ' Ouro Verde do Oeste'],
                ['id_city' => 6470, 'id_state' => 16, 'name' => ' Ouro Verde do Piquiri'],
                ['id_city' => 6471, 'id_state' => 16, 'name' => ' Padre Ponciano'],
                ['id_city' => 6472, 'id_state' => 16, 'name' => ' Paiçandu'],
                ['id_city' => 6473, 'id_state' => 16, 'name' => ' Paiol de Baixo'],
                ['id_city' => 6474, 'id_state' => 16, 'name' => ' Paiol Queimado'],
                ['id_city' => 6475, 'id_state' => 16, 'name' => ' Paiquerê'],
                ['id_city' => 6476, 'id_state' => 16, 'name' => ' Palmas'],
                ['id_city' => 6477, 'id_state' => 16, 'name' => ' Palmeira'],
                ['id_city' => 6478, 'id_state' => 16, 'name' => ' Palmeirinha'],
                ['id_city' => 6479, 'id_state' => 16, 'name' => ' Palmira'],
                ['id_city' => 6480, 'id_state' => 16, 'name' => ' Palmital'],
                ['id_city' => 6481, 'id_state' => 16, 'name' => ' Palmital de São Silvestre'],
                ['id_city' => 6482, 'id_state' => 16, 'name' => ' Palmitópolis'],
                ['id_city' => 6483, 'id_state' => 16, 'name' => ' Palotina'],
                ['id_city' => 6484, 'id_state' => 16, 'name' => ' Panema'],
                ['id_city' => 6485, 'id_state' => 16, 'name' => ' Pangaré'],
                ['id_city' => 6486, 'id_state' => 16, 'name' => ' Papagaios Novos'],
                ['id_city' => 6487, 'id_state' => 16, 'name' => ' Paraíso do Norte'],
                ['id_city' => 6488, 'id_state' => 16, 'name' => ' Paraná d Oeste'],
                ['id_city' => 6489, 'id_state' => 16, 'name' => ' Paranacity'],
                ['id_city' => 6490, 'id_state' => 16, 'name' => ' Paranagi'],
                ['id_city' => 6491, 'id_state' => 16, 'name' => ' Paranaguá'],
                ['id_city' => 6492, 'id_state' => 16, 'name' => ' Paranapoema'],
                ['id_city' => 6493, 'id_state' => 16, 'name' => ' Paranavaí'],
                ['id_city' => 6494, 'id_state' => 16, 'name' => ' Passa Una'],
                ['id_city' => 6495, 'id_state' => 16, 'name' => ' Passo da Ilha'],
                ['id_city' => 6496, 'id_state' => 16, 'name' => ' Passo dos Pupos'],
                ['id_city' => 6497, 'id_state' => 16, 'name' => ' Passo Fundo'],
                ['id_city' => 6498, 'id_state' => 16, 'name' => ' Passo Liso'],
                ['id_city' => 6499, 'id_state' => 16, 'name' => ' Pato Bragado'],
                ['id_city' => 6500, 'id_state' => 16, 'name' => ' Pato Branco'],
                ['id_city' => 6501, 'id_state' => 16, 'name' => ' Patos Velhos'],
                ['id_city' => 6502, 'id_state' => 16, 'name' => ' Pau d Alho do Sul'],
                ['id_city' => 6503, 'id_state' => 16, 'name' => ' Paula Freitas'],
                ['id_city' => 6504, 'id_state' => 16, 'name' => ' Paulistânia'],
                ['id_city' => 6505, 'id_state' => 16, 'name' => ' Paulo Frontin'],
                ['id_city' => 6506, 'id_state' => 16, 'name' => ' Peabiru'],
                ['id_city' => 6507, 'id_state' => 16, 'name' => ' Pedra Branca do Araraquara'],
                ['id_city' => 6508, 'id_state' => 16, 'name' => ' Pedras'],
                ['id_city' => 6509, 'id_state' => 16, 'name' => ' Pedro Lustosa'],
                ['id_city' => 6510, 'id_state' => 16, 'name' => ' Pelado'],
                ['id_city' => 6511, 'id_state' => 16, 'name' => ' Perobal'],
                ['id_city' => 6512, 'id_state' => 16, 'name' => ' Pérola'],
                ['id_city' => 6513, 'id_state' => 16, 'name' => ' Pérola d Oeste'],
                ['id_city' => 6514, 'id_state' => 16, 'name' => ' Pérola Independente'],
                ['id_city' => 6515, 'id_state' => 16, 'name' => ' Piassuguera'],
                ['id_city' => 6516, 'id_state' => 16, 'name' => ' Piên'],
                ['id_city' => 6517, 'id_state' => 16, 'name' => ' Pinaré'],
                ['id_city' => 6518, 'id_state' => 16, 'name' => ' Pinhais'],
                ['id_city' => 6519, 'id_state' => 16, 'name' => ' Pinhal de São Bento'],
                ['id_city' => 6520, 'id_state' => 16, 'name' => ' Pinhalão'],
                ['id_city' => 6521, 'id_state' => 16, 'name' => ' Pinhalzinho'],
                ['id_city' => 6522, 'id_state' => 16, 'name' => ' Pinhão'],
                ['id_city' => 6523, 'id_state' => 16, 'name' => ' Pinheiro'],
                ['id_city' => 6524, 'id_state' => 16, 'name' => ' Piquirivaí'],
                ['id_city' => 6525, 'id_state' => 16, 'name' => ' Piracema'],
                ['id_city' => 6526, 'id_state' => 16, 'name' => ' Piraí do Sul'],
                ['id_city' => 6527, 'id_state' => 16, 'name' => ' Pirapó'],
                ['id_city' => 6528, 'id_state' => 16, 'name' => ' Piraquara'],
                ['id_city' => 6529, 'id_state' => 16, 'name' => ' Piriquitos'],
                ['id_city' => 6530, 'id_state' => 16, 'name' => ' Pitanga'],
                ['id_city' => 6531, 'id_state' => 16, 'name' => ' Pitangueiras'],
                ['id_city' => 6532, 'id_state' => 16, 'name' => ' Pitangui'],
                ['id_city' => 6533, 'id_state' => 16, 'name' => ' Planaltina do Paraná'],
                ['id_city' => 6534, 'id_state' => 16, 'name' => ' Planalto'],
                ['id_city' => 6535, 'id_state' => 16, 'name' => ' Pocinho'],
                ['id_city' => 6536, 'id_state' => 16, 'name' => ' Poema'],
                ['id_city' => 6537, 'id_state' => 16, 'name' => ' Ponta do Pasto'],
                ['id_city' => 6538, 'id_state' => 16, 'name' => ' Ponta Grossa'],
                ['id_city' => 6539, 'id_state' => 16, 'name' => ' Pontal do Paraná'],
                ['id_city' => 6540, 'id_state' => 16, 'name' => ' Porecatu'],
                ['id_city' => 6541, 'id_state' => 16, 'name' => ' Portão'],
                ['id_city' => 6542, 'id_state' => 16, 'name' => ' Porteira Preta'],
                ['id_city' => 6543, 'id_state' => 16, 'name' => ' Porto Amazonas'],
                ['id_city' => 6544, 'id_state' => 16, 'name' => ' Porto Barreiro'],
                ['id_city' => 6545, 'id_state' => 16, 'name' => ' Porto Belo'],
                ['id_city' => 6546, 'id_state' => 16, 'name' => ' Porto Brasílio'],
                ['id_city' => 6547, 'id_state' => 16, 'name' => ' Porto Camargo'],
                ['id_city' => 6548, 'id_state' => 16, 'name' => ' Porto de Cima'],
                ['id_city' => 6549, 'id_state' => 16, 'name' => ' Porto Meira'],
                ['id_city' => 6550, 'id_state' => 16, 'name' => ' Porto Mendes'],
                ['id_city' => 6551, 'id_state' => 16, 'name' => ' Porto Rico'],
                ['id_city' => 6552, 'id_state' => 16, 'name' => ' Porto San Juan'],
                ['id_city' => 6553, 'id_state' => 16, 'name' => ' Porto Santana'],
                ['id_city' => 6554, 'id_state' => 16, 'name' => ' Porto São Carlos'],
                ['id_city' => 6555, 'id_state' => 16, 'name' => ' Porto São José'],
                ['id_city' => 6556, 'id_state' => 16, 'name' => ' Porto Vitória'],
                ['id_city' => 6557, 'id_state' => 16, 'name' => ' Prado Ferreira'],
                ['id_city' => 6558, 'id_state' => 16, 'name' => ' Pranchita'],
                ['id_city' => 6559, 'id_state' => 16, 'name' => ' Prata'],
                ['id_city' => 6560, 'id_state' => 16, 'name' => ' Prata Um'],
                ['id_city' => 6561, 'id_state' => 16, 'name' => ' Presidente Castelo Branco'],
                ['id_city' => 6562, 'id_state' => 16, 'name' => ' Presidente Kennedy'],
                ['id_city' => 6563, 'id_state' => 16, 'name' => ' Primeiro de Maio'],
                ['id_city' => 6564, 'id_state' => 16, 'name' => ' Progresso'],
                ['id_city' => 6565, 'id_state' => 16, 'name' => ' Prudentópolis'],
                ['id_city' => 6566, 'id_state' => 16, 'name' => ' Pulinópolis'],
                ['id_city' => 6567, 'id_state' => 16, 'name' => ' Quatiguá'],
                ['id_city' => 6568, 'id_state' => 16, 'name' => ' Quatro Barras'],
                ['id_city' => 6569, 'id_state' => 16, 'name' => ' Quatro Pontes'],
                ['id_city' => 6570, 'id_state' => 16, 'name' => ' Quebra Freio'],
                ['id_city' => 6571, 'id_state' => 16, 'name' => ' Quedas do Iguaçu'],
                ['id_city' => 6572, 'id_state' => 16, 'name' => ' Queimados'],
                ['id_city' => 6573, 'id_state' => 16, 'name' => ' Querência do Norte'],
                ['id_city' => 6574, 'id_state' => 16, 'name' => ' Quinta do Sol'],
                ['id_city' => 6575, 'id_state' => 16, 'name' => ' Quinzópolis'],
                ['id_city' => 6576, 'id_state' => 16, 'name' => ' Quitandinha'],
                ['id_city' => 6577, 'id_state' => 16, 'name' => ' Ramilândia'],
                ['id_city' => 6578, 'id_state' => 16, 'name' => ' Rancho Alegre'],
                ['id_city' => 6579, 'id_state' => 16, 'name' => ' Rancho Alegre d Oeste'],
                ['id_city' => 6580, 'id_state' => 16, 'name' => ' Realeza'],
                ['id_city' => 6581, 'id_state' => 16, 'name' => ' Rebouças'],
                ['id_city' => 6582, 'id_state' => 16, 'name' => ' Região dos Valos'],
                ['id_city' => 6583, 'id_state' => 16, 'name' => ' Reianópolis'],
                ['id_city' => 6584, 'id_state' => 16, 'name' => ' Renascença'],
                ['id_city' => 6585, 'id_state' => 16, 'name' => ' Reserva'],
                ['id_city' => 6586, 'id_state' => 16, 'name' => ' Reserva do Iguaçu'],
                ['id_city' => 6587, 'id_state' => 16, 'name' => ' Retiro'],
                ['id_city' => 6588, 'id_state' => 16, 'name' => ' Retiro Grande'],
                ['id_city' => 6589, 'id_state' => 16, 'name' => ' Ribeirão Bonito'],
                ['id_city' => 6590, 'id_state' => 16, 'name' => ' Ribeirão Claro'],
                ['id_city' => 6591, 'id_state' => 16, 'name' => ' Ribeirão do Pinhal'],
                ['id_city' => 6592, 'id_state' => 16, 'name' => ' Ribeirão do Pinheiro'],
                ['id_city' => 6593, 'id_state' => 16, 'name' => ' Rio Abaixo'],
                ['id_city' => 6594, 'id_state' => 16, 'name' => ' Rio Azul'],
                ['id_city' => 6595, 'id_state' => 16, 'name' => ' Rio Bom'],
                ['id_city' => 6596, 'id_state' => 16, 'name' => ' Rio Bonito'],
                ['id_city' => 6597, 'id_state' => 16, 'name' => ' Rio Bonito do Iguaçu'],
                ['id_city' => 6598, 'id_state' => 16, 'name' => ' Rio Branco do Ivaí'],
                ['id_city' => 6599, 'id_state' => 16, 'name' => ' Rio Branco do Sul'],
                ['id_city' => 6600, 'id_state' => 16, 'name' => ' Rio Claro do Sul'],
                ['id_city' => 6601, 'id_state' => 16, 'name' => ' Rio da Prata'],
                ['id_city' => 6602, 'id_state' => 16, 'name' => ' Rio das Antas'],
                ['id_city' => 6603, 'id_state' => 16, 'name' => ' Rio das Mortes'],
                ['id_city' => 6604, 'id_state' => 16, 'name' => ' Rio das Pedras'],
                ['id_city' => 6605, 'id_state' => 16, 'name' => ' Rio das Pombas'],
                ['id_city' => 6606, 'id_state' => 16, 'name' => ' Rio do Mato'],
                ['id_city' => 6607, 'id_state' => 16, 'name' => ' Rio do Salto'],
                ['id_city' => 6608, 'id_state' => 16, 'name' => ' Rio Negro'],
                ['id_city' => 6609, 'id_state' => 16, 'name' => ' Rio Novo'],
                ['id_city' => 6610, 'id_state' => 16, 'name' => ' Rio Pinheiro'],
                ['id_city' => 6611, 'id_state' => 16, 'name' => ' Rio Quatorze'],
                ['id_city' => 6612, 'id_state' => 16, 'name' => ' Rio Saltinho'],
                ['id_city' => 6613, 'id_state' => 16, 'name' => ' Rio Saudade'],
                ['id_city' => 6614, 'id_state' => 16, 'name' => ' Rio Verde'],
                ['id_city' => 6615, 'id_state' => 16, 'name' => ' Roberto Silveira'],
                ['id_city' => 6616, 'id_state' => 16, 'name' => ' Roça Velha'],
                ['id_city' => 6617, 'id_state' => 16, 'name' => ' Rolândia'],
                ['id_city' => 6618, 'id_state' => 16, 'name' => ' Romeópolis'],
                ['id_city' => 6619, 'id_state' => 16, 'name' => ' Roncador'],
                ['id_city' => 6620, 'id_state' => 16, 'name' => ' Rondinha'],
                ['id_city' => 6621, 'id_state' => 16, 'name' => ' Rondon'],
                ['id_city' => 6622, 'id_state' => 16, 'name' => ' Rosário do Ivaí'],
                ['id_city' => 6623, 'id_state' => 16, 'name' => ' Sabáudia'],
                ['id_city' => 6624, 'id_state' => 16, 'name' => ' Sagrada Família'],
                ['id_city' => 6625, 'id_state' => 16, 'name' => ' Salgado Filho'],
                ['id_city' => 6626, 'id_state' => 16, 'name' => ' Salles de Oliveira'],
                ['id_city' => 6627, 'id_state' => 16, 'name' => ' Saltinho do Oeste'],
                ['id_city' => 6628, 'id_state' => 16, 'name' => ' Salto do Itararé'],
                ['id_city' => 6629, 'id_state' => 16, 'name' => ' Salto do Lontra'],
                ['id_city' => 6630, 'id_state' => 16, 'name' => ' Salto Portão'],
                ['id_city' => 6631, 'id_state' => 16, 'name' => ' Colônia Samambaia'],
                ['id_city' => 6632, 'id_state' => 16, 'name' => ' Santa Amélia'],
                ['id_city' => 6633, 'id_state' => 16, 'name' => ' Santa Cecília do Pavão'],
                ['id_city' => 6634, 'id_state' => 16, 'name' => ' Santa Clara'],
                ['id_city' => 6635, 'id_state' => 16, 'name' => ' Santa Cruz de Monte Castelo'],
                ['id_city' => 6636, 'id_state' => 16, 'name' => ' Santa Eliza'],
                ['id_city' => 6637, 'id_state' => 16, 'name' => ' Santa Esmeralda'],
                ['id_city' => 6638, 'id_state' => 16, 'name' => ' Santa Fé'],
                ['id_city' => 6639, 'id_state' => 16, 'name' => ' Santa Fé do Pirapó'],
                ['id_city' => 6640, 'id_state' => 16, 'name' => ' Santa Helena'],
                ['id_city' => 6641, 'id_state' => 16, 'name' => ' Santa Inês'],
                ['id_city' => 6642, 'id_state' => 16, 'name' => ' Santa Isabel do Ivaí'],
                ['id_city' => 6643, 'id_state' => 16, 'name' => ' Santa Izabel do Oeste'],
                ['id_city' => 6644, 'id_state' => 16, 'name' => ' Santa Lúcia'],
                ['id_city' => 6645, 'id_state' => 16, 'name' => ' Santa Lurdes'],
                ['id_city' => 6646, 'id_state' => 16, 'name' => ' Santa Luzia da Alvorada'],
                ['id_city' => 6647, 'id_state' => 16, 'name' => ' Santa Margarida'],
                ['id_city' => 6648, 'id_state' => 16, 'name' => ' Santa Maria'],
                ['id_city' => 6649, 'id_state' => 16, 'name' => ' Santa Maria do Oeste'],
                ['id_city' => 6650, 'id_state' => 16, 'name' => ' Santa Maria do Rio do Peixe'],
                ['id_city' => 6651, 'id_state' => 16, 'name' => ' Santa Mariana'],
                ['id_city' => 6652, 'id_state' => 16, 'name' => ' Santa Mônica'],
                ['id_city' => 6653, 'id_state' => 16, 'name' => ' Santa Quitéria'],
                ['id_city' => 6654, 'id_state' => 16, 'name' => ' Santa Rita'],
                ['id_city' => 6655, 'id_state' => 16, 'name' => ' Santa Rita do Oeste'],
                ['id_city' => 6656, 'id_state' => 16, 'name' => ' Santa Rosa'],
                ['id_city' => 6657, 'id_state' => 16, 'name' => ' Santa Tereza do Oeste'],
                ['id_city' => 6658, 'id_state' => 16, 'name' => ' Santa Terezinha de Itaipu'],
                ['id_city' => 6659, 'id_state' => 16, 'name' => ' Santa Zélia'],
                ['id_city' => 6660, 'id_state' => 16, 'name' => ' Santana'],
                ['id_city' => 6661, 'id_state' => 16, 'name' => ' Santana do Itararé'],
                ['id_city' => 6662, 'id_state' => 16, 'name' => ' Santo Antônio'],
                ['id_city' => 6663, 'id_state' => 16, 'name' => ' Santo Antônio da Platina'],
                ['id_city' => 6664, 'id_state' => 16, 'name' => ' Santo Antônio do Caiuá'],
                ['id_city' => 6665, 'id_state' => 16, 'name' => ' Santo Antônio do Iratim'],
                ['id_city' => 6666, 'id_state' => 16, 'name' => ' Santo Antônio do Palmital'],
                ['id_city' => 6667, 'id_state' => 16, 'name' => ' Santo Antônio do Paraíso'],
                ['id_city' => 6668, 'id_state' => 16, 'name' => ' Santo Antônio do Sudoeste'],
                ['id_city' => 6669, 'id_state' => 16, 'name' => ' Santo Inácio'],
                ['id_city' => 6670, 'id_state' => 16, 'name' => ' Santo Rei'],
                ['id_city' => 6671, 'id_state' => 16, 'name' => ' São Braz'],
                ['id_city' => 6672, 'id_state' => 16, 'name' => ' São Braz'],
                ['id_city' => 6673, 'id_state' => 16, 'name' => ' São Camilo'],
                ['id_city' => 6674, 'id_state' => 16, 'name' => ' São Carlos do Ivaí'],
                ['id_city' => 6675, 'id_state' => 16, 'name' => ' São Cirilo'],
                ['id_city' => 6676, 'id_state' => 16, 'name' => ' São Clemente'],
                ['id_city' => 6677, 'id_state' => 16, 'name' => ' São Cristovão'],
                ['id_city' => 6678, 'id_state' => 16, 'name' => ' São Domingos'],
                ['id_city' => 6679, 'id_state' => 16, 'name' => ' São Francisco'],
                ['id_city' => 6680, 'id_state' => 16, 'name' => ' São Francisco de Imbaú'],
                ['id_city' => 6681, 'id_state' => 16, 'name' => ' São Francisco de Sales'],
                ['id_city' => 6682, 'id_state' => 16, 'name' => ' São Gabriel'],
                ['id_city' => 6683, 'id_state' => 16, 'name' => ' São Gotardo'],
                ['id_city' => 6684, 'id_state' => 16, 'name' => ' São Jerônimo da Serra'],
                ['id_city' => 6685, 'id_state' => 16, 'name' => ' São João'],
                ['id_city' => 6686, 'id_state' => 16, 'name' => ' São João d Oeste'],
                ['id_city' => 6687, 'id_state' => 16, 'name' => ' São João do Caiuá'],
                ['id_city' => 6688, 'id_state' => 16, 'name' => ' São João do Ivaí'],
                ['id_city' => 6689, 'id_state' => 16, 'name' => ' São João do Pinhal'],
                ['id_city' => 6690, 'id_state' => 16, 'name' => ' São João do Triunfo'],
                ['id_city' => 6691, 'id_state' => 16, 'name' => ' São Joaquim'],
                ['id_city' => 6692, 'id_state' => 16, 'name' => ' São Joaquim do Pontal'],
                ['id_city' => 6693, 'id_state' => 16, 'name' => ' São Jorge D Oeste'],
                ['id_city' => 6694, 'id_state' => 16, 'name' => ' São Jorge do Ivaí'],
                ['id_city' => 6695, 'id_state' => 16, 'name' => ' São Jorge do Patrocínio'],
                ['id_city' => 6696, 'id_state' => 16, 'name' => ' São José'],
                ['id_city' => 6697, 'id_state' => 16, 'name' => ' São José da Boa Vista'],
                ['id_city' => 6698, 'id_state' => 16, 'name' => ' São José das Palmeiras'],
                ['id_city' => 6699, 'id_state' => 16, 'name' => ' São José do Iguaçu'],
                ['id_city' => 6700, 'id_state' => 16, 'name' => ' São José do Itavo'],
                ['id_city' => 6701, 'id_state' => 16, 'name' => ' São José do Ivaí'],
                ['id_city' => 6702, 'id_state' => 16, 'name' => ' São José dos Pinhais'],
                ['id_city' => 6703, 'id_state' => 16, 'name' => ' São Judas Tadeu'],
                ['id_city' => 6704, 'id_state' => 16, 'name' => ' São Leonardo'],
                ['id_city' => 6705, 'id_state' => 16, 'name' => ' São Lourenço'],
                ['id_city' => 6706, 'id_state' => 16, 'name' => ' São Luiz'],
                ['id_city' => 6707, 'id_state' => 16, 'name' => ' São Luiz do Purunã'],
                ['id_city' => 6708, 'id_state' => 16, 'name' => ' São Manoel do Paraná'],
                ['id_city' => 6709, 'id_state' => 16, 'name' => ' São Marcos'],
                ['id_city' => 6710, 'id_state' => 16, 'name' => ' São Martinho']
            ]);
        }
    }