<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities8 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 4788, 'id_state' => 14, 'name' => ' Inanu'],
                ['id_city' => 4789, 'id_state' => 14, 'name' => ' Inhangapi'],
                ['id_city' => 4790, 'id_state' => 14, 'name' => ' Ipixuna do Pará'],
                ['id_city' => 4791, 'id_state' => 14, 'name' => ' Irituia'],
                ['id_city' => 4792, 'id_state' => 14, 'name' => ' Itaituba'],
                ['id_city' => 4793, 'id_state' => 14, 'name' => ' Itapixuna'],
                ['id_city' => 4794, 'id_state' => 14, 'name' => ' Itatupã'],
                ['id_city' => 4795, 'id_state' => 14, 'name' => ' Itupiranga'],
                ['id_city' => 4796, 'id_state' => 14, 'name' => ' Jacareacanga'],
                ['id_city' => 4797, 'id_state' => 14, 'name' => ' Jacundá'],
                ['id_city' => 4798, 'id_state' => 14, 'name' => ' Jaguarari'],
                ['id_city' => 4799, 'id_state' => 14, 'name' => ' Jamanxinzinho'],
                ['id_city' => 4800, 'id_state' => 14, 'name' => ' Jambuaçu'],
                ['id_city' => 4801, 'id_state' => 14, 'name' => ' Jandiaí'],
                ['id_city' => 4802, 'id_state' => 14, 'name' => ' Japerica'],
                ['id_city' => 4803, 'id_state' => 14, 'name' => ' Joana Coeli'],
                ['id_city' => 4804, 'id_state' => 14, 'name' => ' Joana Peres'],
                ['id_city' => 4805, 'id_state' => 14, 'name' => ' Joanes'],
                ['id_city' => 4806, 'id_state' => 14, 'name' => ' Juabá'],
                ['id_city' => 4807, 'id_state' => 14, 'name' => ' Jubim'],
                ['id_city' => 4808, 'id_state' => 14, 'name' => ' Juruti'],
                ['id_city' => 4809, 'id_state' => 14, 'name' => ' Km 19'],
                ['id_city' => 4810, 'id_state' => 14, 'name' => ' Km 26'],
                ['id_city' => 4811, 'id_state' => 14, 'name' => ' Lauro Sodré'],
                ['id_city' => 4812, 'id_state' => 14, 'name' => ' Ligação do Pará'],
                ['id_city' => 4813, 'id_state' => 14, 'name' => ' Limoeiro do Ajuru'],
                ['id_city' => 4814, 'id_state' => 14, 'name' => ' Mãe do Rio'],
                ['id_city' => 4815, 'id_state' => 14, 'name' => ' Magalhães Barata'],
                ['id_city' => 4816, 'id_state' => 14, 'name' => ' Maiauata'],
                ['id_city' => 4817, 'id_state' => 14, 'name' => ' Manjeiro'],
                ['id_city' => 4818, 'id_state' => 14, 'name' => ' Marabá'],
                ['id_city' => 4819, 'id_state' => 14, 'name' => ' Maracanã'],
                ['id_city' => 4820, 'id_state' => 14, 'name' => ' Marajoara'],
                ['id_city' => 4821, 'id_state' => 14, 'name' => ' Marapanim'],
                ['id_city' => 4822, 'id_state' => 14, 'name' => ' Marituba'],
                ['id_city' => 4823, 'id_state' => 14, 'name' => ' Marudá'],
                ['id_city' => 4824, 'id_state' => 14, 'name' => ' Mata Geral'],
                ['id_city' => 4825, 'id_state' => 14, 'name' => ' Matapiquara'],
                ['id_city' => 4826, 'id_state' => 14, 'name' => ' Medicilândia'],
                ['id_city' => 4827, 'id_state' => 14, 'name' => ' Melgaço'],
                ['id_city' => 4828, 'id_state' => 14, 'name' => ' Menino Deus do Anapu'],
                ['id_city' => 4829, 'id_state' => 14, 'name' => ' Meruú'],
                ['id_city' => 4830, 'id_state' => 14, 'name' => ' Mirasselvas'],
                ['id_city' => 4831, 'id_state' => 14, 'name' => ' Miritituba'],
                ['id_city' => 4832, 'id_state' => 14, 'name' => ' Mocajuba'],
                ['id_city' => 4833, 'id_state' => 14, 'name' => ' Moiraba'],
                ['id_city' => 4834, 'id_state' => 14, 'name' => ' Moju'],
                ['id_city' => 4835, 'id_state' => 14, 'name' => ' Monsaras'],
                ['id_city' => 4836, 'id_state' => 14, 'name' => ' Monte Alegre'],
                ['id_city' => 4837, 'id_state' => 14, 'name' => ' Monte Alegre do Mau'],
                ['id_city' => 4838, 'id_state' => 14, 'name' => ' Monte Dourado'],
                ['id_city' => 4839, 'id_state' => 14, 'name' => ' Morada Nova'],
                ['id_city' => 4840, 'id_state' => 14, 'name' => ' Mosqueiro'],
                ['id_city' => 4841, 'id_state' => 14, 'name' => ' Muaná'],
                ['id_city' => 4842, 'id_state' => 14, 'name' => ' Mujuí dos Campos'],
                ['id_city' => 4843, 'id_state' => 14, 'name' => ' Murajá'],
                ['id_city' => 4844, 'id_state' => 14, 'name' => ' Murucupi'],
                ['id_city' => 4845, 'id_state' => 14, 'name' => ' Murumuru'],
                ['id_city' => 4846, 'id_state' => 14, 'name' => ' Muta'],
                ['id_city' => 4847, 'id_state' => 14, 'name' => ' Mutucal'],
                ['id_city' => 4848, 'id_state' => 14, 'name' => ' Nazaré de Mocajuba'],
                ['id_city' => 4849, 'id_state' => 14, 'name' => ' Nazaré dos Patos'],
                ['id_city' => 4850, 'id_state' => 14, 'name' => ' Nova Esperança do Piriá'],
                ['id_city' => 4851, 'id_state' => 14, 'name' => ' Nova Ipixuna'],
                ['id_city' => 4852, 'id_state' => 14, 'name' => ' Nova Mocajuba'],
                ['id_city' => 4853, 'id_state' => 14, 'name' => ' Nova Timboteua'],
                ['id_city' => 4854, 'id_state' => 14, 'name' => ' Novo Planalto'],
                ['id_city' => 4855, 'id_state' => 14, 'name' => ' Novo Progresso'],
                ['id_city' => 4856, 'id_state' => 14, 'name' => ' Novo Repartimento'],
                ['id_city' => 4857, 'id_state' => 14, 'name' => ' Núcleo Urbano Quilômetro 30'],
                ['id_city' => 4858, 'id_state' => 14, 'name' => ' Óbidos'],
                ['id_city' => 4859, 'id_state' => 14, 'name' => ' Oeiras do Pará'],
                ['id_city' => 4860, 'id_state' => 14, 'name' => ' Oriximiná'],
                ['id_city' => 4861, 'id_state' => 14, 'name' => ' Osvaldilândia'],
                ['id_city' => 4862, 'id_state' => 14, 'name' => ' Ourém'],
                ['id_city' => 4863, 'id_state' => 14, 'name' => ' Ourilândia do Norte'],
                ['id_city' => 4864, 'id_state' => 14, 'name' => ' Outeiro'],
                ['id_city' => 4865, 'id_state' => 14, 'name' => ' Pacajá'],
                ['id_city' => 4866, 'id_state' => 14, 'name' => ' Pacoval'],
                ['id_city' => 4867, 'id_state' => 14, 'name' => ' Palestina do Pará'],
                ['id_city' => 4868, 'id_state' => 14, 'name' => ' Paragominas'],
                ['id_city' => 4869, 'id_state' => 14, 'name' => ' Paratins'],
                ['id_city' => 4870, 'id_state' => 14, 'name' => ' Parauapebas'],
                ['id_city' => 4871, 'id_state' => 14, 'name' => ' Pau D Arco'],
                ['id_city' => 4872, 'id_state' => 14, 'name' => ' Pedreira'],
                ['id_city' => 4873, 'id_state' => 14, 'name' => ' Peixe-Boi'],
                ['id_city' => 4874, 'id_state' => 14, 'name' => ' Penhalonga'],
                ['id_city' => 4875, 'id_state' => 14, 'name' => ' Perseverança'],
                ['id_city' => 4876, 'id_state' => 14, 'name' => ' Pesqueiro'],
                ['id_city' => 4877, 'id_state' => 14, 'name' => ' Piabas'],
                ['id_city' => 4878, 'id_state' => 14, 'name' => ' Piçarra'],
                ['id_city' => 4879, 'id_state' => 14, 'name' => ' Piçarra'],
                ['id_city' => 4880, 'id_state' => 14, 'name' => ' Pinhal'],
                ['id_city' => 4881, 'id_state' => 14, 'name' => ' Piraquara'],
                ['id_city' => 4882, 'id_state' => 14, 'name' => ' Piriá'],
                ['id_city' => 4883, 'id_state' => 14, 'name' => ' Placas'],
                ['id_city' => 4884, 'id_state' => 14, 'name' => ' Ponta de Pedras'],
                ['id_city' => 4885, 'id_state' => 14, 'name' => ' Ponta de Ramos'],
                ['id_city' => 4886, 'id_state' => 14, 'name' => ' Portel'],
                ['id_city' => 4887, 'id_state' => 14, 'name' => ' Porto de Moz'],
                ['id_city' => 4888, 'id_state' => 14, 'name' => ' Porto Salvo'],
                ['id_city' => 4889, 'id_state' => 14, 'name' => ' Porto Trombetas'],
                ['id_city' => 4890, 'id_state' => 14, 'name' => ' Prainha'],
                ['id_city' => 4891, 'id_state' => 14, 'name' => ' Primavera'],
                ['id_city' => 4892, 'id_state' => 14, 'name' => ' Quatipuru'],
                ['id_city' => 4893, 'id_state' => 14, 'name' => ' Quatro Bocas'],
                ['id_city' => 4894, 'id_state' => 14, 'name' => ' Redenção'],
                ['id_city' => 4895, 'id_state' => 14, 'name' => ' Remansão'],
                ['id_city' => 4896, 'id_state' => 14, 'name' => ' Repartimento'],
                ['id_city' => 4897, 'id_state' => 14, 'name' => ' Rio Maria'],
                ['id_city' => 4898, 'id_state' => 14, 'name' => ' Rio Vermelho'],
                ['id_city' => 4899, 'id_state' => 14, 'name' => ' Riozinho'],
                ['id_city' => 4900, 'id_state' => 14, 'name' => ' Rondon do Pará'],
                ['id_city' => 4901, 'id_state' => 14, 'name' => ' Rurópolis'],
                ['id_city' => 4902, 'id_state' => 14, 'name' => ' Salinópolis'],
                ['id_city' => 4903, 'id_state' => 14, 'name' => ' Salvaterra'],
                ['id_city' => 4904, 'id_state' => 14, 'name' => ' Santa Bárbara do Pará'],
                ['id_city' => 4905, 'id_state' => 14, 'name' => ' Santa Cruz do Arari'],
                ['id_city' => 4906, 'id_state' => 14, 'name' => ' Santa Isabel do Pará'],
                ['id_city' => 4907, 'id_state' => 14, 'name' => ' Santa Luzia do Pará'],
                ['id_city' => 4908, 'id_state' => 14, 'name' => ' Santa Maria'],
                ['id_city' => 4909, 'id_state' => 14, 'name' => ' Santa Maria das Barreiras'],
                ['id_city' => 4910, 'id_state' => 14, 'name' => ' Santa Maria do Pará'],
                ['id_city' => 4911, 'id_state' => 14, 'name' => ' Santa Rosa da Vigia'],
                ['id_city' => 4912, 'id_state' => 14, 'name' => ' Santa Terezinha'],
                ['id_city' => 4913, 'id_state' => 14, 'name' => ' Santana do Araguaia'],
                ['id_city' => 4914, 'id_state' => 14, 'name' => ' Santarém'],
                ['id_city' => 4915, 'id_state' => 14, 'name' => ' Santarém Novo'],
                ['id_city' => 4916, 'id_state' => 14, 'name' => ' Santo Antônio'],
                ['id_city' => 4917, 'id_state' => 14, 'name' => ' Santo Antônio do Tauá'],
                ['id_city' => 4918, 'id_state' => 14, 'name' => ' São Caetano de Odivelas'],
                ['id_city' => 4919, 'id_state' => 14, 'name' => ' São Domingos do Araguaia'],
                ['id_city' => 4920, 'id_state' => 14, 'name' => ' São Domingos do Capim'],
                ['id_city' => 4921, 'id_state' => 14, 'name' => ' São Félix do Xingu'],
                ['id_city' => 4922, 'id_state' => 14, 'name' => ' São Francisco'],
                ['id_city' => 4923, 'id_state' => 14, 'name' => ' São Francisco da Jararaca'],
                ['id_city' => 4924, 'id_state' => 14, 'name' => ' São Francisco do Pará'],
                ['id_city' => 4925, 'id_state' => 14, 'name' => ' São Geraldo do Araguaia'],
                ['id_city' => 4926, 'id_state' => 14, 'name' => ' São João da Ponta'],
                ['id_city' => 4927, 'id_state' => 14, 'name' => ' São João de Pirabas'],
                ['id_city' => 4928, 'id_state' => 14, 'name' => ' São João do Acangata'],
                ['id_city' => 4929, 'id_state' => 14, 'name' => ' São João do Araguaia'],
                ['id_city' => 4930, 'id_state' => 14, 'name' => ' São João do Piriá'],
                ['id_city' => 4931, 'id_state' => 14, 'name' => ' São João dos Ramos'],
                ['id_city' => 4932, 'id_state' => 14, 'name' => ' São Joaquim do Tapará'],
                ['id_city' => 4933, 'id_state' => 14, 'name' => ' São Jorge'],
                ['id_city' => 4934, 'id_state' => 14, 'name' => ' São José do Gurupi'],
                ['id_city' => 4935, 'id_state' => 14, 'name' => ' São José do Piriá'],
                ['id_city' => 4936, 'id_state' => 14, 'name' => ' São Luiz do Tapajós'],
                ['id_city' => 4937, 'id_state' => 14, 'name' => ' São Miguel do Guamá'],
                ['id_city' => 4938, 'id_state' => 14, 'name' => ' São Miguel dos Macacos'],
                ['id_city' => 4939, 'id_state' => 14, 'name' => ' São Pedro de Viseu'],
                ['id_city' => 4940, 'id_state' => 14, 'name' => ' São Pedro do Capim'],
                ['id_city' => 4941, 'id_state' => 14, 'name' => ' São Raimundo de Borralhos'],
                ['id_city' => 4942, 'id_state' => 14, 'name' => ' São Raimundo do Araguaia'],
                ['id_city' => 4943, 'id_state' => 14, 'name' => ' São Raimundo dos Furtados'],
                ['id_city' => 4944, 'id_state' => 14, 'name' => ' São Roberto'],
                ['id_city' => 4945, 'id_state' => 14, 'name' => ' São Sebastião da Boa Vista'],
                ['id_city' => 4946, 'id_state' => 14, 'name' => ' São Sebastião de Viçosa'],
                ['id_city' => 4947, 'id_state' => 14, 'name' => ' Sapucaia'],
                ['id_city' => 4948, 'id_state' => 14, 'name' => ' Senador José Porfírio'],
                ['id_city' => 4949, 'id_state' => 14, 'name' => ' Serra Pelada'],
                ['id_city' => 4950, 'id_state' => 14, 'name' => ' Soure'],
                ['id_city' => 4951, 'id_state' => 14, 'name' => ' Tailândia'],
                ['id_city' => 4952, 'id_state' => 14, 'name' => ' Tatuteua'],
                ['id_city' => 4953, 'id_state' => 14, 'name' => ' Tauari'],
                ['id_city' => 4954, 'id_state' => 14, 'name' => ' Tauarizinho'],
                ['id_city' => 4955, 'id_state' => 14, 'name' => ' Tentugal'],
                ['id_city' => 4956, 'id_state' => 14, 'name' => ' Terra Alta'],
                ['id_city' => 4957, 'id_state' => 14, 'name' => ' Terra Santa'],
                ['id_city' => 4958, 'id_state' => 14, 'name' => ' Tijoca'],
                ['id_city' => 4959, 'id_state' => 14, 'name' => ' Timboteua'],
                ['id_city' => 4960, 'id_state' => 14, 'name' => ' Tomé-Açú'],
                ['id_city' => 4961, 'id_state' => 14, 'name' => ' Tracuateua'],
                ['id_city' => 4962, 'id_state' => 14, 'name' => ' Trairão'],
                ['id_city' => 4963, 'id_state' => 14, 'name' => ' Tucumã'],
                ['id_city' => 4964, 'id_state' => 14, 'name' => ' Tucuruí'],
                ['id_city' => 4965, 'id_state' => 14, 'name' => ' Ulianópolis'],
                ['id_city' => 4966, 'id_state' => 14, 'name' => ' Uruará'],
                ['id_city' => 4967, 'id_state' => 14, 'name' => ' Urucuri'],
                ['id_city' => 4968, 'id_state' => 14, 'name' => ' Urucuriteua'],
                ['id_city' => 4969, 'id_state' => 14, 'name' => ' Val-de-Cães'],
                ['id_city' => 4970, 'id_state' => 14, 'name' => ' Veiros'],
                ['id_city' => 4971, 'id_state' => 14, 'name' => ' Vigia'],
                ['id_city' => 4972, 'id_state' => 14, 'name' => ' Vila do Carmo do Tocantins'],
                ['id_city' => 4973, 'id_state' => 14, 'name' => ' Vila dos Cabanos'],
                ['id_city' => 4974, 'id_state' => 14, 'name' => ' Vila França'],
                ['id_city' => 4975, 'id_state' => 14, 'name' => ' Vila Goreth'],
                ['id_city' => 4976, 'id_state' => 14, 'name' => ' Vila Isol'],
                ['id_city' => 4977, 'id_state' => 14, 'name' => ' Vila Nova'],
                ['id_city' => 4978, 'id_state' => 14, 'name' => ' Vila Planalto'],
                ['id_city' => 4979, 'id_state' => 14, 'name' => ' Vila Santa Fé'],
                ['id_city' => 4980, 'id_state' => 14, 'name' => ' Vila Socorro'],
                ['id_city' => 4981, 'id_state' => 14, 'name' => ' Vilarinho do Monte'],
                ['id_city' => 4982, 'id_state' => 14, 'name' => ' Viseu'],
                ['id_city' => 4983, 'id_state' => 14, 'name' => ' Vista Alegre'],
                ['id_city' => 4984, 'id_state' => 14, 'name' => ' Vista Alegre do Pará'],
                ['id_city' => 4985, 'id_state' => 14, 'name' => ' Vitória do Xingu'],
                ['id_city' => 4986, 'id_state' => 14, 'name' => ' Xinguara'],
                ['id_city' => 4987, 'id_state' => 14, 'name' => ' Xinguarinha'],
                ['id_city' => 4988, 'id_state' => 15, 'name' => ' Água Branca'],
                ['id_city' => 4989, 'id_state' => 15, 'name' => ' Aguiar'],
                ['id_city' => 4990, 'id_state' => 15, 'name' => ' Alagoa Grande'],
                ['id_city' => 4991, 'id_state' => 15, 'name' => ' Alagoa Nova'],
                ['id_city' => 4992, 'id_state' => 15, 'name' => ' Alagoinha'],
                ['id_city' => 4993, 'id_state' => 15, 'name' => ' Alcantil'],
                ['id_city' => 4994, 'id_state' => 15, 'name' => ' Algodão de Jandaíra'],
                ['id_city' => 4995, 'id_state' => 15, 'name' => ' Alhandra'],
                ['id_city' => 4996, 'id_state' => 15, 'name' => ' Amparo'],
                ['id_city' => 4997, 'id_state' => 15, 'name' => ' Aparecida'],
                ['id_city' => 4998, 'id_state' => 15, 'name' => ' Araçagi'],
                ['id_city' => 4999, 'id_state' => 15, 'name' => ' Arara'],
                ['id_city' => 5000, 'id_state' => 15, 'name' => ' Araruna'],
                ['id_city' => 5001, 'id_state' => 15, 'name' => ' Areia'],
                ['id_city' => 5002, 'id_state' => 15, 'name' => ' Areia de Baraúnas'],
                ['id_city' => 5003, 'id_state' => 15, 'name' => ' Areial'],
                ['id_city' => 5004, 'id_state' => 15, 'name' => ' Areias'],
                ['id_city' => 5005, 'id_state' => 15, 'name' => ' Aroeiras'],
                ['id_city' => 5006, 'id_state' => 15, 'name' => ' Riachão do Bacamarte'],
                ['id_city' => 5007, 'id_state' => 15, 'name' => ' Assunção'],
                ['id_city' => 5008, 'id_state' => 15, 'name' => ' Baía da Traição'],
                ['id_city' => 5009, 'id_state' => 15, 'name' => ' Balanços'],
                ['id_city' => 5010, 'id_state' => 15, 'name' => ' Bananeiras'],
                ['id_city' => 5011, 'id_state' => 15, 'name' => ' Baraúna'],
                ['id_city' => 5012, 'id_state' => 15, 'name' => ' Barra de Santa Rosa'],
                ['id_city' => 5013, 'id_state' => 15, 'name' => ' Barra de Santana'],
                ['id_city' => 5014, 'id_state' => 15, 'name' => ' Barra de São Miguel'],
                ['id_city' => 5015, 'id_state' => 15, 'name' => ' Barra do Camaratuba'],
                ['id_city' => 5016, 'id_state' => 15, 'name' => ' Bayeux'],
                ['id_city' => 5017, 'id_state' => 15, 'name' => ' Belém'],
                ['id_city' => 5018, 'id_state' => 15, 'name' => ' Belém do Brejo do Cruz'],
                ['id_city' => 5019, 'id_state' => 15, 'name' => ' Bernardino Batista'],
                ['id_city' => 5020, 'id_state' => 15, 'name' => ' Boa Ventura'],
                ['id_city' => 5021, 'id_state' => 15, 'name' => ' Boa Vista'],
                ['id_city' => 5022, 'id_state' => 15, 'name' => ' Bom Jesus'],
                ['id_city' => 5023, 'id_state' => 15, 'name' => ' Bom Sucesso'],
                ['id_city' => 5024, 'id_state' => 15, 'name' => ' Bonito de Santa Fé'],
                ['id_city' => 5025, 'id_state' => 15, 'name' => ' Boqueirão'],
                ['id_city' => 5026, 'id_state' => 15, 'name' => ' Borborema'],
                ['id_city' => 5027, 'id_state' => 15, 'name' => ' Brejo do Cruz'],
                ['id_city' => 5028, 'id_state' => 15, 'name' => ' Brejo dos Santos'],
                ['id_city' => 5029, 'id_state' => 15, 'name' => ' Caaporã'],
                ['id_city' => 5030, 'id_state' => 15, 'name' => ' Cabaceiras'],
                ['id_city' => 5031, 'id_state' => 15, 'name' => ' Cabedelo'],
                ['id_city' => 5032, 'id_state' => 15, 'name' => ' Cachoeira'],
                ['id_city' => 5033, 'id_state' => 15, 'name' => ' Cachoeira dos Índios'],
                ['id_city' => 5034, 'id_state' => 15, 'name' => ' Cachoeirinha'],
                ['id_city' => 5035, 'id_state' => 15, 'name' => ' Cacimba de Areia'],
                ['id_city' => 5036, 'id_state' => 15, 'name' => ' Cacimba de Dentro'],
                ['id_city' => 5037, 'id_state' => 15, 'name' => ' Cacimbas'],
                ['id_city' => 5038, 'id_state' => 15, 'name' => ' Caiçara'],
                ['id_city' => 5039, 'id_state' => 15, 'name' => ' Cajazeiras'],
                ['id_city' => 5040, 'id_state' => 15, 'name' => ' Cajazeirinhas'],
                ['id_city' => 5041, 'id_state' => 15, 'name' => ' Caldas Brandão'],
                ['id_city' => 5042, 'id_state' => 15, 'name' => ' Camalaú'],
                ['id_city' => 5043, 'id_state' => 15, 'name' => ' Campina Grande'],
                ['id_city' => 5044, 'id_state' => 15, 'name' => ' Campo Alegre'],
                ['id_city' => 5045, 'id_state' => 15, 'name' => ' Campo Grande'],
                ['id_city' => 5046, 'id_state' => 15, 'name' => ' Camurupim'],
                ['id_city' => 5047, 'id_state' => 15, 'name' => ' Capim'],
                ['id_city' => 5048, 'id_state' => 15, 'name' => ' Caraúbas'],
                ['id_city' => 5049, 'id_state' => 15, 'name' => ' Cardoso'],
                ['id_city' => 5050, 'id_state' => 15, 'name' => ' Carrapateira'],
                ['id_city' => 5051, 'id_state' => 15, 'name' => ' Casinha do Homem'],
                ['id_city' => 5052, 'id_state' => 15, 'name' => ' Casserengue'],
                ['id_city' => 5053, 'id_state' => 15, 'name' => ' Catingueira'],
                ['id_city' => 5054, 'id_state' => 15, 'name' => ' Catolé'],
                ['id_city' => 5055, 'id_state' => 15, 'name' => ' Catolé do Rocha'],
                ['id_city' => 5056, 'id_state' => 15, 'name' => ' Caturité'],
                ['id_city' => 5057, 'id_state' => 15, 'name' => ' Cepilho'],
                ['id_city' => 5058, 'id_state' => 15, 'name' => ' Conceição'],
                ['id_city' => 5059, 'id_state' => 15, 'name' => ' Condado'],
                ['id_city' => 5060, 'id_state' => 15, 'name' => ' Conde'],
                ['id_city' => 5061, 'id_state' => 15, 'name' => ' Congo'],
                ['id_city' => 5062, 'id_state' => 15, 'name' => ' Coremas'],
                ['id_city' => 5063, 'id_state' => 15, 'name' => ' Coronel Maia'],
                ['id_city' => 5064, 'id_state' => 15, 'name' => ' Coxixola'],
                ['id_city' => 5065, 'id_state' => 15, 'name' => ' Cruz do Espírito Santo'],
                ['id_city' => 5066, 'id_state' => 15, 'name' => ' Cubati'],
                ['id_city' => 5067, 'id_state' => 15, 'name' => ' Cuité'],
                ['id_city' => 5068, 'id_state' => 15, 'name' => ' Cuité de Mamanguape'],
                ['id_city' => 5069, 'id_state' => 15, 'name' => ' Cuitegi'],
                ['id_city' => 5070, 'id_state' => 15, 'name' => ' Cupissura'],
                ['id_city' => 5071, 'id_state' => 15, 'name' => ' Curral de Cima'],
                ['id_city' => 5072, 'id_state' => 15, 'name' => ' Curral Velho'],
                ['id_city' => 5073, 'id_state' => 15, 'name' => ' Damião'],
                ['id_city' => 5074, 'id_state' => 15, 'name' => ' Desterro'],
                ['id_city' => 5075, 'id_state' => 15, 'name' => ' Diamante'],
                ['id_city' => 5076, 'id_state' => 15, 'name' => ' Dona Inês'],
                ['id_city' => 5077, 'id_state' => 15, 'name' => ' Duas Estradas'],
                ['id_city' => 5078, 'id_state' => 15, 'name' => ' Emas'],
                ['id_city' => 5079, 'id_state' => 15, 'name' => ' Engenheiro Ávidos'],
                ['id_city' => 5080, 'id_state' => 15, 'name' => ' Esperança'],
                ['id_city' => 5081, 'id_state' => 15, 'name' => ' Fagundes'],
                ['id_city' => 5082, 'id_state' => 15, 'name' => ' Fátima'],
                ['id_city' => 5083, 'id_state' => 15, 'name' => ' Fazenda Nova'],
                ['id_city' => 5084, 'id_state' => 15, 'name' => ' Forte Velho'],
                ['id_city' => 5085, 'id_state' => 15, 'name' => ' Frei Martinho'],
                ['id_city' => 5086, 'id_state' => 15, 'name' => ' Gado Bravo'],
                ['id_city' => 5087, 'id_state' => 15, 'name' => ' Galante'],
                ['id_city' => 5088, 'id_state' => 15, 'name' => ' Guarabira'],
                ['id_city' => 5089, 'id_state' => 15, 'name' => ' Guarita'],
                ['id_city' => 5090, 'id_state' => 15, 'name' => ' Gurinhém'],
                ['id_city' => 5091, 'id_state' => 15, 'name' => ' Gurjão'],
                ['id_city' => 5092, 'id_state' => 15, 'name' => ' Ibiara'],
                ['id_city' => 5093, 'id_state' => 15, 'name' => ' Igaracy'],
                ['id_city' => 5094, 'id_state' => 15, 'name' => ' Imaculada'],
                ['id_city' => 5095, 'id_state' => 15, 'name' => ' Ingá'],
                ['id_city' => 5096, 'id_state' => 15, 'name' => ' Itabaiana'],
                ['id_city' => 5097, 'id_state' => 15, 'name' => ' Itajubatiba'],
                ['id_city' => 5098, 'id_state' => 15, 'name' => ' Itaporanga'],
                ['id_city' => 5099, 'id_state' => 15, 'name' => ' Itapororoca'],
                ['id_city' => 5100, 'id_state' => 15, 'name' => ' Itatuba'],
                ['id_city' => 5101, 'id_state' => 15, 'name' => ' Jacaraú'],
                ['id_city' => 5102, 'id_state' => 15, 'name' => ' Jericó'],
                ['id_city' => 5103, 'id_state' => 15, 'name' => ' João Pessoa'],
                ['id_city' => 5104, 'id_state' => 15, 'name' => ' Juarez Távora'],
                ['id_city' => 5105, 'id_state' => 15, 'name' => ' Juazeirinho'],
                ['id_city' => 5106, 'id_state' => 15, 'name' => ' Junco do Seridó'],
                ['id_city' => 5107, 'id_state' => 15, 'name' => ' Juripiranga'],
                ['id_city' => 5108, 'id_state' => 15, 'name' => ' Juru'],
                ['id_city' => 5109, 'id_state' => 15, 'name' => ' Lagoa'],
                ['id_city' => 5110, 'id_state' => 15, 'name' => ' Lagoa de Dentro'],
                ['id_city' => 5111, 'id_state' => 15, 'name' => ' Lagoa Seca'],
                ['id_city' => 5112, 'id_state' => 15, 'name' => ' Lastro'],
                ['id_city' => 5113, 'id_state' => 15, 'name' => ' Lerolândia'],
                ['id_city' => 5114, 'id_state' => 15, 'name' => ' Livramento'],
                ['id_city' => 5115, 'id_state' => 15, 'name' => ' Logradouro'],
                ['id_city' => 5116, 'id_state' => 15, 'name' => ' Lucena'],
                ['id_city' => 5117, 'id_state' => 15, 'name' => ' Mãe D Água'],
                ['id_city' => 5118, 'id_state' => 15, 'name' => ' Maia'],
                ['id_city' => 5119, 'id_state' => 15, 'name' => ' Malta'],
                ['id_city' => 5120, 'id_state' => 15, 'name' => ' Mamanguape'],
                ['id_city' => 5121, 'id_state' => 15, 'name' => ' Manaíra'],
                ['id_city' => 5122, 'id_state' => 15, 'name' => ' Marcação'],
                ['id_city' => 5123, 'id_state' => 15, 'name' => ' Mari'],
                ['id_city' => 5124, 'id_state' => 15, 'name' => ' Marizópolis'],
                ['id_city' => 5125, 'id_state' => 15, 'name' => ' Massaranduba'],
                ['id_city' => 5126, 'id_state' => 15, 'name' => ' Mata Limpa'],
                ['id_city' => 5127, 'id_state' => 15, 'name' => ' Mata Virgem'],
                ['id_city' => 5128, 'id_state' => 15, 'name' => ' Mataraca'],
                ['id_city' => 5129, 'id_state' => 15, 'name' => ' Matinhas'],
                ['id_city' => 5130, 'id_state' => 15, 'name' => ' Mato Grosso'],
                ['id_city' => 5131, 'id_state' => 15, 'name' => ' Maturéia'],
                ['id_city' => 5132, 'id_state' => 15, 'name' => ' Melo'],
                ['id_city' => 5133, 'id_state' => 15, 'name' => ' Mogeiro'],
                ['id_city' => 5134, 'id_state' => 15, 'name' => ' Montadas'],
                ['id_city' => 5135, 'id_state' => 15, 'name' => ' Monte Horebe'],
                ['id_city' => 5136, 'id_state' => 15, 'name' => ' Monteiro'],
                ['id_city' => 5137, 'id_state' => 15, 'name' => ' Montevidéu'],
                ['id_city' => 5138, 'id_state' => 15, 'name' => ' Mulungu'],
                ['id_city' => 5139, 'id_state' => 15, 'name' => ' Muquém'],
                ['id_city' => 5140, 'id_state' => 15, 'name' => ' Natuba'],
                ['id_city' => 5141, 'id_state' => 15, 'name' => ' Nazaré'],
                ['id_city' => 5142, 'id_state' => 15, 'name' => ' Nazarezinho'],
                ['id_city' => 5143, 'id_state' => 15, 'name' => ' Nossa Senhora do Livramento'],
                ['id_city' => 5144, 'id_state' => 15, 'name' => ' Nova Floresta'],
                ['id_city' => 5145, 'id_state' => 15, 'name' => ' Nova Olinda'],
                ['id_city' => 5146, 'id_state' => 15, 'name' => ' Nova Palmeira'],
                ['id_city' => 5147, 'id_state' => 15, 'name' => ' Núcleo N 2'],
                ['id_city' => 5148, 'id_state' => 15, 'name' => ' Núcleo N 3'],
                ['id_city' => 5149, 'id_state' => 15, 'name' => ' Odilândia'],
                ['id_city' => 5150, 'id_state' => 15, 'name' => ' Olho D Água'],
                ['id_city' => 5151, 'id_state' => 15, 'name' => ' Olivedos'],
                ['id_city' => 5152, 'id_state' => 15, 'name' => ' Ouro Velho'],
                ['id_city' => 5153, 'id_state' => 15, 'name' => ' Parari'],
                ['id_city' => 5154, 'id_state' => 15, 'name' => ' Passagem'],
                ['id_city' => 5155, 'id_state' => 15, 'name' => ' Patos'],
                ['id_city' => 5156, 'id_state' => 15, 'name' => ' Paulista'],
                ['id_city' => 5157, 'id_state' => 15, 'name' => ' Pedra Branca'],
                ['id_city' => 5158, 'id_state' => 15, 'name' => ' Pedra Lavrada'],
                ['id_city' => 5159, 'id_state' => 15, 'name' => ' Pedras de Fogo'],
                ['id_city' => 5160, 'id_state' => 15, 'name' => ' Pedro Régis'],
                ['id_city' => 5161, 'id_state' => 15, 'name' => ' Pelo Sinal'],
                ['id_city' => 5162, 'id_state' => 15, 'name' => ' Pereiros'],
                ['id_city' => 5163, 'id_state' => 15, 'name' => ' Piancó'],
                ['id_city' => 5164, 'id_state' => 15, 'name' => ' Picuí'],
                ['id_city' => 5165, 'id_state' => 15, 'name' => ' Pilar'],
                ['id_city' => 5166, 'id_state' => 15, 'name' => ' Pilões'],
                ['id_city' => 5167, 'id_state' => 15, 'name' => ' Pilõezinhos'],
                ['id_city' => 5168, 'id_state' => 15, 'name' => ' Pindurão'],
                ['id_city' => 5169, 'id_state' => 15, 'name' => ' Pio X'],
                ['id_city' => 5170, 'id_state' => 15, 'name' => ' Pirauá'],
                ['id_city' => 5171, 'id_state' => 15, 'name' => ' Pirpirituba'],
                ['id_city' => 5172, 'id_state' => 15, 'name' => ' Pitanga de Estrada'],
                ['id_city' => 5173, 'id_state' => 15, 'name' => ' Pitimbu'],
                ['id_city' => 5174, 'id_state' => 15, 'name' => ' Pocinhos'],
                ['id_city' => 5175, 'id_state' => 15, 'name' => ' Poço Dantas'],
                ['id_city' => 5176, 'id_state' => 15, 'name' => ' Poço de José de Moura'],
                ['id_city' => 5177, 'id_state' => 15, 'name' => ' Pombal'],
                ['id_city' => 5178, 'id_state' => 15, 'name' => ' Porteirinha de Pedra'],
                ['id_city' => 5179, 'id_state' => 15, 'name' => ' Prata'],
                ['id_city' => 5180, 'id_state' => 15, 'name' => ' Princesa Isabel'],
                ['id_city' => 5181, 'id_state' => 15, 'name' => ' Puxinanã'],
                ['id_city' => 5182, 'id_state' => 15, 'name' => ' Queimadas'],
                ['id_city' => 5183, 'id_state' => 15, 'name' => ' Quixabá'],
                ['id_city' => 5184, 'id_state' => 15, 'name' => ' Quixadá'],
                ['id_city' => 5185, 'id_state' => 15, 'name' => ' Remígio'],
                ['id_city' => 5186, 'id_state' => 15, 'name' => ' Riachão'],
                ['id_city' => 5187, 'id_state' => 15, 'name' => ' Riachão do Poço'],
                ['id_city' => 5188, 'id_state' => 15, 'name' => ' Riacho de Santo Antônio'],
                ['id_city' => 5189, 'id_state' => 15, 'name' => ' Riacho dos Cavalos'],
                ['id_city' => 5190, 'id_state' => 15, 'name' => ' Ribeira'],
                ['id_city' => 5191, 'id_state' => 15, 'name' => ' Rio Tinto'],
                ['id_city' => 5192, 'id_state' => 15, 'name' => ' Rua Nova'],
                ['id_city' => 5193, 'id_state' => 15, 'name' => ' Salema'],
                ['id_city' => 5194, 'id_state' => 15, 'name' => ' Salgadinho'],
                ['id_city' => 5195, 'id_state' => 15, 'name' => ' Salgado de São Félix'],
                ['id_city' => 5196, 'id_state' => 15, 'name' => ' Santa Cecília'],
                ['id_city' => 5197, 'id_state' => 15, 'name' => ' Santa Cruz'],
                ['id_city' => 5198, 'id_state' => 15, 'name' => ' Santa Gertrudes'],
                ['id_city' => 5199, 'id_state' => 15, 'name' => ' Santa Helena'],
                ['id_city' => 5200, 'id_state' => 15, 'name' => ' Santa Inês'],
                ['id_city' => 5201, 'id_state' => 15, 'name' => ' Santa Luzia'],
                ['id_city' => 5202, 'id_state' => 15, 'name' => ' Santa Luzia do Cariri'],
                ['id_city' => 5203, 'id_state' => 15, 'name' => ' Santa Maria'],
                ['id_city' => 5204, 'id_state' => 15, 'name' => ' Santa Rita'],
                ['id_city' => 5205, 'id_state' => 15, 'name' => ' Santa Teresinha'],
                ['id_city' => 5206, 'id_state' => 15, 'name' => ' Santa Terezinha'],
                ['id_city' => 5207, 'id_state' => 15, 'name' => ' Santana de Mangueira'],
                ['id_city' => 5208, 'id_state' => 15, 'name' => ' Santana dos Garrotes'],
                ['id_city' => 5209, 'id_state' => 15, 'name' => ' Joca Claudino'],
                ['id_city' => 5210, 'id_state' => 15, 'name' => ' Santo André'],
                ['id_city' => 5211, 'id_state' => 15, 'name' => ' São Bento'],
                ['id_city' => 5212, 'id_state' => 15, 'name' => ' São Bentinho'],
                ['id_city' => 5213, 'id_state' => 15, 'name' => ' São Domingos de Pombal'],
                ['id_city' => 5214, 'id_state' => 15, 'name' => ' São Domingos do Cariri'],
                ['id_city' => 5215, 'id_state' => 15, 'name' => ' São Francisco'],
                ['id_city' => 5216, 'id_state' => 15, 'name' => ' São Gonçalo'],
                ['id_city' => 5217, 'id_state' => 15, 'name' => ' São João Bosco'],
                ['id_city' => 5218, 'id_state' => 15, 'name' => ' São João do Cariri'],
                ['id_city' => 5219, 'id_state' => 15, 'name' => ' São João do Rio do Peixe'],
                ['id_city' => 5220, 'id_state' => 15, 'name' => ' São João do Tigre'],
                ['id_city' => 5221, 'id_state' => 15, 'name' => ' São José da Lagoa Tapada'],
                ['id_city' => 5222, 'id_state' => 15, 'name' => ' São José da Mata'],
                ['id_city' => 5223, 'id_state' => 15, 'name' => ' São José de Caiana'],
                ['id_city' => 5224, 'id_state' => 15, 'name' => ' São José de Espinharas'],
                ['id_city' => 5225, 'id_state' => 15, 'name' => ' São José de Marimbas'],
                ['id_city' => 5226, 'id_state' => 15, 'name' => ' São José de Piranhas'],
                ['id_city' => 5227, 'id_state' => 15, 'name' => ' São José de Princesa'],
                ['id_city' => 5228, 'id_state' => 15, 'name' => ' São José do Bonfim'],
                ['id_city' => 5229, 'id_state' => 15, 'name' => ' São José do Brejo do Cruz'],
                ['id_city' => 5230, 'id_state' => 15, 'name' => ' São José do Sabugi'],
                ['id_city' => 5231, 'id_state' => 15, 'name' => ' São José dos Cordeiros'],
                ['id_city' => 5232, 'id_state' => 15, 'name' => ' São José dos Ramos'],
                ['id_city' => 5233, 'id_state' => 15, 'name' => ' São Mamede'],
                ['id_city' => 5234, 'id_state' => 15, 'name' => ' São Miguel de Taipu'],
                ['id_city' => 5235, 'id_state' => 15, 'name' => ' São Pedro'],
                ['id_city' => 5236, 'id_state' => 15, 'name' => ' São Sebastião de Lagoa de Roça'],
                ['id_city' => 5237, 'id_state' => 15, 'name' => ' São Sebastião do Umbuzeiro'],
                ['id_city' => 5238, 'id_state' => 15, 'name' => ' Sapé'],
                ['id_city' => 5239, 'id_state' => 15, 'name' => ' Seridó'],
                ['id_city' => 5240, 'id_state' => 15, 'name' => ' São Vicente do Seridó'],
                ['id_city' => 5241, 'id_state' => 15, 'name' => ' Serra Branca'],
                ['id_city' => 5242, 'id_state' => 15, 'name' => ' Serra da Raiz'],
                ['id_city' => 5243, 'id_state' => 15, 'name' => ' Serra Grande'],
                ['id_city' => 5244, 'id_state' => 15, 'name' => ' Serra Redonda'],
                ['id_city' => 5245, 'id_state' => 15, 'name' => ' Serraria'],
                ['id_city' => 5246, 'id_state' => 15, 'name' => ' Sertãozinho'],
                ['id_city' => 5247, 'id_state' => 15, 'name' => ' Sobrado'],
                ['id_city' => 5248, 'id_state' => 15, 'name' => ' Solânea'],
                ['id_city' => 5249, 'id_state' => 15, 'name' => ' Soledade'],
                ['id_city' => 5250, 'id_state' => 15, 'name' => ' Sossego'],
                ['id_city' => 5251, 'id_state' => 15, 'name' => ' Sousa'],
                ['id_city' => 5252, 'id_state' => 15, 'name' => ' Sucuru'],
                ['id_city' => 5253, 'id_state' => 15, 'name' => ' Sumé'],
                ['id_city' => 5254, 'id_state' => 15, 'name' => ' Tacima'],
                ['id_city' => 5255, 'id_state' => 15, 'name' => ' Tambauzinho'],
                ['id_city' => 5256, 'id_state' => 15, 'name' => ' Taperoá'],
                ['id_city' => 5257, 'id_state' => 15, 'name' => ' Tavares'],
                ['id_city' => 5258, 'id_state' => 15, 'name' => ' Teixeira'],
                ['id_city' => 5259, 'id_state' => 15, 'name' => ' Tenório'],
                ['id_city' => 5260, 'id_state' => 15, 'name' => ' Triunfo'],
                ['id_city' => 5261, 'id_state' => 15, 'name' => ' Uiraúna'],
                ['id_city' => 5262, 'id_state' => 15, 'name' => ' Umari'],
                ['id_city' => 5263, 'id_state' => 15, 'name' => ' Umbuzeiro'],
                ['id_city' => 5264, 'id_state' => 15, 'name' => ' Várzea'],
                ['id_city' => 5265, 'id_state' => 15, 'name' => ' Várzea Comprida'],
                ['id_city' => 5266, 'id_state' => 15, 'name' => ' Várzea Nova'],
                ['id_city' => 5267, 'id_state' => 15, 'name' => ' Vazante'],
                ['id_city' => 5268, 'id_state' => 15, 'name' => ' Vieirópolis'],
                ['id_city' => 5269, 'id_state' => 15, 'name' => ' Vista Serrana'],
                ['id_city' => 5270, 'id_state' => 15, 'name' => ' Zabelê'],
                ['id_city' => 5271, 'id_state' => 17, 'name' => ' Abreu e Lima'],
                ['id_city' => 5272, 'id_state' => 17, 'name' => ' Afogados da Ingazeira'],
                ['id_city' => 5273, 'id_state' => 17, 'name' => ' Afrânio'],
                ['id_city' => 5274, 'id_state' => 17, 'name' => ' Agrestina'],
                ['id_city' => 5275, 'id_state' => 17, 'name' => ' Água Fria'],
                ['id_city' => 5276, 'id_state' => 17, 'name' => ' Água Preta'],
                ['id_city' => 5277, 'id_state' => 17, 'name' => ' Águas Belas'],
                ['id_city' => 5278, 'id_state' => 17, 'name' => ' Airi'],
                ['id_city' => 5279, 'id_state' => 17, 'name' => ' Alagoinha'],
                ['id_city' => 5280, 'id_state' => 17, 'name' => ' Albuquerque Né'],
                ['id_city' => 5281, 'id_state' => 17, 'name' => ' Algodões'],
                ['id_city' => 5282, 'id_state' => 17, 'name' => ' Aliança'],
                ['id_city' => 5283, 'id_state' => 17, 'name' => ' Altinho'],
                ['id_city' => 5284, 'id_state' => 17, 'name' => ' Amaraji'],
                ['id_city' => 5285, 'id_state' => 17, 'name' => ' Ameixas'],
                ['id_city' => 5286, 'id_state' => 17, 'name' => ' Angelim'],
                ['id_city' => 5287, 'id_state' => 17, 'name' => ' Apoti'],
                ['id_city' => 5288, 'id_state' => 17, 'name' => ' Araçoiaba'],
                ['id_city' => 5289, 'id_state' => 17, 'name' => ' Araripina'],
                ['id_city' => 5290, 'id_state' => 17, 'name' => ' Arcoverde'],
                ['id_city' => 5291, 'id_state' => 17, 'name' => ' Aripibu'],
                ['id_city' => 5292, 'id_state' => 17, 'name' => ' Arizona'],
                ['id_city' => 5293, 'id_state' => 17, 'name' => ' Barra de Farias'],
                ['id_city' => 5294, 'id_state' => 17, 'name' => ' Barra de Guabiraba'],
                ['id_city' => 5295, 'id_state' => 17, 'name' => ' Barra de São Pedro'],
                ['id_city' => 5296, 'id_state' => 17, 'name' => ' Barra do Brejo'],
                ['id_city' => 5297, 'id_state' => 17, 'name' => ' Barra do Chata'],
                ['id_city' => 5298, 'id_state' => 17, 'name' => ' Barra do Jardim'],
                ['id_city' => 5299, 'id_state' => 17, 'name' => ' Barra do Riachão'],
                ['id_city' => 5300, 'id_state' => 17, 'name' => ' Barra do Sirinhaém'],
                ['id_city' => 5301, 'id_state' => 17, 'name' => ' Barreiros'],
                ['id_city' => 5302, 'id_state' => 17, 'name' => ' Batateira'],
                ['id_city' => 5303, 'id_state' => 17, 'name' => ' Belém de Maria'],
                ['id_city' => 5304, 'id_state' => 17, 'name' => ' Belém do São Francisco'],
                ['id_city' => 5305, 'id_state' => 17, 'name' => ' Belo Jardim'],
                ['id_city' => 5306, 'id_state' => 17, 'name' => ' Bengalas'],
                ['id_city' => 5307, 'id_state' => 17, 'name' => ' Bentivi'],
                ['id_city' => 5308, 'id_state' => 17, 'name' => ' Bernardo Vieira'],
                ['id_city' => 5309, 'id_state' => 17, 'name' => ' Betânia'],
                ['id_city' => 5310, 'id_state' => 17, 'name' => ' Bezerros'],
                ['id_city' => 5311, 'id_state' => 17, 'name' => ' Bizarra'],
                ['id_city' => 5312, 'id_state' => 17, 'name' => ' Boas Novas'],
                ['id_city' => 5313, 'id_state' => 17, 'name' => ' Bodocó'],
                ['id_city' => 5314, 'id_state' => 17, 'name' => ' Bom Conselho'],
                ['id_city' => 5315, 'id_state' => 17, 'name' => ' Bom Jardim'],
                ['id_city' => 5316, 'id_state' => 17, 'name' => ' Bom Nome'],
                ['id_city' => 5317, 'id_state' => 17, 'name' => ' Bonfim'],
                ['id_city' => 5318, 'id_state' => 17, 'name' => ' Bonito'],
                ['id_city' => 5319, 'id_state' => 17, 'name' => ' Brejão'],
                ['id_city' => 5320, 'id_state' => 17, 'name' => ' Brejinho'],
                ['id_city' => 5321, 'id_state' => 17, 'name' => ' Brejo da Madre de Deus'],
                ['id_city' => 5322, 'id_state' => 17, 'name' => ' Buenos Aires'],
                ['id_city' => 5323, 'id_state' => 17, 'name' => ' Buíque'],
                ['id_city' => 5324, 'id_state' => 17, 'name' => ' Cabanas'],
                ['id_city' => 5325, 'id_state' => 17, 'name' => ' Cabo de Santo Agostinho'],
                ['id_city' => 5326, 'id_state' => 17, 'name' => ' Cabrobó'],
                ['id_city' => 5327, 'id_state' => 17, 'name' => ' Cachoeira do Roberto'],
                ['id_city' => 5328, 'id_state' => 17, 'name' => ' Cachoeirinha'],
                ['id_city' => 5329, 'id_state' => 17, 'name' => ' Caetés'],
                ['id_city' => 5330, 'id_state' => 17, 'name' => ' Caiçarinha da Penha'],
                ['id_city' => 5331, 'id_state' => 17, 'name' => ' Calçado'],
                ['id_city' => 5332, 'id_state' => 17, 'name' => ' Caldeirões'],
                ['id_city' => 5333, 'id_state' => 17, 'name' => ' Calumbi'],
                ['id_city' => 5334, 'id_state' => 17, 'name' => ' Camaragibe'],
                ['id_city' => 5335, 'id_state' => 17, 'name' => ' Camela'],
                ['id_city' => 5336, 'id_state' => 17, 'name' => ' Camocim de São Félix'],
                ['id_city' => 5337, 'id_state' => 17, 'name' => ' Camutanga'],
                ['id_city' => 5338, 'id_state' => 17, 'name' => ' Canaã'],
                ['id_city' => 5339, 'id_state' => 17, 'name' => ' Canhotinho'],
                ['id_city' => 5340, 'id_state' => 17, 'name' => ' Capoeiras'],
                ['id_city' => 5341, 'id_state' => 17, 'name' => ' Caraíba'],
                ['id_city' => 5342, 'id_state' => 17, 'name' => ' Caraibeiras'],
                ['id_city' => 5343, 'id_state' => 17, 'name' => ' Carapotos'],
                ['id_city' => 5344, 'id_state' => 17, 'name' => ' Carice'],
                ['id_city' => 5345, 'id_state' => 17, 'name' => ' Carima'],
                ['id_city' => 5346, 'id_state' => 17, 'name' => ' Caririmirim'],
                ['id_city' => 5347, 'id_state' => 17, 'name' => ' Carnaíba'],
                ['id_city' => 5348, 'id_state' => 17, 'name' => ' Carnaubeira da Penha'],
                ['id_city' => 5349, 'id_state' => 17, 'name' => ' Carneiro'],
                ['id_city' => 5350, 'id_state' => 17, 'name' => ' Carpina'],
                ['id_city' => 5351, 'id_state' => 17, 'name' => ' Carqueja'],
                ['id_city' => 5352, 'id_state' => 17, 'name' => ' Caruaru'],
                ['id_city' => 5353, 'id_state' => 17, 'name' => ' Casinhas'],
                ['id_city' => 5354, 'id_state' => 17, 'name' => ' Catende'],
                ['id_city' => 5355, 'id_state' => 17, 'name' => ' Catimbaú'],
                ['id_city' => 5356, 'id_state' => 17, 'name' => ' Catolé'],
                ['id_city' => 5357, 'id_state' => 17, 'name' => ' Cedro'],
                ['id_city' => 5358, 'id_state' => 17, 'name' => ' Chã de Alegria'],
                ['id_city' => 5359, 'id_state' => 17, 'name' => ' Chã do Rocha'],
                ['id_city' => 5360, 'id_state' => 17, 'name' => ' Chã Grande'],
                ['id_city' => 5361, 'id_state' => 17, 'name' => ' Cimbres'],
                ['id_city' => 5362, 'id_state' => 17, 'name' => ' Clarana'],
                ['id_city' => 5363, 'id_state' => 17, 'name' => ' Cocau'],
                ['id_city' => 5364, 'id_state' => 17, 'name' => ' Conceição das Crioulas'],
                ['id_city' => 5365, 'id_state' => 17, 'name' => ' Condado'],
                ['id_city' => 5366, 'id_state' => 17, 'name' => ' Correntes'],
                ['id_city' => 5367, 'id_state' => 17, 'name' => ' Cortês'],
                ['id_city' => 5368, 'id_state' => 17, 'name' => ' Couro D Antas'],
                ['id_city' => 5369, 'id_state' => 17, 'name' => ' Cristália'],
                ['id_city' => 5370, 'id_state' => 17, 'name' => ' Cruanji'],
                ['id_city' => 5371, 'id_state' => 17, 'name' => ' Cruzes'],
                ['id_city' => 5372, 'id_state' => 17, 'name' => ' Cuiambuca'],
                ['id_city' => 5373, 'id_state' => 17, 'name' => ' Cumaru'],
                ['id_city' => 5374, 'id_state' => 17, 'name' => ' Cupira'],
                ['id_city' => 5375, 'id_state' => 17, 'name' => ' Curral Queimado'],
                ['id_city' => 5376, 'id_state' => 17, 'name' => ' Custódia'],
                ['id_city' => 5377, 'id_state' => 17, 'name' => ' Dois Leões'],
                ['id_city' => 5378, 'id_state' => 17, 'name' => ' Dormentes'],
                ['id_city' => 5379, 'id_state' => 17, 'name' => ' Entroncamento'],
                ['id_city' => 5380, 'id_state' => 17, 'name' => ' Escada'],
                ['id_city' => 5381, 'id_state' => 17, 'name' => ' Espírito Santo'],
                ['id_city' => 5382, 'id_state' => 17, 'name' => ' Exu'],
                ['id_city' => 5383, 'id_state' => 17, 'name' => ' Fazenda Nova'],
                ['id_city' => 5384, 'id_state' => 17, 'name' => ' Feira Nova'],
                ['id_city' => 5385, 'id_state' => 17, 'name' => ' Feitoria'],
                ['id_city' => 5386, 'id_state' => 17, 'name' => ' Fernando de Noronha'],
                ['id_city' => 5387, 'id_state' => 17, 'name' => ' Ferreiros'],
                ['id_city' => 5388, 'id_state' => 17, 'name' => ' Flores'],
                ['id_city' => 5389, 'id_state' => 17, 'name' => ' Floresta'],
                ['id_city' => 5390, 'id_state' => 17, 'name' => ' Frei Miguelinho'],
                ['id_city' => 5391, 'id_state' => 17, 'name' => ' Frexeiras'],
                ['id_city' => 5392, 'id_state' => 17, 'name' => ' Gameleira'],
                ['id_city' => 5393, 'id_state' => 17, 'name' => ' Garanhuns'],
                ['id_city' => 5394, 'id_state' => 17, 'name' => ' Glória do Goitá'],
                ['id_city' => 5395, 'id_state' => 17, 'name' => ' Goiana'],
                ['id_city' => 5396, 'id_state' => 17, 'name' => ' Gonçalves Ferreira'],
                ['id_city' => 5397, 'id_state' => 17, 'name' => ' Granito'],
                ['id_city' => 5398, 'id_state' => 17, 'name' => ' Gravatá'],
                ['id_city' => 5399, 'id_state' => 17, 'name' => ' Gravatá do Ibiapina'],
                ['id_city' => 5400, 'id_state' => 17, 'name' => ' Grotão'],
                ['id_city' => 5401, 'id_state' => 17, 'name' => ' Guanumbi'],
                ['id_city' => 5402, 'id_state' => 17, 'name' => ' Henrique Dias'],
                ['id_city' => 5403, 'id_state' => 17, 'name' => ' Iateca'],
                ['id_city' => 5404, 'id_state' => 17, 'name' => ' Iati'],
                ['id_city' => 5405, 'id_state' => 17, 'name' => ' Ibimirim'],
                ['id_city' => 5406, 'id_state' => 17, 'name' => ' Ibirajuba'],
                ['id_city' => 5407, 'id_state' => 17, 'name' => ' Ibiranga'],
                ['id_city' => 5408, 'id_state' => 17, 'name' => ' Ibiratinga'],
                ['id_city' => 5409, 'id_state' => 17, 'name' => ' Ibitiranga'],
                ['id_city' => 5410, 'id_state' => 17, 'name' => ' Ibó'],
                ['id_city' => 5411, 'id_state' => 17, 'name' => ' Icaiçara'],
                ['id_city' => 5412, 'id_state' => 17, 'name' => ' Igapó'],
                ['id_city' => 5413, 'id_state' => 17, 'name' => ' Igarapeassu'],
                ['id_city' => 5414, 'id_state' => 17, 'name' => ' Igarapeba'],
                ['id_city' => 5415, 'id_state' => 17, 'name' => ' Igarassu'],
                ['id_city' => 5416, 'id_state' => 17, 'name' => ' Iguaraci'],
                ['id_city' => 5417, 'id_state' => 17, 'name' => ' Inajá'],
                ['id_city' => 5418, 'id_state' => 17, 'name' => ' Ingazeira'],
                ['id_city' => 5419, 'id_state' => 17, 'name' => ' Ipojuca'],
                ['id_city' => 5420, 'id_state' => 17, 'name' => ' Ipubi'],
                ['id_city' => 5421, 'id_state' => 17, 'name' => ' Ipuera'],
                ['id_city' => 5422, 'id_state' => 17, 'name' => ' Iraguaçu'],
                ['id_city' => 5423, 'id_state' => 17, 'name' => ' Irajaí'],
                ['id_city' => 5424, 'id_state' => 17, 'name' => ' Iratama'],
                ['id_city' => 5425, 'id_state' => 17, 'name' => ' Itacuruba'],
                ['id_city' => 5426, 'id_state' => 17, 'name' => ' Itaíba'],
                ['id_city' => 5427, 'id_state' => 17, 'name' => ' Ilha de Itamaracá'],
                ['id_city' => 5428, 'id_state' => 17, 'name' => ' Itambé'],
                ['id_city' => 5429, 'id_state' => 17, 'name' => ' Itapetim'],
                ['id_city' => 5430, 'id_state' => 17, 'name' => ' Itapissuma'],
                ['id_city' => 5431, 'id_state' => 17, 'name' => ' Itaquitinga'],
                ['id_city' => 5432, 'id_state' => 17, 'name' => ' Ituguaçu'],
                ['id_city' => 5433, 'id_state' => 17, 'name' => ' Iuiteporã'],
                ['id_city' => 5434, 'id_state' => 17, 'name' => ' Jabitaca'],
                ['id_city' => 5435, 'id_state' => 17, 'name' => ' Jaboatão dos Guararapes']
            ]);
        }
    }