<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities14 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 8640, 'id_state' => 24, 'name' => ' São João Batista'],
                ['id_city' => 8641, 'id_state' => 24, 'name' => ' São João do Itaperiú'],
                ['id_city' => 8642, 'id_state' => 24, 'name' => ' São João do Oeste'],
                ['id_city' => 8643, 'id_state' => 24, 'name' => ' São João do Rio Vermelho'],
                ['id_city' => 8644, 'id_state' => 24, 'name' => ' São João do Sul'],
                ['id_city' => 8645, 'id_state' => 24, 'name' => ' São Joaquim'],
                ['id_city' => 8646, 'id_state' => 24, 'name' => ' São José'],
                ['id_city' => 8647, 'id_state' => 24, 'name' => ' São José do Cedro'],
                ['id_city' => 8648, 'id_state' => 24, 'name' => ' São José do Cerrito'],
                ['id_city' => 8649, 'id_state' => 24, 'name' => ' São José do Laranjal'],
                ['id_city' => 8650, 'id_state' => 24, 'name' => ' São Leonardo'],
                ['id_city' => 8651, 'id_state' => 24, 'name' => ' São Lourenço do Oeste'],
                ['id_city' => 8652, 'id_state' => 24, 'name' => ' São Ludgero'],
                ['id_city' => 8653, 'id_state' => 24, 'name' => ' São Martinho'],
                ['id_city' => 8654, 'id_state' => 24, 'name' => ' São Miguel do Oeste'],
                ['id_city' => 8655, 'id_state' => 24, 'name' => ' São Miguel da Boa Vista'],
                ['id_city' => 8656, 'id_state' => 24, 'name' => ' São Miguel da Serra'],
                ['id_city' => 8657, 'id_state' => 24, 'name' => ' São Pedro de Alcântara'],
                ['id_city' => 8658, 'id_state' => 24, 'name' => ' São Pedro Tobias'],
                ['id_city' => 8659, 'id_state' => 24, 'name' => ' São Roque'],
                ['id_city' => 8660, 'id_state' => 24, 'name' => ' São Sebastião do Arvoredo'],
                ['id_city' => 8661, 'id_state' => 24, 'name' => ' São Sebastião do Sul'],
                ['id_city' => 8662, 'id_state' => 24, 'name' => ' Sapiranga'],
                ['id_city' => 8663, 'id_state' => 24, 'name' => ' Saudades'],
                ['id_city' => 8664, 'id_state' => 24, 'name' => ' Schroeder'],
                ['id_city' => 8665, 'id_state' => 24, 'name' => ' Seara'],
                ['id_city' => 8666, 'id_state' => 24, 'name' => ' Sede Oldemburg'],
                ['id_city' => 8667, 'id_state' => 24, 'name' => ' Serra Alta'],
                ['id_city' => 8668, 'id_state' => 24, 'name' => ' Siderópolis'],
                ['id_city' => 8669, 'id_state' => 24, 'name' => ' Sombrio'],
                ['id_city' => 8670, 'id_state' => 24, 'name' => ' Sorocaba do Sul'],
                ['id_city' => 8671, 'id_state' => 24, 'name' => ' Sul Brasil'],
                ['id_city' => 8672, 'id_state' => 24, 'name' => ' Taió'],
                ['id_city' => 8673, 'id_state' => 24, 'name' => ' Tangará'],
                ['id_city' => 8674, 'id_state' => 24, 'name' => ' Taquara Verde'],
                ['id_city' => 8675, 'id_state' => 24, 'name' => ' Taquaras'],
                ['id_city' => 8676, 'id_state' => 24, 'name' => ' Tigipió'],
                ['id_city' => 8677, 'id_state' => 24, 'name' => ' Tigrinhos'],
                ['id_city' => 8678, 'id_state' => 24, 'name' => ' Tijucas'],
                ['id_city' => 8679, 'id_state' => 24, 'name' => ' Timbé do Sul'],
                ['id_city' => 8680, 'id_state' => 24, 'name' => ' Timbó'],
                ['id_city' => 8681, 'id_state' => 24, 'name' => ' Timbó Grande'],
                ['id_city' => 8682, 'id_state' => 24, 'name' => ' Três Barras'],
                ['id_city' => 8683, 'id_state' => 24, 'name' => ' Treviso'],
                ['id_city' => 8684, 'id_state' => 24, 'name' => ' Treze de Maio'],
                ['id_city' => 8685, 'id_state' => 24, 'name' => ' Treze Tílias'],
                ['id_city' => 8686, 'id_state' => 24, 'name' => ' Trombudo Central'],
                ['id_city' => 8687, 'id_state' => 24, 'name' => ' Tubarão'],
                ['id_city' => 8688, 'id_state' => 24, 'name' => ' Tunápolis'],
                ['id_city' => 8689, 'id_state' => 24, 'name' => ' Tupitinga'],
                ['id_city' => 8690, 'id_state' => 24, 'name' => ' Turvo'],
                ['id_city' => 8691, 'id_state' => 24, 'name' => ' União do Oeste'],
                ['id_city' => 8692, 'id_state' => 24, 'name' => ' Urubici'],
                ['id_city' => 8693, 'id_state' => 24, 'name' => ' Uruguai'],
                ['id_city' => 8694, 'id_state' => 24, 'name' => ' Urupema'],
                ['id_city' => 8695, 'id_state' => 24, 'name' => ' Urussanga'],
                ['id_city' => 8696, 'id_state' => 24, 'name' => ' Vargeão'],
                ['id_city' => 8697, 'id_state' => 24, 'name' => ' Vargem'],
                ['id_city' => 8698, 'id_state' => 24, 'name' => ' Vargem Bonita'],
                ['id_city' => 8699, 'id_state' => 24, 'name' => ' Vargem do Cedro'],
                ['id_city' => 8700, 'id_state' => 24, 'name' => ' Vidal Ramos'],
                ['id_city' => 8701, 'id_state' => 24, 'name' => ' Videira'],
                ['id_city' => 8702, 'id_state' => 24, 'name' => ' Vila Conceição'],
                ['id_city' => 8703, 'id_state' => 24, 'name' => ' Vila de Volta Grande'],
                ['id_city' => 8704, 'id_state' => 24, 'name' => ' Vila Milani'],
                ['id_city' => 8705, 'id_state' => 24, 'name' => ' Vila Nova'],
                ['id_city' => 8706, 'id_state' => 24, 'name' => ' Vítor Meireles'],
                ['id_city' => 8707, 'id_state' => 24, 'name' => ' Witmarsum'],
                ['id_city' => 8708, 'id_state' => 24, 'name' => ' Xanxerê'],
                ['id_city' => 8709, 'id_state' => 24, 'name' => ' Xavantina'],
                ['id_city' => 8710, 'id_state' => 24, 'name' => ' Xaxim'],
                ['id_city' => 8711, 'id_state' => 24, 'name' => ' Zortéa'],
                ['id_city' => 8712, 'id_state' => 26, 'name' => ' Altos Verdes'],
                ['id_city' => 8713, 'id_state' => 26, 'name' => ' Amparo de São Francisco'],
                ['id_city' => 8714, 'id_state' => 26, 'name' => ' Aquidabã'],
                ['id_city' => 8715, 'id_state' => 26, 'name' => ' Aracaju'],
                ['id_city' => 8716, 'id_state' => 26, 'name' => ' Arauá'],
                ['id_city' => 8717, 'id_state' => 26, 'name' => ' Areia Branca'],
                ['id_city' => 8718, 'id_state' => 26, 'name' => ' Barra dos Coqueiros'],
                ['id_city' => 8719, 'id_state' => 26, 'name' => ' Barracas'],
                ['id_city' => 8720, 'id_state' => 26, 'name' => ' Boquim'],
                ['id_city' => 8721, 'id_state' => 26, 'name' => ' Brejo Grande'],
                ['id_city' => 8722, 'id_state' => 26, 'name' => ' Campo do Brito'],
                ['id_city' => 8723, 'id_state' => 26, 'name' => ' Canhoba'],
                ['id_city' => 8724, 'id_state' => 26, 'name' => ' Canindé de São Francisco'],
                ['id_city' => 8725, 'id_state' => 26, 'name' => ' Capela'],
                ['id_city' => 8726, 'id_state' => 26, 'name' => ' Carira'],
                ['id_city' => 8727, 'id_state' => 26, 'name' => ' Carmópolis'],
                ['id_city' => 8728, 'id_state' => 26, 'name' => ' Cedro de São João'],
                ['id_city' => 8729, 'id_state' => 26, 'name' => ' Cristinápolis'],
                ['id_city' => 8730, 'id_state' => 26, 'name' => ' Cumbe'],
                ['id_city' => 8731, 'id_state' => 26, 'name' => ' Divina Pastora'],
                ['id_city' => 8732, 'id_state' => 26, 'name' => ' Estância'],
                ['id_city' => 8733, 'id_state' => 26, 'name' => ' Feira Nova'],
                ['id_city' => 8734, 'id_state' => 26, 'name' => ' Frei Paulo'],
                ['id_city' => 8735, 'id_state' => 26, 'name' => ' Gararu'],
                ['id_city' => 8736, 'id_state' => 26, 'name' => ' General Maynard'],
                ['id_city' => 8737, 'id_state' => 26, 'name' => ' Graccho Cardoso'],
                ['id_city' => 8738, 'id_state' => 26, 'name' => ' Ilha das Flores'],
                ['id_city' => 8739, 'id_state' => 26, 'name' => ' Indiaroba'],
                ['id_city' => 8740, 'id_state' => 26, 'name' => ' Itabaiana'],
                ['id_city' => 8741, 'id_state' => 26, 'name' => ' Itabaianinha'],
                ['id_city' => 8742, 'id_state' => 26, 'name' => ' Itabi'],
                ['id_city' => 8743, 'id_state' => 26, 'name' => ' Itaporanga D Ajuda'],
                ['id_city' => 8744, 'id_state' => 26, 'name' => ' Japaratuba'],
                ['id_city' => 8745, 'id_state' => 26, 'name' => ' Japoatã'],
                ['id_city' => 8746, 'id_state' => 26, 'name' => ' Lagarto'],
                ['id_city' => 8747, 'id_state' => 26, 'name' => ' Lagoa Funda'],
                ['id_city' => 8748, 'id_state' => 26, 'name' => ' Laranjeiras'],
                ['id_city' => 8749, 'id_state' => 26, 'name' => ' Macambira'],
                ['id_city' => 8750, 'id_state' => 26, 'name' => ' Malhada dos Bois'],
                ['id_city' => 8751, 'id_state' => 26, 'name' => ' Malhador'],
                ['id_city' => 8752, 'id_state' => 26, 'name' => ' Maruim'],
                ['id_city' => 8753, 'id_state' => 26, 'name' => ' Miranda'],
                ['id_city' => 8754, 'id_state' => 26, 'name' => ' Moita Bonita'],
                ['id_city' => 8755, 'id_state' => 26, 'name' => ' Monte Alegre de Sergipe'],
                ['id_city' => 8756, 'id_state' => 26, 'name' => ' Mosqueiro'],
                ['id_city' => 8757, 'id_state' => 26, 'name' => ' Muribeca'],
                ['id_city' => 8758, 'id_state' => 26, 'name' => ' Neópolis'],
                ['id_city' => 8759, 'id_state' => 26, 'name' => ' Nossa Senhora Aparecida'],
                ['id_city' => 8760, 'id_state' => 26, 'name' => ' Nossa Senhora da Glória'],
                ['id_city' => 8761, 'id_state' => 26, 'name' => ' Nossa Senhora das Dores'],
                ['id_city' => 8762, 'id_state' => 26, 'name' => ' Nossa Senhora de Lourdes'],
                ['id_city' => 8763, 'id_state' => 26, 'name' => ' Nossa Senhora do Socorro'],
                ['id_city' => 8764, 'id_state' => 26, 'name' => ' Pacatuba'],
                ['id_city' => 8765, 'id_state' => 26, 'name' => ' Palmares'],
                ['id_city' => 8766, 'id_state' => 26, 'name' => ' Pedra Mole'],
                ['id_city' => 8767, 'id_state' => 26, 'name' => ' Pedras'],
                ['id_city' => 8768, 'id_state' => 26, 'name' => ' Pedrinhas'],
                ['id_city' => 8769, 'id_state' => 26, 'name' => ' Pinhão'],
                ['id_city' => 8770, 'id_state' => 26, 'name' => ' Pirambu'],
                ['id_city' => 8771, 'id_state' => 26, 'name' => ' Poço Redondo'],
                ['id_city' => 8772, 'id_state' => 26, 'name' => ' Poço Verde'],
                ['id_city' => 8773, 'id_state' => 26, 'name' => ' Porto da Folha'],
                ['id_city' => 8774, 'id_state' => 26, 'name' => ' Propriá'],
                ['id_city' => 8775, 'id_state' => 26, 'name' => ' Riachão do Dantas'],
                ['id_city' => 8776, 'id_state' => 26, 'name' => ' Riachuelo'],
                ['id_city' => 8777, 'id_state' => 26, 'name' => ' Ribeirópolis'],
                ['id_city' => 8778, 'id_state' => 26, 'name' => ' Rosário do Catete'],
                ['id_city' => 8779, 'id_state' => 26, 'name' => ' Salgado'],
                ['id_city' => 8780, 'id_state' => 26, 'name' => ' Samambaia'],
                ['id_city' => 8781, 'id_state' => 26, 'name' => ' Santa Luzia do Itanhy'],
                ['id_city' => 8782, 'id_state' => 26, 'name' => ' Santa Rosa de Lima'],
                ['id_city' => 8783, 'id_state' => 26, 'name' => ' Santana do São Francisco'],
                ['id_city' => 8784, 'id_state' => 26, 'name' => ' Santo Amaro das Brotas'],
                ['id_city' => 8785, 'id_state' => 26, 'name' => ' São Cristóvão'],
                ['id_city' => 8786, 'id_state' => 26, 'name' => ' São Domingos'],
                ['id_city' => 8787, 'id_state' => 26, 'name' => ' São Francisco'],
                ['id_city' => 8788, 'id_state' => 26, 'name' => ' São José'],
                ['id_city' => 8789, 'id_state' => 26, 'name' => ' São Mateus da Palestina'],
                ['id_city' => 8790, 'id_state' => 26, 'name' => ' São Miguel do Aleixo'],
                ['id_city' => 8791, 'id_state' => 26, 'name' => ' Simão Dias'],
                ['id_city' => 8792, 'id_state' => 26, 'name' => ' Siriri'],
                ['id_city' => 8793, 'id_state' => 26, 'name' => ' Telha'],
                ['id_city' => 8794, 'id_state' => 26, 'name' => ' Tobias Barreto'],
                ['id_city' => 8795, 'id_state' => 26, 'name' => ' Tomar do Geru'],
                ['id_city' => 8796, 'id_state' => 26, 'name' => ' Umbaúba'],
                ['id_city' => 8797, 'id_state' => 25, 'name' => ' Adamantina'],
                ['id_city' => 8798, 'id_state' => 25, 'name' => ' Adolfo'],
                ['id_city' => 8799, 'id_state' => 25, 'name' => ' Agisse'],
                ['id_city' => 8800, 'id_state' => 25, 'name' => ' Água Vermelha'],
                ['id_city' => 8801, 'id_state' => 25, 'name' => ' Aguaí'],
                ['id_city' => 8802, 'id_state' => 25, 'name' => ' Águas da Prata'],
                ['id_city' => 8803, 'id_state' => 25, 'name' => ' Águas de Lindóia'],
                ['id_city' => 8804, 'id_state' => 25, 'name' => ' Águas de Santa Bárbara'],
                ['id_city' => 8805, 'id_state' => 25, 'name' => ' Águas de São Pedro'],
                ['id_city' => 8806, 'id_state' => 25, 'name' => ' Agudos'],
                ['id_city' => 8807, 'id_state' => 25, 'name' => ' Agulha'],
                ['id_city' => 8808, 'id_state' => 25, 'name' => ' Ajapi'],
                ['id_city' => 8809, 'id_state' => 25, 'name' => ' Alambari'],
                ['id_city' => 8810, 'id_state' => 25, 'name' => ' Alberto Moreira'],
                ['id_city' => 8811, 'id_state' => 25, 'name' => ' Aldeia'],
                ['id_city' => 8812, 'id_state' => 25, 'name' => ' Aldeia de Carapicuíba'],
                ['id_city' => 8813, 'id_state' => 25, 'name' => ' Alfredo Guedes'],
                ['id_city' => 8814, 'id_state' => 25, 'name' => ' Alfredo Marcondes'],
                ['id_city' => 8815, 'id_state' => 25, 'name' => ' Altair'],
                ['id_city' => 8816, 'id_state' => 25, 'name' => ' Altinópolis'],
                ['id_city' => 8817, 'id_state' => 25, 'name' => ' Alto Alegre'],
                ['id_city' => 8818, 'id_state' => 25, 'name' => ' Alto Porã'],
                ['id_city' => 8819, 'id_state' => 25, 'name' => ' Alumínio'],
                ['id_city' => 8820, 'id_state' => 25, 'name' => ' Álvares Florence'],
                ['id_city' => 8821, 'id_state' => 25, 'name' => ' Álvares Machado'],
                ['id_city' => 8822, 'id_state' => 25, 'name' => ' Álvaro de Carvalho'],
                ['id_city' => 8823, 'id_state' => 25, 'name' => ' Alvinlândia'],
                ['id_city' => 8824, 'id_state' => 25, 'name' => ' Amadeu Amaral'],
                ['id_city' => 8825, 'id_state' => 25, 'name' => ' Amandaba'],
                ['id_city' => 8826, 'id_state' => 25, 'name' => ' Ameliópolis'],
                ['id_city' => 8827, 'id_state' => 25, 'name' => ' Americana'],
                ['id_city' => 8828, 'id_state' => 25, 'name' => ' Américo Brasiliense'],
                ['id_city' => 8829, 'id_state' => 25, 'name' => ' Américo de Campos'],
                ['id_city' => 8830, 'id_state' => 25, 'name' => ' Amparo'],
                ['id_city' => 8831, 'id_state' => 25, 'name' => ' Ana Dias'],
                ['id_city' => 8832, 'id_state' => 25, 'name' => ' Analândia'],
                ['id_city' => 8833, 'id_state' => 25, 'name' => ' Anápolis'],
                ['id_city' => 8834, 'id_state' => 25, 'name' => ' Andes'],
                ['id_city' => 8835, 'id_state' => 25, 'name' => ' Andradina'],
                ['id_city' => 8836, 'id_state' => 25, 'name' => ' Angatuba'],
                ['id_city' => 8837, 'id_state' => 25, 'name' => ' Anhembi'],
                ['id_city' => 8838, 'id_state' => 25, 'name' => ' Anhumas'],
                ['id_city' => 8839, 'id_state' => 25, 'name' => ' Aparecida'],
                ['id_city' => 8840, 'id_state' => 25, 'name' => ' Aparecida D Oeste'],
                ['id_city' => 8841, 'id_state' => 25, 'name' => ' Aparecida de Monte Alto'],
                ['id_city' => 8842, 'id_state' => 25, 'name' => ' Aparecida de São Manuel'],
                ['id_city' => 8843, 'id_state' => 25, 'name' => ' Aparecida do Bonito'],
                ['id_city' => 8844, 'id_state' => 25, 'name' => ' Apiaí'],
                ['id_city' => 8845, 'id_state' => 25, 'name' => ' Apiaí-Mirim'],
                ['id_city' => 8846, 'id_state' => 25, 'name' => ' Arabela'],
                ['id_city' => 8847, 'id_state' => 25, 'name' => ' Aracaçu'],
                ['id_city' => 8848, 'id_state' => 25, 'name' => ' Araçaíba'],
                ['id_city' => 8849, 'id_state' => 25, 'name' => ' Araçariguama'],
                ['id_city' => 8850, 'id_state' => 25, 'name' => ' Araçatuba'],
                ['id_city' => 8851, 'id_state' => 25, 'name' => ' Araçoiaba da Serra'],
                ['id_city' => 8852, 'id_state' => 25, 'name' => ' Aramina'],
                ['id_city' => 8853, 'id_state' => 25, 'name' => ' Arandu'],
                ['id_city' => 8854, 'id_state' => 25, 'name' => ' Arapeí'],
                ['id_city' => 8855, 'id_state' => 25, 'name' => ' Araraquara'],
                ['id_city' => 8856, 'id_state' => 25, 'name' => ' Araras'],
                ['id_city' => 8857, 'id_state' => 25, 'name' => ' Araxás'],
                ['id_city' => 8858, 'id_state' => 25, 'name' => ' Arcadas'],
                ['id_city' => 8859, 'id_state' => 25, 'name' => ' Arco-Íris'],
                ['id_city' => 8860, 'id_state' => 25, 'name' => ' Arealva'],
                ['id_city' => 8861, 'id_state' => 25, 'name' => ' Areias'],
                ['id_city' => 8862, 'id_state' => 25, 'name' => ' Areiópolis'],
                ['id_city' => 8863, 'id_state' => 25, 'name' => ' Ariranha'],
                ['id_city' => 8864, 'id_state' => 25, 'name' => ' Ariri'],
                ['id_city' => 8865, 'id_state' => 25, 'name' => ' Ártemis'],
                ['id_city' => 8866, 'id_state' => 25, 'name' => ' Artur Nogueira'],
                ['id_city' => 8867, 'id_state' => 25, 'name' => ' Arujá'],
                ['id_city' => 8868, 'id_state' => 25, 'name' => ' Aspásia'],
                ['id_city' => 8869, 'id_state' => 25, 'name' => ' Assis'],
                ['id_city' => 8870, 'id_state' => 25, 'name' => ' Assistência'],
                ['id_city' => 8871, 'id_state' => 25, 'name' => ' Atibaia'],
                ['id_city' => 8872, 'id_state' => 25, 'name' => ' Atlântida'],
                ['id_city' => 8873, 'id_state' => 25, 'name' => ' Auriflama'],
                ['id_city' => 8874, 'id_state' => 25, 'name' => ' Avaí'],
                ['id_city' => 8875, 'id_state' => 25, 'name' => ' Avanhandava'],
                ['id_city' => 8876, 'id_state' => 25, 'name' => ' Avaré'],
                ['id_city' => 8877, 'id_state' => 25, 'name' => ' Avencas'],
                ['id_city' => 8878, 'id_state' => 25, 'name' => ' Bacaetava'],
                ['id_city' => 8879, 'id_state' => 25, 'name' => ' Bacuriti'],
                ['id_city' => 8880, 'id_state' => 25, 'name' => ' Bady Bassitt'],
                ['id_city' => 8881, 'id_state' => 25, 'name' => ' Baguaçu'],
                ['id_city' => 8882, 'id_state' => 25, 'name' => ' Bairro Alto'],
                ['id_city' => 8883, 'id_state' => 25, 'name' => ' Balbinos'],
                ['id_city' => 8884, 'id_state' => 25, 'name' => ' Bálsamo'],
                ['id_city' => 8885, 'id_state' => 25, 'name' => ' Bananal'],
                ['id_city' => 8886, 'id_state' => 25, 'name' => ' Bandeirantes D Oeste'],
                ['id_city' => 8887, 'id_state' => 25, 'name' => ' Barão Ataliba Nogueira'],
                ['id_city' => 8888, 'id_state' => 25, 'name' => ' Barão de Antonina'],
                ['id_city' => 8889, 'id_state' => 25, 'name' => ' Barão de Geraldo'],
                ['id_city' => 8890, 'id_state' => 25, 'name' => ' Barbosa'],
                ['id_city' => 8891, 'id_state' => 25, 'name' => ' Bariri'],
                ['id_city' => 8892, 'id_state' => 25, 'name' => ' Barra Bonita'],
                ['id_city' => 8893, 'id_state' => 25, 'name' => ' Barra do Chapéu'],
                ['id_city' => 8894, 'id_state' => 25, 'name' => ' Barra do Turvo'],
                ['id_city' => 8895, 'id_state' => 25, 'name' => ' Barra Dourada'],
                ['id_city' => 8896, 'id_state' => 25, 'name' => ' Barrânia'],
                ['id_city' => 8897, 'id_state' => 25, 'name' => ' Barretos'],
                ['id_city' => 8898, 'id_state' => 25, 'name' => ' Barrinha'],
                ['id_city' => 8899, 'id_state' => 25, 'name' => ' Barueri'],
                ['id_city' => 8900, 'id_state' => 25, 'name' => ' Bastos'],
                ['id_city' => 8901, 'id_state' => 25, 'name' => ' Batatais'],
                ['id_city' => 8902, 'id_state' => 25, 'name' => ' Batatuba'],
                ['id_city' => 8903, 'id_state' => 25, 'name' => ' Batista Botelho'],
                ['id_city' => 8904, 'id_state' => 25, 'name' => ' Bauru'],
                ['id_city' => 8905, 'id_state' => 25, 'name' => ' Bebedouro'],
                ['id_city' => 8906, 'id_state' => 25, 'name' => ' Bela Floresta'],
                ['id_city' => 8907, 'id_state' => 25, 'name' => ' Bela Vista São-Carlense'],
                ['id_city' => 8908, 'id_state' => 25, 'name' => ' Bento de Abreu'],
                ['id_city' => 8909, 'id_state' => 25, 'name' => ' Bernardino de Campos'],
                ['id_city' => 8910, 'id_state' => 25, 'name' => ' Bertioga'],
                ['id_city' => 8911, 'id_state' => 25, 'name' => ' Bilac'],
                ['id_city' => 8912, 'id_state' => 25, 'name' => ' Birigüi'],
                ['id_city' => 8913, 'id_state' => 25, 'name' => ' Biritiba-Mirim'],
                ['id_city' => 8914, 'id_state' => 25, 'name' => ' Biritiba-Ussu'],
                ['id_city' => 8915, 'id_state' => 25, 'name' => ' Boa Esperança do Sul'],
                ['id_city' => 8916, 'id_state' => 25, 'name' => ' Boa Vista dos Andradas'],
                ['id_city' => 8917, 'id_state' => 25, 'name' => ' Boa Vista Paulista'],
                ['id_city' => 8918, 'id_state' => 25, 'name' => ' Bocaina'],
                ['id_city' => 8919, 'id_state' => 25, 'name' => ' Bofete'],
                ['id_city' => 8920, 'id_state' => 25, 'name' => ' Boituva'],
                ['id_city' => 8921, 'id_state' => 25, 'name' => ' Bom Fim do Bom Jesus'],
                ['id_city' => 8922, 'id_state' => 25, 'name' => ' Bom Jesus dos Perdões'],
                ['id_city' => 8923, 'id_state' => 25, 'name' => ' Bom Retiro da Esperança'],
                ['id_city' => 8924, 'id_state' => 25, 'name' => ' Bom Sucesso de Itararé'],
                ['id_city' => 8925, 'id_state' => 25, 'name' => ' Bonfim Paulista'],
                ['id_city' => 8926, 'id_state' => 25, 'name' => ' Borá'],
                ['id_city' => 8927, 'id_state' => 25, 'name' => ' Boracéia'],
                ['id_city' => 8928, 'id_state' => 25, 'name' => ' Borborema'],
                ['id_city' => 8929, 'id_state' => 25, 'name' => ' Borebi'],
                ['id_city' => 8930, 'id_state' => 25, 'name' => ' Botafogo'],
                ['id_city' => 8931, 'id_state' => 25, 'name' => ' Botelho'],
                ['id_city' => 8932, 'id_state' => 25, 'name' => ' Botucatu'],
                ['id_city' => 8933, 'id_state' => 25, 'name' => ' Botujuru'],
                ['id_city' => 8934, 'id_state' => 25, 'name' => ' Braço'],
                ['id_city' => 8935, 'id_state' => 25, 'name' => ' Bragança Paulista'],
                ['id_city' => 8936, 'id_state' => 25, 'name' => ' Brás Cubas'],
                ['id_city' => 8937, 'id_state' => 25, 'name' => ' Brasitânia'],
                ['id_city' => 8938, 'id_state' => 25, 'name' => ' Braúna'],
                ['id_city' => 8939, 'id_state' => 25, 'name' => ' Brejo Alegre'],
                ['id_city' => 8940, 'id_state' => 25, 'name' => ' Brodowski'],
                ['id_city' => 8941, 'id_state' => 25, 'name' => ' Brotas'],
                ['id_city' => 8942, 'id_state' => 25, 'name' => ' Bueno de Andrada'],
                ['id_city' => 8943, 'id_state' => 25, 'name' => ' Buri'],
                ['id_city' => 8944, 'id_state' => 25, 'name' => ' Buritama'],
                ['id_city' => 8945, 'id_state' => 25, 'name' => ' Buritizal'],
                ['id_city' => 8946, 'id_state' => 25, 'name' => ' Cabrália Paulista'],
                ['id_city' => 8947, 'id_state' => 25, 'name' => ' Cabreúva'],
                ['id_city' => 8948, 'id_state' => 25, 'name' => ' Caçapava'],
                ['id_city' => 8949, 'id_state' => 25, 'name' => ' Cachoeira de Emas'],
                ['id_city' => 8950, 'id_state' => 25, 'name' => ' Cachoeira Paulista'],
                ['id_city' => 8951, 'id_state' => 25, 'name' => ' Caconde'],
                ['id_city' => 8952, 'id_state' => 25, 'name' => ' Cafelândia'],
                ['id_city' => 8953, 'id_state' => 25, 'name' => ' Cafesópolis'],
                ['id_city' => 8954, 'id_state' => 25, 'name' => ' Caiabu'],
                ['id_city' => 8955, 'id_state' => 25, 'name' => ' Caibura'],
                ['id_city' => 8956, 'id_state' => 25, 'name' => ' Caieiras'],
                ['id_city' => 8957, 'id_state' => 25, 'name' => ' Caiuá'],
                ['id_city' => 8958, 'id_state' => 25, 'name' => ' Cajamar'],
                ['id_city' => 8959, 'id_state' => 25, 'name' => ' Cajati'],
                ['id_city' => 8960, 'id_state' => 25, 'name' => ' Cajobi'],
                ['id_city' => 8961, 'id_state' => 25, 'name' => ' Cajuru'],
                ['id_city' => 8962, 'id_state' => 25, 'name' => ' Cambaquara'],
                ['id_city' => 8963, 'id_state' => 25, 'name' => ' Cambaratiba'],
                ['id_city' => 8964, 'id_state' => 25, 'name' => ' Campestrinho'],
                ['id_city' => 8965, 'id_state' => 25, 'name' => ' Campina de Fora'],
                ['id_city' => 8966, 'id_state' => 25, 'name' => ' Campina do Monte Alegre'],
                ['id_city' => 8967, 'id_state' => 25, 'name' => ' Campinal'],
                ['id_city' => 8968, 'id_state' => 25, 'name' => ' Campinas'],
                ['id_city' => 8969, 'id_state' => 25, 'name' => ' Campo Limpo Paulista'],
                ['id_city' => 8970, 'id_state' => 25, 'name' => ' Campos de Cunha'],
                ['id_city' => 8971, 'id_state' => 25, 'name' => ' Campos do Jordão'],
                ['id_city' => 8972, 'id_state' => 25, 'name' => ' Campos Novos Paulista'],
                ['id_city' => 8973, 'id_state' => 25, 'name' => ' Cananéia'],
                ['id_city' => 8974, 'id_state' => 25, 'name' => ' Canas'],
                ['id_city' => 8975, 'id_state' => 25, 'name' => ' Candia'],
                ['id_city' => 8976, 'id_state' => 25, 'name' => ' Cândido Mota'],
                ['id_city' => 8977, 'id_state' => 25, 'name' => ' Cândido Rodrigues'],
                ['id_city' => 8978, 'id_state' => 25, 'name' => ' Canguera'],
                ['id_city' => 8979, 'id_state' => 25, 'name' => ' Canitar'],
                ['id_city' => 8980, 'id_state' => 25, 'name' => ' Capão Bonito'],
                ['id_city' => 8981, 'id_state' => 25, 'name' => ' Capela do Alto'],
                ['id_city' => 8982, 'id_state' => 25, 'name' => ' Capivari'],
                ['id_city' => 8983, 'id_state' => 25, 'name' => ' Capivari da Mata'],
                ['id_city' => 8984, 'id_state' => 25, 'name' => ' Caporanga'],
                ['id_city' => 8985, 'id_state' => 25, 'name' => ' Capuava'],
                ['id_city' => 8986, 'id_state' => 25, 'name' => ' Caraguatatuba'],
                ['id_city' => 8987, 'id_state' => 25, 'name' => ' Carapicuíba'],
                ['id_city' => 8988, 'id_state' => 25, 'name' => ' Cardeal'],
                ['id_city' => 8989, 'id_state' => 25, 'name' => ' Cardoso'],
                ['id_city' => 8990, 'id_state' => 25, 'name' => ' Nova Cardoso'],
                ['id_city' => 8991, 'id_state' => 25, 'name' => ' Caruara'],
                ['id_city' => 8992, 'id_state' => 25, 'name' => ' Casa Branca'],
                ['id_city' => 8993, 'id_state' => 25, 'name' => ' Cássia dos Coqueiros'],
                ['id_city' => 8994, 'id_state' => 25, 'name' => ' Castilho'],
                ['id_city' => 8995, 'id_state' => 25, 'name' => ' Catanduva'],
                ['id_city' => 8996, 'id_state' => 25, 'name' => ' Catiguá'],
                ['id_city' => 8997, 'id_state' => 25, 'name' => ' Catucaba'],
                ['id_city' => 8998, 'id_state' => 25, 'name' => ' Caucaia do Alto'],
                ['id_city' => 8999, 'id_state' => 25, 'name' => ' Cedral'],
                ['id_city' => 9000, 'id_state' => 25, 'name' => ' Cerqueira César'],
                ['id_city' => 9001, 'id_state' => 25, 'name' => ' Cerquilho'],
                ['id_city' => 9002, 'id_state' => 25, 'name' => ' Cesário Lange'],
                ['id_city' => 9003, 'id_state' => 25, 'name' => ' Cezar de Souza'],
                ['id_city' => 9004, 'id_state' => 25, 'name' => ' Charqueada'],
                ['id_city' => 9005, 'id_state' => 25, 'name' => ' Chavantes'],
                ['id_city' => 9006, 'id_state' => 25, 'name' => ' Cipó-Guaçu'],
                ['id_city' => 9007, 'id_state' => 25, 'name' => ' Clarinia'],
                ['id_city' => 9008, 'id_state' => 25, 'name' => ' Clementina'],
                ['id_city' => 9009, 'id_state' => 25, 'name' => ' Cocaes'],
                ['id_city' => 9010, 'id_state' => 25, 'name' => ' Colina'],
                ['id_city' => 9011, 'id_state' => 25, 'name' => ' Colômbia'],
                ['id_city' => 9012, 'id_state' => 25, 'name' => ' Conceição de Monte Alegre'],
                ['id_city' => 9013, 'id_state' => 25, 'name' => ' Conchal'],
                ['id_city' => 9014, 'id_state' => 25, 'name' => ' Conchas'],
                ['id_city' => 9015, 'id_state' => 25, 'name' => ' Cordeirópolis'],
                ['id_city' => 9016, 'id_state' => 25, 'name' => ' Coroados'],
                ['id_city' => 9017, 'id_state' => 25, 'name' => ' Coronel Goulart'],
                ['id_city' => 9018, 'id_state' => 25, 'name' => ' Coronel Macedo'],
                ['id_city' => 9019, 'id_state' => 25, 'name' => ' Corredeira'],
                ['id_city' => 9020, 'id_state' => 25, 'name' => ' Córrego Rico'],
                ['id_city' => 9021, 'id_state' => 25, 'name' => ' Corumbataí'],
                ['id_city' => 9022, 'id_state' => 25, 'name' => ' Cosmópolis'],
                ['id_city' => 9023, 'id_state' => 25, 'name' => ' Cosmorama'],
                ['id_city' => 9024, 'id_state' => 25, 'name' => ' Costa Machado'],
                ['id_city' => 9025, 'id_state' => 25, 'name' => ' Cotia'],
                ['id_city' => 9026, 'id_state' => 25, 'name' => ' Cravinhos'],
                ['id_city' => 9027, 'id_state' => 25, 'name' => ' Cristais Paulista'],
                ['id_city' => 9028, 'id_state' => 25, 'name' => ' Cruz das Posses'],
                ['id_city' => 9029, 'id_state' => 25, 'name' => ' Cruzália'],
                ['id_city' => 9030, 'id_state' => 25, 'name' => ' Cruzeiro'],
                ['id_city' => 9031, 'id_state' => 25, 'name' => ' Cubatão'],
                ['id_city' => 9032, 'id_state' => 25, 'name' => ' Cuiabá Paulista'],
                ['id_city' => 9033, 'id_state' => 25, 'name' => ' Cunha'],
                ['id_city' => 9034, 'id_state' => 25, 'name' => ' Curupá'],
                ['id_city' => 9035, 'id_state' => 25, 'name' => ' Dalas'],
                ['id_city' => 9036, 'id_state' => 25, 'name' => ' Descalvado'],
                ['id_city' => 9037, 'id_state' => 25, 'name' => ' Diadema'],
                ['id_city' => 9038, 'id_state' => 25, 'name' => ' Dirce Reis'],
                ['id_city' => 9039, 'id_state' => 25, 'name' => ' Dirceu'],
                ['id_city' => 9040, 'id_state' => 25, 'name' => ' Divinolândia'],
                ['id_city' => 9041, 'id_state' => 25, 'name' => ' Dobrada'],
                ['id_city' => 9042, 'id_state' => 25, 'name' => ' Dois Córregos'],
                ['id_city' => 9043, 'id_state' => 25, 'name' => ' Dolcinópolis'],
                ['id_city' => 9044, 'id_state' => 25, 'name' => ' Domélia'],
                ['id_city' => 9045, 'id_state' => 25, 'name' => ' Dourado'],
                ['id_city' => 9046, 'id_state' => 25, 'name' => ' Dracena'],
                ['id_city' => 9047, 'id_state' => 25, 'name' => ' Duartina'],
                ['id_city' => 9048, 'id_state' => 25, 'name' => ' Dumont'],
                ['id_city' => 9049, 'id_state' => 25, 'name' => ' Duplo Céu'],
                ['id_city' => 9050, 'id_state' => 25, 'name' => ' Echaporã'],
                ['id_city' => 9051, 'id_state' => 25, 'name' => ' Eldorado'],
                ['id_city' => 9052, 'id_state' => 25, 'name' => ' Eleutério'],
                ['id_city' => 9053, 'id_state' => 25, 'name' => ' Elias Fausto'],
                ['id_city' => 9054, 'id_state' => 25, 'name' => ' Elisiário'],
                ['id_city' => 9055, 'id_state' => 25, 'name' => ' Embaúba'],
                ['id_city' => 9056, 'id_state' => 25, 'name' => ' Embu das Artes'],
                ['id_city' => 9057, 'id_state' => 25, 'name' => ' Embu-Guaçu'],
                ['id_city' => 9058, 'id_state' => 25, 'name' => ' Emilianópolis'],
                ['id_city' => 9059, 'id_state' => 25, 'name' => ' Eneida'],
                ['id_city' => 9060, 'id_state' => 25, 'name' => ' Engenheiro Balduíno'],
                ['id_city' => 9061, 'id_state' => 25, 'name' => ' Engenheiro Coelho'],
                ['id_city' => 9062, 'id_state' => 25, 'name' => ' Engenheiro Maia'],
                ['id_city' => 9063, 'id_state' => 25, 'name' => ' Engenheiro Schmitt'],
                ['id_city' => 9064, 'id_state' => 25, 'name' => ' Esmeralda'],
                ['id_city' => 9065, 'id_state' => 25, 'name' => ' Esperança D Oeste'],
                ['id_city' => 9066, 'id_state' => 25, 'name' => ' Espigão'],
                ['id_city' => 9067, 'id_state' => 25, 'name' => ' Espírito Santo do Pinhal'],
                ['id_city' => 9068, 'id_state' => 25, 'name' => ' Espírito Santo do Turvo'],
                ['id_city' => 9069, 'id_state' => 25, 'name' => ' Estiva Gerbi'],
                ['id_city' => 9070, 'id_state' => 25, 'name' => ' Estrela D Oeste'],
                ['id_city' => 9071, 'id_state' => 25, 'name' => ' Estrela do Norte'],
                ['id_city' => 9072, 'id_state' => 25, 'name' => ' Euclides da Cunha Paulista'],
                ['id_city' => 9073, 'id_state' => 25, 'name' => ' Eugênio de Melo'],
                ['id_city' => 9074, 'id_state' => 25, 'name' => ' Fartura'],
                ['id_city' => 9075, 'id_state' => 25, 'name' => ' Fátima'],
                ['id_city' => 9076, 'id_state' => 25, 'name' => ' Fátima Paulista'],
                ['id_city' => 9077, 'id_state' => 25, 'name' => ' Fazenda Velha'],
                ['id_city' => 9078, 'id_state' => 25, 'name' => ' Fernando Prestes'],
                ['id_city' => 9079, 'id_state' => 25, 'name' => ' Fernandópolis'],
                ['id_city' => 9080, 'id_state' => 25, 'name' => ' Fernão'],
                ['id_city' => 9081, 'id_state' => 25, 'name' => ' Ferraz de Vasconcelos'],
                ['id_city' => 9082, 'id_state' => 25, 'name' => ' Flora Rica'],
                ['id_city' => 9083, 'id_state' => 25, 'name' => ' Floreal'],
                ['id_city' => 9084, 'id_state' => 25, 'name' => ' Floresta do Sul'],
                ['id_city' => 9085, 'id_state' => 25, 'name' => ' Flórida Paulista'],
                ['id_city' => 9086, 'id_state' => 25, 'name' => ' Florínia'],
                ['id_city' => 9087, 'id_state' => 25, 'name' => ' Franca'],
                ['id_city' => 9088, 'id_state' => 25, 'name' => ' Francisco Morato'],
                ['id_city' => 9089, 'id_state' => 25, 'name' => ' Franco da Rocha'],
                ['id_city' => 9090, 'id_state' => 25, 'name' => ' Frutal do Campo'],
                ['id_city' => 9091, 'id_state' => 25, 'name' => ' Gabriel Monteiro'],
                ['id_city' => 9092, 'id_state' => 25, 'name' => ' Gália'],
                ['id_city' => 9093, 'id_state' => 25, 'name' => ' Garça'],
                ['id_city' => 9094, 'id_state' => 25, 'name' => ' Gardênia'],
                ['id_city' => 9095, 'id_state' => 25, 'name' => ' Gastão Vidigal'],
                ['id_city' => 9096, 'id_state' => 25, 'name' => ' Gavião Peixoto'],
                ['id_city' => 9097, 'id_state' => 25, 'name' => ' General Salgado'],
                ['id_city' => 9098, 'id_state' => 25, 'name' => ' Getulina'],
                ['id_city' => 9099, 'id_state' => 25, 'name' => ' Glicério'],
                ['id_city' => 9100, 'id_state' => 25, 'name' => ' Gramadinho'],
                ['id_city' => 9101, 'id_state' => 25, 'name' => ' Guachos'],
                ['id_city' => 9102, 'id_state' => 25, 'name' => ' Guaianas'],
                ['id_city' => 9103, 'id_state' => 25, 'name' => ' Guaiçara'],
                ['id_city' => 9104, 'id_state' => 25, 'name' => ' Guaimbê'],
                ['id_city' => 9105, 'id_state' => 25, 'name' => ' Guaíra'],
                ['id_city' => 9106, 'id_state' => 25, 'name' => ' Guamium'],
                ['id_city' => 9107, 'id_state' => 25, 'name' => ' Guapiaçu'],
                ['id_city' => 9108, 'id_state' => 25, 'name' => ' Guapiara'],
                ['id_city' => 9109, 'id_state' => 25, 'name' => ' Guapiranga'],
                ['id_city' => 9110, 'id_state' => 25, 'name' => ' Guará'],
                ['id_city' => 9111, 'id_state' => 25, 'name' => ' Guaraçaí'],
                ['id_city' => 9112, 'id_state' => 25, 'name' => ' Guaraci'],
                ['id_city' => 9113, 'id_state' => 25, 'name' => ' Guaraciaba D Oeste'],
                ['id_city' => 9114, 'id_state' => 25, 'name' => ' Guarani D Oeste'],
                ['id_city' => 9115, 'id_state' => 25, 'name' => ' Guarantã'],
                ['id_city' => 9116, 'id_state' => 25, 'name' => ' Guarapiranga'],
                ['id_city' => 9117, 'id_state' => 25, 'name' => ' Guarapuá'],
                ['id_city' => 9118, 'id_state' => 25, 'name' => ' Guararapes'],
                ['id_city' => 9119, 'id_state' => 25, 'name' => ' Guararema'],
                ['id_city' => 9120, 'id_state' => 25, 'name' => ' Guaratinguetá'],
                ['id_city' => 9121, 'id_state' => 25, 'name' => ' Guareí'],
                ['id_city' => 9122, 'id_state' => 25, 'name' => ' Guariba'],
                ['id_city' => 9123, 'id_state' => 25, 'name' => ' Guariroba'],
                ['id_city' => 9124, 'id_state' => 25, 'name' => ' Guarizinho'],
                ['id_city' => 9125, 'id_state' => 25, 'name' => ' Guarujá'],
                ['id_city' => 9126, 'id_state' => 25, 'name' => ' Guarulhos'],
                ['id_city' => 9127, 'id_state' => 25, 'name' => ' Guatapará'],
                ['id_city' => 9128, 'id_state' => 25, 'name' => ' Guzolândia'],
                ['id_city' => 9129, 'id_state' => 25, 'name' => ' Herculândia'],
                ['id_city' => 9130, 'id_state' => 25, 'name' => ' Holambra'],
                ['id_city' => 9131, 'id_state' => 25, 'name' => ' Holambra II'],
                ['id_city' => 9132, 'id_state' => 25, 'name' => ' Hortolândia'],
                ['id_city' => 9133, 'id_state' => 25, 'name' => ' Iacanga'],
                ['id_city' => 9134, 'id_state' => 25, 'name' => ' Iacri'],
                ['id_city' => 9135, 'id_state' => 25, 'name' => ' Iaras'],
                ['id_city' => 9136, 'id_state' => 25, 'name' => ' Ibaté'],
                ['id_city' => 9137, 'id_state' => 25, 'name' => ' Ibiporanga'],
                ['id_city' => 9138, 'id_state' => 25, 'name' => ' Ibirá'],
                ['id_city' => 9139, 'id_state' => 25, 'name' => ' Ibirarema'],
                ['id_city' => 9140, 'id_state' => 25, 'name' => ' Ibitinga'],
                ['id_city' => 9141, 'id_state' => 25, 'name' => ' Ibitiruna'],
                ['id_city' => 9142, 'id_state' => 25, 'name' => ' Ibitiúva'],
                ['id_city' => 9143, 'id_state' => 25, 'name' => ' Ibitu'],
                ['id_city' => 9144, 'id_state' => 25, 'name' => ' Ibiúna'],
                ['id_city' => 9145, 'id_state' => 25, 'name' => ' Icém'],
                ['id_city' => 9146, 'id_state' => 25, 'name' => ' Ida Iolanda'],
                ['id_city' => 9147, 'id_state' => 25, 'name' => ' Iepê'],
                ['id_city' => 9148, 'id_state' => 25, 'name' => ' Igaçaba'],
                ['id_city' => 9149, 'id_state' => 25, 'name' => ' Igaraçu do Tietê'],
                ['id_city' => 9150, 'id_state' => 25, 'name' => ' Igaraí'],
                ['id_city' => 9151, 'id_state' => 25, 'name' => ' Igarapava'],
                ['id_city' => 9152, 'id_state' => 25, 'name' => ' Igaratá'],
                ['id_city' => 9153, 'id_state' => 25, 'name' => ' Iguape'],
                ['id_city' => 9154, 'id_state' => 25, 'name' => ' Ilha Comprida'],
                ['id_city' => 9155, 'id_state' => 25, 'name' => ' Ilha Diana'],
                ['id_city' => 9156, 'id_state' => 25, 'name' => ' Ilha Solteira'],
                ['id_city' => 9157, 'id_state' => 25, 'name' => ' Ilhabela'],
                ['id_city' => 9158, 'id_state' => 25, 'name' => ' Indaiá do Aguapeí'],
                ['id_city' => 9159, 'id_state' => 25, 'name' => ' Indaiatuba'],
                ['id_city' => 9160, 'id_state' => 25, 'name' => ' Indiana'],
                ['id_city' => 9161, 'id_state' => 25, 'name' => ' Indiaporã'],
                ['id_city' => 9162, 'id_state' => 25, 'name' => ' Ingás'],
                ['id_city' => 9163, 'id_state' => 25, 'name' => ' Inúbia Paulista'],
                ['id_city' => 9164, 'id_state' => 25, 'name' => ' Ipaussu'],
                ['id_city' => 9165, 'id_state' => 25, 'name' => ' Iperó'],
                ['id_city' => 9166, 'id_state' => 25, 'name' => ' Ipeúna'],
                ['id_city' => 9167, 'id_state' => 25, 'name' => ' Ipiguá'],
                ['id_city' => 9168, 'id_state' => 25, 'name' => ' Iporanga'],
                ['id_city' => 9169, 'id_state' => 25, 'name' => ' Ipuã'],
                ['id_city' => 9170, 'id_state' => 25, 'name' => ' Iracemápolis'],
                ['id_city' => 9171, 'id_state' => 25, 'name' => ' Irapé'],
                ['id_city' => 9172, 'id_state' => 25, 'name' => ' Irapuã'],
                ['id_city' => 9173, 'id_state' => 25, 'name' => ' Irapuru'],
                ['id_city' => 9174, 'id_state' => 25, 'name' => ' Itaberá'],
                ['id_city' => 9175, 'id_state' => 25, 'name' => ' Itaboa'],
                ['id_city' => 9176, 'id_state' => 25, 'name' => ' Itaí'],
                ['id_city' => 9177, 'id_state' => 25, 'name' => ' Itaiúba'],
                ['id_city' => 9178, 'id_state' => 25, 'name' => ' Itajobi'],
                ['id_city' => 9179, 'id_state' => 25, 'name' => ' Itaju'],
                ['id_city' => 9180, 'id_state' => 25, 'name' => ' Itanhaém'],
                ['id_city' => 9181, 'id_state' => 25, 'name' => ' Itaóca'],
                ['id_city' => 9182, 'id_state' => 25, 'name' => ' Itapecerica da Serra'],
                ['id_city' => 9183, 'id_state' => 25, 'name' => ' Itapetininga'],
                ['id_city' => 9184, 'id_state' => 25, 'name' => ' Itapeuna'],
                ['id_city' => 9185, 'id_state' => 25, 'name' => ' Itapeva'],
                ['id_city' => 9186, 'id_state' => 25, 'name' => ' Itapevi'],
                ['id_city' => 9187, 'id_state' => 25, 'name' => ' Itapira'],
                ['id_city' => 9188, 'id_state' => 25, 'name' => ' Itapirapuã Paulista'],
                ['id_city' => 9189, 'id_state' => 25, 'name' => ' Itápolis'],
                ['id_city' => 9190, 'id_state' => 25, 'name' => ' Itaporanga'],
                ['id_city' => 9191, 'id_state' => 25, 'name' => ' Itapuí'],
                ['id_city' => 9192, 'id_state' => 25, 'name' => ' Itapura'],
                ['id_city' => 9193, 'id_state' => 25, 'name' => ' Itaquaquecetuba'],
                ['id_city' => 9194, 'id_state' => 25, 'name' => ' Itaqueri da Serra'],
                ['id_city' => 9195, 'id_state' => 25, 'name' => ' Itararé'],
                ['id_city' => 9196, 'id_state' => 25, 'name' => ' Itariri'],
                ['id_city' => 9197, 'id_state' => 25, 'name' => ' Itatiba'],
                ['id_city' => 9198, 'id_state' => 25, 'name' => ' Itatinga'],
                ['id_city' => 9199, 'id_state' => 25, 'name' => ' Itirapina'],
                ['id_city' => 9200, 'id_state' => 25, 'name' => ' Itirapuã'],
                ['id_city' => 9201, 'id_state' => 25, 'name' => ' Itobi'],
                ['id_city' => 9202, 'id_state' => 25, 'name' => ' Itororó do Paranapanema'],
                ['id_city' => 9203, 'id_state' => 25, 'name' => ' Itu'],
                ['id_city' => 9204, 'id_state' => 25, 'name' => ' Itupeva'],
                ['id_city' => 9205, 'id_state' => 25, 'name' => ' Ituverava'],
                ['id_city' => 9206, 'id_state' => 25, 'name' => ' Iubatinga'],
                ['id_city' => 9207, 'id_state' => 25, 'name' => ' Jaborandi'],
                ['id_city' => 9208, 'id_state' => 25, 'name' => ' Jaboticabal'],
                ['id_city' => 9209, 'id_state' => 25, 'name' => ' Jacaré'],
                ['id_city' => 9210, 'id_state' => 25, 'name' => ' Jacareí'],
                ['id_city' => 9211, 'id_state' => 25, 'name' => ' Jaci'],
                ['id_city' => 9212, 'id_state' => 25, 'name' => ' Jaciporã'],
                ['id_city' => 9213, 'id_state' => 25, 'name' => ' Jacuba'],
                ['id_city' => 9214, 'id_state' => 25, 'name' => ' Jacupiranga'],
                ['id_city' => 9215, 'id_state' => 25, 'name' => ' Jafa'],
                ['id_city' => 9216, 'id_state' => 25, 'name' => ' Jaguariúna'],
                ['id_city' => 9217, 'id_state' => 25, 'name' => ' Jales'],
                ['id_city' => 9218, 'id_state' => 25, 'name' => ' Jamaica'],
                ['id_city' => 9219, 'id_state' => 25, 'name' => ' Jambeiro'],
                ['id_city' => 9220, 'id_state' => 25, 'name' => ' Jandira'],
                ['id_city' => 9221, 'id_state' => 25, 'name' => ' Jardim Belval'],
                ['id_city' => 9222, 'id_state' => 25, 'name' => ' Jardim Presidente Dutra'],
                ['id_city' => 9223, 'id_state' => 25, 'name' => ' Jardim Santa Luzia'],
                ['id_city' => 9224, 'id_state' => 25, 'name' => ' Jardim Silveira'],
                ['id_city' => 9225, 'id_state' => 25, 'name' => ' Jardinópolis'],
                ['id_city' => 9226, 'id_state' => 25, 'name' => ' Jarinu'],
                ['id_city' => 9227, 'id_state' => 25, 'name' => ' Jatobá'],
                ['id_city' => 9228, 'id_state' => 25, 'name' => ' Jaú'],
                ['id_city' => 9229, 'id_state' => 25, 'name' => ' Jeriquara'],
                ['id_city' => 9230, 'id_state' => 25, 'name' => ' Joanópolis'],
                ['id_city' => 9231, 'id_state' => 25, 'name' => ' João Ramalho'],
                ['id_city' => 9232, 'id_state' => 25, 'name' => ' Joaquim Egídio'],
                ['id_city' => 9233, 'id_state' => 25, 'name' => ' Jordanésia'],
                ['id_city' => 9234, 'id_state' => 25, 'name' => ' José Bonifácio'],
                ['id_city' => 9235, 'id_state' => 25, 'name' => ' Juliânia'],
                ['id_city' => 9236, 'id_state' => 25, 'name' => ' Júlio Mesquita'],
                ['id_city' => 9237, 'id_state' => 25, 'name' => ' Jumirim'],
                ['id_city' => 9238, 'id_state' => 25, 'name' => ' Jundiaí'],
                ['id_city' => 9239, 'id_state' => 25, 'name' => ' Jundiapeba'],
                ['id_city' => 9240, 'id_state' => 25, 'name' => ' Junqueira'],
                ['id_city' => 9241, 'id_state' => 25, 'name' => ' Junqueirópolis'],
                ['id_city' => 9242, 'id_state' => 25, 'name' => ' Juquiá'],
                ['id_city' => 9243, 'id_state' => 25, 'name' => ' Juquiratiba'],
                ['id_city' => 9244, 'id_state' => 25, 'name' => ' Juquitiba'],
                ['id_city' => 9245, 'id_state' => 25, 'name' => ' Juritis'],
                ['id_city' => 9246, 'id_state' => 25, 'name' => ' Jurucê'],
                ['id_city' => 9247, 'id_state' => 25, 'name' => ' Jurupeba'],
                ['id_city' => 9248, 'id_state' => 25, 'name' => ' Jurupema'],
                ['id_city' => 9249, 'id_state' => 25, 'name' => ' Lácio'],
                ['id_city' => 9250, 'id_state' => 25, 'name' => ' Lagoa Azul'],
                ['id_city' => 9251, 'id_state' => 25, 'name' => ' Lagoa Branca'],
                ['id_city' => 9252, 'id_state' => 25, 'name' => ' Lagoinha'],
                ['id_city' => 9253, 'id_state' => 25, 'name' => ' Laranjal Paulista'],
                ['id_city' => 9254, 'id_state' => 25, 'name' => ' Laras'],
                ['id_city' => 9255, 'id_state' => 25, 'name' => ' Lauro Penteado'],
                ['id_city' => 9256, 'id_state' => 25, 'name' => ' Lavínia'],
                ['id_city' => 9257, 'id_state' => 25, 'name' => ' Lavrinhas'],
                ['id_city' => 9258, 'id_state' => 25, 'name' => ' Leme'],
                ['id_city' => 9259, 'id_state' => 25, 'name' => ' Lençóis Paulista'],
                ['id_city' => 9260, 'id_state' => 25, 'name' => ' Limeira'],
                ['id_city' => 9261, 'id_state' => 25, 'name' => ' Lindóia'],
                ['id_city' => 9262, 'id_state' => 25, 'name' => ' Lins'],
                ['id_city' => 9263, 'id_state' => 25, 'name' => ' Lobo'],
                ['id_city' => 9264, 'id_state' => 25, 'name' => ' Lorena'],
                ['id_city' => 9265, 'id_state' => 25, 'name' => ' Lourdes'],
                ['id_city' => 9266, 'id_state' => 25, 'name' => ' Louveira'],
                ['id_city' => 9267, 'id_state' => 25, 'name' => ' Lucélia'],
                ['id_city' => 9268, 'id_state' => 25, 'name' => ' Lucianópolis'],
                ['id_city' => 9269, 'id_state' => 25, 'name' => ' Luís Antônio'],
                ['id_city' => 9270, 'id_state' => 25, 'name' => ' Luiziânia'],
                ['id_city' => 9271, 'id_state' => 25, 'name' => ' Lupércio'],
                ['id_city' => 9272, 'id_state' => 25, 'name' => ' Lusitânia'],
                ['id_city' => 9273, 'id_state' => 25, 'name' => ' Lutécia'],
                ['id_city' => 9274, 'id_state' => 25, 'name' => ' Macatuba'],
                ['id_city' => 9275, 'id_state' => 25, 'name' => ' Macaubal'],
                ['id_city' => 9276, 'id_state' => 25, 'name' => ' Macedônia'],
                ['id_city' => 9277, 'id_state' => 25, 'name' => ' Macucos'],
                ['id_city' => 9278, 'id_state' => 25, 'name' => ' Mágda'],
                ['id_city' => 9279, 'id_state' => 25, 'name' => ' Mailasqui'],
                ['id_city' => 9280, 'id_state' => 25, 'name' => ' Mairinque'],
                ['id_city' => 9281, 'id_state' => 25, 'name' => ' Mairiporã'],
                ['id_city' => 9282, 'id_state' => 25, 'name' => ' Major Prado'],
                ['id_city' => 9283, 'id_state' => 25, 'name' => ' Manduri'],
                ['id_city' => 9284, 'id_state' => 25, 'name' => ' Mangaratú'],
                ['id_city' => 9285, 'id_state' => 25, 'name' => ' Marabá Paulista'],
                ['id_city' => 9286, 'id_state' => 25, 'name' => ' Maracaí'],
                ['id_city' => 9287, 'id_state' => 25, 'name' => ' Marapoama'],
                ['id_city' => 9288, 'id_state' => 25, 'name' => ' Marcondésia'],
                ['id_city' => 9289, 'id_state' => 25, 'name' => ' Maresias'],
                ['id_city' => 9290, 'id_state' => 25, 'name' => ' Mariápolis'],
                ['id_city' => 9291, 'id_state' => 25, 'name' => ' Marília'],
            ]);
        }
    }