<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities17 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 10564, 'id_state' => 21, 'name' => ' Campo do Meio'],
                ['id_city' => 10565, 'id_state' => 21, 'name' => ' Engenheiro Luiz Englert'],
                ['id_city' => 10566, 'id_state' => 21, 'name' => ' Colombo'],
                ['id_city' => 10567, 'id_state' => 21, 'name' => ' Santo Antônio'],
                ['id_city' => 10568, 'id_state' => 21, 'name' => ' Pulador'],
                ['id_city' => 10569, 'id_state' => 21, 'name' => ' Fazenda Fialho'],
                ['id_city' => 10570, 'id_state' => 21, 'name' => ' Santa Gema'],
                ['id_city' => 10571, 'id_state' => 21, 'name' => ' Bugre'],
                ['id_city' => 10572, 'id_state' => 21, 'name' => ' Santa Terezinha'],
                ['id_city' => 10573, 'id_state' => 21, 'name' => ' Rincão Comprido'],
                ['id_city' => 10574, 'id_state' => 21, 'name' => ' Cerro Preto'],
                ['id_city' => 10575, 'id_state' => 21, 'name' => ' Nossa Senhora Aparecida'],
                ['id_city' => 10576, 'id_state' => 21, 'name' => ' Pedregal'],
                ['id_city' => 10577, 'id_state' => 21, 'name' => ' Despraiado'],
                ['id_city' => 10578, 'id_state' => 21, 'name' => ' Linha Silveira'],
                ['id_city' => 10579, 'id_state' => 21, 'name' => ' Três Pinheiros'],
                ['id_city' => 10580, 'id_state' => 21, 'name' => ' Treze de Maio'],
                ['id_city' => 10581, 'id_state' => 21, 'name' => ' Santa Lúcia'],
                ['id_city' => 10582, 'id_state' => 21, 'name' => ' São José'],
                ['id_city' => 10583, 'id_state' => 21, 'name' => ' Linha Bonita'],
                ['id_city' => 10584, 'id_state' => 21, 'name' => ' Volta Vitória'],
                ['id_city' => 10585, 'id_state' => 21, 'name' => ' Mundo Novo'],
                ['id_city' => 10586, 'id_state' => 21, 'name' => ' Linha Ferrari'],
                ['id_city' => 10587, 'id_state' => 21, 'name' => ' Rincão dos Toledos'],
                ['id_city' => 10588, 'id_state' => 21, 'name' => ' São José dos Campos Borges'],
                ['id_city' => 10589, 'id_state' => 21, 'name' => ' Varame'],
                ['id_city' => 10590, 'id_state' => 21, 'name' => ' Passo Real'],
                ['id_city' => 10591, 'id_state' => 21, 'name' => ' Rincão do Ivaí'],
                ['id_city' => 10592, 'id_state' => 21, 'name' => ' Júlio Borges'],
                ['id_city' => 10593, 'id_state' => 21, 'name' => ' Floresta'],
                ['id_city' => 10594, 'id_state' => 21, 'name' => ' São Pedro'],
                ['id_city' => 10595, 'id_state' => 21, 'name' => ' Vila Paz'],
                ['id_city' => 10596, 'id_state' => 21, 'name' => ' Linha Glória'],
                ['id_city' => 10597, 'id_state' => 21, 'name' => ' Posse dos Linhares'],
                ['id_city' => 10598, 'id_state' => 21, 'name' => ' Barra Curta Baixa'],
                ['id_city' => 10599, 'id_state' => 21, 'name' => ' São Marcos Baixo'],
                ['id_city' => 10600, 'id_state' => 21, 'name' => ' Coxilha Seca'],
                ['id_city' => 10601, 'id_state' => 21, 'name' => ' Souto Neto'],
                ['id_city' => 10602, 'id_state' => 21, 'name' => ' Brugnarotto'],
                ['id_city' => 10603, 'id_state' => 21, 'name' => ' Cerro Azul'],
                ['id_city' => 10604, 'id_state' => 21, 'name' => ' Jardim Alegre'],
                ['id_city' => 10605, 'id_state' => 21, 'name' => ' Marmeleiro'],
                ['id_city' => 10606, 'id_state' => 21, 'name' => ' São Miguel'],
                ['id_city' => 10607, 'id_state' => 21, 'name' => ' Vila Souza'],
                ['id_city' => 10608, 'id_state' => 21, 'name' => ' Vila Campos'],
                ['id_city' => 10609, 'id_state' => 21, 'name' => ' Engenho Grande'],
                ['id_city' => 10610, 'id_state' => 21, 'name' => ' Santo Antonio dos Pinheirinhos'],
                ['id_city' => 10611, 'id_state' => 21, 'name' => ' São Caetano'],
                ['id_city' => 10612, 'id_state' => 21, 'name' => ' Cruzaltinha'],
                ['id_city' => 10613, 'id_state' => 21, 'name' => ' Linha Francesa Alta'],
                ['id_city' => 10614, 'id_state' => 4, 'name' => ' Paricatuba'],
                ['id_city' => 10615, 'id_state' => 4, 'name' => ' Lago do Limão'],
                ['id_city' => 10616, 'id_state' => 4, 'name' => ' Ariaú'],
                ['id_city' => 10617, 'id_state' => 8, 'name' => ' Córrego Moacyr Ávidos'],
                ['id_city' => 10618, 'id_state' => 6, 'name' => ' Açudinho dos Costas'],
                ['id_city' => 10619, 'id_state' => 6, 'name' => ' Salgado dos Machados'],
                ['id_city' => 10620, 'id_state' => 6, 'name' => ' Barra do Ingá'],
                ['id_city' => 10621, 'id_state' => 13, 'name' => ' Araçaji de Minas'],
                ['id_city' => 10622, 'id_state' => 16, 'name' => ' Saltinho'],
                ['id_city' => 10623, 'id_state' => 6, 'name' => ' Poço da Onça'],
                ['id_city' => 10624, 'id_state' => 6, 'name' => ' Grande Basílio'],
                ['id_city' => 10625, 'id_state' => 5, 'name' => ' Monte Branco'],
                ['id_city' => 10626, 'id_state' => 5, 'name' => ' Itapicuru'],
                ['id_city' => 10627, 'id_state' => 5, 'name' => ' Volta da Serra'],
                ['id_city' => 10628, 'id_state' => 21, 'name' => ' Arroio do Ouro'],
                ['id_city' => 10629, 'id_state' => 21, 'name' => ' Forqueta Baixa'],
                ['id_city' => 10630, 'id_state' => 21, 'name' => ' Morro Gaúcho'],
                ['id_city' => 10631, 'id_state' => 21, 'name' => ' Canto Krewer'],
                ['id_city' => 10632, 'id_state' => 6, 'name' => ' Santa Luzia'],
                ['id_city' => 10633, 'id_state' => 6, 'name' => ' Baú'],
                ['id_city' => 10634, 'id_state' => 19, 'name' => ' Ponta Negra'],
                ['id_city' => 10635, 'id_state' => 19, 'name' => ' Itaipuaçu'],
                ['id_city' => 10636, 'id_state' => 6, 'name' => ' Pedra de Fogo'],
                ['id_city' => 10637, 'id_state' => 6, 'name' => ' Baracho'],
                ['id_city' => 10638, 'id_state' => 6, 'name' => ' Ema'],
                ['id_city' => 10639, 'id_state' => 20, 'name' => ' Bebida Velha'],
                ['id_city' => 10640, 'id_state' => 22, 'name' => ' Industrial'],
                ['id_city' => 10641, 'id_state' => 25, 'name' => ' Taquaral'],
                ['id_city' => 10642, 'id_state' => 11, 'name' => ' Santa Clara do Monte Cristo'],
                ['id_city' => 10643, 'id_state' => 5, 'name' => ' Cana Brava'],
                ['id_city' => 10644, 'id_state' => 16, 'name' => ' Marquês dos Reis'],
                ['id_city' => 10645, 'id_state' => 6, 'name' => ' Palestina'],
                ['id_city' => 10646, 'id_state' => 6, 'name' => ' São Raimundo'],
                ['id_city' => 10647, 'id_state' => 6, 'name' => ' Lagoa da Cruz'],
                ['id_city' => 10648, 'id_state' => 6, 'name' => ' Santa Tereza'],
                ['id_city' => 10649, 'id_state' => 6, 'name' => ' São Roque'],
                ['id_city' => 10650, 'id_state' => 6, 'name' => ' Paus Brancos'],
                ['id_city' => 10651, 'id_state' => 5, 'name' => ' Barra Grande'],
                ['id_city' => 10652, 'id_state' => 6, 'name' => ' Baixio'],
                ['id_city' => 10653, 'id_state' => 6, 'name' => ' Núcleo Colonial Pio XII'],
                ['id_city' => 10654, 'id_state' => 6, 'name' => ' Dourado'],
                ['id_city' => 10655, 'id_state' => 16, 'name' => ' Casa Branca'],
                ['id_city' => 10656, 'id_state' => 16, 'name' => ' Eliza'],
                ['id_city' => 10657, 'id_state' => 16, 'name' => ' Formigueiro'],
                ['id_city' => 10658, 'id_state' => 16, 'name' => ' Capinzal'],
                ['id_city' => 10659, 'id_state' => 1, 'name' => ' te']
            ]);
        }
    }
