<?php

use Illuminate\Database\Seeder;

class SeederCountriesStatesCities4 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
            DB::table('vpr_countries_states_cities')->insert([
                ['id_city' => 2234, 'id_state' => 9, 'name' => ' Araguapaz'],
                ['id_city' => 2235, 'id_state' => 9, 'name' => ' Arenópolis'],
                ['id_city' => 2236, 'id_state' => 9, 'name' => ' Aruanã'],
                ['id_city' => 2237, 'id_state' => 9, 'name' => ' Aurilândia'],
                ['id_city' => 2238, 'id_state' => 9, 'name' => ' Auriverde'],
                ['id_city' => 2239, 'id_state' => 9, 'name' => ' Avelinópolis'],
                ['id_city' => 2240, 'id_state' => 9, 'name' => ' Bacilândia'],
                ['id_city' => 2241, 'id_state' => 9, 'name' => ' Baliza'],
                ['id_city' => 2242, 'id_state' => 9, 'name' => ' Bandeirantes'],
                ['id_city' => 2243, 'id_state' => 9, 'name' => ' Barbosilândia'],
                ['id_city' => 2244, 'id_state' => 9, 'name' => ' Barro Alto'],
                ['id_city' => 2245, 'id_state' => 9, 'name' => ' Bela Vista de Goiás'],
                ['id_city' => 2246, 'id_state' => 9, 'name' => ' Bom Jardim de Goiás'],
                ['id_city' => 2247, 'id_state' => 9, 'name' => ' Bom Jesus'],
                ['id_city' => 2248, 'id_state' => 9, 'name' => ' Bonfinópolis'],
                ['id_city' => 2249, 'id_state' => 9, 'name' => ' Bonópolis'],
                ['id_city' => 2250, 'id_state' => 9, 'name' => ' Brazabrantes'],
                ['id_city' => 2251, 'id_state' => 9, 'name' => ' Britânia'],
                ['id_city' => 2252, 'id_state' => 9, 'name' => ' Buenolândia'],
                ['id_city' => 2253, 'id_state' => 9, 'name' => ' Buriti Alegre'],
                ['id_city' => 2254, 'id_state' => 9, 'name' => ' Buriti de Goiás'],
                ['id_city' => 2255, 'id_state' => 9, 'name' => ' Buritinópolis'],
                ['id_city' => 2256, 'id_state' => 9, 'name' => ' Cabeceiras'],
                ['id_city' => 2257, 'id_state' => 9, 'name' => ' Cachoeira Alta'],
                ['id_city' => 2258, 'id_state' => 9, 'name' => ' Cachoeira de Goiás'],
                ['id_city' => 2259, 'id_state' => 9, 'name' => ' Cachoeira Dourada'],
                ['id_city' => 2260, 'id_state' => 9, 'name' => ' Caçu'],
                ['id_city' => 2261, 'id_state' => 9, 'name' => ' Caiapônia'],
                ['id_city' => 2262, 'id_state' => 9, 'name' => ' Caiçara'],
                ['id_city' => 2263, 'id_state' => 9, 'name' => ' Calcilândia'],
                ['id_city' => 2264, 'id_state' => 9, 'name' => ' Caldas Novas'],
                ['id_city' => 2265, 'id_state' => 9, 'name' => ' Caldazinha'],
                ['id_city' => 2266, 'id_state' => 9, 'name' => ' Calixto'],
                ['id_city' => 2267, 'id_state' => 9, 'name' => ' Campestre de Goiás'],
                ['id_city' => 2268, 'id_state' => 9, 'name' => ' Campinaçu'],
                ['id_city' => 2269, 'id_state' => 9, 'name' => ' Campinorte'],
                ['id_city' => 2270, 'id_state' => 9, 'name' => ' Campo Alegre de Goiás'],
                ['id_city' => 2271, 'id_state' => 9, 'name' => ' Campo Limpo'],
                ['id_city' => 2272, 'id_state' => 9, 'name' => ' Campolândia'],
                ['id_city' => 2273, 'id_state' => 9, 'name' => ' Campos Belos'],
                ['id_city' => 2274, 'id_state' => 9, 'name' => ' Campos Verdes'],
                ['id_city' => 2275, 'id_state' => 9, 'name' => ' Cana Brava'],
                ['id_city' => 2276, 'id_state' => 9, 'name' => ' Canadá'],
                ['id_city' => 2277, 'id_state' => 9, 'name' => ' Capelinha'],
                ['id_city' => 2278, 'id_state' => 9, 'name' => ' Caraíba'],
                ['id_city' => 2279, 'id_state' => 9, 'name' => ' Carmo do Rio Verde'],
                ['id_city' => 2280, 'id_state' => 9, 'name' => ' Castelândia'],
                ['id_city' => 2281, 'id_state' => 9, 'name' => ' Castrinópolis'],
                ['id_city' => 2282, 'id_state' => 9, 'name' => ' Catalão'],
                ['id_city' => 2283, 'id_state' => 9, 'name' => ' Caturaí'],
                ['id_city' => 2284, 'id_state' => 9, 'name' => ' Cavalcante'],
                ['id_city' => 2285, 'id_state' => 9, 'name' => ' Cavalheiro'],
                ['id_city' => 2286, 'id_state' => 9, 'name' => ' Cebrasa'],
                ['id_city' => 2287, 'id_state' => 9, 'name' => ' Ceres'],
                ['id_city' => 2288, 'id_state' => 9, 'name' => ' Cezarina'],
                ['id_city' => 2289, 'id_state' => 9, 'name' => ' Chapadão do Céu'],
                ['id_city' => 2290, 'id_state' => 9, 'name' => ' Choupana'],
                ['id_city' => 2291, 'id_state' => 9, 'name' => ' Cibele'],
                ['id_city' => 2292, 'id_state' => 9, 'name' => ' Cidade Ocidental'],
                ['id_city' => 2293, 'id_state' => 9, 'name' => ' Cirilândia'],
                ['id_city' => 2294, 'id_state' => 9, 'name' => ' Cocalzinho de Goiás'],
                ['id_city' => 2295, 'id_state' => 9, 'name' => ' Colinas do Sul'],
                ['id_city' => 2296, 'id_state' => 9, 'name' => ' Córrego do Ouro'],
                ['id_city' => 2297, 'id_state' => 9, 'name' => ' Córrego Rico'],
                ['id_city' => 2298, 'id_state' => 9, 'name' => ' Corumbá de Goiás'],
                ['id_city' => 2299, 'id_state' => 9, 'name' => ' Corumbaíba'],
                ['id_city' => 2300, 'id_state' => 9, 'name' => ' Cristalina'],
                ['id_city' => 2301, 'id_state' => 9, 'name' => ' Cristianópolis'],
                ['id_city' => 2302, 'id_state' => 9, 'name' => ' Crixás'],
                ['id_city' => 2303, 'id_state' => 9, 'name' => ' Cromínia'],
                ['id_city' => 2304, 'id_state' => 9, 'name' => ' Cruzeiro do Norte'],
                ['id_city' => 2305, 'id_state' => 9, 'name' => ' Cumari'],
                ['id_city' => 2306, 'id_state' => 9, 'name' => ' Damianópolis'],
                ['id_city' => 2307, 'id_state' => 9, 'name' => ' Damolândia'],
                ['id_city' => 2308, 'id_state' => 9, 'name' => ' Davidópolis'],
                ['id_city' => 2309, 'id_state' => 9, 'name' => ' Davinópolis'],
                ['id_city' => 2310, 'id_state' => 9, 'name' => ' Diolândia'],
                ['id_city' => 2311, 'id_state' => 9, 'name' => ' Diorama'],
                ['id_city' => 2312, 'id_state' => 9, 'name' => ' Divinópolis de Goiás'],
                ['id_city' => 2313, 'id_state' => 9, 'name' => ' Domiciano Ribeiro'],
                ['id_city' => 2314, 'id_state' => 9, 'name' => ' Doverlândia'],
                ['id_city' => 2315, 'id_state' => 9, 'name' => ' Edealina'],
                ['id_city' => 2316, 'id_state' => 9, 'name' => ' Edéia'],
                ['id_city' => 2317, 'id_state' => 9, 'name' => ' Estrela do Norte'],
                ['id_city' => 2318, 'id_state' => 9, 'name' => ' Faina'],
                ['id_city' => 2319, 'id_state' => 9, 'name' => ' Fazenda Nova'],
                ['id_city' => 2320, 'id_state' => 9, 'name' => ' Firminópolis'],
                ['id_city' => 2321, 'id_state' => 9, 'name' => ' Flores de Goiás'],
                ['id_city' => 2322, 'id_state' => 9, 'name' => ' Formosa'],
                ['id_city' => 2323, 'id_state' => 9, 'name' => ' Formoso'],
                ['id_city' => 2324, 'id_state' => 9, 'name' => ' Forte'],
                ['id_city' => 2325, 'id_state' => 9, 'name' => ' Gameleira de Goiás'],
                ['id_city' => 2326, 'id_state' => 9, 'name' => ' Geriaçu'],
                ['id_city' => 2327, 'id_state' => 9, 'name' => ' Goialândia'],
                ['id_city' => 2328, 'id_state' => 9, 'name' => ' Goianápolis'],
                ['id_city' => 2329, 'id_state' => 9, 'name' => ' Goiandira'],
                ['id_city' => 2330, 'id_state' => 9, 'name' => ' Goianésia'],
                ['id_city' => 2331, 'id_state' => 9, 'name' => ' Goiânia'],
                ['id_city' => 2332, 'id_state' => 9, 'name' => ' Goianira'],
                ['id_city' => 2333, 'id_state' => 9, 'name' => ' Goiás'],
                ['id_city' => 2334, 'id_state' => 9, 'name' => ' Goiatuba'],
                ['id_city' => 2335, 'id_state' => 9, 'name' => ' Gouvelândia'],
                ['id_city' => 2336, 'id_state' => 9, 'name' => ' Guapó'],
                ['id_city' => 2337, 'id_state' => 9, 'name' => ' Guaraíta'],
                ['id_city' => 2338, 'id_state' => 9, 'name' => ' Guarani de Goiás'],
                ['id_city' => 2339, 'id_state' => 9, 'name' => ' Guarinos'],
                ['id_city' => 2340, 'id_state' => 9, 'name' => ' Heitoraí'],
                ['id_city' => 2341, 'id_state' => 9, 'name' => ' Hidrolândia'],
                ['id_city' => 2342, 'id_state' => 9, 'name' => ' Hidrolina'],
                ['id_city' => 2343, 'id_state' => 9, 'name' => ' Iaciara'],
                ['id_city' => 2344, 'id_state' => 9, 'name' => ' Inaciolândia'],
                ['id_city' => 2345, 'id_state' => 9, 'name' => ' Indiara'],
                ['id_city' => 2346, 'id_state' => 9, 'name' => ' Inhumas'],
                ['id_city' => 2347, 'id_state' => 9, 'name' => ' Interlândia'],
                ['id_city' => 2348, 'id_state' => 9, 'name' => ' Ipameri'],
                ['id_city' => 2349, 'id_state' => 9, 'name' => ' Iporá'],
                ['id_city' => 2350, 'id_state' => 9, 'name' => ' Israelândia'],
                ['id_city' => 2351, 'id_state' => 9, 'name' => ' Itaberaí'],
                ['id_city' => 2352, 'id_state' => 9, 'name' => ' Itaguaçu'],
                ['id_city' => 2353, 'id_state' => 9, 'name' => ' Itaguari'],
                ['id_city' => 2354, 'id_state' => 9, 'name' => ' Itaguaru'],
                ['id_city' => 2355, 'id_state' => 9, 'name' => ' Itajá'],
                ['id_city' => 2356, 'id_state' => 9, 'name' => ' Itapaci'],
                ['id_city' => 2357, 'id_state' => 9, 'name' => ' Itapirapuã'],
                ['id_city' => 2358, 'id_state' => 9, 'name' => ' Itapuranga'],
                ['id_city' => 2359, 'id_state' => 9, 'name' => ' Itarumã'],
                ['id_city' => 2360, 'id_state' => 9, 'name' => ' Itauçu'],
                ['id_city' => 2361, 'id_state' => 9, 'name' => ' Itumbiara'],
                ['id_city' => 2362, 'id_state' => 9, 'name' => ' Ivolândia'],
                ['id_city' => 2363, 'id_state' => 9, 'name' => ' Jacilândia'],
                ['id_city' => 2364, 'id_state' => 9, 'name' => ' Jandaia'],
                ['id_city' => 2365, 'id_state' => 9, 'name' => ' Jaraguá'],
                ['id_city' => 2366, 'id_state' => 9, 'name' => ' Jataí'],
                ['id_city' => 2367, 'id_state' => 9, 'name' => ' Jaupaci'],
                ['id_city' => 2368, 'id_state' => 9, 'name' => ' Jeroaquara'],
                ['id_city' => 2369, 'id_state' => 9, 'name' => ' Jesúpolis'],
                ['id_city' => 2370, 'id_state' => 9, 'name' => ' Joanápolis'],
                ['id_city' => 2371, 'id_state' => 9, 'name' => ' Joviânia'],
                ['id_city' => 2372, 'id_state' => 9, 'name' => ' Juscelino Kubitschek'],
                ['id_city' => 2373, 'id_state' => 9, 'name' => ' Jussara'],
                ['id_city' => 2374, 'id_state' => 9, 'name' => ' Lagoa do Bauzinho'],
                ['id_city' => 2375, 'id_state' => 9, 'name' => ' Lagolândia'],
                ['id_city' => 2376, 'id_state' => 9, 'name' => ' Leopoldo de Bulhões'],
                ['id_city' => 2377, 'id_state' => 9, 'name' => ' Lucilândia'],
                ['id_city' => 2378, 'id_state' => 9, 'name' => ' Luziânia'],
                ['id_city' => 2379, 'id_state' => 9, 'name' => ' Mairipotaba'],
                ['id_city' => 2380, 'id_state' => 9, 'name' => ' Mambaí'],
                ['id_city' => 2381, 'id_state' => 9, 'name' => ' Mara Rosa'],
                ['id_city' => 2382, 'id_state' => 9, 'name' => ' Marcianópolis'],
                ['id_city' => 2383, 'id_state' => 9, 'name' => ' Marzagão'],
                ['id_city' => 2384, 'id_state' => 9, 'name' => ' Matrinchã'],
                ['id_city' => 2385, 'id_state' => 9, 'name' => ' Maurilândia'],
                ['id_city' => 2386, 'id_state' => 9, 'name' => ' Meia Ponte'],
                ['id_city' => 2387, 'id_state' => 9, 'name' => ' Messianópolis'],
                ['id_city' => 2388, 'id_state' => 9, 'name' => ' Mimoso de Goiás'],
                ['id_city' => 2389, 'id_state' => 9, 'name' => ' Minaçu'],
                ['id_city' => 2390, 'id_state' => 9, 'name' => ' Mineiros'],
                ['id_city' => 2391, 'id_state' => 9, 'name' => ' Moiporá'],
                ['id_city' => 2392, 'id_state' => 9, 'name' => ' Monte Alegre de Goiás'],
                ['id_city' => 2393, 'id_state' => 9, 'name' => ' Montes Claros de Goiás'],
                ['id_city' => 2394, 'id_state' => 9, 'name' => ' Montividiu'],
                ['id_city' => 2395, 'id_state' => 9, 'name' => ' Montividiu do Norte'],
                ['id_city' => 2396, 'id_state' => 9, 'name' => ' Morrinhos'],
                ['id_city' => 2397, 'id_state' => 9, 'name' => ' Morro Agudo de Goiás'],
                ['id_city' => 2398, 'id_state' => 9, 'name' => ' Mossâmedes'],
                ['id_city' => 2399, 'id_state' => 9, 'name' => ' Mozarlândia'],
                ['id_city' => 2400, 'id_state' => 9, 'name' => ' Mundo Novo'],
                ['id_city' => 2401, 'id_state' => 9, 'name' => ' Mutunópolis'],
                ['id_city' => 2402, 'id_state' => 9, 'name' => ' Natinópolis'],
                ['id_city' => 2403, 'id_state' => 9, 'name' => ' Nazário'],
                ['id_city' => 2404, 'id_state' => 9, 'name' => ' Nerópolis'],
                ['id_city' => 2405, 'id_state' => 9, 'name' => ' Niquelândia'],
                ['id_city' => 2406, 'id_state' => 9, 'name' => ' Nova América'],
                ['id_city' => 2407, 'id_state' => 9, 'name' => ' Nova Aurora'],
                ['id_city' => 2408, 'id_state' => 9, 'name' => ' Nova Crixás'],
                ['id_city' => 2409, 'id_state' => 9, 'name' => ' Nova Glória'],
                ['id_city' => 2410, 'id_state' => 9, 'name' => ' Nova Iguaçu de Goiás'],
                ['id_city' => 2411, 'id_state' => 9, 'name' => ' Nova Roma'],
                ['id_city' => 2412, 'id_state' => 9, 'name' => ' Nova Veneza'],
                ['id_city' => 2413, 'id_state' => 9, 'name' => ' Novo Brasil'],
                ['id_city' => 2414, 'id_state' => 9, 'name' => ' Novo Gama'],
                ['id_city' => 2415, 'id_state' => 9, 'name' => ' Novo Planalto'],
                ['id_city' => 2416, 'id_state' => 9, 'name' => ' Olaria do Angico'],
                ['id_city' => 2417, 'id_state' => 9, 'name' => ' Olhos D Água'],
                ['id_city' => 2418, 'id_state' => 9, 'name' => ' Orizona'],
                ['id_city' => 2419, 'id_state' => 9, 'name' => ' Ouro Verde de Goiás'],
                ['id_city' => 2420, 'id_state' => 9, 'name' => ' Ouroana'],
                ['id_city' => 2421, 'id_state' => 9, 'name' => ' Ouvidor'],
                ['id_city' => 2422, 'id_state' => 9, 'name' => ' Padre Bernardo'],
                ['id_city' => 2423, 'id_state' => 9, 'name' => ' Palestina de Goiás'],
                ['id_city' => 2424, 'id_state' => 9, 'name' => ' Palmeiras de Goiás'],
                ['id_city' => 2425, 'id_state' => 9, 'name' => ' Palmelo'],
                ['id_city' => 2426, 'id_state' => 9, 'name' => ' Palminópolis'],
                ['id_city' => 2427, 'id_state' => 9, 'name' => ' Panamá'],
                ['id_city' => 2428, 'id_state' => 9, 'name' => ' Paranaiguara'],
                ['id_city' => 2429, 'id_state' => 9, 'name' => ' Paraúna'],
                ['id_city' => 2430, 'id_state' => 9, 'name' => ' Colinaçu'],
                ['id_city' => 2431, 'id_state' => 9, 'name' => ' Pedra Branca'],
                ['id_city' => 2432, 'id_state' => 9, 'name' => ' Perolândia'],
                ['id_city' => 2433, 'id_state' => 9, 'name' => ' Petrolina de Goiás'],
                ['id_city' => 2434, 'id_state' => 9, 'name' => ' Pilar de Goiás'],
                ['id_city' => 2435, 'id_state' => 9, 'name' => ' Piloândia'],
                ['id_city' => 2436, 'id_state' => 9, 'name' => ' Piracanjuba'],
                ['id_city' => 2437, 'id_state' => 9, 'name' => ' Piranhas'],
                ['id_city' => 2438, 'id_state' => 9, 'name' => ' Pirenópolis'],
                ['id_city' => 2439, 'id_state' => 9, 'name' => ' Pires Belo'],
                ['id_city' => 2440, 'id_state' => 9, 'name' => ' Pires do Rio'],
                ['id_city' => 2441, 'id_state' => 9, 'name' => ' Planaltina de Goiás'],
                ['id_city' => 2442, 'id_state' => 9, 'name' => ' Pontalina'],
                ['id_city' => 2443, 'id_state' => 9, 'name' => ' Porangatu'],
                ['id_city' => 2444, 'id_state' => 9, 'name' => ' Porteirão'],
                ['id_city' => 2445, 'id_state' => 9, 'name' => ' Portelândia'],
                ['id_city' => 2446, 'id_state' => 9, 'name' => ' Posse'],
                ['id_city' => 2447, 'id_state' => 9, 'name' => ' Posse D Abadia'],
                ['id_city' => 2448, 'id_state' => 9, 'name' => ' Professor Jamil'],
                ['id_city' => 2449, 'id_state' => 9, 'name' => ' Quirinópolis'],
                ['id_city' => 2450, 'id_state' => 9, 'name' => ' Registro do Araguaia'],
                ['id_city' => 2451, 'id_state' => 9, 'name' => ' Rianápolis'],
                ['id_city' => 2452, 'id_state' => 9, 'name' => ' Rio Quente'],
                ['id_city' => 2453, 'id_state' => 9, 'name' => ' Rio Verde'],
                ['id_city' => 2454, 'id_state' => 9, 'name' => ' Riverlândia'],
                ['id_city' => 2455, 'id_state' => 9, 'name' => ' Campo Limpo de Goiás'],
                ['id_city' => 2456, 'id_state' => 9, 'name' => ' Rosalândia'],
                ['id_city' => 2457, 'id_state' => 9, 'name' => ' Rubiataba'],
                ['id_city' => 2458, 'id_state' => 9, 'name' => ' Sanclerlândia'],
                ['id_city' => 2459, 'id_state' => 9, 'name' => ' Santa Bárbara de Goiás'],
                ['id_city' => 2460, 'id_state' => 9, 'name' => ' Santa Cruz das Lajes'],
                ['id_city' => 2461, 'id_state' => 9, 'name' => ' Santa Cruz de Goiás'],
                ['id_city' => 2462, 'id_state' => 9, 'name' => ' Santa Fé de Goiás'],
                ['id_city' => 2463, 'id_state' => 9, 'name' => ' Santa Helena de Goiás'],
                ['id_city' => 2464, 'id_state' => 9, 'name' => ' Santa Isabel'],
                ['id_city' => 2465, 'id_state' => 9, 'name' => ' Santa Rita do Araguaia'],
                ['id_city' => 2466, 'id_state' => 9, 'name' => ' Santa Rita do Novo Destino'],
                ['id_city' => 2467, 'id_state' => 9, 'name' => ' Santa Rosa'],
                ['id_city' => 2468, 'id_state' => 9, 'name' => ' Santa Rosa de Goiás'],
                ['id_city' => 2469, 'id_state' => 9, 'name' => ' Santa Tereza de Goiás'],
                ['id_city' => 2470, 'id_state' => 9, 'name' => ' Santa Terezinha de Goiás'],
                ['id_city' => 2471, 'id_state' => 9, 'name' => ' Santo Antônio da Barra'],
                ['id_city' => 2472, 'id_state' => 9, 'name' => ' Santo Antônio de Goiás'],
                ['id_city' => 2473, 'id_state' => 9, 'name' => ' Santo Antônio do Descoberto'],
                ['id_city' => 2474, 'id_state' => 9, 'name' => ' Santo Antônio do Rio Verde'],
                ['id_city' => 2475, 'id_state' => 9, 'name' => ' São Domingos'],
                ['id_city' => 2476, 'id_state' => 9, 'name' => ' São Francisco de Goiás'],
                ['id_city' => 2477, 'id_state' => 9, 'name' => ' São Gabriel de Goiás'],
                ['id_city' => 2478, 'id_state' => 9, 'name' => ' São João'],
                ['id_city' => 2479, 'id_state' => 9, 'name' => ' São João D Aliança'],
                ['id_city' => 2480, 'id_state' => 9, 'name' => ' São João da Paraúna'],
                ['id_city' => 2481, 'id_state' => 9, 'name' => ' São Luís de Montes Belos'],
                ['id_city' => 2482, 'id_state' => 9, 'name' => ' São Luiz do Norte'],
                ['id_city' => 2483, 'id_state' => 9, 'name' => ' São Luiz do Tocantins'],
                ['id_city' => 2484, 'id_state' => 9, 'name' => ' São Miguel do Araguaia'],
                ['id_city' => 2485, 'id_state' => 9, 'name' => ' São Miguel do Passa Quatro'],
                ['id_city' => 2486, 'id_state' => 9, 'name' => ' São Patrício'],
                ['id_city' => 2487, 'id_state' => 9, 'name' => ' São Sebastião do Rio Claro'],
                ['id_city' => 2488, 'id_state' => 9, 'name' => ' São Simão'],
                ['id_city' => 2489, 'id_state' => 9, 'name' => ' São Vicente'],
                ['id_city' => 2490, 'id_state' => 9, 'name' => ' Sarandi'],
                ['id_city' => 2491, 'id_state' => 9, 'name' => ' Senador Canedo'],
                ['id_city' => 2492, 'id_state' => 9, 'name' => ' Serra Dourada'],
                ['id_city' => 2493, 'id_state' => 9, 'name' => ' Serranópolis'],
                ['id_city' => 2494, 'id_state' => 9, 'name' => ' Silvânia'],
                ['id_city' => 2495, 'id_state' => 9, 'name' => ' Simolândia'],
                ['id_city' => 2496, 'id_state' => 9, 'name' => ' Sítio D Abadia'],
                ['id_city' => 2497, 'id_state' => 9, 'name' => ' Sousânia'],
                ['id_city' => 2498, 'id_state' => 9, 'name' => ' Taquaral de Goiás'],
                ['id_city' => 2499, 'id_state' => 9, 'name' => ' Taveira'],
                ['id_city' => 2500, 'id_state' => 9, 'name' => ' Teresina de Goiás'],
                ['id_city' => 2501, 'id_state' => 9, 'name' => ' Terezópolis de Goiás'],
                ['id_city' => 2502, 'id_state' => 9, 'name' => ' Lagoa Santa'],
                ['id_city' => 2503, 'id_state' => 9, 'name' => ' Três Ranchos'],
                ['id_city' => 2504, 'id_state' => 9, 'name' => ' Trindade'],
                ['id_city' => 2505, 'id_state' => 9, 'name' => ' Trombas'],
                ['id_city' => 2506, 'id_state' => 9, 'name' => ' Tupiracaba'],
                ['id_city' => 2507, 'id_state' => 9, 'name' => ' Turvânia'],
                ['id_city' => 2508, 'id_state' => 9, 'name' => ' Turvelândia'],
                ['id_city' => 2509, 'id_state' => 9, 'name' => ' Uirapuru'],
                ['id_city' => 2510, 'id_state' => 9, 'name' => ' Uruaçu'],
                ['id_city' => 2511, 'id_state' => 9, 'name' => ' Uruana'],
                ['id_city' => 2512, 'id_state' => 9, 'name' => ' Uruita'],
                ['id_city' => 2513, 'id_state' => 9, 'name' => ' Urutaí'],
                ['id_city' => 2514, 'id_state' => 9, 'name' => ' Uvá'],
                ['id_city' => 2515, 'id_state' => 9, 'name' => ' Valdelândia'],
                ['id_city' => 2516, 'id_state' => 9, 'name' => ' Valparaíso de Goiás'],
                ['id_city' => 2517, 'id_state' => 9, 'name' => ' Varjão'],
                ['id_city' => 2518, 'id_state' => 9, 'name' => ' Vianópolis'],
                ['id_city' => 2519, 'id_state' => 9, 'name' => ' Vicentinópolis'],
                ['id_city' => 2520, 'id_state' => 9, 'name' => ' Vila Boa'],
                ['id_city' => 2521, 'id_state' => 9, 'name' => ' Vila Propício'],
                ['id_city' => 2522, 'id_state' => 9, 'name' => ' Vila Sertaneja'],
                ['id_city' => 2523, 'id_state' => 10, 'name' => ' Açailândia'],
                ['id_city' => 2524, 'id_state' => 10, 'name' => ' Afonso Cunha'],
                ['id_city' => 2525, 'id_state' => 10, 'name' => ' Água Doce do Maranhão'],
                ['id_city' => 2526, 'id_state' => 10, 'name' => ' Alcântara'],
                ['id_city' => 2527, 'id_state' => 10, 'name' => ' Aldeias Altas'],
                ['id_city' => 2528, 'id_state' => 10, 'name' => ' Altamira do Maranhão'],
                ['id_city' => 2529, 'id_state' => 10, 'name' => ' Alto Alegre do Maranhão'],
                ['id_city' => 2530, 'id_state' => 10, 'name' => ' Alto Alegre do Pindaré'],
                ['id_city' => 2531, 'id_state' => 10, 'name' => ' Alto Parnaíba'],
                ['id_city' => 2532, 'id_state' => 10, 'name' => ' Amapá do Maranhão'],
                ['id_city' => 2533, 'id_state' => 10, 'name' => ' Amarante do Maranhão'],
                ['id_city' => 2534, 'id_state' => 10, 'name' => ' Anajatuba'],
                ['id_city' => 2535, 'id_state' => 10, 'name' => ' Anapurus'],
                ['id_city' => 2536, 'id_state' => 10, 'name' => ' Anil'],
                ['id_city' => 2537, 'id_state' => 10, 'name' => ' Apicum-Açu'],
                ['id_city' => 2538, 'id_state' => 10, 'name' => ' Araguanã'],
                ['id_city' => 2539, 'id_state' => 10, 'name' => ' Araióses'],
                ['id_city' => 2540, 'id_state' => 10, 'name' => ' Arame'],
                ['id_city' => 2541, 'id_state' => 10, 'name' => ' Arari'],
                ['id_city' => 2542, 'id_state' => 10, 'name' => ' Aurizona'],
                ['id_city' => 2543, 'id_state' => 10, 'name' => ' Axixá'],
                ['id_city' => 2544, 'id_state' => 10, 'name' => ' Bacabal'],
                ['id_city' => 2545, 'id_state' => 10, 'name' => ' Bacabeira'],
                ['id_city' => 2546, 'id_state' => 10, 'name' => ' Bacatuba'],
                ['id_city' => 2547, 'id_state' => 10, 'name' => ' Bacuri'],
                ['id_city' => 2548, 'id_state' => 10, 'name' => ' Bacurituba'],
                ['id_city' => 2549, 'id_state' => 10, 'name' => ' Balsas'],
                ['id_city' => 2550, 'id_state' => 10, 'name' => ' Barão de Grajaú'],
                ['id_city' => 2551, 'id_state' => 10, 'name' => ' Barão de Tromai'],
                ['id_city' => 2552, 'id_state' => 10, 'name' => ' Barra do Corda'],
                ['id_city' => 2553, 'id_state' => 10, 'name' => ' Barreirinhas'],
                ['id_city' => 2554, 'id_state' => 10, 'name' => ' Barro Duro'],
                ['id_city' => 2555, 'id_state' => 10, 'name' => ' Bela Vista do Maranhão'],
                ['id_city' => 2556, 'id_state' => 10, 'name' => ' Belágua'],
                ['id_city' => 2557, 'id_state' => 10, 'name' => ' Benedito Leite'],
                ['id_city' => 2558, 'id_state' => 10, 'name' => ' Bequimão'],
                ['id_city' => 2559, 'id_state' => 10, 'name' => ' Bernardo do Mearim'],
                ['id_city' => 2560, 'id_state' => 10, 'name' => ' Boa Vista do Gurupi'],
                ['id_city' => 2561, 'id_state' => 10, 'name' => ' Boa Vista do Pindaré'],
                ['id_city' => 2562, 'id_state' => 10, 'name' => ' Bom Jardim'],
                ['id_city' => 2563, 'id_state' => 10, 'name' => ' Bom Jesus das Selvas'],
                ['id_city' => 2564, 'id_state' => 10, 'name' => ' Bom Lugar'],
                ['id_city' => 2565, 'id_state' => 10, 'name' => ' Bonfim do Arari'],
                ['id_city' => 2566, 'id_state' => 10, 'name' => ' Brejo'],
                ['id_city' => 2567, 'id_state' => 10, 'name' => ' Brejo de Areia'],
                ['id_city' => 2568, 'id_state' => 10, 'name' => ' Brejo de São Félix'],
                ['id_city' => 2569, 'id_state' => 10, 'name' => ' Buriti'],
                ['id_city' => 2570, 'id_state' => 10, 'name' => ' Buriti Bravo'],
                ['id_city' => 2571, 'id_state' => 10, 'name' => ' Buriti Cortado'],
                ['id_city' => 2572, 'id_state' => 10, 'name' => ' Buriticupu'],
                ['id_city' => 2573, 'id_state' => 10, 'name' => ' Buritirana'],
                ['id_city' => 2574, 'id_state' => 10, 'name' => ' Cachoeira Grande'],
                ['id_city' => 2575, 'id_state' => 10, 'name' => ' Cajapió'],
                ['id_city' => 2576, 'id_state' => 10, 'name' => ' Cajari'],
                ['id_city' => 2577, 'id_state' => 10, 'name' => ' Campestre do Maranhão'],
                ['id_city' => 2578, 'id_state' => 10, 'name' => ' Cândido Mendes'],
                ['id_city' => 2579, 'id_state' => 10, 'name' => ' Cantanhede'],
                ['id_city' => 2580, 'id_state' => 10, 'name' => ' Capinzal do Norte'],
                ['id_city' => 2581, 'id_state' => 10, 'name' => ' Caraíba do Norte'],
                ['id_city' => 2582, 'id_state' => 10, 'name' => ' Carolina'],
                ['id_city' => 2583, 'id_state' => 10, 'name' => ' Carutapera'],
                ['id_city' => 2584, 'id_state' => 10, 'name' => ' Caxias'],
                ['id_city' => 2585, 'id_state' => 10, 'name' => ' Cedral'],
                ['id_city' => 2586, 'id_state' => 10, 'name' => ' Central do Maranhão'],
                ['id_city' => 2587, 'id_state' => 10, 'name' => ' Centro do Guilherme'],
                ['id_city' => 2588, 'id_state' => 10, 'name' => ' Centro Novo do Maranhão'],
                ['id_city' => 2589, 'id_state' => 10, 'name' => ' Chapadinha'],
                ['id_city' => 2590, 'id_state' => 10, 'name' => ' Cidelândia'],
                ['id_city' => 2591, 'id_state' => 10, 'name' => ' Codó'],
                ['id_city' => 2592, 'id_state' => 10, 'name' => ' Codozinho'],
                ['id_city' => 2593, 'id_state' => 10, 'name' => ' Coelho Neto'],
                ['id_city' => 2594, 'id_state' => 10, 'name' => ' Colinas'],
                ['id_city' => 2595, 'id_state' => 10, 'name' => ' Conceição do Lago-Açu'],
                ['id_city' => 2596, 'id_state' => 10, 'name' => ' Coroatá'],
                ['id_city' => 2597, 'id_state' => 10, 'name' => ' Curupa'],
                ['id_city' => 2598, 'id_state' => 10, 'name' => ' Cururupu'],
                ['id_city' => 2599, 'id_state' => 10, 'name' => ' Curva Grande'],
                ['id_city' => 2600, 'id_state' => 10, 'name' => ' Custódio Lima'],
                ['id_city' => 2601, 'id_state' => 10, 'name' => ' Davinópolis'],
                ['id_city' => 2602, 'id_state' => 10, 'name' => ' Dom Pedro'],
                ['id_city' => 2603, 'id_state' => 10, 'name' => ' Duque Bacelar'],
                ['id_city' => 2604, 'id_state' => 10, 'name' => ' Esperantinópolis'],
                ['id_city' => 2605, 'id_state' => 10, 'name' => ' Estandarte'],
                ['id_city' => 2606, 'id_state' => 10, 'name' => ' Estreito'],
                ['id_city' => 2607, 'id_state' => 10, 'name' => ' Feira Nova do Maranhão'],
                ['id_city' => 2608, 'id_state' => 10, 'name' => ' Fernando Falcão'],
                ['id_city' => 2609, 'id_state' => 10, 'name' => ' Formosa da Serra Negra'],
                ['id_city' => 2610, 'id_state' => 10, 'name' => ' Fortaleza dos Nogueiras'],
                ['id_city' => 2611, 'id_state' => 10, 'name' => ' Fortuna'],
                ['id_city' => 2612, 'id_state' => 10, 'name' => ' Frecheiras'],
                ['id_city' => 2613, 'id_state' => 10, 'name' => ' Godofredo Viana'],
                ['id_city' => 2614, 'id_state' => 10, 'name' => ' Gonçalves Dias'],
                ['id_city' => 2615, 'id_state' => 10, 'name' => ' Governador Archer'],
                ['id_city' => 2616, 'id_state' => 10, 'name' => ' Governador Edson Lobão'],
                ['id_city' => 2617, 'id_state' => 10, 'name' => ' Governador Eugênio Barros'],
                ['id_city' => 2618, 'id_state' => 10, 'name' => ' Governador Luiz Rocha'],
                ['id_city' => 2619, 'id_state' => 10, 'name' => ' Governador Newton Bello'],
                ['id_city' => 2620, 'id_state' => 10, 'name' => ' Governador Nunes Freire'],
                ['id_city' => 2621, 'id_state' => 10, 'name' => ' Graça Aranha'],
                ['id_city' => 2622, 'id_state' => 10, 'name' => ' Grajaú'],
                ['id_city' => 2623, 'id_state' => 10, 'name' => ' Guimarães'],
                ['id_city' => 2624, 'id_state' => 10, 'name' => ' Humberto de Campos'],
                ['id_city' => 2625, 'id_state' => 10, 'name' => ' Ibipira'],
                ['id_city' => 2626, 'id_state' => 10, 'name' => ' Icatu'],
                ['id_city' => 2627, 'id_state' => 10, 'name' => ' Igarapé do Meio'],
                ['id_city' => 2628, 'id_state' => 10, 'name' => ' Igarapé Grande'],
                ['id_city' => 2629, 'id_state' => 10, 'name' => ' Imperatriz'],
                ['id_city' => 2630, 'id_state' => 10, 'name' => ' Itaipava do Grajaú'],
                ['id_city' => 2631, 'id_state' => 10, 'name' => ' Itamataré'],
                ['id_city' => 2632, 'id_state' => 10, 'name' => ' Itapecuru Mirim'],
                ['id_city' => 2633, 'id_state' => 10, 'name' => ' Itapera'],
                ['id_city' => 2634, 'id_state' => 10, 'name' => ' Itinga do Maranhão'],
                ['id_city' => 2635, 'id_state' => 10, 'name' => ' Jatobá'],
                ['id_city' => 2636, 'id_state' => 10, 'name' => ' Jenipapo dos Vieiras'],
                ['id_city' => 2637, 'id_state' => 10, 'name' => ' João Lisboa'],
                ['id_city' => 2638, 'id_state' => 10, 'name' => ' Joselândia'],
                ['id_city' => 2639, 'id_state' => 10, 'name' => ' Junco do Maranhão'],
                ['id_city' => 2640, 'id_state' => 10, 'name' => ' Lago da Pedra'],
                ['id_city' => 2641, 'id_state' => 10, 'name' => ' Lago do Junco'],
                ['id_city' => 2642, 'id_state' => 10, 'name' => ' Lago dos Rodrigues'],
                ['id_city' => 2643, 'id_state' => 10, 'name' => ' Lago Verde'],
                ['id_city' => 2644, 'id_state' => 10, 'name' => ' Lagoa do Mato'],
                ['id_city' => 2645, 'id_state' => 10, 'name' => ' Lagoa Grande do Maranhão'],
                ['id_city' => 2646, 'id_state' => 10, 'name' => ' Lajeado Novo'],
                ['id_city' => 2647, 'id_state' => 10, 'name' => ' Lapela'],
                ['id_city' => 2648, 'id_state' => 10, 'name' => ' Leandro'],
                ['id_city' => 2649, 'id_state' => 10, 'name' => ' Lima Campos'],
                ['id_city' => 2650, 'id_state' => 10, 'name' => ' Loreto'],
                ['id_city' => 2651, 'id_state' => 10, 'name' => ' Luís Domingues'],
                ['id_city' => 2652, 'id_state' => 10, 'name' => ' Magalhães de Almeida'],
                ['id_city' => 2653, 'id_state' => 10, 'name' => ' Maioba'],
                ['id_city' => 2654, 'id_state' => 10, 'name' => ' Maracaçumé'],
                ['id_city' => 2655, 'id_state' => 10, 'name' => ' Marajá do Sena'],
                ['id_city' => 2656, 'id_state' => 10, 'name' => ' Maranhãozinho'],
                ['id_city' => 2657, 'id_state' => 10, 'name' => ' Marianópolis'],
                ['id_city' => 2658, 'id_state' => 10, 'name' => ' Mata'],
                ['id_city' => 2659, 'id_state' => 10, 'name' => ' Mata Roma'],
                ['id_city' => 2660, 'id_state' => 10, 'name' => ' Matinha'],
                ['id_city' => 2661, 'id_state' => 10, 'name' => ' Matões'],
                ['id_city' => 2662, 'id_state' => 10, 'name' => ' Matões do Norte'],
                ['id_city' => 2663, 'id_state' => 10, 'name' => ' Milagres do Maranhão'],
                ['id_city' => 2664, 'id_state' => 10, 'name' => ' Mirador'],
                ['id_city' => 2665, 'id_state' => 10, 'name' => ' Miranda do Norte'],
                ['id_city' => 2666, 'id_state' => 10, 'name' => ' Mirinzal'],
                ['id_city' => 2667, 'id_state' => 10, 'name' => ' Monção'],
                ['id_city' => 2668, 'id_state' => 10, 'name' => ' Montes Altos'],
                ['id_city' => 2669, 'id_state' => 10, 'name' => ' Morros'],
                ['id_city' => 2670, 'id_state' => 10, 'name' => ' Nina Rodrigues'],
                ['id_city' => 2671, 'id_state' => 10, 'name' => ' Nova Colinas'],
                ['id_city' => 2672, 'id_state' => 10, 'name' => ' Nova Iorque'],
                ['id_city' => 2673, 'id_state' => 10, 'name' => ' Nova Olinda do Maranhão'],
                ['id_city' => 2674, 'id_state' => 10, 'name' => ' Olho D Água das Cunhãs'],
                ['id_city' => 2675, 'id_state' => 10, 'name' => ' Olinda Nova do Maranhão'],
                ['id_city' => 2676, 'id_state' => 10, 'name' => ' Paço do Lumiar'],
                ['id_city' => 2677, 'id_state' => 10, 'name' => ' Palmeirândia'],
                ['id_city' => 2678, 'id_state' => 10, 'name' => ' Papagaio'],
                ['id_city' => 2679, 'id_state' => 10, 'name' => ' Paraibano'],
                ['id_city' => 2680, 'id_state' => 10, 'name' => ' Parnarama'],
                ['id_city' => 2681, 'id_state' => 10, 'name' => ' Passagem Franca'],
                ['id_city' => 2682, 'id_state' => 10, 'name' => ' Pastos Bons'],
                ['id_city' => 2683, 'id_state' => 10, 'name' => ' Paulino Neves'],
                ['id_city' => 2684, 'id_state' => 10, 'name' => ' Paulo Ramos'],
                ['id_city' => 2685, 'id_state' => 10, 'name' => ' Pedreiras'],
                ['id_city' => 2686, 'id_state' => 10, 'name' => ' Pedro do Rosário'],
                ['id_city' => 2687, 'id_state' => 10, 'name' => ' Penalva'],
                ['id_city' => 2688, 'id_state' => 10, 'name' => ' Peri Mirim'],
                ['id_city' => 2689, 'id_state' => 10, 'name' => ' Peritoró'],
                ['id_city' => 2690, 'id_state' => 10, 'name' => ' Pimentel'],
                ['id_city' => 2691, 'id_state' => 10, 'name' => ' Pindaré Mirim'],
                ['id_city' => 2692, 'id_state' => 10, 'name' => ' Pinheiro'],
                ['id_city' => 2693, 'id_state' => 10, 'name' => ' Pio XII'],
                ['id_city' => 2694, 'id_state' => 10, 'name' => ' Pirapemas'],
                ['id_city' => 2695, 'id_state' => 10, 'name' => ' Poção de Pedras'],
                ['id_city' => 2696, 'id_state' => 10, 'name' => ' Porto das Gabarras'],
                ['id_city' => 2697, 'id_state' => 10, 'name' => ' Porto Franco'],
                ['id_city' => 2698, 'id_state' => 10, 'name' => ' Porto Rico do Maranhão'],
                ['id_city' => 2699, 'id_state' => 10, 'name' => ' Presidente Dutra'],
                ['id_city' => 2700, 'id_state' => 10, 'name' => ' Presidente Juscelino'],
                ['id_city' => 2701, 'id_state' => 10, 'name' => ' Presidente Médici'],
                ['id_city' => 2702, 'id_state' => 10, 'name' => ' Presidente Sarney'],
                ['id_city' => 2703, 'id_state' => 10, 'name' => ' Presidente Vargas'],
                ['id_city' => 2704, 'id_state' => 10, 'name' => ' Primeira Cruz'],
                ['id_city' => 2705, 'id_state' => 10, 'name' => ' Raposa'],
                ['id_city' => 2706, 'id_state' => 10, 'name' => ' Resplandes'],
                ['id_city' => 2707, 'id_state' => 10, 'name' => ' Riachão'],
                ['id_city' => 2708, 'id_state' => 10, 'name' => ' Ribamar Fiquene'],
                ['id_city' => 2709, 'id_state' => 10, 'name' => ' Ribeirão Azul'],
                ['id_city' => 2710, 'id_state' => 10, 'name' => ' Rocado'],
                ['id_city' => 2711, 'id_state' => 10, 'name' => ' Roque'],
                ['id_city' => 2712, 'id_state' => 10, 'name' => ' Rosário'],
                ['id_city' => 2713, 'id_state' => 10, 'name' => ' Sambaíba'],
                ['id_city' => 2714, 'id_state' => 10, 'name' => ' Santa Filomena do Maranhão'],
                ['id_city' => 2715, 'id_state' => 10, 'name' => ' Santa Helena'],
                ['id_city' => 2716, 'id_state' => 10, 'name' => ' Santa Inês'],
                ['id_city' => 2717, 'id_state' => 10, 'name' => ' Santa Luzia'],
                ['id_city' => 2718, 'id_state' => 10, 'name' => ' Santa Luzia do Paruá'],
                ['id_city' => 2719, 'id_state' => 10, 'name' => ' Santa Quitéria do Maranhão'],
                ['id_city' => 2720, 'id_state' => 10, 'name' => ' Santa Rita'],
                ['id_city' => 2721, 'id_state' => 10, 'name' => ' Santana do Maranhão'],
                ['id_city' => 2722, 'id_state' => 10, 'name' => ' Santo Amaro'],
                ['id_city' => 2723, 'id_state' => 10, 'name' => ' Santo Antônio dos Lopes'],
                ['id_city' => 2724, 'id_state' => 10, 'name' => ' São Benedito do Rio Preto'],
                ['id_city' => 2725, 'id_state' => 10, 'name' => ' São Bento'],
                ['id_city' => 2726, 'id_state' => 10, 'name' => ' São Bernardo'],
                ['id_city' => 2727, 'id_state' => 10, 'name' => ' São Domingos do Azeitão'],
                ['id_city' => 2728, 'id_state' => 10, 'name' => ' São Domingos do Maranhão'],
                ['id_city' => 2729, 'id_state' => 10, 'name' => ' São Félix de Balsas'],
                ['id_city' => 2730, 'id_state' => 10, 'name' => ' São Francisco do Brejão'],
                ['id_city' => 2731, 'id_state' => 10, 'name' => ' São Francisco do Maranhão'],
                ['id_city' => 2732, 'id_state' => 10, 'name' => ' São João Batista'],
                ['id_city' => 2733, 'id_state' => 10, 'name' => ' São João de Cortes'],
                ['id_city' => 2734, 'id_state' => 10, 'name' => ' São João do Carú'],
                ['id_city' => 2735, 'id_state' => 10, 'name' => ' São João do Paraíso'],
                ['id_city' => 2736, 'id_state' => 10, 'name' => ' São João do Sóter'],
                ['id_city' => 2737, 'id_state' => 10, 'name' => ' São João dos Patos'],
                ['id_city' => 2738, 'id_state' => 10, 'name' => ' São Joaquim dos Melos'],
                ['id_city' => 2739, 'id_state' => 10, 'name' => ' São José de Ribamar'],
                ['id_city' => 2740, 'id_state' => 10, 'name' => ' São José dos Basílios'],
                ['id_city' => 2741, 'id_state' => 10, 'name' => ' São Luís'],
                ['id_city' => 2742, 'id_state' => 10, 'name' => ' São Luís Gonzaga do Maranhão'],
                ['id_city' => 2743, 'id_state' => 10, 'name' => ' São Mateus do Maranhão'],
                ['id_city' => 2744, 'id_state' => 10, 'name' => ' São Pedro da Água Branca'],
                ['id_city' => 2745, 'id_state' => 10, 'name' => ' São Pedro dos Crentes'],
                ['id_city' => 2746, 'id_state' => 10, 'name' => ' São Raimundo das Mangabeiras'],
                ['id_city' => 2747, 'id_state' => 10, 'name' => ' São Raimundo de Codó'],
                ['id_city' => 2748, 'id_state' => 10, 'name' => ' São Raimundo do Doca Bezerra'],
                ['id_city' => 2749, 'id_state' => 10, 'name' => ' São Roberto'],
                ['id_city' => 2750, 'id_state' => 10, 'name' => ' São Vicente Ferrer'],
                ['id_city' => 2751, 'id_state' => 10, 'name' => ' Satubinha'],
                ['id_city' => 2752, 'id_state' => 10, 'name' => ' Senador Alexandre Costa'],
                ['id_city' => 2753, 'id_state' => 10, 'name' => ' Senador La Roque'],
                ['id_city' => 2754, 'id_state' => 10, 'name' => ' Serrano do Maranhão'],
                ['id_city' => 2755, 'id_state' => 10, 'name' => ' Sítio Novo'],
                ['id_city' => 2756, 'id_state' => 10, 'name' => ' Sucupira do Norte'],
                ['id_city' => 2757, 'id_state' => 10, 'name' => ' Sucupira do Riachão'],
                ['id_city' => 2758, 'id_state' => 10, 'name' => ' Tasso Fragoso'],
                ['id_city' => 2759, 'id_state' => 10, 'name' => ' Timbiras'],
                ['id_city' => 2760, 'id_state' => 10, 'name' => ' Timon'],
                ['id_city' => 2761, 'id_state' => 10, 'name' => ' Trizidela do Vale'],
                ['id_city' => 2762, 'id_state' => 10, 'name' => ' Tufilândia'],
                ['id_city' => 2763, 'id_state' => 10, 'name' => ' Tuntum'],
                ['id_city' => 2764, 'id_state' => 10, 'name' => ' Turiaçu'],
                ['id_city' => 2765, 'id_state' => 10, 'name' => ' Turilândia'],
                ['id_city' => 2766, 'id_state' => 10, 'name' => ' Tutóia'],
                ['id_city' => 2767, 'id_state' => 10, 'name' => ' Urbano Santos'],
                ['id_city' => 2768, 'id_state' => 10, 'name' => ' Vargem Grande'],
                ['id_city' => 2769, 'id_state' => 10, 'name' => ' Viana'],
                ['id_city' => 2770, 'id_state' => 10, 'name' => ' Vila Nova dos Martírios'],
                ['id_city' => 2771, 'id_state' => 10, 'name' => ' Vitória do Mearim'],
                ['id_city' => 2772, 'id_state' => 10, 'name' => ' Vitorino Freire'],
                ['id_city' => 2773, 'id_state' => 10, 'name' => ' Zé Doca'],
                ['id_city' => 2774, 'id_state' => 13, 'name' => ' Abadia dos Dourados'],
                ['id_city' => 2775, 'id_state' => 13, 'name' => ' Abaeté'],
                ['id_city' => 2776, 'id_state' => 13, 'name' => ' Abaeté dos Mendes'],
                ['id_city' => 2777, 'id_state' => 13, 'name' => ' Abaíba'],
                ['id_city' => 2778, 'id_state' => 13, 'name' => ' Abre Campo'],
                ['id_city' => 2779, 'id_state' => 13, 'name' => ' Abreus'],
                ['id_city' => 2780, 'id_state' => 13, 'name' => ' Acaiaca'],
                ['id_city' => 2781, 'id_state' => 13, 'name' => ' Açucena'],
                ['id_city' => 2782, 'id_state' => 13, 'name' => ' Acuruí'],
                ['id_city' => 2783, 'id_state' => 13, 'name' => ' Adão Colares'],
                ['id_city' => 2784, 'id_state' => 13, 'name' => ' Água Boa'],
                ['id_city' => 2785, 'id_state' => 13, 'name' => ' Água Branca de Minas'],
                ['id_city' => 2786, 'id_state' => 13, 'name' => ' Água Comprida'],
                ['id_city' => 2787, 'id_state' => 13, 'name' => ' Água Viva'],
                ['id_city' => 2788, 'id_state' => 13, 'name' => ' Aguanil'],
                ['id_city' => 2789, 'id_state' => 13, 'name' => ' Águas de Araxá'],
                ['id_city' => 2790, 'id_state' => 13, 'name' => ' Águas de Contendas'],
                ['id_city' => 2791, 'id_state' => 13, 'name' => ' Águas Férreas'],
                ['id_city' => 2792, 'id_state' => 13, 'name' => ' Águas Formosas'],
                ['id_city' => 2793, 'id_state' => 13, 'name' => ' Águas Vermelhas'],
                ['id_city' => 2794, 'id_state' => 13, 'name' => ' Aimorés'],
                ['id_city' => 2795, 'id_state' => 13, 'name' => ' Aiuruoca'],
                ['id_city' => 2796, 'id_state' => 13, 'name' => ' Alagoa'],
                ['id_city' => 2797, 'id_state' => 13, 'name' => ' Albertina'],
                ['id_city' => 2798, 'id_state' => 13, 'name' => ' Alberto Isaacson'],
                ['id_city' => 2799, 'id_state' => 13, 'name' => ' Albertos'],
                ['id_city' => 2800, 'id_state' => 13, 'name' => ' Aldeia'],
                ['id_city' => 2801, 'id_state' => 13, 'name' => ' Alegre'],
                ['id_city' => 2802, 'id_state' => 13, 'name' => ' Alegria'],
                ['id_city' => 2803, 'id_state' => 13, 'name' => ' Além Paraíba'],
                ['id_city' => 2804, 'id_state' => 13, 'name' => ' Alexandrita'],
                ['id_city' => 2805, 'id_state' => 13, 'name' => ' Alfenas'],
                ['id_city' => 2806, 'id_state' => 13, 'name' => ' Alfredo Vasconcelos'],
                ['id_city' => 2807, 'id_state' => 13, 'name' => ' Almeida'],
                ['id_city' => 2808, 'id_state' => 13, 'name' => ' Almenara'],
                ['id_city' => 2809, 'id_state' => 13, 'name' => ' Alpercata'],
                ['id_city' => 2810, 'id_state' => 13, 'name' => ' Alpinópolis'],
                ['id_city' => 2811, 'id_state' => 13, 'name' => ' Alterosa'],
                ['id_city' => 2812, 'id_state' => 13, 'name' => ' Alto Caparaó'],
                ['id_city' => 2813, 'id_state' => 13, 'name' => ' Alto Capim'],
                ['id_city' => 2814, 'id_state' => 13, 'name' => ' Alto de Santa Helena'],
                ['id_city' => 2815, 'id_state' => 13, 'name' => ' Alto Jequitibá'],
                ['id_city' => 2816, 'id_state' => 13, 'name' => ' Alto Maranhão'],
                ['id_city' => 2817, 'id_state' => 13, 'name' => ' Alto Rio Doce'],
                ['id_city' => 2818, 'id_state' => 13, 'name' => ' Altolândia'],
                ['id_city' => 2819, 'id_state' => 13, 'name' => ' Alvação'],
                ['id_city' => 2820, 'id_state' => 13, 'name' => ' Alvarenga'],
                ['id_city' => 2821, 'id_state' => 13, 'name' => ' Alvinópolis'],
                ['id_city' => 2822, 'id_state' => 13, 'name' => ' Alvorada'],
                ['id_city' => 2823, 'id_state' => 13, 'name' => ' Alvorada de Minas'],
                ['id_city' => 2824, 'id_state' => 13, 'name' => ' Amanda'],
                ['id_city' => 2825, 'id_state' => 13, 'name' => ' Amanhece'],
                ['id_city' => 2826, 'id_state' => 13, 'name' => ' Amarantina'],
                ['id_city' => 2827, 'id_state' => 13, 'name' => ' Amparo da Serra'],
                ['id_city' => 2828, 'id_state' => 13, 'name' => ' Andiroba'],
                ['id_city' => 2829, 'id_state' => 13, 'name' => ' Andradas'],
                ['id_city' => 2830, 'id_state' => 13, 'name' => ' Andrelândia'],
                ['id_city' => 2831, 'id_state' => 13, 'name' => ' Andrequicé'],
                ['id_city' => 2832, 'id_state' => 13, 'name' => ' Angaturama'],
                ['id_city' => 2833, 'id_state' => 13, 'name' => ' Angelândia'],
                ['id_city' => 2834, 'id_state' => 13, 'name' => ' Angicos de Minas'],
                ['id_city' => 2835, 'id_state' => 13, 'name' => ' Angueretá'],
                ['id_city' => 2836, 'id_state' => 13, 'name' => ' Angustura'],
                ['id_city' => 2837, 'id_state' => 13, 'name' => ' Antônio Carlos'],
                ['id_city' => 2838, 'id_state' => 13, 'name' => ' Antônio Dias'],
                ['id_city' => 2839, 'id_state' => 13, 'name' => ' Antônio dos Santos'],
                ['id_city' => 2840, 'id_state' => 13, 'name' => ' Antônio Ferreira'],
                ['id_city' => 2841, 'id_state' => 13, 'name' => ' Antônio Pereira'],
                ['id_city' => 2842, 'id_state' => 13, 'name' => ' Antônio Prado de Minas'],
                ['id_city' => 2843, 'id_state' => 13, 'name' => ' Antunes'],
                ['id_city' => 2844, 'id_state' => 13, 'name' => ' Aparecida de Minas'],
                ['id_city' => 2845, 'id_state' => 13, 'name' => ' Araçaí'],
                ['id_city' => 2846, 'id_state' => 13, 'name' => ' Aracati de Minas'],
                ['id_city' => 2847, 'id_state' => 13, 'name' => ' Aracitaba'],
                ['id_city' => 2848, 'id_state' => 13, 'name' => ' Araçuaí'],
                ['id_city' => 2849, 'id_state' => 13, 'name' => ' Araguari'],
                ['id_city' => 2850, 'id_state' => 13, 'name' => ' Aramirim'],
                ['id_city' => 2851, 'id_state' => 13, 'name' => ' Aranha'],
                ['id_city' => 2852, 'id_state' => 13, 'name' => ' Arantina'],
                ['id_city' => 2853, 'id_state' => 13, 'name' => ' Araponga'],
                ['id_city' => 2854, 'id_state' => 13, 'name' => ' Araporã'],
                ['id_city' => 2855, 'id_state' => 13, 'name' => ' Arapuá'],
                ['id_city' => 2856, 'id_state' => 13, 'name' => ' Araújos'],
                ['id_city' => 2857, 'id_state' => 13, 'name' => ' Araúna'],
                ['id_city' => 2858, 'id_state' => 13, 'name' => ' Araxá'],
                ['id_city' => 2859, 'id_state' => 13, 'name' => ' Arcângelo'],
                ['id_city' => 2860, 'id_state' => 13, 'name' => ' Arceburgo'],
                ['id_city' => 2861, 'id_state' => 13, 'name' => ' Arcos'],
                ['id_city' => 2862, 'id_state' => 13, 'name' => ' Areado'],
                ['id_city' => 2863, 'id_state' => 13, 'name' => ' Argenita'],
                ['id_city' => 2864, 'id_state' => 13, 'name' => ' Argirita'],
                ['id_city' => 2865, 'id_state' => 13, 'name' => ' Aricanduva'],
                ['id_city' => 2866, 'id_state' => 13, 'name' => ' Arinos'],
                ['id_city' => 2867, 'id_state' => 13, 'name' => ' Aristides Batista'],
                ['id_city' => 2868, 'id_state' => 13, 'name' => ' Ascenção'],
                ['id_city' => 2869, 'id_state' => 13, 'name' => ' Assaraí'],
                ['id_city' => 2870, 'id_state' => 13, 'name' => ' Astolfo Dutra'],
                ['id_city' => 2871, 'id_state' => 13, 'name' => ' Ataléia'],
                ['id_city' => 2872, 'id_state' => 13, 'name' => ' Augusto de Lima'],
                ['id_city' => 2873, 'id_state' => 13, 'name' => ' Avaí do Jacinto'],
                ['id_city' => 2874, 'id_state' => 13, 'name' => ' Azurita'],
                ['id_city' => 2875, 'id_state' => 13, 'name' => ' Babilônia']
            ]);
        }
    }
